quarkus:
  http:
    cors: true

  log:
    level: INFO
    category: 
      io.resys:
        level: INFO

  stencil-composer:
    server-path: /q/ide-services

  stencil-composer-pg:
    service-path: /q/ide-services
    repo:
      repo-name: test-assets

  stencil-site-pg:
    service-path: /q/portal/site
    repo:
      repo-name: test-assets

  datasource:
    db-kind: postgresql 
    username: my_stencil
    password: password123
    reactive:
      max-size: 3
      url: postgresql://localhost:5433/my_stencil

"%prod":
  quarkus:

"%dev":
  quarkus:
    http:
      cors:
        origins: /.*/
        methods: GET, OPTIONS, HEAD, PUT, POST
    log:
      level: INFO
      category: 
        io.thestencil:
          level: INFO
        io.resys:
          level: INFO