// ESLint flat config for @dxs-ts/eveli-primitives
// Generated by ESLintConfigBuilder at 2025-08-09T06:15:28.911Z

export default {
 files: ["modules/eveli-primitives/**/*"],
 rules: {
  "no-restricted-imports": [
    "error",
    {
      "patterns": [
        {
          "group": [
            "@dxs-ts/eveli-demo-app",
            "@dxs-ts/eveli-demo-app/*"
          ],
          "message": "Import of '@dxs-ts/eveli-demo-app' is not allowed. Add it to dependencies in @dxs-ts/eveli-primitives/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/gamut-demo-app",
            "@dxs-ts/gamut-demo-app/*"
          ],
          "message": "Import of '@dxs-ts/gamut-demo-app' is not allowed. Add it to dependencies in @dxs-ts/eveli-primitives/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/envir-util",
            "@dxs-ts/envir-util/*"
          ],
          "message": "Import of '@dxs-ts/envir-util' is not allowed. Add it to dependencies in @dxs-ts/eveli-primitives/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/eveli-intl",
            "@dxs-ts/eveli-intl/*"
          ],
          "message": "Import of '@dxs-ts/eveli-intl' is not allowed. Add it to dependencies in @dxs-ts/eveli-primitives/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/eveli-routes",
            "@dxs-ts/eveli-routes/*"
          ],
          "message": "Import of '@dxs-ts/eveli-routes' is not allowed. Add it to dependencies in @dxs-ts/eveli-primitives/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/gamut-api",
            "@dxs-ts/gamut-api/*"
          ],
          "message": "Import of '@dxs-ts/gamut-api' is not allowed. Add it to dependencies in @dxs-ts/eveli-primitives/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/gamut-form",
            "@dxs-ts/gamut-form/*"
          ],
          "message": "Import of '@dxs-ts/gamut-form' is not allowed. Add it to dependencies in @dxs-ts/eveli-primitives/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/gamut-form-review",
            "@dxs-ts/gamut-form-review/*"
          ],
          "message": "Import of '@dxs-ts/gamut-form-review' is not allowed. Add it to dependencies in @dxs-ts/eveli-primitives/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/gamut-intl",
            "@dxs-ts/gamut-intl/*"
          ],
          "message": "Import of '@dxs-ts/gamut-intl' is not allowed. Add it to dependencies in @dxs-ts/eveli-primitives/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/gamut-md",
            "@dxs-ts/gamut-md/*"
          ],
          "message": "Import of '@dxs-ts/gamut-md' is not allowed. Add it to dependencies in @dxs-ts/eveli-primitives/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/gamut-primitives",
            "@dxs-ts/gamut-primitives/*"
          ],
          "message": "Import of '@dxs-ts/gamut-primitives' is not allowed. Add it to dependencies in @dxs-ts/eveli-primitives/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/gamut-routes",
            "@dxs-ts/gamut-routes/*"
          ],
          "message": "Import of '@dxs-ts/gamut-routes' is not allowed. Add it to dependencies in @dxs-ts/eveli-primitives/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/gamut-shell",
            "@dxs-ts/gamut-shell/*"
          ],
          "message": "Import of '@dxs-ts/gamut-shell' is not allowed. Add it to dependencies in @dxs-ts/eveli-primitives/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/gamut-theme",
            "@dxs-ts/gamut-theme/*"
          ],
          "message": "Import of '@dxs-ts/gamut-theme' is not allowed. Add it to dependencies in @dxs-ts/eveli-primitives/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/eveli-ide",
            "@dxs-ts/eveli-ide/*"
          ],
          "message": "Import of '@dxs-ts/eveli-ide' is not allowed. Add it to dependencies in @dxs-ts/eveli-primitives/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/gamut",
            "@dxs-ts/gamut/*"
          ],
          "message": "Import of '@dxs-ts/gamut' is not allowed. Add it to dependencies in @dxs-ts/eveli-primitives/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/stencil-api",
            "@dxs-ts/stencil-api/*"
          ],
          "message": "Import of '@dxs-ts/stencil-api' is not allowed. Add it to dependencies in @dxs-ts/eveli-primitives/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/stencil-routes",
            "@dxs-ts/stencil-routes/*"
          ],
          "message": "Import of '@dxs-ts/stencil-routes' is not allowed. Add it to dependencies in @dxs-ts/eveli-primitives/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/wrench-api",
            "@dxs-ts/wrench-api/*"
          ],
          "message": "Import of '@dxs-ts/wrench-api' is not allowed. Add it to dependencies in @dxs-ts/eveli-primitives/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/wrench-routes",
            "@dxs-ts/wrench-routes/*"
          ],
          "message": "Import of '@dxs-ts/wrench-routes' is not allowed. Add it to dependencies in @dxs-ts/eveli-primitives/package.json to use it."
        },
        {
          "group": [
            "@material-table/core",
            "@material-table/core/*"
          ],
          "message": "External dependency '@material-table/core' is not declared. Add it to dependencies in @dxs-ts/eveli-primitives/package.json to use it."
        },
        {
          "group": [
            "@monaco-editor/react",
            "@monaco-editor/react/*"
          ],
          "message": "External dependency '@monaco-editor/react' is not declared. Add it to dependencies in @dxs-ts/eveli-primitives/package.json to use it."
        },
        {
          "group": [
            "@mui/types",
            "@mui/types/*"
          ],
          "message": "External dependency '@mui/types' is not declared. Add it to dependencies in @dxs-ts/eveli-primitives/package.json to use it."
        },
        {
          "group": [
            "@uiw/react-md-editor",
            "@uiw/react-md-editor/*"
          ],
          "message": "External dependency '@uiw/react-md-editor' is not declared. Add it to dependencies in @dxs-ts/eveli-primitives/package.json to use it."
        },
        {
          "group": [
            "@xyflow/react",
            "@xyflow/react/*"
          ],
          "message": "External dependency '@xyflow/react' is not declared. Add it to dependencies in @dxs-ts/eveli-primitives/package.json to use it."
        },
        {
          "group": [
            "diff2html",
            "diff2html/*"
          ],
          "message": "External dependency 'diff2html' is not declared. Add it to dependencies in @dxs-ts/eveli-primitives/package.json to use it."
        },
        {
          "group": [
            "elkjs",
            "elkjs/*"
          ],
          "message": "External dependency 'elkjs' is not declared. Add it to dependencies in @dxs-ts/eveli-primitives/package.json to use it."
        },
        {
          "group": [
            "js-file-download",
            "js-file-download/*"
          ],
          "message": "External dependency 'js-file-download' is not declared. Add it to dependencies in @dxs-ts/eveli-primitives/package.json to use it."
        },
        {
          "group": [
            "leaflet",
            "leaflet/*"
          ],
          "message": "External dependency 'leaflet' is not declared. Add it to dependencies in @dxs-ts/eveli-primitives/package.json to use it."
        },
        {
          "group": [
            "leaflet-geosearch",
            "leaflet-geosearch/*"
          ],
          "message": "External dependency 'leaflet-geosearch' is not declared. Add it to dependencies in @dxs-ts/eveli-primitives/package.json to use it."
        },
        {
          "group": [
            "monaco-editor",
            "monaco-editor/*"
          ],
          "message": "External dependency 'monaco-editor' is not declared. Add it to dependencies in @dxs-ts/eveli-primitives/package.json to use it."
        },
        {
          "group": [
            "react-dom",
            "react-dom/*"
          ],
          "message": "External dependency 'react-dom' is not declared. Add it to dependencies in @dxs-ts/eveli-primitives/package.json to use it."
        },
        {
          "group": [
            "react-leaflet",
            "react-leaflet/*"
          ],
          "message": "External dependency 'react-leaflet' is not declared. Add it to dependencies in @dxs-ts/eveli-primitives/package.json to use it."
        },
        {
          "group": [
            "react-markdown",
            "react-markdown/*"
          ],
          "message": "External dependency 'react-markdown' is not declared. Add it to dependencies in @dxs-ts/eveli-primitives/package.json to use it."
        },
        {
          "group": [
            "react-time-picker",
            "react-time-picker/*"
          ],
          "message": "External dependency 'react-time-picker' is not declared. Add it to dependencies in @dxs-ts/eveli-primitives/package.json to use it."
        },
        {
          "group": [
            "recharts",
            "recharts/*"
          ],
          "message": "External dependency 'recharts' is not declared. Add it to dependencies in @dxs-ts/eveli-primitives/package.json to use it."
        },
        {
          "group": [
            "yaml",
            "yaml/*"
          ],
          "message": "External dependency 'yaml' is not declared. Add it to dependencies in @dxs-ts/eveli-primitives/package.json to use it."
        }
      ]
    }
  ]
},
 
 // Metadata (for reference)
 // Module: @dxs-ts/eveli-primitives
 // Allowed internal imports: ["@dxs-ts/eveli-api","@dxs-ts/envir-fetch"]
 // Blocked internal imports: 20 modules
 // Allowed external imports: ["ts-md5","react","react-intl","@mui/material","@mui/system","@mui/icons-material","@mui/utils","@mui/x-tree-view","@tanstack/react-router","@tanstack/react-query","@tanstack/react-table","react-date-picker","notistack","luxon","moment","numbro","file-saver"]
};
