// ESLint flat config for @dxs-ts/eveli-api
// Generated by ESLintConfigBuilder at 2025-08-09T06:15:28.911Z

export default {
 files: ["modules/eveli-api/**/*"],
 rules: {
  "no-restricted-imports": [
    "error",
    {
      "patterns": [
        {
          "group": [
            "@dxs-ts/eveli-demo-app",
            "@dxs-ts/eveli-demo-app/*"
          ],
          "message": "Import of '@dxs-ts/eveli-demo-app' is not allowed. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/gamut-demo-app",
            "@dxs-ts/gamut-demo-app/*"
          ],
          "message": "Import of '@dxs-ts/gamut-demo-app' is not allowed. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/eveli-primitives",
            "@dxs-ts/eveli-primitives/*"
          ],
          "message": "Import of '@dxs-ts/eveli-primitives' is not allowed. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/eveli-routes",
            "@dxs-ts/eveli-routes/*"
          ],
          "message": "Import of '@dxs-ts/eveli-routes' is not allowed. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/gamut-api",
            "@dxs-ts/gamut-api/*"
          ],
          "message": "Import of '@dxs-ts/gamut-api' is not allowed. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/gamut-form",
            "@dxs-ts/gamut-form/*"
          ],
          "message": "Import of '@dxs-ts/gamut-form' is not allowed. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/gamut-form-review",
            "@dxs-ts/gamut-form-review/*"
          ],
          "message": "Import of '@dxs-ts/gamut-form-review' is not allowed. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/gamut-intl",
            "@dxs-ts/gamut-intl/*"
          ],
          "message": "Import of '@dxs-ts/gamut-intl' is not allowed. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/gamut-md",
            "@dxs-ts/gamut-md/*"
          ],
          "message": "Import of '@dxs-ts/gamut-md' is not allowed. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/gamut-primitives",
            "@dxs-ts/gamut-primitives/*"
          ],
          "message": "Import of '@dxs-ts/gamut-primitives' is not allowed. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/gamut-routes",
            "@dxs-ts/gamut-routes/*"
          ],
          "message": "Import of '@dxs-ts/gamut-routes' is not allowed. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/gamut-shell",
            "@dxs-ts/gamut-shell/*"
          ],
          "message": "Import of '@dxs-ts/gamut-shell' is not allowed. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/eveli-ide",
            "@dxs-ts/eveli-ide/*"
          ],
          "message": "Import of '@dxs-ts/eveli-ide' is not allowed. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/gamut",
            "@dxs-ts/gamut/*"
          ],
          "message": "Import of '@dxs-ts/gamut' is not allowed. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/stencil-routes",
            "@dxs-ts/stencil-routes/*"
          ],
          "message": "Import of '@dxs-ts/stencil-routes' is not allowed. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/wrench-routes",
            "@dxs-ts/wrench-routes/*"
          ],
          "message": "Import of '@dxs-ts/wrench-routes' is not allowed. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "@monaco-editor/react",
            "@monaco-editor/react/*"
          ],
          "message": "External dependency '@monaco-editor/react' is not declared. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "@mui/icons-material",
            "@mui/icons-material/*"
          ],
          "message": "External dependency '@mui/icons-material' is not declared. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "@mui/system",
            "@mui/system/*"
          ],
          "message": "External dependency '@mui/system' is not declared. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "@mui/types",
            "@mui/types/*"
          ],
          "message": "External dependency '@mui/types' is not declared. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "@mui/utils",
            "@mui/utils/*"
          ],
          "message": "External dependency '@mui/utils' is not declared. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "@mui/x-tree-view",
            "@mui/x-tree-view/*"
          ],
          "message": "External dependency '@mui/x-tree-view' is not declared. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "@tanstack/react-router",
            "@tanstack/react-router/*"
          ],
          "message": "External dependency '@tanstack/react-router' is not declared. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "@tanstack/react-table",
            "@tanstack/react-table/*"
          ],
          "message": "External dependency '@tanstack/react-table' is not declared. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "@uiw/react-md-editor",
            "@uiw/react-md-editor/*"
          ],
          "message": "External dependency '@uiw/react-md-editor' is not declared. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "@xyflow/react",
            "@xyflow/react/*"
          ],
          "message": "External dependency '@xyflow/react' is not declared. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "diff2html",
            "diff2html/*"
          ],
          "message": "External dependency 'diff2html' is not declared. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "elkjs",
            "elkjs/*"
          ],
          "message": "External dependency 'elkjs' is not declared. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "file-saver",
            "file-saver/*"
          ],
          "message": "External dependency 'file-saver' is not declared. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "js-file-download",
            "js-file-download/*"
          ],
          "message": "External dependency 'js-file-download' is not declared. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "leaflet",
            "leaflet/*"
          ],
          "message": "External dependency 'leaflet' is not declared. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "leaflet-geosearch",
            "leaflet-geosearch/*"
          ],
          "message": "External dependency 'leaflet-geosearch' is not declared. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "luxon",
            "luxon/*"
          ],
          "message": "External dependency 'luxon' is not declared. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "moment",
            "moment/*"
          ],
          "message": "External dependency 'moment' is not declared. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "monaco-editor",
            "monaco-editor/*"
          ],
          "message": "External dependency 'monaco-editor' is not declared. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "numbro",
            "numbro/*"
          ],
          "message": "External dependency 'numbro' is not declared. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "react-date-picker",
            "react-date-picker/*"
          ],
          "message": "External dependency 'react-date-picker' is not declared. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "react-dom",
            "react-dom/*"
          ],
          "message": "External dependency 'react-dom' is not declared. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "react-leaflet",
            "react-leaflet/*"
          ],
          "message": "External dependency 'react-leaflet' is not declared. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "react-markdown",
            "react-markdown/*"
          ],
          "message": "External dependency 'react-markdown' is not declared. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "react-time-picker",
            "react-time-picker/*"
          ],
          "message": "External dependency 'react-time-picker' is not declared. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "recharts",
            "recharts/*"
          ],
          "message": "External dependency 'recharts' is not declared. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "ts-md5",
            "ts-md5/*"
          ],
          "message": "External dependency 'ts-md5' is not declared. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        },
        {
          "group": [
            "yaml",
            "yaml/*"
          ],
          "message": "External dependency 'yaml' is not declared. Add it to dependencies in @dxs-ts/eveli-api/package.json to use it."
        }
      ]
    }
  ]
},
 
 // Metadata (for reference)
 // Module: @dxs-ts/eveli-api
 // Allowed internal imports: ["@dxs-ts/envir-fetch","@dxs-ts/envir-util","@dxs-ts/wrench-api","@dxs-ts/stencil-api","@dxs-ts/eveli-intl","@dxs-ts/gamut-theme"]
 // Blocked internal imports: 16 modules
 // Allowed external imports: ["react","@tanstack/react-query","@mui/material","notistack","react-intl","@material-table/core"]
};
