// ESLint flat config for @dxs-ts/gamut-api
// Generated by ESLintConfigBuilder at 2025-08-01T09:27:04.559Z

export default {
 files: ["modules/gamut-api/**/*"],
 rules: {
  "no-restricted-imports": [
    "error",
    {
      "patterns": [
        {
          "group": [
            "@dxs-ts/gamut-demo-app",
            "@dxs-ts/gamut-demo-app/*"
          ],
          "message": "Import of '@dxs-ts/gamut-demo-app' is not allowed. Add it to dependencies in @dxs-ts/gamut-api/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/envir-util",
            "@dxs-ts/envir-util/*"
          ],
          "message": "Import of '@dxs-ts/envir-util' is not allowed. Add it to dependencies in @dxs-ts/gamut-api/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/gamut-primitives",
            "@dxs-ts/gamut-primitives/*"
          ],
          "message": "Import of '@dxs-ts/gamut-primitives' is not allowed. Add it to dependencies in @dxs-ts/gamut-api/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/gamut-routes",
            "@dxs-ts/gamut-routes/*"
          ],
          "message": "Import of '@dxs-ts/gamut-routes' is not allowed. Add it to dependencies in @dxs-ts/gamut-api/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/gamut",
            "@dxs-ts/gamut/*"
          ],
          "message": "Import of '@dxs-ts/gamut' is not allowed. Add it to dependencies in @dxs-ts/gamut-api/package.json to use it."
        },
        {
          "group": [
            "@mui/icons-material",
            "@mui/icons-material/*"
          ],
          "message": "External dependency '@mui/icons-material' is not declared. Add it to dependencies in @dxs-ts/gamut-api/package.json to use it."
        },
        {
          "group": [
            "@mui/material",
            "@mui/material/*"
          ],
          "message": "External dependency '@mui/material' is not declared. Add it to dependencies in @dxs-ts/gamut-api/package.json to use it."
        },
        {
          "group": [
            "@mui/system",
            "@mui/system/*"
          ],
          "message": "External dependency '@mui/system' is not declared. Add it to dependencies in @dxs-ts/gamut-api/package.json to use it."
        },
        {
          "group": [
            "@mui/types",
            "@mui/types/*"
          ],
          "message": "External dependency '@mui/types' is not declared. Add it to dependencies in @dxs-ts/gamut-api/package.json to use it."
        },
        {
          "group": [
            "@mui/utils",
            "@mui/utils/*"
          ],
          "message": "External dependency '@mui/utils' is not declared. Add it to dependencies in @dxs-ts/gamut-api/package.json to use it."
        },
        {
          "group": [
            "leaflet",
            "leaflet/*"
          ],
          "message": "External dependency 'leaflet' is not declared. Add it to dependencies in @dxs-ts/gamut-api/package.json to use it."
        },
        {
          "group": [
            "numbro",
            "numbro/*"
          ],
          "message": "External dependency 'numbro' is not declared. Add it to dependencies in @dxs-ts/gamut-api/package.json to use it."
        },
        {
          "group": [
            "react-date-picker",
            "react-date-picker/*"
          ],
          "message": "External dependency 'react-date-picker' is not declared. Add it to dependencies in @dxs-ts/gamut-api/package.json to use it."
        },
        {
          "group": [
            "react-leaflet",
            "react-leaflet/*"
          ],
          "message": "External dependency 'react-leaflet' is not declared. Add it to dependencies in @dxs-ts/gamut-api/package.json to use it."
        },
        {
          "group": [
            "react-markdown",
            "react-markdown/*"
          ],
          "message": "External dependency 'react-markdown' is not declared. Add it to dependencies in @dxs-ts/gamut-api/package.json to use it."
        },
        {
          "group": [
            "react-router-dom",
            "react-router-dom/*"
          ],
          "message": "External dependency 'react-router-dom' is not declared. Add it to dependencies in @dxs-ts/gamut-api/package.json to use it."
        },
        {
          "group": [
            "react-time-picker",
            "react-time-picker/*"
          ],
          "message": "External dependency 'react-time-picker' is not declared. Add it to dependencies in @dxs-ts/gamut-api/package.json to use it."
        }
      ]
    }
  ]
},
 
 // Metadata (for reference)
 // Module: @dxs-ts/gamut-api
 // Allowed internal imports: ["@dxs-ts/gamut-intl"]
 // Blocked internal imports: 5 modules
 // Allowed external imports: ["react","react-dom","react-intl","@tanstack/react-query","@tanstack/react-router","luxon","leaflet-geosearch","ts-md5"]
};
