// ESLint flat config for @dxs-ts/gamut-primitives
// Generated by ESLintConfigBuilder at 2025-08-09T06:15:28.912Z

export default {
 files: ["modules/gamut-primitives/**/*"],
 rules: {
  "no-restricted-imports": [
    "error",
    {
      "patterns": [
        {
          "group": [
            "@dxs-ts/eveli-demo-app",
            "@dxs-ts/eveli-demo-app/*"
          ],
          "message": "Import of '@dxs-ts/eveli-demo-app' is not allowed. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/gamut-demo-app",
            "@dxs-ts/gamut-demo-app/*"
          ],
          "message": "Import of '@dxs-ts/gamut-demo-app' is not allowed. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/envir-fetch",
            "@dxs-ts/envir-fetch/*"
          ],
          "message": "Import of '@dxs-ts/envir-fetch' is not allowed. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/envir-util",
            "@dxs-ts/envir-util/*"
          ],
          "message": "Import of '@dxs-ts/envir-util' is not allowed. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/eveli-api",
            "@dxs-ts/eveli-api/*"
          ],
          "message": "Import of '@dxs-ts/eveli-api' is not allowed. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/eveli-intl",
            "@dxs-ts/eveli-intl/*"
          ],
          "message": "Import of '@dxs-ts/eveli-intl' is not allowed. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/eveli-primitives",
            "@dxs-ts/eveli-primitives/*"
          ],
          "message": "Import of '@dxs-ts/eveli-primitives' is not allowed. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/eveli-routes",
            "@dxs-ts/eveli-routes/*"
          ],
          "message": "Import of '@dxs-ts/eveli-routes' is not allowed. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/gamut-form",
            "@dxs-ts/gamut-form/*"
          ],
          "message": "Import of '@dxs-ts/gamut-form' is not allowed. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/gamut-intl",
            "@dxs-ts/gamut-intl/*"
          ],
          "message": "Import of '@dxs-ts/gamut-intl' is not allowed. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/gamut-routes",
            "@dxs-ts/gamut-routes/*"
          ],
          "message": "Import of '@dxs-ts/gamut-routes' is not allowed. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/gamut-theme",
            "@dxs-ts/gamut-theme/*"
          ],
          "message": "Import of '@dxs-ts/gamut-theme' is not allowed. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/eveli-ide",
            "@dxs-ts/eveli-ide/*"
          ],
          "message": "Import of '@dxs-ts/eveli-ide' is not allowed. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/gamut",
            "@dxs-ts/gamut/*"
          ],
          "message": "Import of '@dxs-ts/gamut' is not allowed. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/stencil-api",
            "@dxs-ts/stencil-api/*"
          ],
          "message": "Import of '@dxs-ts/stencil-api' is not allowed. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/stencil-routes",
            "@dxs-ts/stencil-routes/*"
          ],
          "message": "Import of '@dxs-ts/stencil-routes' is not allowed. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/wrench-api",
            "@dxs-ts/wrench-api/*"
          ],
          "message": "Import of '@dxs-ts/wrench-api' is not allowed. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/wrench-routes",
            "@dxs-ts/wrench-routes/*"
          ],
          "message": "Import of '@dxs-ts/wrench-routes' is not allowed. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "@material-table/core",
            "@material-table/core/*"
          ],
          "message": "External dependency '@material-table/core' is not declared. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "@monaco-editor/react",
            "@monaco-editor/react/*"
          ],
          "message": "External dependency '@monaco-editor/react' is not declared. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "@mui/x-tree-view",
            "@mui/x-tree-view/*"
          ],
          "message": "External dependency '@mui/x-tree-view' is not declared. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "@tanstack/react-query",
            "@tanstack/react-query/*"
          ],
          "message": "External dependency '@tanstack/react-query' is not declared. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "@tanstack/react-table",
            "@tanstack/react-table/*"
          ],
          "message": "External dependency '@tanstack/react-table' is not declared. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "@uiw/react-md-editor",
            "@uiw/react-md-editor/*"
          ],
          "message": "External dependency '@uiw/react-md-editor' is not declared. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "@xyflow/react",
            "@xyflow/react/*"
          ],
          "message": "External dependency '@xyflow/react' is not declared. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "diff2html",
            "diff2html/*"
          ],
          "message": "External dependency 'diff2html' is not declared. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "elkjs",
            "elkjs/*"
          ],
          "message": "External dependency 'elkjs' is not declared. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "file-saver",
            "file-saver/*"
          ],
          "message": "External dependency 'file-saver' is not declared. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "js-file-download",
            "js-file-download/*"
          ],
          "message": "External dependency 'js-file-download' is not declared. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "leaflet-geosearch",
            "leaflet-geosearch/*"
          ],
          "message": "External dependency 'leaflet-geosearch' is not declared. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "moment",
            "moment/*"
          ],
          "message": "External dependency 'moment' is not declared. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "monaco-editor",
            "monaco-editor/*"
          ],
          "message": "External dependency 'monaco-editor' is not declared. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "notistack",
            "notistack/*"
          ],
          "message": "External dependency 'notistack' is not declared. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "recharts",
            "recharts/*"
          ],
          "message": "External dependency 'recharts' is not declared. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "ts-md5",
            "ts-md5/*"
          ],
          "message": "External dependency 'ts-md5' is not declared. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "yaml",
            "yaml/*"
          ],
          "message": "External dependency 'yaml' is not declared. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        }
      ]
    }
  ]
},
 
 // Metadata (for reference)
 // Module: @dxs-ts/gamut-primitives
 // Allowed internal imports: ["@dxs-ts/gamut-api","@dxs-ts/gamut-md","@dxs-ts/gamut-shell","@dxs-ts/gamut-form-review"]
 // Blocked internal imports: 18 modules
 // Allowed external imports: ["react","react-dom","react-intl","react-markdown","react-leaflet","react-date-picker","react-time-picker","@mui/material","@mui/system","@mui/icons-material","@mui/utils","@mui/types","@tanstack/react-router","luxon","numbro","leaflet"]
};
