// ESLint flat config for @dxs-ts/gamut-routes
// Generated by ESLintConfigBuilder at 2025-08-01T09:27:04.559Z

export default {
 files: ["modules/gamut-routes/**/*"],
 rules: {
  "no-restricted-imports": [
    "error",
    {
      "patterns": [
        {
          "group": [
            "@dxs-ts/gamut-demo-app",
            "@dxs-ts/gamut-demo-app/*"
          ],
          "message": "Import of '@dxs-ts/gamut-demo-app' is not allowed. Add it to dependencies in @dxs-ts/gamut-routes/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/envir-util",
            "@dxs-ts/envir-util/*"
          ],
          "message": "Import of '@dxs-ts/envir-util' is not allowed. Add it to dependencies in @dxs-ts/gamut-routes/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/gamut-intl",
            "@dxs-ts/gamut-intl/*"
          ],
          "message": "Import of '@dxs-ts/gamut-intl' is not allowed. Add it to dependencies in @dxs-ts/gamut-routes/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/gamut",
            "@dxs-ts/gamut/*"
          ],
          "message": "Import of '@dxs-ts/gamut' is not allowed. Add it to dependencies in @dxs-ts/gamut-routes/package.json to use it."
        },
        {
          "group": [
            "@mui/types",
            "@mui/types/*"
          ],
          "message": "External dependency '@mui/types' is not declared. Add it to dependencies in @dxs-ts/gamut-routes/package.json to use it."
        },
        {
          "group": [
            "@tanstack/react-query",
            "@tanstack/react-query/*"
          ],
          "message": "External dependency '@tanstack/react-query' is not declared. Add it to dependencies in @dxs-ts/gamut-routes/package.json to use it."
        },
        {
          "group": [
            "leaflet",
            "leaflet/*"
          ],
          "message": "External dependency 'leaflet' is not declared. Add it to dependencies in @dxs-ts/gamut-routes/package.json to use it."
        },
        {
          "group": [
            "leaflet-geosearch",
            "leaflet-geosearch/*"
          ],
          "message": "External dependency 'leaflet-geosearch' is not declared. Add it to dependencies in @dxs-ts/gamut-routes/package.json to use it."
        },
        {
          "group": [
            "luxon",
            "luxon/*"
          ],
          "message": "External dependency 'luxon' is not declared. Add it to dependencies in @dxs-ts/gamut-routes/package.json to use it."
        },
        {
          "group": [
            "numbro",
            "numbro/*"
          ],
          "message": "External dependency 'numbro' is not declared. Add it to dependencies in @dxs-ts/gamut-routes/package.json to use it."
        },
        {
          "group": [
            "react-date-picker",
            "react-date-picker/*"
          ],
          "message": "External dependency 'react-date-picker' is not declared. Add it to dependencies in @dxs-ts/gamut-routes/package.json to use it."
        },
        {
          "group": [
            "react-leaflet",
            "react-leaflet/*"
          ],
          "message": "External dependency 'react-leaflet' is not declared. Add it to dependencies in @dxs-ts/gamut-routes/package.json to use it."
        },
        {
          "group": [
            "react-markdown",
            "react-markdown/*"
          ],
          "message": "External dependency 'react-markdown' is not declared. Add it to dependencies in @dxs-ts/gamut-routes/package.json to use it."
        },
        {
          "group": [
            "react-time-picker",
            "react-time-picker/*"
          ],
          "message": "External dependency 'react-time-picker' is not declared. Add it to dependencies in @dxs-ts/gamut-routes/package.json to use it."
        },
        {
          "group": [
            "ts-md5",
            "ts-md5/*"
          ],
          "message": "External dependency 'ts-md5' is not declared. Add it to dependencies in @dxs-ts/gamut-routes/package.json to use it."
        }
      ]
    }
  ]
},
 
 // Metadata (for reference)
 // Module: @dxs-ts/gamut-routes
 // Allowed internal imports: ["@dxs-ts/gamut-api","@dxs-ts/gamut-primitives"]
 // Blocked internal imports: 4 modules
 // Allowed external imports: ["react","react-dom","react-router-dom","@tanstack/react-router","@mui/material","@mui/icons-material","@mui/utils","@mui/system","react-intl"]
};
