// ESLint flat config for @dxs-ts/gamut-primitives
// Generated by ESLintConfigBuilder at 2025-08-01T09:27:04.559Z

export default {
 files: ["modules/gamut-primitives/**/*"],
 rules: {
  "no-restricted-imports": [
    "error",
    {
      "patterns": [
        {
          "group": [
            "@dxs-ts/gamut-demo-app",
            "@dxs-ts/gamut-demo-app/*"
          ],
          "message": "Import of '@dxs-ts/gamut-demo-app' is not allowed. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/envir-util",
            "@dxs-ts/envir-util/*"
          ],
          "message": "Import of '@dxs-ts/envir-util' is not allowed. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/gamut-intl",
            "@dxs-ts/gamut-intl/*"
          ],
          "message": "Import of '@dxs-ts/gamut-intl' is not allowed. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/gamut-routes",
            "@dxs-ts/gamut-routes/*"
          ],
          "message": "Import of '@dxs-ts/gamut-routes' is not allowed. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "@dxs-ts/gamut",
            "@dxs-ts/gamut/*"
          ],
          "message": "Import of '@dxs-ts/gamut' is not allowed. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "@tanstack/react-query",
            "@tanstack/react-query/*"
          ],
          "message": "External dependency '@tanstack/react-query' is not declared. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "leaflet-geosearch",
            "leaflet-geosearch/*"
          ],
          "message": "External dependency 'leaflet-geosearch' is not declared. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "react-router-dom",
            "react-router-dom/*"
          ],
          "message": "External dependency 'react-router-dom' is not declared. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        },
        {
          "group": [
            "ts-md5",
            "ts-md5/*"
          ],
          "message": "External dependency 'ts-md5' is not declared. Add it to dependencies in @dxs-ts/gamut-primitives/package.json to use it."
        }
      ]
    }
  ]
},
 
 // Metadata (for reference)
 // Module: @dxs-ts/gamut-primitives
 // Allowed internal imports: ["@dxs-ts/gamut-api"]
 // Blocked internal imports: 5 modules
 // Allowed external imports: ["react","react-dom","react-intl","react-markdown","react-leaflet","react-date-picker","react-time-picker","@mui/material","@mui/system","@mui/icons-material","@mui/utils","@mui/types","@tanstack/react-router","luxon","numbro","leaflet"]
};
