// ESLint flat config for all modules
// Generated by ESLintConfigBuilder at 2025-08-09T06:15:28.913Z

import eveliDemoAppConfig from './eveli-demo-app.config.js';
import gamutDemoAppConfig from './gamut-demo-app.config.js';
import envirFetchConfig from './envir-fetch.config.js';
import envirUtilConfig from './envir-util.config.js';
import eveliApiConfig from './eveli-api.config.js';
import eveliIntlConfig from './eveli-intl.config.js';
import eveliPrimitivesConfig from './eveli-primitives.config.js';
import eveliRoutesConfig from './eveli-routes.config.js';
import gamutApiConfig from './gamut-api.config.js';
import gamutFormConfig from './gamut-form.config.js';
import gamutFormReviewConfig from './gamut-form-review.config.js';
import gamutIntlConfig from './gamut-intl.config.js';
import gamutMdConfig from './gamut-md.config.js';
import gamutPrimitivesConfig from './gamut-primitives.config.js';
import gamutRoutesConfig from './gamut-routes.config.js';
import gamutShellConfig from './gamut-shell.config.js';
import gamutThemeConfig from './gamut-theme.config.js';
import eveliIdeConfig from './eveli-ide.config.js';
import gamutConfig from './gamut.config.js';
import stencilApiConfig from './stencil-api.config.js';
import stencilRoutesConfig from './stencil-routes.config.js';
import wrenchApiConfig from './wrench-api.config.js';
import wrenchRoutesConfig from './wrench-routes.config.js';

export default [
  eveliDemoAppConfig,
  gamutDemoAppConfig,
  envirFetchConfig,
  envirUtilConfig,
  eveliApiConfig,
  eveliIntlConfig,
  eveliPrimitivesConfig,
  eveliRoutesConfig,
  gamutApiConfig,
  gamutFormConfig,
  gamutFormReviewConfig,
  gamutIntlConfig,
  gamutMdConfig,
  gamutPrimitivesConfig,
  gamutRoutesConfig,
  gamutShellConfig,
  gamutThemeConfig,
  eveliIdeConfig,
  gamutConfig,
  stencilApiConfig,
  stencilRoutesConfig,
  wrenchApiConfig,
  wrenchRoutesConfig,
];

// Usage: Add this to your eslint.config.js
// import moduleConfigs from './.modules/eslint/modules.config.js';
// export default [...moduleConfigs, ...yourOtherConfigs];
