// ESLint flat config for all modules
// Generated by ESLintConfigBuilder at 2025-08-01T09:27:04.559Z

import gamutDemoAppConfig from './gamut-demo-app.config.js';
import envirUtilConfig from './envir-util.config.js';
import gamutApiConfig from './gamut-api.config.js';
import gamutIntlConfig from './gamut-intl.config.js';
import gamutPrimitivesConfig from './gamut-primitives.config.js';
import gamutRoutesConfig from './gamut-routes.config.js';
import gamutConfig from './gamut.config.js';

export default [
  gamutDemoAppConfig,
  envirUtilConfig,
  gamutApiConfig,
  gamutIntlConfig,
  gamutPrimitivesConfig,
  gamutRoutesConfig,
  gamutConfig,
];

// Usage: Add this to your eslint.config.js
// import moduleConfigs from './.modules/eslint/modules.config.js';
// export default [...moduleConfigs, ...yourOtherConfigs];
