import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { resolve, join } from 'node:path';

import { ESLintModuleConfig, ESLintConfigGeneratorOptions } from './gen-eslint-types'


export declare namespace Command_WriteConfigFiles {
  export interface Input {
    rootPath: string;
    moduleConfigs: ESLintModuleConfig[];
    options: Required<ESLintConfigGeneratorOptions>;
  }

  export interface Result {
    // void - writes files to disk
  }
}

export class Command_WriteConfigFiles {
  execute(input: Command_WriteConfigFiles.Input): Command_WriteConfigFiles.Result {
    const { rootPath, moduleConfigs, options } = input;

    const outputPath = resolve(rootPath, options.outputDir);

    // Ensure output directory exists
    if (!existsSync(outputPath)) {
      mkdirSync(outputPath, { recursive: true });
    }

    _writeFlatConfigs(outputPath, moduleConfigs);

    return {};
  }
}

// Pure transformative functions
function _writeFlatConfigs(outputPath: string, moduleConfigs: ESLintModuleConfig[]): void {
  // Write individual module configs (flat format)
  for (const config of moduleConfigs) {
    const fileName = _getFlatConfigFileName(config.moduleName);
    const filePath = join(outputPath, fileName);

    const flatConfig = _generateFlatConfig(config);

    writeFileSync(filePath, flatConfig, 'utf-8');
    console.log(`     📄 Created ${fileName}`);
  }

  // Write master flat configuration
  _writeMasterFlatConfig(outputPath, moduleConfigs);
}

function _generateFlatConfig(config: ESLintModuleConfig): string {
  const moduleFolderName = _getModuleFolderName(config.moduleName);

  return `// ESLint flat config for ${config.moduleName}
// Generated by ESLintConfigBuilder at ${new Date().toISOString()}

export default {
 files: ["modules/${moduleFolderName}/**/*"],
 rules: ${JSON.stringify(config.generatedRules, null, 2)},
 
 // Metadata (for reference)
 // Module: ${config.moduleName}
 // Allowed internal imports: ${JSON.stringify(config.allowedInternalImports)}
 // Blocked internal imports: ${config.blockedInternalImports.length} modules
 // Allowed external imports: ${JSON.stringify(config.allowedExternalImports)}
};
`;
}

function _writeMasterFlatConfig(outputPath: string, moduleConfigs: ESLintModuleConfig[]): void {
  const masterConfig = `// ESLint flat config for all modules
// Generated by ESLintConfigBuilder at ${new Date().toISOString()}

${moduleConfigs.map(config => {
    const fileName = _getFlatConfigFileName(config.moduleName);
    const importName = _getImportName(config.moduleName);
    return `import ${importName} from './${fileName}';`;
  }).join('\n')}

export default [
${moduleConfigs.map(config => {
    const importName = _getImportName(config.moduleName);
    return `  ${importName},`;
  }).join('\n')}
];

// Usage: Add this to your eslint.config.js
// import moduleConfigs from './.modules/eslint/modules.config.js';
// export default [...moduleConfigs, ...yourOtherConfigs];
`;

  const masterPath = join(outputPath, 'modules.config.js');
  writeFileSync(masterPath, masterConfig, 'utf-8');
  console.log(`     📄 Created master flat config: modules.config.js`);
}

function _getFlatConfigFileName(moduleName: string): string {
  // Convert @dxs-ts/gamut-api -> gamut-api.config.js
  return `${moduleName.replace('@dxs-ts/', '')}.config.js`;
}

function _getImportName(moduleName: string): string {
  // Convert @dxs-ts/gamut-api -> gamutApiConfig
  return moduleName
    .replace('@dxs-ts/', '')
    .split('-')
    .map((word, index) => index === 0 ? word : word.charAt(0).toUpperCase() + word.slice(1))
    .join('') + 'Config';
}

function _getModuleFolderName(moduleName: string): string {
  // Convert @dxs-ts/gamut-api -> gamut-api (assuming folder structure)
  return moduleName.replace('@dxs-ts/', '');
}