export const en = {
  'document.title': 'DigiExpress',
  'eveli.textSeparatorColon': ':',
  'eveli.textSeparator': '/',
  'eveli.noValueIndicator': '--',
  'eveli.permissions.none.title': 'Oops!',
  'eveli.permissions.none.desc1': 'You don\'t have the correct access rights to use this application.',
  'eveli.permissions.none.desc2': 'Please contact your system administrator.',
  'tasksView.title': 'Tasks',
  'taskDialog.priority': 'Priority',
  'taskDialog.subject': 'Subject',
  'taskDialog.dueDate': 'Due date',
  'taskDialog.assignedTo': 'User role',
  'taskDialog.assignedUser': 'User',
  'taskDialog.status': 'Status',
  'taskDialog.task': 'Task',
  'taskDialog.category': 'Type',
  'taskDialog.source': 'Source',
  'taskDialog.additionalInfo': 'Additional information',
  'task.assignable.dialog.title': 'Manage assigned forms',
  'task.assignable.new': 'Assign new forms',
  'task.assignable.desc': 'Will be assigned the selected forms in the chosen language.',
  'task.assignable.locale': 'Language',
  'task.assignable.forms': 'Forms',
  'task.assignable.cancel': 'Cancel assigned forms',
  'task.assignable.cancel.desc': 'Assigned forms cannot be cancelled after the customer has completed them!',
  'task.assignable.selectForms': 'Select forms',
  'task.assignable.cancel.formsList.desc': 'The following form(s) will be cancelled!',
  'button.cancelSelected': 'Cancel selected forms ({count})',
  'button.acceptSelected': 'Assigned selected forms ({count})',
  'task.priority.low': 'Low',
  'task.priority.normal': 'Normal',
  'task.priority.high': 'High',
  'task.dueDate': 'Due date',
  'task.customerMessages': 'Customer messages',
  'task.customerMessages.messageHistory': 'Message history',
  'task.customerMessages.none': 'No messages',
  'task.customerMessages.newMessageTitle': 'Write a new message to the customer',
  'task.customerMessages.newMessagePlaceholder': 'My message to customer',
  'button.sendMessage': 'Send message',
  'task.edit': 'Edit task',
  'task.customerName': 'Customer name',
  'task.subject': 'Subject',
  'task.additionalInfo': 'Additional info',
  'task.ai.assistant.loading': 'Loading AI assistant...',
  'task.metaData': 'Metadata',
  'task.status': 'Status',
  'task.priority': 'Priority',
  'task.status.new': 'New',
  'task.status.open': 'Open',
  'task.status.completed': 'Completed',
  'task.status.rejected': 'No processing',
  'task.status.transferred': 'Transferred',
  'task.status.delegated': 'Delegated',
  'task.status.waiting': 'Waiting',
  'task.pdf.options.select.CUSTOMER_NAME': 'Customer name',
  'task.pdf.options.select.CUSTOMER_SSN': 'Customer SSN',
  'task.pdf.options.select.EXTERNAL_COMMENTS': 'Customer messages',
  'task.pdf.options.select': 'PDF Printing options',
  'task.pdf.print': 'Print PDF',
  'task.pdf.options.select.desc': 'Select addition data tobe included to generated pdf document',
  'task.form.review': 'View form',
  'task.created': 'Created',
  'task.updated': 'Updated',
  'task.comments.external.createTask': 'Create task before adding external comments',
  'task.comments.internal.createTask': 'Create task before adding internal comments',
  'task.attachments.createTask': 'Create task before uploading attachments',
  'task.comments.external.added': 'Internal comment added',
  'task.feedback.publishedSaved': 'Feedback changes saved',
  'task.transfer.published': 'Document transfer',
  'task.transfer.create.title': 'Document transfer',
  'task.transfer.create.journalNumber': 'Journal number',
  'task.transfer.create.files': 'Transferred documents',
  'task.transfer.button.transfer': 'Transfer documents',
  'task.transfer.button.retransfer': 'Retransfer documents',
  'task.transfer.create.docTitle': 'Document title',
  'task.transfer.create.docTitle.placeholder': 'Enter document title',
  'task.transfer.create.error': 'Transfer creation error',
  'task.transfer.props.title': 'Transfer properties',
  'task.assigneesAndRolesEdit': 'Edit assignees and roles',
  'task.assigneesAndRolesEdit.assignee.select': 'Select assignee',
  'task.assignee': 'Assignee',
  'task.assignedRoles': 'Roles',
  'internalComments': 'Internal comments',
  'externalComments': 'Client messages',
  'comment.store': 'Save',
  'comment.add': 'Add comment',
  'comment.addInternal': 'Add internal comment',
  'comment.addExternal': 'Message to client',
  'taskButton.refresh': 'Check for new tasks',
  'taskButton.accept': 'Accept',
  'taskButton.cancel': 'Close',
  'taskReopenDialog.title': 'Reopen Task',
  'taskReopenDialog.subtitle1': 'You are about to reopen this task',
  'taskReopenDialog.subtitle2': 'Upon accepting changes, task status will be set to OPEN and message will be sent to customer',
  'taskReopenDialog.customer-message': 'Please write a message to send to the customer explaining this change',
  'taskReopenDialog.customer-message-label-placeholder1': 'Message to customer',
  'taskReopenDialog.customer-message-label-placeholder2': 'Enter message',
  'button.taskReopenDialog': 'Reopen task',
  'table.body.emptyDataSourceMessage': 'No data',
  'table.body.filterRow.filterTooltip': 'Filter',
  'table.body.deleteTooltip': 'Delete',
  'table.header.actions': 'Actions',
  'table.pagination.labelDisplayedRows': '{from}-{to} of {count}',
  'table.pagination.labelRowsPerPage': 'Rows per page:',
  'table.pagination.firstPage': 'First page',
  'table.pagination.previousPage': 'Previous page',
  'table.pagination.nextPage': 'Next page',
  'table.pagination.lastPage': 'Last page',
  'table.toolbar.search': 'Search',
  'table.toolbar.showColumnsTitle': 'Show columns',
  'table.toolbar.addRemoveColumns': 'Add or remove columns',
  'taskLink.pdf.open': 'PDF',
  'explorer.login': 'Log in',
  'login.dialog.title': 'Use DigiExpress services',
  'login.dialog.message': 'Please login to proceed',
  'locale.fi': 'Suomi',
  'locale.sv': 'Svenska',
  'locale.en': 'English',
  'main.articles.all': 'All Articles',
  'main.links.all': 'All Links',
  'main.services.all': 'All Services',
  'main.flows.all': 'All Service Flows',
  'main.debug': 'Debug',
  'main.decisions.all': 'All Decisions Tables',
  'menu.dashboard': 'Dashboard',
  'menu.profile': 'Profile',
  'menu.tasks': 'Tasks',
  'menu.forms': 'Dialob',
  'menu.queues': 'Queues',
  'menu.help': 'Help',
  'menu.processes': 'Monitoring',
  'menu.logout': 'Log out',
  'menu.publications': 'Publications',
  'menu.services': 'Services',
  'menu.feedback': 'Feedback',
  'menu.compose': 'Compose',
  'menu.articles': 'Articles',
  'menu.links': 'Links',
  'menu.locales': 'Languages',
  'menu.templates': 'Templates',
  'menu.flows': 'Service Flows',
  'menu.decisions': 'Decision tables',
  'menu.debug': 'Debug',
  'menu.releases': 'Releases',
  'menu.compare': 'Compare',
  'menu.compose.wrench': 'Compose',
  'menu.flows.wrench': 'Service Flows',
  'menu.decisions.wrench': 'Decision tables',
  'menu.services.wrench': 'Services',
  'menu.services.tagomi': 'Services',
  'menu.images.tagomi': 'Images',
  'menu.scripts.tagomi': 'Scripts',
  'menu.debug.wrench': 'Debug',
  'menu.compare.wrench': 'Compare',
  'menu.releases.wrench': 'Releases',
  'profile.user.name': 'Name:',
  'profile.user.email': 'e-mail:',
  'profile.user.role': 'Role:',
  'button.cancel': 'Cancel',
  'button.archive': 'Archive',
  'button.confirmDelete': 'Delete',
  'button.delete.feedback': 'Delete this feedback',
  'button.delete.template': 'Delete this template',
  'button.delete.link': 'Delete this link',
  'button.delete.article': 'Delete this article',
  'button.delete.page': 'Delete this page',
  'button.update': 'Update',
  'button.publish': 'Publish',
  'button.accept': 'Accept',
  'button.close': 'Close',
  'button.republish': 'Republish',
  'button.save': 'Save',
  'button.dismiss': 'Dismiss',
  'button.select': 'Select',
  'button.startBatch': 'Start batch',
  'error.minTextLength': 'Value should be at least {minLength} characters long',
  'error.maxTextLength': 'Value should be no more than {max} characters long',
  'error.valueRequired': '* Value required',
  'error.title': 'Error!',
  'error.dialob.session': 'Questionnaire cannot be opened at this moment, please try again later',
  'error.errorLoadingData': 'Error during data loading',
  'error.unauthorized.title': 'Missing access role',
  'error.unauthorized.text': 'Contact your system administrator to check your role',
  'error.unauthorizedAccess': 'Missing access role',
  'error.dataAccess': 'Error during data loading',
  'error.statusOpenError': 'Required when status is open',
  'error.workflowCreation': 'Error on workflow creation, check worflow name for duplicates',
  'error.invalidFormName': 'Invalid form name',
  'table.body.editRow.deleteMessage': 'Are you sure you want to delete this?',
  'workflowTable.title': 'Stencil Services',
  'workflowTableHeader.name': 'Name',
  'workflowTableHeader.formName': 'Form',
  'workflowTableHeader.flowName': 'Flow',
  'workflowTableHeader.updated': 'Updated',
  'workflowTable.editButton': 'Edit workflow',
  'workflow.dialogTitle': 'Stencil service',
  'workflow.name': 'Name',
  'workflow.form.formName': 'Form name',
  'workflow.form.formTag': 'Form tag',
  'workflow.flowName': 'Flow name',
  'processTable.title': 'Stencil service execution history',
  'processTableHeader.workflow': 'Stencil service name',
  'processTableHeader.status': 'Status',
  'processTableHeader.created': 'Created',
  'processTableHeader.questionnaireId': 'Questionnaire',
  'processTableHeader.taskRef': 'Task reference',
  'process.status.ANSWERED': 'Answered',
  'process.status.CREATED': 'Created',
  'process.status.ANSWERING': 'Answering',
  'process.status.IN_PROGRESS': 'In progress',
  'process.status.WAITING': 'Waiting',
  'process.status.COMPLETED': 'Completed',
  'process.status.REJECTED': 'Rejected',
  'spoTasksTableHeader.taskName': 'Name',
  'spoTasksTableHeader.status': 'Status',
  'spoTasksTableHeader.priority': 'Priority',
  'spoTasksTableHeader.dueDate': 'Due',
  'spoTasksTableHeader.assigned': 'Role',
  'spoTasksTableHeader.assignedUser': 'Handler',
  'spoTasksTableHeader.created': 'Created',
  'spoTasksTableHeader.clientName': 'Client',
  'spoTasksTableHeader.additionalInfo': 'Info',
  'taskDialog.clientIdentificator': 'Client name',
  'Manual': 'Manual',
  'Protected': 'Protected',
  'Normal': 'Normal',
  'CustomerCreated': 'Customer created',
  'Internal': 'Internal',
  'task.role.assignedAllUsers': 'All users',
  'task.roles.none': 'No roles',
  'task.assignees.none': 'No assignees',
  'confirm.close.title': 'Confirmation required',
  'confirm.unsavedChanges': 'Unsaved changes will be lost, do you want to continue?',
  'task.statistics.statusCount': 'By status',
  'task.statistics.priorityCount': 'By priority',
  'task.statistics.daily': 'Daily',
  'task.statistics.overdue': 'Overdue',
  'task.statistics.new_task_by_role': 'New task per user role',
  'task.statistics.task_by_questionnaire': 'Task per form name',
  'task.statistics.open_task_by_role': 'Open tasks per user role',
  'feedback.create.title': 'Create public reply to customer feedback',
  'feedback.update.title': 'Edit public reply to customer feedback',
  'feedback.taskReferenceId': 'Task Reference ID',
  'feedback.taskReferenceId.short': 'Task Ref',
  'feedback.mainCategory': 'Subject',
  'feedback.feedbackValue': 'Customer feedback',
  'feedback.feedbackValue.placeholder': 'Customer feedback content',
  'feedback.customerTitle': 'Feedback title',
  'feedback.myReply': 'Reply to customer',
  'feedback.myReply.placeholder': 'My reply to the customer',
  'feedback.customerApprovals': 'Customer approvals',
  'feedback.createdBy': 'Created by',
  'feedback.updatedBy': 'Updated by',
  'feedback.updated': 'Last updated',
  'feedback.notPublished': 'This feedback is not published',
  'feedback.isPublished': 'This feedback is published and publicly viewable',
  'feedback.delete.confirmTitle': 'Delete Feedback?',
  'feedback.delete.confirmText': 'Are you sure you want to delete this feedback?',
  'feedback.main_topic.cityService': 'City and customer service',
  'feedback.main_topic.roadMaintance': 'Feedback related to street maintenance (plowing, anti-slip, dust/sand removal)',
  'feedback.main_topic.cityConstruction': 'Urban environment, construction and housing',
  'feedback.main_topic.youthService': 'Children and youth services',
  'feedback.main_topic.exercise': 'Exercise',
  'feedback.main_topic.school': 'Basic education and upper secondary school',
  'feedback.main_topic.employmentImmigration': 'Employment, working-age people, the elderly and immigrants',
  'feedback.main_topic.freeTimeCulture': 'Leisure and culture',
  'feedback.main_topic.preschoolEducation': 'Early childhood education and preschool education',
  'feedback.main_topic.communication': 'Communications and marketing',
  'feedback.main_topic.cooperation': 'Cooperation, industries and tourism',
  'help.title': 'Help',
  'attachmentView.title': 'Attachments',
  'attachmentTableHeader.size': 'Size',
  'attachmentTableHeader.created': 'Created',
  'attachmentTableHeader.name': 'Subject',
  'attachmentButton.addAttachment': 'Add file',
  'attachmentButton.downloadAttachment': 'Download file',
  'attachmentButton.deleteAttachment': 'Delete file',
  'attachment.uploadOk': 'File {fileName} uploaded',
  'attachment.uploadFailed': 'File {fileName} upload failed!',
  'attachment.delete.confirmTitle': 'Delete file?',
  'attachment.delete.confirmText': 'Are you sure you want to delete the file {fileName}?',
  'attachment.deleteFailed': 'File {fileName} delete failed!',
  'publicationsTable.title': 'Publications',
  'publicationsTableHeader.name': 'Release name',
  'publicationsTableHeader.description': 'Description',
  'publicationsTableHeader.createdBy': 'User',
  'publicationsTableHeader.created': 'Created',
  'publicationsTableHeader.liveDate': 'Live date',
  'publicationsTable.addButton': 'Add',
  'publicationsTable.exportButton': 'Export',
  'publicationsTable.uploadButton': 'Upload',
  'publications.liveDate': 'Live date',
  'publications.upload': 'Select file to upload',
  'publications.dialog.upload.description': 'Publication file in JSON format',
  'publications.external': 'This is externally configured deployment and will be in effect when there are no other deployments',
  'publications.changeStatus': 'Modify deployment status',
  'publications.currentStatus': 'Current status of deployment',
  'publications.remove': 'Remove deployment',
  'publications.deploy': 'Deploy now',
  'publications.dialogTitle': 'Create new Publication',
  'publications.name': 'Release name',
  'publications.description': 'Description',
  'publications.workflowTag': 'Workflow tag',
  'publications.wrenchTag': 'theWrench tag',
  'publications.contentTag': 'Content tag',
  'publications.createNewTag': 'Create new tag \"{tag}\"',
  'publications.downloadFailed': 'Release download failed, cause: {cause}',
  'publications.tagCreationFailed': 'Release creation failed, cause: {cause}',
  'publications.uploadDialogTitle': 'Upload publication',
  'dialobForm.saveFailed': 'Saving failed',
  'dialobForm.downloadFailed': 'Saving failed',
  'dialobForm.deleteFailed': 'Remove failed',
  'dialobForm.review.title': 'Form review',
  'feedback.notenabled': 'Feedback is not enabled for this task',
  'pages': 'Pages',
  'articles': 'Articles',
  'locale': 'Locale',
  'locales': 'Site Languages',
  'links': 'Links',
  'releases': 'Releases',
  'options': 'Options',
  'value': 'Value',
  'date': 'Date',
  'description': 'Description',
  'name': 'Name',
  'download': 'Download JSON',
  'download.all': 'Download all',
  'status': 'Status',
  'created': 'Created',
  'remove': 'Remove',
  'site.content.empty': 'Site has no content! Create content before making a release!',
  'composer.select.article': 'Select Article',
  'search.field.placeholder': 'Enter search keyword',
  'search.results.title': 'Search results',
  'search.field.label': 'Search',
  'search.all': 'All',
  'search.articles': 'Articles',
  'search.services': 'Services',
  'search.links': 'Links',
  'search.templates': 'Templates',
  'search.flows': 'Flows',
  'search.decisions': 'Decisions',
  'adminUI.formConfiguration.label': 'Title',
  'adminUI.formConfiguration.lastSaved': 'Modified',
  'adminUI.formConfiguration.latestTagDate': 'Latest tag',
  'adminUI.formConfiguration.latestTagName': 'Latest tag name',
  'adminUI.formConfiguration.labels': 'Labels',
  'adminUI.dialog.formName': 'Form name',
  'adminUI.dialog.formLabel': 'Form title',
  'adminUI.dialog.emptyTitle': '(Untitled)',
  'adminUI.dialog.heading': 'Dialogs',
  'adminUI.dialog.deleteQuestion': 'Do you want to delete the dialog',
  'adminUI.dialog.form.addFormLabel.title': 'Add a new label',
  'adminUI.dialog.form.addFormLabel.desc': 'Use labels for making sorting easier',
  'adminUI.table.tooltip.add': 'Add new dialog',
  'adminUI.table.tooltip.edit': 'Edit in Composer',
  'adminUI.table.tooltip.copy': 'Copy dialog',
  'adminUI.table.tooltip.delete': 'Delete',
  'adminUI.table.tooltip.download': 'Download',
  'activities.article.title': 'Article',
  'activities.article.desc': 'An Article is like a category: It groups Pages, Links, and Services together under one roof.',
  'activities.locale.title': 'Locale',
  'activities.locale.desc': 'Locales are your languages: Add, activate, and deactivate sitewide locales here. You can add a Page in a specific language if you have defined a locale for that page.',
  'activities.page.title': 'Page',
  'activities.page.desc': 'A Page is one content file within an Article. It represents one language and any links / workflows that are associated with an Article. It is written using Markdown syntax.',
  'activities.link.title': 'Hyperlink',
  'activities.link.desc': 'A Hyperlink will connect users to webpages you own, webpages of other organisations, and your telephone numbers.',
  'activities.release.title': 'Release',
  'activities.release.desc': 'A Release is a snapshot of all site content at one certain point of time. Use this for testing, prouduction, or backup purposes.',
  'activities.migration.title': 'Migration',
  'migration.create': 'Migrate data',
  'activities.migration.desc': 'Use a JSON file to perform a migration of a site.',
  'activities.templates.title': 'Templates',
  'activities.templates.desc': 'Use templates to customise and standardise a page default Markdown content and/or structure. Templates can be applied to new pages upon creation. Not implemented yet!',
  'activities.version.composer': 'Composer: build version {version}, build date {date}',
  'activities.version.core': 'Core: build version {version}, build date {date}',
  'dialog.about.title': 'About',
  'dialog.about.preamble': 'DigiExpress is based on open source project',
  'dialog.about.trademark': 'DigiExpress trademark and logo copyright-reserved by ReSys OÜ',
  'heading.copyDialog': 'Create copy',
  'heading.addDialog': 'Create new form',
  'heading.deleteDialog': 'Confirm',
  'templates': 'Templates',
  'template.name': 'Name',
  'template.name.desc': 'User-given name for this template',
  'template.create': 'Create template',
  'template.edit': 'Edit Template',
  'template.type': 'Template type',
  'template.page': 'Page template',
  'template.page.desc': 'This template can be applied to a new page upon creation of that page.',
  'template.description': 'Write templates in Markdown to apply to your pages and content. Templates help speed up your development and unify your content structure.',
  'template.desc': 'Description',
  'template.description.desc': 'Additional information to help identify the use cases of this template',
  'template.delete': 'Delete template',
  'template.delete.message': 'This template will be permanently removed from the application',
  'template.newpage.none': 'None',
  'templates.templatesview.description': 'A new Page can be created from a Template',
  'templates.intro': 'Remember to use a Markdown Level 1 Heading (# My Heading 1) when composing your templates.',
  'services': 'Services',
  'services.create': 'Create service',
  'services.desc': 'Connect your forms and other integrations to your content with the Wrench and Dialob workflows',
  'services.add': 'Add a service',
  'services.change': 'Change existing services',
  'services.edit': 'Edit service',
  'services.technicalname': 'Service name',
  'services.selected': 'Selected services',
  'services.modeselect.title': 'Configuration options',
  'services.modeselect.label': 'Select',
  'services.devmode': 'Development mode',
  'services.devmode.helper': 'Development mode: Service appears only in the development environment for testing and is not included in production releases.',
  'services.devmode.label': 'Development mode',
  'services.devmode.tooltip': 'Development mode',
  'services.disabledmode.label': 'Disabled mode',
  'services.disabledmode.helper': 'Disabled mode: Service does not appear on client portal',
  'services.disabledmode.tooltip': 'Disabled mode',
  'services.assignableMode.label': 'Assignable mode',
  'services.assignableMode.helper': 'Assignable mode: Can be assigned directly to customer',
  'services.assignableMode.tooltip': 'Assignable mode',
  'services.none.label': 'No configuration selected',
  'services.none.helper': 'Default mode: Service appears in production, is available ONLY to authenticated users, and is connected to ALL ARTICLES if no Article is selected',
  'services.none.tooltip': 'No special configuration',
  'services.anonmode.helper': 'Anonymous mode: Service appears for BOTH anonymous and authenticated users.',
  'services.anonmode.label': 'Anonymous mode',
  'services.anonmode.tooltip': 'Anonymous mode',
  'services.flowName': 'Flow name',
  'services.formName': 'Dialob form name',
  'services.formTag': 'Dialob form tag',
  'services.startdate': 'Start date and time',
  'services.startdate.description': 'Service activation date and time',
  'services.enddate': 'End date and time',
  'services.enddate.description': 'Service activation ending date and time',
  'services.delete': 'Delete service',
  'services.delete.desc': 'Deleting this service will permanently remove it from the application, and all associations with Articles/Pages will be lost.',
  'service.name': 'Service name',
  'service.unknown': 'Unknown service',
  'service.button.delete': 'Delete This Service',
  'snack.article.createdMessage': 'Article created successfully',
  'snack.article.deletedMessage': 'Article deleted',
  'snack.article.editedMessage': 'Article changes saved',
  'snack.page.createdMessage': 'Page created successfully',
  'snack.page.deletedMessage': 'Page deleted',
  'snack.page.savedMessage': 'Page changes saved',
  'snack.page.missingTitle': 'Please add a title to {locale} in {articleName}',
  'snack.link.createdMessage': 'Link created successfully',
  'snack.link.deletedMessage': 'Link deleted',
  'snack.link.editedMessage': 'Link changes saved',
  'snack.workflow.createdMessage': 'Service created successfully',
  'snack.workflow.deletedMessage': 'Service deleted',
  'snack.workflow.editedMessage': 'Service changes saved',
  'snack.locale.createdMessage': 'Locale created successfully',
  'snack.locale.enabled': 'Locale enabled',
  'snack.locale.disabled': 'Locale disabled',
  'snack.template.createdMessage': 'Template created successfully',
  'snack.template.deletedMessage': 'Template deleted',
  'snack.template.editedMessage': 'Template changes saved',
  'snack.template.savedMessage': 'Template saved successfully',
  'snack.service.deletedMessage': 'Service deleted',
  'snack.release.createdMessage': 'Release created successfully',
  'snack.release.deletedMessage': 'Release deleted',
  'snack.migration.createdMessage': 'Site data updated',
  'toolbar.save': 'Save',
  'toolbar.stencil': 'theStencil',
  'toolbar.contracts': 'Contracts',
  'toolbar.ledgers': 'Ledgers',
  'toolbar.wrench': 'theWrench',
  'toolbar.menu': 'Menu',
  'toolbar.help': 'Help',
  'toolbar.import': 'Import data',
  'toolbar.tasks': 'Tasks',
  'toolbar.about': 'About',
  'toolbar.cockpits': 'Cockpits',
  'stencil.services.found.none': 'No services found',
  'link.type.internal': 'Internal',
  'link.type.external': 'External',
  'link.type.phone': 'Phone number',
  'link.search.title': 'Search links by value',
  'link.value': 'Link value',
  'sitelocale.label.select.alreadyDefined': 'Cannot add because this locale is already defined',
  'sitelocale.label.table.editLocaleValue': 'Edit locale value',
  'locales.label.table.title': 'Locale labels',
  'locales.label.title.helper': 'At least one language code (locale) + locale label value is required',
  'locales.label.table.value': 'Translated text value',
  'locales.label.table.noneSet': 'No translated labels!',
  'locales.enabledMessage': 'Enabled: Content for this locale will be displayed on the portal side',
  'locales.disabledMessage': 'Disabled: Content for this locale will be hidden from the portal side. Content can still be edited.',
  'transferlist.noItemsSelected': 'No items selected',
  'transferlist.search': 'Search',
  'transferlist.noSearchResults': 'No search results found',
  'explorer.tabs.links': 'Links',
  'explorer.tabs.services': 'Services',
  'imports.select': 'Select a file to import',
  'imports.import.action': 'Import selected',
  'article.order': 'Article order number',
  'article.order.view': 'View current Article ordering hierarchy',
  'article.select': 'Select Articles',
  'article.links.selectedlinks': 'Selected links',
  'article.composer.title': 'Create new Article',
  'article.composer.parent': 'Parent Article',
  'article.parent.helper': 'If a Parent article is selected, this article will live inside this parent, like a file inside a folder does.',
  'article.composer.parent.unselected': 'No parent article',
  'article.create': 'Create article',
  'article.name': 'Article name',
  'article.unknown': 'Unknown article',
  'article.delete.title': 'Delete article',
  'article.delete.description': 'Deleting this article will remove it and its associated pages globally from the application.',
  'article.edit.title': 'Edit article',
  'article.edit.parent': 'Parent article',
  'article.devmode.helper': 'If Development mode is active, this article will only appear in the development environment for testing. It will not be included in production releases.',
  'article.devmode': 'Development mode',
  'articleservices': 'Article services: {name}',
  'articlelinks': 'Article links: {name}',
  'article.composer.orderhelper': 'The lower the number, the higher up this article will appear in your portal UI Topic Menu.  Example: 000 will be the first Topic menu item, while 999 will be the last.',
  'article.timestamps.title': 'History',
  'button.create': 'Create',
  'button.add': 'Add',
  'button.disable': 'Continue and disable',
  'button.enable': 'Continue and enable',
  'button.apply': 'Apply changes',
  'button.view.all.locales': 'View locales',
  'button.view.all.releases': 'View releases',
  'button.view.all.templates': 'View templates',
  'links.searchAll': 'Search all links',
  'link.article.select': 'Select Article',
  'link.type': 'Type',
  'link.content': 'Link URL / path',
  'link.composer.title': 'Create a new link',
  'link.composer.valuehelper': 'URL / path of link (http://www.example.com)',
  'link.edit.title': 'Edit link',
  'link.delete.title': 'Delete link',
  'link.delete': 'Deleting this link will permanently remove it from the application, and all associations with Articles/Pages will be lost.',
  'resource.edit.links': 'Edit links',
  'links.change': 'Change existing links',
  'link.create': 'Create new link',
  'link.devmode.helper': 'If Development mode is active, this link will only appear in the development environment. It will not be included in production releases.',
  'link.devmode': 'Development mode',
  'locale.create': 'Create locale',
  'locale.disable.title': 'Disable this locale?',
  'locale.enable.title': 'Enable this locale?',
  'locale.disable': 'Any Pages using this locale will be hidden on the UI. Pages can still be edited.',
  'locale.enable': 'All Pages using this locale will be displayed on the UI.',
  'locale.composer.title': 'Create a new locale',
  'locale.composer.placeholder': 'Two-letter language code',
  'locale.composer.helper': 'Two-letter language codes designate the content language. Common examples: en = English, fi = Finnish, sv = Swedish',
  'locale.overview': 'Locale usage overview',
  'locales.overview.description': 'Manage the languages of your site content. Disable locales to hide all content associated with that language from your site',
  'locales.content': 'Page in this locale has content',
  'locales.nocontent': 'Page in this locale has no content',
  'locales.nopage': 'There is no page for this locale in this Article',
  'locales.label.table.locale': 'Language code',
  'newpage.title': 'Create a new page',
  'newpage.template.select': 'Template',
  'newpage.info': 'A page consists of localised content and must be associated with an Article.',
  'newpage.article.info': 'Confirm creation of page for: {article} with locale: {locale}',
  'page.create': 'Create page',
  'page.delete.dialog.title': 'Delete a page from article',
  'page.delete.description': 'The selected page will be permanently removed from your site',
  'pages.add': 'Add a page',
  'pages.change': 'Change a page locale',
  'pages.select.locale': 'Edit localised page content',
  'pages.select.locale.edit.desc': 'Select two languages to enable side-by-side editing in one tab.',
  'pages.edit.language1': 'Edit language',
  'pages.edit.language2': 'Edit this language side-by-side',
  'pages.edit.currentlyEditing.language2': 'Editing side-by-side',
  'pages.edit.currentlyEditing.language1': 'Editing language',
  'pages.change.info': 'Select a page from this Article and enter a new value for its locale.',
  'pages.change.devmode': 'Change a page development mode',
  'pages.change.devmode.info': 'Select a page from this Article and change its development mode.',
  'pages.devmode.helper': 'If Development mode is active, this page will only appear in the development environment. It will not be included in production releases.',
  'pages.devmode': 'Development mode',
  'pages.delete': 'Delete a page',
  'pages.edit.selectpage': 'Select page',
  'pages.edit.selectTargetLocale': 'Select target locale',
  'release.create': 'Create release',
  'release.composer.title': 'Create a new release',
  'release.composer.label': 'Tag Name',
  'release.composer.note': 'Note',
  'release.composer.helper': 'Optional additional information for future reference',
  'release.composer.helper.optionalDesc': 'Optional description',
  'release.desc': 'View all releases and download all site content in JSON format. For more detailed information on specific releases and their content, view the Graph.',
  'release.delete.title': 'Delete release',
  'release.delete.desc': 'Delete this release permanently from site data?',
  'releases.view.note': 'Notes',
  'releases.view.tag': 'Name',
  'releases.view.created': 'Created',
  'releases.view.download': 'JSON download',
  'buttons.create': 'Create',
  'buttons.apply': 'Apply',
  'buttons.delete': 'Delete',
  'buttons.copy': 'Copy',
  'button.compose': 'Compose',
  'buttons.download': 'Download',
  'activities.flows.title': 'Workflow',
  'activities.flows.desc': 'A a sequence of tasks which are defined by using simple configuration language.',
  'activities.decisions.title': 'Decisions',
  'activities.decisions.desc': 'A decision table that can be used to make decisions based on input data.',
  'activities.services.title': 'Services',
  'activities.services.desc': 'A piece of Java or Groovy code that is embedded inside of a flow as a task.',
  'activities.releases.title': 'Releases',
  'activities.releases.desc': 'A Release is a snapshot of all site content at one certain point of time.',
  'activities.releases.desc.additional': 'Each Release can be downloaded to be used for production or backup purposes, or can be branched for further editing. This will replace all current assets so make sure any changes are saved.',
  'activities.releases.view': 'View all releases',
  'activities.compare.title': 'Compare',
  'activities.compare.desc': 'Compare two releases to see what has changed between them.',
  'activities.compare.view': 'Compare',
  'activities.compare.sort.oldestFirst': 'Sort oldest first',
  'activities.compare.sort.newestFirst': 'Sort newest first',
  'activities.debug.title': 'Debug',
  'activities.debug.desc': 'Simulate execution of an asset. Can be done via form input, JSON input, or by using a CSV file.',
  'activities.debug.view': 'Simulate',
  'activities.assets.saveSuccess': 'Saved asset: {name}',
  'wrench.explorer.info': 'Info',
  'wrench.explorer.info.lastModified': 'Last modified: {value}',
  'flows': 'Flows',
  'upload.json': 'JSON',
  'upload.csv': 'CSV',
  'migrations.title': 'Migration',
  'migrations.create': 'Perform migration',
  'migrations.select': 'Select tag.json file',
  'flows.edit.title': 'Edit flow',
  'flows.copyas.title': 'Copy flow as',
  'flows.delete.title': 'Delete flow',
  'flows.delete.error.title': 'Failed to delete flow',
  'flows.delete.content': 'Are you sure you want to delete FLOW: {name}?',
  'flows.deleted.message': 'Deleted FLOW: {name}',
  'flows.simulate.title': 'Debug the flow',
  'flows.composer.title': 'Create new FLOW',
  'flows.composer.copyTitle': 'Copy FLOW as',
  'flows.composer.createdMessage': 'Created FLOW: {name}',
  'flows.composer.copiedMessage': 'Copied FLOW {name} as: {newName}',
  'flows.composer.errorsTitle': 'Failed to create FLOW',
  'flows.composer.assetName': 'Unique name for the FLOW',
  'flows.autocomplete.task.create': 'Create new asset',
  'flows.autocomplete.task.link': 'Link selected asset',
  'flows.autocomplete.task.searchField': 'Search for asset...',
  'flows.autocomplete.task.searchPlaceholder': 'Asset name or description',
  'flows.autocomplete.task.selectType': 'Select asset type to link',
  'flows.autocomplete.task.searchHelper': 'Matches asset name and description',
  'flows.autocomplete.task.searchResults': 'Search results',
  'flows.autocomplete.task.snackbar.created': 'Created new {type}: {name}',
  'flows.autocomplete.task.snackbar.creating': 'Creating new {type}: {name}',
  'flows.graph.show': 'Show flow graph',
  'flows.graph.hide': 'Hide flow graph',
  'services.searchAll': 'Search all services',
  'services.edit.title': 'Edit service',
  'services.copyas.title': 'Copy service as',
  'services.delete.title': 'Delete service',
  'services.delete.error.title': 'Failed to delete SERVICE',
  'services.delete.content': 'Are you sure you want to delete SERVICE: {name}?',
  'services.deleted.message': 'Deleted SERVICE: {name}',
  'services.simulate.title': 'Debug the service',
  'services.composer.title': 'Create new SERVICE',
  'services.composer.copyTitle': 'Copy SERVICE as',
  'services.composer.createdMessage': 'Created SERVICE: {name}',
  'services.composer.copiedMessage': 'Copied SERVICE {name} as: {newName}',
  'services.composer.errorsTitle': 'Failed to create SERVICE',
  'services.composer.assetName': 'Unique name for the SERVICE',
  'decisions.name': 'Name',
  'decisions.desc': 'Description',
  'decisions.simulate.title': 'Debug the decision',
  'decisions.hitpolicy': 'Hit-policy',
  'decisions.edit.title': 'Edit decision',
  'decisions.copyas.title': 'Copy decision as',
  'decisions.delete.error.title': 'Failed to delete DECISION',
  'decisions.delete.title': 'Delete decision',
  'decisions.delete.content': 'Are you sure you want to delete DECISION: {name}?',
  'decisions.deleted.message': 'Deleted DECISION: {name}',
  'decisions.deleteConfirmTitle': 'Confirm Delete',
  'decisions.deleteConfirmText': 'Are you sure you want to delete this {type}?',
  'decisions.type.row': 'Row',
  'decisions.type.column': 'Column',
  'decisions.table.hitpolicy': 'Column',
  'decisions.composer.title': 'Create new DECISION',
  'decisions.composer.copyTitle': 'Copy DECISION as',
  'decisions.composer.createdMessage': 'Created DECISION: {name}',
  'decisions.composer.copiedMessage': 'Copied DECISION {name} as: {newName}',
  'decisions.composer.errorsTitle': 'Failed to create DECISION',
  'decisions.composer.assetName': 'Unique name for the DECISION',
  'decisions.toolbar.options': 'Options',
  'decisions.toolbar.addInputColumn': 'Add input column',
  'decisions.toolbar.addOutputColumn': 'Add output column',
  'decisions.toolbar.addRow': 'Add row',
  'decisions.toolbar.csvDownload': 'Download CSV',
  'decisions.toolbar.csvUpload': 'Upload CSV',
  'decisions.toolbar.copyCommands': 'Copy commands',
  'decisions.toolbar.nameAndHitpolicy': 'Name and hit-policy',
  'decisions.toolbar.organize.rows.columns': 'Organize rows and columns',
  'decisions.toolbar.organize.action': 'Select action',
  'decisions.toolbar.organize.action.helper': 'Choose an action to perform on the table',
  'decisions.toolbar.organize.action.expression': 'Select expression',
  'decisions.toolbar.organize.action.expression.column': 'Select column',
  'decisions.toolbar.organize.action.deleteColumn': 'Delete whole column',
  'decisions.toolbar.organize.action.deleteRow': 'Delete whole row',
  'decisions.toolbar.organize.action.deleteRow.contents': 'Row contents',
  'decisions.toolbar.organize.action.move.from.column': 'Column to move',
  'decisions.toolbar.organize.action.move.from.row': 'Row to move',
  'decisions.toolbar.organize.action.move.to.column': 'New Position',
  'decisions.toolbar.organize.action.move.to.row': 'New Position',
  'decisions.toolbar.organize.action.direction.column': 'Select column to change direction',
  'decisions.toolbar.organize.action.direction.change': 'Changing direction to {newDirection}',
  'decisions.toolbar.organize.operation.MOVE_ROW': 'Move row',
  'decisions.toolbar.organize.operation.DELETE_ROW': 'Delete row',
  'decisions.toolbar.organize.operation.MOVE_HEADER': 'Move column',
  'decisions.toolbar.organize.operation.DELETE_HEADER': 'Delete column',
  'decisions.toolbar.organize.operation.SET_HEADER_EXPRESSION': 'Set column expression',
  'decisions.toolbar.organize.operation.SET_HEADER_DIRECTION': 'Change column direction',
  'decisions.toolbar.organize.helper.MOVE_ROW': 'Move a row to a different position in the table',
  'decisions.toolbar.organize.helper.DELETE_ROW': 'Permanently delete a row from the table',
  'decisions.toolbar.organize.helper.MOVE_HEADER': 'Move a column to a different position',
  'decisions.toolbar.organize.helper.DELETE_HEADER': 'Permanently delete a column from the table',
  'decisions.toolbar.organize.helper.SET_HEADER_EXPRESSION': 'Apply an expression to a column\'s values',
  'decisions.toolbar.organize.helper.SET_HEADER_DIRECTION': 'Change column between input and output',
  'decisions.csv.delimiter': 'Delimiter',
  'decisions.csv.delimiter.custom': 'Custom',
  'decisions.csv.delimiter.custom.placeholder': 'Enter custom delimiter',
  'decisions.table.inputs.title': 'Matching rules',
  'decisions.table.outputs.title': 'Results',
  'decisions.header.dialog.title': 'Decision table: {name}, column: {column}',
  'decisions.cells.dialog.title': 'Decision table: {name}, column: {column}, value: {value}',
  'decisions.cells.dialog.title.simple': 'Edit Value',
  'decisions.header.dialog.title.simple': 'Edit Header',
  'decisions.cells.dialog.title.intl': 'Edit Localized Value',
  'decisions.cells.newvalue.boolean': 'Enter new value',
  'decisions.cells.newvalue.boolean.helper': 'Select boolean value',
  'decisions.cells.newvalue.boolean.empty': 'No value selected',
  'decisions.cells.newvalue.date.operator': 'Operator',
  'decisions.cells.newvalue.date.start': 'Start date',
  'decisions.cells.newvalue.date.end': 'End date',
  'decisions.cells.newvalue.date.value': 'Date',
  'decisions.cells.newvalue.number.comparisonType': 'Comparison',
  'decisions.cells.newvalue.number.comparisonTypeEmpty': 'Comparison not selected',
  'decisions.cells.newvalue.number.comparisonValue': 'New numerical value',
  'decisions.cells.newvalue.number.comparisonToRange': 'Change to range',
  'decisions.cells.newvalue.number.rangeStart': 'Start',
  'decisions.cells.newvalue.number.rangeEnd': 'End',
  'decisions.cells.newvalue.string.comparisonType': 'Comparison',
  'decisions.cells.newvalue.string.addValue': 'Add new value',
  'decisions.cells.newvalue.string.available': 'Available values',
  'decisions.cells.newvalue.string.selected.values': 'Selected values',
  'decisions.cells.newvalue.string.selected': 'Selected value',
  'decisions.cells.newvalue.string.selected.empty': 'No value selected',
  'decisions.cells.newvalue.string.empty': 'Comparison not selected',
  'decisions.cells.newvalue.clear': 'Clear current value',
  'decisions.valueSet': 'Define value set',
  'decisions.valueSet.description': 'Value sets can be used to define a predetermined set of values for any input',
  'decisions.valueSet.add': 'Add to value set',
  'decisions.valueSet.add.placeholder': 'Type and press Enter',
  'decisions.valueSet.current': 'Current value set',
  'decisions.valueSet.current.empty': 'No values',
  'decisions.intl.locales.addNew': 'Add locale',
  'decisions.intl.locales.hint': 'Example: fi or en',
  'decisions.intl.locales.current': 'Current locales',
  'decisions.intl.columnType.help': 'INTL columns use per-locale values. Define which locales are supported below.',
  'dt.header.name': 'Name',
  'dt.header.delete': 'Delete',
  'dt.header.expression': 'Expression',
  'dt.header.dataType': 'Data type',
  'dt.header.script': 'Script',
  'decisions': 'Decisions',
  'program.status.DEPENDENCY_ERROR': 'Dependency Errors',
  'program.status.UP': 'Program is UP',
  'program.status.AST_ERROR': 'Syntax errors',
  'program.status.PROGRAM_ERROR': 'Compiler errors',
  'release.deleted.message': 'Release {name} deleted',
  'releases.composer.createdMessage': 'Created new release {name}',
  'releases.view.action': 'Action',
  'releases.composer.title': 'Create new release',
  'releases.composer.assetName': 'Release name',
  'releases.composer.assetDesc': 'Release description',
  'releases.composer.errorsTitle': 'Error while creating release',
  'releases.button.compare': 'Compare',
  'releases.button.branch': 'Create new branch',
  'releases.button.checkout': 'Checkout',
  'releases.button.release': 'Release',
  'releases.button.details': 'View release assets',
  'releases.default.name': 'Default',
  'releases.default.note': 'This is the default branch that you can go back to',
  'releases.latest.name': 'Latest',
  'releases.latest.note': 'These are current assets with the latest changes that can be released',
  'releases.details.title': 'Release assets: {name}',
  'release.branch.creating': 'Creating new branch: {name}',
  'release.branch.created': 'Created new branch: {name}',
  'release.branch.deleting': 'Deleting branch: {name}',
  'release.branch.deleted': 'Deleted branch: {name}',
  'release.branch.checkout': 'Checked out to branch: {name}',
  'debug.toolbar.options': 'Options',
  'debug.toolbar.selectAsset': 'Select asset to debug',
  'debug.toolbar.inputCsv': 'Define input data as a CSV',
  'debug.toolbar.inputForm': 'Define input data as a FORM',
  'debug.toolbar.inputJson': 'Define input data as a JSON',
  'debug.toolbar.execute': 'Execute',
  'debug.toolbar.noAsset': 'Select asset from options',
  'debug.toolbar.openAsset': 'Open',
  'debug.toolbar.download': 'Download results as CSV',
  'debug.input.noAsset': 'There is no ASSET selected',
  'debug.input.form': 'Debug using FORM',
  'debug.input.formTitle': 'Define inputs',
  'debug.input.form.invalid.integer': 'Value must be an integer',
  'debug.input.form.invalid.number': 'Value must be a number',
  'debug.input.form.invalid.range': 'Value must be in the specified range',
  'debug.input.json': 'Debug using JSON',
  'debug.input.jsonTitle': 'Define JSON input',
  'debug.input.csvUpload': 'Debug using CSV',
  'debug.input.csvFile': 'Upload CSV FILE',
  'debug.input.csvFileTitle': 'Upload CSV file - semicolon-delimited (;)',
  'debug.input.csvFileOrText': 'Or paste CSV contents - semicolon-delimited (;)',
  'debug.inputs.fieldName': 'Field Name',
  'debug.inputs.fieldValue': 'Field Value',
  'debug.select.title': 'Select asset to debug',
  'debug.select.assetType': 'Asset type to filter',
  'debug.select.searchField': 'Asset name to search',
  'debug.select.searchHelper': 'Search matches asset name or description',
  'debug.select.searchPlaceholder': 'Keyword to search',
  'debug.select.searchResults': 'Found assets',
  'debug.select.confirm': 'Select',
  'debug.inputs.format': 'Asset input format: {type}',
  'debug.asset.execute.errors': 'Execution errors',
  'debug.asset.execute.outputs.dt.json': 'Matched row(s)',
  'debug.asset.execute.outputs.dt.rejects': 'Rejected row(s)',
  'debug.asset.execute.outputs.flow.step': 'Step name: {name}, status: {status}',
  'debug.csv.row': 'Data row: {row}',
  'debug.csv.download': 'Download results as CSV',
  'debug.csv.download.delimiter': 'Choose a delimiter for the CSV file',
  'debug.csv.download.delimiter.semicolon': 'Semicolon (;)',
  'debug.csv.download.delimiter.comma': 'Comma (,)',
  'debug.csv.download.options': 'Export options',
  'debug.csv.download.wrap': 'Wrap cells containing delimiters with quotes',
  'compare.tip': 'Select releases to compare below. Base is the starting point of the comparison, and target is the release that will be compared to the base.',
  'compare.base': 'Select base release',
  'compare.target': 'Select target release',
  'compare.dialog.title': 'Comparing releases {base} and {target}',
  'compare.dialog.line': 'Inline',
  'compare.dialog.side': 'Side-by-side',
  'menu.activities': 'Activities',
  'feedback.all': 'All feedback',
  'queues.all': 'Queues',
  'consumers.all': 'Consumers',
  'queue.config.none': 'Loading',
  'queue.config.consumerName': 'Consumer name',
  'queue.config.routingKey': 'Routing key',
  'queue.config.consumerStatus': 'Status',
  'queue.config.comment': 'Comment',
  'queue.config.queueName': 'Queue name',
  'queue.config.createdAt': 'Created at',
  'queue.config.createdBy': 'Created by',
  'queue.all_deliveries.title': 'All deliveries',
  'queue.all_deliveries.created': 'Created',
  'queue.all_deliveries.consumerComment': 'Comment',
  'queue.all_deliveries.status': 'Status',
  'queue.all_deliveries.messageId': 'Message id',
  'queue.all_deliveries.consumerId': 'Consumer id',
  'queue.all_messages.title': 'All messages',
  'queue.all_messages.routingKey': 'Routing key',
  'queue.all_messages.messageId': 'Message id',
  'queue.all_messages.bodyId': 'Body id',
  'queue.all_messages.bodyType': 'Body type',
  'queue.all_messages.status': 'Status',
  'queue.all_messages.body': 'Body',
  'queue.all_messages.created': 'Created',
  'workflows': 'Workflows',
  'explorer.pages': 'Pages',
  'articles.searchAll': 'Search all articles',
  'composer.article.selected': 'Selected Articles',
  'resource.edit.workflows': 'Workflows',
  'workflow.delete': 'Delete',
  'workflow.edit': 'Edit',
  'eveli.table.menu.filter.filterBy': 'Filter by {title}',
  'eveli.table.menu.filter.showAllItems': 'Select all',
  'eveli.table.menu.sort.ascending': 'Ascending',
  'eveli.table.menu.sort.descending': 'Descending',
  'eveli.table.menu.sort.clearSorting': 'Clear sorting',
  'eveli.table.menu.sort.chooseCols': 'Choose columns',
  'eveli.table.menu.sort.colsReset': 'Reset columns',
  'eveli.table.dialog.columns.chooseCols': 'Choose columns',
  'eveli.table.footer.tasks.total': 'Total',
  'eveli.table.footer.tasks.rowsPerPage': 'Rows per page',
  'eveli.table.footer.pageNumber': 'Page number',
  'eveli.table.footer.rowsPerPage': 'Rows per page',
  'eveli.table.drawer.buttons.colsButton': 'Columns',
  'eveli.table.drawer.buttons.filtersButton': 'Column filters',
  'eveli.table.resetAll': 'Reset all',
  'eveli.table.drawer.title.columns': 'Columns',
  'eveli.table.drawer.title.filters': 'Filters',
  'eveli.table.drawer.title.saved-filters': 'Saved table views',
  'eveli.table.drawer.title.export-data': 'Export data',
  'eveli.table.defaultSettings': 'Default Settings',
  'eveli.error.general': 'We have encountered an error!',
  'eveli.error.notFound': 'The thing you are looking for is not found!',
  'eveli.error.backToHome': 'Go back to our home page',
  'eveli.table.saveas.title': 'Save current configuration as filter',
  'eveli.table.updatefilter.title': 'Update filter name',
  'eveli.table.saveas.name': 'Filter name',
  'eveli.table.resetColumnVisbility': 'Reset column order and visibility',
  'eveli.table.resetColumnSorting': 'Reset column sorting',
  'eveli.table.menu.filter.filterByDateEqual': 'Date is equal',
  'eveli.table.menu.filter.filterByDateLt': 'Date is before',
  'eveli.table.menu.filter.filterByDateGte': 'Date is greater than or equal',
  'eveli.table.menu.filter.filterByDateTitle': 'Date filtering',
  'eveli.userProfile.title': 'User Profile',
  'eveli.userProfile.id': 'Id',
  'eveli.userProfile.displayName': 'Display name',
  'eveli.userProfile.firstAndLastName': 'Full name',
  'eveli.userProfile.created': 'Created',
  'eveli.userProfile.updated': 'Updated',
  'eveli.userProfile.firstName': 'First name',
  'eveli.userProfile.lastName': 'Last name',
  'eveli.userProfile.email': 'Email',
  'eveli.userProfile.notificationSettings': 'Notification settings',
  'eveli.userProfile.userRoles': 'My roles',
  'eveli.userProfile.userPermissions': 'My permissions',
  'eveli.userProfile.editDetails': 'Edit personal details',
  'eveli.userProfile.currentDetails': 'My current details',
  'eveli.userProfile.tenantConfig': 'Configuration options',
  'eveli.userProfile.tenantConfig.select': 'Config option',
  'eveli.userProfile.tenantConfig.select.title': 'Personalise your experience by adding and removing features',
  'eveli.userProfile.tenantConfig.select.LOGIN_BUTTON': 'Login button',
  'eveli.userProfile.tenantConfig.select.external-deployment': 'External deployment',
  'eveli.userProfile.tenantConfig.select.external-deployment.desc': 'Assets come explicitly from an environment-specific data source that implements ExternalDeploymentProvider',
  'eveli.userProfile.tenantConfig.select.feedback-visually-disabled': 'Feedback visually disabled',
  'eveli.userProfile.tenantConfig.select.feedback-visually-disabled.desc': 'Show / hide the feedback feature from the UI',
  'eveli.userProfile.tenantConfig.select.queues-visually-disabled': 'Queues visually disabled',
  'eveli.userProfile.tenantConfig.select.queues-visually-disabled.desc': 'Show / hide the Queues feature from the UI',
  'eveli.userProfile.tenantConfig.select.stencil-disabled': 'Stencil disabled',
  'eveli.userProfile.tenantConfig.select.stencil-disabled.desc': 'Eveli is reconfigured so as to remove Stencil',
  'eveli.userProfile.tenantConfig.select.wrench-disabled': 'Wrench disabled',
  'eveli.userProfile.tenantConfig.select.wrench-disabled.desc': 'Eveli is reconfigured so as to remove Wrench',
  'eveli.userProfile.tenantConfig.select.wrench-only': 'Wrench only',
  'eveli.userProfile.tenantConfig.select.wrench-only.desc': 'Eveli is reconfigured so as to include only Wrench',
  'eveli.userProfile.tenantConfig.select.batches': 'Batches',
  'eveli.userProfile.tenantConfig.select.batches.desc': 'Enable / disable batch processing features',
  'eveli.userProfile.tenantConfig.select.eveli_publication_only': 'Eveli publication only',
  'eveli.userProfile.tenantConfig.select.eveli_publication_only.desc': 'Editing assets is disabled - they come directly from a publication',
  'eveli.userProfile.tenantConfig.select.smart_tables': 'Smart tables',
  'eveli.userProfile.tenantConfig.select.smart_tables.desc': 'All tables are persistant - they save user-defined configurations',
  'eveli.userProfile.tenantConfig.select.stencil_locale_filter': 'Stencil locale filter',
  'eveli.userProfile.tenantConfig.select.stencil_locale_filter.desc': 'Configure visibility of the locale filtering UI component in Stencil',
  'eveli.userProfile.tenantConfig.select.user_profile': 'User profile enabled',
  'eveli.userProfile.tenantConfig.select.user_profile.desc': 'Show / hide the user profile feature from the UI',
  'eveli.userProfile.tenantConfig.select.smart_task': 'Smart task view',
  'eveli.userProfile.tenantConfig.select.smart_task.desc': 'Editing a task is enhanced via drag and drop/unified editing/flashy colours',
  'eveli.userProfile.tenantConfig.select.smart_task_audit': 'Smart task audit',
  'eveli.userProfile.tenantConfig.select.smart_task_audit.desc': 'Additional detailed views are enabled for auditing/debugging a task',
  'eveli.userProfile.tenantConfig.select.visual_accommodation': 'Visual accommodation',
  'eveli.userProfile.tenantConfig.select.visual_accommodation.desc': 'To make certain buttons and UI items pop for enhanced visibility',
  'eveli.userProfile.tenantConfig.select.dialob_dashboard_smart': 'Smart Dialob dashboard',
  'eveli.userProfile.tenantConfig.select.dialob_dashboard_smart.desc': 'Improved filtering and sorting of Dialob forms using Smart tables',
  'eveli.userProfile.tenantConfig.select.tagomi': 'Tagomi PDF Composer',
  'eveli.userProfile.tenantConfig.select.tagomi.desc': 'Create and manage custom PDF files',
  'eveli.userProfile.tenantConfig.select.contract': 'Contracts',
  'eveli.userProfile.tenantConfig.select.contract.desc': 'Enable contract and ledger management module',
  'eveli.userProfile.tenantConfig.select.cockpits': 'Cockpits',
  'eveli.userProfile.tenantConfig.select.cockpits.desc': 'Configure individual tenants with differing assets for different use cases',
  'eveli.userProfile.tenantConfig.select.contracts': 'Contracts',
  'eveli.userProfile.tenantConfig.select.contracts.desc': 'Enable contract and ledger management module',
  'eveli.userProfile.tenantConfig.select.eveli_tree': 'File explorer',
  'eveli.userProfile.tenantConfig.select.eveli_tree.desc': 'Manage all Eveli assets in one location via Smart file explorer',
  'taskTable.col.header.priority': 'Priority',
  'taskTable.col.header.subject': 'Subject',
  'taskTable.col.header.addInfo': 'Info',
  'taskTable.col.header.client': 'Client',
  'taskTable.col.header.status': 'Status',
  'taskTable.col.header.roles': 'Role',
  'taskTable.col.header.assignee': 'Assigned',
  'taskTable.col.header.due': 'Due date',
  'taskTable.col.header.created': 'Created',
  'taskTable.col.header.archive': 'Archive',
  'taskTable.col.header.overdue': 'Overdue',
  'taskTable.button.archive.confirm': 'You are about to archive this task. Are you sure you want to continue?',
  'taskTable.confirmArchive.title': 'Confirming archive task {taskRef}',
  'taskTable.snackbar.archived': 'Archived task {taskRef}: {subject}',
  'taskTable.snackbar.archiveFailed': 'Failed to archive task {taskRef}',
  'taskTable.title': 'Tasks',
  'taskButton.addTask': 'Add task',
  'eveli.table.clearFilters': 'Clear all filters',
  'eveli.table.drawer.buttons.savedFiltersButton': 'Personalise',
  'eveli.table.saveasdefault': 'Save as default',
  'eveli.table.saveas': 'New filter from current',
  'eveli.batches.batchView.averageRunTime': 'Average run time',
  'eveli.batches.batchView.averageRunTime.ms': 'ms',
  'taskcard.style.COMPACT': 'Compact',
  'taskcard.style.DEFAULT': 'Default',
  'taskcard.style.LARGE': 'Large',
  'taskcard.title.rolesAndAssignees': 'Roles and assignees',
  'taskcard.title.customerMessages': 'Customer messages',
  'taskcard.title.notes': 'Notes',
  'taskcard.title.statusAndPriority': 'Status and priority',
  'taskcard.title.formReview': 'Review form',
  'taskcard.title.history': 'History and metadata',
  'taskcard.title.taskRefId': 'Task reference ID',
  'taskcard.title.edit': 'Edit',
  'taskcard.title.transfer': 'Document transfers',
  'taskcard.title.assignable': 'Assigned to customer',
  'taskcard.title.customerFeedback': 'Customer feedback',
  'taskcard.title.files': 'Files',
  'taskcard.body.roles': 'Roles',
  'taskcard.body.assignee': 'Assignee',
  'taskcard.body.lastEditedBy': 'Last edited by',
  'taskcard.body.lastEditedDate': 'Last edited date',
  'taskcard.body.dueDate': 'Due date',
  'taskcard.body.dueDate.value.invalid': 'Invalid date format or range--check format: dd.MM.yyyy',
  'taskcard.body.customerName': 'Customer name',
  'taskcard.body.subject': 'Subject',
  'taskcard.body.additionalInfo': 'Additional info',
  'taskcard.body.sentiment': 'Sentiment',
  'taskcard.body.similar.feedback': 'Similar feedback',
  'taskcard.body.subcategory': 'Subcategory',
  'taskcard.body.transfer.none': 'No transfers',
  'taskcard.body.transfer.title': 'Document transfers',
  'taskcard.body.form.formName': 'Form name',
  'taskcard.body.form.submittedDate': 'Submitted',
  'taskcard.body.form.canPublishFeedback': 'Publish feedback?',
  'taskcard.body.form.representative': 'Representative',
  'taskcard.body.task.status': 'Status',
  'taskcard.body.task.priority': 'Priority',
  'taskcard.cardStyle': 'Card display style',
  'taskcard.title.ai.assistant': 'AI Assistant',
  'taskcard.title.audit.ai': 'Audit: AI Analysis',
  'taskcard.title.audit.viewers': 'Audit: Viewers',
  'taskcard.title.audit.commits': 'Audit: Commits',
  'taskcard.title.audit.queues': 'Audit: Queues',
  'taskcard.title.audit.processes': 'Audit: Processes',
  'taskcard.title.audit.flow': 'Audit: Flow',
  'taskcard.title.audit.queueMessages': 'Audit: Queue messages',
  'taskcard.title.audit.queueBindings': 'Audit: Queue bindings',
  'taskcard.title.audit.queueDeliveries': 'Audit: Queue deliveries',
  'task.audit.commits.commitBody.title': 'Commit body',
  'task.audit.commits.author': 'Author',
  'task.audit.commits.message': 'Message',
  'task.audit.commits.commitBody': 'Commit body',
  'task.audit.commits.bodyValue.title': 'Body value',
  'task.audit.commits.createdAt': 'Created',
  'task.audit.ai.sentiment.and.subcategory': 'AI: Sentiment and subcategory',
  'task.audit.ai.similar.feedback': 'AI: Similar feedback',
  'task.audit.deliveries.attempts.title': 'Delivery attempts',
  'task.audit.process.type': 'Type',
  'task.audit.process.value': 'Value',
  'task.audit.process.createdAt': 'Created',
  'task.audit.processes.None': 'No process for this task',
  'task.audit.queue.name': 'Queue name',
  'task.audit.queue.createdBy': 'Created by',
  'task.audit.queue.comment': 'Comment',
  'task.audit.queue.createdAt': 'Created',
  'task.audit.queueBindings.createdBy': 'Created by',
  'task.audit.queueBindings.status': 'Status',
  'task.audit.queueBindings.comment': 'Comment',
  'task.audit.queueBindings.createdAt': 'Created',
  'task.audit.queueDeliveries.queueName': 'Queue name',
  'task.audit.queueBindings.attempts': 'Attempts',
  'task.audit.queueMessages.routingKey': 'Routing key',
  'task.audit.queueMessages.bodyType': 'Body type',
  'task.audit.queueMessages.bodyValue': 'Body value',
  'task.audit.queueMessages.createdAt': 'Created',
  'task.audit.viewers.usedBy': 'Viewed by',
  'task.audit.viewers.updatedAt': 'Updated',
  'task.composer.error.subject.required': '* Task subject is required',
  'task.composer.create': 'Create new task',
  'task.composer.dueDate': 'Due',
  'task.composer.clientName': 'Client name',
  'task.composer.subject': '* Subject',
  'task.composer.field.required': '* required',
  'task.composer.description': 'Description',
  'task.composer.additionalInfo': 'Additional info',
  'task.composer.roles': 'Roles',
  'task.composer.assignee': 'Assignee',
  'task.composer.assignments.none': 'No assignments',
  'task.composer.assignments.status.NEW': 'New',
  'task.composer.assignments.status.OPEN': 'Open',
  'task.composer.assignments.status.COMPLETED': 'Completed',
  'task.composer.assignments.status.CANCELLED': 'Cancelled',
  'task.composer.priority': 'Priority',
  'task.composer.status': 'Status',
  'task.composer.task.edit': 'Edit task',
  'task.customerFeedback': 'Customer feedback',
  'task.feedback.none': 'No feedback available',
  'task.feedback.similarities.none': 'No similar feedback found',
  'task.feedback.title': 'Customer title',
  'task.feedback.detailedResponse': 'Details from customer',
  'task.feedback.published': 'Published',
  'task.feedback.notPublished': 'Not published',
  'task.attachments': 'Task attached files',
  'task.button.uploadFile': 'Upload file',
  'task.file.fileName': 'File name',
  'task.file.uploadDate': 'Upload date',
  'task.files.none': 'No files',
  'task.files.error.duplicateSingle': 'A file named "{fileName}" already exists. Please rename it before uploading.',
  'task.files.error.duplicateMultiple': 'These files already exist: {fileNames}. Please rename them before uploading.',
  'task.notes.edit': 'Edit notes for task',
  'task.notes.history': 'Note history',
  'task.notes.none': 'No notes',
  'task.notes.newNote': 'Write a new note',
  'task.note.history': 'Note history',
  'task.noTaskReferenceId': 'No task reference ID',
  'task.overdue': 'Overdue',
  'task.sentiment.none': 'No sentiment available',
  'task.subcategory.none': 'No subcategory available',
  'task.status.percComplete': '% complete',
  'task.priorityAndStatusEdit': 'Edit priority and status',
  'taskcard.button.viewForm': 'View form',
  'task.keywords.internal': 'Internal',
  'task.keywords.customerCreated': 'Customer-created',
  'task.keywords.protected': 'Protected',
  'task.keywords.normal': 'Normal',
  'toolbar.tagomi': 'Tagomi',
  'tagomi.services.searchAll': 'Search all Tagomi services',
  'tagomi.main.services.all': 'All services',
  'tagomi.main.images.all': 'All images',
  'tagomi.main.scripts.all': 'All scripts',
  'tagomi.templates.templateTab': 'Template',
  'tagomi.services.title': 'Services',
  'tagomi.services.desc': 'Services description',
  'tagomi.service.create': 'Service',
  'tagomi.locales.title': 'Locales',
  'tagomi.locales.desc': 'Locales description',
  'tagomi.locale.create': 'Locale',
  'tagomi.templates.title': 'Templates',
  'tagomi.templates.desc': 'Templates description',
  'tagomi.template.create': 'Template',
  'tagomi.service.options.edit': 'Edit service',
  'tagomi.service.options.delete': 'Delete service',
  'tagomi.service.options.templates.create': 'Create template',
  'tagomi.service.options.template.changeLocale': 'Change template locale',
  'tagomi.service.options.template.delete': 'Delete template',
  'tagomi.service.options.template.addDependencies': 'Add dependencies',
  'tagomi.service.options.template.debug': 'Debug service',
  'tagomi.service.create.dialog.title': 'Create service',
  'tagomi.service.create.dialog.serviceName': 'Service name',
  'tagomi.service.create.dialog.orchestratorName': 'Orchestrator name',
  'tagomi.service.edit.dialog.title': 'Edit service:',
  'tagomi.service.edit.dialog.name': 'Service name',
  'tagomi.service.edit.dialog.orchestratorName': 'Orchestrator name',
  'tagomi.template.edit.currentlyEditing.language1': 'Currently editing',
  'tagomi.template.edit.language1': 'Edit content for this language',
  'tagomi.template.editor.compile': 'Compile',
  'tagomi.template.editor.fillInput': 'Fill input',
  'tagomi.template.change.dialog.title': 'Change template locale',
  'tagomi.template.change.dialog.desc': 'Choosing an available locale will change this template language from its original to the new one you select',
  'tagomi.template.change.dialog.selectOrigin': 'Select current template',
  'tagomi.template.change.dialog.selectTarget': 'Select new locale',
  'tagomi.template.change.dialog.noTemplates': 'There are no templates available for this service',
  'tagomi.template.change.dialog.noLocales': 'Either no locale is selected or no unassigned locales available',
  'tagomi.template.delete.dialog.title': 'Delete template from',
  'tagomi.template.delete.dialog.desc': 'Choose a template to delete. Deleted templates will no longer be available for use.',
  'tagomi.template.delete.dialog.selectTemplate': 'Selected template',
  'tagomi.template.editor.title': 'Edit template content',
  'tagomi.template.editor.serviceName': 'Service name:',
  'tagomi.template.editor.localeLabel': 'Locale label:',
  'tagomi.template.dependencies.add.dialog.title': 'Add dependencies',
  'tagomi.template.dependencies.add.dialog.desc': 'Dependencies are other templates or images imported from outside this template for use inside of it',
  'tagomi.template.dependencies.add.dialog.selectOrigin': 'Select template',
  'tagomi.template.dependencies.add.dialog.selectTargets': 'Select dependencies to add',
  'tagomi.template.dependencies.add.dialog.helperText.noTemplateSelected': 'Select a target template before selecting dependencies',
  'tagomi.service.options.template.editDependencies': 'Change dependencies',
  'tagomi.template.dependencies.edit.dialog.title': 'Change dependencies',
  'tagomi.template.dependencies.edit.dialog.desc': 'Modify existing dependencies for this service template',
  'tagomi.template.dependencies.edit.dialog.selectOrigin': 'Select template',
  'tagomi.button.delete.dialog.template': 'Delete',
  'tagomi.template.delete.dialog.noTemplates.helperText': 'No available templates to delete',
  'tagomi.template.create.dialog.title': 'Create new template',
  'tagomi.template.create.dialog.desc': 'A template contains your language-specific pdf content',
  'tagomi.template.create.dialog.service.name': 'Service name',
  'tagomi.template.create.dialog.localeLabel.select': 'Locale label: Associate a language to your template',
  'tagomi.template.create.dialog.noLocales': 'All available locales have already been assigned to other templates',
  'tagomi.service.delete.dialog.title': 'Delete service:',
  'tagomi.service.delete.dialog.desc': 'You are about to delete this service. Its contents will no longer be available for use.',
  'tagomi.service.delete.dialog.button': 'Delete',
  'tagomi.locale.select.alreadyDefined': 'Locale is already defined',
  'tagomi.locale.label.editLocaleValue': 'Edit locale label value',
  'tagomi.image.create': 'Image',
  'tagomi.script.create': 'Script',
  'tagomi.image.options.edit': 'Edit image',
  'tagomi.image.options.delete': 'Delete image',
  'tagomi.script.options.edit': 'Edit script',
  'tagomi.script.options.delete': 'Delete script',
  'tagomi.image.create.dialog.title': 'Create new image',
  'tagomi.image.create.dialog.resourceName': 'image name',
  'tagomi.image.create.dialog.uploadFile': 'Upload image file',
  'tagomi.image.create.dialog.fileSelected': 'File selected',
  'tagomi.image.edit.dialog.title': 'Edit image:',
  'tagomi.image.edit.dialog.resourceName': 'image name',
  'tagomi.image.edit.dialog.uploadFile': 'Upload new image file (optional)',
  'tagomi.image.edit.dialog.fileSelected': 'New file selected',
  'tagomi.image.delete.dialog.title': 'Delete image:',
  'tagomi.image.delete.dialog.desc': 'You are about to delete this image. It will no longer be available for use in templates.',
  'tagomi.image.delete.dialog.button': 'Delete',
  'tagomi.script.create.dialog.title': 'Create new script',
  'tagomi.script.create.dialog.resourceName': 'Script name',
  'tagomi.script.create.dialog.uploadFile': 'Upload script file',
  'tagomi.script.create.dialog.fileSelected': 'File selected',
  'tagomi.script.edit.dialog.title': 'Edit script:',
  'tagomi.script.edit.dialog.resourceName': 'Script name',
  'tagomi.script.edit.dialog.uploadFile': 'Upload new script file (optional)',
  'tagomi.script.edit.dialog.fileSelected': 'New file selected',
  'tagomi.script.delete.dialog.title': 'Delete script:',
  'tagomi.script.delete.dialog.desc': 'You are about to delete this script. It will no longer be available for use in templates.',
  'tagomi.script.delete.dialog.button': 'Delete',
  'tagomi.logos.searchAll': 'Search all logos',
  'tagomi.scripts.searchAll': 'Search all scripts',
  'xui.calendarInput.mask.placeholder.day': 'dd',
  'xui.calendarInput.mask.placeholder.month': 'mm',
  'xui.calendarInput.mask.placeholder.year': 'yyyy',
  'contractsTable.title': 'Contracts',
  'contractTable.col.header.status': 'Status',
  'contractTable.col.header.contractNumber': 'Number',
  'contractTable.col.header.contractType': 'Type',
  'contractTable.col.header.created': 'Created',
  'contractTable.col.header.maturityDate': 'Maturity Date',
  'contractTable.col.header.policyholder': 'Policyholder',
  'contract.composer.contract.edit': 'Edit contract',
  'contractcard.edit': 'Edit',
  'contractcard.product.title': 'Product',
  'contractcard.contractMain.title': 'Contract number: {contractId}',
  'contractcard.contractDetails.title': 'Contract details',
  'contractcard.contractParties.title': 'Contract parties',
  'contractcard.contractPartyDetails.title': 'Contract party details',
  'contractcard.investmentPlans.invPlanAllocations.title': 'Plan allocations',
  'contractcard.paymentPlans.title': 'Payment plans',
  'contractcard.investmentPlans.title': 'Investment plans',
  'contractcard.coverages.title': 'Coverages',
  'contractcard.body.category': 'Category',
  'contractcard.body.status': 'Status',
  'contractcard.body.productName': 'Product name',
  'contractcard.body.productCode': 'Product code',
  'contractcard.body.limits.annualMaxContribution': 'Annual max contribution',
  'contractcard.body.limits.contractMinValue': 'Contract minimum value',
  'contractcard.body.limits.partialWithdrawalMin': 'Partial withdrawl minimum',
  'contractcard.body.issueDate': 'Issue date',
  'contractcard.body.issueDateInterval': 'Issue date interval',
  'contractcard.body.issueDateType': 'Issue date type',
  'contractcard.body.startDate': 'Start date',
  'contractcard.body.startDateInterval': 'Start date interval',
  'contractcard.body.startDateType': 'Start date type',
  'contractcard.body.maturityDate': 'Maturity date',
  'contractcard.body.maturityDateInterval': 'Maturity date interval',
  'contractcard.body.maturityDateType': 'Maturity date type',
  'contractcard.body.transitives.updatedTreeAt': 'Updated tree at',
  'contractcard.body.parties.partyType': 'Party type',
  'contractcard.body.parties.partyFullName': 'Full name',
  'contractcard.body.parties.dateOfBirth': 'Date of birth',
  'contractcard.body.parties.partyPersonalId': 'Personal ID',
  'contractcard.body.parties.investmentExperience': 'Investment experience',
  'contractcard.body.parties.riskTolerance': 'Risk tolerance',
  'contractcard.body.parties.partyAddress.city': 'City',
  'contractcard.body.parties.partyAddress.street': 'Street',
  'contractcard.body.parties.partyAddress.postalCode': 'Postal code',
  'contractcard.body.parties.partyAddress.country': 'Country',
  'contractcard.body.parties.partyTermStartDate': 'Term start date',
  'contractcard.body.parties.partyTermStartDateInterval': 'Term start date interval',
  'contractcard.body.parties.partyTermStartDateType': 'Term start date type',
  'contractcard.body.parties.partyEffectiveFrom': 'Effective from',
  'contractcard.body.parties.partyEffectiveTo': 'Effective to',
  'contractcard.body.parties.partyTermEndDate': 'Term end date',
  'contractcard.body.parties.partyTermEndDateInterval': 'Term end date interval',
  'contractcard.body.parties.partyTermEndDateType': 'Term end date type',
  'contractcard.body.parties.partyCoverages': 'Party covers',
  'contractcard.body.coverages.coverageCode': 'Coverage code',
  'contractcard.body.coverages.coverageType': 'Type',
  'contractcard.body.coverages.coverageStatus': 'Status',
  'contractcard.body.coverages.insuredId': 'Insured party',
  'contractcard.body.coverages.coverageSumInsured': 'Sum insured',
  'contractcard.body.coverages.coverageEffectiveFrom': 'Effective from',
  'contractcard.body.coverages.coverageTermStartDate': 'Term start date',
  'contractcard.body.coverages.coverageTermStartDateType': 'Term start date type',
  'contractcard.body.coverages.coverageTermStartDateInterval': 'Term start date interval',
  'contractcard.body.paymentPlans.partyName': 'Party name',
  'contractcard.body.paymentPlans.paymentPlanFrequency': 'Payment plan frequency',
  'contractcard.body.paymentPlans.paymentPlanAmount': 'Payment amount',
  'contractcard.body.paymentPlans.paymentPlanStatus': 'Status',
  'contractcard.body.paymentPlans.paymentPlanStartDate': 'Start date',
  'contractcard.body.paymentPlans.paymentPlanStartDateInterval': 'Start date interval',
  'contractcard.body.paymentPlans.paymentPlanStartDateType': 'Start date type',
  'contractcard.body.paymentPlans.paymentPlanStartDateIntervalType': 'Start date interval type',
  'contractcard.body.investmentPlans.invPlanName': 'Name',
  'contractcard.body.investmentPlans.invPlanCode': 'Code',
  'contractcard.body.investmentPlans.invPlanStatus': 'Status',
  'contractcard.body.investmentPlans.invPlanStartDate': 'Start date',
  'contractcard.body.investmentPlans.invPlanStartDateInterval': 'Start date interval',
  'contractcard.body.investmentPlans.invPlanStartDateType': 'Start date interval type',
  'contractcard.body.investmentPlans.invPlanEndDate': 'End date',
  'contractcard.body.investmentPlans.invPlanEndDateType': 'End date type',
  'contractcard.body.investmentPlans.invPlanEndDateInterval': 'End date interval',
  'contractcard.body.investmentPlans.invPlanAllocation.allocationCode': 'Code',
  'contractcard.body.investmentPlans.invPlanAllocation.allocationName': 'Name',
  'contractcard.body.investmentPlans.invPlanAllocation.allocationPercentage': 'Percentage',
  'contractcard.body.investmentPlans.invPlanAllocation.allocationStatus': 'Status',
  'contractcard.body.product.description.ruleCode': 'Code',
  'contractcard.body.product.description.ruleText': 'Text',
  'contractcard.product.description.view': 'Product description',
  'contractcard.transitives.createdAt': 'Created',
  'contractcard.transitives.updatedAt': 'Updated',
  'contractcard.transitives.updatedTreeAt': 'Updated tree',
  'contract.status.active': 'Active',
  'ledgersTable.title': 'Ledgers',
  'ledgerTable.col.header.ledgerNumber': 'Ledger number',
  'ledgerTable.col.header.updatedAt': 'Updated',
  'ledgerTable.col.header.lastChangeType': 'Last change type',
  'ledgerTable.col.header.netAddedToAccount': 'Added to account',
  'ledgerTable.col.header.removedFromAccount': 'Removed from account',
  'ledgercard.title.ledgerMain': 'Ledger {ledgerName}',
  'ledgercard.title.ledgerPayments': 'Payments',
  'ledgercard.title.ledgerMoneyRequests': 'Money requests',
  'ledgercard.title.ledgerBlackBooks': 'Account details',
  'ledgercard.ledgerMain.description': 'Description',
  'ledgercard.payment.amount': 'Amount',
  'ledgercard.payment.description': 'Description',
  'ledgercard.payment.date': 'Date',
  'ledgercard.payment.type': 'Type',
  'ledgercard.moneyRequest.description': 'Payment description',
  'ledgercard.moneyRequest.type': 'Type',
  'ledgercard.moneyRequest.targetDate': 'Target date',
  'ledgercard.moneyRequest.amount': 'Amount',
  'ledgercard.blackBook.description': 'Description',
  'ledgercard.blackBook.amount': 'Amount',
  'ledgercard.blackBook.type': 'Type',
  'ledgercard.blackBook.bookDate': 'Created',
  'ledgercard.blackBook.detail.detailType': 'Type',
  'ledgercard.blackBook.detail.detailDescription': 'Description',
  'ledgercard.blackBook.detail.detailAmount': 'Amount',
  'ledgercard.blackBook.detail.inflowAmount': 'Inflow',
  'ledgercard.blackBook.detail.outflowAmount': 'Outflow',
  'ledgercard.blackBook.detail.deltaAmount': 'Delta',
  'ledgercard.blackBook.details.none': 'No details found',
  'ledgercard.blackBook.detail.breakdown': 'Breakdown',
  'ledgercard.blackBook.detail.expander.collapseBreakdown': 'Hide breakdown',
  'ledgercard.blackBook.detail.expander.expandBreakdown': 'View breakdown',
  'ledgercard.transitives.createdAt': 'Created',
  'ledgercard.transitives.updatedAt': 'Updated',
  'cockpitsTable.title': 'Cockpits',
  'cockpit.composer.cockpit.edit': 'Edit Cockpit:',
  'cockpitCreate.dialog.title': 'Create new Cockpit',
  'cockpit.name': 'Name',
  'cockpit.description': 'Description',
  'cockpitcard.wrenchStencil.wrenchConfig.title': 'Wrench assets',
  'cockpitcard.wrenchStencil.stencilConfig.title': 'Stencil assets',
  'cockpitcard.wrenchStencil.wrenchTenantDesc.title': 'Wrench assets description',
  'cockpitcard.wrenchStencil.stencilTenantDesc.title': 'Stencil assets description',
  'cockpitTable.col.header.status': 'Status',
  'cockpitcard.cockpitMain.title': 'Cockpit main',
  'cockpitcard.cockpitWrenchStencilConfig.title': 'Wrench and Stencil Config',
  'cockpit.tenantDescription': 'Tenant description',
  'cockpit.edit': 'Edit',
  'cockpit.status': 'Status',
  'cockpit.status.active': 'Active',
  'cockpit.status.inactive': 'Inactive',
  'cockpit.config.description': 'Config description',
  'cockpit.wrenchConfig': 'Wrench config',
  'cockpit.stencilConfig': 'Stencil config',
  'cockpit.config.name': 'Config name',
  'cockpit.wrenchStencilEdit.title': 'Edit Wrench and Stencil configurations',
  'cockpit.tenantCreate.title': 'Configure Cockpit tenants',
  'cockpit.tenantCreate.description': 'Select a set of Wrench and Stencil assets to use in this tenant',
  'cockpit.tenantCreate.stencilConfig.label': 'Stencil assets',
  'cockpit.tenantCreate.wrenchConfig.label': 'Wrench assets',
  'cockpit.tenantCreate.description.placeholder': 'Enter a short text to give additional info about this tenant',
  'toolbar.files': 'Explorer',
  'task.reference.missing': 'No task reference ID',
  'task.overdue.daysLeft': '{days} day(s) left to complete task',
  'task.overdue.dueToday': 'Task is due today!',
  'task.overdue.closedOverdue': 'Task was closed {days} day(s) overdue',
  'button.view': 'View',
  'taskcard.menu.option.formReview': 'Show form review',
  'taskcard.menu.option.editSection': 'Edit this section',
  'taskcard.menu.option.removeFlashy': 'Remove Flashy',
  'taskcard.menu.option.setFlashy': 'Make Flashy',
  'task.audit.ai.sentiment.unavailable': 'No AI analysis for sentiment and subcategory available',
  'task.audit.ai.similar.unavailable': 'No similar feedback available',
  'taskcard.body.customerName.none': 'Not specified',
  'taskcard.body.form.canPublishFeedback.yes': 'Yes',
  'taskcard.body.form.representative.placeholder': 'Representative name',
  'fs.articleOrder.title': 'Article Order',
  'fs.articleOrder.col.position': 'Position',
  'fs.articleOrder.col.name': 'Name',
  'fs.articleOrder.col.description': 'Description',
  'fs.breadcrumb.tooltip.error': 'An issue with this asset needs attention.',
  'fs.changesView.title': 'Unsaved changes',
  'fs.changesView.undo': 'Undo changes',
  'fs.changesView.discardAll': 'Discard all changes',
  'fs.changesView.saveAll': 'Save all changes',
  'fs.changesView.undoConfirmDialog.title': 'Undo changes to asset',
  'fs.changesView.undoConfirmDialog.content': 'You are about to discard all changes to this file. This action cannot be undone.',
  'fs.configOptions.title': 'Configuration options',
  'fs.configOptions.message.selectDirent': 'Select an item from the file explorer to view config options',
  'fs.configOptions.title.direntName': 'Config options: {direntName}',
  'fs.configOptions.optionKey.devMode.desc': 'Asset appears only in the development environment and will not be published publically in a release.',
  'fs.configOptions.optionKey.disabledMode.disabled': 'Asset is not active and will not appear in production.',
  'fs.configOptions.optionKey.anonymousMode.disabled': 'Service is available for anonymous users (does not require login)',
  'fs.configOptions.optionKey.assignableMode.disabled': 'Service can be assigned to customers',
  'fs.configOptions.optionKey.assignableMode.desc.none': 'No description available for this configuration option.',
  'fs.direntComments.commentField.placeholder': 'Add a comment',
  'fs.direntCreate.nameField.placeholder': 'Asset name',
  'fs.direntCreate.nameField.label': 'Asset name',
  'fs.direntCreate.orderNumberField.placeholder': '100',
  'fs.direntCreate.orderNumberField.label': '3-digit order number',
  'fs.direntCreate.descriptionField.placeholder': 'Description',
  'fs.direntCreate.descriptionField.label': 'Description',
  'fs.direntCreate.labelsField.placeholder': 'Select or add new labels',
  'fs.direntCreate.commentsField.placeholder': 'Notes/comments about this asset',
  'fs.direntCreate.commentsField.label': 'Comments',
  'fs.direntCreate.configOptionsField.label': 'Configuration options',
  'fs.direntCreate.labelsField.label': 'Labels',
  'fs.direntCreate.sectionTitle.createNew': 'Create new asset',
  'fs.direntCreate.sectionTitle.sharing': 'Sharing and permissions',
  'fs.dirent.article.sectionTitle.createNew': 'Create new article',
  'fs.dirent.article.sectionTitle.edit': 'Edit article',
  'fs.dirent.article.sectionTitle.sharing': 'Sharing and permissions',
  'fs.dirent.article.nameField.label': 'Name',
  'fs.dirent.article.nameField.placeholder': 'Enter article name',
  'fs.dirent.article.orderNumberField.label': '3-digit order number',
  'fs.dirent.article.orderNumberField.placeholder': '100',
  'fs.dirent.article.descriptionField.label': 'Description',
  'fs.dirent.article.descriptionField.placeholder': 'Enter article description',
  'fs.dirent.article.configOptionsField.label': 'Configuration options',
  'fs.dirent.article.labelsField.label': 'Labels',
  'fs.dirent.article.labelsField.placeholder': 'Select or add new labels',
  'fs.dirent.article.commentsField.label': 'Comments',
  'fs.dirent.article.commentsField.placeholder': 'Notes/comments about this asset',
  'fs.dirent.article.expandToggle.show': 'More options',
  'fs.dirent.article.expandToggle.hide': 'Fewer options',
  'fs.dirent.article.parentArticleField.label': 'Parent article',
  'fs.dirent.article.parentArticleField.desc': 'This article will be created as a child of the article below. Please note that child articles may be rendered differently on your client-facing application.',
  'fs.dirent.link.sectionTitle.createNew': 'Create new link',
  'fs.dirent.link.sectionTitle.edit': 'Edit link',
  'fs.dirent.link.urlValueField.label': 'URL',
  'fs.dirent.link.urlValueField.placeholder': 'Enter link URL',
  'fs.dirent.link.sectionTitle.localeLabels': 'Labels by language',
  'fs.dirent.link.labelField.en.label': 'Label (English)',
  'fs.dirent.link.labelField.fi.label': 'Label (Finnish)',
  'fs.dirent.link.labelField.sv.label': 'Label (Swedish)',
  'fs.dirent.link.labelField.placeholder': 'Enter label',
  'fs.dirent.link.articlesField.label': 'Articles',
  'fs.dirent.link.configOptionsField.label': 'Configuration options',
  'fs.dirent.link.expandToggle.show': 'More options',
  'fs.dirent.link.expandToggle.hide': 'Fewer options',
  'fs.dirent.phone.sectionTitle.createNew': 'Create new phone number',
  'fs.dirent.phone.sectionTitle.edit': 'Edit phone number',
  'fs.dirent.phone.phoneValueField.label': 'Phone number',
  'fs.dirent.phone.phoneValueField.placeholder': '+358 9 000 0000',
  'fs.dirent.phone.sectionTitle.localeLabels': 'Labels by language',
  'fs.dirent.phone.labelField.en.label': 'Label (English)',
  'fs.dirent.phone.labelField.fi.label': 'Label (Finnish)',
  'fs.dirent.phone.labelField.sv.label': 'Label (Swedish)',
  'fs.dirent.phone.labelField.placeholder': 'Enter label',
  'fs.dirent.phone.articlesField.label': 'Associated articles',
  'fs.dirent.phone.configOptionsField.label': 'Configuration options',
  'fs.dirent.phone.expandToggle.show': 'More options',
  'fs.dirent.phone.expandToggle.hide': 'Fewer options',
  'fs.dirent.folder.sectionTitle.createNew': 'Create new folder',
  'fs.dirent.folder.sectionTitle.edit': 'Edit folder',
  'fs.dirent.folder.locationField.label': 'Location',
  'fs.dirent.folder.locationField.root': 'Root',
  'fs.dirent.folder.locationField.newFolder': 'New folder',
  'fs.dirent.folder.nameField.label': 'Folder name',
  'fs.dirent.folder.nameField.placeholder': 'Enter folder name',
  'fs.dirent.language.sectionTitle.createNew': 'Create new language',
  'fs.dirent.language.sectionTitle.edit': 'Edit language',
  'fs.dirent.language.nameField.placeholder': 'Enter language name',
  'fs.dirent.language.localeCodeField.label': 'Locale code',
  'fs.dirent.language.localeCodeField.placeholder': 'example: en',
  'fs.dirent.language.descriptionField.label': 'Description',
  'fs.dirent.language.descriptionField.placeholder': 'Description of this language',
  'fs.dirent.language.configOptionsField.label': 'Configuration options',
  'fs.dirent.service.sectionTitle.createNew': 'Create new service',
  'fs.dirent.service.sectionTitle.edit': 'Edit service',
  'fs.dirent.service.nameField.label': 'Service name',
  'fs.dirent.service.nameField.placeholder': 'Enter service name',
  'fs.dirent.service.sectionTitle.dialobForm': 'Connect service to Dialob form',
  'fs.dirent.service.dialobFormField.label': 'Form',
  'fs.dirent.service.dialobTagField.label': 'Version tag',
  'fs.dirent.service.flowField.label': 'Flow',
  'fs.dirent.service.sectionTitle.createLocaleLabels': 'Add localised service names',
  'fs.dirent.service.labelField.en.label': 'English label',
  'fs.dirent.service.labelField.fi.label': 'Finnish label',
  'fs.dirent.service.labelField.sv.label': 'Swedish label',
  'fs.dirent.service.labelField.placeholder': 'Display text for this language',
  'fs.dirent.service.expandToggle.show': 'More options',
  'fs.dirent.service.expandToggle.hide': 'Fewer options',
  'fs.dirent.service.validityStartField.label': 'Valid from',
  'fs.dirent.service.validityStartField.placeholder': 'DD.MM.YYYY',
  'fs.dirent.service.validityEndField.label': 'Valid until',
  'fs.dirent.service.validityEndField.placeholder': 'DD.MM.YYYY',
  'fs.dirent.service.articlesField.label': 'Associated articles',
  'fs.dirent.service.configOptionsField.label': 'Configuration options',
  'fs.dirent.page.sectionTitle.createNew': 'Create new page',
  'fs.dirent.page.sectionTitle.edit': 'Edit page',
  'fs.dirent.page.localeCodeField.label': 'Locale code',
  'fs.dirent.page.localeCodeField.placeholder': 'example: en',
  'fs.dirent.page.articleField.label': 'Article',
  'fs.dirent.page.descriptionField.label': 'Description',
  'fs.dirent.page.descriptionField.placeholder': 'Enter page description',
  'fs.dirent.page.parentField.label': 'Location',
  'fs.dirent.page.configOptionsField.label': 'Configuration options',
  'fs.dirent.flow.sectionTitle.createNew': 'Create new flow',
  'fs.dirent.flow.sectionTitle.edit': 'Edit flow',
  'fs.dirent.flow.nameField.label': 'Name',
  'fs.dirent.flow.nameField.placeholder': 'Enter flow name',
  'fs.direntCreate.configOption.devMode.description': 'Development mode: Asset appears only in the development environment for testing and is not included in production releases.',
  'fs.direntCreate.configOption.disabledMode.description': 'Disabled mode: Service does not appear on client-facing application.',
  'fs.direntCreate.configOption.anonymousMode.description': 'Anonymous mode: Asset appears for BOTH anonymous and authenticated users.',
  'fs.direntCreate.configOption.assignableMode.description': 'Assignable mode: Service/Form can be assigned directly to customer.',
  'fs.direntTextField.required': '* Required',
  'fs.direntCreate.printout.sectionTitle.createNew': 'Create new printout service',
  'fs.direntCreate.printout.printoutServiceNameField.label': 'Printout service name',
  'fs.direntCreate.printout.printoutServiceNameField.placeholder': 'Enter printout service name',
  'fs.direntCreate.printout.orchestratorNameField.label': 'Orchestrator',
  'fs.direntCreate.printout.sectionTitle.createLocaleLabels': 'Add localised printout names',
  'fs.direntCreate.printout.labelField.placeholder': 'Display text for this language',
  'fs.direntCreate.printout.labelField.en.label': 'English label',
  'fs.direntCreate.printout.labelField.fi.label': 'Finnish label',
  'fs.direntCreate.printout.labelField.sv.label': 'Swedish label',
  'fs.direntCreate.printout.configOptionsField.label': 'Config options',
  'fs.direntCreate.dialob.sectionTitle.createNew': 'Create new Dialob form',
  'fs.direntCreate.dialob.formNameField.label': 'Form name',
  'fs.direntCreate.dialob.formNameField.placeholder': 'Enter a user-friendly form name',
  'fs.direntCreate.dialob.formTechnicalIdField.label': 'Technical ID',
  'fs.direntCreate.dialob.formTechnicalIdField.placeholder': 'Enter technical ID. This cannot be changed.',
  'fs.direntNew.title': 'New',
  'fs.direntNew.type.folder': 'Folder',
  'fs.direntNew.type.article': 'Article',
  'fs.direntNew.type.service': 'Service',
  'fs.direntNew.type.dialob': 'Dialob',
  'fs.direntNew.type.flow': 'Flow',
  'fs.direntNew.type.link': 'Link',
  'fs.direntNew.type.language': 'Language',
  'fs.direntNew.type.printout': 'Printout',
  'fs.direntNew.type.image': 'Image',
  'fs.direntNew.type.template': 'Template',
  'fs.direntNew.type.phone': 'Phone number',
  'fs.direntNew.type.page': 'Page',
  'fs.tabs.new.folder': 'New folder',
  'fs.tabs.new.article': 'New article',
  'fs.tabs.new.service': 'New service',
  'fs.tabs.new.dialob': 'New dialob',
  'fs.tabs.new.flow': 'New flow',
  'fs.tabs.new.link': 'New link',
  'fs.tabs.new.language': 'New language',
  'fs.tabs.new.printout': 'New printout',
  'fs.tabs.new.image': 'New image',
  'fs.tabs.new.template': 'New template',
  'fs.tabs.new.page': 'New page',
  'fs.direntRename.title': 'Rename',
  'fs.direntHistory.title': 'Recent changes to this item',
  'fs.direntHistory.tableHeader.user': 'User',
  'fs.direntHistory.tableHeader.change': 'Change',
  'fs.direntHistory.tableHeader.date': 'Date',
  'fs.direntLabels.labelsField.placeholder': 'Add labels...',
  'fs.direntMenu.header.lastEdited': 'Last edited: {updated} by {user}',
  'fs.direntMenu.menuItem.new': 'New',
  'fs.direntMenu.menuItem.edit': 'Edit',
  'fs.direntMenu.menuItem.lock': 'Lock',
  'fs.direntMenu.menuItem.unlock': 'Unlock',
  'fs.direntMenu.menuItem.copy': 'Copy',
  'fs.direntMenu.menuItem.rename': 'Rename',
  'fs.direntMenu.menuItem.delete': 'Delete',
  'fs.direntMenu.menuItem.configOptions': 'Configuration Options',
  'fs.direntMenu.chip.devMode': 'Development',
  'fs.direntMenu.chip.assignable': 'Assignable',
  'fs.direntMenu.chip.disabled': 'Disabled',
  'fs.direntMenu.chip.anonymous': 'Anonymous',
  'fs.direntMenu.menuItem.labels': 'Labels',
  'fs.direntMenu.menuItem.comments': 'Comments ({count})',
  'fs.direntMenu.menuItem.sharing': 'Sharing and Permissions',
  'fs.direntMenu.menuItem.history': 'History',
  'fs.direntMenu.menuItem.references': 'References ({count})',
  'fs.tabMenu.menuItem.close': 'Close',
  'fs.tabMenu.menuItem.closeToTheRight': 'Close all to the right',
  'fs.tabMenu.menuItem.closeAll': 'Close all',
  'fs.direntPermissions.message.readWrite': 'You can read and write',
  'fs.direntPermissionType.read': 'Read',
  'fs.direntPermissionType.write': 'Write',
  'fs.direntPermissionType.view': 'View',
  'fs.direntPermissionType.none': 'None',
  'fs.direntPermissions.tableHeader.name': 'Name',
  'fs.direntPermissions.tableHeader.privilege': 'Privilege',
  'fs.direntReferences.title.referenced': 'This asset is referenced in {count} location(s)',
  'fs.direntReferences.title.notReferenced': 'This asset is not referenced anywhere',
  'fs.direntReferences.tableHeader.asset': 'Asset',
  'fs.direntReferences.tableHeader.location': 'Location',
  'fs.errors.title': 'Errors',
  'fs.errors.title.direntName': 'Errors: {direntName}',
  'fs.errors.message.selectDirent': 'Select a dirent from the tree to view errors.',
  'fs.errors.message.noErrors': 'No errors found for this dirent.',
  'fs.errors.sectionTitle.summary': 'Error Summary',
  'fs.errors.statLabel.errors': 'Errors',
  'fs.errors.statLabel.warnings': 'Warnings',
  'fs.explorer.title': 'File System Composer',
  'fs.explorer.tooltip.toggleSearch': 'Toggle search',
  'fs.explorer.tooltip.newFile': 'New file',
  'fs.explorer.tooltip.newFolder': 'New folder',
  'fs.explorer.tooltip.collapseAll': 'Collapse all',
  'fs.explorer.tooltip.toggleTheme': 'Toggle light/dark mode',
  'fs.explorer.message.noResults': 'No results found',
  'fs.history.title': 'History',
  'fs.history.message.selectDirent': 'Select a dirent from the tree to view history.',
  'fs.history.title.direntName': 'History: {direntName}',
  'fs.history.sectionTitle.recentChanges': 'Recent changes to this item',
  'fs.history.message.noHistory': 'No history available for this dirent.',
  'fs.changeType.update': 'Updated',
  'fs.changeType.create': 'Created',
  'fs.changeType.delete': 'Deleted',
  'fs.main.message.noAssetSelected': 'No asset selected',
  'fs.main.chooseView.title': 'Choose a View',
  'fs.main.chooseView.message': 'Select an option from the toolbar to view details.',
  'fs.main.message.mainContent': 'Main content',
  'fs.main.tooltip.articleOrder': 'Article Order',
  'fs.main.tooltip.togglePanelCollapse': 'Collapse Panel',
  'fs.main.tooltip.togglePanelExpand': 'Expand Panel',
  'fs.main.tooltip.properties': 'Properties',
  'fs.main.tooltip.configuration': 'Configuration',
  'fs.main.tooltip.references': 'References',
  'fs.main.tooltip.debug': 'Debug',
  'fs.main.tooltip.errors': 'Errors',
  'fs.main.tooltip.preview': 'Preview',
  'fs.main.tooltip.history': 'History',
  'fs.main.tooltip.help': 'Help',
  'fs.main.tooltip.changes': 'Save',
  'fs.panel.message.selectDirent': 'Select a dirent from the tree to view details.',
  'fs.properties.title': 'Properties',
  'fs.properties.message.selectDirent': 'Select a dirent from the tree to view properties.',
  'fs.properties.title.direntName': 'Properties: {direntName}',
  'fs.properties.propertyLabel.pageLocales': 'Page Locales',
  'fs.properties.propertyLabel.labels': 'Labels',
  'fs.properties.tagLabel.label': 'label',
  'fs.properties.propertyLabel.serviceName': 'Service Name',
  'fs.properties.propertyLabel.serviceLocales': 'Service Locales',
  'fs.properties.propertyLabel.serviceValidityStart': 'Service Validity Start',
  'fs.properties.propertyLabel.serviceValidityEnd': 'Service Validity End',
  'fs.properties.propertyLabel.serviceValidityPeriod': 'Service Validity Period',
  'fs.properties.propertyLabel.dialobFormName': 'Dialob Form Name',
  'fs.properties.propertyLabel.dialobFormTag': 'Dialob Form Tag',
  'fs.properties.propertyLabel.flowName': 'Flow Name',
  'fs.properties.propertyLabel.configOptionsEnabled': 'Config Options Enabled',
  'fs.properties.propertyLabel.selectedArticles': 'Selected Articles',
  'fs.properties.propertyLabel.comments': 'Comments',
  'fs.properties.propertyLabel.locales': 'Locales',
  'fs.properties.propertyLabel.localeCode': 'Locale Code',
  'fs.properties.propertyLabel.phoneValue': 'Phone Number',
  'fs.properties.propertyLabel.urlValue': 'URL',
  'fs.properties.propertyLabel.formName': 'Form Name',
  'fs.properties.propertyLabel.formTechnicalId': 'Technical ID',
  'fs.properties.propertyLabel.versionTag': 'Version Tag',
  'fs.properties.propertyLabel.printoutServiceName': 'Printout Service Name',
  'fs.properties.propertyLabel.orchestratorName': 'Orchestrator Name',
  'fs.properties.propertyLabel.children': 'Children',
  'fs.references.title': 'References',
  'fs.references.message.selectDirent': 'Select a dirent from the tree to view references.',
  'fs.references.title.direntName': 'References: {direntName}',
  'fs.references.sectionTitle.childReferences': 'Child References',
  'fs.references.label.type': 'Type: {childType}',
  'fs.references.label.refMarker': '(REF)',
  'fs.references.message.noReferences': 'This dirent does not contain any references.',
  'fs.search.searchField.placeholder': 'Search',
  'fs.search.filterSelect.placeholder': 'Filter by type'
}