export const en = {
  'document.title': 'DigiExpress',
  'eveli.textSeparatorColon': ':',
  'eveli.noValueIndicator': '--',
  'eveli.permissions.none.title': 'Oops!',
  'eveli.permissions.none.desc1': 'You don\'t have the correct access rights to use this application.',
  'eveli.permissions.none.desc2': 'Please contact your system administrator.',
  'tasksView.title': 'Tasks',
  'taskDialog.priority': 'Priority',
  'taskDialog.subject': 'Subject',
  'taskDialog.dueDate': 'Due date',
  'taskDialog.assignedTo': 'User role',
  'taskDialog.assignedUser': 'User',
  'taskDialog.status': 'Status',
  'taskDialog.task': 'Task',
  'taskDialog.category': 'Type',
  'taskDialog.source': 'Source',
  'taskDialog.additionalInfo': 'Additional information',
  'task.assignable.dialog.title': 'Manage assigned forms',
  'task.assignable.new': 'Assign new forms',
  'task.assignable.desc': 'will be assigned the selected forms in the chosen language.',
  'task.assignable.locale': 'Language',
  'task.assignable.forms': 'Forms',
  'task.assignable.cancel': 'Cancel assigned forms',
  'task.assignable.cancel.desc': 'Assigned forms cannot be cancelled after the customer has completed them!',
  'task.assignable.selectForms': 'Select forms',
  'task.assignable.cancel.formsList.desc': 'The following form(s) will be cancelled!',
  'button.cancelSelected': 'Cancel selected forms ({count})',
  'button.acceptSelected': 'Assigned selected forms ({count})',
  'task.priority.low': 'Low',
  'task.priority.normal': 'Normal',
  'task.priority.high': 'High',
  'task.dueDate': 'Due date',
  'task.customerMessages': 'Customer messages',
  'task.edit': 'Edit task',
  'task.customerName': 'Customer name',
  'task.subject': 'Subject',
  'task.additionalInfo': 'Additional info',
  'task.metaData': 'Metadata',
  'task.status.new': 'New',
  'task.status.open': 'Open',
  'task.status.completed': 'Completed',
  'task.status.rejected': 'No processing',
  'task.status.transferred': 'Transferred',
  'task.status.delegated': 'Delegated',
  'task.status.waiting': 'Waiting',
  'task.pdf.options.select.CUSTOMER_NAME': 'Customer name',
  'task.pdf.options.select.CUSTOMER_SSN': 'Customer SSN',
  'task.pdf.options.select.EXTERNAL_COMMENTS': 'Customer messages',
  'task.pdf.options.select': 'PDF Printing options',
  'task.pdf.print': 'Print PDF',
  'task.pdf.options.select.desc': 'Select addition data tobe included to generated pdf document',
  'task.form.review': 'View form',
  'task.created': 'Created',
  'task.updated': 'Updated',
  'task.comments.external.createTask': 'Create task before adding external comments',
  'task.comments.internal.createTask': 'Create task before adding internal comments',
  'task.attachments.createTask': 'Create task before uploading attachments',
  'task.comments.external.added': 'Internal comment added',
  'task.feedback.publishedSaved': 'Feedback changes saved',
  'internalComments': 'Internal comments',
  'externalComments': 'Client messages',
  'comment.store': 'Save',
  'comment.add': 'Add comment',
  'comment.addInternal': 'Add internal comment',
  'comment.addExternal': 'Message to client',
  'taskButton.addTask': 'Add task',
  'taskButton.refresh': 'Check for new tasks',
  'taskButton.accept': 'Accept',
  'taskButton.cancel': 'Close',
  'table.body.emptyDataSourceMessage': 'No data',
  'table.body.filterRow.filterTooltip': 'Filter',
  'table.body.deleteTooltip': 'Delete',
  'table.header.actions': 'Actions',
  'table.pagination.labelDisplayedRows': '{from}-{to} of {count}',
  'table.pagination.labelRowsPerPage': 'Rows per page:',
  'table.pagination.firstPage': 'First page',
  'table.pagination.previousPage': 'Previous page',
  'table.pagination.nextPage': 'Next page',
  'table.pagination.lastPage': 'Last page',
  'table.toolbar.search': 'Search',
  'table.toolbar.showColumnsTitle': 'Show columns',
  'table.toolbar.addRemoveColumns': 'Add or remove columns',
  'taskLink.pdf.open': 'PDF',
  'explorer.login': 'Log in',
  'locale.fi': 'Suomi',
  'locale.sv': 'Svenska',
  'locale.en': 'English',
  'main.articles.all': 'All Articles',
  'main.links.all': 'All Links',
  'main.services.all': 'All Services',
  'main.flows.all': 'All Service Flows',
  'main.debug': 'Debug',
  'main.decisions.all': 'All Decisions Tables',
  'menu.dashboard': 'Dashboard',
  'menu.profile': 'Profile',
  'menu.tasks': 'Tasks',
  'menu.forms': 'Dialob',
  'menu.queues': 'Queues',
  'menu.help': 'Help',
  'menu.processes': 'Monitoring',
  'menu.logout': 'Log out',
  'menu.publications': 'Publications',
  'menu.services': 'Services',
  'menu.feedback': 'Feedback',
  'menu.compose': 'Compose',
  'menu.articles': 'Articles',
  'menu.links': 'Links',
  'menu.locales': 'Languages',
  'menu.templates': 'Templates',
  'menu.flows': 'Service Flows',
  'menu.decisions': 'Decision tables',
  'menu.debug': 'Debug',
  'menu.releases': 'Releases',
  'menu.compare': 'Compare',
  'profile.user.name': 'Name:',
  'profile.user.email': 'e-mail:',
  'profile.user.role': 'Role:',
  'button.cancel': 'Cancel',
  'button.confirmDelete': 'Delete',
  'button.delete': 'Delete this feedback',
  'button.delete.template': 'Delete this template',
  'button.delete.link': 'Delete this link',
  'button.delete.article': 'Delete this article',
  'button.delete.page': 'Delete this page',
  'button.update': 'Update',
  'button.publish': 'Publish',
  'button.accept': 'Accept',
  'button.close': 'Close',
  'button.save': 'Save',
  'button.dismiss': 'Dismiss',
  'button.select': 'Select',
  'button.startBatch': 'Start batch',
  'error.minTextLength': 'Value should be at least {minLength} characters long',
  'error.maxTextLength': 'Value should be no more than {max} characters long',
  'error.valueRequired': '* Value required',
  'error.title': 'Error!',
  'error.dialob.session': 'Questionnaire cannot be opened at this moment, please try again later',
  'error.errorLoadingData': 'Error during data loading',
  'error.unauthorized.title': 'Missing access role',
  'error.unauthorized.text': 'Contact your system administrator to check your role',
  'error.unauthorizedAccess': 'Missing access role',
  'error.dataAccess': 'Error during data loading',
  'error.statusOpenError': 'Required when status is open',
  'error.workflowCreation': 'Error on workflow creation, check worflow name for duplicates',
  'table.body.editRow.deleteMessage': 'Are you sure you want to delete this?',
  'workflowTable.title': 'Stencil Services',
  'workflowTableHeader.name': 'Name',
  'workflowTableHeader.formName': 'Form',
  'workflowTableHeader.flowName': 'Flow',
  'workflowTableHeader.updated': 'Updated',
  'workflowTable.editButton': 'Edit workflow',
  'workflow.dialogTitle': 'Stencil service',
  'workflow.name': 'Name',
  'workflow.form.formName': 'Form name',
  'workflow.form.formTag': 'Form tag',
  'workflow.flowName': 'Flow name',
  'processTable.title': 'Stencil service execution history',
  'processTableHeader.workflow': 'Stencil service name',
  'processTableHeader.status': 'Status',
  'processTableHeader.created': 'Created',
  'processTableHeader.questionnaireId': 'Questionnaire',
  'processTableHeader.taskRef': 'Task reference',
  'process.status.ANSWERED': 'Answered',
  'process.status.CREATED': 'Created',
  'process.status.ANSWERING': 'Answering',
  'process.status.IN_PROGRESS': 'In progress',
  'process.status.WAITING': 'Waiting',
  'process.status.COMPLETED': 'Completed',
  'process.status.REJECTED': 'Rejected',
  'spoTasksTableHeader.taskName': 'Name',
  'spoTasksTableHeader.status': 'Status',
  'spoTasksTableHeader.priority': 'Priority',
  'spoTasksTableHeader.dueDate': 'Due',
  'spoTasksTableHeader.assigned': 'Role',
  'spoTasksTableHeader.assignedUser': 'Handler',
  'spoTasksTableHeader.created': 'Created',
  'spoTasksTableHeader.clientName': 'Client',
  'spoTasksTableHeader.additionalInfo': 'Info',
  'taskDialog.clientIdentificator': 'Client name',
  'Manual': 'Manual',
  'Protected': 'Protected',
  'Normal': 'Normal',
  'CustomerCreated': 'Customer created',
  'Internal': 'Internal',
  'task.role.assignedAllUsers': 'All users',
  'task.feedback.published': 'Published reply',
  'confirm.close.title': 'Confirmation required',
  'confirm.unsavedChanges': 'Unsaved changes will be lost, do you want to continue?',
  'task.statistics.statusCount': 'By status',
  'task.statistics.priorityCount': 'By priority',
  'task.statistics.daily': 'Daily',
  'task.statistics.overdue': 'Overdue',
  'task.statistics.new_task_by_role': 'New task per user role',
  'task.statistics.task_by_questionnaire': 'Task per form name',
  'task.statistics.open_task_by_role': 'Open tasks per user role',
  'feedback.create.title': 'Create public reply to customer feedback',
  'feedback.update.title': 'Edit public reply to customer feedback',
  'feedback.taskReferenceId': 'Task Reference ID',
  'feedback.taskReferenceId.short': 'Task Ref',
  'feedback.mainCategory': 'Subject',
  'feedback.subCategory': 'Specific topic area',
  'feedback.feedbackValue': 'Customer feedback',
  'feedback.customerTitle': 'Feedback title',
  'feedback.myReply': 'Reply to customer',
  'feedback.customerApprovals': 'Customer approvals',
  'feedback.createdBy': 'Created by',
  'feedback.updatedBy': 'Updated by',
  'feedback.updated': 'Last updated',
  'feedback.notPublished': 'This feedback is not published',
  'feedback.isPublished': 'This feedback is published and publicly viewable',
  'feedback.delete.confirmTitle': 'Delete Feedback?',
  'feedback.delete.confirmText': 'Are you sure you want to delete this feedback?',
  'feedback.main_topic.employmentimmigration': 'Employment immigration',
  'feedback.main_topic.youthservice': 'Youth service',
  'feedback.main_topic.freetimeculture': 'Free time culture',
  'feedback.main_topic.cityconstruction': 'City construction',
  'feedback.main_topic.exercise': 'Exercise',
  'feedback.main_topic.communication': 'Communication',
  'feedback.sub_topic.otherfeedback': 'Other feedback',
  'feedback.sub_topic.familywithchildren': 'Family with children',
  'feedback.sub_topic.libraryservices': 'Library services',
  'feedback.sub_topic.streetmaintservices': 'Street maintenance services',
  'feedback.sub_topic.exercise': 'Exercise',
  'feedback.sub_topic.brand': 'Brand',
  'help.title': 'Help',
  'attachmentView.title': 'Attachments',
  'attachmentTableHeader.size': 'Size',
  'attachmentTableHeader.created': 'Created',
  'attachmentTableHeader.name': 'Subject',
  'attachmentButton.addAttachment': 'Add file',
  'attachmentButton.downloadAttachment': 'Download file',
  'attachmentButton.deleteAttachment': 'Delete file',
  'attachment.uploadOk': 'File {fileName} uploaded',
  'attachment.uploadFailed': 'File {fileName} upload failed!',
  'attachment.delete.confirmTitle': 'Delete file?',
  'attachment.delete.confirmText': 'Are you sure you want to delete the file {fileName}?',
  'attachment.deleteFailed': 'File {fileName} delete failed!',
  'publicationsTable.title': 'Publications',
  'publicationsTableHeader.name': 'Release name',
  'publicationsTableHeader.description': 'Description',
  'publicationsTableHeader.createdBy': 'User',
  'publicationsTableHeader.created': 'Created',
  'publicationsTableHeader.liveDate': 'Live date',
  'publicationsTable.addButton': 'Add',
  'publicationsTable.exportButton': 'Export',
  'publicationsTable.uploadButton': 'Upload',
  'publications.external': 'This is externally configured deployment and will be in effect when there are no other deployments',
  'publications.changeStatus': 'Modify deployment status',
  'publications.currentStatus': 'Current status of deployment',
  'publications.remove': 'Remove deployment',
  'publications.deploy': 'Deploy now',
  'publications.dialogTitle': 'Create new Publication',
  'publications.name': 'Release name',
  'publications.description': 'Description',
  'publications.workflowTag': 'Workflow tag',
  'publications.wrenchTag': 'theWrench tag',
  'publications.contentTag': 'Content tag',
  'publications.createNewTag': 'Create new tag \"{tag}\"',
  'publications.downloadFailed': 'Release download failed, cause: {cause}',
  'publications.tagCreationFailed': 'Release creation failed, cause: {cause}',
  'publications.uploadDialogTitle': 'Upload publication',
  'dialobForm.saveFailed': 'Saving failed',
  'dialobForm.downloadFailed': 'Saving failed',
  'dialobForm.deleteFailed': 'Remove failed',
  'dialobForm.review.title': 'Form review',
  'feedback.notenabled': 'Feedback is not enabled for this task',
  'pages': 'Pages',
  'articles': 'Articles',
  'locale': 'Locale',
  'locales': 'Site Languages',
  'links': 'Links',
  'releases': 'Releases',
  'options': 'Options',
  'value': 'Value',
  'date': 'Date',
  'description': 'Description',
  'name': 'Name',
  'download': 'Download JSON',
  'status': 'Status',
  'created': 'Created',
  'remove': 'Remove',
  'site.content.empty': 'Site has no content! Create content before making a release!',
  'composer.select.article': 'Select Article',
  'search.field.placeholder': 'Enter search keyword',
  'search.results.title': 'Search results',
  'search.field.label': 'Search',
  'search.all': 'All',
  'search.articles': 'Articles',
  'search.services': 'Services',
  'search.links': 'Links',
  'search.templates': 'Templates',
  'search.flows': 'Flows',
  'search.decisions': 'Decisions',
  'activities.article.title': 'Article',
  'activities.article.desc': 'An Article is like a category: It groups Pages, Links, and Services together under one roof.',
  'activities.locale.title': 'Locale',
  'activities.locale.desc': 'Locales are your languages: Add, activate, and deactivate sitewide locales here. You can add a Page in a specific language if you have defined a locale for that page.',
  'activities.page.title': 'Page',
  'activities.page.desc': 'A Page is one content file within an Article. It represents one language and any links / workflows that are associated with an Article. It is written using Markdown syntax.',
  'activities.link.title': 'Hyperlink',
  'activities.link.desc': 'A Hyperlink will connect users to webpages you own, webpages of other organisations, and your telephone numbers.',
  'activities.release.title': 'Release',
  'activities.release.desc': 'A Release is a snapshot of all site content at one certain point of time. Use this for testing, prouduction, or backup purposes.',
  'activities.migration.title': 'Migration',
  'migration.create': 'Migrate data',
  'activities.migration.desc': 'Use a JSON file to perform a migration of a site.',
  'activities.templates.title': 'Templates',
  'activities.templates.desc': 'Use templates to customise and standardise a page default Markdown content and/or structure. Templates can be applied to new pages upon creation. Not implemented yet!',
  'activities.version.composer': 'Composer: build version {version}, build date {date}',
  'activities.version.core': 'Core: build version {version}, build date {date}',
  'dialog.about.title': 'About',
  'dialog.about.preamble': 'DigiExpress is based on open source project',
  'dialog.about.trademark': 'DigiExpress trademark and logo copyright-reserved by ReSys OÜ',
  'templates': 'Templates',
  'template.name': 'Name',
  'template.name.desc': 'User-given name for this template',
  'template.create': 'Create template',
  'template.edit': 'Edit Template',
  'template.type': 'Template type',
  'template.page': 'Page template',
  'template.page.desc': 'This template can be applied to a new page upon creation of that page.',
  'template.description': 'Write templates in Markdown to apply to your pages and content. Templates help speed up your development and unify your content structure.',
  'template.desc': 'Description',
  'template.description.desc': 'Additional information to help identify the use cases of this template',
  'template.delete': 'Delete template',
  'template.delete.message': 'This template will be permanently removed from the application',
  'template.newpage.none': 'None',
  'templates.templatesview.description': 'A new Page can be created from a Template',
  'templates.intro': 'Remember to use a Markdown Level 1 Heading (# My Heading 1) when composing your templates.',
  'services': 'Services',
  'services.create': 'Create service',
  'services.desc': 'Connect your forms and other integrations to your content with the Wrench and Dialob workflows',
  'services.add': 'Add a service',
  'services.change': 'Change existing services',
  'services.edit': 'Edit service',
  'services.technicalname': 'User given unique service name',
  'services.selected': 'Selected services',
  'services.modeselect.title': 'Configuration options',
  'services.modeselect.label': 'Select',
  'services.devmode.helper': 'Development mode: Service appears only in the development environment for testing and is not included in production releases.',
  'services.devmode.label': 'Development mode',
  'services.devmode.tooltip': 'Development mode',
  'services.disabledmode.label': 'Disabled mode',
  'services.disabledmode.helper': 'Disabled mode: Service does not appear on client portal',
  'services.disabledmode.tooltip': 'Disabled mode',
  'services.assignableMode.label': 'Assignable mode',
  'services.assignableMode.helper': 'Assignable mode: Can be assigned directly to customer',
  'services.assignableMode.tooltip': 'Assignable mode',
  'services.none.label': 'No configuration selected',
  'services.none.helper': 'Default mode: Service appears in production, is available ONLY to authenticated users, and is connected to ALL ARTICLES if no Article is selected',
  'services.none.tooltip': 'No special configuration',
  'services.anonmode.helper': 'Anonymous mode: Service appears for BOTH anonymous and authenticated users.',
  'services.anonmode.label': 'Anonymous mode',
  'services.anonmode.tooltip': 'Anonymous mode',
  'services.flowName': 'Flow name',
  'services.formName': 'Dialob form name',
  'services.formName.description': 'Name of Dialob form used in service',
  'services.formTag': 'Dialob form tag',
  'services.formTag.description': 'Tag name for Dialob form used in service',
  'services.startdate': 'Start date and time',
  'services.startdate.description': 'Service activation date and time',
  'services.enddate': 'End date and time',
  'services.enddate.description': 'Service activation ending date and time',
  'services.delete': 'Delete service',
  'services.delete.desc': 'Deleting this service will permanently remove it from the application, and all associations with Articles/Pages will be lost.',
  'snack.article.createdMessage': 'Article created successfully',
  'snack.article.deletedMessage': 'Article deleted',
  'snack.article.editedMessage': 'Article changes saved',
  'snack.page.createdMessage': 'Page created successfully',
  'snack.page.deletedMessage': 'Page deleted',
  'snack.page.savedMessage': 'Page changes saved',
  'snack.page.missingTitle': 'Please add a title to {locale} in {articleName}',
  'snack.link.createdMessage': 'Link created successfully',
  'snack.link.deletedMessage': 'Link deleted',
  'snack.link.editedMessage': 'Link changes saved',
  'snack.workflow.createdMessage': 'Service created successfully',
  'snack.workflow.deletedMessage': 'Service deleted',
  'snack.workflow.editedMessage': 'Service changes saved',
  'snack.locale.createdMessage': 'Locale created successfully',
  'snack.locale.enabled': 'Locale enabled',
  'snack.locale.disabled': 'Locale disabled',
  'snack.template.createdMessage': 'Template created successfully',
  'snack.template.deletedMessage': 'Template deleted',
  'snack.template.editedMessage': 'Template changes saved',
  'snack.release.createdMessage': 'Release created successfully',
  'snack.release.deletedMessage': 'Release deleted',
  'snack.migration.createdMessage': 'Site data updated',
  'toolbar.save': 'Save',
  'toolbar.stencil': 'theStencil',
  'toolbar.wrench': 'theWrench',
  'toolbar.menu': 'Menu',
  'toolbar.help': 'Help',
  'toolbar.import': 'Import data',
  'toolbar.tasks': 'Tasks',
  'toolbar.about': 'About',
  'stencil.services.found.none': 'No services found',
  'link.type.internal': 'Internal',
  'link.type.external': 'External',
  'link.type.phone': 'Phone number',
  'link.search.title': 'Search links by value',
  'link.value': 'Link value',
  'sitelocale.label.select.alreadyDefined': 'Cannot add because this locale is already defined',
  'sitelocale.label.table.editLocaleValue': 'Edit locale value',
  'locales.label.table.title': 'Locale labels',
  'locales.label.title.helper': 'At least one language code (locale) + locale label value is required',
  'locales.label.table.value': 'Translated text value',
  'locales.label.table.noneSet': 'No translated labels!',
  'locales.enabledMessage': 'Enabled: Content for this locale will be displayed on the portal side',
  'locales.disabledMessage': 'Disabled: Content for this locale will be hidden from the portal side. Content can still be edited.',
  'transferlist.noItemsSelected': 'No items selected',
  'transferlist.search': 'Search',
  'transferlist.noSearchResults': 'No search results found',
  'explorer.tabs.links': 'Links',
  'explorer.tabs.services': 'Services',
  'imports.select': 'Select a file to import',
  'imports.import.action': 'Import selected',
  'article.order': 'Article order number',
  'article.order.view': 'View current Article ordering hierarchy',
  'article.select': 'Select Articles',
  'article.links.selectedlinks': 'Selected links',
  'article.composer.title': 'Create new Article',
  'article.composer.parent': 'Parent Article',
  'article.parent.helper': 'If a Parent article is selected, this article will live inside this parent, like a file inside a folder does.',
  'article.composer.parent.unselected': 'No parent article',
  'article.create': 'Create article',
  'article.name': 'Article name',
  'article.delete.title': 'Delete article',
  'article.delete.description': 'Deleting this article will remove it and its associated pages globally from the application.',
  'article.edit.title': 'Edit article',
  'article.edit.parent': 'Parent article',
  'article.devmode.helper': 'If Development mode is active, this article will only appear in the development environment for testing. It will not be included in production releases.',
  'article.devmode': 'Development mode',
  'articleservices': 'Article services: {name}',
  'articlelinks': 'Article links: {name}',
  'article.composer.orderhelper': 'The lower the number, the higher up this article will appear in your portal UI Topic Menu.  Example: 000 will be the first Topic menu item, while 999 will be the last.',
  'article.timestamps.title': 'Additional info',
  'button.create': 'Create',
  'button.add': 'Add',
  'button.disable': 'Continue and disable',
  'button.enable': 'Continue and enable',
  'button.apply': 'Apply changes',
  'button.view.all.locales': 'View locales',
  'button.view.all.releases': 'View releases',
  'button.view.all.templates': 'View templates',
  'links.searchAll': 'Search all links',
  'link.article.select': 'Select Article',
  'link.type': 'Type',
  'link.content': 'Link URL / path',
  'link.composer.title': 'Create a new link',
  'link.composer.valuehelper': 'URL / path of link (http://www.example.com)',
  'link.edit.title': 'Edit link',
  'link.delete.title': 'Delete link',
  'link.delete': 'Deleting this link will permanently remove it from the application, and all associations with Articles/Pages will be lost.',
  'resource.edit.links': 'Edit links',
  'links.change': 'Change existing links',
  'link.create': 'Create new link',
  'link.devmode.helper': 'If Development mode is active, this link will only appear in the development environment for testing. It will not be included in production releases.',
  'link.devmode': 'Development mode',
  'locale.create': 'Create locale',
  'locale.disable.title': 'Disable this locale?',
  'locale.enable.title': 'Enable this locale?',
  'locale.disable': 'Any Pages using this locale will be hidden on the UI. Pages can still be edited.',
  'locale.enable': 'All Pages using this locale will be displayed on the UI.',
  'locale.composer.title': 'Create a new locale',
  'locale.composer.placeholder': 'Two-letter language code',
  'locale.composer.helper': 'Two-letter language codes designate the content language. Common examples: en = English, fi = Finnish, sv = Swedish',
  'locale.overview': 'Locale usage overview',
  'locales.overview.description': 'Manage the languages of your site content. Disable locales to hide all content associated with that language from your site',
  'locales.content': 'Page in this locale has content',
  'locales.nocontent': 'Page in this locale has no content',
  'locales.nopage': 'There is no page for this locale in this Article',
  'locales.label.table.locale': 'Language code',
  'newpage.title': 'Create a new page',
  'newpage.info': 'A page consists of localised content and must be associated with an Article.',
  'newpage.article.info': 'Confirm creation of page for: {article} with locale: {locale}',
  'page.create': 'Create page',
  'page.delete.dialog.title': 'Delete a page from article',
  'page.delete.description': 'The selected page and all of its content will be permanently removed from your site',
  'pages.add': 'Add a page',
  'pages.change': 'Change a page locale',
  'pages.select.locale': 'Edit localised page content',
  'pages.select.locale.edit.desc': 'Select two languages to enable side-by-side editing in one tab.',
  'pages.edit.language1': 'Edit this language',
  'pages.edit.language2': 'Edit this language side-by-side',
  'pages.edit.currentlyEditing.language2': 'Editing side-by-side',
  'pages.edit.currentlyEditing.language1': 'Editing this language',
  'pages.change.info': 'Select a page from this Article and enter a new value for its locale.',
  'pages.change.devmode': 'Change a page development mode',
  'pages.change.devmode.info': 'Select a page from this Article and change its development mode.',
  'pages.devmode.helper': 'If Development mode is active, this page will only appear in the development environment for testing. It will not be included in production releases.',
  'pages.devmode': 'Development mode',
  'pages.delete': 'Delete a page',
  'pages.edit.selectpage': 'Select page',
  'pages.edit.selectTargetLocale': 'Select target locale',
  'release.create': 'Create release',
  'release.composer.title': 'Create a new release',
  'release.composer.label': 'Tag Name',
  'release.composer.note': 'Note',
  'release.composer.helper': 'Optional additional information for future reference',
  'release.desc': 'View all releases and download all site content in JSON format. For more detailed information on specific releases and their content, view the Graph.',
  'release.delete.title': 'Delete release',
  'release.delete.desc': 'Delete this release permanently from site data?',
  'releases.view.note': 'Notes',
  'releases.view.tag': 'Name',
  'releases.view.created': 'Created',
  'releases.view.download': 'JSON download',
  'buttons.create': 'Create',
  'buttons.apply': 'Apply',
  'buttons.delete': 'Delete',
  'buttons.copy': 'Copy',
  'button.compose': 'Compose',
  'buttons.download': 'Download',
  'activities.flows.title': 'Workflow',
  'activities.flows.desc': 'A a sequence of tasks which are defined by using simple configuration language.',
  'activities.decisions.title': 'Decisions',
  'activities.decisions.desc': 'A decision table that can be used to make decisions based on input data.',
  'activities.services.title': 'Services',
  'activities.services.desc': 'A piece of Java or Groovy code that is embedded inside of a flow as a task.',
  'activities.releases.title': 'Releases',
  'activities.releases.desc': 'A Release is a snapshot of all site content at one certain point of time.',
  'activities.releases.desc.additional': 'Each Release can be downloaded to be used for production or backup purposes, or can be branched for further editing. This will replace all current assets so make sure any changes are saved.',
  'activities.releases.view': 'View all releases',
  'activities.compare.title': 'Compare',
  'activities.compare.desc': 'Compare two releases to see what has changed between them.',
  'activities.compare.view': 'Compare',
  'activities.debug.title': 'Debug',
  'activities.debug.desc': 'Simulate execution of an asset. Can be done via form input, JSON input, or by using a CSV file.',
  'activities.debug.view': 'Simulate',
  'activities.assets.saveSuccess': 'Saved asset: {name}',
  'flows': 'Flows',
  'migrations.title': 'Migration',
  'migrations.create': 'Perform migration',
  'migrations.select': 'Select tag.json file',
  'flows.edit.title': 'Edit flow',
  'flows.copyas.title': 'Copy flow as',
  'flows.delete.title': 'Delete flow',
  'flows.delete.error.title': 'Failed to delete flow',
  'flows.delete.content': 'Are you sure you want to delete FLOW: {name}?',
  'flows.deleted.message': 'Deleted FLOW: {name}',
  'flows.simulate.title': 'Debug the flow',
  'flows.composer.title': 'Create new FLOW',
  'flows.composer.copyTitle': 'Copy FLOW as',
  'flows.composer.createdMessage': 'Created FLOW: {name}',
  'flows.composer.copiedMessage': 'Copied FLOW {name} as: {newName}',
  'flows.composer.errorsTitle': 'Failed to create FLOW',
  'flows.composer.assetName': 'Unique name for the FLOW',
  'flows.autocomplete.task.create': 'Create new asset',
  'flows.autocomplete.task.link': 'Link selected asset',
  'flows.autocomplete.task.searchField': 'Search for asset...',
  'flows.autocomplete.task.searchPlaceholder': 'Asset name or description',
  'flows.autocomplete.task.selectType': 'Select asset type to link',
  'flows.autocomplete.task.searchHelper': 'Matches asset name and description',
  'flows.autocomplete.task.searchResults': 'Search results',
  'flows.autocomplete.task.snackbar.created': 'Created new {type}: {name}',
  'flows.autocomplete.task.snackbar.creating': 'Creating new {type}: {name}',
  'flows.graph.show': 'Show flow graph',
  'flows.graph.hide': 'Hide flow graph',
  'services.searchAll': 'Search all services',
  'services.edit.title': 'Edit service',
  'services.copyas.title': 'Copy service as',
  'services.delete.title': 'Delete service',
  'services.delete.error.title': 'Failed to delete SERVICE',
  'services.delete.content': 'Are you sure you want to delete SERVICE: {name}?',
  'services.deleted.message': 'Deleted SERVICE: {name}',
  'services.simulate.title': 'Debug the service',
  'services.composer.title': 'Create new SERVICE',
  'services.composer.copyTitle': 'Copy SERVICE as',
  'services.composer.createdMessage': 'Created SERVICE: {name}',
  'services.composer.copiedMessage': 'Copied SERVICE {name} as: {newName}',
  'services.composer.errorsTitle': 'Failed to create SERVICE',
  'services.composer.assetName': 'Unique name for the SERVICE',
  'decisions.name': 'Name',
  'decisions.desc': 'Description',
  'decisions.simulate.title': 'Debug the decision',
  'decisions.hitpolicy': 'Hit-policy',
  'decisions.edit.title': 'Edit decision',
  'decisions.copyas.title': 'Copy decision as',
  'decisions.delete.error.title': 'Failed to delete DECISION',
  'decisions.delete.title': 'Delete decision',
  'decisions.delete.content': 'Are you sure you want to delete DECISION: {name}?',
  'decisions.deleted.message': 'Deleted DECISION: {name}',
  'decisions.deleteConfirmTitle': 'Confirm Delete',
  'decisions.deleteConfirmText': 'Are you sure you want to delete this {type}?',
  'decisions.type.row': 'row',
  'decisions.type.column': 'column',
  'decisions.table.hitpolicy': 'Matches',
  'decisions.composer.title': 'Create new DECISION',
  'decisions.composer.copyTitle': 'Copy DECISION as',
  'decisions.composer.createdMessage': 'Created DECISION: {name}',
  'decisions.composer.copiedMessage': 'Copied DECISION {name} as: {newName}',
  'decisions.composer.errorsTitle': 'Failed to create DECISION',
  'decisions.composer.assetName': 'Unique name for the DECISION',
  'decisions.toolbar.addInputColumn': 'Add input column',
  'decisions.toolbar.addOutputColumn': 'Add output column',
  'decisions.toolbar.addRow': 'Add row',
  'decisions.toolbar.csvDownload': 'Download CSV, with separator \';\'',
  'decisions.toolbar.csvUpload': 'Upload CSV, with separator \';\'',
  'decisions.toolbar.nameAndHitpolicy': 'Name and hit-policy',
  'decisions.toolbar.organize.rows.columns': 'Organize rows and columns',
  'decisions.toolbar.organize.action': 'Select action',
  'decisions.toolbar.organize.action.helper': 'Move column or row based on name/index',
  'decisions.toolbar.organize.action.expression': 'Select expression',
  'decisions.toolbar.organize.action.expression.column': 'Select column',
  'decisions.toolbar.organize.action.deleteColumn': 'Delete whole column',
  'decisions.toolbar.organize.action.deleteRow': 'Delete whole row',
  'decisions.toolbar.organize.action.deleteRow.contents': 'Row contents',
  'decisions.toolbar.organize.action.move.from.column': 'Column to move',
  'decisions.toolbar.organize.action.move.from.row': 'Row to move',
  'decisions.toolbar.organize.action.move.to.column': 'New Position',
  'decisions.toolbar.organize.action.move.to.row': 'New Position',
  'decisions.table.inputs.title': 'Matching rules',
  'decisions.table.outputs.title': 'Results',
  'decisions.header.dialog.title': 'Decision table: {name}, column: {column}',
  'decisions.cells.dialog.title': 'Decision table: {name}, column: {column}, value: {value}',
  'decisions.cells.dialog.title.simple': 'Edit Value',
  'decisions.header.dialog.title.simple': 'Edit Header',
  'decisions.cells.dialog.title.intl': 'Edit Localized Value',
  'decisions.cells.newvalue.boolean': 'Enter new value',
  'decisions.cells.newvalue.boolean.helper': 'Select boolean value',
  'decisions.cells.newvalue.boolean.empty': 'No value selected',
  'decisions.cells.newvalue.date.operator': 'Operator',
  'decisions.cells.newvalue.date.start': 'Start date',
  'decisions.cells.newvalue.date.end': 'End date',
  'decisions.cells.newvalue.date.value': 'Date',
  'decisions.cells.newvalue.number.comparisonType': 'Comparison',
  'decisions.cells.newvalue.number.comparisonTypeEmpty': 'Comparison not selected',
  'decisions.cells.newvalue.number.comparisonValue': 'New numerical value',
  'decisions.cells.newvalue.number.comparisonToRange': 'Change to range',
  'decisions.cells.newvalue.number.rangeStart': 'Start',
  'decisions.cells.newvalue.number.rangeEnd': 'End',
  'decisions.cells.newvalue.string.comparisonType': 'Comparison',
  'decisions.cells.newvalue.string.addValue': 'Add new value',
  'decisions.cells.newvalue.string.available': 'Available values',
  'decisions.cells.newvalue.string.selected': 'Selected values',
  'decisions.cells.newvalue.string.empty': 'Comparison not selected',
  'decisions.cells.newvalue.clear': 'Clear current value',
  'decisions.valueSet': 'Define value set',
  'decisions.valueSet.description': 'Value sets can be used to define a predetermined set of values for any input',
  'decisions.valueSet.add': 'Add to value set',
  'decisions.valueSet.current': 'Current value set',
  'dt.header.name': 'Name',
  'dt.header.delete': 'Delete',
  'dt.header.expression': 'Expression',
  'dt.header.dataType': 'Data type',
  'dt.header.script': 'Script',
  'decisions': 'Decisions',
  'program.status.DEPENDENCY_ERROR': 'Dependency Errors',
  'program.status.UP': 'Program is UP',
  'program.status.AST_ERROR': 'Syntax errors',
  'program.status.PROGRAM_ERROR': 'Compiler errors',
  'release.deleted.message': 'Release {name} deleted',
  'releases.composer.createdMessage': 'Created new release {name}',
  'releases.view.action': 'Action',
  'releases.composer.title': 'Create new release',
  'releases.composer.assetName': 'Release name',
  'releases.composer.assetDesc': 'Release description',
  'releases.composer.errorsTitle': 'Error while creating release',
  'releases.button.compare': 'Compare',
  'releases.button.branch': 'Create new branch',
  'releases.button.checkout': 'Checkout',
  'releases.button.release': 'Release',
  'releases.button.details': 'View release assets',
  'releases.default.name': 'default',
  'releases.default.note': 'This is the default branch that you can go back to',
  'releases.latest.name': 'latest',
  'releases.latest.note': 'These are current assets with the latest changes that can be released',
  'releases.details.title': 'Release assets: {name}',
  'release.branch.creating': 'Creating new branch: {name}',
  'release.branch.created': 'Created new branch: {name}',
  'release.branch.deleting': 'Deleting branch: {name}',
  'release.branch.deleted': 'Deleted branch: {name}',
  'release.branch.checkout': 'Checked out to branch: {name}',
  'debug.toolbar.options': 'Options',
  'debug.toolbar.selectAsset': 'Select asset to debug',
  'debug.toolbar.inputCsv': 'Define input data as a CSV',
  'debug.toolbar.inputForm': 'Define input data as a FORM',
  'debug.toolbar.inputJson': 'Define input data as a JSON',
  'debug.toolbar.execute': 'Execute',
  'debug.toolbar.noAsset': 'Select asset from options',
  'debug.toolbar.openAsset': 'Open',
  'debug.toolbar.download': 'Download results as CSV',
  'debug.input.noAsset': 'There is no ASSET selected',
  'debug.input.form': 'Debug using FORM',
  'debug.input.formTitle': 'Define inputs',
  'debug.input.form.invalid.integer': 'Value must be an integer',
  'debug.input.form.invalid.number': 'Value must be a number',
  'debug.input.form.invalid.range': 'Value must be in the specified range',
  'debug.input.json': 'Debug using JSON',
  'debug.input.jsonTitle': 'Define JSON input',
  'debug.input.csvUpload': 'Debug using CSV',
  'debug.input.csvFile': 'Upload CSV FILE',
  'debug.input.csvFileTitle': 'Upload CSV file - semicolon-delimited (;)',
  'debug.input.csvFileOrText': 'Or paste CSV contents - semicolon-delimited (;)',
  'debug.inputs.fieldName': 'Field Name',
  'debug.inputs.fieldValue': 'Field Value',
  'debug.select.title': 'Select asset to debug',
  'debug.select.assetType': 'Asset type to filter',
  'debug.select.searchField': 'Asset name to search',
  'debug.select.searchHelper': 'Search matches asset name or description',
  'debug.select.searchPlaceholder': 'Keyword to search',
  'debug.select.searchResults': 'Found assets',
  'debug.select.confirm': 'Select',
  'debug.inputs.format': 'Asset input format: {type}',
  'debug.asset.execute.errors': 'Execution errors',
  'debug.asset.execute.outputs.dt.json': 'Matched row(s)',
  'debug.asset.execute.outputs.dt.rejects': 'Rejected row(s)',
  'debug.asset.execute.outputs.flow.step': 'Step name: {name}, status: {status}',
  'debug.csv.row': 'Data row: {row}',
  'debug.csv.download': 'Download results as CSV',
  'debug.csv.download.delimiter': 'Choose a delimiter for the CSV file',
  'debug.csv.download.delimiter.semicolon': 'Semicolon (;)',
  'debug.csv.download.delimiter.comma': 'Comma (,)',
  'debug.csv.download.options': 'Export options',
  'debug.csv.download.wrap': 'Wrap cells containing delimiters with quotes',
  'compare.tip': 'Select releases to compare below. Base is the starting point of the comparison, and target is the release that will be compared to the base.',
  'compare.base': 'Select base release',
  'compare.target': 'Select target release',
  'compare.dialog.title': 'Comparing releases {base} and {target}',
  'compare.dialog.line': 'Inline',
  'compare.dialog.side': 'Side-by-side',
  'menu.activities': 'Activities',
  'feedback.all': 'All feedback',
  'task.feedback.none': 'No feedback available',
  'queues.all': 'Queues',
  'consumers.all': 'Consumers',
  'queue.config.none': 'Loading',
  'queue.config.consumerName': 'Consumer name',
  'queue.config.routingKey': 'Routing key',
  'queue.config.consumerStatus': 'Status',
  'queue.config.comment': 'Comment',
  'queue.config.queueName': 'Queue name',
  'queue.config.createdAt': 'Created at',
  'queue.config.createdBy': 'Created by',
  'queue.all_deliveries.title': 'All deliveries',
  'queue.all_deliveries.created': 'Created',
  'queue.all_deliveries.consumerComment': 'Comment',
  'queue.all_deliveries.status': 'Status',
  'queue.all_deliveries.messageId': 'Message id',
  'queue.all_deliveries.consumerId': 'Consumer id',
  'queue.all_messages.title': 'All messages',
  'queue.all_messages.routingKey': 'Routing key',
  'queue.all_messages.messageId': 'Message id',
  'queue.all_messages.bodyId': 'Body id',
  'queue.all_messages.bodyType': 'Body type',
  'queue.all_messages.status': 'Status',
  'queue.all_messages.body': 'Body',
  'queue.all_messages.created': 'Created',
  'workflows': 'Workflows',
  'explorer.pages': 'Pages',
  'articles.searchAll': 'Search all articles',
  'composer.article.selected': 'Selected Articles',
  'resource.edit.workflows': 'Workflows',
  'workflow.delete': 'Delete',
  'workflow.edit': 'Edit',
  'eveli.table.menu.filter.filterBy': 'Filter by',
  'eveli.table.menu.filter.showAllItems': 'Show all tiems',
  'eveli.table.menu.sort.ascending': 'Ascending',
  'eveli.table.menu.sort.descending': 'Descending',
  'eveli.table.menu.sort.clearSorting': 'Clear sorting',
  'eveli.table.menu.sort.chooseCols': 'Choose Columns',
  'eveli.table.menu.sort.colsReset': 'Reset Columns',
  'eveli.table.dialog.columns.chooseCols': 'Choose Columns',
  'eveli.table.footer.tasks.total': 'Total',
  'eveli.table.footer.tasks.rowsPerPage': 'Rows per page',
  'eveli.table.footer.pageNumber': 'Page number',
  'eveli.table.footer.rowsPerPage': 'Rows per page',
  'eveli.table.drawer.buttons.colsButton': 'Columns',
  'eveli.table.drawer.buttons.filtersButton': 'Buttons',
  'eveli.table.resetAll': 'Reset all',
  'eveli.table.drawer.title.columns': 'Columns',
  'eveli.table.drawer.title.filters': 'Filters',
  'eveli.table.drawer.title.saved-filters': 'Saved Filters',
  'eveli.table.drawer.title.export-data': 'Export data',
  'eveli.error.general': 'Ooops, we have encountered an error!',
  'eveli.error.notFound': 'Ooops, the thing you are looking for is not found!',
  'eveli.error.backToHome': 'Go back to our home page',
  'eveli.userProfile.title': 'User Profile',
  'eveli.userProfile.id': 'Id',
  'eveli.userProfile.displayName': 'Display name',
  'eveli.userProfile.firstAndLastName': 'Full name',
  'eveli.userProfile.created': 'Created',
  'eveli.userProfile.updated': 'Updated',
  'eveli.userProfile.firstName': 'First name',
  'eveli.userProfile.lastName': 'Last name',
  'eveli.userProfile.email': 'Email',
  'eveli.userProfile.notificationSettings': 'Notification settings',
  'eveli.userProfile.userRoles': 'My roles',
  'eveli.userProfile.userPermissions': 'My permissions',
  'eveli.userProfile.editDetails': 'Edit personal details',
  'eveli.userProfile.currentDetails': 'My current details',
  'eveli.userProfile.tenantConfig.select.LOGIN_BUTTON': 'Login button',
  'eveli.userProfile.tenantConfig.select.external-deployment': 'External deployment',
  'eveli.userProfile.tenantConfig.select.external-deployment.desc': 'Assets come explicitly from an environment-specific data source that implements ExternalDeploymentProvider',
  'eveli.userProfile.tenantConfig.select.feedback-visually-disabled': 'Feedback visually disabled',
  'eveli.userProfile.tenantConfig.select.feedback-visually-disabled.desc': 'Show / hide the feedback feature from the UI',
  'eveli.userProfile.tenantConfig.select.queues-visually-disabled': 'Queues visually disabled',
  'eveli.userProfile.tenantConfig.select.queues-visually-disabled.desc': 'Show / hide the Queues feature from the UI',
  'eveli.userProfile.tenantConfig.select.stencil-disabled': 'Stencil disabled',
  'eveli.userProfile.tenantConfig.select.stencil-disabled.desc': 'Eveli is reconfigured so as to remove Stencil',
  'eveli.userProfile.tenantConfig.select.wrench-disabled': 'Wrench disabled',
  'eveli.userProfile.tenantConfig.select.wrench-disabled.desc': 'Eveli is reconfigured so as to remove Wrench',
  'eveli.userProfile.tenantConfig.select.wrench-only': 'Wrench only',
  'eveli.userProfile.tenantConfig.select.wrench-only.desc': 'Eveli is reconfigured so as to include only Wrench',
  'eveli.userProfile.tenantConfig.select.batches': 'Batches',
  'eveli.userProfile.tenantConfig.select.batches.desc': 'Enable / disable batch processing features',
  'eveli.userProfile.tenantConfig.select.eveli_publication_only': 'Eveli publication only',
  'eveli.userProfile.tenantConfig.select.eveli_publication_only.desc': 'Editing assets is disabled - they come directly from a publication',
  'eveli.userProfile.tenantConfig.select.smart_tables': 'Smart tables',
  'eveli.userProfile.tenantConfig.select.smart_tables.desc': 'All tables are persistant - they save user-defined configurations',
  'eveli.userProfile.tenantConfig.select.stencil_locale_filter': 'Stencil locale filter',
  'eveli.userProfile.tenantConfig.select.stencil_locale_filter.desc': 'Configure visibility of the locale filtering UI component in Stencil',
  'eveli.userProfile.tenantConfig.select.user_profile': 'User profile enabled',
  'eveli.userProfile.tenantConfig.select.user_profile.desc': 'Show / hide the user profile feature from the UI',
  'eveli.userProfile.tenantConfig.select.smart_task': 'Smart task view',
  'eveli.userProfile.tenantConfig.select.smart_task.desc': 'Editing a task is enhanced via drag and drop/unified editing/flashy colours',
  'eveli.userProfile.tenantConfig.select.smart_task_audit': 'Smart task audit',
  'eveli.userProfile.tenantConfig.select.smart_task_audit.desc': 'Additional detailed views are enabled for auditing/debugging a task',
  'eveli.userProfile.tenantConfig.select.visual_accommodation': 'Visual accommodation',
  'eveli.userProfile.tenantConfig.select.visual_accommodation.desc': 'To make certain buttons and UI items pop for enhanced visibility',
  'taskTable.col.header.priority': 'Priority',
  'taskTable.col.header.subject': 'Subject',
  'taskTable.col.header.addInfo': 'Info',
  'taskTable.col.header.client': 'Client',
  'taskTable.col.header.status': 'Status',
  'taskTable.col.header.roles': 'Role',
  'taskTable.col.header.assignee': 'Assigned',
  'taskTable.col.header.due': 'Duedate',
  'taskTable.col.header.created': 'Created',
  'taskTable.col.header.archive': 'Archive',
  'eveli.batches.batchView.averageRunTime': 'Average run time',
  'eveli.batches.batchView.averageRunTime.ms': 'ms',
  'taskcard.style.COMPACT': 'Compact',
  'taskcard.style.DEFAULT': 'Default',
  'taskcard.style.LARGE': 'Large'
}