export const fi = {
  'document.title': 'DigiExpress',
  'eveli.textSeparatorColon': ':',
  'eveli.noValueIndicator': '--',
  'eveli.permissions.none.title': 'Joitain meni väärin!',
  'eveli.permissions.none.desc1': 'Sinulla ei ole oikeuksia tämän sovelluksen käyttöön',
  'eveli.permissions.none.desc2': 'Ota yhteyttä teidän käyttöoikeuksista vastaan henkilöön',
  'tasksView.title': 'Tehtävät',
  'taskDialog.priority': 'Prioriteetti',
  'taskDialog.subject': 'Aihe',
  'taskDialog.dueDate': 'Eräpäivä',
  'taskDialog.assignedTo': 'Käsittelijän rooli',
  'taskDialog.assignedUser': 'Käsittelijä',
  'taskDialog.status': 'Tila',
  'taskDialog.task': 'Tehtävä',
  'taskDialog.category': 'Tyyppi',
  'taskDialog.source': 'Lähde',
  'taskDialog.additionalInfo': 'Lisätieto',
  'task.assignable.dialog.title': 'Kohdistetut lomakkeet',
  'task.assignable.new': 'Kohdista uusi lomake',
  'task.assignable.desc': 'Kohdista lomakeella käytetty kielli',
  'task.assignable.locale': 'Kieli',
  'task.assignable.forms': 'Lomakkeet',
  'task.assignable.cancel': 'Peruuta kohdistettu lomakke',
  'task.assignable.cancel.desc': 'Kohdistettua lomakketa ei voi poistaa sen jälkeen, kun asiakas on täyttänyt ne!',
  'task.assignable.selectForms': 'Valitse lomakke',
  'task.assignable.cancel.formsList.desc': 'Seuraavat lomakkeet perutaan!',
  'button.cancelSelected': 'Peru valitut lomakkeet ({count})',
  'button.acceptSelected': 'Kohdista valitut lomakkeet ({count})',
  'task.priority.low': 'Ei kiireellinen',
  'task.priority.normal': 'Normaali',
  'task.priority.high': 'Kiire',
  'task.dueDate': 'Eräpäivä',
  'task.customerMessages': 'Asiakkaiden viestit',
  'task.customerMessages.messageHistory': 'Viestiketju',
  'task.customerMessages.none': 'Ei viestejä',
  'task.customerMessages.newMessageTitle': 'Kirjoita uusi viesti asiakkaalle',
  'task.customerMessages.newMessagePlaceholder': 'Viestit asiakkaalle',
  'button.sendMessage': 'Lähtetä viesti',
  'task.edit': 'Muokkaa tehtävää',
  'task.customerName': 'Asiakkaan nimi',
  'task.subject': 'Aihe',
  'task.additionalInfo': 'Lisätiedot',
  'task.metaData': 'Metatiedot',
  'task.status.new': 'Uusi',
  'task.status.open': 'Käsittelyssä',
  'task.status.completed': 'Valmis',
  'task.status.rejected': 'Ei käsittelyä',
  'task.status.transferred': 'Siirretty',
  'task.status.delegated': 'Delegoitu',
  'task.status.waiting': 'Odottaa',
  'task.pdf.options.select.CUSTOMER_NAME': 'Asiakkaan nimi',
  'task.pdf.options.select.CUSTOMER_SSN': 'Asiakkaan tunnus',
  'task.pdf.options.select.EXTERNAL_COMMENTS': 'Viestiketju',
  'task.pdf.options.select': 'PDF Tuloste listätiedot',
  'task.pdf.print': 'Tulosta PDF',
  'task.pdf.options.select.desc': 'Valitse pdf-dokumenttiin sisällytettävät lisätiedot',
  'task.form.review': 'Avaa lomake',
  'task.created': 'Luotu',
  'task.updated': 'Päivitetty',
  'task.comments.external.createTask': 'Luo tehtävä ennen ulkoisten kommenttien lisäämistä',
  'task.comments.internal.createTask': 'Luo tehtävä ennen sisäisten kommenttien lisäämistä',
  'task.attachments.createTask': 'Luo tehtävä ennen liitteiden lataamista',
  'task.comments.external.added': 'Sisäinen kommentti tallletettu',
  'task.feedback.publishedSaved': 'Palautemuutokset tallennettu',
  'task.transfer.published': 'Asiakirjan siirto',
  'task.transfer.create.title': 'Asiakirjan siirto',
  'task.transfer.create.journalNumber': 'Diaarinumero',
  'task.transfer.create.files': 'Siirretyt asiakirjat',
  'task.transfer.button.transfer': 'Siirtää',
  'task.transfer.button.retransfer': 'Siirtää uudelleen',
  'internalComments': 'Sisäiset kommentit',
  'externalComments': 'Viesti/palaute asiakkaalle',
  'comment.store': 'Tallenna',
  'comment.add': 'Lisää kommentti',
  'comment.addInternal': 'Lisää sisäinen kommentti',
  'comment.addExternal': 'Viesti/palaute asiakkaalle',
  'taskButton.refresh': 'Tarkista uudet tehtävät',
  'taskButton.accept': 'Hyväksy',
  'taskButton.cancel': 'Takaisin',
  'taskReopenDialog.title': 'Avaa tehtävä uudelleen',
  'taskReopenDialog.subtitle1': 'Olet avaamassa tämän tehtävän uudelleen',
  'taskReopenDialog.subtitle2': 'Kun hyväksyt muutokset, tehtävän tilaksi asetetaan AUKI ja asiakkaalle lähetetään viesti.',
  'taskReopenDialog.customer-message': 'Kirjoita asiakkaalle lähetettävä viesti',
  'taskReopenDialog.customer-message-label-placeholder1': 'Viesti asiakkaalle',
  'taskReopenDialog.customer-message-label-placeholder2': 'Kirjoita viesti',
  'button.taskReopenDialog': 'Avaa tehtävä uudelleen',
  'table.body.emptyDataSourceMessage': 'Ei dataa',
  'table.body.filterRow.filterTooltip': 'Suodatin',
  'table.body.deleteTooltip': 'Poista',
  'table.header.actions': 'Toiminnot',
  'table.pagination.labelDisplayedRows': '{from}-{to} / {count}',
  'table.pagination.labelRowsPerPage': 'Riviä per sivu:',
  'table.pagination.firstPage': 'Ensimmäinen sivu',
  'table.pagination.previousPage': 'Edellinen',
  'table.pagination.nextPage': 'Seuraava',
  'table.pagination.lastPage': 'Viimeinen sivu',
  'table.toolbar.search': 'Etsi',
  'table.toolbar.showColumnsTitle': 'Näytä sarakkeet',
  'table.toolbar.addRemoveColumns': 'Lisää tai poista sarakkeita',
  'taskLink.pdf.open': 'PDF',
  'explorer.login': 'Kirjaudu sisään',
  'locale.fi': 'Suomi',
  'locale.sv': 'Ruotsi',
  'locale.en': 'Englanti',
  'main.articles.all': 'Kaikki Artikkelit',
  'main.links.all': 'Kaikki Linkit',
  'main.services.all': 'Kaikki Palvelut',
  'main.flows.all': 'All Service Flows',
  'main.debug': 'Testaa',
  'main.decisions.all': 'All Decisions Tables',
  'menu.dashboard': 'Kojelauta',
  'menu.profile': 'Käyttäjän profiili',
  'menu.tasks': 'Tehtävät',
  'menu.forms': 'Dialob',
  'menu.queues': 'Queues',
  'menu.help': 'Ohjeet',
  'menu.processes': 'Monitorointi',
  'menu.logout': 'Kirjaudu ulos',
  'menu.publications': 'Julkaisut',
  'menu.services': 'Palvelut',
  'menu.feedback': 'Palaute',
  'menu.compose': 'Luo uusi',
  'menu.articles': 'Artikkelit',
  'menu.links': 'Linkit',
  'menu.locales': 'Kielet',
  'menu.templates': 'Valmis pohjat',
  'menu.flows': 'Service Flows',
  'menu.decisions': 'Service Flows',
  'menu.debug': 'Debug',
  'menu.releases': 'Debug',
  'menu.compare': 'Debug',
  'profile.user.name': 'Nimi:',
  'profile.user.email': 'Sähköposti:',
  'profile.user.role': 'Rooli:',
  'button.cancel': 'Peruuta',
  'button.archive': 'Arkisto',
  'button.confirmDelete': 'Poista',
  'button.delete.feedback': 'Poista tämä palaute',
  'button.delete.template': 'Poista tämä valmispohja',
  'button.delete.link': 'Poista tämä linkki',
  'button.delete.article': 'Poista tämä artikkeli',
  'button.delete.page': 'Poista tämä sivu',
  'button.update': 'Päivitä',
  'button.publish': 'Julkaise',
  'button.accept': 'Hyväksy',
  'button.close': 'Sulje',
  'button.save': 'Tallenna',
  'button.dismiss': 'Hylkää',
  'button.select': 'Valitse',
  'button.startBatch': 'Start batch',
  'error.minTextLength': 'Annetun arvon pitää olla vähintään {minLength} merkkiä',
  'error.maxTextLength': 'Annetun arvon tulee olla enintään {max} merkkiä pitkä',
  'error.valueRequired': '* Vaaditaan',
  'error.title': 'Virhe!',
  'error.dialob.session': 'Lomaketta ei voida aukaista juuri nyt. Yritä uudelleen myöhemmin',
  'error.errorLoadingData': 'Virhe tietojen latauksen aikana',
  'error.unauthorized.title': 'Käyttöoikeutesi ovat puutteelliset',
  'error.unauthorized.text': 'Ota yhteyttä IT-palveluihin lähettämällä tukipyyntö Tiketin kautta -> Jätä tukipyyntö -> Kirjautumisongelma.',
  'error.unauthorizedAccess': 'Käyttöoikeutesi ovat puutteelliset',
  'error.dataAccess': 'Virhe toiminnassa',
  'error.statusOpenError': 'Tila',
  'error.workflowCreation': 'Virhe konfiguroinnissa, tarkista nimen yksilöllisyys',
  'error.invalidFormName': 'Virheellinen lomakkeen nimi',
  'table.body.editRow.deleteMessage': 'Halutko varmasti poistaa tämän?',
  'workflowTable.title': 'Stencil palvelut',
  'workflowTableHeader.name': 'Nimi',
  'workflowTableHeader.formName': 'Lomake',
  'workflowTableHeader.flowName': 'Prosessi',
  'workflowTableHeader.updated': 'Päivitetty',
  'workflowTable.editButton': 'Muokka',
  'workflow.dialogTitle': 'Stencil palvelu',
  'workflow.name': 'Nimi',
  'workflow.form.formName': 'Lomakkeen nimi',
  'workflow.form.formTag': 'Lomakkeen versio',
  'workflow.flowName': 'Workflow nimi',
  'processTable.title': 'Työt',
  'processTableHeader.workflow': 'Stencil palvelu nimi',
  'processTableHeader.status': 'Tila',
  'processTableHeader.created': 'Luotu',
  'processTableHeader.questionnaireId': 'Lomake tunnus',
  'processTableHeader.taskRef': 'Tehtävän viite',
  'process.status.ANSWERED': 'Lähetetty',
  'process.status.CREATED': 'Luotu',
  'process.status.ANSWERING': 'Keskeneräinen',
  'process.status.IN_PROGRESS': 'Käsittelyssä',
  'process.status.WAITING': 'Odottaa',
  'process.status.COMPLETED': 'Valmis',
  'process.status.REJECTED': 'Hylätty',
  'spoTasksTableHeader.taskName': 'Nimi',
  'spoTasksTableHeader.status': 'Tila',
  'spoTasksTableHeader.priority': 'Prioriteetti',
  'spoTasksTableHeader.dueDate': 'Eräpäivä',
  'spoTasksTableHeader.assigned': 'Rooli',
  'spoTasksTableHeader.assignedUser': 'Käsittelijä',
  'spoTasksTableHeader.created': 'Luotu',
  'spoTasksTableHeader.clientName': 'Asiakas',
  'spoTasksTableHeader.additionalInfo': 'Info',
  'taskDialog.clientIdentificator': 'Asiakas',
  'Manual': 'Manuaalinen',
  'Protected': 'Suojattu',
  'Normal': 'Normaali',
  'CustomerCreated': 'Asiakas luotu',
  'Internal': 'Sisäinen',
  'task.role.assignedAllUsers': 'Kaikki käyttäjät',
  'confirm.close.title': 'Vahvistus vaaditaan',
  'confirm.unsavedChanges': 'Tallentamattomat muutokset menetetään. Haluatko jatkaa?',
  'task.statistics.statusCount': 'Tilan mukaan',
  'task.statistics.priorityCount': 'Prioriteetin mukaan',
  'task.statistics.daily': 'Päivittäin',
  'task.statistics.overdue': 'Myöhässä',
  'task.statistics.new_task_by_role': 'Uudet tehtävät rooleittain',
  'task.statistics.task_by_questionnaire': 'Tehtävät lomakkeittain',
  'task.statistics.open_task_by_role': 'Avoimet tehtävät rooleittain',
  'feedback.create.title': 'Julkaise vastine palautteeseen',
  'feedback.update.title': 'Muokkaa vastinetta asiakkaan palautteelle',
  'feedback.taskReferenceId': 'Tehtävän tunnus',
  'feedback.taskReferenceId.short': 'Tehtävän viite',
  'feedback.mainCategory': 'Aihe',
  'feedback.feedbackValue': 'Asiakkaan palaute',
  'feedback.feedbackValue.placeholder': 'Asiakaspalautteen sisältö',
  'feedback.customerTitle': 'Palautteen otsikko',
  'feedback.myReply': 'Vastaa asiakkaalle',
  'feedback.myReply.placeholder': 'Vastaus asiakkaalle',
  'feedback.customerApprovals': 'Asiakkaan suostumukset',
  'feedback.createdBy': 'Luonut',
  'feedback.updatedBy': 'Päivittänyt',
  'feedback.updated': 'Viimeisin päivitys',
  'feedback.notPublished': 'Tätä vastinetta ei ole julkaistu',
  'feedback.isPublished': 'Tämä vastine on julkaistu',
  'feedback.delete.confirmTitle': 'Poista palautte ja vastine?',
  'feedback.delete.confirmText': 'Haluatko varmasti poistaa tämän palautteen?',
  'feedback.main_topic.cityService': 'Kaupunki ja asiakaspalvelu',
  'feedback.main_topic.roadMaintance': 'Katujen kunnossapitoon liittyvät palautteet (auraus, liukkauden torjunta, pöly/hiekanpoisto)',
  'feedback.main_topic.cityConstruction': 'Kaupunkiympäristö, rakentaminen ja asuminen',
  'feedback.main_topic.youthService': 'Lasten ja nuorten palvelut',
  'feedback.main_topic.exercise': 'Liikunta',
  'feedback.main_topic.school': 'Perusopetua ja lukio',
  'feedback.main_topic.employmentImmigration': 'Työllisyys, työikäiset, ikääntyneet ja maahanmuuttajat',
  'feedback.main_topic.freeTimeCulture': 'Vapaa-aika ja kulttuuri',
  'feedback.main_topic.preschoolEducation': 'Varhaiskasvatus ja esiopetus',
  'feedback.main_topic.communication': 'Viestintä ja markkinointi',
  'feedback.main_topic.cooperation': 'Yhteistyö, elinkeinot ja matkailu',
  'help.title': 'Ohjeet',
  'attachmentView.title': 'Liitetiedostot',
  'attachmentTableHeader.size': 'Koko',
  'attachmentTableHeader.created': 'Luotu',
  'attachmentTableHeader.name': 'Aihe',
  'attachmentButton.addAttachment': 'Lisää tiedosto',
  'attachmentButton.downloadAttachment': 'Lataa tiedosto',
  'attachmentButton.deleteAttachment': 'Poista tiedosto',
  'attachment.uploadOk': 'Tiedosto {fileName} ladattu',
  'attachment.uploadFailed': 'Tiedoston {fileName} lataaminen epäonnistui!',
  'attachment.delete.confirmTitle': 'Poista tiedosto?',
  'attachment.delete.confirmText': 'Haluatko varmasti poistaa tiedoston {fileName}?',
  'attachment.deleteFailed': 'Tiedoston {fileName} poistaminen epäonnistui!',
  'publicationsTable.title': 'Julkaisut',
  'publicationsTableHeader.name': 'Julkaisun tunniste',
  'publicationsTableHeader.description': 'Kuvaus',
  'publicationsTableHeader.createdBy': 'Päivittäjä',
  'publicationsTableHeader.created': 'Luotu',
  'publicationsTableHeader.liveDate': 'Päivitetty',
  'publicationsTable.addButton': 'Lisää uusi',
  'publicationsTable.exportButton': 'Vie tiedosto',
  'publicationsTable.uploadButton': 'Lataa sisään',
  'publications.external': 'Tämä on ulkoisesti konfiguroitu päivitys, joka astuu voimaan vasta kun muut päivitykset on tehty',
  'publications.changeStatus': 'Muokkaa päivityksen tilaan',
  'publications.currentStatus': 'Nykyisen päivitysen tila',
  'publications.remove': 'Poista päivitys',
  'publications.deploy': 'Julkaise nyt',
  'publications.dialogTitle': 'Tee uusi julkaisu',
  'publications.name': 'Julkaisun tunniste',
  'publications.description': 'Kuvaus',
  'publications.workflowTag': 'Workflow versio',
  'publications.wrenchTag': 'theWrench versio',
  'publications.contentTag': 'Sisältöversio',
  'publications.createNewTag': 'Luo uusi versio \"{tag}\"',
  'publications.downloadFailed': 'Julkaisun lataus epäonnistui, syy: {cause}',
  'publications.tagCreationFailed': 'Julkaisun luominen epäonnistui, syy: {cause}',
  'publications.uploadDialogTitle': 'Lataa julkaisu',
  'dialobForm.saveFailed': 'Tallennus epäonnistui',
  'dialobForm.downloadFailed': 'Tallennus epäonnistui',
  'dialobForm.deleteFailed': 'Poisto epäonnistui',
  'dialobForm.review.title': 'Lomakkeen tarkistus',
  'feedback.notenabled': 'Palaute toiminnallisuutta ei voi käyttää tehtävässä',
  'pages': 'Sivut',
  'articles': 'Artikkelit',
  'locale': 'Sijainti',
  'locales': 'Sijainnit',
  'links': 'Linkit',
  'releases': 'Julkaisut',
  'options': 'Valinnat',
  'value': 'Arvo',
  'date': 'Päiväys',
  'description': 'Kuvaus',
  'name': 'Nimi',
  'download': 'Vie JSON tiedosto',
  'download.all': 'Lataa kaikki',
  'status': 'Muokkaa päivityksen tilaa',
  'created': 'Luotu',
  'remove': 'Poista',
  'site.content.empty': 'Sivustolla ei ole sisältöä! Luo sisältöä ennen julkaisua!',
  'composer.select.article': 'Valitse artikkelit',
  'search.field.placeholder': 'Kirjoita hakusana',
  'search.results.title': 'Hakutulokset',
  'search.field.label': 'Haku',
  'search.all': 'Kaikki',
  'search.articles': 'Artikkeleita',
  'search.services': 'Palveluja',
  'search.links': 'Linkkejä',
  'search.templates': 'Mallit',
  'search.flows': 'Flows',
  'search.decisions': 'Decisions',
  'adminUI.formConfiguration.label': 'Otsikko',
  'adminUI.formConfiguration.lastSaved': 'Muokattu',
  'adminUI.formConfiguration.latestTagDate': 'Viimeisin tunniste',
  'adminUI.formConfiguration.latestTagName': 'Viimeisin tunnistenimi',
  'adminUI.formConfiguration.labels': 'Luokat',
  'adminUI.dialog.formName': 'Lomakkeen nimi',
  'adminUI.dialog.formLabel': 'Lomakkeen otsikko',
  'adminUI.dialog.emptyTitle': '(Nimetön)',
  'adminUI.dialog.heading': 'Lomakkeet',
  'adminUI.dialog.deleteQuestion': 'Haluatko poistaa lomakkeen',
  'adminUI.dialog.form.addFormLabel.title': 'Lisää uusi tunniste',
  'adminUI.dialog.form.addFormLabel.desc': 'Luo tunniste lajittelun helpottamiseksi',
  'adminUI.table.tooltip.add': 'Lisää uusi lomake',
  'adminUI.table.tooltip.edit': 'Muokkaa Composerissa',
  'adminUI.table.tooltip.copy': 'Kopioi lomake',
  'adminUI.table.tooltip.delete': 'Poista',
  'adminUI.table.tooltip.download': 'Lataa',
  'activities.article.title': 'Artikkeli',
  'activities.article.desc': 'Artikkeli on kuin luokka: se ryhmittelee sivut, linkit ja palvelut saman aihealueen alle.',
  'activities.locale.title': 'Lokalistointi',
  'activities.locale.desc': 'Kieliasetukset: Lisää, aktivoi ja deaktivoi sivustossa käytettyjä kieliä. Voit lisätä sivun tietyllä kielellä, jos olet määrittänyt tälle sivulle alueen.',
  'activities.page.title': 'Sivu',
  'activities.page.desc': 'Sisältöä tietys artikkelissa hallinnoidaan sivun kautta. Yksi sivu edustaa aina yhtä kieltä ja kaikkia linkkejä/työnkulkuja, jotka liittyvät artikkeliin. Se on kirjoitettu hyödyntämällä Markdown-syntaksia.',
  'activities.link.title': 'Linkki',
  'activities.link.desc': 'Hyperlinkki yhdistää käyttäjät tosiin sivuihin, muiden organisaatioiden verkkosivuille ja puhelinnumeroihisi.',
  'activities.release.title': 'Julkaisu',
  'activities.release.desc': 'Julkaisu on pitää sisällää  sivuston koko sisällön ajankohtana kun se tehdään. Julkaisuja voi hyödyntää testaukseen, tuotantoon tai varmuuskopiointitarkoituksiin.',
  'activities.migration.title': 'Migraatio',
  'migration.create': 'Migraatio data',
  'activities.migration.desc': 'Käytä JSON tiedosta tämän portaalin migrointiin',
  'activities.templates.title': 'Mallipohjat',
  'activities.templates.desc': 'Käytä malleja sivun oletusarvoisen Markdown-sisällön ja/tai -rakenteen mukauttamiseen ja standardointiin. Malleja voidaan käyttää uusille sivuille luomisen yhteydessä. Ei vielä toteutettu!',
  'activities.version.composer': 'Composer: build version {version}, build date {date}',
  'activities.version.core': 'Core: build version {version}, build date {date}',
  'dialog.about.title': 'Lisätietoja',
  'dialog.about.preamble': 'DigiExpress perustuu avoimeen lähdekoodiin',
  'dialog.about.trademark': 'DigiExpress-tavaramerkin ja logo tekijänoikeudet omistaa ReSys OÜ',
  'heading.copyDialog': 'Luo kopio',
  'heading.addDialog': 'Luo uusi lomake',
  'heading.deleteDialog': 'Vahvista',
  'templates': 'Mallipohjat',
  'template.name': 'Nimi',
  'template.name.desc': 'Mallipohjan nimi',
  'template.create': 'Luo mallipohja',
  'template.edit': 'Muokkaa mallipohjaa',
  'template.type': 'Mallipohjan tyyppi',
  'template.page': 'Sivun mallipohja',
  'template.page.desc': 'Mallipohjaa voidaan käyttää uudelle sivulle sen luomisen yhteydessä.',
  'template.description': 'Hyödynnä Markdow mallipohja sivuihisi ja sisältöösi. Mallit nopeuttavat kehitystäsi ja yhtenäistävät sisältörakennettasi.',
  'template.desc': 'Kuvaus',
  'template.description.desc': 'Lisätietoja, jotka auttavat tunnistamaan tämän mallipohjan käyttötarkoituksen',
  'template.delete': 'Poista mallipohja',
  'template.delete.message': 'Tämä mallipohja poistetaan pysyvästi sovelluksesta',
  'template.newpage.none': 'Tyhjä',
  'templates.templatesview.description': 'Mallistapohjasta voidaan luoda uusi sivu',
  'templates.intro': 'Muista käyttää Markdown Level 1 -otsikkoa (# My Heading 1), kun kirjoitat malleja.',
  'services': 'Palvelut',
  'services.create': 'Luo palvelu',
  'services.desc': 'Yhdistä lomakkeet ja muut integraatiot sisältöösi Wrench- ja Dialob-työkalujen avulla',
  'services.add': 'Lisää palvelu',
  'services.change': 'Muokaa olemassa olevaa palvelua',
  'services.edit': 'Muokaa palvelua',
  'services.technicalname': 'Palvelun nimi',
  'services.selected': 'Valitse palavelu',
  'services.modeselect.title': 'Asetusvaihtoehdot',
  'services.modeselect.label': 'Valitse',
  'services.devmode': 'Kehitystila',
  'services.devmode.helper': 'Kehitystila: Palvelu näkyy vain kehitysympäristössä testausta varten, eikä se sisälly tuotantojulkaisuihin.',
  'services.devmode.label': 'Kehitystila',
  'services.devmode.tooltip': 'Kehitystila',
  'services.disabledmode.label': 'Ei käytössä',
  'services.disabledmode.helper': 'Palvelu ei ole portaalissa näkyvissä',
  'services.disabledmode.tooltip': 'Ei käytössä',
  'services.assignableMode.label': 'Palvelun käytöntila',
  'services.assignableMode.helper': 'Määritettävä tila: Voidaan määrittää suoraan asiakkaalle',
  'services.assignableMode.tooltip': 'Palvelun käytöntila',
  'services.none.label': 'Ei valintaa',
  'services.none.helper': 'Perustila',
  'services.none.tooltip': 'Ei eritystilaa',
  'services.anonmode.helper': 'Anonyymi tila: Palvelu näkyy SEKÄ anonyymeille ja todennetuille käyttäjille.',
  'services.anonmode.label': 'Anonyymi käyttäjä',
  'services.anonmode.tooltip': 'Anonyymi käyttäjä',
  'services.flowName': 'Workflow nimi',
  'services.formName': 'Dialob lomakkeen nimi',
  'services.formTag': 'Lomakkeen versionumero',
  'services.startdate': 'Palvelun saataville',
  'services.startdate.description': 'Palvelun julkaisuajankohta',
  'services.enddate': 'Palvelun pois saatavilta',
  'services.enddate.description': 'Palvelu poistuu käytöstä',
  'services.delete': 'Poista palvelu',
  'services.delete.desc': 'Tämän palvelun poistaminen poistaa sen pysyvästi sovelluksesta mukaan lukien ne kaikki artikkelit, jossa se on julkaistu',
  'service.name': 'Palvelun nimi',
  'service.unknown': 'Tuntematon palvelu',
  'service.button.delete': 'Poista tämä palvelu',
  'snack.article.createdMessage': 'Artikkeli luotu',
  'snack.article.deletedMessage': 'Artikkeli poistettu',
  'snack.article.editedMessage': 'Artikkelin muutokset tallennettu',
  'snack.page.createdMessage': 'Sivu luotu',
  'snack.page.deletedMessage': 'Sivu poistettu',
  'snack.page.savedMessage': 'Sivun muutokset tallennettu',
  'snack.page.missingTitle': 'Lisää otsikko kohteelle {locale} artikkelissa {articleName}',
  'snack.link.createdMessage': 'Linkin luominen onnistui',
  'snack.link.deletedMessage': 'Linkki poistettu',
  'snack.link.editedMessage': 'Linkin muutokset tallennettu',
  'snack.workflow.createdMessage': 'Palvelu luotu onnistuneesti',
  'snack.workflow.deletedMessage': 'Palvelu poistettu',
  'snack.workflow.editedMessage': 'Palvelumuutokset tallennettu',
  'snack.locale.createdMessage': 'Kieli-asetuksen luominen onnistui',
  'snack.locale.enabled': 'Kieliasetus käytössä',
  'snack.locale.disabled': 'Kieliasetus poistettu käytöstä',
  'snack.template.createdMessage': 'Malli luotiin onnistuneesti',
  'snack.template.deletedMessage': 'Malli poistettu',
  'snack.template.editedMessage': 'Mallin muutokset tallennettu',
  'snack.template.savedMessage': 'Mallipohja tallennettu onnistuneesti',
  'snack.service.deletedMessage': 'Palvelu poistettu',
  'snack.release.createdMessage': 'Julkaisun luominen onnistui',
  'snack.release.deletedMessage': 'Julkaisu poistettu',
  'snack.migration.createdMessage': 'Sivuston tiedot päivitetty',
  'toolbar.save': 'Tallenna',
  'toolbar.stencil': 'theStencil',
  'toolbar.wrench': 'theWrench',
  'toolbar.menu': 'Valikko',
  'toolbar.help': 'Tuki',
  'toolbar.import': 'Tuo dataa',
  'toolbar.tasks': 'Tehtävät',
  'toolbar.about': 'Tietoja',
  'stencil.services.found.none': 'Ei tuloksia',
  'link.type.internal': 'Sisäinen (domainin sisällä)',
  'link.type.external': 'Ulkoinen (domainin ulkopuolella)',
  'link.type.phone': 'Puhelinnumero',
  'link.search.title': 'Etsi linkkejä',
  'link.value': 'Linkin tiedot',
  'sitelocale.label.select.alreadyDefined': 'Tämä lokalisointi on jo käytössä',
  'sitelocale.label.table.editLocaleValue': 'Editoi lokalisointia',
  'locales.label.table.title': 'Lokalisonti tunniste',
  'locales.label.title.helper': 'Vähintään yksi kielikoodi (locale) + sen sisältö vaaditaan',
  'locales.label.table.value': 'Lokalisointi',
  'locales.label.table.noneSet': 'Ei käännöksiä',
  'locales.enabledMessage': 'Käytössä: Tämän aiheen sisältö näytetään portaalin puolella',
  'locales.disabledMessage': 'Pois käytöstä: Tämän kieliasetuksen sisältö piilotetaan portaalin puolelta. Sisältöä voi edelleen muokata.',
  'transferlist.noItemsSelected': 'Ei valintoja',
  'transferlist.search': 'Hae',
  'transferlist.noSearchResults': 'Ei tuloksia',
  'explorer.tabs.links': 'Lomakkeet',
  'explorer.tabs.services': 'Palvelut',
  'imports.select': 'Valitse tiedosto',
  'imports.import.action': 'Tuo valitut',
  'article.order': 'Artikkelin järjestysnumero',
  'article.order.view': 'Näytä Artikkelien järjestys',
  'article.select': 'Valitse Artikkeli',
  'article.links.selectedlinks': 'Valitse Linkki',
  'article.composer.title': 'Luo uusi artikkeli',
  'article.composer.parent': 'Ylemmäntason artikkeli',
  'article.parent.helper': 'Jos ylätason artikkeli valitaan, tämä artikkeli säilyy tämän ylätason sisällä, kuten kansion sisällä oleva tiedosto.',
  'article.composer.parent.unselected': 'Ei valittu',
  'article.create': 'Luo artikkeli',
  'article.name': 'Artikkelin nimi',
  'article.unknown': 'Tuntematon artikkeli',
  'article.delete.title': 'Poista tämä artikkeli pysyvästi?',
  'article.delete.description': 'Artikkelin poistaminen poistaa sen ja siihen yhdistetyt sivut koko sovelluksesta.',
  'article.edit.title': 'Muokkaa artikkelia',
  'article.edit.parent': 'Ylemmän tason artikkeli',
  'article.devmode.helper': 'Jos kehitysverisio on aktiivinen niin Artikkeli näkyy ainoastaan kehitysympäristössä',
  'article.devmode': 'Julkaisu tyyppi',
  'articleservices': 'Artikkelin palvelut: {name}',
  'articlelinks': 'Artikkelin linkit: {name}',
  'article.composer.orderhelper': 'Mitä pienempi numero sen ylempänän tämä Artikkeli on valinnoissa',
  'article.timestamps.title': 'Lisätietoa',
  'button.create': 'Luo',
  'button.add': 'Lisää',
  'button.disable': 'Jatka ja deaktivoi',
  'button.enable': 'Jatka ja salli käyttö',
  'button.apply': 'Salli muutokset ja jatka',
  'button.view.all.locales': 'Näytä kaikki sijainnit',
  'button.view.all.releases': 'Näytä kaikki julkaisut',
  'button.view.all.templates': 'Maillipohjat',
  'links.searchAll': 'Etsi linkkejä',
  'link.article.select': 'Valitse artikkeli',
  'link.type': 'Tyyppi',
  'link.content': 'Linkki URL / reitti',
  'link.composer.title': 'Luo uusi linkki',
  'link.composer.valuehelper': 'URL / linkin reitti (http://www.example.com)',
  'link.edit.title': 'Muokkaa linkkiä',
  'link.delete.title': 'Poista linkki pysyvästi?',
  'link.delete': 'Linkin poistaminen poistaa sen lopullisesti koko sovelluksesta ja sen kaikki yhteydet artikkeleihin/sivuihin menetetään.',
  'resource.edit.links': 'Lisää ja poista artikkelilinkkejä',
  'links.change': 'Muokkaa linkkejä',
  'link.create': 'Luo linkki',
  'link.devmode.helper': 'Jos kehitystila on aktiivinen, tämä linkki näkyy vain kehitysympäristössä. Sitä ei sisällytetä tuotantojulkaisuihin.',
  'link.devmode': 'Kehitysversion aktivointi',
  'locale.create': 'Luo lokalisointi',
  'locale.disable.title': 'Poista lokalisointi käytöstä?',
  'locale.enable.title': 'Salli lokalisoinnin käyttö?',
  'locale.disable': 'Kaikki tätä lokalisointi käyttävät sivut ovat käyttöliittymässä piilossa. Sivuja voidaan edelleen muokata.',
  'locale.enable': 'Kaikki tätä lokalisointi käyttävät sivut ovat esillä käyttöliittymässä.',
  'locale.composer.title': 'Luo uusi lokalisointi',
  'locale.composer.placeholder': 'Kaksikirjaiminen kielitunniste',
  'locale.composer.helper': 'Kaksikirjaiminen kielitunniste',
  'locale.overview': 'Lokalisointien yhteenveto',
  'locales.overview.description': 'Hallinnoi sivujen kieliä. Poista maa-asetukset käytöstä piilottaaksesi kaikki kyseiseen kieleen liittyvän sisällön sivustostasi',
  'locales.content': 'Sivulta löytyy lokalisoitua sisältöä',
  'locales.nocontent': 'Sivulta ei löydy lokalisoitua',
  'locales.nopage': 'Artikkelissa ei löydä tätä kieliversiota',
  'locales.label.table.locale': 'Kielikoodi',
  'newpage.title': 'Luo uusi sivu',
  'newpage.template.select': 'Mallipohja',
  'newpage.info': 'Sivulla on sisällöstä ja sen tulee olla yhdistetty artikkeliin.',
  'newpage.article.info': 'Vahvista sivun luominen artikkelille: {article} sijainnilla: {locale}',
  'page.create': 'Luo sivu',
  'page.delete.dialog.title': 'Poista sivu tästä artikkelista',
  'page.delete.description': 'Valittu sivu poistetaan pysyvästi sivustostasi',
  'pages.add': 'Lisää sivu',
  'pages.change': 'Muuta sivun lokalisointia',
  'pages.select.locale': 'Muokkaa lokalisoitua sivun sisältöä',
  'pages.select.locale.edit.desc': 'Ota käyttöön vierekkäinen muokkaus yhdellä välilehdellä valitsemalla kaksi kieltä.',
  'pages.edit.language1': 'Muokkaa kieltä',
  'pages.edit.language2': 'Muokkaa tätä kieltä vierekkäin',
  'pages.edit.currentlyEditing.language2': 'Muokkaus vierekkäin',
  'pages.edit.currentlyEditing.language1': 'Muokkaa kieltä',
  'pages.change.info': 'Valitse sivu tästä artikkelista ja anna uusi arvo sen sijainnille.',
  'pages.change.devmode': 'Muuta sivun kehitystilaa',
  'pages.change.devmode.info': 'Valitse sivu tästä artikkelista ja muuta sen kehitystapaa.',
  'pages.devmode.helper': 'Jos kehitystila on aktiivinen, tämä sivu näkyy vain kehitysympäristössä. Sitä ei sisällytetä tuotantojulkaisuihin.',
  'pages.devmode': 'Kehitysversio aktiivinen',
  'pages.delete': 'Poista sivu',
  'pages.edit.selectpage': 'Valitse sivue',
  'pages.edit.selectTargetLocale': 'Valitse kieli',
  'release.create': 'Luo julkaisu',
  'release.composer.title': 'Luo uusi julkaisu',
  'release.composer.label': 'Version nimi nimi',
  'release.composer.note': 'Info',
  'release.composer.helper': 'Valinnainen lisätieto tulevaa käyttöä varten',
  'release.composer.helper.optionalDesc': 'Valinnainen kuvaus',
  'release.desc': 'Katso kaikki julkaisut ja lataa kaikki sivuston sisältö JSON-muodossa. Tarkempia tietoja tietyistä julkaisuista ja niiden sisällöstä on kaaviossa.',
  'release.delete.title': 'Poista päivitys?',
  'release.delete.desc': 'Haluatko poista päivityksen pysyvästi',
  'releases.view.note': 'Lisä tietoa',
  'releases.view.tag': 'Nimi',
  'releases.view.created': 'Luotu',
  'releases.view.download': 'JSON tiedoston lataus',
  'buttons.create': 'Lisää',
  'buttons.apply': 'Laita voimaan',
  'buttons.delete': 'Poista',
  'buttons.copy': 'Kopio',
  'button.compose': 'Luo',
  'buttons.download': 'Lataa',
  'activities.flows.title': 'Workflow',
  'activities.flows.desc': 'A a sequence of tasks which are defined by using simple configuration language.',
  'activities.decisions.title': 'Decisions',
  'activities.decisions.desc': 'A decision table that can be used to make decisions based on input data.',
  'activities.services.title': 'Services',
  'activities.services.desc': 'A piece of Java or Groovy code that is embedded inside of a flow as a task.',
  'activities.releases.title': 'Releases',
  'activities.releases.desc': 'A Release is a snapshot of all site content at one certain point of time.',
  'activities.releases.desc.additional': 'Each Release can be downloaded to be used for production or backup purposes, or can be branched for further editing. This will replace all current assets so make sure any changes are saved.',
  'activities.releases.view': 'View all releases',
  'activities.compare.title': 'Compare',
  'activities.compare.desc': 'Compare two releases to see what has changed between them.',
  'activities.compare.view': 'Compare',
  'activities.debug.title': 'Debug',
  'activities.debug.desc': 'Simulate execution of an asset. Can be done via form input, JSON input, or by using a CSV file.',
  'activities.debug.view': 'Simulate',
  'activities.assets.saveSuccess': 'Saved asset: {name}',
  'flows': 'Flows',
  'upload.json': 'JSON',
  'upload.csv': 'CSV',
  'migrations.title': 'Migration',
  'migrations.create': 'Perform migration',
  'migrations.select': 'Select tag.json file',
  'flows.edit.title': 'Edit flow',
  'flows.copyas.title': 'Copy flow as',
  'flows.delete.title': 'Delete flow',
  'flows.delete.error.title': 'Failed to delete flow',
  'flows.delete.content': 'Are you sure you want to delete FLOW: {name}?',
  'flows.deleted.message': 'Deleted FLOW: {name}',
  'flows.simulate.title': 'Debug the flow',
  'flows.composer.title': 'Create new FLOW',
  'flows.composer.copyTitle': 'Copy FLOW as',
  'flows.composer.createdMessage': 'Created FLOW: {name}',
  'flows.composer.copiedMessage': 'Copied FLOW {name} as: {newName}',
  'flows.composer.errorsTitle': 'Failed to create FLOW',
  'flows.composer.assetName': 'Unique name for the FLOW',
  'flows.autocomplete.task.create': 'Create new asset',
  'flows.autocomplete.task.link': 'Link selected asset',
  'flows.autocomplete.task.searchField': 'Search for asset...',
  'flows.autocomplete.task.searchPlaceholder': 'Asset name or description',
  'flows.autocomplete.task.selectType': 'Select asset type to link',
  'flows.autocomplete.task.searchHelper': 'Matches asset name and description',
  'flows.autocomplete.task.searchResults': 'Search results',
  'flows.autocomplete.task.snackbar.created': 'Created new {type}: {name}',
  'flows.autocomplete.task.snackbar.creating': 'Creating new {type}: {name}',
  'flows.graph.show': 'Show flow graph',
  'flows.graph.hide': 'Hide flow graph',
  'services.searchAll': 'Search all services',
  'services.edit.title': 'Edit service',
  'services.copyas.title': 'Copy service as',
  'services.delete.title': 'Delete service',
  'services.delete.error.title': 'Failed to delete SERVICE',
  'services.delete.content': 'Are you sure you want to delete SERVICE: {name}?',
  'services.deleted.message': 'Deleted SERVICE: {name}',
  'services.simulate.title': 'Debug the service',
  'services.composer.title': 'Create new SERVICE',
  'services.composer.copyTitle': 'Copy SERVICE as',
  'services.composer.createdMessage': 'Created SERVICE: {name}',
  'services.composer.copiedMessage': 'Copied SERVICE {name} as: {newName}',
  'services.composer.errorsTitle': 'Failed to create SERVICE',
  'services.composer.assetName': 'Unique name for the SERVICE',
  'decisions.name': 'Name',
  'decisions.desc': 'Description',
  'decisions.simulate.title': 'Debug the decision',
  'decisions.hitpolicy': 'Hit-policy',
  'decisions.edit.title': 'Edit decision',
  'decisions.copyas.title': 'Copy decision as',
  'decisions.delete.error.title': 'Failed to delete DECISION',
  'decisions.delete.title': 'Delete decision',
  'decisions.delete.content': 'Are you sure you want to delete DECISION: {name}?',
  'decisions.deleted.message': 'Deleted DECISION: {name}',
  'decisions.deleteConfirmTitle': 'Confirm Delete',
  'decisions.deleteConfirmText': 'Are you sure you want to delete this {type}?',
  'decisions.type.row': 'Row',
  'decisions.type.column': 'Column',
  'decisions.table.hitpolicy': 'Column',
  'decisions.composer.title': 'Create new DECISION',
  'decisions.composer.copyTitle': 'Copy DECISION as',
  'decisions.composer.createdMessage': 'Created DECISION: {name}',
  'decisions.composer.copiedMessage': 'Copied DECISION {name} as: {newName}',
  'decisions.composer.errorsTitle': 'Failed to create DECISION',
  'decisions.composer.assetName': 'Unique name for the DECISION',
  'decisions.toolbar.addInputColumn': 'Add input column',
  'decisions.toolbar.addOutputColumn': 'Add output column',
  'decisions.toolbar.addRow': 'Add row',
  'decisions.toolbar.csvDownload': 'Download CSV, with separator \';\'',
  'decisions.toolbar.csvUpload': 'Upload CSV, with separator \';\'',
  'decisions.toolbar.nameAndHitpolicy': 'Name and hit-policy',
  'decisions.toolbar.organize.rows.columns': 'Organize rows and columns',
  'decisions.toolbar.organize.action': 'Select action',
  'decisions.toolbar.organize.action.helper': 'Move column or row based on name/index',
  'decisions.toolbar.organize.action.expression': 'Select expression',
  'decisions.toolbar.organize.action.expression.column': 'Select column',
  'decisions.toolbar.organize.action.deleteColumn': 'Delete whole column',
  'decisions.toolbar.organize.action.deleteRow': 'Delete whole row',
  'decisions.toolbar.organize.action.deleteRow.contents': 'Row contents',
  'decisions.toolbar.organize.action.move.from.column': 'Column to move',
  'decisions.toolbar.organize.action.move.from.row': 'Row to move',
  'decisions.toolbar.organize.action.move.to.column': 'New Position',
  'decisions.toolbar.organize.action.move.to.row': 'New Position',
  'decisions.table.inputs.title': 'Matching rules',
  'decisions.table.outputs.title': 'Results',
  'decisions.header.dialog.title': 'Decision table: {name}, column: {column}',
  'decisions.cells.dialog.title': 'Decision table: {name}, column: {column}, value: {value}',
  'decisions.cells.dialog.title.simple': 'Edit Value',
  'decisions.header.dialog.title.simple': 'Edit Header',
  'decisions.cells.dialog.title.intl': 'Edit Localized Value',
  'decisions.cells.newvalue.boolean': 'Enter new value',
  'decisions.cells.newvalue.boolean.helper': 'Select boolean value',
  'decisions.cells.newvalue.boolean.empty': 'No value selected',
  'decisions.cells.newvalue.date.operator': 'Operator',
  'decisions.cells.newvalue.date.start': 'Start date',
  'decisions.cells.newvalue.date.end': 'End date',
  'decisions.cells.newvalue.date.value': 'Date',
  'decisions.cells.newvalue.number.comparisonType': 'Comparison',
  'decisions.cells.newvalue.number.comparisonTypeEmpty': 'Comparison not selected',
  'decisions.cells.newvalue.number.comparisonValue': 'New numerical value',
  'decisions.cells.newvalue.number.comparisonToRange': 'Change to range',
  'decisions.cells.newvalue.number.rangeStart': 'Start',
  'decisions.cells.newvalue.number.rangeEnd': 'End',
  'decisions.cells.newvalue.string.comparisonType': 'Comparison',
  'decisions.cells.newvalue.string.addValue': 'Add new value',
  'decisions.cells.newvalue.string.available': 'Available values',
  'decisions.cells.newvalue.string.selected': 'Selected values',
  'decisions.cells.newvalue.string.empty': 'Comparison not selected',
  'decisions.cells.newvalue.clear': 'Clear current value',
  'decisions.valueSet': 'Define value set',
  'decisions.valueSet.description': 'Value sets can be used to define a predetermined set of values for any input',
  'decisions.valueSet.add': 'Add to value set',
  'decisions.valueSet.current': 'Current value set',
  'dt.header.name': 'Name',
  'dt.header.delete': 'Delete',
  'dt.header.expression': 'Expression',
  'dt.header.dataType': 'Data type',
  'dt.header.script': 'Script',
  'decisions': 'Decisions',
  'program.status.DEPENDENCY_ERROR': 'Dependency Errors',
  'program.status.UP': 'Program is UP',
  'program.status.AST_ERROR': 'Syntax errors',
  'program.status.PROGRAM_ERROR': 'Compiler errors',
  'release.deleted.message': 'Julkaisu {name} poistettu',
  'releases.composer.createdMessage': 'Luotu uusi julkaisu {name}',
  'releases.view.action': 'Action',
  'releases.composer.title': 'Create new release',
  'releases.composer.assetName': 'Release name',
  'releases.composer.assetDesc': 'Release description',
  'releases.composer.errorsTitle': 'Error while creating release',
  'releases.button.compare': 'Compare',
  'releases.button.branch': 'Create new branch',
  'releases.button.checkout': 'Checkout',
  'releases.button.release': 'Release',
  'releases.button.details': 'View release assets',
  'releases.default.name': 'Default',
  'releases.default.note': 'This is the default branch that you can go back to',
  'releases.latest.name': 'Viimeisin',
  'releases.latest.note': 'These are current assets with the latest changes that can be released',
  'releases.details.title': 'Release assets: {name}',
  'release.branch.creating': 'Creating new branch: {name}',
  'release.branch.created': 'Created new branch: {name}',
  'release.branch.deleting': 'Deleting branch: {name}',
  'release.branch.deleted': 'Deleted branch: {name}',
  'release.branch.checkout': 'Checked out to branch: {name}',
  'debug.toolbar.options': 'Options',
  'debug.toolbar.selectAsset': 'Select asset to debug',
  'debug.toolbar.inputCsv': 'Define input data as a CSV',
  'debug.toolbar.inputForm': 'Define input data as a FORM',
  'debug.toolbar.inputJson': 'Define input data as a JSON',
  'debug.toolbar.execute': 'Execute',
  'debug.toolbar.noAsset': 'Select asset from options',
  'debug.toolbar.openAsset': 'Open',
  'debug.toolbar.download': 'Download results as CSV',
  'debug.input.noAsset': 'There is no ASSET selected',
  'debug.input.form': 'Debug using FORM',
  'debug.input.formTitle': 'Define inputs',
  'debug.input.form.invalid.integer': 'Value must be an integer',
  'debug.input.form.invalid.number': 'Value must be a number',
  'debug.input.form.invalid.range': 'Value must be in the specified range',
  'debug.input.json': 'Debug using JSON',
  'debug.input.jsonTitle': 'Define JSON input',
  'debug.input.csvUpload': 'Debug using CSV',
  'debug.input.csvFile': 'Upload CSV FILE',
  'debug.input.csvFileTitle': 'Upload CSV file - semicolon-delimited (;)',
  'debug.input.csvFileOrText': 'Or paste CSV contents - semicolon-delimited (;)',
  'debug.inputs.fieldName': 'Field Value',
  'debug.inputs.fieldValue': 'Field Value',
  'debug.select.title': 'Select asset to debug',
  'debug.select.assetType': 'Asset type to filter',
  'debug.select.searchField': 'Asset name to search',
  'debug.select.searchHelper': 'Search matches asset name or description',
  'debug.select.searchPlaceholder': 'Keyword to search',
  'debug.select.searchResults': 'Found assets',
  'debug.select.confirm': 'Select',
  'debug.inputs.format': 'Asset input format: {type}',
  'debug.asset.execute.errors': 'Execution errors',
  'debug.asset.execute.outputs.dt.json': 'Matched row(s)',
  'debug.asset.execute.outputs.dt.rejects': 'Rejected row(s)',
  'debug.asset.execute.outputs.flow.step': 'Step name: {name}, status: {status}',
  'debug.csv.row': 'Data row: {row}',
  'debug.csv.download': 'Download results as CSV',
  'debug.csv.download.delimiter': 'Choose a delimiter for the CSV file',
  'debug.csv.download.delimiter.semicolon': 'Semicolon (;)',
  'debug.csv.download.delimiter.comma': 'Comma (,)',
  'debug.csv.download.options': 'Export options',
  'debug.csv.download.wrap': 'Wrap cells containing delimiters with quotes',
  'compare.tip': 'Select releases to compare below. Base is the starting point of the comparison, and target is the release that will be compared to the base.',
  'compare.base': 'Select base release',
  'compare.target': 'Select target release',
  'compare.dialog.title': 'Comparing releases {base} and {target}',
  'compare.dialog.line': 'Inline',
  'compare.dialog.side': 'Vierekkäin',
  'menu.activities': 'Aktiviteetit',
  'feedback.all': 'Kaikki palaute',
  'queues.all': 'Queues',
  'consumers.all': 'Consumers',
  'queue.config.none': 'Loading',
  'queue.config.consumerName': 'Consumer name',
  'queue.config.routingKey': 'Routing key',
  'queue.config.consumerStatus': 'Status',
  'queue.config.comment': 'Comment',
  'queue.config.queueName': 'Queue name',
  'queue.config.createdAt': 'Created at',
  'queue.config.createdBy': 'Created by',
  'queue.all_deliveries.title': 'All deliveries',
  'queue.all_deliveries.created': 'Created',
  'queue.all_deliveries.consumerComment': 'Comment',
  'queue.all_deliveries.status': 'Status',
  'queue.all_deliveries.messageId': 'Message id',
  'queue.all_deliveries.consumerId': 'Consumer id',
  'queue.all_messages.title': 'All messages',
  'queue.all_messages.routingKey': 'Routing key',
  'queue.all_messages.messageId': 'Message id',
  'queue.all_messages.bodyId': 'Body id',
  'queue.all_messages.bodyType': 'Body type',
  'queue.all_messages.status': 'Status',
  'queue.all_messages.body': 'Body',
  'queue.all_messages.created': 'Created',
  'workflows': 'Workflows',
  'explorer.pages': 'Sivut',
  'articles.searchAll': 'Search all articles',
  'composer.article.selected': 'Valitut artikkelit',
  'resource.edit.workflows': 'Workflows',
  'workflow.delete': 'Delete',
  'workflow.edit': 'Edit',
  'eveli.table.menu.filter.filterBy': 'Suodatusperuste {title}',
  'eveli.table.menu.filter.showAllItems': 'Valitse kaikki',
  'eveli.table.menu.sort.ascending': 'Nouseva',
  'eveli.table.menu.sort.descending': 'Laskeva',
  'eveli.table.menu.sort.clearSorting': 'Tyhjää lajittelu',
  'eveli.table.menu.sort.chooseCols': 'Valitse sarakkeet',
  'eveli.table.menu.sort.colsReset': 'Nollaa sarakkeet',
  'eveli.table.dialog.columns.chooseCols': 'Valitse sarakkeet',
  'eveli.table.footer.tasks.total': 'Rivejä',
  'eveli.table.footer.tasks.rowsPerPage': 'Rivejä per sivu',
  'eveli.table.footer.pageNumber': 'Sivunumero',
  'eveli.table.footer.rowsPerPage': 'Rivejä per sivu',
  'eveli.table.drawer.buttons.colsButton': 'Sarakkeet',
  'eveli.table.drawer.buttons.filtersButton': 'Suodatusnäkymä',
  'eveli.table.resetAll': 'Nollaa kaikki',
  'eveli.table.drawer.title.columns': 'Sarakkeet',
  'eveli.table.drawer.title.filters': 'Suodattimet',
  'eveli.table.drawer.title.saved-filters': 'Tallennetut näkymät',
  'eveli.table.drawer.title.export-data': 'Vie tiedot',
  'eveli.table.defaultSettings': 'Oletusasetukset',
  'eveli.error.general': 'Havaitsimme virheen!',
  'eveli.error.notFound': 'Etsimääsi asiaa ei löydy!',
  'eveli.error.backToHome': 'Palaa kotisivullemme',
  'eveli.table.saveas.title': 'Tallenna nämä suodatin astetukset',
  'eveli.table.updatefilter.title': 'Päivitä suodattimen nimi',
  'eveli.table.saveas.name': 'Suodattimen nimi',
  'eveli.table.resetColumnVisbility': 'Mukauta sarakkeiden järjestystä ja näkyvyyttä',
  'eveli.table.resetColumnSorting': 'Palauta sarakkeiden järjestys',
  'eveli.table.menu.filter.filterByDateEqual': 'Tämä päivä',
  'eveli.table.menu.filter.filterByDateLt': 'Aiemmin kuin annettu päivä',
  'eveli.table.menu.filter.filterByDateGte': 'Annettu päivä tai jälkeiset päivät',
  'eveli.table.menu.filter.filterByDateTitle': 'Päivämäärän suodatus',
  'eveli.userProfile.title': 'Käyttäjän profiili',
  'eveli.userProfile.id': 'Tunnus',
  'eveli.userProfile.displayName': 'Käyttäjän nimi',
  'eveli.userProfile.firstAndLastName': 'Koko nimi',
  'eveli.userProfile.created': 'Luotu',
  'eveli.userProfile.updated': 'Päivitetty',
  'eveli.userProfile.firstName': 'Etunimi',
  'eveli.userProfile.lastName': 'Sukunimi',
  'eveli.userProfile.email': 'Sähköposti',
  'eveli.userProfile.notificationSettings': 'Ilmoitusten asetukset',
  'eveli.userProfile.userRoles': 'Minun roolini',
  'eveli.userProfile.userPermissions': 'Minun oikeudet',
  'eveli.userProfile.editDetails': 'Muokkaa henkilötietoja',
  'eveli.userProfile.currentDetails': 'Nykyiset tietoni',
  'eveli.userProfile.tenantConfig.select.LOGIN_BUTTON': 'Kirjautumispainike',
  'eveli.userProfile.tenantConfig.select.external-deployment': 'Ulkoinen käyttöönotto',
  'eveli.userProfile.tenantConfig.select.external-deployment.desc': 'Omaisuudet tulevat nimenomaisesti ympäristökohtaisesta tietolähteestä, joka toteuttaa ExternalDeploymentProviderin',
  'eveli.userProfile.tenantConfig.select.feedback-visually-disabled': 'Palaute visuaalisesti poistettu käytöstä',
  'eveli.userProfile.tenantConfig.select.feedback-visually-disabled.desc': 'Näytä/piilota palauteominaisuus käyttöliittymästä',
  'eveli.userProfile.tenantConfig.select.queues-visually-disabled': 'Jonot visuaalisesti poissa käytöstä',
  'eveli.userProfile.tenantConfig.select.queues-visually-disabled.desc': 'Näytä/piilota Jonot-ominaisuus käyttöliittymästä',
  'eveli.userProfile.tenantConfig.select.stencil-disabled': 'Stencil pois käytöstä',
  'eveli.userProfile.tenantConfig.select.stencil-disabled.desc': 'Eveli on konfiguroitu uudelleen poistamaan Stencil',
  'eveli.userProfile.tenantConfig.select.wrench-disabled': 'theWrench poistettu käytöstä',
  'eveli.userProfile.tenantConfig.select.wrench-disabled.desc': 'Eveli on konfiguroitu uudelleen jakoavaimen poistamiseksi',
  'eveli.userProfile.tenantConfig.select.wrench-only': 'Vain theWrench käytössä',
  'eveli.userProfile.tenantConfig.select.wrench-only.desc': 'Vain theWrench käytössä',
  'eveli.userProfile.tenantConfig.select.batches': 'Eräajot',
  'eveli.userProfile.tenantConfig.select.batches.desc': 'Ota eräkäsittelyominaisuudet käyttöön / poista se käytöstä',
  'eveli.userProfile.tenantConfig.select.eveli_publication_only': 'Portaalin julkaisu',
  'eveli.userProfile.tenantConfig.select.eveli_publication_only.desc': 'Omaisuuden muokkaaminen on poistettu käytöstä – ne tulevat suoraan julkaisusta',
  'eveli.userProfile.tenantConfig.select.smart_tables': 'Älykkäät taulukot',
  'eveli.userProfile.tenantConfig.select.smart_tables.desc': 'Taulukkonäkymien aktiivinen tallentaminen',
  'eveli.userProfile.tenantConfig.select.stencil_locale_filter': 'Stencil suodattimet',
  'eveli.userProfile.tenantConfig.select.stencil_locale_filter.desc': 'Määritä kieliasetusten suodatuksen käyttöliittymäkomponentin näkyvyys Stencilissä',
  'eveli.userProfile.tenantConfig.select.user_profile': 'Käyttäjäprofiili käytössä',
  'eveli.userProfile.tenantConfig.select.user_profile.desc': 'Näytä/piilota käyttäjäprofiiliominaisuus käyttöliittymästä',
  'eveli.userProfile.tenantConfig.select.smart_task': 'Älykäs tehtävänäkymä',
  'eveli.userProfile.tenantConfig.select.smart_task.desc': 'Tehtävän muokkaamista tehostetaan vetämällä ja pudottamalla / yhdistetyllä muokkauksella / kirkkailla väreillä',
  'eveli.userProfile.tenantConfig.select.smart_task_audit': 'Älykäs tehtävien auditointi',
  'eveli.userProfile.tenantConfig.select.smart_task_audit.desc': 'Tarkat lisänäkymät ovat käytössä tehtävän tarkastamista/virheenkorjausta varten',
  'eveli.userProfile.tenantConfig.select.visual_accommodation': 'Visuaalinen muokautus',
  'eveli.userProfile.tenantConfig.select.visual_accommodation.desc': 'Tietyt painikkeet ja käyttöliittymäkohteet ponnahtavat näkyvyyden parantamiseksi',
  'taskTable.col.header.priority': 'Prioriteetti',
  'taskTable.col.header.subject': 'Aihe',
  'taskTable.col.header.addInfo': 'Tiedot',
  'taskTable.col.header.client': 'Asiakas',
  'taskTable.col.header.status': 'Tila',
  'taskTable.col.header.roles': 'Käsittelijän rooli',
  'taskTable.col.header.assignee': 'Käsittelijä',
  'taskTable.col.header.due': 'Määräaika',
  'taskTable.col.header.created': 'Luotu',
  'taskTable.col.header.archive': 'Arkistoi',
  'taskTable.button.archive.confirm': 'Olet arkistoimassa tätä tehtävää. Haluatko varmasti jatkaa?',
  'taskTable.confirmArchive.title': 'Vahvista arkistointi',
  'taskTable.title': 'Tehtävät',
  'taskButton.addTask': 'Lisää tehtävä',
  'eveli.table.clearFilters': 'Tyhjennä kaikki suodattimet',
  'eveli.table.drawer.buttons.savedFiltersButton': 'Mukauta',
  'eveli.table.saveasdefault': 'Tallenna oletuksena',
  'eveli.table.saveas': 'Uusi suodatin nykyisestä',
  'eveli.batches.batchView.averageRunTime': 'Average run time',
  'eveli.batches.batchView.averageRunTime.ms': 'ms',
  'taskcard.style.COMPACT': 'Kompakti',
  'taskcard.style.DEFAULT': 'Oletus',
  'taskcard.style.LARGE': 'Suuri',
  'task.feedback.none': 'Palautetta ei ole saatavilla',
  'task.feedback.published': 'Julkaise vastine palautteelle',
  'toolbar.tagomi': 'Tagomi',
  'tagomi.services.searchAll': 'Hae kaikista Tagomi-palveluista',
  'tagomi.main.services.all': 'Kaikki palvelut',
  'tagomi.templates.templateTab': 'Mallipohja',
  'tagomi.services.title': 'Palvelut',
  'tagomi.services.desc': 'Palveluiden kuvaus',
  'tagomi.service.create': 'Palvelu',
  'tagomi.locales.title': 'Kieliasetukset',
  'tagomi.locales.desc': 'Kieliasetusten kuvaus',
  'tagomi.locale.create': 'Kieliasetus',
  'tagomi.templates.title': 'Mallit',
  'tagomi.templates.desc': 'Mallien kuvaus',
  'tagomi.template.create': 'Mallipohja',
  'tagomi.service.options.edit': 'Muokkaa palvelua',
  'tagomi.service.options.delete': 'Poista palvelu',
  'tagomi.service.options.templates.create': 'Luo mallipohja',
  'tagomi.service.options.template.changeLocale': 'Vaihda mallipohjan kieliasetusta',
  'tagomi.service.options.template.delete': 'Poista mallipohja',
  'tagomi.service.options.template.addDependencies': 'Lisää riippuvuuksia',
  'tagomi.service.options.template.debug': 'Virheenkorjauspalvelu',
  'tagomi.service.create.dialog.title': 'Luo palvelu',
  'tagomi.service.create.dialog.serviceName': 'Palvelun nimi',
  'tagomi.service.create.dialog.orchestratorName': 'Orkestroijan nimi',
  'tagomi.service.edit.dialog.title': 'Muokkaa palvelua:',
  'tagomi.service.edit.dialog.name': 'Palvelun nimi',
  'tagomi.service.edit.dialog.orchestratorName': 'Orkestroijan nimi',
  'tagomi.template.edit.currentlyEditing.language1': 'Muokkaa parhaillaan',
  'tagomi.template.edit.language1': 'Muokkaa sisältöä tälle kielelle',
  'tagomi.template.editor.compile': 'Kokoa',
  'tagomi.template.editor.fillInput': 'Täytä syöte',
  'tagomi.template.change.dialog.title': 'Vaihda mallipohjan kieliasetusta',
  'tagomi.template.change.dialog.desc': 'Käytettävissä olevan kieliasetuksen valitseminen vaihtaa tämän mallipohjan kielen alkuperäisestä valitsemaasi uuteen.',
  'tagomi.template.change.dialog.selectOrigin': 'Valitse nykyinen mallipohja',
  'tagomi.template.change.dialog.selectTarget': 'Valitse uusi kieliasetus',
  'tagomi.template.change.dialog.noTemplates': 'Tälle palvelulle ei ole saatavilla malleja',
  'tagomi.template.change.dialog.noLocales': 'Joko kieli- tai alueasetuksia ei ole valittu tai määrittämättömiä kieli- tai alueasetuksia ei ole saatavilla',
  'tagomi.template.delete.dialog.title': 'Poista mallipohja kohteesta',
  'tagomi.template.delete.dialog.desc': 'Valitse poistettava malli. Poistettuja malleja ei voi enää käyttää.',
  'tagomi.template.delete.dialog.selectTemplate': 'Valittu malli',
  'tagomi.template.editor.title': 'Muokkaa mallipohjan sisältöä',
  'tagomi.template.editor.serviceName': 'Palvelun nimi:',
  'tagomi.template.editor.localeLabel': 'Kieliasetuksen otsikko:',
  'tagomi.template.dependencies.add.dialog.title': 'Lisää riippuvuuksia',
  'tagomi.template.dependencies.add.dialog.desc': 'Riippuvuudet ovat muita malleja tai kuvia, jotka on tuotu tämän mallin ulkopuolelta käytettäväksi sen sisällä.',
  'tagomi.template.dependencies.add.dialog.selectOrigin': 'Valitse mallipohja',
  'tagomi.template.dependencies.add.dialog.selectTargets': 'Valitse lisättävät riippuvuudet',
  'tagomi.template.dependencies.add.dialog.helperText.noTemplateSelected': 'Valitse kohdemalli ennen riippuvuuksien valitsemista',
  'tagomi.service.options.template.editDependencies': 'Muuta riippuvuuksia',
  'tagomi.template.dependencies.edit.dialog.title': 'Muuta riippuvuuksia',
  'tagomi.template.dependencies.edit.dialog.desc': 'Muokkaa tämän palvelumallin olemassa olevia riippuvuuksia',
  'tagomi.template.dependencies.edit.dialog.selectOrigin': 'Valitse mallipohja',
  'tagomi.button.delete.dialog.template': 'Poista',
  'tagomi.template.delete.dialog.noTemplates.helperText': 'Ei poistettavia malleja',
  'tagomi.template.create.dialog.title': 'Luo uusi mallipohja',
  'tagomi.template.create.dialog.desc': 'Mallipohja sisältää kielikohtaisen PDF-sisällön',
  'tagomi.template.create.dialog.service.name': 'Palvelun nimi',
  'tagomi.template.create.dialog.localeLabel.select': 'Kieliasetuksen otsikko: Liitä kieli malliisi',
  'tagomi.template.create.dialog.noLocales': 'Kaikki käytettävissä olevat kieliasetukset on jo määritetty muille malleille',
  'tagomi.service.delete.dialog.title': 'Poista palvelu:',
  'tagomi.service.delete.dialog.desc': 'Olet poistamassa tätä palvelua. Sen sisältöä ei enää voi käyttää.',
  'tagomi.service.delete.dialog.button': 'Poista',
  'tagomi.locale.select.alreadyDefined': 'Kieli on jo määritelty',
  'tagomi.locale.label.editLocaleValue': 'Muokkaa kieliasetusta',
  'xui.calendarInput.mask.placeholder.day': 'pp',
  'xui.calendarInput.mask.placeholder.month': 'mm',
  'xui.calendarInput.mask.placeholder.year': 'vvvv',
  'contractsTable.title': 'Sopimukset',
  'contractTable.col.header.status': 'Status',
  'contractTable.col.header.contractNumber': 'Määrä',
  'contractTable.col.header.contractType': 'Tyyppi',
  'contractTable.col.header.created': 'Luotu',
  'contractTable.col.header.maturityDate': 'Erääntymispäivä',
  'contractTable.col.header.policyholder': 'Vakuutuksenottaja',
  'contract.composer.contract.edit': 'Muokkaa sopimusta',
  'contractcard.edit': 'Muokata',
  'contractcard.contractMain.title': 'Sopimusnumero: {contractId}',
  'contractcard.contractDetails.title': 'Sopimuksen tiedot',
  'contractcard.contractParties.title': 'Sopimusosapuolet',
  'contractcard.contractPartyDetails.title': 'Sopimusosapuolen tiedot',
  'contractcard.investmentPlans.invPlanAllocations.title': 'Suunnitelman kohdennukset',
  'contractcard.paymentPlans.title': 'Maksusuunnitelmat',
  'contractcard.investmentPlans.title': 'Sijoitussuunnitelmat',
  'contractcard.coverages.title': 'Kattavuus',
  'contractcard.body.category': 'Kategoria',
  'contractcard.body.status': 'Status',
  'contractcard.body.productName': 'Tuotteen nimi',
  'contractcard.body.productCode': 'Tuotekoodi',
  'contractcard.body.limits.annualMaxContribution': 'Vuosittainen enimmäismaksuosuus',
  'contractcard.body.limits.contractMinValue': 'Sopimuksen vähimmäisarvo',
  'contractcard.body.limits.partialWithdrawalMin': 'Osittaisen noston vähimmäismäärä',
  'contractcard.body.issueDate': 'Myöntämispäivämäärä',
  'contractcard.body.issueDateInterval': 'Myöntöpäivämäärän väli',
  'contractcard.body.issueDateType': 'Myöntöpäivämäärän tyyppi',
  'contractcard.body.startDate': 'Aloituspäivämäärä',
  'contractcard.body.startDateInterval': 'Aloituspäivämäärän aikaväli',
  'contractcard.body.startDateType': 'Aloituspäivämäärän tyyppi',
  'contractcard.body.maturityDate': 'Erääntymispäivä',
  'contractcard.body.maturityDateInterval': 'Erääntymispäivämääräväli',
  'contractcard.body.maturityDateType': 'Erääntymispäivämäärän tyyppi',
  'contractcard.body.transitives.updatedTreeAt': 'Päivitetty puu osoitteessa',
  'contractcard.body.parties.partyType': 'Juhlatyyppi',
  'contractcard.body.parties.partyFullName': 'Koko nimi',
  'contractcard.body.parties.dateOfBirth': 'Syntymäaika',
  'contractcard.body.parties.partyPersonalId': 'Henkilötunnus',
  'contractcard.body.parties.investmentExperience': 'sijoituskokemus',
  'contractcard.body.parties.riskTolerance': 'Riskinsietokyky',
  'contractcard.body.parties.partyAddress.city': 'Kaupunki',
  'contractcard.body.parties.partyAddress.street': 'Katu',
  'contractcard.body.parties.partyAddress.postalCode': 'Postinumero',
  'contractcard.body.parties.partyAddress.country': 'Maa',
  'contractcard.body.parties.partyTermStartDate': 'Lukukauden alkamispäivä',
  'contractcard.body.parties.partyTermStartDateInterval': 'Lukukauden alkamispäivämäärän väli',
  'contractcard.body.parties.partyTermStartDateType': 'Lukukauden alkamispäivämäärän tyyppi',
  'contractcard.body.parties.partyEffectiveFrom': 'Voimassa alkaen',
  'contractcard.body.parties.partyEffectiveTo': 'Tehokas',
  'contractcard.body.parties.partyTermEndDate': 'Lukukauden päättymispäivä',
  'contractcard.body.parties.partyTermEndDateInterval': 'Lukukauden päättymispäivämäärän väli',
  'contractcard.body.parties.partyTermEndDateType': 'Määräajan päättymispäivämäärän tyyppi',
  'contractcard.body.parties.partyCoverages': 'Juhlakannet',
  'contractcard.body.coverages.coverageCode': 'Kattavuuskoodi',
  'contractcard.body.coverages.coverageType': 'Tyyppi',
  'contractcard.body.coverages.coverageStatus': 'Status',
  'contractcard.body.coverages.insuredId': 'Vakuutettu osapuoli',
  'contractcard.body.coverages.coverageSumInsured': 'Vakuutussumma',
  'contractcard.body.coverages.coverageEffectiveFrom': 'Voimassa alkaen',
  'contractcard.body.coverages.coverageTermStartDate': 'Lukukauden alkamispäivä',
  'contractcard.body.coverages.coverageTermStartDateType': 'Lukukauden alkamispäivämäärän tyyppi',
  'contractcard.body.coverages.coverageTermStartDateInterval': 'Lukukauden alkamispäivämäärän väli',
  'contractcard.body.paymentPlans.partyName': 'Puolueen nimi',
  'contractcard.body.paymentPlans.paymentPlanFrequency': 'Maksusuunnitelman tiheys',
  'contractcard.body.paymentPlans.paymentPlanAmount': 'Maksun määrä',
  'contractcard.body.paymentPlans.paymentPlanStatus': 'Status',
  'contractcard.body.paymentPlans.paymentPlanStartDate': 'Aloituspäivämäärä',
  'contractcard.body.paymentPlans.paymentPlanStartDateInterval': 'Aloituspäivämäärän aikaväli',
  'contractcard.body.paymentPlans.paymentPlanStartDateType': 'Aloituspäivämäärän tyyppi',
  'contractcard.body.paymentPlans.paymentPlanStartDateIntervalType': 'Aloituspäivämäärän aikavälin tyyppi',
  'contractcard.body.investmentPlans.invPlanName': 'Nimi',
  'contractcard.body.investmentPlans.invPlanCode': 'Koodi',
  'contractcard.body.investmentPlans.invPlanStatus': 'Status',
  'contractcard.body.investmentPlans.invPlanStartDate': 'Aloituspäivämäärä',
  'contractcard.body.investmentPlans.invPlanStartDateInterval': 'Aloituspäivämäärän aikaväli',
  'contractcard.body.investmentPlans.invPlanStartDateType': 'Aloituspäivämäärän aikavälin tyyppi',
  'contractcard.body.investmentPlans.invPlanEndDate': 'Päättymispäivä',
  'contractcard.body.investmentPlans.invPlanEndDateType': 'Päättymispäivämäärän tyyppi',
  'contractcard.body.investmentPlans.invPlanEndDateInterval': 'Päättymispäivämäärän aikaväli',
  'contractcard.body.investmentPlans.invPlanAllocation.allocationCode': 'Koodi',
  'contractcard.body.investmentPlans.invPlanAllocation.allocationName': 'Nimi',
  'contractcard.body.investmentPlans.invPlanAllocation.allocationPercentage': 'Prosenttiosuus',
  'contractcard.body.investmentPlans.invPlanAllocation.allocationStatus': 'Status',
  'contractcard.transitives.createdAt': 'Luotu',
  'contractcard.transitives.updatedAt': 'Päivitetty',
  'contractcard.transitives.updatedTreeAt': 'Päivitetty puu',
  'contract.status.active': 'Aktiivinen'
}