export const fi = {
  'document.title': 'DigiExpress',
  'eveli.textSeparatorColon': ':',
  'eveli.noValueIndicator': '--',
  'eveli.permissions.none.title': 'Joitain meni väärin!',
  'eveli.permissions.none.desc1': 'Sinulla ei ole oikeuksia tämän sovelluksen käyttöön',
  'eveli.permissions.none.desc2': 'Ota yhteyttä teidän käyttöoikeuksista vastaan henkilöön',
  'tasksView.title': 'Tehtävät',
  'taskDialog.priority': 'Prioriteetti',
  'taskDialog.subject': 'Aihe',
  'taskDialog.dueDate': 'Eräpäivä',
  'taskDialog.assignedTo': 'Käsittelijän rooli',
  'taskDialog.assignedUser': 'Käsittelijä',
  'taskDialog.status': 'Tila',
  'taskDialog.task': 'Tehtävä',
  'taskDialog.category': 'Tyyppi',
  'taskDialog.source': 'Lähde',
  'taskDialog.additionalInfo': 'Lisätieto',
  'task.priority.low': 'Ei kiireellinen',
  'task.priority.normal': 'Normaali',
  'task.priority.high': 'Kiire',
  'task.dueDate': 'Eräpäivä',
  'task.customerMessages': 'Asiakkaiden viestit',
  'task.edit': 'Muokkaa tehtävää',
  'task.customerName': 'Asiakkaan nimi',
  'task.subject': 'Aihe',
  'task.additionalInfo': 'Lisätiedot',
  'task.metaData': 'Metatiedot',
  'task.status.new': 'Uusi',
  'task.status.open': 'Käsittelyssä',
  'task.status.completed': 'Valmis',
  'task.status.rejected': 'Ei käsittelyä',
  'task.status.transferred': 'Siirretty',
  'task.status.delegated': 'Delegoitu',
  'task.status.waiting': 'Odottaa',
  'task.pdf.options.select.CUSTOMER_NAME': 'Customer name',
  'task.pdf.options.select.CUSTOMER_SSN': 'Customer SSN',
  'task.pdf.options.select.EXTERNAL_COMMENTS': 'Customer messages',
  'task.pdf.options.select': 'PDF Printing options',
  'task.pdf.print': 'Print PDF',
  'task.pdf.options.select.desc': 'The form will be printed as a PDF which includes the additional options you select here.',
  'task.form.review': 'Avaa lomake',
  'task.created': 'Luotu',
  'task.updated': 'Päivitetty',
  'task.comments.external.createTask': 'Luo tehtävä ennen ulkoisten kommenttien lisäämistä',
  'task.comments.internal.createTask': 'Luo tehtävä ennen sisäisten kommenttien lisäämistä',
  'task.attachments.createTask': 'Luo tehtävä ennen liitteiden lataamista',
  'task.comments.external.added': 'Sisäinen kommentti tallletettu',
  'task.feedback.publishedSaved': 'Palautemuutokset tallennettu',
  'internalComments': 'Sisäiset kommentit',
  'externalComments': 'Asiakas viestit',
  'comment.store': 'Tallenna',
  'comment.add': 'Lisää kommentti',
  'comment.addInternal': 'Lisää sisäinen kommentti',
  'comment.addExternal': 'Viesti/palaute asiakkaalle',
  'taskButton.addTask': 'Lisää tehtävä',
  'taskButton.refresh': 'Tarkista uudet tehtävät',
  'taskButton.accept': 'Hyväksy',
  'taskButton.cancel': 'Takaisin',
  'table.body.emptyDataSourceMessage': 'Ei dataa',
  'table.body.filterRow.filterTooltip': 'Suodatin',
  'table.body.deleteTooltip': 'Poista',
  'table.header.actions': 'Toiminnot',
  'table.pagination.labelDisplayedRows': '{from}-{to} / {count}',
  'table.pagination.labelRowsPerPage': 'Riviä per sivu:',
  'table.pagination.firstPage': 'Ensimmäinen sivu',
  'table.pagination.previousPage': 'Edellinen',
  'table.pagination.nextPage': 'Seuraava',
  'table.pagination.lastPage': 'Viimeinen sivu',
  'table.toolbar.search': 'Etsi',
  'table.toolbar.showColumnsTitle': 'Näytä sarakkeet',
  'table.toolbar.addRemoveColumns': 'Lisää tai poista sarakkeita',
  'taskLink.pdf.open': 'PDF',
  'explorer.login': 'Kirjaudu sisään',
  'locale.fi': 'Suomi',
  'locale.sv': 'Ruotsi',
  'locale.en': 'Englanti',
  'main.articles.all': 'Kaikki Artikkelit',
  'main.links.all': 'Kaikki Linkit',
  'main.services.all': 'Kaikki Palvelut',
  'main.flows.all': 'Kaikki  Palveluprosessit',
  'main.debug': 'Testaa',
  'main.decisions.all': 'Kaikki Päätöstaulut',
  'menu.dashboard': 'Kojelauta',
  'menu.profile': 'Käyttäjän profiili',
  'menu.tasks': 'Tehtävät',
  'menu.forms': 'Dialob',
  'menu.queues': 'Queues',
  'menu.help': 'Ohjeet',
  'menu.processes': 'Monitorointi',
  'menu.logout': 'Kirjaudu ulos',
  'menu.publications': 'Julkaisut',
  'menu.services': 'Palvelut',
  'menu.feedback': 'Palaute',
  'menu.compose': 'Luo uusi',
  'menu.articles': 'Artikkelit',
  'menu.links': 'Linkit',
  'menu.locales': 'Kielet',
  'menu.templates': 'Valmis pohjat',
  'menu.flows': 'Palveluprosessit',
  'menu.decisions': 'Päätöstaulut',
  'menu.debug': 'Testaa',
  'menu.releases': 'Versiot',
  'menu.compare': 'Vertaile',
  'profile.user.name': 'Nimi:',
  'profile.user.email': 'Sähköposti:',
  'profile.user.role': 'Rooli:',
  'button.cancel': 'Peruuta',
  'button.confirmDelete': 'Poista',
  'button.delete': 'Poista tämä palaute',
  'button.delete.template': 'Poista tämä valmispohja',
  'button.delete.link': 'Poista tämä linkki',
  'button.delete.article': 'Poista tämä artikkeli',
  'button.delete.page': 'Poista tämä sivu',
  'button.update': 'Päivitä',
  'button.publish': 'Julkaise',
  'button.accept': 'Hyväksy',
  'button.close': 'Sulje',
  'button.save': 'Save',
  'button.dismiss': 'Sulje',
  'button.select': 'Valita',
  'button.startBatch': 'Start batch',
  'error.minTextLength': 'Annetun arvon pitää olla vähintään {minLength} merkkiä',
  'error.maxTextLength': 'Annetun arvon tulee olla enintään {max} merkkiä pitkä',
  'error.valueRequired': '* Vaaditaan',
  'error.title': 'Virhe!',
  'error.dialob.session': 'Lomaketta ei voida aukaista juuri nyt. Yritä uudelleen myöhemmin',
  'error.errorLoadingData': 'Error during data loading',
  'error.unauthorized.title': 'Käyttöoikeutesi ovat puutteelliset',
  'error.unauthorized.text': 'Ota yhteyttä IT-palveluihin lähettämällä tukipyyntö Tiketin kautta -> Jätä tukipyyntö -> Kirjautumisongelma.',
  'error.unauthorizedAccess': 'Käyttöoikeutesi ovat puutteelliset',
  'error.dataAccess': 'Virhe toiminnassa',
  'error.statusOpenError': 'Required when status is open',
  'error.workflowCreation': 'Virhe konfiguroinnissa, tarkista nimen yksilöllisyys',
  'table.body.editRow.deleteMessage': 'Halutko varmasti poistaa tämän?',
  'workflowTable.title': 'Kokoonpano',
  'workflowTableHeader.name': 'Nimi',
  'workflowTableHeader.formName': 'Lomake',
  'workflowTableHeader.flowName': 'Prosessi',
  'workflowTableHeader.updated': 'Päivitetty',
  'workflowTable.editButton': 'Muokka',
  'workflow.dialogTitle': 'Työnkulku',
  'workflow.name': 'Nimi',
  'workflow.form.formName': 'Lomakkeen nimi',
  'workflow.form.formTag': 'Lomakkeen versio',
  'workflow.flowName': 'Prosessi',
  'processTable.title': 'Työt',
  'processTableHeader.workflow': 'Tyyppi',
  'processTableHeader.status': 'Tila',
  'processTableHeader.created': 'Luotu',
  'processTableHeader.questionnaireId': 'Lomake',
  'processTableHeader.taskRef': 'Tehtävän viite',
  'process.status.ANSWERED': 'Lähetetty',
  'process.status.CREATED': 'Luotu',
  'process.status.ANSWERING': 'Keskeneräinen',
  'process.status.IN_PROGRESS': 'Käsittelyssä',
  'process.status.WAITING': 'Odottaa',
  'process.status.COMPLETED': 'Valmis',
  'process.status.REJECTED': 'Hylätty',
  'spoTasksTableHeader.taskName': 'Nimi',
  'spoTasksTableHeader.status': 'Tila',
  'spoTasksTableHeader.priority': 'Prioriteetti',
  'spoTasksTableHeader.dueDate': 'Eräpäivä',
  'spoTasksTableHeader.assigned': 'Rooli',
  'spoTasksTableHeader.assignedUser': 'Käsittelijä',
  'spoTasksTableHeader.created': 'Luotu',
  'spoTasksTableHeader.clientName': 'Asiakas',
  'spoTasksTableHeader.additionalInfo': 'Info',
  'taskDialog.clientIdentificator': 'Asiakas',
  'Manual': 'Manuaalinen',
  'Protected': 'Suojattu',
  'Normal': 'Normaali',
  'CustomerCreated': 'Asiakas luotu',
  'Internal': 'Sisäinen',
  'task.role.assignedAllUsers': 'Kaikki käyttäjät',
  'task.feedback.published': 'Julkaistu vastaus',
  'confirm.close.title': 'Vahvistus vaaditaan',
  'confirm.unsavedChanges': 'Tallentamattomat muutokset menetetään. Haluatko jatkaa?',
  'task.statistics.statusCount': 'Tilan mukaan',
  'task.statistics.priorityCount': 'Prioriteetin mukaan',
  'task.statistics.daily': 'Päivittäin',
  'task.statistics.overdue': 'Myöhässä',
  'feedback.create.title': 'Luo vastine asiakkaan palautteeseen',
  'feedback.update.title': 'Editoi vastinetta asiakkaan palautteelle',
  'feedback.taskReferenceId': 'Tehtävän viite',
  'feedback.taskReferenceId.short': 'Task Ref',
  'feedback.mainCategory': 'Aihe',
  'feedback.subCategory': 'Tarkempi aihealue',
  'feedback.feedbackValue': 'Asiakkaan palaute',
  'feedback.customerTitle': 'Palautteen otsikko',
  'feedback.myReply': 'Vastaa asiakkaalle',
  'feedback.customerApprovals': 'Asiakkaan suostumukset',
  'feedback.createdBy': 'Luonut',
  'feedback.updatedBy': 'Päivittänyt',
  'feedback.updated': 'Viimeisin päivitys',
  'feedback.notPublished': 'Tätä vastinetta ei ole julkaistu',
  'feedback.isPublished': 'Tämä vastine on julkaistu',
  'feedback.delete.confirmTitle': 'Poista palaute?',
  'feedback.delete.confirmText': 'Haluatko varmasti poistaa tämän palautteen?',
  'feedback.main_topic.employmentimmigration': 'Työllisyys, työikäiset, ikääntyneet ja maahanmuuttajat',
  'feedback.main_topic.youthservice': 'Nuorisopalvelu',
  'feedback.main_topic.freetimeculture': 'Vapaa-aika ja kulttuuri',
  'feedback.main_topic.cityconstruction': 'Kaupunkiympäristö, rakentaminen ja asuminen',
  'feedback.main_topic.exercise': 'Liikunta',
  'feedback.main_topic.communication': 'Viestintä ja markkinointi',
  'feedback.sub_topic.otherfeedback': 'Muu palaute',
  'feedback.sub_topic.familywithchildren': 'Perhe ja lapset',
  'feedback.sub_topic.libraryservices': 'Kirjatopalavelut',
  'feedback.sub_topic.streetmaintservices': 'Katujen kunnossapito',
  'feedback.sub_topic.exercise': 'Liikunta',
  'feedback.sub_topic.brand': 'Brand',
  'help.title': 'Ohjeet',
  'attachmentView.title': 'Liitetiedostot',
  'attachmentTableHeader.size': 'Koko',
  'attachmentTableHeader.created': 'Luotu',
  'attachmentTableHeader.name': 'Aihe',
  'attachmentButton.addAttachment': 'Lisää tiedosto',
  'attachmentButton.downloadAttachment': 'Lataa tiedosto',
  'attachmentButton.deleteAttachment': 'Poista tiedosto',
  'attachment.uploadOk': 'Tiedosto {fileName} ladattu',
  'attachment.uploadFailed': 'Tiedoston {fileName} lataaminen epäonnistui!',
  'attachment.delete.confirmTitle': 'Poista tiedosto?',
  'attachment.delete.confirmText': 'Haluatko varmasti poistaa tiedoston {fileName}?',
  'attachment.deleteFailed': 'Tiedoston {fileName} poistaminen epäonnistui!',
  'publicationsTable.title': 'Julkaisut',
  'publicationsTableHeader.name': 'Julkaisun tunniste',
  'publicationsTableHeader.description': 'Kuvaus',
  'publicationsTableHeader.createdBy': 'Päivittäjä',
  'publicationsTableHeader.created': 'Luotu',
  'publicationsTableHeader.liveDate': 'Päivitetty',
  'publicationsTable.addButton': 'Lisää uusi',
  'publicationsTable.exportButton': 'Lataa ulos',
  'publicationsTable.uploadButton': 'Lataa sisään',
  'publications.external': 'Tämä on ulkoisesti konfiguroitu päivitys, joka astuu voimaan vasta kun muut päivitykset on tehty',
  'publications.changeStatus': 'Muokkaa päivityksen tilaan',
  'publications.currentStatus': 'Nykyisen päivitysen status',
  'publications.remove': 'Poista päivitys',
  'publications.deploy': 'Julkaise nyt',
  'publications.dialogTitle': 'Tee uusi julkaisu',
  'publications.name': 'Julkaisun tunniste',
  'publications.description': 'Kuvaus',
  'publications.workflowTag': 'Workflow versio',
  'publications.wrenchTag': 'theWrench versio',
  'publications.contentTag': 'Sisältöversio',
  'publications.createNewTag': 'Luo uusi versio \"{tag}\"',
  'publications.downloadFailed': 'Julkaisun lataus epäonnistui, syy: {cause}',
  'publications.tagCreationFailed': 'Julkaisun luominen epäonnistui, syy: {cause}',
  'publications.uploadDialogTitle': 'Lataa julkaisu',
  'dialobForm.saveFailed': 'Tallennus epäonnistui',
  'dialobForm.downloadFailed': 'Tallennus epäonnistui',
  'dialobForm.deleteFailed': 'Poisto epäonnistui',
  'dialobForm.review.title': 'Lomakkeen tarkistus',
  'feedback.notenabled': 'Feedback is not enabled for this task',
  'pages': 'Sivut',
  'articles': 'Artikkelit',
  'locale': 'Sijainti',
  'locales': 'Sijainnit',
  'links': 'Linkit',
  'releases': 'Julkaisut',
  'options': 'Valinnat',
  'value': 'Arvo',
  'date': 'Päiväys',
  'description': 'Kuvaus',
  'name': 'Nimi',
  'download': 'Lataa JSON',
  'status': 'Status',
  'created': 'Luotu',
  'remove': 'Poista',
  'site.content.empty': 'Sivustolla ei ole sisältöä! Luo sisältöä ennen julkaisua!',
  'composer.select.article': 'Valitse artikkelit',
  'search.field.placeholder': 'Kirjoita hakusana',
  'search.results.title': 'Hakutulokset',
  'search.field.label': 'Haku',
  'search.all': 'Kaikki',
  'search.articles': 'Artikkeleita',
  'search.services': 'Palveluja',
  'search.links': 'Linkkejä',
  'search.templates': 'Templeitit',
  'search.flows': 'Flows',
  'search.decisions': 'Decisions',
  'activities.article.title': 'Artikkeli',
  'activities.locale.title': 'Lokalistointi',
  'activities.page.title': 'Sivu',
  'activities.link.title': 'Linkki',
  'activities.release.title': 'Julkaisu',
  'activities.migration.title': 'Migraatio',
  'migration.create': 'Migraatio data',
  'activities.migration.desc': 'Käytä JSON tiedosta tämän portaalin migrointiin',
  'activities.templates.title': 'Mallipohjat',
  'activities.version.composer': 'Composer: build version {version}, build date {date}',
  'activities.version.core': 'Core: build version {version}, build date {date}',
  'dialog.about.title': 'DigiExpress',
  'dialog.about.preamble': 'DigiExpress perustuu avoimeen lähdekoodiin',
  'templates': 'Mallipohjat',
  'template.name': 'Nimi',
  'template.name.desc': 'Mallipohjan nimi',
  'template.create': 'Luo mallipohja',
  'template.edit': 'Muokkaa mallipohjaa',
  'template.type': 'Mallipohjan tyyppi',
  'template.page': 'Sivun mallipohja',
  'template.desc': 'Kuvaus',
  'template.delete': 'Poista mallipohja',
  'template.newpage.none': 'Tyhjä',
  'templates.templatesview.description': 'Mallistapohjasta voidaan luoda uusi sivu',
  'services': 'Palvelut',
  'services.create': 'Luo palvelu',
  'services.add': 'Lisää palvelu',
  'services.change': 'Muokaa olemassa olevaa palvelua',
  'services.edit': 'Muokaa palvelua',
  'services.technicalname': 'Palvelun nimi',
  'services.selected': 'Valitse palavelu',
  'services.modeselect.title': 'Configuration options',
  'services.modeselect.label': 'Valitse',
  'services.devmode.label': 'Kehitystila',
  'services.devmode.tooltip': 'Kehitystila',
  'services.disabledmode.label': 'Ei käytössä',
  'services.disabledmode.helper': 'Palvelu ei ole portaalissa näkyvissä',
  'services.disabledmode.tooltip': 'Ei käytössä',
  'services.assignableMode.label': 'Palvelun käytöntila',
  'services.assignableMode.helper': 'Assignable manually: Can be assigned directly to customer',
  'services.assignableMode.tooltip': 'Palvelun käytöntila',
  'services.none.label': 'Ei valintaa',
  'services.none.helper': 'Perustila',
  'services.none.tooltip': 'Ei eritystilaa',
  'services.anonmode.helper': 'Anonyymi tila: Palvelu näkyy SEKÄ anonyymeille ja todennetuille käyttäjille.',
  'services.anonmode.label': 'Anonyymi käyttäjä',
  'services.anonmode.tooltip': 'Anonyymi käyttäjä',
  'services.flowName': 'Workflow nimi',
  'services.formName': 'Dialob lomakkeen nimi',
  'services.formName.description': 'Lomakkeen nimi',
  'services.formTag': 'Lomakkeen versionumero',
  'services.formTag.description': 'Lomakkeen versionnumero',
  'services.startdate': 'Palvelun saataville',
  'services.startdate.description': 'Palvelun julkaisuajankohta',
  'services.enddate': 'Palvelun pois saatavilta',
  'services.enddate.description': 'Palvelu poistuu käytöstä',
  'services.delete': 'Poista palvelu',
  'snack.article.createdMessage': 'Artikkeli luotu',
  'snack.article.deletedMessage': 'Artikkeli poistettu',
  'snack.article.editedMessage': 'Artikkelin muutokset tallennettu',
  'snack.page.createdMessage': 'Sivu luotu',
  'snack.page.deletedMessage': 'Sivu poistettu',
  'snack.page.savedMessage': 'Sivun muutokset tallennettu',
  'snack.page.missingTitle': 'Lisää otsikko kohteelle {locale} artikkelissa {articleName}',
  'snack.link.createdMessage': 'Linkin luominen onnistui',
  'snack.link.deletedMessage': 'Linkki poistettu',
  'snack.link.editedMessage': 'Linkin muutokset tallennettu',
  'snack.workflow.createdMessage': 'Palvelu luotu onnistuneesti',
  'snack.workflow.deletedMessage': 'Palvelu poistettu',
  'snack.workflow.editedMessage': 'Palvelumuutokset tallennettu',
  'snack.locale.createdMessage': 'Kieli-asetuksen luominen onnistui',
  'snack.locale.enabled': 'Kieliasetus käytössä',
  'snack.locale.disabled': 'Kieliasetus poistettu käytöstä',
  'snack.template.createdMessage': 'Malli luotiin onnistuneesti',
  'snack.template.deletedMessage': 'Malli poistettu',
  'snack.template.editedMessage': 'Mallin muutokset tallennettu',
  'snack.release.createdMessage': 'Julkaisun luominen onnistui',
  'snack.release.deletedMessage': 'Julkaisu poistettu',
  'snack.migration.createdMessage': 'Sivuston tiedot päivitetty',
  'toolbar.save': 'Tallenna',
  'toolbar.stencil': 'theStencil',
  'toolbar.wrench': 'theWrench',
  'toolbar.menu': 'Valikko',
  'toolbar.help': 'Tuki',
  'toolbar.import': 'Tuo dataa',
  'toolbar.tasks': 'Tehtävät',
  'toolbar.about': 'Tietoja',
  'stencil.services.found.none': 'Ei tuloksia',
  'link.type.internal': 'Sisäinen (domainin sisällä)',
  'link.type.external': 'Ulkoinen (domainin ulkopuolella)',
  'link.type.phone': 'Puhelinnumero',
  'link.search.title': 'Etsi linkkejä',
  'link.value': 'Linkin tiedot',
  'sitelocale.label.select.alreadyDefined': 'Tämä lokalisointi on jo käytössä',
  'sitelocale.label.table.editLocaleValue': 'Editoi lokalisointia',
  'locales.label.table.title': 'Lokalisonti tunniste',
  'locales.label.table.value': 'Lokalisointi',
  'locales.label.table.noneSet': 'Ei käännöksiä',
  'locales.enabledMessage': 'Käytössä: Tämän aiheen sisältö näytetään portaalin puolella',
  'locales.disabledMessage': 'Pois käytöstä: Tämän kieliasetuksen sisältö piilotetaan portaalin puolelta. Sisältöä voi edelleen muokata.',
  'transferlist.noItemsSelected': 'Ei valintoja',
  'transferlist.search': 'Hae',
  'transferlist.noSearchResults': 'Ei tuloksia',
  'explorer.tabs.links': 'Lomakkeet',
  'explorer.tabs.services': 'Palvelut',
  'imports.select': 'Valitse tuotava tiedosto',
  'imports.import.action': 'Tuonti valittu',
  'article.order': 'Artikkelin järjestysnumero',
  'article.order.view': 'Näytä Artikkelien järjestys',
  'article.select': 'Valitse Artikkeli',
  'article.links.selectedlinks': 'Valitse Linkki',
  'article.composer.title': 'Luo uusi artikkeli',
  'article.composer.parent': 'Emoartikkeli',
  'article.composer.parent.unselected': 'Ei valittu',
  'article.create': 'Luo artikkeli',
  'article.name': 'Artikkelin nimi',
  'article.delete.title': 'Poista tämä artikkeli pysyvästi?',
  'article.delete.description': 'Artikkelin poistaminen poistaa sen ja siihen yhdistetyt sivut koko sovelluksesta.',
  'article.edit.title': 'Muokkaa artikkelia',
  'article.edit.parent': 'Juuri Artikkeli',
  'article.devmode.helper': 'Jos kehitysverisio on aktiivinen niin Artikkeli näkyy ainoastaan kehitysympäristössä',
  'article.devmode': 'Julkaisu tyyppi',
  'articleservices': 'Artikkelin palvelut: {name}',
  'articlelinks': 'Artikkelin linkit: {name}',
  'article.composer.orderhelper': 'Mitä pienempi numero sen ylempänän tämä Artikkeli on valinnoissa',
  'article.timestamps.title': 'Apu',
  'button.create': 'Luo',
  'button.add': 'Lisää',
  'button.disable': 'Jatka ja deaktivoi',
  'button.enable': 'Jatka ja salli käyttö',
  'button.apply': 'Salli muutokset ja jatka',
  'button.view.all.locales': 'Näytä kaikki sijainnit',
  'button.view.all.releases': 'Näytä kaikki julkaisut',
  'button.view.all.templates': 'Maillipohjat',
  'links.searchAll': 'Etsi linkkejä',
  'link.article.select': 'Valitse artikkeli',
  'link.type': 'Tyyppi',
  'link.content': 'Linkki URL / reitti',
  'link.composer.title': 'Luo uusi linkki',
  'link.composer.valuehelper': 'URL / linkin reitti (http://www.example.com)',
  'link.edit.title': 'Muokkaa linkkiä',
  'link.delete.title': 'Poista linkki pysyvästi?',
  'link.delete': 'Linkin poistaminen poistaa sen lopullisesti koko sovelluksesta ja sen kaikki yhteydet artikkeleihin/sivuihin menetetään.',
  'resource.edit.links': 'Lisää ja poista artikkelilinkkejä',
  'links.change': 'Muokkaa linkkejä',
  'link.create': 'Luo linkki',
  'link.devmode': 'Kehitysversion aktivointi',
  'locale.create': 'Luo lokalisointi',
  'locale.disable.title': 'Poista lokalisointi käytöstä?',
  'locale.enable.title': 'Salli lokalisoinnin käyttö?',
  'locale.disable': 'Kaikki tätä lokalisointi käyttävät sivut ovat käyttöliittymässä piilossa. Sivuja voidaan edelleen muokata.',
  'locale.enable': 'Kaikki tätä lokalisointi käyttävät sivut ovat esillä käyttöliittymässä.',
  'locale.composer.title': 'Luo uusi lokalisointi',
  'locale.composer.placeholder': 'Kaksikirjaiminen kielitunniste',
  'locale.composer.helper': 'Kaksikirjaiminen kielitunniste',
  'locale.overview': 'Lokalisointien yhteenveto',
  'locales.content': 'Sivulta löytyy lokalisoitua sisältöä',
  'locales.nocontent': 'Sivulta ei löydy lokalisoitua',
  'locales.nopage': 'Artikkelissa ei löyd tätä kieliversiota',
  'locales.label.table.locale': 'Kielikoodi',
  'newpage.title': 'Luo uusi sivu',
  'newpage.info': 'Sivulla on sisällöstä ja sen tulee olla yhdistetty artikkeliin.',
  'newpage.article.info': 'Vahvista sivun luominen artikkelille: {article} sijainnilla: {locale}',
  'page.create': 'Luo sivu',
  'page.delete.dialog.title': 'Poista sivu tästä artikkelista',
  'pages.add': 'Lisää sivu',
  'pages.change': 'Muuta sivun lokalisointia',
  'pages.select.locale': 'Muokkaa lokalisoitua sivun sisältöä',
  'pages.select.locale.edit.desc': 'Ota käyttöön vierekkäinen muokkaus yhdellä välilehdellä valitsemalla kaksi kieltä.',
  'pages.edit.language1': 'Muokkaa tätä kieltä',
  'pages.edit.language2': 'Muokkaa tätä kieltä vierekkäin',
  'pages.edit.currentlyEditing.language2': 'Muokkaus vierekkäin',
  'pages.edit.currentlyEditing.language1': 'Muokkaa tätä kieltä',
  'pages.change.info': 'Valitse sivu tästä artikkelista ja anna uusi arvo sen sijainnille.',
  'pages.change.devmode': 'Muuta sivun kehitystilaa',
  'pages.change.devmode.info': 'Valitse sivu tästä artikkelista ja muuta sen kehitystapaa.',
  'pages.devmode': 'Kehitysversio aktiivinen',
  'pages.delete': 'Poista sivu',
  'pages.edit.selectpage': 'Valitse sivue',
  'pages.edit.selectTargetLocale': 'Valitse kieli',
  'release.create': 'Luo julkaisu',
  'release.composer.title': 'Luo uusi julkaisu',
  'release.composer.label': 'Version nimi nimi',
  'release.composer.note': 'Info',
  'release.composer.helper': 'Valinnainen lisätieto tulevaa käyttöä varten',
  'release.desc': 'Katso kaikki julkaisut ja lataa kaikki sivuston sisältö JSON-muodossa. Tarkempia tietoja tietyistä julkaisuista ja niiden sisällöstä on kaaviossa.',
  'release.delete.title': 'Poista päivitys?',
  'release.delete.desc': 'Haluatko poista päivityksen pysyvästi',
  'releases.view.note': 'Lisä tietoa',
  'releases.view.tag': 'Nimi',
  'releases.view.created': 'Luotu',
  'releases.view.download': 'JSON alas lataus',
  'buttons.create': 'Lisää',
  'buttons.apply': 'Laita voimaan',
  'buttons.delete': 'Poista',
  'buttons.copy': 'Kopio',
  'button.compose': 'Luo',
  'buttons.download': 'Lataa',
  'activities.flows.title': 'Workflow',
  'activities.flows.desc': 'A a sequence of tasks which are defined by using simple configuration language.',
  'activities.decisions.title': 'Decisions',
  'activities.decisions.desc': 'A decision table that can be used to make decisions based on input data.',
  'activities.services.title': 'Services',
  'activities.services.desc': 'A piece of Java or Groovy code that is embedded inside of a flow as a task.',
  'activities.releases.title': 'Releases',
  'activities.releases.desc': 'A Release is a snapshot of all site content at one certain point of time.',
  'activities.releases.desc.additional': 'Each Release can be downloaded to be used for production or backup purposes, or can be branched for further editing. This will replace all current assets so make sure any changes are saved.',
  'activities.releases.view': 'View all releases',
  'activities.compare.title': 'Compare',
  'activities.compare.desc': 'Compare two releases to see what has changed between them.',
  'activities.compare.view': 'Compare',
  'activities.debug.title': 'Debug',
  'activities.debug.desc': 'Simulate execution of an asset. Can be done via form input, JSON input, or by using a CSV file.',
  'activities.debug.view': 'Simulate',
  'activities.assets.saveSuccess': 'Saved asset: {name}',
  'flows': 'Flows',
  'migrations.title': 'Migration',
  'migrations.create': 'Perform migration',
  'migrations.select': 'Select tag.json file',
  'flows.edit.title': 'Edit flow',
  'flows.copyas.title': 'Copy flow as',
  'flows.delete.title': 'Delete flow',
  'flows.delete.error.title': 'Failed to delete flow',
  'flows.delete.content': 'Are you sure you want to delete FLOW: {name}?',
  'flows.deleted.message': 'Deleted FLOW: {name}',
  'flows.simulate.title': 'Debug the flow',
  'flows.composer.title': 'Create new FLOW',
  'flows.composer.copyTitle': 'Copy FLOW as',
  'flows.composer.createdMessage': 'Created FLOW: {name}',
  'flows.composer.copiedMessage': 'Copied FLOW {name} as: {newName}',
  'flows.composer.errorsTitle': 'Failed to create FLOW',
  'flows.composer.assetName': 'Unique name for the FLOW',
  'flows.autocomplete.task.create': 'Create new asset',
  'flows.autocomplete.task.link': 'Link selected asset',
  'flows.autocomplete.task.searchField': 'Search for asset...',
  'flows.autocomplete.task.searchPlaceholder': 'Asset name or description',
  'flows.autocomplete.task.selectType': 'Select asset type to link',
  'flows.autocomplete.task.searchHelper': 'Matches asset name and description',
  'flows.autocomplete.task.searchResults': 'Search results',
  'flows.autocomplete.task.snackbar.created': 'Created new {type}: {name}',
  'flows.autocomplete.task.snackbar.creating': 'Creating new {type}: {name}',
  'flows.graph.show': 'Show flow graph',
  'flows.graph.hide': 'Hide flow graph',
  'services.searchAll': 'Search all services',
  'services.edit.title': 'Edit service',
  'services.copyas.title': 'Copy service as',
  'services.delete.title': 'Delete service',
  'services.delete.error.title': 'Failed to delete SERVICE',
  'services.delete.content': 'Are you sure you want to delete SERVICE: {name}?',
  'services.deleted.message': 'Deleted SERVICE: {name}',
  'services.simulate.title': 'Debug the service',
  'services.composer.title': 'Create new SERVICE',
  'services.composer.copyTitle': 'Copy SERVICE as',
  'services.composer.createdMessage': 'Created SERVICE: {name}',
  'services.composer.copiedMessage': 'Copied SERVICE {name} as: {newName}',
  'services.composer.errorsTitle': 'Failed to create SERVICE',
  'services.composer.assetName': 'Unique name for the SERVICE',
  'decisions.name': 'Name',
  'decisions.desc': 'Description',
  'decisions.simulate.title': 'Debug the decision',
  'decisions.hitpolicy': 'Hit-policy',
  'decisions.edit.title': 'Edit decision',
  'decisions.copyas.title': 'Copy decision as',
  'decisions.delete.error.title': 'Failed to delete DECISION',
  'decisions.delete.title': 'Delete decision',
  'decisions.delete.content': 'Are you sure you want to delete DECISION: {name}?',
  'decisions.deleted.message': 'Deleted DECISION: {name}',
  'decisions.deleteConfirmTitle': 'Confirm Delete',
  'decisions.deleteConfirmText': 'Are you sure you want to delete this {type}?',
  'decisions.type.row': 'row',
  'decisions.type.column': 'column',
  'decisions.table.hitpolicy': 'Matches',
  'decisions.composer.title': 'Create new DECISION',
  'decisions.composer.copyTitle': 'Copy DECISION as',
  'decisions.composer.createdMessage': 'Created DECISION: {name}',
  'decisions.composer.copiedMessage': 'Copied DECISION {name} as: {newName}',
  'decisions.composer.errorsTitle': 'Failed to create DECISION',
  'decisions.composer.assetName': 'Unique name for the DECISION',
  'decisions.toolbar.addInputColumn': 'Add input column',
  'decisions.toolbar.addOutputColumn': 'Add output column',
  'decisions.toolbar.addRow': 'Add row',
  'decisions.toolbar.csvDownload': 'Download CSV, with separator \';\'',
  'decisions.toolbar.csvUpload': 'Upload CSV, with separator \';\'',
  'decisions.toolbar.nameAndHitpolicy': 'Name and hit-policy',
  'decisions.toolbar.organize.rows.columns': 'Organize rows and columns',
  'decisions.toolbar.organize.action': 'Select action',
  'decisions.toolbar.organize.action.helper': 'Move column or row based on name/index',
  'decisions.toolbar.organize.action.expression': 'Select expression',
  'decisions.toolbar.organize.action.expression.column': 'Select column',
  'decisions.toolbar.organize.action.deleteColumn': 'Delete whole column',
  'decisions.toolbar.organize.action.deleteRow': 'Delete whole row',
  'decisions.toolbar.organize.action.deleteRow.contents': 'Row contents',
  'decisions.toolbar.organize.action.move.from.column': 'Column to move',
  'decisions.toolbar.organize.action.move.from.row': 'Row to move',
  'decisions.toolbar.organize.action.move.to.column': 'New Position',
  'decisions.toolbar.organize.action.move.to.row': 'New Position',
  'decisions.table.inputs.title': 'Matching rules',
  'decisions.table.outputs.title': 'Results',
  'decisions.header.dialog.title': 'Decision table: {name}, column: {column}',
  'decisions.cells.dialog.title': 'Decision table: {name}, column: {column}, value: {value}',
  'decisions.cells.dialog.title.simple': 'Edit Value',
  'decisions.header.dialog.title.simple': 'Edit Header',
  'decisions.cells.dialog.title.intl': 'Edit Localized Value',
  'decisions.cells.newvalue.boolean': 'Enter new value',
  'decisions.cells.newvalue.boolean.helper': 'Select boolean value',
  'decisions.cells.newvalue.boolean.empty': 'No value selected',
  'decisions.cells.newvalue.date.operator': 'Operator',
  'decisions.cells.newvalue.date.start': 'Start date',
  'decisions.cells.newvalue.date.end': 'End date',
  'decisions.cells.newvalue.date.value': 'Date',
  'decisions.cells.newvalue.number.comparisonType': 'Comparison',
  'decisions.cells.newvalue.number.comparisonTypeEmpty': 'Comparison not selected',
  'decisions.cells.newvalue.number.comparisonValue': 'New numerical value',
  'decisions.cells.newvalue.number.comparisonToRange': 'Change to range',
  'decisions.cells.newvalue.number.rangeStart': 'Start',
  'decisions.cells.newvalue.number.rangeEnd': 'End',
  'decisions.cells.newvalue.string.comparisonType': 'Comparison',
  'decisions.cells.newvalue.string.addValue': 'Add new value',
  'decisions.cells.newvalue.string.available': 'Available values',
  'decisions.cells.newvalue.string.selected': 'Selected values',
  'decisions.cells.newvalue.string.empty': 'Comparison not selected',
  'decisions.cells.newvalue.clear': 'Clear current value',
  'decisions.valueSet': 'Define value set',
  'decisions.valueSet.description': 'Value sets can be used to define a predetermined set of values for any input',
  'decisions.valueSet.add': 'Add to value set',
  'decisions.valueSet.current': 'Current value set',
  'dt.header.name': 'Name',
  'dt.header.delete': 'Delete',
  'dt.header.expression': 'Expression',
  'dt.header.dataType': 'Data type',
  'dt.header.script': 'Script',
  'decisions': 'Decisions',
  'program.status.DEPENDENCY_ERROR': 'Dependency Errors',
  'program.status.UP': 'Program is UP',
  'program.status.AST_ERROR': 'Syntax errors',
  'program.status.PROGRAM_ERROR': 'Compiler errors',
  'release.deleted.message': 'Julkaisu {name} poistettu',
  'releases.composer.createdMessage': 'Luotu uusi julkaisu {name}',
  'releases.view.action': 'Action',
  'releases.composer.title': 'Create new release',
  'releases.composer.assetName': 'Release name',
  'releases.composer.assetDesc': 'Release description',
  'releases.composer.errorsTitle': 'Error while creating release',
  'releases.button.compare': 'Compare',
  'releases.button.branch': 'Create new branch',
  'releases.button.checkout': 'Checkout',
  'releases.button.release': 'Release',
  'releases.button.details': 'View release assets',
  'releases.default.name': 'default',
  'releases.default.note': 'This is the default branch that you can go back to',
  'releases.latest.name': 'latest',
  'releases.latest.note': 'These are current assets with the latest changes that can be released',
  'releases.details.title': 'Release assets: {name}',
  'release.branch.creating': 'Creating new branch: {name}',
  'release.branch.created': 'Created new branch: {name}',
  'release.branch.deleting': 'Deleting branch: {name}',
  'release.branch.deleted': 'Deleted branch: {name}',
  'release.branch.checkout': 'Checked out to branch: {name}',
  'debug.toolbar.options': 'Options',
  'debug.toolbar.selectAsset': 'Select asset to debug',
  'debug.toolbar.inputCsv': 'Define input data as a CSV',
  'debug.toolbar.inputForm': 'Define input data as a FORM',
  'debug.toolbar.inputJson': 'Define input data as a JSON',
  'debug.toolbar.execute': 'Execute',
  'debug.toolbar.noAsset': 'Select asset from options',
  'debug.toolbar.openAsset': 'Open',
  'debug.toolbar.download': 'Download results as CSV',
  'debug.input.noAsset': 'There is no ASSET selected',
  'debug.input.form': 'Debug using FORM',
  'debug.input.formTitle': 'Define inputs',
  'debug.input.form.invalid.integer': 'Value must be an integer',
  'debug.input.form.invalid.number': 'Value must be a number',
  'debug.input.form.invalid.range': 'Value must be in the specified range',
  'debug.input.json': 'Debug using JSON',
  'debug.input.jsonTitle': 'Define JSON input',
  'debug.input.csvUpload': 'Debug using CSV',
  'debug.input.csvFile': 'Upload CSV FILE',
  'debug.input.csvFileTitle': 'Upload CSV file - semicolon-delimited (;)',
  'debug.input.csvFileOrText': 'Or paste CSV contents - semicolon-delimited (;)',
  'debug.inputs.fieldName': 'Field Name',
  'debug.inputs.fieldValue': 'Field Value',
  'debug.select.title': 'Select asset to debug',
  'debug.select.assetType': 'Asset type to filter',
  'debug.select.searchField': 'Asset name to search',
  'debug.select.searchHelper': 'Search matches asset name or description',
  'debug.select.searchPlaceholder': 'Keyword to search',
  'debug.select.searchResults': 'Found assets',
  'debug.select.confirm': 'Select',
  'debug.inputs.format': 'Asset input format: {type}',
  'debug.asset.execute.errors': 'Execution errors',
  'debug.asset.execute.outputs.dt.json': 'Matched row(s)',
  'debug.asset.execute.outputs.dt.rejects': 'Rejected row(s)',
  'debug.asset.execute.outputs.flow.step': 'Step name: {name}, status: {status}',
  'debug.csv.row': 'Data row: {row}',
  'debug.csv.download': 'Download results as CSV',
  'debug.csv.download.delimiter': 'Choose a delimiter for the CSV file',
  'debug.csv.download.delimiter.semicolon': 'Semicolon (;)',
  'debug.csv.download.delimiter.comma': 'Comma (,)',
  'debug.csv.download.options': 'Export options',
  'debug.csv.download.wrap': 'Wrap cells containing delimiters with quotes',
  'compare.tip': 'Select releases to compare below. Base is the starting point of the comparison, and target is the release that will be compared to the base.',
  'compare.base': 'Select base release',
  'compare.target': 'Select target release',
  'compare.dialog.title': 'Comparing releases {base} and {target}',
  'compare.dialog.line': 'Inline',
  'compare.dialog.side': 'Vierekkäin',
  'menu.activities': 'Aktiviteetit',
  'feedback.all': 'Kaikki palaute',
  'task.feedback.none': 'Palautetta ei ole saatavilla',
  'queues.all': 'Jonot',
  'consumers.all': 'Kuluttajat',
  'queue.config.none': 'Ladataan',
  'queue.config.consumerName': 'Kuluttajan nimi',
  'queue.config.routingKey': 'Reititysavain',
  'queue.config.consumerStatus': 'Status',
  'queue.config.comment': 'Kommentti',
  'queue.config.queueName': 'Jonon nimi',
  'queue.config.createdAt': 'Luotu klo',
  'queue.config.createdBy': 'Luonut',
  'queue.all_deliveries.title': 'Kaikki toimitukset',
  'queue.all_deliveries.created': 'Luotu',
  'queue.all_deliveries.consumerComment': 'Kommentti',
  'queue.all_deliveries.status': 'Status',
  'queue.all_deliveries.messageId': 'Viestin tunnus',
  'queue.all_deliveries.consumerId': 'Kuluttajatunnus',
  'queue.all_messages.title': 'Kaikki viestit',
  'queue.all_messages.routingKey': 'Reititysavain',
  'queue.all_messages.messageId': 'Viestin tunnus',
  'queue.all_messages.bodyId': 'Rungon tunnus',
  'queue.all_messages.bodyType': 'Vartalotyyppi',
  'queue.all_messages.status': 'Status',
  'queue.all_messages.body': 'Runko',
  'queue.all_messages.created': 'Luotu',
  'workflows': 'Workflows',
  'explorer.pages': 'Sivut',
  'articles.searchAll': 'Search all articles',
  'composer.article.selected': 'Selected Articles',
  'resource.edit.workflows': 'Workflows',
  'workflow.delete': 'Delete',
  'workflow.edit': 'Edit',
  'eveli.table.menu.filter.filterBy': 'Poistaa',
  'eveli.table.menu.filter.showAllItems': 'Muokata',
  'eveli.table.menu.sort.ascending': 'Suodatusperuste',
  'eveli.table.menu.sort.descending': 'Näytä kaikki ajat',
  'eveli.table.menu.sort.clearSorting': 'Nouseva',
  'eveli.table.menu.sort.chooseCols': 'Laskeva',
  'eveli.table.menu.sort.colsReset': 'Selkeä lajittelu',
  'eveli.table.dialog.columns.chooseCols': 'Valitse Sarakkeet',
  'eveli.table.footer.tasks.total': 'Nollaa sarakkeet',
  'eveli.table.footer.tasks.rowsPerPage': 'Valitse Sarakkeet',
  'eveli.table.footer.pageNumber': 'Kokonais',
  'eveli.table.footer.rowsPerPage': 'Rivejä per sivu',
  'eveli.table.drawer.buttons.colsButton': 'Rivejä per sivu',
  'eveli.table.drawer.buttons.filtersButton': 'Kokonais',
  'eveli.table.resetAll': 'Sarakkeet',
  'eveli.table.drawer.title.columns': 'Painikkeet',
  'eveli.table.drawer.title.filters': 'Nollaa kaikki',
  'eveli.table.drawer.title.saved-filters': 'Henkilökohtaiset pöytäprofiilit',
  'eveli.table.drawer.title.export-data': 'Vie tiedot',
  'eveli.error.general': 'Hups, havaitsimme virheen!',
  'eveli.error.notFound': 'Hups, etsimääsi asiaa ei löydy!',
  'eveli.error.backToHome': 'Palaa kotisivullemme',
  'eveli.userProfile.title': 'Käyttäjäprofiili',
  'eveli.userProfile.id': 'Id',
  'eveli.userProfile.displayName': 'Näyttönimi',
  'eveli.userProfile.firstAndLastName': 'Koko nimi',
  'eveli.userProfile.created': 'Luotu',
  'eveli.userProfile.updated': 'Päivitetty',
  'eveli.userProfile.firstName': 'Etunimi',
  'eveli.userProfile.lastName': 'Sukunimi',
  'eveli.userProfile.email': 'Sähköposti',
  'eveli.userProfile.notificationSettings': 'Ilmoitusasetukset',
  'eveli.userProfile.userRoles': 'Minun roolini',
  'eveli.userProfile.userPermissions': 'Minun luvat',
  'eveli.userProfile.editDetails': 'Muokkaa henkilötietoja',
  'eveli.userProfile.currentDetails': 'Nykyiset tietoni',
  'eveli.userProfile.tenantConfig.select.LOGIN_BUTTON': 'Kirjautumispainike',
  'eveli.userProfile.tenantConfig.select.external-deployment': 'Ulkoinen käyttöönotto',
  'eveli.userProfile.tenantConfig.select.external-deployment.desc': 'Omaisuudet tulevat nimenomaisesti ympäristökohtaisesta tietolähteestä, joka toteuttaa ExternalDeploymentProviderin',
  'eveli.userProfile.tenantConfig.select.feedback-visually-disabled': 'Palaute visuaalisesti poistettu käytöstä',
  'eveli.userProfile.tenantConfig.select.feedback-visually-disabled.desc': 'Näytä/piilota palauteominaisuus käyttöliittymästä',
  'eveli.userProfile.tenantConfig.select.queues-visually-disabled': 'Jonot visuaalisesti poissa käytöstä',
  'eveli.userProfile.tenantConfig.select.queues-visually-disabled.desc': 'Näytä/piilota Jonot-ominaisuus käyttöliittymästä',
  'eveli.userProfile.tenantConfig.select.stencil-disabled': 'Stencil pois käytöstä',
  'eveli.userProfile.tenantConfig.select.stencil-disabled.desc': 'Eveli on konfiguroitu uudelleen poistamaan Stencil',
  'eveli.userProfile.tenantConfig.select.wrench-disabled': 'theWrench poistettu käytöstä',
  'eveli.userProfile.tenantConfig.select.wrench-disabled.desc': 'Eveli on konfiguroitu uudelleen jakoavaimen poistamiseksi',
  'eveli.userProfile.tenantConfig.select.wrench-only': 'Vain jakoavain',
  'eveli.userProfile.tenantConfig.select.wrench-only.desc': 'Eveli on konfiguroitu uudelleen sisältämään vain jakoavaimen',
  'eveli.userProfile.tenantConfig.select.batches': 'Erät',
  'eveli.userProfile.tenantConfig.select.batches.desc': 'Ota eräkäsittelyominaisuudet käyttöön / poista se käytöstä',
  'eveli.userProfile.tenantConfig.select.eveli_publication_only': 'Vain Evelin julkaisu',
  'eveli.userProfile.tenantConfig.select.eveli_publication_only.desc': 'Omaisuuden muokkaaminen on poistettu käytöstä – ne tulevat suoraan julkaisusta',
  'eveli.userProfile.tenantConfig.select.smart_tables': 'Älykkäät pöydät',
  'eveli.userProfile.tenantConfig.select.smart_tables.desc': 'Kaikki taulukot ovat pysyviä - ne tallentavat käyttäjän määrittämät kokoonpanot',
  'eveli.userProfile.tenantConfig.select.stencil_locale_filter': 'Stensiilialuesuodatin',
  'eveli.userProfile.tenantConfig.select.stencil_locale_filter.desc': 'Määritä kieliasetusten suodatuksen käyttöliittymäkomponentin näkyvyys Stencilissä',
  'eveli.userProfile.tenantConfig.select.user_profile': 'Käyttäjäprofiili käytössä',
  'eveli.userProfile.tenantConfig.select.user_profile.desc': 'Näytä/piilota käyttäjäprofiiliominaisuus käyttöliittymästä',
  'eveli.userProfile.tenantConfig.select.smart_task': 'Älykäs tehtävänäkymä',
  'eveli.userProfile.tenantConfig.select.smart_task.desc': 'Tehtävän muokkaamista tehostetaan vetämällä ja pudottamalla / yhdistetyllä muokkauksella / kirkkailla väreillä',
  'eveli.userProfile.tenantConfig.select.smart_task_audit': 'Älykäs tehtävätarkastus',
  'eveli.userProfile.tenantConfig.select.smart_task_audit.desc': 'Tarkat lisänäkymät ovat käytössä tehtävän tarkastamista/virheenkorjausta varten',
  'eveli.userProfile.tenantConfig.select.visual_accommodation': 'Visuaalinen muokautus',
  'eveli.userProfile.tenantConfig.select.visual_accommodation.desc': 'Tietyt painikkeet ja käyttöliittymäkohteet ponnahtavat näkyvyyden parantamiseksi',
  'taskTable.col.header.priority': 'Prioriteetti',
  'taskTable.col.header.subject': 'Aihe',
  'taskTable.col.header.addInfo': 'Tiedot',
  'taskTable.col.header.client': 'Asiakas',
  'taskTable.col.header.status': 'Status',
  'taskTable.col.header.roles': 'Rooli',
  'taskTable.col.header.assignee': 'Määrätty',
  'taskTable.col.header.due': 'Määräaika',
  'taskTable.col.header.created': 'Luotu',
  'taskTable.col.header.archive': 'Arkistoi',
  'eveli.batches.batchView.averageRunTime': 'Average run time',
  'eveli.batches.batchView.averageRunTime.ms': 'ms',
  'taskcard.style.COMPACT': 'Compact',
  'taskcard.style.DEFAULT': 'Default',
  'taskcard.style.LARGE': 'Large'
}