export const sv = {
  'document.title': 'DigiExpress',
  'eveli.textSeparatorColon': ':',
  'eveli.noValueIndicator': '--',
  'eveli.permissions.none.title': 'Oops!',
  'eveli.permissions.none.desc1': 'Du har inte rätt åtkomsträttigheter för att använda denna applikation.',
  'eveli.permissions.none.desc2': 'Kontakta din systemadministratör.',
  'tasksView.title': 'Uppgiften',
  'taskDialog.priority': 'Prioritet',
  'taskDialog.subject': 'Ämne',
  'taskDialog.dueDate': 'Deadline',
  'taskDialog.assignedTo': 'Hanteraregrupp',
  'taskDialog.assignedUser': 'Användare',
  'taskDialog.status': 'Status',
  'taskDialog.task': 'Uppgiften',
  'taskDialog.category': 'Typ',
  'taskDialog.source': 'Källa',
  'taskDialog.additionalInfo': 'Tilläggsinformation',
  'task.priority.low': 'Inte bråttom',
  'task.priority.normal': 'Normal',
  'task.priority.high': 'Brådskande',
  'task.dueDate': 'Förfallodatum',
  'task.customerMessages': 'Kundmeddelanden',
  'task.edit': 'Redigera uppgift',
  'task.customerName': 'Kundens namn',
  'task.subject': 'Ämne',
  'task.additionalInfo': 'Ytterligare information',
  'task.metaData': 'Metadata',
  'task.status.new': 'Nya',
  'task.status.open': 'Läsning',
  'task.status.completed': 'Redo',
  'task.status.rejected': 'Ingen bearbetning',
  'task.status.transferred': 'Överförs',
  'task.status.delegated': 'Delegerad',
  'task.status.waiting': 'Väntar',
  'task.pdf.options.select.CUSTOMER_NAME': 'Customer name',
  'task.pdf.options.select.CUSTOMER_SSN': 'Customer SSN',
  'task.pdf.options.select.EXTERNAL_COMMENTS': 'Customer messages',
  'task.pdf.options.select': 'PDF Printing options',
  'task.pdf.print': 'Print PDF',
  'task.pdf.options.select.desc': 'The form will be printed as a PDF which includes the additional options you select here.',
  'task.form.review': 'Visa formulär',
  'task.created': 'Skapad',
  'task.updated': 'Uppdaterad',
  'task.comments.external.createTask': 'Skapa uppgift innan du lägger till externa kommentarer',
  'task.comments.internal.createTask': 'Skapa uppgift innan du lägger till interna kommentarer',
  'task.attachments.createTask': 'Skapa uppgift innan du laddar upp bilagor',
  'task.comments.external.added': 'Intern kommentar tillagd',
  'task.feedback.publishedSaved': 'Feedbackändringar sparade',
  'internalComments': 'Interna kommentarer',
  'externalComments': 'Kundmeddelanden',
  'comment.store': 'Spara',
  'comment.add': 'Skriv en kommentar',
  'comment.addInternal': 'Skriva en intern kommentar',
  'comment.addExternal': 'Meddelande till klienten',
  'taskButton.addTask': 'Mer uppgift',
  'taskButton.refresh': 'Sök efter nya uppgifter',
  'taskButton.accept': 'Acceptera',
  'taskButton.cancel': 'Avbryt',
  'table.body.emptyDataSourceMessage': 'Ingen data',
  'table.body.filterRow.filterTooltip': 'Filtrera',
  'table.body.deleteTooltip': 'Radera',
  'table.header.actions': 'Funktioner',
  'table.pagination.labelDisplayedRows': '{from}-{to} av {count}',
  'table.pagination.labelRowsPerPage': 'Rader per sida:',
  'table.pagination.firstPage': 'Första sidan',
  'table.pagination.previousPage': 'Färegående',
  'table.pagination.nextPage': 'Nästa',
  'table.pagination.lastPage': 'Sista sidan',
  'table.toolbar.search': 'Söka',
  'table.toolbar.showColumnsTitle': 'Visa kolumner',
  'table.toolbar.addRemoveColumns': 'Lägg till eller ta bort kolumner',
  'taskLink.pdf.open': 'PDF',
  'explorer.login': 'Logga in',
  'locale.fi': 'Finska',
  'locale.sv': 'Svenska',
  'locale.en': 'Engelska',
  'main.articles.all': 'Alla Artiklar',
  'main.links.all': 'Alla Länkar',
  'main.services.all': 'Alla Tjänster',
  'main.flows.all': 'Alla Serviceflöden',
  'main.debug': 'Debuggning',
  'main.decisions.all': 'Alla Beslutstabeller',
  'menu.dashboard': 'Översiktspanel',
  'menu.profile': 'Användarens profil',
  'menu.tasks': 'Uppgifter',
  'menu.forms': 'Dialob',
  'menu.queues': 'Queues',
  'menu.help': 'Anvisningar',
  'menu.processes': 'Övervakning',
  'menu.logout': 'Logga ut',
  'menu.publications': 'Offentliggörande',
  'menu.services': 'Tjänster',
  'menu.feedback': 'Feedback',
  'menu.compose': 'Compose',
  'menu.articles': 'Artiklar',
  'menu.links': 'Länkar',
  'menu.locales': 'Språk',
  'menu.templates': 'Mallar',
  'menu.flows': 'Serviceflöden',
  'menu.decisions': 'Beslutstabeller',
  'menu.debug': 'Debuggning',
  'menu.releases': 'Släpp',
  'menu.compare': 'Jämföra',
  'profile.user.name': 'Namn:',
  'profile.user.email': 'e-post:',
  'profile.user.role': 'Roll:',
  'button.cancel': 'Avboka',
  'button.confirmDelete': 'Ta bort',
  'button.delete': 'Ta bort denna feedback',
  'button.delete.template': 'Ta bort denna mall',
  'button.delete.link': 'Avlägsna denna länk',
  'button.delete.article': 'Avlägsna denna artikel',
  'button.delete.page': 'Avlägsna denna sidan',
  'button.update': 'Uppdatering',
  'button.publish': 'Ladda upp',
  'button.accept': 'Acceptera',
  'button.close': 'Stäng',
  'button.save': 'Save',
  'button.dismiss': 'Stäng',
  'button.select': 'Select',
  'button.startBatch': 'Start batch',
  'error.minTextLength': 'Texten måste vara minst {minLength} tecken lång.',
  'error.maxTextLength': 'Texten måste vara max {max} tecken lång.',
  'error.valueRequired': '* Nödvändig',
  'error.title': 'Fel!',
  'error.dialob.session': 'Blanketten kan inte öppnas just nu. Vänligen försök på nytt senare',
  'error.errorLoadingData': 'Fel då försöker ladda data',
  'error.unauthorized.title': 'Du saknar rättighet till tjänsten',
  'error.unauthorized.text': 'Tag kontakt med IT genom att göra en Tiket: Rapportera IT problem -> Problem med inloggning.',
  'error.unauthorizedAccess': 'Du saknar rättighet till tjänsten',
  'error.dataAccess': 'Fel vid drift',
  'error.statusOpenError': 'Required when status is open',
  'error.workflowCreation': 'Error on workflow creation, check worflow name for duplicates',
  'table.body.editRow.deleteMessage': 'Är du säker på att du vill radera detta?',
  'workflowTable.title': 'Sammansättning',
  'workflowTableHeader.name': 'Namn',
  'workflowTableHeader.formName': 'Formulär',
  'workflowTableHeader.flowName': 'Process',
  'workflowTableHeader.updated': 'Uppdaterad',
  'workflowTable.editButton': 'Editera',
  'workflow.dialogTitle': 'Nytt arbetsflöde',
  'workflow.name': 'Namn',
  'workflow.form.formName': 'Formulär namn',
  'workflow.form.formTag': 'Formulär version',
  'workflow.flowName': 'Process',
  'processTable.title': 'Arbeten',
  'processTableHeader.workflow': 'Typ',
  'processTableHeader.status': 'Status',
  'processTableHeader.created': 'Skapad',
  'processTableHeader.questionnaireId': 'Formulär',
  'processTableHeader.taskRef': 'Uppgiftsreferens',
  'process.status.ANSWERED': 'Skickad',
  'process.status.CREATED': 'Skapad',
  'process.status.ANSWERING': 'På hälft',
  'process.status.IN_PROGRESS': 'Under arbete',
  'process.status.WAITING': 'Väntar',
  'process.status.COMPLETED': 'Färdig',
  'process.status.REJECTED': 'Avslagen',
  'spoTasksTableHeader.taskName': 'Uppgiftens namn',
  'spoTasksTableHeader.status': 'Status',
  'spoTasksTableHeader.priority': 'Prioritet',
  'spoTasksTableHeader.dueDate': 'Förfallodag',
  'spoTasksTableHeader.assigned': 'Roll',
  'spoTasksTableHeader.assignedUser': 'Hanterare',
  'spoTasksTableHeader.created': 'Ankomnstdatum',
  'spoTasksTableHeader.clientName': 'Kund',
  'spoTasksTableHeader.additionalInfo': 'Info',
  'taskDialog.clientIdentificator': 'Kundens namn',
  'Manual': 'Manuellt',
  'Protected': 'Skyddad',
  'Normal': 'Normalt',
  'CustomerCreated': 'Kund skapad',
  'Internal': 'Intern',
  'task.role.assignedAllUsers': 'Alla användare',
  'task.feedback.published': 'Publicerat svar',
  'confirm.close.title': 'Bekräftelse krävs',
  'confirm.unsavedChanges': 'Osparade ändringar kommer att gå förlorade, vill du fortsätta?',
  'task.statistics.statusCount': 'Efter status',
  'task.statistics.priorityCount': 'Efter prioritet',
  'task.statistics.daily': 'Dagligen',
  'task.statistics.overdue': 'Försenad',
  'feedback.create.title': 'Skapa offentliga svar på kundfeedback',
  'feedback.update.title': 'Redigera offentligt svar på kundfeedback',
  'feedback.taskReferenceId': 'Ärende-ID',
  'feedback.taskReferenceId.short': 'Task Ref',
  'feedback.mainCategory': 'Ämne',
  'feedback.subCategory': 'Specifikt ämnesområde',
  'feedback.feedbackValue': 'Kundfeedback',
  'feedback.customerTitle': 'Feedback titel',
  'feedback.myReply': 'Svara kunden',
  'feedback.customerApprovals': 'Kundgodkännanden',
  'feedback.createdBy': 'Skapat av',
  'feedback.updatedBy': 'Uppdaterad av',
  'feedback.updated': 'Senast uppdaterad',
  'feedback.notPublished': 'This feedback is not published',
  'feedback.isPublished': 'This feedback is published and publicly viewable',
  'feedback.delete.confirmTitle': 'Ta bort feedback?',
  'feedback.delete.confirmText': 'Är du säker på att du vill ta bort denna feedback?',
  'feedback.main_topic.employmentimmigration': 'Työllisyys, työikäiset, ikääntyneet ja maahanmuuttajat',
  'feedback.main_topic.youthservice': 'Nuorisopalvelu',
  'feedback.main_topic.freetimeculture': 'Vapaa-aika ja kulttuuri',
  'feedback.main_topic.cityconstruction': 'Kaupunkiympäristö, rakentaminen ja asuminen',
  'feedback.main_topic.exercise': 'Liikunta',
  'feedback.main_topic.communication': 'Viestintä ja markkinointi',
  'feedback.sub_topic.otherfeedback': 'Muu palaute',
  'feedback.sub_topic.familywithchildren': 'Perhe ja lapset',
  'feedback.sub_topic.libraryservices': 'Kirjatopalavelut',
  'feedback.sub_topic.streetmaintservices': 'Katujen kunnossapito',
  'feedback.sub_topic.exercise': 'Liikunta',
  'feedback.sub_topic.brand': 'Brand',
  'help.title': 'Anvisningar',
  'attachmentView.title': 'Fastsättning',
  'attachmentTableHeader.size': 'Storlek',
  'attachmentTableHeader.created': 'Skapad',
  'attachmentTableHeader.name': 'Ämne',
  'attachmentButton.addAttachment': 'Lägg till fil',
  'attachmentButton.downloadAttachment': 'Ladda ner filen',
  'attachmentButton.deleteAttachment': 'Ta bort fil',
  'attachment.uploadOk': 'Fil {fileName} uploaded',
  'attachment.uploadFailed': 'Fil {fileName} upload failed!',
  'attachment.delete.confirmTitle': 'Delete file?',
  'attachment.delete.confirmText': 'Är du säker på att du vill ta bort denna {fileName}?',
  'attachment.deleteFailed': 'File {fileName} delete failed!',
  'publicationsTable.title': 'Publikationer',
  'publicationsTableHeader.name': 'Publikationer nam',
  'publicationsTableHeader.description': 'Beskrivning',
  'publicationsTableHeader.createdBy': 'User',
  'publicationsTableHeader.created': 'Skapad',
  'publicationsTableHeader.liveDate': 'Lanseringsdatum',
  'publicationsTable.addButton': 'Tillägg',
  'publicationsTable.exportButton': 'Export',
  'publicationsTable.uploadButton': 'Uppladdning',
  'publications.external': 'Detta är externt konfigurerad distribution och kommer att gälla när det inte finns några andra distributioner',
  'publications.changeStatus': 'Ändra driftsstatusen',
  'publications.currentStatus': 'Nuvarande distributionsstatus',
  'publications.remove': 'Ta bort distributionen',
  'publications.deploy': 'Driftsätt nu',
  'publications.dialogTitle': 'Skapa ny publikation',
  'publications.name': 'Utgivningsnamn',
  'publications.description': 'Description',
  'publications.workflowTag': 'Workflow tag',
  'publications.wrenchTag': 'theWrench tag',
  'publications.contentTag': 'Content tag',
  'publications.createNewTag': 'Create new tag \"{tag}\"',
  'publications.downloadFailed': 'Release download failed, cause: {cause}',
  'publications.tagCreationFailed': 'Release creation failed, cause: {cause}',
  'publications.uploadDialogTitle': 'Ladda upp publicering',
  'dialobForm.saveFailed': 'Saving failed',
  'dialobForm.downloadFailed': 'Saving failed',
  'dialobForm.deleteFailed': 'Remove failed',
  'dialobForm.review.title': 'Form review',
  'feedback.notenabled': 'Feedback is not enabled for this task',
  'pages': 'Sidor',
  'articles': 'Artiklar',
  'locale': 'Plats',
  'locales': 'Webbplatsspråk',
  'links': 'Länkar',
  'releases': 'Släpps',
  'options': 'Alternativ',
  'value': 'Värde',
  'date': 'Datum',
  'description': 'Beskrivning',
  'name': 'Namn',
  'download': 'Ladda ner JSON',
  'status': 'Status',
  'created': 'Skapad',
  'remove': 'Ta bort',
  'site.content.empty': 'Webbplatsen har inget innehåll! Skapa innehåll innan du gör en release!',
  'composer.select.article': 'Välj Artikel',
  'search.field.placeholder': 'Ange sökord',
  'search.results.title': 'Sökresultat',
  'search.field.label': 'Söka',
  'search.all': 'Alla',
  'search.articles': 'Artiklar',
  'search.services': 'Tjänster',
  'search.links': 'Länkar',
  'search.templates': 'Mallar',
  'search.flows': 'Flows',
  'search.decisions': 'Decisions',
  'activities.article.title': 'Artikel',
  'activities.article.desc': 'En artikel är som en kategori: Den grupperar sidor, länkar och tjänster under ett tak.',
  'activities.locale.title': 'Plats',
  'activities.locale.desc': 'Språk är dina språk: Lägg till, aktivera och inaktivera språk för hela webbplatsen här. Du kan lägga till en sida på ett specifikt språk om du har definierat ett språk för den sidan.',
  'activities.page.title': 'Sida',
  'activities.page.desc': 'En sida är en innehållsfil i en artikel. Det representerar ett språk och alla länkar/arbetsflöden som är associerade med en artikel. Det är skrivet med Markdown-syntax.',
  'activities.link.title': 'Hyperlänk',
  'activities.link.desc': 'En hyperlänk kopplar användare till webbsidor du äger, webbsidor för andra organisationer och dina telefonnummer.',
  'activities.release.title': 'Släppa',
  'activities.release.desc': 'En release är en ögonblicksbild av allt innehåll på webbplatsen vid en viss tidpunkt. Använd detta för testning, produktion eller säkerhetskopiering.',
  'activities.migration.title': 'Migration',
  'migration.create': 'Migrera data',
  'activities.migration.desc': 'Använd en JSON-fil för att utföra en migrering av en webbplats.',
  'activities.templates.title': 'Mallar',
  'activities.templates.desc': 'Använd mallar för att anpassa och standardisera en sidas standard Markdown-innehåll och/eller -struktur. Mallar kan appliceras på nya sidor när de skapas. Inte implementerat ännu!',
  'activities.version.composer': 'Kompositör: byggversion {version}, byggdatum {date}',
  'activities.version.core': 'Kärna: byggversion {version}, byggdatum {date}',
  'dialog.about.title': 'Om',
  'dialog.about.preamble': 'DigiExpress är baserad på öppen källkodsprojekt:',
  'dialog.about.trademark': 'DigiExpress varumärke och logotyp upphovsrättsskyddat av ReSys OÜ',
  'templates': 'Mallar',
  'template.name': 'Namn',
  'template.name.desc': 'Användarnamn för denna mall',
  'template.create': 'Skapa mall',
  'template.edit': 'Redigera mall',
  'template.type': 'Malltyp',
  'template.page': 'Sidmall',
  'template.page.desc': 'Denna mall kan appliceras på en ny sida när den sidan skapas.',
  'template.description': 'Skriv mallar i Markdown för att tillämpa på dina sidor och innehåll. Mallar hjälper till att påskynda din utveckling och förena din innehållsstruktur.',
  'template.desc': 'Beskrivning',
  'template.description.desc': 'Ytterligare information för att identifiera användningsfallen för denna mall',
  'template.delete': 'Ta bort mall',
  'template.delete.message': 'Denna mall kommer att tas bort permanent från applikationen',
  'template.newpage.none': 'Ingen',
  'templates.templatesview.description': 'En ny sida kan skapas från en mall',
  'templates.intro': 'Kom ihåg att använda en Markdown Level 1 Heading (# My Heading 1) när du komponerar dina mallar.',
  'services': 'Tjänster',
  'services.create': 'Skapa tjänst',
  'services.desc': 'Anslut dina formulär och andra integrationer till ditt innehåll med Wrench- och Dialob-arbetsflödena',
  'services.add': 'Lägg till en tjänst',
  'services.change': 'Ändra befintliga tjänster',
  'services.edit': 'Redigera tjänst',
  'services.technicalname': 'Användarens unika tjänstnamn',
  'services.selected': 'Utvalda tjänster',
  'services.modeselect.title': 'Konfigurationsalternativ',
  'services.modeselect.label': 'Välja',
  'services.devmode.helper': 'Utvecklingsläge: Tjänsten visas endast i utvecklingsmiljön för testning och ingår inte i produktionsutgåvor.',
  'services.devmode.label': 'Utvecklingsläge',
  'services.devmode.tooltip': 'Utvecklingsläge',
  'services.disabledmode.label': 'Inaktiverat läge',
  'services.disabledmode.helper': 'Inaktiverat läge: Tjänsten visas inte på klientportalen',
  'services.disabledmode.tooltip': 'Inaktiverat läge',
  'services.assignableMode.label': 'Assignable mode',
  'services.assignableMode.helper': 'Assignable manually: Can be assigned directly to customer',
  'services.assignableMode.tooltip': 'Assignable mode',
  'services.none.label': 'Ingen konfiguration har valts',
  'services.none.helper': 'Standardläge: Tjänsten visas i produktion, är ENDAST tillgänglig för autentiserade användare och är ansluten till ALLA ARTIKLAR om ingen artikel är vald',
  'services.none.tooltip': 'Ingen speciell konfiguration',
  'services.anonmode.helper': 'Anonymt läge: Tjänsten visas för BÅDE anonyma och autentiserade användare.',
  'services.anonmode.label': 'Anonymt läge',
  'services.anonmode.tooltip': 'Anonymt läge',
  'services.flowName': 'Flödes namn',
  'services.formName': 'Dialob formnamn',
  'services.formName.description': 'Namn på Dialob-formuläret som används i tjänsten',
  'services.formTag': 'Dialob formtagg',
  'services.formTag.description': 'Taggnamn för Dialob-formulär som används i tjänsten',
  'services.startdate': 'Startdatum och tid',
  'services.startdate.description': 'Serviceaktiveringsdatum och tid',
  'services.enddate': 'Slutdatum och tid',
  'services.enddate.description': 'Serviceaktiveringens slutdatum och tid',
  'services.delete': 'Ta bort tjänsten',
  'services.delete.desc': 'Om du tar bort den här tjänsten tas den bort permanent från applikationen, och alla kopplingar till artiklar/sidor kommer att gå förlorade.',
  'snack.article.createdMessage': 'Artikel skapad framgångsrikt',
  'snack.article.deletedMessage': 'Artikel raderad',
  'snack.article.editedMessage': 'Artikeländringar sparade',
  'snack.page.createdMessage': 'Sidan har skapats',
  'snack.page.deletedMessage': 'Sidan raderad',
  'snack.page.savedMessage': 'Sidändringar sparade',
  'snack.page.missingTitle': 'Lägg till en titel till {locale} i {articleName}',
  'snack.link.createdMessage': 'Länken har skapats',
  'snack.link.deletedMessage': 'Länken raderad',
  'snack.link.editedMessage': 'Länkändringar har sparats',
  'snack.workflow.createdMessage': 'Tjänsten har skapats',
  'snack.workflow.deletedMessage': 'Tjänsten raderad',
  'snack.workflow.editedMessage': 'Tjänständringar sparade',
  'snack.locale.createdMessage': 'Språket har skapats',
  'snack.locale.enabled': 'Språk aktiverat',
  'snack.locale.disabled': 'Plats inaktiverad',
  'snack.template.createdMessage': 'Mallen har skapats',
  'snack.template.deletedMessage': 'Mallen raderad',
  'snack.template.editedMessage': 'Malländringar sparade',
  'snack.release.createdMessage': 'Release skapad framgångsrikt',
  'snack.release.deletedMessage': 'Release raderad',
  'snack.migration.createdMessage': 'Webbplatsdata uppdaterad',
  'toolbar.save': 'Spara',
  'toolbar.stencil': 'stencilen',
  'toolbar.wrench': 'skiftnyckeln',
  'toolbar.menu': 'Meny',
  'toolbar.help': 'Hjälp',
  'toolbar.import': 'Importera data',
  'toolbar.tasks': 'Uppgifter',
  'toolbar.about': 'Om',
  'stencil.services.found.none': 'Inga tjänster hittades',
  'link.type.internal': 'Inre',
  'link.type.external': 'Extern',
  'link.type.phone': 'Telefonnummer',
  'link.search.title': 'Sök länkar efter värde',
  'link.value': 'Länkvärde',
  'sitelocale.label.select.alreadyDefined': 'Kan inte lägga till eftersom det här språket redan är definierat',
  'sitelocale.label.table.editLocaleValue': 'Redigera språkvärde',
  'locales.label.table.title': 'Platsetiketter',
  'locales.label.title.helper': 'Minst en språkkod (lokal) + lokaletikettvärde krävs',
  'locales.label.table.value': 'Platsetikettvärden',
  'locales.label.table.noneSet': 'Inga översatta etiketter!',
  'locales.enabledMessage': 'Aktiverad: Innehåll för den här lokalen kommer att visas på portalsidan',
  'locales.disabledMessage': 'Inaktiverad: Innehåll för den här lokalen kommer att döljas från portalsidan. Innehållet kan fortfarande redigeras.',
  'transferlist.noItemsSelected': 'Inga objekt har valts',
  'transferlist.search': 'Söka',
  'transferlist.noSearchResults': 'Inga sökresultat hittades',
  'explorer.tabs.links': 'Länkar',
  'explorer.tabs.services': 'Tjänster',
  'imports.select': 'Välj en fil att importera',
  'imports.import.action': 'Importera valt',
  'article.order': 'Artikelbeställningsnummer',
  'article.order.view': 'Se aktuell artikelordningshierarki',
  'article.select': 'Välj Artiklar',
  'article.links.selectedlinks': 'Valda länkar',
  'article.composer.title': 'Skapa ny artikel',
  'article.composer.parent': 'Föräldraartikel',
  'article.parent.helper': 'Om en överordnad artikel väljs, kommer den här artikeln att finnas i denna förälder, som en fil i en mapp gör.',
  'article.composer.parent.unselected': 'Ingen överordnad artikel',
  'article.create': 'Skapa artikel',
  'article.name': 'Artikelnamn',
  'article.delete.title': 'Ta bort artikel',
  'article.delete.description': 'Om du tar bort den här artikeln tas den och dess associerade sidor bort globalt från programmet.',
  'article.edit.title': 'Redigera artikel',
  'article.edit.parent': 'Överordnad artikel',
  'article.devmode.helper': 'Om utvecklingsläget är aktivt kommer den här artikeln endast att visas i utvecklingsmiljön för testning. Det kommer inte att inkluderas i produktionsutgåvor.',
  'article.devmode': 'Utvecklingsläge',
  'articleservices': 'Artikeltjänster: {name}',
  'articlelinks': 'Artikellänkar: {name}',
  'article.composer.orderhelper': 'Ju lägre siffra, desto högre upp kommer denna artikel att visas i portalens gränssnittsämnesmeny.  Exempel: 000 kommer att vara det första ämnesmenyn, medan 999 kommer att vara det sista.',
  'article.timestamps.title': 'Assistance',
  'button.create': 'Skapa',
  'button.add': 'Tillägga',
  'button.disable': 'Fortsätt och inaktivera',
  'button.enable': 'Fortsätt och aktivera',
  'button.apply': 'Tillämpa ändringar',
  'button.view.all.locales': 'Visa lokaler',
  'button.view.all.releases': 'Visa releaser',
  'button.view.all.templates': 'Visa mallar',
  'links.searchAll': 'Sök i alla länkar',
  'link.article.select': 'Välj Artikel',
  'link.type': 'Typ',
  'link.content': 'Länk URL / sökväg',
  'link.composer.title': 'Skapa en ny länk',
  'link.composer.valuehelper': 'URL/sökväg till länk (http://www.example.com)',
  'link.edit.title': 'Redigera länk',
  'link.delete.title': 'Ta bort länk',
  'link.delete': 'Om du tar bort den här länken kommer den att tas bort permanent från applikationen och alla kopplingar till artiklar/sidor kommer att gå förlorade.',
  'resource.edit.links': 'Redigera länkar',
  'links.change': 'Ändra befintliga länkar',
  'link.create': 'Skapa ny länk',
  'link.devmode.helper': 'Om utvecklingsläget är aktivt kommer denna länk endast att visas i utvecklingsmiljön för testning. Det kommer inte att inkluderas i produktionsutgåvor.',
  'link.devmode': 'Utvecklingsläge',
  'locale.create': 'Skapa språklokalisering',
  'locale.disable.title': 'Inaktivera den här språklokalisering?',
  'locale.enable.title': 'Vill du aktivera det här språklokaliseret ?',
  'locale.disable': 'Alla sidor som använder dettaspråklokaliseringkommer att döljas i användargränssnittet. Sidor kan fortfarande redigeras.',
  'locale.enable': 'Alla sidor som använder den här lspråklokalisering kommer att visas i användargränssnittet.',
  'locale.composer.title': 'Skapa en ny språklokalisering',
  'locale.composer.placeholder': 'Språkkod på två bokstäver',
  'locale.composer.helper': 'Språkkoder på två bokstäver anger innehållsspråket. Vanliga exempel: en = engelska, fi = finska, sv = svenska',
  'locale.overview': 'Översikt över användning av språklokalisering',
  'locales.overview.description': 'Hantera språken för innehållet på din webbplats. Inaktivera språk för att dölja allt innehåll som är kopplat till det språket från din webbplats',
  'locales.content': 'Sidan i det här språket har innehåll',
  'locales.nocontent': 'Sidan i det här språket har inget innehåll',
  'locales.nopage': 'Det finns ingen sida för detta språk i denna artikel',
  'locales.label.table.locale': 'Språkkod',
  'newpage.title': 'Skapa en ny sida',
  'newpage.info': 'En sida består av lokaliserat innehåll och måste kopplas till en artikel.',
  'newpage.article.info': 'Bekräfta skapandet av sidan för: {article} med språk: {locale}',
  'page.create': 'Skapa sida',
  'page.delete.dialog.title': 'Ta bort en sida från artikeln',
  'page.delete.description': 'Den valda sidan och allt dess innehåll kommer att tas bort permanent från din webbplats',
  'pages.add': 'Lägg till en sida',
  'pages.change': 'Ändra en sidspråk',
  'pages.select.locale': 'Redigera lokaliserat sidinnehåll',
  'pages.select.locale.edit.desc': 'Välj två språk för att möjliggöra sida vid sida redigering på en flik.',
  'pages.edit.language1': 'Redigera detta språk',
  'pages.edit.language2': 'Redigera detta språk sida vid sida',
  'pages.edit.currentlyEditing.language2': 'Redigering sida vid sida',
  'pages.edit.currentlyEditing.language1': 'Redigerar detta språk',
  'pages.change.info': 'Välj en sida från den här artikeln och ange ett nytt värde för dess språk.',
  'pages.change.devmode': 'Ändra ett sidutvecklingsläge',
  'pages.change.devmode.info': 'Välj en sida från den här artikeln och ändra dess utvecklingsläge.',
  'pages.devmode.helper': 'Om utvecklingsläget är aktivt kommer denna sida endast att visas i utvecklingsmiljön för testning. Det kommer inte att inkluderas i produktionsutgåvor.',
  'pages.devmode': 'Utvecklingsläge',
  'pages.delete': 'Ta bort en sida',
  'pages.edit.selectpage': 'Välj sida',
  'pages.edit.selectTargetLocale': 'Välj målspråk',
  'release.create': 'Skapa release',
  'release.composer.title': 'Skapa en ny version',
  'release.composer.label': 'Taggnamn',
  'release.composer.note': 'Notera',
  'release.composer.helper': 'Valfri ytterligare information för framtida referens',
  'release.desc': 'Visa alla utgåvor och ladda ner allt innehåll på webbplatsen i JSON-format. För mer detaljerad information om specifika utgåvor och deras innehåll, se diagrammet.',
  'release.delete.title': 'Ta bort release',
  'release.delete.desc': 'Vill du ta bort den här versionen permanent från webbplatsdata?',
  'releases.view.note': 'Anteckningar',
  'releases.view.tag': 'Namn',
  'releases.view.created': 'Skapad',
  'releases.view.download': 'Ladda ner JSON',
  'buttons.create': 'Skapa',
  'buttons.apply': 'Tillämpas',
  'buttons.delete': 'Radera',
  'buttons.copy': 'Kopiera',
  'button.compose': 'Komponera',
  'buttons.download': 'Ladda ner',
  'activities.flows.title': 'Workflow',
  'activities.flows.desc': 'A a sequence of tasks which are defined by using simple configuration language.',
  'activities.decisions.title': 'Decisions',
  'activities.decisions.desc': 'A decision table that can be used to make decisions based on input data.',
  'activities.services.title': 'Services',
  'activities.services.desc': 'A piece of Java or Groovy code that is embedded inside of a flow as a task.',
  'activities.releases.title': 'Releases',
  'activities.releases.desc': 'A Release is a snapshot of all site content at one certain point of time.',
  'activities.releases.desc.additional': 'Each Release can be downloaded to be used for production or backup purposes, or can be branched for further editing. This will replace all current assets so make sure any changes are saved.',
  'activities.releases.view': 'View all releases',
  'activities.compare.title': 'Compare',
  'activities.compare.desc': 'Compare two releases to see what has changed between them.',
  'activities.compare.view': 'Compare',
  'activities.debug.title': 'Debug',
  'activities.debug.desc': 'Simulate execution of an asset. Can be done via form input, JSON input, or by using a CSV file.',
  'activities.debug.view': 'Simulate',
  'activities.assets.saveSuccess': 'Saved asset: {name}',
  'flows': 'Flows',
  'migrations.title': 'Migration',
  'migrations.create': 'Perform migration',
  'migrations.select': 'Select tag.json file',
  'flows.edit.title': 'Edit flow',
  'flows.copyas.title': 'Copy flow as',
  'flows.delete.title': 'Delete flow',
  'flows.delete.error.title': 'Failed to delete flow',
  'flows.delete.content': 'Are you sure you want to delete FLOW: {name}?',
  'flows.deleted.message': 'Deleted FLOW: {name}',
  'flows.simulate.title': 'Debug the flow',
  'flows.composer.title': 'Create new FLOW',
  'flows.composer.copyTitle': 'Copy FLOW as',
  'flows.composer.createdMessage': 'Created FLOW: {name}',
  'flows.composer.copiedMessage': 'Copied FLOW {name} as: {newName}',
  'flows.composer.errorsTitle': 'Failed to create FLOW',
  'flows.composer.assetName': 'Unique name for the FLOW',
  'flows.autocomplete.task.create': 'Create new asset',
  'flows.autocomplete.task.link': 'Link selected asset',
  'flows.autocomplete.task.searchField': 'Search for asset...',
  'flows.autocomplete.task.searchPlaceholder': 'Asset name or description',
  'flows.autocomplete.task.selectType': 'Select asset type to link',
  'flows.autocomplete.task.searchHelper': 'Matches asset name and description',
  'flows.autocomplete.task.searchResults': 'Search results',
  'flows.autocomplete.task.snackbar.created': 'Created new {type}: {name}',
  'flows.autocomplete.task.snackbar.creating': 'Creating new {type}: {name}',
  'flows.graph.show': 'Show flow graph',
  'flows.graph.hide': 'Hide flow graph',
  'services.searchAll': 'Search all services',
  'services.edit.title': 'Edit service',
  'services.copyas.title': 'Copy service as',
  'services.delete.title': 'Delete service',
  'services.delete.error.title': 'Failed to delete SERVICE',
  'services.delete.content': 'Are you sure you want to delete SERVICE: {name}?',
  'services.deleted.message': 'Deleted SERVICE: {name}',
  'services.simulate.title': 'Debug the service',
  'services.composer.title': 'Create new SERVICE',
  'services.composer.copyTitle': 'Copy SERVICE as',
  'services.composer.createdMessage': 'Created SERVICE: {name}',
  'services.composer.copiedMessage': 'Copied SERVICE {name} as: {newName}',
  'services.composer.errorsTitle': 'Failed to create SERVICE',
  'services.composer.assetName': 'Unique name for the SERVICE',
  'decisions.name': 'Name',
  'decisions.desc': 'Description',
  'decisions.simulate.title': 'Debug the decision',
  'decisions.hitpolicy': 'Hit-policy',
  'decisions.edit.title': 'Edit decision',
  'decisions.copyas.title': 'Copy decision as',
  'decisions.delete.error.title': 'Failed to delete DECISION',
  'decisions.delete.title': 'Delete decision',
  'decisions.delete.content': 'Are you sure you want to delete DECISION: {name}?',
  'decisions.deleted.message': 'Deleted DECISION: {name}',
  'decisions.deleteConfirmTitle': 'Confirm Delete',
  'decisions.deleteConfirmText': 'Are you sure you want to delete this {type}?',
  'decisions.type.row': 'row',
  'decisions.type.column': 'column',
  'decisions.table.hitpolicy': 'Matches',
  'decisions.composer.title': 'Create new DECISION',
  'decisions.composer.copyTitle': 'Copy DECISION as',
  'decisions.composer.createdMessage': 'Created DECISION: {name}',
  'decisions.composer.copiedMessage': 'Copied DECISION {name} as: {newName}',
  'decisions.composer.errorsTitle': 'Failed to create DECISION',
  'decisions.composer.assetName': 'Unique name for the DECISION',
  'decisions.toolbar.addInputColumn': 'Add input column',
  'decisions.toolbar.addOutputColumn': 'Add output column',
  'decisions.toolbar.addRow': 'Add row',
  'decisions.toolbar.csvDownload': 'Download CSV, with separator \';\'',
  'decisions.toolbar.csvUpload': 'Upload CSV, with separator \';\'',
  'decisions.toolbar.nameAndHitpolicy': 'Name and hit-policy',
  'decisions.toolbar.organize.rows.columns': 'Organize rows and columns',
  'decisions.toolbar.organize.action': 'Select action',
  'decisions.toolbar.organize.action.helper': 'Move column or row based on name/index',
  'decisions.toolbar.organize.action.expression': 'Select expression',
  'decisions.toolbar.organize.action.expression.column': 'Select column',
  'decisions.toolbar.organize.action.deleteColumn': 'Delete whole column',
  'decisions.toolbar.organize.action.deleteRow': 'Delete whole row',
  'decisions.toolbar.organize.action.deleteRow.contents': 'Row contents',
  'decisions.toolbar.organize.action.move.from.column': 'Column to move',
  'decisions.toolbar.organize.action.move.from.row': 'Row to move',
  'decisions.toolbar.organize.action.move.to.column': 'New Position',
  'decisions.toolbar.organize.action.move.to.row': 'New Position',
  'decisions.table.inputs.title': 'Matching rules',
  'decisions.table.outputs.title': 'Results',
  'decisions.header.dialog.title': 'Decision table: {name}, column: {column}',
  'decisions.cells.dialog.title': 'Decision table: {name}, column: {column}, value: {value}',
  'decisions.cells.dialog.title.simple': 'Edit Value',
  'decisions.header.dialog.title.simple': 'Edit Header',
  'decisions.cells.dialog.title.intl': 'Edit Localized Value',
  'decisions.cells.newvalue.boolean': 'Enter new value',
  'decisions.cells.newvalue.boolean.helper': 'Select boolean value',
  'decisions.cells.newvalue.boolean.empty': 'No value selected',
  'decisions.cells.newvalue.date.operator': 'Operator',
  'decisions.cells.newvalue.date.start': 'Start date',
  'decisions.cells.newvalue.date.end': 'End date',
  'decisions.cells.newvalue.date.value': 'Date',
  'decisions.cells.newvalue.number.comparisonType': 'Comparison',
  'decisions.cells.newvalue.number.comparisonTypeEmpty': 'Comparison not selected',
  'decisions.cells.newvalue.number.comparisonValue': 'New numerical value',
  'decisions.cells.newvalue.number.comparisonToRange': 'Change to range',
  'decisions.cells.newvalue.number.rangeStart': 'Start',
  'decisions.cells.newvalue.number.rangeEnd': 'End',
  'decisions.cells.newvalue.string.comparisonType': 'Comparison',
  'decisions.cells.newvalue.string.addValue': 'Add new value',
  'decisions.cells.newvalue.string.available': 'Available values',
  'decisions.cells.newvalue.string.selected': 'Selected values',
  'decisions.cells.newvalue.string.empty': 'Comparison not selected',
  'decisions.cells.newvalue.clear': 'Clear current value',
  'decisions.valueSet': 'Define value set',
  'decisions.valueSet.description': 'Value sets can be used to define a predetermined set of values for any input',
  'decisions.valueSet.add': 'Add to value set',
  'decisions.valueSet.current': 'Current value set',
  'dt.header.name': 'Name',
  'dt.header.delete': 'Delete',
  'dt.header.expression': 'Expression',
  'dt.header.dataType': 'Data type',
  'dt.header.script': 'Script',
  'decisions': 'Decisions',
  'program.status.DEPENDENCY_ERROR': 'Dependency Errors',
  'program.status.UP': 'Program is UP',
  'program.status.AST_ERROR': 'Syntax errors',
  'program.status.PROGRAM_ERROR': 'Compiler errors',
  'release.deleted.message': 'Release {name} raderad',
  'releases.composer.createdMessage': 'Skapat ny version {name}',
  'releases.view.action': 'Action',
  'releases.composer.title': 'Create new release',
  'releases.composer.assetName': 'Release name',
  'releases.composer.assetDesc': 'Release description',
  'releases.composer.errorsTitle': 'Error while creating release',
  'releases.button.compare': 'Compare',
  'releases.button.branch': 'Create new branch',
  'releases.button.checkout': 'Checkout',
  'releases.button.release': 'Release',
  'releases.button.details': 'View release assets',
  'releases.default.name': 'default',
  'releases.default.note': 'This is the default branch that you can go back to',
  'releases.latest.name': 'latest',
  'releases.latest.note': 'These are current assets with the latest changes that can be released',
  'releases.details.title': 'Release assets: {name}',
  'release.branch.creating': 'Creating new branch: {name}',
  'release.branch.created': 'Created new branch: {name}',
  'release.branch.deleting': 'Deleting branch: {name}',
  'release.branch.deleted': 'Deleted branch: {name}',
  'release.branch.checkout': 'Checked out to branch: {name}',
  'debug.toolbar.options': 'Options',
  'debug.toolbar.selectAsset': 'Select asset to debug',
  'debug.toolbar.inputCsv': 'Define input data as a CSV',
  'debug.toolbar.inputForm': 'Define input data as a FORM',
  'debug.toolbar.inputJson': 'Define input data as a JSON',
  'debug.toolbar.execute': 'Execute',
  'debug.toolbar.noAsset': 'Select asset from options',
  'debug.toolbar.openAsset': 'Open',
  'debug.toolbar.download': 'Download results as CSV',
  'debug.input.noAsset': 'There is no ASSET selected',
  'debug.input.form': 'Debug using FORM',
  'debug.input.formTitle': 'Define inputs',
  'debug.input.form.invalid.integer': 'Value must be an integer',
  'debug.input.form.invalid.number': 'Value must be a number',
  'debug.input.form.invalid.range': 'Value must be in the specified range',
  'debug.input.json': 'Debug using JSON',
  'debug.input.jsonTitle': 'Define JSON input',
  'debug.input.csvUpload': 'Debug using CSV',
  'debug.input.csvFile': 'Upload CSV FILE',
  'debug.input.csvFileTitle': 'Upload CSV file - semicolon-delimited (;)',
  'debug.input.csvFileOrText': 'Or paste CSV contents - semicolon-delimited (;)',
  'debug.inputs.fieldName': 'Field Name',
  'debug.inputs.fieldValue': 'Field Value',
  'debug.select.title': 'Select asset to debug',
  'debug.select.assetType': 'Asset type to filter',
  'debug.select.searchField': 'Asset name to search',
  'debug.select.searchHelper': 'Search matches asset name or description',
  'debug.select.searchPlaceholder': 'Keyword to search',
  'debug.select.searchResults': 'Found assets',
  'debug.select.confirm': 'Select',
  'debug.inputs.format': 'Asset input format: {type}',
  'debug.asset.execute.errors': 'Execution errors',
  'debug.asset.execute.outputs.dt.json': 'Matched row(s)',
  'debug.asset.execute.outputs.dt.rejects': 'Rejected row(s)',
  'debug.asset.execute.outputs.flow.step': 'Step name: {name}, status: {status}',
  'debug.csv.row': 'Data row: {row}',
  'debug.csv.download': 'Download results as CSV',
  'debug.csv.download.delimiter': 'Choose a delimiter for the CSV file',
  'debug.csv.download.delimiter.semicolon': 'Semicolon (;)',
  'debug.csv.download.delimiter.comma': 'Comma (,)',
  'debug.csv.download.options': 'Export options',
  'debug.csv.download.wrap': 'Wrap cells containing delimiters with quotes',
  'compare.tip': 'Select releases to compare below. Base is the starting point of the comparison, and target is the release that will be compared to the base.',
  'compare.base': 'Select base release',
  'compare.target': 'Select target release',
  'compare.dialog.title': 'Comparing releases {base} and {target}',
  'compare.dialog.line': 'Inline',
  'compare.dialog.side': 'Sida vid sida',
  'menu.activities': 'Aktiviteter',
  'feedback.all': 'All feedback',
  'task.feedback.none': 'Ingen feedback tillgänglig',
  'queues.all': 'Köer',
  'consumers.all': 'Konsumenter',
  'queue.config.none': 'Belastning',
  'queue.config.consumerName': 'Konsumentnamn',
  'queue.config.routingKey': 'Routing nyckel',
  'queue.config.consumerStatus': 'Status',
  'queue.config.comment': 'Kommentar',
  'queue.config.queueName': 'Könamn',
  'queue.config.createdAt': 'Skapad på',
  'queue.config.createdBy': 'Skapad av',
  'queue.all_deliveries.title': 'Alla leveranser',
  'queue.all_deliveries.created': 'Skapad',
  'queue.all_deliveries.consumerComment': 'Kommentar',
  'queue.all_deliveries.status': 'Status',
  'queue.all_deliveries.messageId': 'Meddelande-id',
  'queue.all_deliveries.consumerId': 'Konsument-id',
  'queue.all_messages.title': 'Alla meddelanden',
  'queue.all_messages.routingKey': 'Routing nyckel',
  'queue.all_messages.messageId': 'Meddelande-id',
  'queue.all_messages.bodyId': 'Kropps-ID',
  'queue.all_messages.bodyType': 'Kroppstyp',
  'queue.all_messages.status': 'Status',
  'queue.all_messages.body': 'Kropp',
  'queue.all_messages.created': 'Skapad',
  'workflows': 'Workflows',
  'explorer.pages': 'Pages',
  'articles.searchAll': 'Search all articles',
  'composer.article.selected': 'Selected Articles',
  'resource.edit.workflows': 'Workflows',
  'workflow.delete': 'Delete',
  'workflow.edit': 'Edit',
  'eveli.table.menu.filter.filterBy': 'Radera',
  'eveli.table.menu.filter.showAllItems': 'Redigera',
  'eveli.table.menu.sort.ascending': 'Filtrera efter',
  'eveli.table.menu.sort.descending': 'Visa alla matcher',
  'eveli.table.menu.sort.clearSorting': 'Stigande',
  'eveli.table.menu.sort.chooseCols': 'Fallande',
  'eveli.table.menu.sort.colsReset': 'Tydlig sortering',
  'eveli.table.dialog.columns.chooseCols': 'Välj Kolumner',
  'eveli.table.footer.tasks.total': 'Återställ kolumner',
  'eveli.table.footer.tasks.rowsPerPage': 'Välj Kolumner',
  'eveli.table.footer.pageNumber': 'Total',
  'eveli.table.footer.rowsPerPage': 'Rader per sida',
  'eveli.table.drawer.buttons.colsButton': 'Rader per sida',
  'eveli.table.drawer.buttons.filtersButton': 'Total',
  'eveli.table.resetAll': 'Kolumner',
  'eveli.table.drawer.title.columns': 'Knappar',
  'eveli.table.drawer.title.filters': 'Återställ alla',
  'eveli.table.drawer.title.saved-filters': 'Personalised table profiles',
  'eveli.table.drawer.title.export-data': 'Export data',
  'eveli.error.general': 'Ooops, we have encountered an error!',
  'eveli.error.notFound': 'Ooops, the thing you are looking for is not found!',
  'eveli.error.backToHome': 'Go back to our home page',
  'eveli.userProfile.title': 'User Profile',
  'eveli.userProfile.id': 'Id',
  'eveli.userProfile.displayName': 'Display name',
  'eveli.userProfile.firstAndLastName': 'Full name',
  'eveli.userProfile.created': 'Created',
  'eveli.userProfile.updated': 'Updated',
  'eveli.userProfile.firstName': 'First name',
  'eveli.userProfile.lastName': 'Last name',
  'eveli.userProfile.email': 'Email',
  'eveli.userProfile.notificationSettings': 'Notification settings',
  'eveli.userProfile.userRoles': 'My roles',
  'eveli.userProfile.userPermissions': 'My permissions',
  'eveli.userProfile.editDetails': 'Edit personal details',
  'eveli.userProfile.currentDetails': 'My current details',
  'eveli.userProfile.tenantConfig.select.LOGIN_BUTTON': 'Login button',
  'eveli.userProfile.tenantConfig.select.external-deployment': 'External deployment',
  'eveli.userProfile.tenantConfig.select.external-deployment.desc': 'Assets come explicitly from an environment-specific data source that implements ExternalDeploymentProvider',
  'eveli.userProfile.tenantConfig.select.feedback-visually-disabled': 'Feedback visually disabled',
  'eveli.userProfile.tenantConfig.select.feedback-visually-disabled.desc': 'Show / hide the feedback feature from the UI',
  'eveli.userProfile.tenantConfig.select.queues-visually-disabled': 'Queues visually disabled',
  'eveli.userProfile.tenantConfig.select.queues-visually-disabled.desc': 'Show / hide the Queues feature from the UI',
  'eveli.userProfile.tenantConfig.select.stencil-disabled': 'Stencil disabled',
  'eveli.userProfile.tenantConfig.select.stencil-disabled.desc': 'Eveli is reconfigured so as to remove Stencil',
  'eveli.userProfile.tenantConfig.select.wrench-disabled': 'Wrench disabled',
  'eveli.userProfile.tenantConfig.select.wrench-disabled.desc': 'Eveli is reconfigured so as to remove Wrench',
  'eveli.userProfile.tenantConfig.select.wrench-only': 'Wrench only',
  'eveli.userProfile.tenantConfig.select.wrench-only.desc': 'Eveli is reconfigured so as to include only Wrench',
  'eveli.userProfile.tenantConfig.select.batches': 'Batches',
  'eveli.userProfile.tenantConfig.select.batches.desc': 'Enable / disable batch processing features',
  'eveli.userProfile.tenantConfig.select.eveli_publication_only': 'Eveli publication only',
  'eveli.userProfile.tenantConfig.select.eveli_publication_only.desc': 'Editing assets is disabled - they come directly from a publication',
  'eveli.userProfile.tenantConfig.select.smart_tables': 'Smart tables',
  'eveli.userProfile.tenantConfig.select.smart_tables.desc': 'All tables are persistant - they save user-defined configurations',
  'eveli.userProfile.tenantConfig.select.stencil_locale_filter': 'Stencil locale filter',
  'eveli.userProfile.tenantConfig.select.stencil_locale_filter.desc': 'Configure visibility of the locale filtering UI component in Stencil',
  'eveli.userProfile.tenantConfig.select.user_profile': 'User profile enabled',
  'eveli.userProfile.tenantConfig.select.user_profile.desc': 'Show / hide the user profile feature from the UI',
  'eveli.userProfile.tenantConfig.select.smart_task': 'Smart task view',
  'eveli.userProfile.tenantConfig.select.smart_task.desc': 'Editing a task is enhanced via drag and drop/unified editing/flashy colours',
  'eveli.userProfile.tenantConfig.select.smart_task_audit': 'Smart task audit',
  'eveli.userProfile.tenantConfig.select.smart_task_audit.desc': 'Additional detailed views are enabled for auditing/debugging a task',
  'eveli.userProfile.tenantConfig.select.visual_accommodation': 'Visual accommodation',
  'eveli.userProfile.tenantConfig.select.visual_accommodation.desc': 'To make certain buttons and UI items pop for enhanced visibility',
  'taskTable.col.header.priority': 'Prioritet',
  'taskTable.col.header.subject': 'Ämne',
  'taskTable.col.header.addInfo': 'Info',
  'taskTable.col.header.client': 'Klient',
  'taskTable.col.header.status': 'Status',
  'taskTable.col.header.roles': 'Roll',
  'taskTable.col.header.assignee': 'Tilldelad',
  'taskTable.col.header.due': 'Förfallodatum',
  'taskTable.col.header.created': 'Skapad',
  'taskTable.col.header.archive': 'Arkiv',
  'eveli.batches.batchView.averageRunTime': 'Average run time',
  'eveli.batches.batchView.averageRunTime.ms': 'ms',
  'taskcard.style.COMPACT': 'Compact',
  'taskcard.style.DEFAULT': 'Default',
  'taskcard.style.LARGE': 'Large'
}