workspace(
    # How this workspace would be referenced with absolute labels from another workspace
    name = "digiexpress-monorepo",
    # Map the @npm bazel workspace to the node_modules directory. This lets Bazel use the same node_modules as other local tooling.
    managed_directories = {"@npm": ["ts-parent/node_modules"]},
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Download node, yarn rules
NODEJS_RULES_VERSION = "5.8.2"
NODEJS_RULES_SHA = "764a3b3757bb8c3c6a02ba3344731a3d71e558220adcb0cf7e43c9bba2c37ba8"
http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "f10a3a12894fc3c9bf578ee5a5691769f6805c4be84359681a785a0c12e8d2b6",
    url = "https://github.com/bazelbuild/rules_nodejs/releases/download/%s/rules_nodejs-%s.tar.gz" % (NODEJS_RULES_VERSION, NODEJS_RULES_VERSION),
)

# Standard way of loading nodejs library.
load("@build_bazel_rules_nodejs//:repositories.bzl", "build_bazel_rules_nodejs_dependencies")
build_bazel_rules_nodejs_dependencies()


# set up yarn and node envir
# Setup rules for the Node.js toolchain.
load("@rules_nodejs//nodejs:repositories.bzl", "nodejs_register_toolchains")
# The yarn_install rule runs yarn anytime the package.json or yarn.lock file changes.
# It also extracts any Bazel rules distributed in an npm package.
load("@build_bazel_rules_nodejs//:index.bzl", "yarn_install")

nodejs_register_toolchains(
    name = "nodejs",
    node_version = "16.14.0",
)
yarn_install(
    name = "npm",  # Name this "npm" so that Bazel Label references look like @npm//package
    package_json = "//ts-parent:package.json",
    quiet = False,
    yarn_lock = "//ts-parent:yarn.lock",
    data = [
        "//ts-parent/tools/releases:yarn-3.1.1.cjs",
        "//ts-parent:.yarnrc.yml",
    ],
    # Currently disabled due to:
    #  1. Missing Windows support currently.
    #  2. Incompatibilites with the `ts_library` rule.
    exports_directories_only = False,
    # We prefer to symlink the `node_modules` to only maintain a single install.
    # See https://github.com/angular/dev-infra/pull/446#issuecomment-1059820287 for details.
    symlink_node_modules = True,
    yarn = "//ts-parent/tools/releases:yarn-3.1.1.cjs",
)

