<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.digiexpress</groupId>
    <artifactId>digiexpress-build-parent</artifactId>
    <version>6.0.36</version>
    <relativePath>../build-parent/pom.xml</relativePath>
  </parent>

  <name>thena-parent</name>
  <artifactId>thena-parent</artifactId>
  <packaging>pom</packaging>

  <modules>
    <module>thena-test-client</module>
    <module>thena-sql-client</module>
    <module>thena-sql-client-annot-proc</module>
    <module>thena-sql-client-sample</module>
    <module>thena-db-client</module>
    <module>thena-grim-client</module>
    <module>thena-mq-client</module>
    <module>thena-batch-client</module>
    <module>thena-doc-client</module>
    <module>thena-git-client</module>
    <module>thena-product-client</module>
    <module>thena-contract-client</module>
    <module>thena-ledger-client</module>
    <module>thena-fs-client</module>
  </modules>

</project>
