quarkus:

  log:
    level: INFO
    category: 
      io.resys.thena.tasks.dev.app:
        level: DEBUG
      io.resys.thena.tasks.dev.app.security:
        level: WARN
    console:  
      json: false
      
  http:
    tcp-quick-ack: true
    tcp-cork: true
    tcp-fast-open: true
    enable-compression: true
    body:
      preallocate-body-buffer: true
    limits:
      max-body-size: 102400K
      max-header-size: 102400K
      max-chunk-size: 102400K

  vertx:
    keep-alive-time: PT10.000S

  native:
    resources:
      includes: asset_sysconfig_flat.json
  rest:
    output-buffer-size: 16384000
# DO NOT bother, with this, transactions area leaked via PgPool, some data is visible some is not.
#  datasource: 
#    db-kind: postgresql 
#    username: postgres
#    password: postgres
#    reactive:
#      url: postgresql://localhost:5432/tasks_db
#      max-size: 90
# QUARKUS_DATASOURCE_USERNAME
# QUARKUS_DATASOURCE_PASSWORD
# QUARKUS_DATASOURCE_REACTIVE_URL
# QUARKUS_DATASOURCE_REACTIVE_MAX_SIZE

tenant:
  currentTenantId: "local_test_tenant"
  failSafeUsers: olev.mutso@resys.io
  db:
    pg: 
      repositoryName: "tenant_store"
      pgPort: 5432
      pgHost: "localhost"
      pgDb: "tasks_db"
      pgUser: "postgres"
      pgPass: "postgres"
      pgPoolSize: 30


"%dev": 
  tenant:
    failSafeUsers: olev.mutso@resys.io
    devLoggedInUser: olev.mutso@resys.io
  quarkus:
    log:
      level: WARN
      category:
        io.resys.thena.tasks.dev.app:
          level: DEBUG
        io.resys.thena.tasks.dev.app.security:
          level: WARN
        org.jboss.resteasy.reactive.server.handlers.RequestDeserializeHandler: 
          level: DEBUG
      console:  
        json: false

"%test":
  quarkus:
    log:
      level: ERROR
      category:
        io.resys.thena.tasks.dev.app:
          level: DEBUG
