package io.resys.thena.doc.api;

import java.time.OffsetDateTime;

/*-
 * #%L
 * thena-docdb-api
 * %%
 * Copyright (C) 2015 - 2024 Copyright 2022 ReSys OÜ
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import java.util.List;

import javax.annotation.Nullable;

import org.immutables.value.Value;


import io.resys.thena.api.entities.CommitResultStatus;
import io.resys.thena.api.entities.doc.Doc;
import io.resys.thena.api.entities.doc.DocBranch;
import io.resys.thena.api.entities.doc.DocCommands;
import io.resys.thena.api.entities.doc.DocCommit;
import io.resys.thena.api.entities.doc.DocCommitTree;
import io.resys.thena.api.envelope.Message;
import io.resys.thena.api.envelope.ThenaEnvelope;
import io.smallrye.mutiny.Uni;
import io.vertx.core.json.JsonObject;


public interface DocCommitActions {
  CreateOneDoc createOneDoc();
  CreateManyDocs createManyDocs();
  
  CreateOneDocBranch branchOneDoc();

  ModifyOneDoc modifyOneDoc();
  ModifyManyDocs modifyManyDocs();
  
  ModifyOneDocBranch modifyOneBranch();
  ModifyManyDocBranches modifyManyBranches();

  /*
   * Create doc and doc by: One/Many
   */
  interface CreateOneDoc {
    CreateOneDoc docType(String docType);                 // user given classifier
    CreateOneDoc docId(@Nullable String docId);           // when empty generated by system
    CreateOneDoc parentDocId(@Nullable String parentDocId); 
    CreateOneDoc externalId(@Nullable String externalId); // user given unique id
    CreateOneDoc ownerId(@Nullable String ownerId);       //user given 'grouping' identifier for claiming ownership  
    CreateOneDoc meta(@Nullable JsonObject docMeta);
    
    CreateOneDoc docName(@Nullable String docName);
    CreateOneDoc docDescription(@Nullable String docDescription);
    CreateOneDoc docStartsAt(@Nullable OffsetDateTime docStartsAt); 
    CreateOneDoc docEndsAt(@Nullable OffsetDateTime docEndsAt); 
    CreateOneDoc docSubStatus(@Nullable String subStatus);

    CreateOneDoc commitAuthor(String author);
    CreateOneDoc commitMessage(String message);
    CreateOneDoc commitLogExcludesBranchBody(); // disables writing into doc_log(body_before, body_after, body_patch) and doc_commit.commit_log 
    CreateOneDoc commitTreeEnabled(boolean commitTreeEnabled); // disabled doc_log table fully
    
    CreateOneDoc branchName(String branchName); // first branch of the document, when empty generated as 'main' by the system
    CreateOneDoc branchContent(JsonObject branchContent);
    CreateOneDoc commands(List<JsonObject> commands);
    
    Uni<OneDocEnvelope> build();
  }
  interface CreateManyDocs { 
    CreateManyDocs commitAuthor(String author);
    CreateManyDocs commitMessage(String message);
    CreateManyDocs commitLogExcludesBranchBody(); // disables writing into doc_log(body_before, body_after, body_patch) and doc_commit.commit_log 
    CreateManyDocs commitTreeEnabled(boolean commitTreeEnabled); // disabled doc_log table fully
    
    AddItemToCreateDoc item();
    Uni<ManyDocsEnvelope> build();
  }
  interface AddItemToCreateDoc {
    AddItemToCreateDoc docType(String docType);                 // user given classifier
    AddItemToCreateDoc parentDocId(@Nullable String parentDocId); 
    AddItemToCreateDoc docId(@Nullable String docId); 
    AddItemToCreateDoc meta(@Nullable JsonObject docMeta);
    AddItemToCreateDoc externalId(@Nullable String externalId);
    AddItemToCreateDoc docName(@Nullable String docName); 
    AddItemToCreateDoc docDescription(@Nullable String docDescription);
    AddItemToCreateDoc docSubStatus(@Nullable String subStatus);
    AddItemToCreateDoc docStartsAt(@Nullable OffsetDateTime docStartsAt); 
    AddItemToCreateDoc docEndsAt(@Nullable OffsetDateTime docEndsAt); 
    
    AddItemToCreateDoc ownerId(@Nullable String ownerId);
    AddItemToCreateDoc branchName(String branchName); // first branch of the document, when empty generated as 'main' by the system
    AddItemToCreateDoc branchContent(JsonObject branchContent); 
    AddItemToCreateDoc commands(List<JsonObject> commands);
    
    CreateManyDocs next();
  }

  /*
   * Modify/Delete existing doc by: One/Many 
   */
  interface ModifyOneDoc {
    ModifyOneDoc docId(String docIdOrExternalId);
    ModifyOneDoc commitAuthor(String author);
    ModifyOneDoc commitMessage(String message);
    
    ModifyOneDoc docStartsAt(OffsetDateTime docStartsAt);
    ModifyOneDoc docEndsAt(OffsetDateTime docEndsAt);
    
    ModifyOneDoc docName(@Nullable String docName); 
    ModifyOneDoc docDescription(@Nullable String docDescription);
    ModifyOneDoc docSubStatus(@Nullable String subStatus);
    ModifyOneDoc parentDocId(@Nullable String parentDocId); 
    ModifyOneDoc externalId(@Nullable String externalId); // user given unique id
    ModifyOneDoc ownerId(@Nullable String ownerId);       //user given 'grouping' identifier for claiming ownership  
    ModifyOneDoc meta(@Nullable JsonObject docMeta);
    ModifyOneDoc commands(List<JsonObject> commands);
    ModifyOneDoc commitTreeEnabled(boolean commitTreeEnabled); // disabled doc_log table fully
    ModifyOneDoc commitLogExcludesBranchBody(); // disables writing into doc_log(body_before, body_after, body_patch) and doc_commit.commit_log
    
    ModifyOneDoc remove();   // remove the whole document                         
    Uni<OneDocEnvelope> build();
  }
  interface ModifyManyDocs {
    ModifyManyDocs commitAuthor(String author);
    ModifyManyDocs commitMessage(String message);
    ModifyManyDocs commitTreeEnabled(boolean commitTreeEnabled); // disabled doc_log table fully
    ModifyManyDocs commitLogExcludesBranchBody(); // disables writing into doc_log(body_before, body_after, body_patch) and doc_commit.commit_log
    AddItemToModifyDoc item();
    Uni<ManyDocsEnvelope> build();
  }
  interface AddItemToModifyDoc {
    AddItemToModifyDoc docId(String docIdOrExternalId);
    AddItemToModifyDoc docName(@Nullable String name);
    AddItemToModifyDoc docSubStatus(@Nullable String subStatus);
    AddItemToModifyDoc docStartsAt(@Nullable OffsetDateTime docStartsAt); 
    AddItemToModifyDoc docEndsAt(@Nullable OffsetDateTime docEndsAt); 
    AddItemToModifyDoc parentDocId(@Nullable String parentDocId); 
    AddItemToModifyDoc externalId(@Nullable String externalId); // user given unique id
    AddItemToModifyDoc ownerId(@Nullable String ownerId);       //user given 'grouping' identifier for claiming ownership  
    AddItemToModifyDoc meta(@Nullable JsonObject docMeta);
    AddItemToModifyDoc commands(@Nullable List<JsonObject> docMeta);
    AddItemToModifyDoc remove();
    ModifyManyDocs next();
  }
  
  
  /*
   * Modify/Delete existing branch by: One/Many 
   */
  interface CreateOneDocBranch {
    CreateOneDocBranch docId(String docId);
    CreateOneDocBranch branchFrom(@Nullable String branchIdFromWhatToCreateABranch);  // branch name from what to create the branch
    CreateOneDocBranch commitAuthor(String author);
    CreateOneDocBranch commitMessage(String message);

    CreateOneDocBranch commands(List<JsonObject> commands);
    CreateOneDocBranch branchName(String branchName);
    CreateOneDocBranch branchContent(JsonObject branchContent);
    CreateOneDocBranch commitLogExcludesBranchBody(); // disables writing into doc_log(body_before, body_after, body_patch) and doc_commit.commit_log 
    CreateOneDocBranch commitTreeEnabled(boolean commitTreeEnabled); // disabled doc_log table fully
    
    Uni<OneDocEnvelope> build();
  }
  
  interface ModifyOneDocBranch {
    ModifyOneDocBranch docId(String docId);
    ModifyOneDocBranch commit(String versionToModify);
    ModifyOneDocBranch parentIsLatest();
    
    ModifyOneDocBranch branchName(String branchName);
    ModifyOneDocBranch commands(List<JsonObject> commands);
    ModifyOneDocBranch replace(JsonObject newContent); 
    ModifyOneDocBranch merge(JsonObjectMerge doc);

    ModifyOneDocBranch remove(); // deletes the branch

    ModifyOneDocBranch commitAuthor(String author);
    ModifyOneDocBranch commitMessage(String message);
    ModifyOneDocBranch commitLogExcludesBranchBody(); // disables writing into doc_log(body_before, body_after, body_patch) and doc_commit.commit_log 
    ModifyOneDocBranch commitTreeEnabled(boolean commitTreeEnabled); // disabled doc_log table fully
    
    Uni<OneDocEnvelope> build();
  }
  
  interface ModifyManyDocBranches {
    int getItemsAdded();
    ModifyManyDocBranches commitAuthor(String author);
    ModifyManyDocBranches commitMessage(String message);
    ModifyManyDocBranches commitLogExcludesBranchBody(); // disables writing into doc_log(body_before, body_after, body_patch) and doc_commit.commit_log 
    ModifyManyDocBranches commitTreeEnabled(boolean commitTreeEnabled); // disabled doc_log table fully
    
    AddItemToModifyDocBranch item();
    Uni<ManyDocsEnvelope> build();
  }
  
  interface AddItemToModifyDocBranch {
    AddItemToModifyDocBranch docId(String docId);
    AddItemToModifyDocBranch commit(String versionToModify);

    AddItemToModifyDocBranch parentIsLatest();
    AddItemToModifyDocBranch branchName(String branchName);
    AddItemToModifyDocBranch commands(List<JsonObject> commands);
    AddItemToModifyDocBranch replace(JsonObject newContent); 
    AddItemToModifyDocBranch merge(JsonObjectMerge doc);

    AddItemToModifyDocBranch remove(); // deletes the branch
    ModifyManyDocBranches next();
  }
  
  
  @Value.Immutable
  interface OneDocEnvelope extends ThenaEnvelope {
    String getRepoId();
    @Nullable Doc getDoc();
    @Nullable DocBranch getBranch();
    @Nullable DocCommit getCommit();
    List<DocCommands> getCommands();
    List<DocCommit> getCommits();
    List<DocCommitTree> getCommitTree();
    
    CommitResultStatus getStatus();
    List<Message> getMessages();
  }
  @Value.Immutable
  interface ManyDocsEnvelope extends ThenaEnvelope {
    String getRepoId();
    List<Doc> getDoc();
    List<DocBranch> getBranch();
    List<DocCommands> getCommands();
    List<DocCommit> getCommits();
    List<DocCommitTree> getCommitTree();
    CommitResultStatus getStatus();
    List<Message> getMessages();
  }
  
  @FunctionalInterface
  interface JsonObjectMerge {
    JsonObject apply(JsonObject previousState);
  }
}
