export const fi = {
  'booleanValue.true': 'Kyllä',
  'booleanValue.false': 'Ei',
  'cust.inbox.message.sender-name.org-user': 'Info',
  'cust.phone': 'Puhelin: 12345',
  'cust.email': 'info@lifeDigital.com',
  'footer.column2.title': 'DigiExpress',
  'footer.column2.subtitle': 'Avoimen lähdekoodin alusta palvelujen digitalisointiin',
  'footer.column3.link.acessibility': 'Saavutettavuus seloste',
  'footer.column3.link.dataProtection': 'Tietosuoja',
  'footer.column3.link.feedback': 'Palautteet',
  'footer.column3.link.siteInfo': 'Lisätieto tästä sivustosta',
  'footer.column3.link.newsletter': 'Tilaa uutiskirje',
  'footer.column4.title': 'DigiExpress info',
  'footer.column4.email': 'Sähköposti: info@digiExpress.io',
  'footer.column4.phone': 'Phone: 123 456 7890',
  'footer.column4.address': 'Käyntiosoite: 1234 Suomentie 4, Suomi',
  'footer.column4.postalCode': 'Postinumero: 1234',
  'gamut.forms': 'Lomake',
  'gamut.new-messages': 'Uusi viesti',
  'gamut.services': 'Palvelut',
  'gamut.bookings': 'Kalenteri varaukset',
  'gamut.noValueIndicator': '-',
  'gamut.loading': 'Sisältöä ladataan',
  'gamut.public.servicesHome': 'Palvelut pääsivu',
  'gamut.public.forms.summary.button.backToServicesHome': 'Takaisin Palvelut pääsivulle',
  'gamut.buttons.login': 'Kirjaudu sisään',
  'gamut.buttons.logout': 'Kirjaudu ulos',
  'gamut.buttons.search': 'Hae',
  'gamut.buttons.cancel': 'Peruuta',
  'gamut.buttons.select': 'Valitse',
  'gamut.buttons.close': 'Sulje',
  'gamut.buttons.reply': 'Vastaa',
  'gamut.buttons.delete': 'Poista',
  'gamut.buttons.serviceSelect': 'Palvelumme',
  'gamut.buttons.attachment.add': 'Lisää liite',
  'gamut.locale.en': 'Englanti',
  'gamut.locale.fi': 'Suomi',
  'gamut.locale.sv': 'Ruotsi',
  'gamut.search.placeholder': 'Hae palvelua',
  'gamut.search.popover.title': 'Hae sivustolta',
  'gamut.search.popover.input.placeholder': 'Mitä etsi',
  'gamut.search.popover.result.chip.form': 'Lomake',
  'gamut.search.popover.result.chip.link': 'Linkki',
  'gamut.search.popover.result.chip.phone': 'Puhelin',
  'gamut.search.popover.result.chip.content': 'Sisältö',
  'gamut.search.popover.allForms': 'Kaikki lomakkeet',
  'gamut.search.popover.allPhones': 'Kaikki puhelin numerot',
  'gamut.search.popover.allLinks': 'Kaikki linkit',
  'gamut.search.popover.allServices': 'Kaikki palvelut',
  'gamut.article.pagelinks.forms.title': 'Lomakkeet',
  'gamut.article.pagelinks.otherlinks.title': 'Linkit',
  'gamut.forms.formName': 'Lomakkeen nimi',
  'gamut.forms.started': 'Aloitettu',
  'gamut.forms.status': 'Tila',
  'gamut.forms.status.OPEN': 'Käsittelyssä',
  'gamut.forms.status.NEW': 'Valmis käsittelyyn',
  'gamut.forms.status.COMPLETED': 'Valmis käsittelyyn',
  'gamut.forms.status.REJECTED': 'Poistettu',
  'gamut.forms.lastModified': 'Viimeksi muutettu',
  'gamut.forms.files': 'Liitteet',
  'gamut.forms.messages': 'Viestit',
  'gamut.forms.page.subtitle': 'Seuraava:{nextPageTitle}',
  'gamut.forms.page.subtitle.complete': 'Seuraava: Valmis',
  'gamut.forms.page.stepper': '{start} of {end}',
  'gamut.forms.page.selection.key': 'Step {stepNumber} out of {totalSteps}',
  'gamut.forms.page.next': 'Seuraava',
  'gamut.forms.page.complete': 'Valmis',
  'gamut.forms.filling.welcome': 'Tervetuloa',
  'gamut.forms.summary.button.back-to-overview': 'Takaisin Minun asiat sivulle',
  'gamut.forms.answer.date.placeholder.day': 'pp',
  'gamut.forms.answer.date.placeholder.month': 'kk',
  'gamut.forms.answer.date.placeholder.year': 'vvvv',
  'gamut.forms.answer.date.placeholder.hour': 'tt',
  'gamut.forms.answer.date.placeholder.minute': 'mm',
  'gamut.forms.answer.boolean.yes': 'Kyllä',
  'gamut.forms.answer.boolean.no': 'Ei',
  'gamut.forms.unfinished.none': 'Sinulla ei ole keskeneräisiä lomakkeita',
  'gamut.forms.awaitingDecision.none': 'Sinulla ei ole keskeneräisiä asiointipyyntöjä',
  'gamut.forms.page.selection.start': 'Aloita',
  'gamut.forms.page.selection.complete': 'Valmis',
  'gamut.forms.unfinished.title': 'Keskeneräiset lomakkeet'
}