export const my = {
  'booleanValue.true': 'Ya',
  'booleanValue.false': 'Tidak',
  'cust.inbox.message.sender-name.org-user': 'Meja maklumat',
  'cust.phone': 'Telefon: 123 456 7890',
  'cust.email': 'info@lifeDigital.com',
  'header.userIdentity.label': 'Sedang masuk sebagai',
  'document.title': 'DigiExpress',
  'footer.column2.title': 'DigiExpress',
  'footer.column2.subtitle': 'Platform sumber terbuka untuk perkhidmatan pendigitalan',
  'footer.column3.title': 'Pautan pantas',
  'footer.column3.link.acessibility': 'Kenyataan kebolehcapaian',
  'footer.column3.link.dataProtection': 'Perlindungan data',
  'footer.column3.link.feedback': 'Maklum balas dan idea pembangunan',
  'footer.column3.link.siteInfo': 'Maklumat mengenai tapak',
  'footer.column3.link.newsletter': 'Langgan surat berita',
  'footer.column4.title': 'Maklumat DigiExpress',
  'footer.column4.email': 'E-mel: info@digiExpress.io',
  'footer.column4.phone': 'Telefon: 123 456 7890',
  'footer.column4.address': 'Alamat lawatan: 1234 Any Street MyTown',
  'footer.column4.postalCode': 'Poskod: 1234',
  'gamut.forms': 'Borang',
  'gamut.new-messages': 'Mesej baharu',
  'gamut.services': 'Perkhidmatan',
  'gamut.bookings': 'Tempahan kalendar',
  'gamut.noValueIndicator': '-',
  'gamut.noValueIndicatorColon': '-',
  'gamut.textSeparatorColon': ':',
  'gamut.loading': 'Kandungan anda sedang dalam perjalanan',
  'gamut.public.servicesHome': 'Perkhidmatan rumah',
  'gamut.public.forms.summary.button.backToServicesHome': 'Kembali ke Laman Utama Perkhidmatan',
  'gamut.buttons.login': 'Log masuk',
  'gamut.buttons.logout': 'Log keluar',
  'gamut.buttons.search': 'Cari',
  'gamut.buttons.cancel': 'Batal',
  'gamut.buttons.select': 'Pilih',
  'gamut.buttons.close': 'Tutup',
  'gamut.buttons.reply': 'Balas',
  'gamut.buttons.delete': 'Padam',
  'gamut.buttons.serviceSelect': 'Perkhidmatan kami',
  'gamut.buttons.attachment.add': 'Tambah lampiran',
  'gamut.buttons.sort-last-modified.contracts': 'Isih mengikut terakhir diubah suai',
  'gamut.buttons.sort-last-modified.offers': 'Isih mengikut terakhir diubah suai',
  'gamut.buttons.sort-last-modified.inbox': 'Isih mengikut terakhir diubah suai',
  'gamut.locale.en': 'Inggeris',
  'gamut.locale.fi': 'Bahasa Finland',
  'gamut.locale.sv': 'Bahasa Sweden',
  'gamut.locale.my': 'Bahasa Melayu',
  'gamut.locale.bs': 'Bahasa Bosnia',
  'gamut.search.placeholder': 'Cari perkhidmatan kami',
  'gamut.search.popover.title': 'Cari tapak kami',
  'gamut.search.popover.input.placeholder': 'Apa yang anda cari?',
  'gamut.search.popover.result.chip.form': 'Borang',
  'gamut.search.popover.result.chip.link': 'Pautan',
  'gamut.search.popover.result.chip.phone': 'Telefon',
  'gamut.search.popover.result.chip.content': 'Kandungan',
  'gamut.search.popover.allForms': 'Semua bentuk',
  'gamut.search.popover.allPhones': 'Semua nombor telefon',
  'gamut.search.popover.allLinks': 'Semua pautan',
  'gamut.search.popover.allServices': 'Semua perkhidmatan',
  'gamut.search.results.allResults': 'Semua keputusan',
  'gamut.search.results.noResults': 'Tiada hasil',
  'gamut.search.results.serviceLinks': 'Perkhidmatan',
  'gamut.search.results.formLinks': 'Borang',
  'gamut.search.results.phoneLinks': 'Telefon',
  'gamut.search.results.internalExternalLinks': 'Pautan',
  'gamut.search.results.internalLinks': 'Pautan',
  'gamut.search.results.externalLinks': 'Pautan luar',
  'gamut.search.results.otherForms': 'Bentuk lain',
  'gamut.article.pagelinks.forms.title': 'Borang',
  'gamut.article.pagelinks.otherlinks.title': 'Pautan',
  'gamut.forms.formName': 'Nama',
  'gamut.forms.taskRefId': 'Id Rujukan',
  'gamut.forms.started': 'Bermula',
  'gamut.forms.status': 'Status',
  'gamut.forms.status.OPEN': 'Sedang berlangsung',
  'gamut.forms.status.NEW': 'Pemprosesan bermula tidak lama lagi',
  'gamut.forms.status.COMPLETED': 'Selesai',
  'gamut.forms.status.REJECTED': 'Ditolak',
  'gamut.forms.lastModified': 'Terakhir diubah suai',
  'gamut.forms.files': 'Fail',
  'gamut.forms.messages': 'Mesej',
  'gamut.forms.page.subtitle': 'Seterusnya:{nextPageTitle}',
  'gamut.forms.page.subtitle.complete': 'Seterusnya: Lengkap',
  'gamut.forms.page.stepper': '{start} of {end}',
  'gamut.forms.page.selection.key': 'Langkah {stepNumber} daripada {totalSteps}',
  'gamut.forms.page.next': 'Seterusnya',
  'gamut.forms.page.complete': 'Lengkap',
  'gamut.forms.page.cancel': 'Batal',
  'gamut.forms.filling.welcome': 'Selamat datang!',
  'gamut.forms.filling.must_be_authenticated': 'Anda mesti log masuk untuk mengisi borang ini',
  'gamut.forms.filling.authenticated_and_welcome': 'Hello {userName}!',
  'gamut.forms.filling.proceed_to_form': 'Sila klik di bawah untuk memulakan borang',
  'gamut.forms.filling.anonUser_and_welcome': 'Hello!',
  'gamut.forms.filling.start': 'Anda akan memulakan borang ini',
  'gamut.forms.filling.login-then-start.button': 'Log in now',
  'gamut.forms.filling.start.info1': 'Kemajuan borang anda disimpan secara automatik semasa anda pergi',
  'gamut.forms.filling.start.button': 'Teruskan membentuk',
  'gamut.forms.filling.cancel.button': 'Batal',
  'gamut.forms.filling.summary': 'Anda telah melengkapkan borang',
  'gamut.forms.filling.summary.thank-you': 'terima kasih!',
  'gamut.forms.filling.summary.info1': 'Kakitangan kami telah dimaklumkan tentang permintaan anda dan akan mula memproses tidak lama lagi.',
  'gamut.forms.filling.summary.info2': 'Pastikan anda menyemak Gambaran Keseluruhan Saya dengan kerap untuk',
  'gamut.forms.filling.summary.info3': 'Kemas kini status pemprosesan borang',
  'gamut.forms.filling.summary.info4': 'Mesej baharu daripada kakitangan kami mengenai permintaan anda',
  'gamut.forms.filling.summary.info5': 'Fail baharu yang telah kami hantar kepada anda atau diminta daripada anda',
  'gamut.forms.filling.summary.info6': 'Masih ada soalan? Hubungi kami melalui telefon di xxxx-xxxx dengan pertanyaan',
  'gamut.forms.filling.representativeNotAuthorized': 'Anda tidak memiliki izin untuk mengisi formulir ini. Hubungi kantor kami.',
  'gamut.forms.summary.button.back-to-overview': 'Kembali ke Gambaran Keseluruhan Saya',
  'gamut.forms.answer.date.placeholder.day': 'hh',
  'gamut.forms.answer.date.placeholder.month': 'bb',
  'gamut.forms.answer.date.placeholder.year': 'tttt',
  'gamut.forms.answer.date.placeholder.hour': 'jj',
  'gamut.forms.answer.date.placeholder.minute': 'mm',
  'gamut.forms.answer.boolean.yes': 'Ya',
  'gamut.forms.answer.boolean.no': 'Tidak',
  'gamut.forms.unfinished.none': 'Anda tidak mempunyai sebarang borang yang belum selesai',
  'gamut.forms.awaitingDecision.none': 'Anda tidak mempunyai sebarang borang menunggu keputusan',
  'gamut.forms.page.selection.start': 'Mulakan',
  'gamut.forms.page.selection.complete': 'Lengkap',
  'gamut.forms.unfinished.title': 'Borang yang belum selesai',
  'gamut.forms.unfinished.subtitle': 'Pemprosesan belum bermula - Sila pilih borang untuk terus mengisi atau membatalkan',
  'gamut.forms.awaitingDecision.title': 'Borang menunggu keputusan',
  'gamut.forms.awaitingDecision.subtitle': 'Pemprosesan telah bermula - Kakitangan kami sedang mengusahakan permintaan anda',
  'gamut.forms.withDecision.title': 'Borang dengan keputusan muktamad',
  'gamut.forms.withDecision.subtitle': 'Pemprosesan selesai dan dimuktamadkan',
  'gamut.offers.deleteForm.title': 'Padamkan borang yang belum selesai',
  'gamut.offers.deleteForm.content': 'Adakah anda pasti mahu memadamkan borang ini? Anda tidak boleh membuat asal tindakan ini.',
  'gamut.offers.deleteForm.cancelButton': 'Jangan simpan borang ini',
  'gamut.offers.deleteForm.deleteButton': 'Ya padamkan borang ini',
  'gamut.inbox.title': 'Peti masuk',
  'gamut.inbox.subtitle': 'Mesej dan fail yang berkaitan dengan borang anda',
  'gamut.inbox.sender': 'Penghantar',
  'gamut.inbox.files': 'Fail',
  'gamut.inbox.messages': 'Mesej: {count}',
  'gamut.inbox.messages.title': 'Mesej',
  'gamut.inbox.formName': 'Nama borang',
  'gamut.inbox.message-preview': 'Pratonton mesej',
  'gamut.inbox.message-date': 'Tarikh',
  'gamut.inbox.subjectAttachment.title': 'Lampiran',
  'gamut.inbox.newMessage.placeholder': 'Sila tulis mesej anda',
  'gamut.inbox.newMessage.replyingTo': 'Membalas kepada',
  'gamut.inbox.newMessage.sendNew': 'Hantar mesej baharu',
  'gamut.inbox.newMessage.replyingTo.subject': 'Subjek',
  'gamut.inbox.newMessage.notAllowed1': 'Mesej tidak didayakan.',
  'gamut.inbox.newMessage.notAllowed2': 'Kami memohon maaf atas kesulitan ini.',
  'gamut.inbox.newMessage.notAllowed.questions': 'Sila hubungi kami melalui telefon atau e-mel untuk pertanyaan lanjut.',
  'gamut.inbox.noMessages': 'Tiada mesej',
  'gamut.inbox.newMessageFrom': 'Mesej baharu daripada',
  'gamut.subjectMessage.title': 'Mesej berkenaan {subject}',
  'gamut.bookings.title': 'Tempahan kalendar',
  'gamut.bookings.subtitle': 'Uruskan janji temu dan tempahan anda yang sedia ada di sini',
  'gamut.bookings.serviceName': 'Nama perkhidmatan',
  'gamut.bookings.bookingDateTime': 'Tarikh dan masa yang dijadualkan',
  'gamut.bookings.deleteBooking.title': 'Batalkan tempahan kalendar',
  'gamut.bookings.deleteBooking.content': 'Adakah anda pasti mahu membatalkan tempahan anda? Anda tidak boleh membuat asal tindakan ini.',
  'gamut.bookings.deleteBooking.cancelButton': 'Jangan simpan tempahan saya',
  'gamut.bookings.deleteBooking.deleteButton': 'Ya batalkan tempahan ini',
  'gamut.userOverview.services.detail.title': 'Cari perkhidmatan dan mulakan borang',
  'gamut.userOverview.buttons.logout-representative': 'Log keluar sebagai wakil',
  'gamut.userOverview.buttons.login-representative': 'Log masuk sebagai wakil',
  'gamut.userOverview.buttons.logout': 'Log keluar',
  'gamut.userOverview.buttons.logout-company': 'Log keluar sebagai syarikat',
  'gamut.userOverview.buttons.login-company': 'Log masuk sebagai syarikat',
  'gamut.userOverview.buttons.user-overview': 'Rumah gambaran keseluruhan pengguna',
  'gamut.userOverview.buttons.services': 'Cari perkhidmatan dan mulakan borang',
  'gamut.userOverview.buttons.requests-in-progress': 'Borang yang belum selesai',
  'gamut.userOverview.buttons.awaiting-decision': 'Borang menunggu keputusan',
  'gamut.userOverview.buttons.with-decision': 'Borang dengan keputusan muktamad',
  'gamut.userOverview.buttons.inbox': 'Peti masuk',
  'gamut.userOverview.buttons.bookings': 'Tempahan kalendar',
  'gamut.userOverview.home': 'Rumah gambaran keseluruhan pengguna',
  'gamut.userOverview.welcome.title': 'Selamat datang ke Gambaran Keseluruhan saya',
  'gamut.userOverview.unfinished-forms.detail.title': 'Borang yang belum selesai',
  'gamut.userOverview.waiting-forms.detail.title': 'Borang menunggu keputusan',
  'gamut.userOverview.decided-forms.detail.title': 'Borang dengan keputusan muktamad',
  'gamut.userOverview.inbox.detail.title': 'Peti masuk',
  'gamut.userOverview.bookings.detail.title': 'Tempahan kalendar',
  'gamut.userOverview.personal-info.detail.title': 'Maklumat peribadi saya',
  'gamut.userOverview.welcome.desc': 'Dari sini anda boleh mencari dan memohon perkhidmatan kami melihat status aplikasi anda menghantar mesej dan fail serta menempah janji temu dengan kami',
  'gamut.services.subtitle': 'Pilih atau cari perkhidmatan untuk melihat borang yang tersedia',
  'gamut.feedback.table.sorted.desc': 'Diisih menurun',
  'gamut.feedback.table.sorted.asc': 'Diisih menaik',
  'gamut.feedback.table.topic': 'Topik',
  'gamut.feedback.table.subtopic': 'Sub topik',
  'gamut.feedback.table.updatedOnDate': 'Tarikh',
  'gamut.feedback.table.title': 'Maklum balas',
  'gamut.feedback.table.topicTitle': 'Tajuk',
  'gamut.feedback.table.nodata': 'Tiada data',
  'gamut.feedback.vote.title': 'Adakah jawapan ini membantu?',
  'gamut.feedback.vote.notHelpful': 'Tidak, ini tidak membantu',
  'gamut.feedback.vote.yesHelpful': 'Ya ini membantu',
  'gamut.feedback.vote.loginReq': 'Anda mesti log masuk untuk menilai maklum balas',
  'gamut.feedback.updatedOnDate': 'Tarikh dikemas kini',
  'gamut.feedback.feedbackViewerTitle': 'Maklum balas pelanggan',
  'gamut.feedback.feedbackViewerSubTitle': 'Balasan organisasi',
  'dialob.review.title': 'Semakan borang',
  'dialob.review.button.close': 'Tutup'
}