load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

RULES_JVM_EXTERNAL_TAG = "5.2"
RULES_JVM_EXTERNAL_SHA ="f86fd42a809e1871ca0aabe89db0d440451219c3ce46c58da240c7dcdc00125f"

http_archive(
    name = "rules_jvm_external",
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    sha256 = RULES_JVM_EXTERNAL_SHA,
    url = "https://github.com/bazelbuild/rules_jvm_external/releases/download/%s/rules_jvm_external-%s.tar.gz" % (RULES_JVM_EXTERNAL_TAG, RULES_JVM_EXTERNAL_TAG)
)

load("@rules_jvm_external//:repositories.bzl", "rules_jvm_external_deps")

rules_jvm_external_deps()

load("@rules_jvm_external//:setup.bzl", "rules_jvm_external_setup")

rules_jvm_external_setup()

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    maven_install_json = "//:maven_install.json",
    artifacts = [
        "ch.qos.logback:logback-classic:1.2.11",
        "com.fasterxml.jackson.core:jackson-core:2.13.4",
        "com.fasterxml.jackson.core:jackson-annotations:2.13.4",
        "com.fasterxml.jackson.datatype:jackson-datatype-guava:2.13.4",
        "com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.13.0",
        "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.13.0",
        "com.fasterxml.jackson.core:jackson-databind:2.13.0",
        "com.google.code.findbugs:jsr305:3.0.2",
        "commons-codec:commons-codec:1.15",
        "io.dialob:dialob-client-api:3.0.4",
        "io.dialob:dialob-compiler:3.0.4",
        "io.dialob:dialob-rule-parser:3.0.4",
        "io.dialob:dialob-form-store-pgsql:3.0.4",
        "io.dialob:dialob-api:2.2.3",
        "io.resys.hdes:hdes-client-api:3.130.59",
        "io.resys.hdes:hdes-store-thena:3.130.59",
        "io.resys.hdes:thena-docdb-pgsql:1.1.24",
        "io.resys.hdes:thena-docdb-api:1.1.24",
        "io.smallrye.reactive:mutiny:1.8.0",
        "io.smallrye.reactive:smallrye-mutiny-vertx-pg-client:2.27.0",
        "io.vertx:vertx-pg-client:4.3.4",
        "io.vertx:vertx-sql-client:4.3.4",
        "io.thestencil:stencil-client-api:1.148.15",
        "jakarta.validation:jakarta.validation-api:2.0.2",
        "org.apache.commons:commons-lang3:3.12.0",
        "org.ehcache:ehcache:3.8.1",
        "org.immutables:gson:2.8.8",
        "org.immutables:value:2.8.8",
        "org.projectlombok:lombok:1.18.22",
        "org.slf4j:slf4j-api:1.7.36",
        "org.springframework.boot:spring-boot-autoconfigure:2.7.0",
        "org.springframework.boot:spring-boot-starter-actuator:2.7.0",
        "org.springframework.boot:spring-boot-starter-thymeleaf:2.7.0",
        "org.springframework.boot:spring-boot-starter-web:2.7.0",
        "org.springframework.boot:spring-boot:2.7.0",
        "org.hibernate.validator:hibernate-validator:6.2.5.Final"
    ],
    excluded_artifacts = ["org.hibernate:hibernate-validator"],
    repositories = [
    	"https://maven.google.com",
    	"https://repo1.maven.org/maven2",
    ],
      fetch_sources = True,
      version_conflict_policy = 'pinned',
      strict_visibility = True,
      generate_compat_repositories = False,
)

load("@maven//:defs.bzl", "pinned_maven_install")
pinned_maven_install()
