# This is where everything around bazel starts in our project.
# We will define all global bazel library imports in here.
# This file just defines, bazel libraries that we will use, from here you should see the BUILD file in the same directory.
#

# Root folder/project definition, optional, just informative
workspace(
  name = "digiexpress_with_bazel",
  # Map the @npm bazel workspace to the node_modules directory. This lets Bazel use the same node_modules as other local tooling.
  managed_directories = {"@npm": ["node_modules"]},
)

# Import built in `rule` called `http_archive` for downloading extra bazel `rules`
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Download java rules, this will add support for java/maven related build operations
# In bazel version 7 this is made a lot easier, via MODULE file.
RULES_JVM_EXTERNAL_TAG = "5.2"
RULES_JVM_EXTERNAL_SHA ="f86fd42a809e1871ca0aabe89db0d440451219c3ce46c58da240c7dcdc00125f"
http_archive(
    name = "rules_jvm_external",
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    sha256 = RULES_JVM_EXTERNAL_SHA,
    url = "https://github.com/bazelbuild/rules_jvm_external/releases/download/%s/rules_jvm_external-%s.tar.gz" % (RULES_JVM_EXTERNAL_TAG, RULES_JVM_EXTERNAL_TAG)
)
# Standard way of loading. This is part of setting up java support for, will download additional libraries and dependencies from maven
load("@rules_jvm_external//:repositories.bzl", "rules_jvm_external_deps")
rules_jvm_external_deps()
load("@rules_jvm_external//:setup.bzl", "rules_jvm_external_setup")
rules_jvm_external_setup()


# Download contrib java rules we will use this for junit5 support
CONTRIB_RULES_JVM_VERSION = "0.9.0"
CONTRIB_RULES_JVM_SHA = "548f0583192ff79c317789b03b882a7be9b1325eb5d3da5d7fdcc4b7ca69d543"
http_archive(
    name = "contrib_rules_jvm",
    sha256 = CONTRIB_RULES_JVM_SHA,
    strip_prefix = "rules_jvm-%s" % CONTRIB_RULES_JVM_VERSION,
    url = "https://github.com/bazel-contrib/rules_jvm/archive/refs/tags/v%s.tar.gz" % CONTRIB_RULES_JVM_VERSION,
)

# Standard way of loading. This is part of setting up java support, will download additional libraries and dependencies from maven
load("@contrib_rules_jvm//:repositories.bzl", "contrib_rules_jvm_deps")
contrib_rules_jvm_deps()
load("@contrib_rules_jvm//:setup.bzl", "contrib_rules_jvm_setup")
contrib_rules_jvm_setup()




# Setup maven dependencies, perform command equivalent to maven install, creates/updates/loads lock file and folder "@maven"
load("//tools/maven:maven_setup.bzl", "maven_setup")
maven_setup()

# load the lock file generated previously
load("@maven//:defs.bzl", "pinned_maven_install")
# install dependencies from the lock file
pinned_maven_install()