###
# #%L
# hdes-dev-app
# %%
# Copyright (C) 2020 Copyright 2020 ReSys OÜ
# %%
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# #L%
###


quarkus:
    

  http:
    cors: true
    auth: 
      policy:
        hdes-role-policy:
          roles-allowed: hdes-projects-admin
      permission:
        deny1:
          paths: /hdes-pm/*
          policy: hdes-role-policy
        deny2:
          paths: /hdes-pm/*
          policy: authenticated

  log:
    level: DEBUG
    category: 
      io.resys.hdes:
        level: DEBUG

  hdes-projects:
    init-user-name: olev.mutso@resys.io
    connection-url: mongodb://appUser:123456@localhost:27017/PM?authSource=PM
    
    
    
    