quarkus:
  http:
    cors: true

  log:
    level: DEBUG
    category: 
      io.resys:
        level: DEBUG

  stencil-composer:
    server-path: /q/ide-services

  stencil-composer-pg:
    service-path: /q/ide-services
    repo:
      repo-name: test-assets

  stencil-sc:
    service-path: /q/site
    site-json: site.json

  datasource:
    db-kind: postgresql 
    username: spo_stencil
    password: joo4XooHllK2thei
    reactive:
      max-size: 16
      url: postgresql://localhost:5432/spo_stencil

"%prod":
  quarkus:

"%dev":
  quarkus:
    log:
      level: DEBUG
      category: 
        io.thestencil:
          level: DEBUG
        io.resys:
          level: DEBUG