version: '3.1'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasks_db
    ports:
      - 5432:5432

  application:
    image: docker.io/library/digiexpress-dev-app:1-snapshot
    restart: always
    environment:
      TENANT_CURRENTTENANTID: "local_test_tenant"
      TENANT_DB_PG_PGREPOSITORYNAME: "5432"
      TENANT_DB_PG_PGPORT: "5432"
      TENANT_DB_PG_PGHOST: "localhost"
      TENANT_DB_PG_PGDB: "tasks_db"
      TENANT_DB_PG_PGUSER: "postgres"
      TENANT_DB_PG_PGPASS: "postgres"
      TENANT_DB_PG_PGPOOLSIZE: "5"
      DIGIEXPRESS_ASSETS_URL: "https://cdn.resys.io/digiexpress-io/tasks-ui/dev/"
      DIGIEXPRESS_INDEX_PAGE: "index.html"
    ports:
      - 8080:8080
    links:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8091:8080
    links:
      - db
