import React from 'react';


/*
  "permissions": [
    "WRENCH_VIEW",     --> 'NAV_TO_WRENCH'
    "STENCIL_VIEW",    --> 'NAV_TO_STENCIL'
    "FEEDBACK_VIEW",   --> 'NAV_TO_FEEDBACK'
    "DASHBOARD_VIEW",  --> 'NAV_TO_DASHBOARD'
    "TASK_ALL_VIEW",   --> 'NAV_TO_TASKS'
    "RELEASE_VIEW",    --> 'NAV_TO_RELEASES'
    "DEPLOYMENT_VIEW", --> 'NAV_TO_DEPLOYMENTS'
    "TASK_GROUP_VIEW", --> 'NAV_TO_TASK_GROUP'
  
    "TASK_ALL_DELETE", --> 'DELETE_TASK_ALL'
    
    "FEEDBACK_EDIT",   --> 'EDIT_FEEDBACK'
    "STENCIL_EDIT",    --> 'EDIT_STENCIL'
    "WRENCH_EDIT",     --> 'EDIT_WRENCH'
    "TASK_GROUP_EDIT", --> 'EDIT_TASK_GROUP'
    "RELEASE_EDIT",    --> 'EDIT_RELEASE'
    "TASK_ALL_EDIT",   --> 'EDIT_TASK_ALL'
    "DEPLOYMENT_EDIT", --> 'EDIT_DEPLOYMENT'

    ],
*/

type PermissionType =
  'NAV_TO_WRENCH' |
  'NAV_TO_STENCIL' |
  'NAV_TO_TASKS' |
  'NAV_TO_DIALOB' |
  'NAV_TO_RELEASES' |
  'NAV_TO_DEPLOYMENTS' |
  'NAV_TO_TASK_GROUP' |

  'NAV_TO_TASKS_FEEDBACK' |
  'NAV_TO_TASKS_DASHBOARD' |
  'NAV_TO_TASKS_MONITORING' |
  'NAV_TO_TASKS_QUEUES' |

  'NAV_TO_STENCIL_ARTICLES' |
  'NAV_TO_STENCIL_SERVICES' |
  'NAV_TO_STENCIL_LINKS' |
  'NAV_TO_STENCIL_LOCALES' |
  'NAV_TO_STENCIL_TEMPLATES' |
  'NAV_TO_STENCIL_MIGRATIONS' |
  'NAV_TO_STENCIL_RELEASES' |

  'NAV_TO_WRENCH_FLOWS' |
  'NAV_TO_WRENCH_DECISIONS' |
  'NAV_TO_WRENCH_SERVICES' |
  'NAV_TO_WRENCH_DEBUG' |
  'NAV_TO_WRENCH_COMPARE' |
  'NAV_TO_WRENCH_RELEASES' |





  'CREATE_TASK' |
  'CREATE_STENCIL_ASSET' |
  'CREATE_WRENCH_ASSET' |
  
  'DELETE_TASK';


export const EveliPermissions: React.FC<{ children: React.ReactNode, id: PermissionType }> = ({ children, id }) => {

  return (<>{children}</>)
}