spring:
  config.activate.on-profile: 'dev'
  jpa:
    showSql: false
    generateDdl: false
    hibernate:
      ddlAuto: "validate"
      autoQuoteKeyword: true
      connection:
        useUnicode: true
        characterEncoding: 'UTF-8'
        charSet: 'UTF-8'
  flyway:
    enabled: true
    locations: classpath:db/postgresql
    validate-on-migrate: true

management:
  server:
    servlet.context-path: "/manage"
    add-application-context-header: false
  endpoints:
    web:
      exposure:
        include: "health,mappings"

# Logging config
#logging.level.org.springframework.web: INFO
#logging.org.springframework.http: INFO
#logging.level.org.springframework.boot: INFO


# quarkus warnings when something takes too long, or simply at breakpoint with debugger
logging.level.io.vertx.core.impl.btc.BlockedThreadChecker: OFF
logging.level.io.vertx.core.impl.BlockedThreadChecker: OFF
logging.level.io.digiexpress.eveli.dialob: OFF
# wrench asset compiler noise, for broken assets
logging.level.io.resys.hdes.client.spi.groovy: OFF
logging.level.io.resys.hdes.client.spi.envir: OFF

# deployment CACHE, BUILDERS, QUERIES
logging.level.io.digiexpress.eveli.envir.spi.actions.DeploymentBuilderLogger: OFF
logging.level.io.digiexpress.eveli.envir.spi.ExternalDeploymentProviderDevEnvir: OFF
logging.level.io.digiexpress.eveli.envir.spi.EveliRuntimeCacheInMemory: OFF
logging.level.io.digiexpress.eveli.envir.spi.actions.EveliRuntimeLogger: OFF
logging.level.io.thestencil.client.spi.staticontent.visitors.SiteStateVisitor: OFF
logging.level.io.resys.thena.datasource.TenantCacheImpl: OFF
logging.level.io.digiexpress.eveli.client.spi.mq.WrenchFlowCommand: ERROR

# SQL-s
#logging.level.io.resys.thena.show_sql: ERROR
#logging.level.io.resys.thenamq.show_sql: ERROR


# DB config
spring.datasource.url: "jdbc:postgresql://localhost:5433/eveli-app"
spring.datasource.username: "eveli-app"
spring.datasource.password: "password123"


eveli.task.adminsearch: true
eveli.assets.importDeployment: /Users/olevmutso/Development/init_v_1-3.json
eveli.assets.use-form-id: false

# dialob related config
eveli.dialob.enabled: true
eveli.dialob.service-url: http://localhost:9000
eveli.dialob.api-key:

# feedback  
eveli.feedback.enabled: true
eveli.feedback.forms: palautteet
eveli.feedback.category-main: mainList
eveli.feedback.category-sub: cityServiceGroup, preschoolEducationGroup, cityServiceMainList, constructionMainList, youthServiceMainList, exerciseMainList, schoolMainList, employmentImmigrationMainList, freeTimeCultureMainList, preschoolMainList, communicationMainList, cooperationMainList
eveli.feedback.question-title: feedBackTitle
eveli.feedback.question: feedBackTxt
eveli.feedback.username-allowed: publicAnswerAllowed

# jwt linked crm from security proxy
eveli.crm.enabled: false
eveli.crm.host: 
eveli.crm.service-path-company:
eveli.crm.service-path-person:

# mq
eveli.mq.enabled: true
eveli.mq.app-id: task-app
eveli.mq.channel-name: main-channel-for-all

eveli.jwt.eveli-public-key-value: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAi4PobwPTnWPJWwjnND2j\naYZoF8i0xGVI0FZsIcQ1cF1qSSHJH1J2JfspDpY4dJwN8zGsS3el4kgI0XcOzLam\n3s9U/Ix70kxTXvEosydtsPeKEh8qKIoTszPyHETPe3OyfhTR8mFggn0+2B1xSbMd\nsnlPLai+Xdp+o4Yg5A4ApxRpF/nvu8LdpSGfw3z1un+D+nEX3joWzc55mloHWiDi\nj2TUuqrDVNUz5oUYJJPUAYHa23hGFhWP21tFaqYeFwO6CGC8LxL6tN5ERh2hvXms\nLdN4ATCa/LjQQqv4Rls93R7jrEuNHjjMX2EOI/rLXZ1jgkB5VOYeJ7qHMmTu2YLY\nfQIDAQAB\n-----END PUBLIC KEY-----\n"
eveli.jwt.eveli-issuer: https://frontdesk.digiexpress.io/gateway/issuer
eveli.jwt.gamut-public-key-value: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkb8vttXCPPraVCQBkFR/\nNIVP4PXnYS9Ik3KBX3Th684d3P1OdEnQ4EMU3gn+jnG5+qQSs+KpXBvwcCsyE1jx\ncIeSQ5GpuXC1BwhCTSM6RY78I2A+mcnt4h45a9ipPi6W9PHfk+PzYFrrp9jgFflZ\n6fyJt5Hfaz3yhnPb7Y/GE5zz9v+HgoCLDbu7xj98BOgt7rIZ27End90Q1iFyQpu1\nYbyyvGy/61hUv/rDeL7gsypyfvjL1n5a1mJ2A3VheXLyLJIleu4vNw8yejtXqp7S\nHc9EiCCf+ccEQnQgAAWLOvgYMaIvaXmuT/MszCjSpsQyqbGV5k9TrlZ7X7gxvcOJ\njQIDAQAB\n-----END PUBLIC KEY-----\n"
eveli.jwt.gamut-issuer: "https://portal.digiexpress.io/gateway/issuer"


eveli.email.enabled: false
# In case of using jakarta email transport implementation
eveli.email.host-name: 
eveli.email.host-port: 
eveli.email.sender-email: 
eveli.email.sender-name: 
eveli.email.server-user-name: 
eveli.email.server-password: 
eveli.email.allowed-recipients: 
eveli.email.enabled-domains:
#in case of REST API implementation, if defined it is used
eveli.email.service-url:

eveli.notification.enabled: false
eveli.notification.service-url: 

eveli.user-registry.service-url:

eveli.envir.cache-expirations.short-deployment: PT1M
eveli.envir.cache-expirations.long-runtime: PT30M
eveli.envir.dev-enabled: false
eveli.tenant-features: batches-dev


