<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.digiexpress</groupId>
    <artifactId>digiexpress-build-parent</artifactId>
    <relativePath>../build-parent/pom.xml</relativePath>
    <version>5.1.54</version>
  </parent>

  <artifactId>eveli-parent</artifactId>
  <packaging>pom</packaging>
  
  <modules>
    <module>eveli-client</module>
    <module>eveli-envir</module>
    <module>eveli-integration-suomifi-rest</module>
    <module>eveli-integration-suomifi-wsl</module>
    <module>eveli-integration-google</module>
    <module>eveli-integration-queue</module>
    <module>eveli-integration-git</module>
    <module>eveli-app</module>
    <module>eveli-app-gcloud</module>
    <module>eveli-app-wrench-only</module>
    <module>dialob-client</module>
  </modules>
</project>