quarkus:

  log:
    level: INFO
    category: 
      io.resys:
        level: INFO
  http:
    tcp-quick-ack: true
    tcp-cork: true
    tcp-fast-open: true
    enable-compression: true
    body:
      preallocate-body-buffer: true
    limits:
      max-body-size: 102400K
      max-header-size: 102400K
      max-chunk-size: 102400K
  
  resteasy-reactive:
    output-buffer-size: 16384000

  vertx:
    keep-alive-time: PT10.000S

  native:
    resources:
      includes: asset_sysconfig_flat.json

tenant:
  currentTenantId: "local_test_tenant"
  failSafeUsers: olev.mutso@resys.io;jocelyn.mutso@resys.io
  db:
    pg: 
      repositoryName: "tenant_store"
      pgPort: 5432
      pgHost: "localhost"
      pgDb: "tasks_db"
      pgUser: "postgres"
      pgPass: "postgres"
      pgPoolSize: 5


"%dev": 
  tenant:
    failSafeUsers: sam.vimes@digiexpress.io
  quarkus:
    log:
      level: ERROR
      category:
        io.resys:
          level: DEBUG
        org.jboss.resteasy.reactive.server.handlers.RequestDeserializeHandler: 
          level: DEBUG
      console:  
        json: false

"%test":
  quarkus:
    log:
      level: ERROR
      category:
        io.resys:
          level: DEBUG
