quarkus:

  log:
    level: INFO
    category: 
      io.resys:
        level: DEBUG
  http:
    tcp-quick-ack: true
    tcp-cork: true
    tcp-fast-open: true
    enable-compression: true
    body:
      preallocate-body-buffer: true
    limits:
      max-body-size: 102400K
      max-header-size: 102400K
      max-chunk-size: 102400K
  
  resteasy-reactive:
    output-buffer-size: 16384000

  vertx:
    keep-alive-time: PT10.000S
    
tenant:
  currentTenantId: "local_test_tenant"
  db:
    pg: 
      repositoryName: "tenant_store"
      pgPort: 32788 
      pgHost: "localhost"
      pgDb: "tasks_db"
      pgUser: "postgres"
      pgPass: "postgres"
      pgPoolSize: 5
