/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SecuredLocaleImport } from './routes/secured.$locale'
import { Route as SecuredLocaleIndexImport } from './routes/secured.$locale.index'
import { Route as SecuredLocaleWorkerImport } from './routes/secured.$locale.worker'
import { Route as SecuredLocaleAssetsImport } from './routes/secured.$locale.assets'
import { Route as PublicLocaleAuthImport } from './routes/public.$locale.auth'
import { Route as SecuredLocalePublicationsIndexImport } from './routes/secured.$locale.publications.index'
import { Route as SecuredLocaleWorkerTasksImport } from './routes/secured.$locale.worker.tasks'
import { Route as SecuredLocaleWorkerProfileImport } from './routes/secured.$locale.worker.profile'
import { Route as SecuredLocaleWorkerBatchesImport } from './routes/secured.$locale.worker.batches'
import { Route as SecuredLocaleWorkerTasksIndexImport } from './routes/secured.$locale.worker.tasks.index'
import { Route as SecuredLocaleWorkerTablesIndexImport } from './routes/secured.$locale.worker.tables.index'
import { Route as SecuredLocaleWorkerQueuesIndexImport } from './routes/secured.$locale.worker.queues.index'
import { Route as SecuredLocaleWorkerMonitoringIndexImport } from './routes/secured.$locale.worker.monitoring.index'
import { Route as SecuredLocaleWorkerHelpIndexImport } from './routes/secured.$locale.worker.help.index'
import { Route as SecuredLocaleWorkerFeedbackIndexImport } from './routes/secured.$locale.worker.feedback.index'
import { Route as SecuredLocaleWorkerDashboardIndexImport } from './routes/secured.$locale.worker.dashboard.index'
import { Route as SecuredLocaleWorkerBatchesIndexImport } from './routes/secured.$locale.worker.batches.index'
import { Route as SecuredLocaleAssetsWrenchIndexImport } from './routes/secured.$locale.assets.wrench.index'
import { Route as SecuredLocaleAssetsStencilIndexImport } from './routes/secured.$locale.assets.stencil.index'
import { Route as SecuredLocaleAssetsServicesIndexImport } from './routes/secured.$locale.assets.services.index'
import { Route as SecuredLocaleAssetsMigrateIndexImport } from './routes/secured.$locale.assets.migrate.index'
import { Route as SecuredLocaleAssetsFormsIndexImport } from './routes/secured.$locale.assets.forms.index'
import { Route as SecuredLocaleAssetsFormsFormIdImport } from './routes/secured.$locale.assets.forms.$formId'
import { Route as SecuredLocaleWorkerTasksCreateIndexImport } from './routes/secured.$locale.worker.tasks.create.index'
import { Route as SecuredLocaleWorkerTasksTaskIdIndexImport } from './routes/secured.$locale.worker.tasks.$taskId.index'
import { Route as SecuredLocaleWorkerQueuesMessagesIndexImport } from './routes/secured.$locale.worker.queues.messages.index'
import { Route as SecuredLocaleWorkerQueuesDeliveriesIndexImport } from './routes/secured.$locale.worker.queues.deliveries.index'
import { Route as SecuredLocaleWorkerFeedbackFeedbackIdIndexImport } from './routes/secured.$locale.worker.feedback.$feedbackId.index'
import { Route as SecuredLocaleWorkerBatchesCreateIndexImport } from './routes/secured.$locale.worker.batches.create.index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SecuredLocaleRoute = SecuredLocaleImport.update({
  id: '/secured/$locale',
  path: '/secured/$locale',
  getParentRoute: () => rootRoute,
} as any)

const SecuredLocaleIndexRoute = SecuredLocaleIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SecuredLocaleRoute,
} as any)

const SecuredLocaleWorkerRoute = SecuredLocaleWorkerImport.update({
  id: '/worker',
  path: '/worker',
  getParentRoute: () => SecuredLocaleRoute,
} as any)

const SecuredLocaleAssetsRoute = SecuredLocaleAssetsImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => SecuredLocaleRoute,
} as any)

const PublicLocaleAuthRoute = PublicLocaleAuthImport.update({
  id: '/public/$locale/auth',
  path: '/public/$locale/auth',
  getParentRoute: () => rootRoute,
} as any)

const SecuredLocalePublicationsIndexRoute =
  SecuredLocalePublicationsIndexImport.update({
    id: '/publications/',
    path: '/publications/',
    getParentRoute: () => SecuredLocaleRoute,
  } as any)

const SecuredLocaleWorkerTasksRoute = SecuredLocaleWorkerTasksImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => SecuredLocaleWorkerRoute,
} as any)

const SecuredLocaleWorkerProfileRoute = SecuredLocaleWorkerProfileImport.update(
  {
    id: '/profile',
    path: '/profile',
    getParentRoute: () => SecuredLocaleWorkerRoute,
  } as any,
)

const SecuredLocaleWorkerBatchesRoute = SecuredLocaleWorkerBatchesImport.update(
  {
    id: '/batches',
    path: '/batches',
    getParentRoute: () => SecuredLocaleWorkerRoute,
  } as any,
)

const SecuredLocaleWorkerTasksIndexRoute =
  SecuredLocaleWorkerTasksIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SecuredLocaleWorkerTasksRoute,
  } as any)

const SecuredLocaleWorkerTablesIndexRoute =
  SecuredLocaleWorkerTablesIndexImport.update({
    id: '/tables/',
    path: '/tables/',
    getParentRoute: () => SecuredLocaleWorkerRoute,
  } as any)

const SecuredLocaleWorkerQueuesIndexRoute =
  SecuredLocaleWorkerQueuesIndexImport.update({
    id: '/queues/',
    path: '/queues/',
    getParentRoute: () => SecuredLocaleWorkerRoute,
  } as any)

const SecuredLocaleWorkerMonitoringIndexRoute =
  SecuredLocaleWorkerMonitoringIndexImport.update({
    id: '/monitoring/',
    path: '/monitoring/',
    getParentRoute: () => SecuredLocaleWorkerRoute,
  } as any)

const SecuredLocaleWorkerHelpIndexRoute =
  SecuredLocaleWorkerHelpIndexImport.update({
    id: '/help/',
    path: '/help/',
    getParentRoute: () => SecuredLocaleWorkerRoute,
  } as any)

const SecuredLocaleWorkerFeedbackIndexRoute =
  SecuredLocaleWorkerFeedbackIndexImport.update({
    id: '/feedback/',
    path: '/feedback/',
    getParentRoute: () => SecuredLocaleWorkerRoute,
  } as any)

const SecuredLocaleWorkerDashboardIndexRoute =
  SecuredLocaleWorkerDashboardIndexImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => SecuredLocaleWorkerRoute,
  } as any)

const SecuredLocaleWorkerBatchesIndexRoute =
  SecuredLocaleWorkerBatchesIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SecuredLocaleWorkerBatchesRoute,
  } as any)

const SecuredLocaleAssetsWrenchIndexRoute =
  SecuredLocaleAssetsWrenchIndexImport.update({
    id: '/wrench/',
    path: '/wrench/',
    getParentRoute: () => SecuredLocaleAssetsRoute,
  } as any)

const SecuredLocaleAssetsStencilIndexRoute =
  SecuredLocaleAssetsStencilIndexImport.update({
    id: '/stencil/',
    path: '/stencil/',
    getParentRoute: () => SecuredLocaleAssetsRoute,
  } as any)

const SecuredLocaleAssetsServicesIndexRoute =
  SecuredLocaleAssetsServicesIndexImport.update({
    id: '/services/',
    path: '/services/',
    getParentRoute: () => SecuredLocaleAssetsRoute,
  } as any)

const SecuredLocaleAssetsMigrateIndexRoute =
  SecuredLocaleAssetsMigrateIndexImport.update({
    id: '/migrate/',
    path: '/migrate/',
    getParentRoute: () => SecuredLocaleAssetsRoute,
  } as any)

const SecuredLocaleAssetsFormsIndexRoute =
  SecuredLocaleAssetsFormsIndexImport.update({
    id: '/forms/',
    path: '/forms/',
    getParentRoute: () => SecuredLocaleAssetsRoute,
  } as any)

const SecuredLocaleAssetsFormsFormIdRoute =
  SecuredLocaleAssetsFormsFormIdImport.update({
    id: '/forms/$formId',
    path: '/forms/$formId',
    getParentRoute: () => SecuredLocaleAssetsRoute,
  } as any)

const SecuredLocaleWorkerTasksCreateIndexRoute =
  SecuredLocaleWorkerTasksCreateIndexImport.update({
    id: '/create/',
    path: '/create/',
    getParentRoute: () => SecuredLocaleWorkerTasksRoute,
  } as any)

const SecuredLocaleWorkerTasksTaskIdIndexRoute =
  SecuredLocaleWorkerTasksTaskIdIndexImport.update({
    id: '/$taskId/',
    path: '/$taskId/',
    getParentRoute: () => SecuredLocaleWorkerTasksRoute,
  } as any)

const SecuredLocaleWorkerQueuesMessagesIndexRoute =
  SecuredLocaleWorkerQueuesMessagesIndexImport.update({
    id: '/queues/messages/',
    path: '/queues/messages/',
    getParentRoute: () => SecuredLocaleWorkerRoute,
  } as any)

const SecuredLocaleWorkerQueuesDeliveriesIndexRoute =
  SecuredLocaleWorkerQueuesDeliveriesIndexImport.update({
    id: '/queues/deliveries/',
    path: '/queues/deliveries/',
    getParentRoute: () => SecuredLocaleWorkerRoute,
  } as any)

const SecuredLocaleWorkerFeedbackFeedbackIdIndexRoute =
  SecuredLocaleWorkerFeedbackFeedbackIdIndexImport.update({
    id: '/feedback/$feedbackId/',
    path: '/feedback/$feedbackId/',
    getParentRoute: () => SecuredLocaleWorkerRoute,
  } as any)

const SecuredLocaleWorkerBatchesCreateIndexRoute =
  SecuredLocaleWorkerBatchesCreateIndexImport.update({
    id: '/create/',
    path: '/create/',
    getParentRoute: () => SecuredLocaleWorkerBatchesRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/secured/$locale': {
      id: '/secured/$locale'
      path: '/secured/$locale'
      fullPath: '/secured/$locale'
      preLoaderRoute: typeof SecuredLocaleImport
      parentRoute: typeof rootRoute
    }
    '/public/$locale/auth': {
      id: '/public/$locale/auth'
      path: '/public/$locale/auth'
      fullPath: '/public/$locale/auth'
      preLoaderRoute: typeof PublicLocaleAuthImport
      parentRoute: typeof rootRoute
    }
    '/secured/$locale/assets': {
      id: '/secured/$locale/assets'
      path: '/assets'
      fullPath: '/secured/$locale/assets'
      preLoaderRoute: typeof SecuredLocaleAssetsImport
      parentRoute: typeof SecuredLocaleImport
    }
    '/secured/$locale/worker': {
      id: '/secured/$locale/worker'
      path: '/worker'
      fullPath: '/secured/$locale/worker'
      preLoaderRoute: typeof SecuredLocaleWorkerImport
      parentRoute: typeof SecuredLocaleImport
    }
    '/secured/$locale/': {
      id: '/secured/$locale/'
      path: '/'
      fullPath: '/secured/$locale/'
      preLoaderRoute: typeof SecuredLocaleIndexImport
      parentRoute: typeof SecuredLocaleImport
    }
    '/secured/$locale/worker/batches': {
      id: '/secured/$locale/worker/batches'
      path: '/batches'
      fullPath: '/secured/$locale/worker/batches'
      preLoaderRoute: typeof SecuredLocaleWorkerBatchesImport
      parentRoute: typeof SecuredLocaleWorkerImport
    }
    '/secured/$locale/worker/profile': {
      id: '/secured/$locale/worker/profile'
      path: '/profile'
      fullPath: '/secured/$locale/worker/profile'
      preLoaderRoute: typeof SecuredLocaleWorkerProfileImport
      parentRoute: typeof SecuredLocaleWorkerImport
    }
    '/secured/$locale/worker/tasks': {
      id: '/secured/$locale/worker/tasks'
      path: '/tasks'
      fullPath: '/secured/$locale/worker/tasks'
      preLoaderRoute: typeof SecuredLocaleWorkerTasksImport
      parentRoute: typeof SecuredLocaleWorkerImport
    }
    '/secured/$locale/publications/': {
      id: '/secured/$locale/publications/'
      path: '/publications'
      fullPath: '/secured/$locale/publications'
      preLoaderRoute: typeof SecuredLocalePublicationsIndexImport
      parentRoute: typeof SecuredLocaleImport
    }
    '/secured/$locale/assets/forms/$formId': {
      id: '/secured/$locale/assets/forms/$formId'
      path: '/forms/$formId'
      fullPath: '/secured/$locale/assets/forms/$formId'
      preLoaderRoute: typeof SecuredLocaleAssetsFormsFormIdImport
      parentRoute: typeof SecuredLocaleAssetsImport
    }
    '/secured/$locale/assets/forms/': {
      id: '/secured/$locale/assets/forms/'
      path: '/forms'
      fullPath: '/secured/$locale/assets/forms'
      preLoaderRoute: typeof SecuredLocaleAssetsFormsIndexImport
      parentRoute: typeof SecuredLocaleAssetsImport
    }
    '/secured/$locale/assets/migrate/': {
      id: '/secured/$locale/assets/migrate/'
      path: '/migrate'
      fullPath: '/secured/$locale/assets/migrate'
      preLoaderRoute: typeof SecuredLocaleAssetsMigrateIndexImport
      parentRoute: typeof SecuredLocaleAssetsImport
    }
    '/secured/$locale/assets/services/': {
      id: '/secured/$locale/assets/services/'
      path: '/services'
      fullPath: '/secured/$locale/assets/services'
      preLoaderRoute: typeof SecuredLocaleAssetsServicesIndexImport
      parentRoute: typeof SecuredLocaleAssetsImport
    }
    '/secured/$locale/assets/stencil/': {
      id: '/secured/$locale/assets/stencil/'
      path: '/stencil'
      fullPath: '/secured/$locale/assets/stencil'
      preLoaderRoute: typeof SecuredLocaleAssetsStencilIndexImport
      parentRoute: typeof SecuredLocaleAssetsImport
    }
    '/secured/$locale/assets/wrench/': {
      id: '/secured/$locale/assets/wrench/'
      path: '/wrench'
      fullPath: '/secured/$locale/assets/wrench'
      preLoaderRoute: typeof SecuredLocaleAssetsWrenchIndexImport
      parentRoute: typeof SecuredLocaleAssetsImport
    }
    '/secured/$locale/worker/batches/': {
      id: '/secured/$locale/worker/batches/'
      path: '/'
      fullPath: '/secured/$locale/worker/batches/'
      preLoaderRoute: typeof SecuredLocaleWorkerBatchesIndexImport
      parentRoute: typeof SecuredLocaleWorkerBatchesImport
    }
    '/secured/$locale/worker/dashboard/': {
      id: '/secured/$locale/worker/dashboard/'
      path: '/dashboard'
      fullPath: '/secured/$locale/worker/dashboard'
      preLoaderRoute: typeof SecuredLocaleWorkerDashboardIndexImport
      parentRoute: typeof SecuredLocaleWorkerImport
    }
    '/secured/$locale/worker/feedback/': {
      id: '/secured/$locale/worker/feedback/'
      path: '/feedback'
      fullPath: '/secured/$locale/worker/feedback'
      preLoaderRoute: typeof SecuredLocaleWorkerFeedbackIndexImport
      parentRoute: typeof SecuredLocaleWorkerImport
    }
    '/secured/$locale/worker/help/': {
      id: '/secured/$locale/worker/help/'
      path: '/help'
      fullPath: '/secured/$locale/worker/help'
      preLoaderRoute: typeof SecuredLocaleWorkerHelpIndexImport
      parentRoute: typeof SecuredLocaleWorkerImport
    }
    '/secured/$locale/worker/monitoring/': {
      id: '/secured/$locale/worker/monitoring/'
      path: '/monitoring'
      fullPath: '/secured/$locale/worker/monitoring'
      preLoaderRoute: typeof SecuredLocaleWorkerMonitoringIndexImport
      parentRoute: typeof SecuredLocaleWorkerImport
    }
    '/secured/$locale/worker/queues/': {
      id: '/secured/$locale/worker/queues/'
      path: '/queues'
      fullPath: '/secured/$locale/worker/queues'
      preLoaderRoute: typeof SecuredLocaleWorkerQueuesIndexImport
      parentRoute: typeof SecuredLocaleWorkerImport
    }
    '/secured/$locale/worker/tables/': {
      id: '/secured/$locale/worker/tables/'
      path: '/tables'
      fullPath: '/secured/$locale/worker/tables'
      preLoaderRoute: typeof SecuredLocaleWorkerTablesIndexImport
      parentRoute: typeof SecuredLocaleWorkerImport
    }
    '/secured/$locale/worker/tasks/': {
      id: '/secured/$locale/worker/tasks/'
      path: '/'
      fullPath: '/secured/$locale/worker/tasks/'
      preLoaderRoute: typeof SecuredLocaleWorkerTasksIndexImport
      parentRoute: typeof SecuredLocaleWorkerTasksImport
    }
    '/secured/$locale/worker/batches/create/': {
      id: '/secured/$locale/worker/batches/create/'
      path: '/create'
      fullPath: '/secured/$locale/worker/batches/create'
      preLoaderRoute: typeof SecuredLocaleWorkerBatchesCreateIndexImport
      parentRoute: typeof SecuredLocaleWorkerBatchesImport
    }
    '/secured/$locale/worker/feedback/$feedbackId/': {
      id: '/secured/$locale/worker/feedback/$feedbackId/'
      path: '/feedback/$feedbackId'
      fullPath: '/secured/$locale/worker/feedback/$feedbackId'
      preLoaderRoute: typeof SecuredLocaleWorkerFeedbackFeedbackIdIndexImport
      parentRoute: typeof SecuredLocaleWorkerImport
    }
    '/secured/$locale/worker/queues/deliveries/': {
      id: '/secured/$locale/worker/queues/deliveries/'
      path: '/queues/deliveries'
      fullPath: '/secured/$locale/worker/queues/deliveries'
      preLoaderRoute: typeof SecuredLocaleWorkerQueuesDeliveriesIndexImport
      parentRoute: typeof SecuredLocaleWorkerImport
    }
    '/secured/$locale/worker/queues/messages/': {
      id: '/secured/$locale/worker/queues/messages/'
      path: '/queues/messages'
      fullPath: '/secured/$locale/worker/queues/messages'
      preLoaderRoute: typeof SecuredLocaleWorkerQueuesMessagesIndexImport
      parentRoute: typeof SecuredLocaleWorkerImport
    }
    '/secured/$locale/worker/tasks/$taskId/': {
      id: '/secured/$locale/worker/tasks/$taskId/'
      path: '/$taskId'
      fullPath: '/secured/$locale/worker/tasks/$taskId'
      preLoaderRoute: typeof SecuredLocaleWorkerTasksTaskIdIndexImport
      parentRoute: typeof SecuredLocaleWorkerTasksImport
    }
    '/secured/$locale/worker/tasks/create/': {
      id: '/secured/$locale/worker/tasks/create/'
      path: '/create'
      fullPath: '/secured/$locale/worker/tasks/create'
      preLoaderRoute: typeof SecuredLocaleWorkerTasksCreateIndexImport
      parentRoute: typeof SecuredLocaleWorkerTasksImport
    }
  }
}

// Create and export the route tree

interface SecuredLocaleAssetsRouteChildren {
  SecuredLocaleAssetsFormsFormIdRoute: typeof SecuredLocaleAssetsFormsFormIdRoute
  SecuredLocaleAssetsFormsIndexRoute: typeof SecuredLocaleAssetsFormsIndexRoute
  SecuredLocaleAssetsMigrateIndexRoute: typeof SecuredLocaleAssetsMigrateIndexRoute
  SecuredLocaleAssetsServicesIndexRoute: typeof SecuredLocaleAssetsServicesIndexRoute
  SecuredLocaleAssetsStencilIndexRoute: typeof SecuredLocaleAssetsStencilIndexRoute
  SecuredLocaleAssetsWrenchIndexRoute: typeof SecuredLocaleAssetsWrenchIndexRoute
}

const SecuredLocaleAssetsRouteChildren: SecuredLocaleAssetsRouteChildren = {
  SecuredLocaleAssetsFormsFormIdRoute: SecuredLocaleAssetsFormsFormIdRoute,
  SecuredLocaleAssetsFormsIndexRoute: SecuredLocaleAssetsFormsIndexRoute,
  SecuredLocaleAssetsMigrateIndexRoute: SecuredLocaleAssetsMigrateIndexRoute,
  SecuredLocaleAssetsServicesIndexRoute: SecuredLocaleAssetsServicesIndexRoute,
  SecuredLocaleAssetsStencilIndexRoute: SecuredLocaleAssetsStencilIndexRoute,
  SecuredLocaleAssetsWrenchIndexRoute: SecuredLocaleAssetsWrenchIndexRoute,
}

const SecuredLocaleAssetsRouteWithChildren =
  SecuredLocaleAssetsRoute._addFileChildren(SecuredLocaleAssetsRouteChildren)

interface SecuredLocaleWorkerBatchesRouteChildren {
  SecuredLocaleWorkerBatchesIndexRoute: typeof SecuredLocaleWorkerBatchesIndexRoute
  SecuredLocaleWorkerBatchesCreateIndexRoute: typeof SecuredLocaleWorkerBatchesCreateIndexRoute
}

const SecuredLocaleWorkerBatchesRouteChildren: SecuredLocaleWorkerBatchesRouteChildren =
  {
    SecuredLocaleWorkerBatchesIndexRoute: SecuredLocaleWorkerBatchesIndexRoute,
    SecuredLocaleWorkerBatchesCreateIndexRoute:
      SecuredLocaleWorkerBatchesCreateIndexRoute,
  }

const SecuredLocaleWorkerBatchesRouteWithChildren =
  SecuredLocaleWorkerBatchesRoute._addFileChildren(
    SecuredLocaleWorkerBatchesRouteChildren,
  )

interface SecuredLocaleWorkerTasksRouteChildren {
  SecuredLocaleWorkerTasksIndexRoute: typeof SecuredLocaleWorkerTasksIndexRoute
  SecuredLocaleWorkerTasksTaskIdIndexRoute: typeof SecuredLocaleWorkerTasksTaskIdIndexRoute
  SecuredLocaleWorkerTasksCreateIndexRoute: typeof SecuredLocaleWorkerTasksCreateIndexRoute
}

const SecuredLocaleWorkerTasksRouteChildren: SecuredLocaleWorkerTasksRouteChildren =
  {
    SecuredLocaleWorkerTasksIndexRoute: SecuredLocaleWorkerTasksIndexRoute,
    SecuredLocaleWorkerTasksTaskIdIndexRoute:
      SecuredLocaleWorkerTasksTaskIdIndexRoute,
    SecuredLocaleWorkerTasksCreateIndexRoute:
      SecuredLocaleWorkerTasksCreateIndexRoute,
  }

const SecuredLocaleWorkerTasksRouteWithChildren =
  SecuredLocaleWorkerTasksRoute._addFileChildren(
    SecuredLocaleWorkerTasksRouteChildren,
  )

interface SecuredLocaleWorkerRouteChildren {
  SecuredLocaleWorkerBatchesRoute: typeof SecuredLocaleWorkerBatchesRouteWithChildren
  SecuredLocaleWorkerProfileRoute: typeof SecuredLocaleWorkerProfileRoute
  SecuredLocaleWorkerTasksRoute: typeof SecuredLocaleWorkerTasksRouteWithChildren
  SecuredLocaleWorkerDashboardIndexRoute: typeof SecuredLocaleWorkerDashboardIndexRoute
  SecuredLocaleWorkerFeedbackIndexRoute: typeof SecuredLocaleWorkerFeedbackIndexRoute
  SecuredLocaleWorkerHelpIndexRoute: typeof SecuredLocaleWorkerHelpIndexRoute
  SecuredLocaleWorkerMonitoringIndexRoute: typeof SecuredLocaleWorkerMonitoringIndexRoute
  SecuredLocaleWorkerQueuesIndexRoute: typeof SecuredLocaleWorkerQueuesIndexRoute
  SecuredLocaleWorkerTablesIndexRoute: typeof SecuredLocaleWorkerTablesIndexRoute
  SecuredLocaleWorkerFeedbackFeedbackIdIndexRoute: typeof SecuredLocaleWorkerFeedbackFeedbackIdIndexRoute
  SecuredLocaleWorkerQueuesDeliveriesIndexRoute: typeof SecuredLocaleWorkerQueuesDeliveriesIndexRoute
  SecuredLocaleWorkerQueuesMessagesIndexRoute: typeof SecuredLocaleWorkerQueuesMessagesIndexRoute
}

const SecuredLocaleWorkerRouteChildren: SecuredLocaleWorkerRouteChildren = {
  SecuredLocaleWorkerBatchesRoute: SecuredLocaleWorkerBatchesRouteWithChildren,
  SecuredLocaleWorkerProfileRoute: SecuredLocaleWorkerProfileRoute,
  SecuredLocaleWorkerTasksRoute: SecuredLocaleWorkerTasksRouteWithChildren,
  SecuredLocaleWorkerDashboardIndexRoute:
    SecuredLocaleWorkerDashboardIndexRoute,
  SecuredLocaleWorkerFeedbackIndexRoute: SecuredLocaleWorkerFeedbackIndexRoute,
  SecuredLocaleWorkerHelpIndexRoute: SecuredLocaleWorkerHelpIndexRoute,
  SecuredLocaleWorkerMonitoringIndexRoute:
    SecuredLocaleWorkerMonitoringIndexRoute,
  SecuredLocaleWorkerQueuesIndexRoute: SecuredLocaleWorkerQueuesIndexRoute,
  SecuredLocaleWorkerTablesIndexRoute: SecuredLocaleWorkerTablesIndexRoute,
  SecuredLocaleWorkerFeedbackFeedbackIdIndexRoute:
    SecuredLocaleWorkerFeedbackFeedbackIdIndexRoute,
  SecuredLocaleWorkerQueuesDeliveriesIndexRoute:
    SecuredLocaleWorkerQueuesDeliveriesIndexRoute,
  SecuredLocaleWorkerQueuesMessagesIndexRoute:
    SecuredLocaleWorkerQueuesMessagesIndexRoute,
}

const SecuredLocaleWorkerRouteWithChildren =
  SecuredLocaleWorkerRoute._addFileChildren(SecuredLocaleWorkerRouteChildren)

interface SecuredLocaleRouteChildren {
  SecuredLocaleAssetsRoute: typeof SecuredLocaleAssetsRouteWithChildren
  SecuredLocaleWorkerRoute: typeof SecuredLocaleWorkerRouteWithChildren
  SecuredLocaleIndexRoute: typeof SecuredLocaleIndexRoute
  SecuredLocalePublicationsIndexRoute: typeof SecuredLocalePublicationsIndexRoute
}

const SecuredLocaleRouteChildren: SecuredLocaleRouteChildren = {
  SecuredLocaleAssetsRoute: SecuredLocaleAssetsRouteWithChildren,
  SecuredLocaleWorkerRoute: SecuredLocaleWorkerRouteWithChildren,
  SecuredLocaleIndexRoute: SecuredLocaleIndexRoute,
  SecuredLocalePublicationsIndexRoute: SecuredLocalePublicationsIndexRoute,
}

const SecuredLocaleRouteWithChildren = SecuredLocaleRoute._addFileChildren(
  SecuredLocaleRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/secured/$locale': typeof SecuredLocaleRouteWithChildren
  '/public/$locale/auth': typeof PublicLocaleAuthRoute
  '/secured/$locale/assets': typeof SecuredLocaleAssetsRouteWithChildren
  '/secured/$locale/worker': typeof SecuredLocaleWorkerRouteWithChildren
  '/secured/$locale/': typeof SecuredLocaleIndexRoute
  '/secured/$locale/worker/batches': typeof SecuredLocaleWorkerBatchesRouteWithChildren
  '/secured/$locale/worker/profile': typeof SecuredLocaleWorkerProfileRoute
  '/secured/$locale/worker/tasks': typeof SecuredLocaleWorkerTasksRouteWithChildren
  '/secured/$locale/publications': typeof SecuredLocalePublicationsIndexRoute
  '/secured/$locale/assets/forms/$formId': typeof SecuredLocaleAssetsFormsFormIdRoute
  '/secured/$locale/assets/forms': typeof SecuredLocaleAssetsFormsIndexRoute
  '/secured/$locale/assets/migrate': typeof SecuredLocaleAssetsMigrateIndexRoute
  '/secured/$locale/assets/services': typeof SecuredLocaleAssetsServicesIndexRoute
  '/secured/$locale/assets/stencil': typeof SecuredLocaleAssetsStencilIndexRoute
  '/secured/$locale/assets/wrench': typeof SecuredLocaleAssetsWrenchIndexRoute
  '/secured/$locale/worker/batches/': typeof SecuredLocaleWorkerBatchesIndexRoute
  '/secured/$locale/worker/dashboard': typeof SecuredLocaleWorkerDashboardIndexRoute
  '/secured/$locale/worker/feedback': typeof SecuredLocaleWorkerFeedbackIndexRoute
  '/secured/$locale/worker/help': typeof SecuredLocaleWorkerHelpIndexRoute
  '/secured/$locale/worker/monitoring': typeof SecuredLocaleWorkerMonitoringIndexRoute
  '/secured/$locale/worker/queues': typeof SecuredLocaleWorkerQueuesIndexRoute
  '/secured/$locale/worker/tables': typeof SecuredLocaleWorkerTablesIndexRoute
  '/secured/$locale/worker/tasks/': typeof SecuredLocaleWorkerTasksIndexRoute
  '/secured/$locale/worker/batches/create': typeof SecuredLocaleWorkerBatchesCreateIndexRoute
  '/secured/$locale/worker/feedback/$feedbackId': typeof SecuredLocaleWorkerFeedbackFeedbackIdIndexRoute
  '/secured/$locale/worker/queues/deliveries': typeof SecuredLocaleWorkerQueuesDeliveriesIndexRoute
  '/secured/$locale/worker/queues/messages': typeof SecuredLocaleWorkerQueuesMessagesIndexRoute
  '/secured/$locale/worker/tasks/$taskId': typeof SecuredLocaleWorkerTasksTaskIdIndexRoute
  '/secured/$locale/worker/tasks/create': typeof SecuredLocaleWorkerTasksCreateIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/public/$locale/auth': typeof PublicLocaleAuthRoute
  '/secured/$locale/assets': typeof SecuredLocaleAssetsRouteWithChildren
  '/secured/$locale/worker': typeof SecuredLocaleWorkerRouteWithChildren
  '/secured/$locale': typeof SecuredLocaleIndexRoute
  '/secured/$locale/worker/profile': typeof SecuredLocaleWorkerProfileRoute
  '/secured/$locale/publications': typeof SecuredLocalePublicationsIndexRoute
  '/secured/$locale/assets/forms/$formId': typeof SecuredLocaleAssetsFormsFormIdRoute
  '/secured/$locale/assets/forms': typeof SecuredLocaleAssetsFormsIndexRoute
  '/secured/$locale/assets/migrate': typeof SecuredLocaleAssetsMigrateIndexRoute
  '/secured/$locale/assets/services': typeof SecuredLocaleAssetsServicesIndexRoute
  '/secured/$locale/assets/stencil': typeof SecuredLocaleAssetsStencilIndexRoute
  '/secured/$locale/assets/wrench': typeof SecuredLocaleAssetsWrenchIndexRoute
  '/secured/$locale/worker/batches': typeof SecuredLocaleWorkerBatchesIndexRoute
  '/secured/$locale/worker/dashboard': typeof SecuredLocaleWorkerDashboardIndexRoute
  '/secured/$locale/worker/feedback': typeof SecuredLocaleWorkerFeedbackIndexRoute
  '/secured/$locale/worker/help': typeof SecuredLocaleWorkerHelpIndexRoute
  '/secured/$locale/worker/monitoring': typeof SecuredLocaleWorkerMonitoringIndexRoute
  '/secured/$locale/worker/queues': typeof SecuredLocaleWorkerQueuesIndexRoute
  '/secured/$locale/worker/tables': typeof SecuredLocaleWorkerTablesIndexRoute
  '/secured/$locale/worker/tasks': typeof SecuredLocaleWorkerTasksIndexRoute
  '/secured/$locale/worker/batches/create': typeof SecuredLocaleWorkerBatchesCreateIndexRoute
  '/secured/$locale/worker/feedback/$feedbackId': typeof SecuredLocaleWorkerFeedbackFeedbackIdIndexRoute
  '/secured/$locale/worker/queues/deliveries': typeof SecuredLocaleWorkerQueuesDeliveriesIndexRoute
  '/secured/$locale/worker/queues/messages': typeof SecuredLocaleWorkerQueuesMessagesIndexRoute
  '/secured/$locale/worker/tasks/$taskId': typeof SecuredLocaleWorkerTasksTaskIdIndexRoute
  '/secured/$locale/worker/tasks/create': typeof SecuredLocaleWorkerTasksCreateIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/secured/$locale': typeof SecuredLocaleRouteWithChildren
  '/public/$locale/auth': typeof PublicLocaleAuthRoute
  '/secured/$locale/assets': typeof SecuredLocaleAssetsRouteWithChildren
  '/secured/$locale/worker': typeof SecuredLocaleWorkerRouteWithChildren
  '/secured/$locale/': typeof SecuredLocaleIndexRoute
  '/secured/$locale/worker/batches': typeof SecuredLocaleWorkerBatchesRouteWithChildren
  '/secured/$locale/worker/profile': typeof SecuredLocaleWorkerProfileRoute
  '/secured/$locale/worker/tasks': typeof SecuredLocaleWorkerTasksRouteWithChildren
  '/secured/$locale/publications/': typeof SecuredLocalePublicationsIndexRoute
  '/secured/$locale/assets/forms/$formId': typeof SecuredLocaleAssetsFormsFormIdRoute
  '/secured/$locale/assets/forms/': typeof SecuredLocaleAssetsFormsIndexRoute
  '/secured/$locale/assets/migrate/': typeof SecuredLocaleAssetsMigrateIndexRoute
  '/secured/$locale/assets/services/': typeof SecuredLocaleAssetsServicesIndexRoute
  '/secured/$locale/assets/stencil/': typeof SecuredLocaleAssetsStencilIndexRoute
  '/secured/$locale/assets/wrench/': typeof SecuredLocaleAssetsWrenchIndexRoute
  '/secured/$locale/worker/batches/': typeof SecuredLocaleWorkerBatchesIndexRoute
  '/secured/$locale/worker/dashboard/': typeof SecuredLocaleWorkerDashboardIndexRoute
  '/secured/$locale/worker/feedback/': typeof SecuredLocaleWorkerFeedbackIndexRoute
  '/secured/$locale/worker/help/': typeof SecuredLocaleWorkerHelpIndexRoute
  '/secured/$locale/worker/monitoring/': typeof SecuredLocaleWorkerMonitoringIndexRoute
  '/secured/$locale/worker/queues/': typeof SecuredLocaleWorkerQueuesIndexRoute
  '/secured/$locale/worker/tables/': typeof SecuredLocaleWorkerTablesIndexRoute
  '/secured/$locale/worker/tasks/': typeof SecuredLocaleWorkerTasksIndexRoute
  '/secured/$locale/worker/batches/create/': typeof SecuredLocaleWorkerBatchesCreateIndexRoute
  '/secured/$locale/worker/feedback/$feedbackId/': typeof SecuredLocaleWorkerFeedbackFeedbackIdIndexRoute
  '/secured/$locale/worker/queues/deliveries/': typeof SecuredLocaleWorkerQueuesDeliveriesIndexRoute
  '/secured/$locale/worker/queues/messages/': typeof SecuredLocaleWorkerQueuesMessagesIndexRoute
  '/secured/$locale/worker/tasks/$taskId/': typeof SecuredLocaleWorkerTasksTaskIdIndexRoute
  '/secured/$locale/worker/tasks/create/': typeof SecuredLocaleWorkerTasksCreateIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/secured/$locale'
    | '/public/$locale/auth'
    | '/secured/$locale/assets'
    | '/secured/$locale/worker'
    | '/secured/$locale/'
    | '/secured/$locale/worker/batches'
    | '/secured/$locale/worker/profile'
    | '/secured/$locale/worker/tasks'
    | '/secured/$locale/publications'
    | '/secured/$locale/assets/forms/$formId'
    | '/secured/$locale/assets/forms'
    | '/secured/$locale/assets/migrate'
    | '/secured/$locale/assets/services'
    | '/secured/$locale/assets/stencil'
    | '/secured/$locale/assets/wrench'
    | '/secured/$locale/worker/batches/'
    | '/secured/$locale/worker/dashboard'
    | '/secured/$locale/worker/feedback'
    | '/secured/$locale/worker/help'
    | '/secured/$locale/worker/monitoring'
    | '/secured/$locale/worker/queues'
    | '/secured/$locale/worker/tables'
    | '/secured/$locale/worker/tasks/'
    | '/secured/$locale/worker/batches/create'
    | '/secured/$locale/worker/feedback/$feedbackId'
    | '/secured/$locale/worker/queues/deliveries'
    | '/secured/$locale/worker/queues/messages'
    | '/secured/$locale/worker/tasks/$taskId'
    | '/secured/$locale/worker/tasks/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/public/$locale/auth'
    | '/secured/$locale/assets'
    | '/secured/$locale/worker'
    | '/secured/$locale'
    | '/secured/$locale/worker/profile'
    | '/secured/$locale/publications'
    | '/secured/$locale/assets/forms/$formId'
    | '/secured/$locale/assets/forms'
    | '/secured/$locale/assets/migrate'
    | '/secured/$locale/assets/services'
    | '/secured/$locale/assets/stencil'
    | '/secured/$locale/assets/wrench'
    | '/secured/$locale/worker/batches'
    | '/secured/$locale/worker/dashboard'
    | '/secured/$locale/worker/feedback'
    | '/secured/$locale/worker/help'
    | '/secured/$locale/worker/monitoring'
    | '/secured/$locale/worker/queues'
    | '/secured/$locale/worker/tables'
    | '/secured/$locale/worker/tasks'
    | '/secured/$locale/worker/batches/create'
    | '/secured/$locale/worker/feedback/$feedbackId'
    | '/secured/$locale/worker/queues/deliveries'
    | '/secured/$locale/worker/queues/messages'
    | '/secured/$locale/worker/tasks/$taskId'
    | '/secured/$locale/worker/tasks/create'
  id:
    | '__root__'
    | '/'
    | '/secured/$locale'
    | '/public/$locale/auth'
    | '/secured/$locale/assets'
    | '/secured/$locale/worker'
    | '/secured/$locale/'
    | '/secured/$locale/worker/batches'
    | '/secured/$locale/worker/profile'
    | '/secured/$locale/worker/tasks'
    | '/secured/$locale/publications/'
    | '/secured/$locale/assets/forms/$formId'
    | '/secured/$locale/assets/forms/'
    | '/secured/$locale/assets/migrate/'
    | '/secured/$locale/assets/services/'
    | '/secured/$locale/assets/stencil/'
    | '/secured/$locale/assets/wrench/'
    | '/secured/$locale/worker/batches/'
    | '/secured/$locale/worker/dashboard/'
    | '/secured/$locale/worker/feedback/'
    | '/secured/$locale/worker/help/'
    | '/secured/$locale/worker/monitoring/'
    | '/secured/$locale/worker/queues/'
    | '/secured/$locale/worker/tables/'
    | '/secured/$locale/worker/tasks/'
    | '/secured/$locale/worker/batches/create/'
    | '/secured/$locale/worker/feedback/$feedbackId/'
    | '/secured/$locale/worker/queues/deliveries/'
    | '/secured/$locale/worker/queues/messages/'
    | '/secured/$locale/worker/tasks/$taskId/'
    | '/secured/$locale/worker/tasks/create/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SecuredLocaleRoute: typeof SecuredLocaleRouteWithChildren
  PublicLocaleAuthRoute: typeof PublicLocaleAuthRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SecuredLocaleRoute: SecuredLocaleRouteWithChildren,
  PublicLocaleAuthRoute: PublicLocaleAuthRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/secured/$locale",
        "/public/$locale/auth"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/secured/$locale": {
      "filePath": "secured.$locale.tsx",
      "children": [
        "/secured/$locale/assets",
        "/secured/$locale/worker",
        "/secured/$locale/",
        "/secured/$locale/publications/"
      ]
    },
    "/public/$locale/auth": {
      "filePath": "public.$locale.auth.tsx"
    },
    "/secured/$locale/assets": {
      "filePath": "secured.$locale.assets.tsx",
      "parent": "/secured/$locale",
      "children": [
        "/secured/$locale/assets/forms/$formId",
        "/secured/$locale/assets/forms/",
        "/secured/$locale/assets/migrate/",
        "/secured/$locale/assets/services/",
        "/secured/$locale/assets/stencil/",
        "/secured/$locale/assets/wrench/"
      ]
    },
    "/secured/$locale/worker": {
      "filePath": "secured.$locale.worker.tsx",
      "parent": "/secured/$locale",
      "children": [
        "/secured/$locale/worker/batches",
        "/secured/$locale/worker/profile",
        "/secured/$locale/worker/tasks",
        "/secured/$locale/worker/dashboard/",
        "/secured/$locale/worker/feedback/",
        "/secured/$locale/worker/help/",
        "/secured/$locale/worker/monitoring/",
        "/secured/$locale/worker/queues/",
        "/secured/$locale/worker/tables/",
        "/secured/$locale/worker/feedback/$feedbackId/",
        "/secured/$locale/worker/queues/deliveries/",
        "/secured/$locale/worker/queues/messages/"
      ]
    },
    "/secured/$locale/": {
      "filePath": "secured.$locale.index.tsx",
      "parent": "/secured/$locale"
    },
    "/secured/$locale/worker/batches": {
      "filePath": "secured.$locale.worker.batches.tsx",
      "parent": "/secured/$locale/worker",
      "children": [
        "/secured/$locale/worker/batches/",
        "/secured/$locale/worker/batches/create/"
      ]
    },
    "/secured/$locale/worker/profile": {
      "filePath": "secured.$locale.worker.profile.tsx",
      "parent": "/secured/$locale/worker"
    },
    "/secured/$locale/worker/tasks": {
      "filePath": "secured.$locale.worker.tasks.tsx",
      "parent": "/secured/$locale/worker",
      "children": [
        "/secured/$locale/worker/tasks/",
        "/secured/$locale/worker/tasks/$taskId/",
        "/secured/$locale/worker/tasks/create/"
      ]
    },
    "/secured/$locale/publications/": {
      "filePath": "secured.$locale.publications.index.tsx",
      "parent": "/secured/$locale"
    },
    "/secured/$locale/assets/forms/$formId": {
      "filePath": "secured.$locale.assets.forms.$formId.tsx",
      "parent": "/secured/$locale/assets"
    },
    "/secured/$locale/assets/forms/": {
      "filePath": "secured.$locale.assets.forms.index.tsx",
      "parent": "/secured/$locale/assets"
    },
    "/secured/$locale/assets/migrate/": {
      "filePath": "secured.$locale.assets.migrate.index.tsx",
      "parent": "/secured/$locale/assets"
    },
    "/secured/$locale/assets/services/": {
      "filePath": "secured.$locale.assets.services.index.tsx",
      "parent": "/secured/$locale/assets"
    },
    "/secured/$locale/assets/stencil/": {
      "filePath": "secured.$locale.assets.stencil.index.tsx",
      "parent": "/secured/$locale/assets"
    },
    "/secured/$locale/assets/wrench/": {
      "filePath": "secured.$locale.assets.wrench.index.tsx",
      "parent": "/secured/$locale/assets"
    },
    "/secured/$locale/worker/batches/": {
      "filePath": "secured.$locale.worker.batches.index.tsx",
      "parent": "/secured/$locale/worker/batches"
    },
    "/secured/$locale/worker/dashboard/": {
      "filePath": "secured.$locale.worker.dashboard.index.tsx",
      "parent": "/secured/$locale/worker"
    },
    "/secured/$locale/worker/feedback/": {
      "filePath": "secured.$locale.worker.feedback.index.tsx",
      "parent": "/secured/$locale/worker"
    },
    "/secured/$locale/worker/help/": {
      "filePath": "secured.$locale.worker.help.index.tsx",
      "parent": "/secured/$locale/worker"
    },
    "/secured/$locale/worker/monitoring/": {
      "filePath": "secured.$locale.worker.monitoring.index.tsx",
      "parent": "/secured/$locale/worker"
    },
    "/secured/$locale/worker/queues/": {
      "filePath": "secured.$locale.worker.queues.index.tsx",
      "parent": "/secured/$locale/worker"
    },
    "/secured/$locale/worker/tables/": {
      "filePath": "secured.$locale.worker.tables.index.tsx",
      "parent": "/secured/$locale/worker"
    },
    "/secured/$locale/worker/tasks/": {
      "filePath": "secured.$locale.worker.tasks.index.tsx",
      "parent": "/secured/$locale/worker/tasks"
    },
    "/secured/$locale/worker/batches/create/": {
      "filePath": "secured.$locale.worker.batches.create.index.tsx",
      "parent": "/secured/$locale/worker/batches"
    },
    "/secured/$locale/worker/feedback/$feedbackId/": {
      "filePath": "secured.$locale.worker.feedback.$feedbackId.index.tsx",
      "parent": "/secured/$locale/worker"
    },
    "/secured/$locale/worker/queues/deliveries/": {
      "filePath": "secured.$locale.worker.queues.deliveries.index.tsx",
      "parent": "/secured/$locale/worker"
    },
    "/secured/$locale/worker/queues/messages/": {
      "filePath": "secured.$locale.worker.queues.messages.index.tsx",
      "parent": "/secured/$locale/worker"
    },
    "/secured/$locale/worker/tasks/$taskId/": {
      "filePath": "secured.$locale.worker.tasks.$taskId.index.tsx",
      "parent": "/secured/$locale/worker/tasks"
    },
    "/secured/$locale/worker/tasks/create/": {
      "filePath": "secured.$locale.worker.tasks.create.index.tsx",
      "parent": "/secured/$locale/worker/tasks"
    }
  }
}
ROUTE_MANIFEST_END */
