/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SecuredLocaleRouteImport } from './routes/secured.$locale'
import { Route as SecuredLocaleIndexRouteImport } from './routes/secured.$locale.index'
import { Route as SecuredLocaleWorkerRouteImport } from './routes/secured.$locale.worker'
import { Route as SecuredLocaleAssetsRouteImport } from './routes/secured.$locale.assets'
import { Route as PublicLocaleAuthRouteImport } from './routes/public.$locale.auth'
import { Route as SecuredLocalePublicationsIndexRouteImport } from './routes/secured.$locale.publications.index'
import { Route as SecuredLocaleWorkerTasksRouteImport } from './routes/secured.$locale.worker.tasks'
import { Route as SecuredLocaleWorkerProfileRouteImport } from './routes/secured.$locale.worker.profile'
import { Route as SecuredLocaleWorkerBatchesRouteImport } from './routes/secured.$locale.worker.batches'
import { Route as SecuredLocaleWorkerTasksIndexRouteImport } from './routes/secured.$locale.worker.tasks.index'
import { Route as SecuredLocaleWorkerTablesIndexRouteImport } from './routes/secured.$locale.worker.tables.index'
import { Route as SecuredLocaleWorkerQueuesIndexRouteImport } from './routes/secured.$locale.worker.queues.index'
import { Route as SecuredLocaleWorkerMonitoringIndexRouteImport } from './routes/secured.$locale.worker.monitoring.index'
import { Route as SecuredLocaleWorkerHelpIndexRouteImport } from './routes/secured.$locale.worker.help.index'
import { Route as SecuredLocaleWorkerFeedbackIndexRouteImport } from './routes/secured.$locale.worker.feedback.index'
import { Route as SecuredLocaleWorkerDashboardIndexRouteImport } from './routes/secured.$locale.worker.dashboard.index'
import { Route as SecuredLocaleWorkerBatchesIndexRouteImport } from './routes/secured.$locale.worker.batches.index'
import { Route as SecuredLocaleAssetsWrenchIndexRouteImport } from './routes/secured.$locale.assets.wrench.index'
import { Route as SecuredLocaleAssetsStencilIndexRouteImport } from './routes/secured.$locale.assets.stencil.index'
import { Route as SecuredLocaleAssetsServicesIndexRouteImport } from './routes/secured.$locale.assets.services.index'
import { Route as SecuredLocaleAssetsMigrateIndexRouteImport } from './routes/secured.$locale.assets.migrate.index'
import { Route as SecuredLocaleAssetsFormsIndexRouteImport } from './routes/secured.$locale.assets.forms.index'
import { Route as SecuredLocaleAssetsFormsFormIdRouteImport } from './routes/secured.$locale.assets.forms.$formId'
import { Route as SecuredLocaleWorkerTasksCreateIndexRouteImport } from './routes/secured.$locale.worker.tasks.create.index'
import { Route as SecuredLocaleWorkerTasksTaskIdIndexRouteImport } from './routes/secured.$locale.worker.tasks.$taskId.index'
import { Route as SecuredLocaleWorkerQueuesMessagesIndexRouteImport } from './routes/secured.$locale.worker.queues.messages.index'
import { Route as SecuredLocaleWorkerQueuesDeliveriesIndexRouteImport } from './routes/secured.$locale.worker.queues.deliveries.index'
import { Route as SecuredLocaleWorkerFeedbackFeedbackIdIndexRouteImport } from './routes/secured.$locale.worker.feedback.$feedbackId.index'
import { Route as SecuredLocaleWorkerBatchesCreateIndexRouteImport } from './routes/secured.$locale.worker.batches.create.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SecuredLocaleRoute = SecuredLocaleRouteImport.update({
  id: '/secured/$locale',
  path: '/secured/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const SecuredLocaleIndexRoute = SecuredLocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SecuredLocaleRoute,
} as any)
const SecuredLocaleWorkerRoute = SecuredLocaleWorkerRouteImport.update({
  id: '/worker',
  path: '/worker',
  getParentRoute: () => SecuredLocaleRoute,
} as any)
const SecuredLocaleAssetsRoute = SecuredLocaleAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => SecuredLocaleRoute,
} as any)
const PublicLocaleAuthRoute = PublicLocaleAuthRouteImport.update({
  id: '/public/$locale/auth',
  path: '/public/$locale/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SecuredLocalePublicationsIndexRoute =
  SecuredLocalePublicationsIndexRouteImport.update({
    id: '/publications/',
    path: '/publications/',
    getParentRoute: () => SecuredLocaleRoute,
  } as any)
const SecuredLocaleWorkerTasksRoute =
  SecuredLocaleWorkerTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => SecuredLocaleWorkerRoute,
  } as any)
const SecuredLocaleWorkerProfileRoute =
  SecuredLocaleWorkerProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => SecuredLocaleWorkerRoute,
  } as any)
const SecuredLocaleWorkerBatchesRoute =
  SecuredLocaleWorkerBatchesRouteImport.update({
    id: '/batches',
    path: '/batches',
    getParentRoute: () => SecuredLocaleWorkerRoute,
  } as any)
const SecuredLocaleWorkerTasksIndexRoute =
  SecuredLocaleWorkerTasksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SecuredLocaleWorkerTasksRoute,
  } as any)
const SecuredLocaleWorkerTablesIndexRoute =
  SecuredLocaleWorkerTablesIndexRouteImport.update({
    id: '/tables/',
    path: '/tables/',
    getParentRoute: () => SecuredLocaleWorkerRoute,
  } as any)
const SecuredLocaleWorkerQueuesIndexRoute =
  SecuredLocaleWorkerQueuesIndexRouteImport.update({
    id: '/queues/',
    path: '/queues/',
    getParentRoute: () => SecuredLocaleWorkerRoute,
  } as any)
const SecuredLocaleWorkerMonitoringIndexRoute =
  SecuredLocaleWorkerMonitoringIndexRouteImport.update({
    id: '/monitoring/',
    path: '/monitoring/',
    getParentRoute: () => SecuredLocaleWorkerRoute,
  } as any)
const SecuredLocaleWorkerHelpIndexRoute =
  SecuredLocaleWorkerHelpIndexRouteImport.update({
    id: '/help/',
    path: '/help/',
    getParentRoute: () => SecuredLocaleWorkerRoute,
  } as any)
const SecuredLocaleWorkerFeedbackIndexRoute =
  SecuredLocaleWorkerFeedbackIndexRouteImport.update({
    id: '/feedback/',
    path: '/feedback/',
    getParentRoute: () => SecuredLocaleWorkerRoute,
  } as any)
const SecuredLocaleWorkerDashboardIndexRoute =
  SecuredLocaleWorkerDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => SecuredLocaleWorkerRoute,
  } as any)
const SecuredLocaleWorkerBatchesIndexRoute =
  SecuredLocaleWorkerBatchesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SecuredLocaleWorkerBatchesRoute,
  } as any)
const SecuredLocaleAssetsWrenchIndexRoute =
  SecuredLocaleAssetsWrenchIndexRouteImport.update({
    id: '/wrench/',
    path: '/wrench/',
    getParentRoute: () => SecuredLocaleAssetsRoute,
  } as any)
const SecuredLocaleAssetsStencilIndexRoute =
  SecuredLocaleAssetsStencilIndexRouteImport.update({
    id: '/stencil/',
    path: '/stencil/',
    getParentRoute: () => SecuredLocaleAssetsRoute,
  } as any)
const SecuredLocaleAssetsServicesIndexRoute =
  SecuredLocaleAssetsServicesIndexRouteImport.update({
    id: '/services/',
    path: '/services/',
    getParentRoute: () => SecuredLocaleAssetsRoute,
  } as any)
const SecuredLocaleAssetsMigrateIndexRoute =
  SecuredLocaleAssetsMigrateIndexRouteImport.update({
    id: '/migrate/',
    path: '/migrate/',
    getParentRoute: () => SecuredLocaleAssetsRoute,
  } as any)
const SecuredLocaleAssetsFormsIndexRoute =
  SecuredLocaleAssetsFormsIndexRouteImport.update({
    id: '/forms/',
    path: '/forms/',
    getParentRoute: () => SecuredLocaleAssetsRoute,
  } as any)
const SecuredLocaleAssetsFormsFormIdRoute =
  SecuredLocaleAssetsFormsFormIdRouteImport.update({
    id: '/forms/$formId',
    path: '/forms/$formId',
    getParentRoute: () => SecuredLocaleAssetsRoute,
  } as any)
const SecuredLocaleWorkerTasksCreateIndexRoute =
  SecuredLocaleWorkerTasksCreateIndexRouteImport.update({
    id: '/create/',
    path: '/create/',
    getParentRoute: () => SecuredLocaleWorkerTasksRoute,
  } as any)
const SecuredLocaleWorkerTasksTaskIdIndexRoute =
  SecuredLocaleWorkerTasksTaskIdIndexRouteImport.update({
    id: '/$taskId/',
    path: '/$taskId/',
    getParentRoute: () => SecuredLocaleWorkerTasksRoute,
  } as any)
const SecuredLocaleWorkerQueuesMessagesIndexRoute =
  SecuredLocaleWorkerQueuesMessagesIndexRouteImport.update({
    id: '/queues/messages/',
    path: '/queues/messages/',
    getParentRoute: () => SecuredLocaleWorkerRoute,
  } as any)
const SecuredLocaleWorkerQueuesDeliveriesIndexRoute =
  SecuredLocaleWorkerQueuesDeliveriesIndexRouteImport.update({
    id: '/queues/deliveries/',
    path: '/queues/deliveries/',
    getParentRoute: () => SecuredLocaleWorkerRoute,
  } as any)
const SecuredLocaleWorkerFeedbackFeedbackIdIndexRoute =
  SecuredLocaleWorkerFeedbackFeedbackIdIndexRouteImport.update({
    id: '/feedback/$feedbackId/',
    path: '/feedback/$feedbackId/',
    getParentRoute: () => SecuredLocaleWorkerRoute,
  } as any)
const SecuredLocaleWorkerBatchesCreateIndexRoute =
  SecuredLocaleWorkerBatchesCreateIndexRouteImport.update({
    id: '/create/',
    path: '/create/',
    getParentRoute: () => SecuredLocaleWorkerBatchesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/secured/$locale': typeof SecuredLocaleRouteWithChildren
  '/public/$locale/auth': typeof PublicLocaleAuthRoute
  '/secured/$locale/assets': typeof SecuredLocaleAssetsRouteWithChildren
  '/secured/$locale/worker': typeof SecuredLocaleWorkerRouteWithChildren
  '/secured/$locale/': typeof SecuredLocaleIndexRoute
  '/secured/$locale/worker/batches': typeof SecuredLocaleWorkerBatchesRouteWithChildren
  '/secured/$locale/worker/profile': typeof SecuredLocaleWorkerProfileRoute
  '/secured/$locale/worker/tasks': typeof SecuredLocaleWorkerTasksRouteWithChildren
  '/secured/$locale/publications': typeof SecuredLocalePublicationsIndexRoute
  '/secured/$locale/assets/forms/$formId': typeof SecuredLocaleAssetsFormsFormIdRoute
  '/secured/$locale/assets/forms': typeof SecuredLocaleAssetsFormsIndexRoute
  '/secured/$locale/assets/migrate': typeof SecuredLocaleAssetsMigrateIndexRoute
  '/secured/$locale/assets/services': typeof SecuredLocaleAssetsServicesIndexRoute
  '/secured/$locale/assets/stencil': typeof SecuredLocaleAssetsStencilIndexRoute
  '/secured/$locale/assets/wrench': typeof SecuredLocaleAssetsWrenchIndexRoute
  '/secured/$locale/worker/batches/': typeof SecuredLocaleWorkerBatchesIndexRoute
  '/secured/$locale/worker/dashboard': typeof SecuredLocaleWorkerDashboardIndexRoute
  '/secured/$locale/worker/feedback': typeof SecuredLocaleWorkerFeedbackIndexRoute
  '/secured/$locale/worker/help': typeof SecuredLocaleWorkerHelpIndexRoute
  '/secured/$locale/worker/monitoring': typeof SecuredLocaleWorkerMonitoringIndexRoute
  '/secured/$locale/worker/queues': typeof SecuredLocaleWorkerQueuesIndexRoute
  '/secured/$locale/worker/tables': typeof SecuredLocaleWorkerTablesIndexRoute
  '/secured/$locale/worker/tasks/': typeof SecuredLocaleWorkerTasksIndexRoute
  '/secured/$locale/worker/batches/create': typeof SecuredLocaleWorkerBatchesCreateIndexRoute
  '/secured/$locale/worker/feedback/$feedbackId': typeof SecuredLocaleWorkerFeedbackFeedbackIdIndexRoute
  '/secured/$locale/worker/queues/deliveries': typeof SecuredLocaleWorkerQueuesDeliveriesIndexRoute
  '/secured/$locale/worker/queues/messages': typeof SecuredLocaleWorkerQueuesMessagesIndexRoute
  '/secured/$locale/worker/tasks/$taskId': typeof SecuredLocaleWorkerTasksTaskIdIndexRoute
  '/secured/$locale/worker/tasks/create': typeof SecuredLocaleWorkerTasksCreateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/public/$locale/auth': typeof PublicLocaleAuthRoute
  '/secured/$locale/assets': typeof SecuredLocaleAssetsRouteWithChildren
  '/secured/$locale/worker': typeof SecuredLocaleWorkerRouteWithChildren
  '/secured/$locale': typeof SecuredLocaleIndexRoute
  '/secured/$locale/worker/profile': typeof SecuredLocaleWorkerProfileRoute
  '/secured/$locale/publications': typeof SecuredLocalePublicationsIndexRoute
  '/secured/$locale/assets/forms/$formId': typeof SecuredLocaleAssetsFormsFormIdRoute
  '/secured/$locale/assets/forms': typeof SecuredLocaleAssetsFormsIndexRoute
  '/secured/$locale/assets/migrate': typeof SecuredLocaleAssetsMigrateIndexRoute
  '/secured/$locale/assets/services': typeof SecuredLocaleAssetsServicesIndexRoute
  '/secured/$locale/assets/stencil': typeof SecuredLocaleAssetsStencilIndexRoute
  '/secured/$locale/assets/wrench': typeof SecuredLocaleAssetsWrenchIndexRoute
  '/secured/$locale/worker/batches': typeof SecuredLocaleWorkerBatchesIndexRoute
  '/secured/$locale/worker/dashboard': typeof SecuredLocaleWorkerDashboardIndexRoute
  '/secured/$locale/worker/feedback': typeof SecuredLocaleWorkerFeedbackIndexRoute
  '/secured/$locale/worker/help': typeof SecuredLocaleWorkerHelpIndexRoute
  '/secured/$locale/worker/monitoring': typeof SecuredLocaleWorkerMonitoringIndexRoute
  '/secured/$locale/worker/queues': typeof SecuredLocaleWorkerQueuesIndexRoute
  '/secured/$locale/worker/tables': typeof SecuredLocaleWorkerTablesIndexRoute
  '/secured/$locale/worker/tasks': typeof SecuredLocaleWorkerTasksIndexRoute
  '/secured/$locale/worker/batches/create': typeof SecuredLocaleWorkerBatchesCreateIndexRoute
  '/secured/$locale/worker/feedback/$feedbackId': typeof SecuredLocaleWorkerFeedbackFeedbackIdIndexRoute
  '/secured/$locale/worker/queues/deliveries': typeof SecuredLocaleWorkerQueuesDeliveriesIndexRoute
  '/secured/$locale/worker/queues/messages': typeof SecuredLocaleWorkerQueuesMessagesIndexRoute
  '/secured/$locale/worker/tasks/$taskId': typeof SecuredLocaleWorkerTasksTaskIdIndexRoute
  '/secured/$locale/worker/tasks/create': typeof SecuredLocaleWorkerTasksCreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/secured/$locale': typeof SecuredLocaleRouteWithChildren
  '/public/$locale/auth': typeof PublicLocaleAuthRoute
  '/secured/$locale/assets': typeof SecuredLocaleAssetsRouteWithChildren
  '/secured/$locale/worker': typeof SecuredLocaleWorkerRouteWithChildren
  '/secured/$locale/': typeof SecuredLocaleIndexRoute
  '/secured/$locale/worker/batches': typeof SecuredLocaleWorkerBatchesRouteWithChildren
  '/secured/$locale/worker/profile': typeof SecuredLocaleWorkerProfileRoute
  '/secured/$locale/worker/tasks': typeof SecuredLocaleWorkerTasksRouteWithChildren
  '/secured/$locale/publications/': typeof SecuredLocalePublicationsIndexRoute
  '/secured/$locale/assets/forms/$formId': typeof SecuredLocaleAssetsFormsFormIdRoute
  '/secured/$locale/assets/forms/': typeof SecuredLocaleAssetsFormsIndexRoute
  '/secured/$locale/assets/migrate/': typeof SecuredLocaleAssetsMigrateIndexRoute
  '/secured/$locale/assets/services/': typeof SecuredLocaleAssetsServicesIndexRoute
  '/secured/$locale/assets/stencil/': typeof SecuredLocaleAssetsStencilIndexRoute
  '/secured/$locale/assets/wrench/': typeof SecuredLocaleAssetsWrenchIndexRoute
  '/secured/$locale/worker/batches/': typeof SecuredLocaleWorkerBatchesIndexRoute
  '/secured/$locale/worker/dashboard/': typeof SecuredLocaleWorkerDashboardIndexRoute
  '/secured/$locale/worker/feedback/': typeof SecuredLocaleWorkerFeedbackIndexRoute
  '/secured/$locale/worker/help/': typeof SecuredLocaleWorkerHelpIndexRoute
  '/secured/$locale/worker/monitoring/': typeof SecuredLocaleWorkerMonitoringIndexRoute
  '/secured/$locale/worker/queues/': typeof SecuredLocaleWorkerQueuesIndexRoute
  '/secured/$locale/worker/tables/': typeof SecuredLocaleWorkerTablesIndexRoute
  '/secured/$locale/worker/tasks/': typeof SecuredLocaleWorkerTasksIndexRoute
  '/secured/$locale/worker/batches/create/': typeof SecuredLocaleWorkerBatchesCreateIndexRoute
  '/secured/$locale/worker/feedback/$feedbackId/': typeof SecuredLocaleWorkerFeedbackFeedbackIdIndexRoute
  '/secured/$locale/worker/queues/deliveries/': typeof SecuredLocaleWorkerQueuesDeliveriesIndexRoute
  '/secured/$locale/worker/queues/messages/': typeof SecuredLocaleWorkerQueuesMessagesIndexRoute
  '/secured/$locale/worker/tasks/$taskId/': typeof SecuredLocaleWorkerTasksTaskIdIndexRoute
  '/secured/$locale/worker/tasks/create/': typeof SecuredLocaleWorkerTasksCreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/secured/$locale'
    | '/public/$locale/auth'
    | '/secured/$locale/assets'
    | '/secured/$locale/worker'
    | '/secured/$locale/'
    | '/secured/$locale/worker/batches'
    | '/secured/$locale/worker/profile'
    | '/secured/$locale/worker/tasks'
    | '/secured/$locale/publications'
    | '/secured/$locale/assets/forms/$formId'
    | '/secured/$locale/assets/forms'
    | '/secured/$locale/assets/migrate'
    | '/secured/$locale/assets/services'
    | '/secured/$locale/assets/stencil'
    | '/secured/$locale/assets/wrench'
    | '/secured/$locale/worker/batches/'
    | '/secured/$locale/worker/dashboard'
    | '/secured/$locale/worker/feedback'
    | '/secured/$locale/worker/help'
    | '/secured/$locale/worker/monitoring'
    | '/secured/$locale/worker/queues'
    | '/secured/$locale/worker/tables'
    | '/secured/$locale/worker/tasks/'
    | '/secured/$locale/worker/batches/create'
    | '/secured/$locale/worker/feedback/$feedbackId'
    | '/secured/$locale/worker/queues/deliveries'
    | '/secured/$locale/worker/queues/messages'
    | '/secured/$locale/worker/tasks/$taskId'
    | '/secured/$locale/worker/tasks/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/public/$locale/auth'
    | '/secured/$locale/assets'
    | '/secured/$locale/worker'
    | '/secured/$locale'
    | '/secured/$locale/worker/profile'
    | '/secured/$locale/publications'
    | '/secured/$locale/assets/forms/$formId'
    | '/secured/$locale/assets/forms'
    | '/secured/$locale/assets/migrate'
    | '/secured/$locale/assets/services'
    | '/secured/$locale/assets/stencil'
    | '/secured/$locale/assets/wrench'
    | '/secured/$locale/worker/batches'
    | '/secured/$locale/worker/dashboard'
    | '/secured/$locale/worker/feedback'
    | '/secured/$locale/worker/help'
    | '/secured/$locale/worker/monitoring'
    | '/secured/$locale/worker/queues'
    | '/secured/$locale/worker/tables'
    | '/secured/$locale/worker/tasks'
    | '/secured/$locale/worker/batches/create'
    | '/secured/$locale/worker/feedback/$feedbackId'
    | '/secured/$locale/worker/queues/deliveries'
    | '/secured/$locale/worker/queues/messages'
    | '/secured/$locale/worker/tasks/$taskId'
    | '/secured/$locale/worker/tasks/create'
  id:
    | '__root__'
    | '/'
    | '/secured/$locale'
    | '/public/$locale/auth'
    | '/secured/$locale/assets'
    | '/secured/$locale/worker'
    | '/secured/$locale/'
    | '/secured/$locale/worker/batches'
    | '/secured/$locale/worker/profile'
    | '/secured/$locale/worker/tasks'
    | '/secured/$locale/publications/'
    | '/secured/$locale/assets/forms/$formId'
    | '/secured/$locale/assets/forms/'
    | '/secured/$locale/assets/migrate/'
    | '/secured/$locale/assets/services/'
    | '/secured/$locale/assets/stencil/'
    | '/secured/$locale/assets/wrench/'
    | '/secured/$locale/worker/batches/'
    | '/secured/$locale/worker/dashboard/'
    | '/secured/$locale/worker/feedback/'
    | '/secured/$locale/worker/help/'
    | '/secured/$locale/worker/monitoring/'
    | '/secured/$locale/worker/queues/'
    | '/secured/$locale/worker/tables/'
    | '/secured/$locale/worker/tasks/'
    | '/secured/$locale/worker/batches/create/'
    | '/secured/$locale/worker/feedback/$feedbackId/'
    | '/secured/$locale/worker/queues/deliveries/'
    | '/secured/$locale/worker/queues/messages/'
    | '/secured/$locale/worker/tasks/$taskId/'
    | '/secured/$locale/worker/tasks/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SecuredLocaleRoute: typeof SecuredLocaleRouteWithChildren
  PublicLocaleAuthRoute: typeof PublicLocaleAuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secured/$locale': {
      id: '/secured/$locale'
      path: '/secured/$locale'
      fullPath: '/secured/$locale'
      preLoaderRoute: typeof SecuredLocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/$locale/auth': {
      id: '/public/$locale/auth'
      path: '/public/$locale/auth'
      fullPath: '/public/$locale/auth'
      preLoaderRoute: typeof PublicLocaleAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secured/$locale/assets': {
      id: '/secured/$locale/assets'
      path: '/assets'
      fullPath: '/secured/$locale/assets'
      preLoaderRoute: typeof SecuredLocaleAssetsRouteImport
      parentRoute: typeof SecuredLocaleRoute
    }
    '/secured/$locale/worker': {
      id: '/secured/$locale/worker'
      path: '/worker'
      fullPath: '/secured/$locale/worker'
      preLoaderRoute: typeof SecuredLocaleWorkerRouteImport
      parentRoute: typeof SecuredLocaleRoute
    }
    '/secured/$locale/': {
      id: '/secured/$locale/'
      path: '/'
      fullPath: '/secured/$locale/'
      preLoaderRoute: typeof SecuredLocaleIndexRouteImport
      parentRoute: typeof SecuredLocaleRoute
    }
    '/secured/$locale/worker/batches': {
      id: '/secured/$locale/worker/batches'
      path: '/batches'
      fullPath: '/secured/$locale/worker/batches'
      preLoaderRoute: typeof SecuredLocaleWorkerBatchesRouteImport
      parentRoute: typeof SecuredLocaleWorkerRoute
    }
    '/secured/$locale/worker/profile': {
      id: '/secured/$locale/worker/profile'
      path: '/profile'
      fullPath: '/secured/$locale/worker/profile'
      preLoaderRoute: typeof SecuredLocaleWorkerProfileRouteImport
      parentRoute: typeof SecuredLocaleWorkerRoute
    }
    '/secured/$locale/worker/tasks': {
      id: '/secured/$locale/worker/tasks'
      path: '/tasks'
      fullPath: '/secured/$locale/worker/tasks'
      preLoaderRoute: typeof SecuredLocaleWorkerTasksRouteImport
      parentRoute: typeof SecuredLocaleWorkerRoute
    }
    '/secured/$locale/publications/': {
      id: '/secured/$locale/publications/'
      path: '/publications'
      fullPath: '/secured/$locale/publications'
      preLoaderRoute: typeof SecuredLocalePublicationsIndexRouteImport
      parentRoute: typeof SecuredLocaleRoute
    }
    '/secured/$locale/assets/forms/$formId': {
      id: '/secured/$locale/assets/forms/$formId'
      path: '/forms/$formId'
      fullPath: '/secured/$locale/assets/forms/$formId'
      preLoaderRoute: typeof SecuredLocaleAssetsFormsFormIdRouteImport
      parentRoute: typeof SecuredLocaleAssetsRoute
    }
    '/secured/$locale/assets/forms/': {
      id: '/secured/$locale/assets/forms/'
      path: '/forms'
      fullPath: '/secured/$locale/assets/forms'
      preLoaderRoute: typeof SecuredLocaleAssetsFormsIndexRouteImport
      parentRoute: typeof SecuredLocaleAssetsRoute
    }
    '/secured/$locale/assets/migrate/': {
      id: '/secured/$locale/assets/migrate/'
      path: '/migrate'
      fullPath: '/secured/$locale/assets/migrate'
      preLoaderRoute: typeof SecuredLocaleAssetsMigrateIndexRouteImport
      parentRoute: typeof SecuredLocaleAssetsRoute
    }
    '/secured/$locale/assets/services/': {
      id: '/secured/$locale/assets/services/'
      path: '/services'
      fullPath: '/secured/$locale/assets/services'
      preLoaderRoute: typeof SecuredLocaleAssetsServicesIndexRouteImport
      parentRoute: typeof SecuredLocaleAssetsRoute
    }
    '/secured/$locale/assets/stencil/': {
      id: '/secured/$locale/assets/stencil/'
      path: '/stencil'
      fullPath: '/secured/$locale/assets/stencil'
      preLoaderRoute: typeof SecuredLocaleAssetsStencilIndexRouteImport
      parentRoute: typeof SecuredLocaleAssetsRoute
    }
    '/secured/$locale/assets/wrench/': {
      id: '/secured/$locale/assets/wrench/'
      path: '/wrench'
      fullPath: '/secured/$locale/assets/wrench'
      preLoaderRoute: typeof SecuredLocaleAssetsWrenchIndexRouteImport
      parentRoute: typeof SecuredLocaleAssetsRoute
    }
    '/secured/$locale/worker/batches/': {
      id: '/secured/$locale/worker/batches/'
      path: '/'
      fullPath: '/secured/$locale/worker/batches/'
      preLoaderRoute: typeof SecuredLocaleWorkerBatchesIndexRouteImport
      parentRoute: typeof SecuredLocaleWorkerBatchesRoute
    }
    '/secured/$locale/worker/dashboard/': {
      id: '/secured/$locale/worker/dashboard/'
      path: '/dashboard'
      fullPath: '/secured/$locale/worker/dashboard'
      preLoaderRoute: typeof SecuredLocaleWorkerDashboardIndexRouteImport
      parentRoute: typeof SecuredLocaleWorkerRoute
    }
    '/secured/$locale/worker/feedback/': {
      id: '/secured/$locale/worker/feedback/'
      path: '/feedback'
      fullPath: '/secured/$locale/worker/feedback'
      preLoaderRoute: typeof SecuredLocaleWorkerFeedbackIndexRouteImport
      parentRoute: typeof SecuredLocaleWorkerRoute
    }
    '/secured/$locale/worker/help/': {
      id: '/secured/$locale/worker/help/'
      path: '/help'
      fullPath: '/secured/$locale/worker/help'
      preLoaderRoute: typeof SecuredLocaleWorkerHelpIndexRouteImport
      parentRoute: typeof SecuredLocaleWorkerRoute
    }
    '/secured/$locale/worker/monitoring/': {
      id: '/secured/$locale/worker/monitoring/'
      path: '/monitoring'
      fullPath: '/secured/$locale/worker/monitoring'
      preLoaderRoute: typeof SecuredLocaleWorkerMonitoringIndexRouteImport
      parentRoute: typeof SecuredLocaleWorkerRoute
    }
    '/secured/$locale/worker/queues/': {
      id: '/secured/$locale/worker/queues/'
      path: '/queues'
      fullPath: '/secured/$locale/worker/queues'
      preLoaderRoute: typeof SecuredLocaleWorkerQueuesIndexRouteImport
      parentRoute: typeof SecuredLocaleWorkerRoute
    }
    '/secured/$locale/worker/tables/': {
      id: '/secured/$locale/worker/tables/'
      path: '/tables'
      fullPath: '/secured/$locale/worker/tables'
      preLoaderRoute: typeof SecuredLocaleWorkerTablesIndexRouteImport
      parentRoute: typeof SecuredLocaleWorkerRoute
    }
    '/secured/$locale/worker/tasks/': {
      id: '/secured/$locale/worker/tasks/'
      path: '/'
      fullPath: '/secured/$locale/worker/tasks/'
      preLoaderRoute: typeof SecuredLocaleWorkerTasksIndexRouteImport
      parentRoute: typeof SecuredLocaleWorkerTasksRoute
    }
    '/secured/$locale/worker/batches/create/': {
      id: '/secured/$locale/worker/batches/create/'
      path: '/create'
      fullPath: '/secured/$locale/worker/batches/create'
      preLoaderRoute: typeof SecuredLocaleWorkerBatchesCreateIndexRouteImport
      parentRoute: typeof SecuredLocaleWorkerBatchesRoute
    }
    '/secured/$locale/worker/feedback/$feedbackId/': {
      id: '/secured/$locale/worker/feedback/$feedbackId/'
      path: '/feedback/$feedbackId'
      fullPath: '/secured/$locale/worker/feedback/$feedbackId'
      preLoaderRoute: typeof SecuredLocaleWorkerFeedbackFeedbackIdIndexRouteImport
      parentRoute: typeof SecuredLocaleWorkerRoute
    }
    '/secured/$locale/worker/queues/deliveries/': {
      id: '/secured/$locale/worker/queues/deliveries/'
      path: '/queues/deliveries'
      fullPath: '/secured/$locale/worker/queues/deliveries'
      preLoaderRoute: typeof SecuredLocaleWorkerQueuesDeliveriesIndexRouteImport
      parentRoute: typeof SecuredLocaleWorkerRoute
    }
    '/secured/$locale/worker/queues/messages/': {
      id: '/secured/$locale/worker/queues/messages/'
      path: '/queues/messages'
      fullPath: '/secured/$locale/worker/queues/messages'
      preLoaderRoute: typeof SecuredLocaleWorkerQueuesMessagesIndexRouteImport
      parentRoute: typeof SecuredLocaleWorkerRoute
    }
    '/secured/$locale/worker/tasks/$taskId/': {
      id: '/secured/$locale/worker/tasks/$taskId/'
      path: '/$taskId'
      fullPath: '/secured/$locale/worker/tasks/$taskId'
      preLoaderRoute: typeof SecuredLocaleWorkerTasksTaskIdIndexRouteImport
      parentRoute: typeof SecuredLocaleWorkerTasksRoute
    }
    '/secured/$locale/worker/tasks/create/': {
      id: '/secured/$locale/worker/tasks/create/'
      path: '/create'
      fullPath: '/secured/$locale/worker/tasks/create'
      preLoaderRoute: typeof SecuredLocaleWorkerTasksCreateIndexRouteImport
      parentRoute: typeof SecuredLocaleWorkerTasksRoute
    }
  }
}

declare module './routes/index' {
  const createFileRoute: CreateFileRoute<
    '/',
    FileRoutesByPath['/']['parentRoute'],
    FileRoutesByPath['/']['id'],
    FileRoutesByPath['/']['path'],
    FileRoutesByPath['/']['fullPath']
  >
}
declare module './routes/secured.$locale' {
  const createFileRoute: CreateFileRoute<
    '/secured/$locale',
    FileRoutesByPath['/secured/$locale']['parentRoute'],
    FileRoutesByPath['/secured/$locale']['id'],
    FileRoutesByPath['/secured/$locale']['path'],
    FileRoutesByPath['/secured/$locale']['fullPath']
  >
}
declare module './routes/public.$locale.auth' {
  const createFileRoute: CreateFileRoute<
    '/public/$locale/auth',
    FileRoutesByPath['/public/$locale/auth']['parentRoute'],
    FileRoutesByPath['/public/$locale/auth']['id'],
    FileRoutesByPath['/public/$locale/auth']['path'],
    FileRoutesByPath['/public/$locale/auth']['fullPath']
  >
}
declare module './routes/secured.$locale.assets' {
  const createFileRoute: CreateFileRoute<
    '/secured/$locale/assets',
    FileRoutesByPath['/secured/$locale/assets']['parentRoute'],
    FileRoutesByPath['/secured/$locale/assets']['id'],
    FileRoutesByPath['/secured/$locale/assets']['path'],
    FileRoutesByPath['/secured/$locale/assets']['fullPath']
  >
}
declare module './routes/secured.$locale.worker' {
  const createFileRoute: CreateFileRoute<
    '/secured/$locale/worker',
    FileRoutesByPath['/secured/$locale/worker']['parentRoute'],
    FileRoutesByPath['/secured/$locale/worker']['id'],
    FileRoutesByPath['/secured/$locale/worker']['path'],
    FileRoutesByPath['/secured/$locale/worker']['fullPath']
  >
}
declare module './routes/secured.$locale.index' {
  const createFileRoute: CreateFileRoute<
    '/secured/$locale/',
    FileRoutesByPath['/secured/$locale/']['parentRoute'],
    FileRoutesByPath['/secured/$locale/']['id'],
    FileRoutesByPath['/secured/$locale/']['path'],
    FileRoutesByPath['/secured/$locale/']['fullPath']
  >
}
declare module './routes/secured.$locale.worker.batches' {
  const createFileRoute: CreateFileRoute<
    '/secured/$locale/worker/batches',
    FileRoutesByPath['/secured/$locale/worker/batches']['parentRoute'],
    FileRoutesByPath['/secured/$locale/worker/batches']['id'],
    FileRoutesByPath['/secured/$locale/worker/batches']['path'],
    FileRoutesByPath['/secured/$locale/worker/batches']['fullPath']
  >
}
declare module './routes/secured.$locale.worker.profile' {
  const createFileRoute: CreateFileRoute<
    '/secured/$locale/worker/profile',
    FileRoutesByPath['/secured/$locale/worker/profile']['parentRoute'],
    FileRoutesByPath['/secured/$locale/worker/profile']['id'],
    FileRoutesByPath['/secured/$locale/worker/profile']['path'],
    FileRoutesByPath['/secured/$locale/worker/profile']['fullPath']
  >
}
declare module './routes/secured.$locale.worker.tasks' {
  const createFileRoute: CreateFileRoute<
    '/secured/$locale/worker/tasks',
    FileRoutesByPath['/secured/$locale/worker/tasks']['parentRoute'],
    FileRoutesByPath['/secured/$locale/worker/tasks']['id'],
    FileRoutesByPath['/secured/$locale/worker/tasks']['path'],
    FileRoutesByPath['/secured/$locale/worker/tasks']['fullPath']
  >
}
declare module './routes/secured.$locale.publications.index' {
  const createFileRoute: CreateFileRoute<
    '/secured/$locale/publications/',
    FileRoutesByPath['/secured/$locale/publications/']['parentRoute'],
    FileRoutesByPath['/secured/$locale/publications/']['id'],
    FileRoutesByPath['/secured/$locale/publications/']['path'],
    FileRoutesByPath['/secured/$locale/publications/']['fullPath']
  >
}
declare module './routes/secured.$locale.assets.forms.$formId' {
  const createFileRoute: CreateFileRoute<
    '/secured/$locale/assets/forms/$formId',
    FileRoutesByPath['/secured/$locale/assets/forms/$formId']['parentRoute'],
    FileRoutesByPath['/secured/$locale/assets/forms/$formId']['id'],
    FileRoutesByPath['/secured/$locale/assets/forms/$formId']['path'],
    FileRoutesByPath['/secured/$locale/assets/forms/$formId']['fullPath']
  >
}
declare module './routes/secured.$locale.assets.forms.index' {
  const createFileRoute: CreateFileRoute<
    '/secured/$locale/assets/forms/',
    FileRoutesByPath['/secured/$locale/assets/forms/']['parentRoute'],
    FileRoutesByPath['/secured/$locale/assets/forms/']['id'],
    FileRoutesByPath['/secured/$locale/assets/forms/']['path'],
    FileRoutesByPath['/secured/$locale/assets/forms/']['fullPath']
  >
}
declare module './routes/secured.$locale.assets.migrate.index' {
  const createFileRoute: CreateFileRoute<
    '/secured/$locale/assets/migrate/',
    FileRoutesByPath['/secured/$locale/assets/migrate/']['parentRoute'],
    FileRoutesByPath['/secured/$locale/assets/migrate/']['id'],
    FileRoutesByPath['/secured/$locale/assets/migrate/']['path'],
    FileRoutesByPath['/secured/$locale/assets/migrate/']['fullPath']
  >
}
declare module './routes/secured.$locale.assets.services.index' {
  const createFileRoute: CreateFileRoute<
    '/secured/$locale/assets/services/',
    FileRoutesByPath['/secured/$locale/assets/services/']['parentRoute'],
    FileRoutesByPath['/secured/$locale/assets/services/']['id'],
    FileRoutesByPath['/secured/$locale/assets/services/']['path'],
    FileRoutesByPath['/secured/$locale/assets/services/']['fullPath']
  >
}
declare module './routes/secured.$locale.assets.stencil.index' {
  const createFileRoute: CreateFileRoute<
    '/secured/$locale/assets/stencil/',
    FileRoutesByPath['/secured/$locale/assets/stencil/']['parentRoute'],
    FileRoutesByPath['/secured/$locale/assets/stencil/']['id'],
    FileRoutesByPath['/secured/$locale/assets/stencil/']['path'],
    FileRoutesByPath['/secured/$locale/assets/stencil/']['fullPath']
  >
}
declare module './routes/secured.$locale.assets.wrench.index' {
  const createFileRoute: CreateFileRoute<
    '/secured/$locale/assets/wrench/',
    FileRoutesByPath['/secured/$locale/assets/wrench/']['parentRoute'],
    FileRoutesByPath['/secured/$locale/assets/wrench/']['id'],
    FileRoutesByPath['/secured/$locale/assets/wrench/']['path'],
    FileRoutesByPath['/secured/$locale/assets/wrench/']['fullPath']
  >
}
declare module './routes/secured.$locale.worker.batches.index' {
  const createFileRoute: CreateFileRoute<
    '/secured/$locale/worker/batches/',
    FileRoutesByPath['/secured/$locale/worker/batches/']['parentRoute'],
    FileRoutesByPath['/secured/$locale/worker/batches/']['id'],
    FileRoutesByPath['/secured/$locale/worker/batches/']['path'],
    FileRoutesByPath['/secured/$locale/worker/batches/']['fullPath']
  >
}
declare module './routes/secured.$locale.worker.dashboard.index' {
  const createFileRoute: CreateFileRoute<
    '/secured/$locale/worker/dashboard/',
    FileRoutesByPath['/secured/$locale/worker/dashboard/']['parentRoute'],
    FileRoutesByPath['/secured/$locale/worker/dashboard/']['id'],
    FileRoutesByPath['/secured/$locale/worker/dashboard/']['path'],
    FileRoutesByPath['/secured/$locale/worker/dashboard/']['fullPath']
  >
}
declare module './routes/secured.$locale.worker.feedback.index' {
  const createFileRoute: CreateFileRoute<
    '/secured/$locale/worker/feedback/',
    FileRoutesByPath['/secured/$locale/worker/feedback/']['parentRoute'],
    FileRoutesByPath['/secured/$locale/worker/feedback/']['id'],
    FileRoutesByPath['/secured/$locale/worker/feedback/']['path'],
    FileRoutesByPath['/secured/$locale/worker/feedback/']['fullPath']
  >
}
declare module './routes/secured.$locale.worker.help.index' {
  const createFileRoute: CreateFileRoute<
    '/secured/$locale/worker/help/',
    FileRoutesByPath['/secured/$locale/worker/help/']['parentRoute'],
    FileRoutesByPath['/secured/$locale/worker/help/']['id'],
    FileRoutesByPath['/secured/$locale/worker/help/']['path'],
    FileRoutesByPath['/secured/$locale/worker/help/']['fullPath']
  >
}
declare module './routes/secured.$locale.worker.monitoring.index' {
  const createFileRoute: CreateFileRoute<
    '/secured/$locale/worker/monitoring/',
    FileRoutesByPath['/secured/$locale/worker/monitoring/']['parentRoute'],
    FileRoutesByPath['/secured/$locale/worker/monitoring/']['id'],
    FileRoutesByPath['/secured/$locale/worker/monitoring/']['path'],
    FileRoutesByPath['/secured/$locale/worker/monitoring/']['fullPath']
  >
}
declare module './routes/secured.$locale.worker.queues.index' {
  const createFileRoute: CreateFileRoute<
    '/secured/$locale/worker/queues/',
    FileRoutesByPath['/secured/$locale/worker/queues/']['parentRoute'],
    FileRoutesByPath['/secured/$locale/worker/queues/']['id'],
    FileRoutesByPath['/secured/$locale/worker/queues/']['path'],
    FileRoutesByPath['/secured/$locale/worker/queues/']['fullPath']
  >
}
declare module './routes/secured.$locale.worker.tables.index' {
  const createFileRoute: CreateFileRoute<
    '/secured/$locale/worker/tables/',
    FileRoutesByPath['/secured/$locale/worker/tables/']['parentRoute'],
    FileRoutesByPath['/secured/$locale/worker/tables/']['id'],
    FileRoutesByPath['/secured/$locale/worker/tables/']['path'],
    FileRoutesByPath['/secured/$locale/worker/tables/']['fullPath']
  >
}
declare module './routes/secured.$locale.worker.tasks.index' {
  const createFileRoute: CreateFileRoute<
    '/secured/$locale/worker/tasks/',
    FileRoutesByPath['/secured/$locale/worker/tasks/']['parentRoute'],
    FileRoutesByPath['/secured/$locale/worker/tasks/']['id'],
    FileRoutesByPath['/secured/$locale/worker/tasks/']['path'],
    FileRoutesByPath['/secured/$locale/worker/tasks/']['fullPath']
  >
}
declare module './routes/secured.$locale.worker.batches.create.index' {
  const createFileRoute: CreateFileRoute<
    '/secured/$locale/worker/batches/create/',
    FileRoutesByPath['/secured/$locale/worker/batches/create/']['parentRoute'],
    FileRoutesByPath['/secured/$locale/worker/batches/create/']['id'],
    FileRoutesByPath['/secured/$locale/worker/batches/create/']['path'],
    FileRoutesByPath['/secured/$locale/worker/batches/create/']['fullPath']
  >
}
declare module './routes/secured.$locale.worker.feedback.$feedbackId.index' {
  const createFileRoute: CreateFileRoute<
    '/secured/$locale/worker/feedback/$feedbackId/',
    FileRoutesByPath['/secured/$locale/worker/feedback/$feedbackId/']['parentRoute'],
    FileRoutesByPath['/secured/$locale/worker/feedback/$feedbackId/']['id'],
    FileRoutesByPath['/secured/$locale/worker/feedback/$feedbackId/']['path'],
    FileRoutesByPath['/secured/$locale/worker/feedback/$feedbackId/']['fullPath']
  >
}
declare module './routes/secured.$locale.worker.queues.deliveries.index' {
  const createFileRoute: CreateFileRoute<
    '/secured/$locale/worker/queues/deliveries/',
    FileRoutesByPath['/secured/$locale/worker/queues/deliveries/']['parentRoute'],
    FileRoutesByPath['/secured/$locale/worker/queues/deliveries/']['id'],
    FileRoutesByPath['/secured/$locale/worker/queues/deliveries/']['path'],
    FileRoutesByPath['/secured/$locale/worker/queues/deliveries/']['fullPath']
  >
}
declare module './routes/secured.$locale.worker.queues.messages.index' {
  const createFileRoute: CreateFileRoute<
    '/secured/$locale/worker/queues/messages/',
    FileRoutesByPath['/secured/$locale/worker/queues/messages/']['parentRoute'],
    FileRoutesByPath['/secured/$locale/worker/queues/messages/']['id'],
    FileRoutesByPath['/secured/$locale/worker/queues/messages/']['path'],
    FileRoutesByPath['/secured/$locale/worker/queues/messages/']['fullPath']
  >
}
declare module './routes/secured.$locale.worker.tasks.$taskId.index' {
  const createFileRoute: CreateFileRoute<
    '/secured/$locale/worker/tasks/$taskId/',
    FileRoutesByPath['/secured/$locale/worker/tasks/$taskId/']['parentRoute'],
    FileRoutesByPath['/secured/$locale/worker/tasks/$taskId/']['id'],
    FileRoutesByPath['/secured/$locale/worker/tasks/$taskId/']['path'],
    FileRoutesByPath['/secured/$locale/worker/tasks/$taskId/']['fullPath']
  >
}
declare module './routes/secured.$locale.worker.tasks.create.index' {
  const createFileRoute: CreateFileRoute<
    '/secured/$locale/worker/tasks/create/',
    FileRoutesByPath['/secured/$locale/worker/tasks/create/']['parentRoute'],
    FileRoutesByPath['/secured/$locale/worker/tasks/create/']['id'],
    FileRoutesByPath['/secured/$locale/worker/tasks/create/']['path'],
    FileRoutesByPath['/secured/$locale/worker/tasks/create/']['fullPath']
  >
}

interface SecuredLocaleAssetsRouteChildren {
  SecuredLocaleAssetsFormsFormIdRoute: typeof SecuredLocaleAssetsFormsFormIdRoute
  SecuredLocaleAssetsFormsIndexRoute: typeof SecuredLocaleAssetsFormsIndexRoute
  SecuredLocaleAssetsMigrateIndexRoute: typeof SecuredLocaleAssetsMigrateIndexRoute
  SecuredLocaleAssetsServicesIndexRoute: typeof SecuredLocaleAssetsServicesIndexRoute
  SecuredLocaleAssetsStencilIndexRoute: typeof SecuredLocaleAssetsStencilIndexRoute
  SecuredLocaleAssetsWrenchIndexRoute: typeof SecuredLocaleAssetsWrenchIndexRoute
}

const SecuredLocaleAssetsRouteChildren: SecuredLocaleAssetsRouteChildren = {
  SecuredLocaleAssetsFormsFormIdRoute: SecuredLocaleAssetsFormsFormIdRoute,
  SecuredLocaleAssetsFormsIndexRoute: SecuredLocaleAssetsFormsIndexRoute,
  SecuredLocaleAssetsMigrateIndexRoute: SecuredLocaleAssetsMigrateIndexRoute,
  SecuredLocaleAssetsServicesIndexRoute: SecuredLocaleAssetsServicesIndexRoute,
  SecuredLocaleAssetsStencilIndexRoute: SecuredLocaleAssetsStencilIndexRoute,
  SecuredLocaleAssetsWrenchIndexRoute: SecuredLocaleAssetsWrenchIndexRoute,
}

const SecuredLocaleAssetsRouteWithChildren =
  SecuredLocaleAssetsRoute._addFileChildren(SecuredLocaleAssetsRouteChildren)

interface SecuredLocaleWorkerBatchesRouteChildren {
  SecuredLocaleWorkerBatchesIndexRoute: typeof SecuredLocaleWorkerBatchesIndexRoute
  SecuredLocaleWorkerBatchesCreateIndexRoute: typeof SecuredLocaleWorkerBatchesCreateIndexRoute
}

const SecuredLocaleWorkerBatchesRouteChildren: SecuredLocaleWorkerBatchesRouteChildren =
  {
    SecuredLocaleWorkerBatchesIndexRoute: SecuredLocaleWorkerBatchesIndexRoute,
    SecuredLocaleWorkerBatchesCreateIndexRoute:
      SecuredLocaleWorkerBatchesCreateIndexRoute,
  }

const SecuredLocaleWorkerBatchesRouteWithChildren =
  SecuredLocaleWorkerBatchesRoute._addFileChildren(
    SecuredLocaleWorkerBatchesRouteChildren,
  )

interface SecuredLocaleWorkerTasksRouteChildren {
  SecuredLocaleWorkerTasksIndexRoute: typeof SecuredLocaleWorkerTasksIndexRoute
  SecuredLocaleWorkerTasksTaskIdIndexRoute: typeof SecuredLocaleWorkerTasksTaskIdIndexRoute
  SecuredLocaleWorkerTasksCreateIndexRoute: typeof SecuredLocaleWorkerTasksCreateIndexRoute
}

const SecuredLocaleWorkerTasksRouteChildren: SecuredLocaleWorkerTasksRouteChildren =
  {
    SecuredLocaleWorkerTasksIndexRoute: SecuredLocaleWorkerTasksIndexRoute,
    SecuredLocaleWorkerTasksTaskIdIndexRoute:
      SecuredLocaleWorkerTasksTaskIdIndexRoute,
    SecuredLocaleWorkerTasksCreateIndexRoute:
      SecuredLocaleWorkerTasksCreateIndexRoute,
  }

const SecuredLocaleWorkerTasksRouteWithChildren =
  SecuredLocaleWorkerTasksRoute._addFileChildren(
    SecuredLocaleWorkerTasksRouteChildren,
  )

interface SecuredLocaleWorkerRouteChildren {
  SecuredLocaleWorkerBatchesRoute: typeof SecuredLocaleWorkerBatchesRouteWithChildren
  SecuredLocaleWorkerProfileRoute: typeof SecuredLocaleWorkerProfileRoute
  SecuredLocaleWorkerTasksRoute: typeof SecuredLocaleWorkerTasksRouteWithChildren
  SecuredLocaleWorkerDashboardIndexRoute: typeof SecuredLocaleWorkerDashboardIndexRoute
  SecuredLocaleWorkerFeedbackIndexRoute: typeof SecuredLocaleWorkerFeedbackIndexRoute
  SecuredLocaleWorkerHelpIndexRoute: typeof SecuredLocaleWorkerHelpIndexRoute
  SecuredLocaleWorkerMonitoringIndexRoute: typeof SecuredLocaleWorkerMonitoringIndexRoute
  SecuredLocaleWorkerQueuesIndexRoute: typeof SecuredLocaleWorkerQueuesIndexRoute
  SecuredLocaleWorkerTablesIndexRoute: typeof SecuredLocaleWorkerTablesIndexRoute
  SecuredLocaleWorkerFeedbackFeedbackIdIndexRoute: typeof SecuredLocaleWorkerFeedbackFeedbackIdIndexRoute
  SecuredLocaleWorkerQueuesDeliveriesIndexRoute: typeof SecuredLocaleWorkerQueuesDeliveriesIndexRoute
  SecuredLocaleWorkerQueuesMessagesIndexRoute: typeof SecuredLocaleWorkerQueuesMessagesIndexRoute
}

const SecuredLocaleWorkerRouteChildren: SecuredLocaleWorkerRouteChildren = {
  SecuredLocaleWorkerBatchesRoute: SecuredLocaleWorkerBatchesRouteWithChildren,
  SecuredLocaleWorkerProfileRoute: SecuredLocaleWorkerProfileRoute,
  SecuredLocaleWorkerTasksRoute: SecuredLocaleWorkerTasksRouteWithChildren,
  SecuredLocaleWorkerDashboardIndexRoute:
    SecuredLocaleWorkerDashboardIndexRoute,
  SecuredLocaleWorkerFeedbackIndexRoute: SecuredLocaleWorkerFeedbackIndexRoute,
  SecuredLocaleWorkerHelpIndexRoute: SecuredLocaleWorkerHelpIndexRoute,
  SecuredLocaleWorkerMonitoringIndexRoute:
    SecuredLocaleWorkerMonitoringIndexRoute,
  SecuredLocaleWorkerQueuesIndexRoute: SecuredLocaleWorkerQueuesIndexRoute,
  SecuredLocaleWorkerTablesIndexRoute: SecuredLocaleWorkerTablesIndexRoute,
  SecuredLocaleWorkerFeedbackFeedbackIdIndexRoute:
    SecuredLocaleWorkerFeedbackFeedbackIdIndexRoute,
  SecuredLocaleWorkerQueuesDeliveriesIndexRoute:
    SecuredLocaleWorkerQueuesDeliveriesIndexRoute,
  SecuredLocaleWorkerQueuesMessagesIndexRoute:
    SecuredLocaleWorkerQueuesMessagesIndexRoute,
}

const SecuredLocaleWorkerRouteWithChildren =
  SecuredLocaleWorkerRoute._addFileChildren(SecuredLocaleWorkerRouteChildren)

interface SecuredLocaleRouteChildren {
  SecuredLocaleAssetsRoute: typeof SecuredLocaleAssetsRouteWithChildren
  SecuredLocaleWorkerRoute: typeof SecuredLocaleWorkerRouteWithChildren
  SecuredLocaleIndexRoute: typeof SecuredLocaleIndexRoute
  SecuredLocalePublicationsIndexRoute: typeof SecuredLocalePublicationsIndexRoute
}

const SecuredLocaleRouteChildren: SecuredLocaleRouteChildren = {
  SecuredLocaleAssetsRoute: SecuredLocaleAssetsRouteWithChildren,
  SecuredLocaleWorkerRoute: SecuredLocaleWorkerRouteWithChildren,
  SecuredLocaleIndexRoute: SecuredLocaleIndexRoute,
  SecuredLocalePublicationsIndexRoute: SecuredLocalePublicationsIndexRoute,
}

const SecuredLocaleRouteWithChildren = SecuredLocaleRoute._addFileChildren(
  SecuredLocaleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SecuredLocaleRoute: SecuredLocaleRouteWithChildren,
  PublicLocaleAuthRoute: PublicLocaleAuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
