<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>io.digiexpress</groupId>
    <artifactId>digiexpress-parent</artifactId>
    <version>6.0.36</version>
  </parent>

  <name>digiexpress-bom</name>
  <artifactId>digiexpress-bom</artifactId>
  <packaging>pom</packaging>

  <dependencyManagement>
    <dependencies>
    
      <dependency>
        <groupId>io.digiexpress</groupId>
        <artifactId>thena-test-client</artifactId>
        <version>${project.version}</version>
        <scope>test</scope>
      </dependency>
      <dependency>
        <groupId>io.digiexpress</groupId>
        <artifactId>lp-client</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>io.digiexpress</groupId>
        <artifactId>lp-batches</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>io.digiexpress</groupId>
        <artifactId>lp-products</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>io.digiexpress</groupId>
        <artifactId>limaone-compiler</artifactId>
        <version>${project.version}</version>
      </dependency>

      <dependency>
        <groupId>io.digiexpress</groupId>
        <artifactId>thena-contract-client</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>io.digiexpress</groupId>
        <artifactId>thena-ledger-client</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>io.digiexpress</groupId>
        <artifactId>thena-product-client</artifactId>
        <version>${project.version}</version>
      </dependency>
      
      <dependency>
        <groupId>io.digiexpress</groupId>
        <artifactId>eveli-user-profile</artifactId>
        <version>${project.version}</version>
      </dependency>  
      <dependency>
        <groupId>io.digiexpress</groupId>
        <artifactId>eveli-permissions</artifactId>
        <version>${project.version}</version>
      </dependency>  
      <dependency>
        <groupId>io.digiexpress</groupId>
        <artifactId>eveli-client</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>io.digiexpress</groupId>
        <artifactId>eveli-integration-google</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>io.digiexpress</groupId>
        <artifactId>eveli-integration-suomifi-rest</artifactId>
        <version>${project.version}</version>
      </dependency>    
      <dependency>
        <groupId>io.digiexpress</groupId>
        <artifactId>eveli-integration-queue</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>io.digiexpress</groupId>
        <artifactId>thena-db-client</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>io.digiexpress</groupId>
        <artifactId>thena-mq-client</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>io.digiexpress</groupId>
        <artifactId>thena-batch-client</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>io.digiexpress</groupId>
        <artifactId>thena-grim-client</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>io.digiexpress</groupId>
        <artifactId>thena-git-client</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>io.digiexpress</groupId>
        <artifactId>thena-doc-client</artifactId>
        <version>${project.version}</version>
      </dependency>

      
      <dependency>
        <groupId>io.digiexpress</groupId>
        <artifactId>thena-fs-client</artifactId>
        <version>${project.version}</version>
      </dependency>      
      <dependency>
        <groupId>io.digiexpress</groupId>
        <artifactId>thena-sql-client</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>io.digiexpress</groupId>
        <artifactId>thena-sql-client-annot-proc</artifactId>
        <version>${project.version}</version>
      </dependency>
      
    </dependencies>
  </dependencyManagement>
</project>