export const en = {
  'document.title': 'DigiExpress',
  'booleanValue.true': 'Yes',
  'booleanValue.false': 'No',
  'eveli.textSeparatorColon': ':',
  'eveli.permissions.none.title': 'Oops!',
  'eveli.permissions.none.desc1': 'You don\'t have the correct access rights to use this application.',
  'eveli.permissions.none.desc2': 'Please contact your system administrator.',
  'tasksView.title': 'Tasks',
  'tasksTableHeader.taskName': 'Task name',
  'tasksTableHeader.category': 'Type',
  'tasksTableHeader.status': 'Status',
  'tasksTableHeader.dueDate': 'Due date',
  'tasksTableHeader.priority': 'Priority',
  'tasksTableHeader.assigned': 'Assigned to',
  'tasksTableAction.editTask': 'Edit task',
  'tasksTableAction.deleteTask': 'Delete task',
  'taskPriority.low': 'Low',
  'taskPriority.normal': 'Normal',
  'taskPriority.high': 'High',
  'taskDialog.priority': 'Priority',
  'taskDialog.subject': 'Subject',
  'taskDialog.description': 'Description',
  'taskDialog.dueDate': 'Due date',
  'taskDialog.assignedTo': 'User role',
  'taskDialog.assignedUser': 'User',
  'taskDialog.status': 'Status',
  'taskDialog.task': 'Task',
  'taskDialog.category': 'Type',
  'taskDialog.source': 'Source',
  'taskDialog.additionalInfo': 'Additional information',
  'task.priority.low': 'Low',
  'task.priority.normal': 'Normal',
  'task.priority.high': 'High',
  'task.status.new': 'New',
  'task.status.open': 'Open',
  'task.status.completed': 'Completed',
  'task.status.rejected': 'No processing',
  'task.form.review': 'View form',
  'task.form.feedback.manage': 'Manage feedback',
  'task.form.feedback.updated': 'Feedback update successful',
  'task.created': 'Created',
  'task.updated': 'Updated',
  'comments': 'Comments',
  'task.comments.external.createTask': 'Create task before adding external comments',
  'task.comments.internal.createTask': 'Create task before adding internal comments',
  'task.attachments.createTask': 'Create task before uploading attachments',
  'task.comments.external.added': 'Internal comment added',
  'task.feedback.publishedSaved': 'Message to client sended',
  'task.comments.internal.added': 'Comment added',
  'internalComments': 'Internal comments',
  'externalComments': 'Client messages',
  'comment.store': 'Save',
  'comment.add': 'Add comment',
  'comment.addInternal': 'Add internal comment',
  'comment.addExternal': 'Message to client',
  'comment.reply': 'Reply',
  'taskButton.addTask': 'Add task',
  'taskButton.refresh': 'Check for new tasks',
  'taskButton.accept': 'Accept',
  'taskButton.cancel': 'Close',
  'table.body.emptyDataSourceMessage': 'No data',
  'table.body.filterRow.filterTooltip': 'Filter',
  'table.body.deleteTooltip': 'Delete',
  'table.body.editRow.deleteText': 'Are you sure you want to delete this task?',
  'table.body.editRow.cancelTask': 'Cancel',
  'table.body.editRow.saveTask': 'Confirm',
  'table.header.actions': 'Actions',
  'table.pagination.labelDisplayedRows': '{from}-{to} of {count}',
  'table.pagination.labelRowsPerPage': 'Rows per page:',
  'table.pagination.firstPage': 'First page',
  'table.pagination.previousPage': 'Previous page',
  'table.pagination.nextPage': 'Next page',
  'table.pagination.lastPage': 'Last page',
  'table.toolbar.search': 'Search',
  'table.toolbar.showColumnsTitle': 'Show columns',
  'table.toolbar.addRemoveColumns': 'Add or remove columns',
  'taskLink.title': 'Task link',
  'taskLink.button.open': 'View related data',
  'taskLink.pdf.open': 'PDF',
  'explorer.title': 'Public feedback',
  'explorer.login': 'Log in',
  'locale.fi': 'Suomi',
  'locale.sv': 'Svenska',
  'locale.en': 'English',
  'app.logout': 'Log out',
  'app.login': 'Log in',
  'app.feedback': 'Feedback',
  'main.articles.all': 'All Articles',
  'main.links.all': 'All Links',
  'main.services.all': 'All Services',
  'main.flows.all': 'All Service Flows',
  'main.debug': 'Debug',
  'main.compare': 'Compare',
  'main.decisions.all': 'All Decisions Tables',
  'menu.dashboard': 'Dashboard',
  'menu.profile': 'Profile',
  'menu.tasks': 'Tasks',
  'menu.evaluations': 'Questionnaires',
  'menu.forms': 'Dialob',
  'menu.queues': 'Queues',
  'menu.users': 'Users',
  'menu.help': 'Help',
  'menu.flow': 'theWrench',
  'menu.processes': 'Monitoring',
  'menu.reports': 'Reports',
  'menu.workflows': 'Stencil services',
  'menu.logout': 'Log out',
  'menu.workflowTags': 'Workflow tags',
  'menu.publications': 'Publications',
  'menu.services': 'Services',
  'menu.content': 'Stencil',
  'menu.calendar': 'Calendar',
  'menu.feedback': 'Feedback',
  'menu.compose': 'Compose',
  'menu.pages': 'Pages',
  'menu.articles': 'Articles',
  'menu.links': 'Links',
  'menu.locales': 'Languages',
  'menu.migrations': 'Migrations',
  'menu.templates': 'Templates',
  'menu.flows': 'Service Flows',
  'menu.decisions': 'Decision tables',
  'menu.debug': 'Debug',
  'menu.releases': 'Releases',
  'menu.compare': 'Compare',
  'front.intro.title': 'Welcome!',
  'profile.title': 'User Profile',
  'profile.user.name': 'Name:',
  'profile.user.email': 'e-mail:',
  'profile.user.role': 'Role:',
  'profile.user.phone': 'Phone:',
  'profile.app.version': 'Application version:',
  'button.cancel': 'Cancel',
  'button.confirmDelete': 'Delete',
  'button.delete': 'Delete this feedback',
  'button.delete.template': 'Delete this template',
  'button.delete.link': 'Delete this link',
  'button.delete.article': 'Delete this article',
  'button.delete.page': 'Delete this page',
  'button.unpublish': 'Unpublish this feedback',
  'button.update': 'Update',
  'button.publish': 'Publish',
  'button.accept': 'Accept',
  'button.edit': 'Edit',
  'button.close': 'Close',
  'button.reject': 'Reject',
  'button.send': 'Send',
  'button.dismiss': 'Dismiss',
  'button.editRoles': 'Edit',
  'button.select': 'Select',
  'error.minTextLength': 'Value should be at least {minLength} characters long',
  'error.maxTextLength': 'Value should be no more than {max} characters long',
  'error.valueRequired': 'Value required',
  'error.title': 'Error!',
  'error.dialob.session': 'Questionnaire cannot be opened at this moment, please try again later',
  'error.errorLoadingData': 'Error during data loading',
  'error.unauthorized.title': 'Missing access role',
  'error.unauthorized.text': 'Contact your system administrator to check your role',
  'error.unauthorizedAccess': 'Missing access role',
  'error.dataAccess': 'Error during data loading',
  'error.statusOpenError': 'Required when status is open',
  'error.workflowCreation': 'Error on workflow creation, check worflow name for duplicates',
  'table.body.addTooltip': 'Add',
  'table.body.editTooltip': 'Edit',
  'table.body.editRow.deleteMessage': 'Are you sure you want to delete this?',
  'workflowTable.title': 'Stencil services',
  'workflowTableHeader.name': 'Name',
  'workflowTableHeader.formName': 'Form',
  'workflowTableHeader.flowName': 'Flow',
  'workflowTableHeader.updated': 'Updated',
  'workflowTable.addButton': 'New workflow',
  'workflowTable.editButton': 'Edit workflow',
  'workflow.dialogTitle': 'Stencil service',
  'workflow.name': 'Name',
  'workflow.form.formName': 'Form name',
  'workflow.form.formTag': 'Form tag',
  'workflow.flowName': 'Flow name',
  'processTable.title': 'Stencil service execution history',
  'processTableHeader.workflow': 'Stencil service name',
  'processTableHeader.user': 'User id',
  'processTableHeader.status': 'Status',
  'processTableHeader.created': 'Created',
  'processTableHeader.questionnaireId': 'Questionnaire',
  'process.status.ANSWERED': 'Answered',
  'process.status.CREATED': 'Created',
  'process.status.ANSWERING': 'Answering',
  'process.status.IN_PROGRESS': 'In progress',
  'process.status.WAITING': 'Waiting',
  'process.status.COMPLETED': 'Completed',
  'process.status.REJECTED': 'Rejected',
  'comment.button': 'Send comment',
  'comment.title': 'Send comment',
  'comment.form.email': 'E-mail',
  'comment.form.feedbackType': 'Type',
  'comment.form.body': 'Message',
  'comment.type.general': 'General',
  'comment.type.propose': 'Propose',
  'comment.type.contact': 'Contact me',
  'comment.submitted.success': 'Thank you for your feedback!',
  'comment.submitted.failure': 'Comment submission failed!',
  'spoTasksTableHeader.taskName': 'Name',
  'spoTasksTableHeader.category': 'Type',
  'spoTasksTableHeader.status': 'Status',
  'spoTasksTableHeader.priority': 'Priority',
  'spoTasksTableHeader.dueDate': 'Due',
  'spoTasksTableHeader.assigned': 'Role',
  'spoTasksTableHeader.assignedUser': 'Handler',
  'spoTasksTableHeader.created': 'Created',
  'spoTasksTableHeader.clientName': 'Client',
  'spoTasksTableHeader.additionalInfo': 'Info',
  'taskDialog.clientIdentificator': 'Client name',
  'taskDialog.assignedUserEmail': 'User\'s email',
  'task.editRoles': 'Task groups',
  'Questionnaire': 'Questionnaire',
  'Manual': 'Manual',
  'Protected': 'Protected',
  'Normal': 'Normal',
  'Represented': 'Represented',
  'CustomerCreated': 'Customer created',
  'Internal': 'Internal',
  'task.role.assignedAllUsers': 'All users',
  'task.feedback.published': 'Published reply',
  'confirm.close.title': 'Confirmation required',
  'confirm.unsavedChanges': 'Unsaved changes will be lost, do you want to continue?',
  'task.statistics.statusCount': 'By status',
  'task.statistics.priorityCount': 'By priority',
  'task.statistics.daily': 'Daily',
  'task.statistics.overdue': 'Overdue',
  'feedback.button': 'Send feedback',
  'feedback.thanks': 'Thank you for your feedback!',
  'feedback.create.title': 'Create public reply to customer feedback',
  'feedback.title': 'Public reply to customer feedback',
  'feedback.update.title': 'Edit public reply to customer feedback',
  'feedback.description': 'Description',
  'feedback.name': 'Your name',
  'feedback.sendScreenshot': 'Send screenshot',
  'feedback.close': 'Close',
  'feedback.send': 'Send',
  'feedback.taskReferenceId': 'Task Reference ID',
  'feedback.taskId': 'Task ID',
  'feedback.mainCategory': 'Subject',
  'feedback.subCategory': 'Specific topic area',
  'feedback.feedbackValue': 'Customer feedback',
  'feedback.customerTitle': 'Feedback title',
  'feedback.myReply': 'Reply to customer',
  'feedback.noFeedback.info1': 'No reply to publish!',
  'feedback.noFeedback.info2': 'Please send an external comment to customer, then you can publish the external comment.',
  'feedback.customerFeedback': 'Customer feedback',
  'feedback.customerApprovals': 'Customer approvals',
  'feedback.sourceTaskId': 'Source task id',
  'feedback.formName': 'Form name',
  'feedback.dateReceived': 'Date received from customer',
  'feedback.createdBy': 'Created by',
  'feedback.updatedBy': 'Updated by',
  'feedback.updated': 'Last updated',
  'feedback.notPublished': 'This feedback is not published',
  'feedback.isPublished': 'This feedback is published and publicly viewable',
  'feedback.delete.confirmTitle': 'Delete Feedback?',
  'feedback.delete.confirmText': 'Are you sure you want to delete this feedback?',
  'help.title': 'Help',
  'attachmentView.title': 'Attachments',
  'attachmentTableHeader.size': 'Size',
  'attachmentTableHeader.updated': 'Updated',
  'attachmentTableHeader.created': 'Created',
  'attachmentTableHeader.name': 'Subject',
  'attachmentButton.addAttachment': 'Add file',
  'attachmentButton.downloadAttachment': 'Download file',
  'attachmentButton.deleteAttachment': 'Delete file',
  'attachment.uploadOk': 'File {fileName} uploaded',
  'attachment.uploadFailed': 'File {fileName} upload failed!',
  'attachment.delete.confirmTitle': 'Delete file?',
  'attachment.delete.confirmText': 'Are you sure you want to delete file {fileName}?',
  'attachment.deleteFailed': 'File {fileName} delete failed!',
  'workflowReleaseTable.title': 'Workflow release tags',
  'workflowReleaseTableHeader.name': 'Name',
  'workflowReleaseTableHeader.description': 'Description',
  'workflowReleaseTableHeader.updatedBy': 'Updater',
  'workflowReleaseTableHeader.updated': 'Updated',
  'workflowReleaseTable.addButton': 'Add',
  'workflowReleaseTable.viewButton': 'View',
  'workflowReleaseTable.exportButton': 'Export',
  'workflowRelease.dialogTitle': 'Workflow release',
  'workflowRelease.name': 'Release name',
  'workflowRelease.description': 'Description',
  'workflowRelease.releaseCreationFailed': 'Workflow tag creation failed, cause: {cause}',
  'publicationsTable.title': 'Publications',
  'publicationsTableHeader.name': 'Release name',
  'publicationsTableHeader.description': 'Description',
  'publicationsTableHeader.createdBy': 'User',
  'publicationsTableHeader.created': 'Created',
  'publicationsTableHeader.contentTag': 'Content tag',
  'publicationsTableHeader.workflowTag': 'Workflow tag',
  'publicationsTableHeader.wrenchTag': 'theWrench tag',
  'publicationsTableHeader.liveDate': 'Live date',
  'publicationsTable.addButton': 'Add',
  'publicationsTable.viewButton': 'View',
  'publicationsTable.exportButton': 'Export',
  'publicationsTable.uploadButton': 'Upload',
  'publications.external': 'This is externally configured deployment and will be in effect when there are no other deployments',
  'publications.changeStatus': 'Modify deployment status',
  'publications.currentStatus': 'Current status of deployment',
  'publications.remove': 'Remove deployment',
  'publications.deploy': 'Deploy now',
  'publications.dialogTitle': 'Create new Publication',
  'publications.name': 'Release name',
  'publications.description': 'Description',
  'publications.workflowTag': 'Workflow tag',
  'publications.wrenchTag': 'theWrench tag',
  'publications.contentTag': 'Content tag',
  'publications.createNewTag': 'Create new tag \"{tag}\"',
  'publications.downloadFailed': 'Release download failed, cause: {cause}',
  'publications.tagCreationFailed': 'Release creation failed, cause: {cause}',
  'publications.uploadDialogTitle': 'Upload publication',
  'dialobForms.dialog.heading': 'Forms',
  'dialobForms.table.tooltip.add': 'Add',
  'dialobForms.table.label': 'ID',
  'dialobForms.table.created': 'Created',
  'dialobForms.table.lastSaved': 'Updated',
  'dialobForms.table.tooltip.edit': 'Edit',
  'dialobForms.dialog.emptyTitle': '-',
  'dialobForms.table.tooltip.copy': 'Copy',
  'dialobForms.table.tooltip.delete': 'Remove',
  'dialobForm.saveFailed': 'Saving failed',
  'dialobForm.downloadFailed': 'Saving failed',
  'dialobForm.deleteFailed': 'Remove failed',
  'dialobForm.heading.copyDialog': 'Copy',
  'dialobForm.heading.addDialog': 'Add',
  'dialobForm.dialog.formName': 'ID',
  'dialobForm.dialog.formLabel': 'Name',
  'dialobForm.error.invalidFormName': 'Incorrect ID',
  'dialobForm.dialog.deleteQuestion': 'Do you want to remove form \"{formName}\"?',
  'dialobForm.heading.deleteDialog': 'Remove form',
  'dialobForm.review.title': 'Form review',
  'feedback.notenabled': 'Feedback is not enabled for this task',
  'pages': 'Pages',
  'articles': 'Articles',
  'locale': 'Locale',
  'locales': 'Site Languages',
  'tag': 'Tag',
  'links': 'Links',
  'releases': 'Releases',
  'options': 'Options',
  'value': 'Value',
  'date': 'Date',
  'order': 'Order',
  'description': 'Description',
  'name': 'Name',
  'delete': 'Delete',
  'download': 'Download JSON',
  'disable': 'Disable',
  'status': 'Status',
  'created': 'Created',
  'modified': 'Modified',
  'rename': 'Rename',
  'reorder': 'Re-order',
  'remove': 'Remove',
  'site.content.empty': 'Site has no content! Create content before making a release!',
  'composer.select.article': 'Select Article',
  'search.field.placeholder': 'Enter search keyword',
  'search.results.title': 'Search results',
  'search.field.label': 'Search',
  'search.all': 'All',
  'search.articles': 'Articles',
  'search.services': 'Services',
  'search.links': 'Links',
  'search.templates': 'Templates',
  'search.flows': 'Flows',
  'search.decisions': 'Decisions',
  'activities.title': 'Activities',
  'activities.desc': 'Create, view, and navigate site resources',
  'activities.article.title': 'Article',
  'activities.article.desc': 'An Article is like a category: It groups Pages, Links, and Services together under one roof.',
  'activities.locale.title': 'Locale',
  'activities.locale.desc': 'Locales are your languages: Add, activate, and deactivate sitewide locales here. You can add a Page in a specific language if you have defined a locale for that page.',
  'activities.page.title': 'Page',
  'activities.page.desc': 'A Page is one content file within an Article. It represents one language and any links / workflows that are associated with an Article. It is written using Markdown syntax.',
  'activities.link.title': 'Hyperlink',
  'activities.link.desc': 'A Hyperlink will connect users to webpages you own, webpages of other organisations, and your telephone numbers.',
  'activities.release.title': 'Release',
  'activities.release.desc': 'A Release is a snapshot of all site content at one certain point of time. Use this for testing, prouduction, or backup purposes.',
  'activities.migration.title': 'Migration',
  'migration.create': 'Migrate data',
  'activities.migration.desc': 'Use a JSON file to perform a migration of a site.',
  'activities.templates.title': 'Templates',
  'activities.templates.desc': 'Use templates to customise and standardise a page default Markdown content and/or structure. Templates can be applied to new pages upon creation. Not implemented yet!',
  'activities.version.composer': 'Composer: build version {version}, build date {date}',
  'activities.version.core': 'Core: build version {version}, build date {date}',
  'dialog.about.title': 'About',
  'dialog.about.preamble': 'DigiExpress is based on open source projects:',
  'dialog.about.trademark': 'DigiExpress trademark and logo copyright-reserved by ReSys OÜ',
  'templates': 'Templates',
  'template.name': 'Name',
  'template.name.desc': 'User-given name for this template',
  'template.create': 'Create template',
  'template.edit': 'Edit Template',
  'template.type': 'Template type',
  'template.page': 'Page template',
  'template.page.desc': 'This template can be applied to a new page upon creation of that page.',
  'template.description': 'Write templates in Markdown to apply to your pages and content. Templates help speed up your development and unify your content structure.',
  'template.desc': 'Description',
  'template.description.desc': 'Additional information to help identify the use cases of this template',
  'template.delete': 'Delete template',
  'template.delete.message': 'This template will be permanently removed from the application',
  'template.newpage.none': 'None',
  'templates.templatesview.description': 'A new Page can be created from a Template',
  'templates.intro': 'Remember to use a Markdown Level 1 Heading (# My Heading 1) when composing your templates.',
  'services': 'Services',
  'services.create': 'Create service',
  'services.desc': 'Connect your forms and other integrations to your content with the Wrench and Dialob workflows',
  'services.add': 'Add a service',
  'services.change': 'Change existing services',
  'services.edit': 'Edit service',
  'services.technicalname': 'User given unique service name',
  'services.technicalname.description': 'Workflow descriptive name',
  'services.selected': 'Selected services',
  'services.modeselect.title': 'Configuration options',
  'services.modeselect.label': 'Select',
  'services.devmode.helper': 'Development mode: Service appears only in the development environment for testing and is not included in production releases.',
  'services.devmode.label': 'Development mode',
  'services.devmode.tooltip': 'Development mode',
  'services.disabledmode.label': 'Disabled mode',
  'services.disabledmode.helper': 'Disabled mode: Service does not appear on client portal',
  'services.disabledmode.tooltip': 'Disabled mode',
  'services.none.label': 'No configuration selected',
  'services.none.helper': 'Default mode: Service appears in production, is available ONLY to authenticated users, and is connected to ALL ARTICLES if no Article is selected',
  'services.none.tooltip': 'No special configuration',
  'services.anonmode.helper': 'Anonymous mode: Service appears for BOTH anonymous and authenticated users.',
  'services.anonmode.label': 'Anonymous mode',
  'services.anonmode.tooltip': 'Anonymous mode',
  'services.flowName': 'Flow name',
  'services.flowName.description': 'Flow name as defined in the Wrench',
  'services.formName': 'Dialob form name',
  'services.formName.description': 'Name of Dialob form used in service',
  'services.formTag': 'Dialob form tag',
  'services.formTag.description': 'Tag name for Dialob form used in service',
  'services.startdate': 'Start date and time',
  'services.startdate.description': 'Service activation date and time',
  'services.enddate': 'End date and time',
  'services.enddate.description': 'Service activation ending date and time',
  'services.delete': 'Delete service',
  'services.delete.desc': 'Deleting this service will permanently remove it from the application, and all associations with Articles/Pages will be lost.',
  'snack.article.createdMessage': 'Article created successfully',
  'snack.article.deletedMessage': 'Article deleted',
  'snack.article.editedMessage': 'Article changes saved',
  'snack.page.createdMessage': 'Page created successfully',
  'snack.page.deletedMessage': 'Page deleted',
  'snack.page.savedMessage': 'Page changes saved',
  'snack.page.missingTitle': 'Please add a title to {locale} in {articleName}',
  'snack.link.createdMessage': 'Link created successfully',
  'snack.link.deletedMessage': 'Link deleted',
  'snack.link.editedMessage': 'Link changes saved',
  'snack.link.addedMessage': 'Link added to article',
  'snack.link.removedMessage': 'Link removed from article',
  'snack.workflow.createdMessage': 'Service created successfully',
  'snack.workflow.deletedMessage': 'Service deleted',
  'snack.workflow.editedMessage': 'Service changes saved',
  'snack.workflow.addedMessage': 'Service added to article',
  'snack.workflow.removedMessage': 'Service removed from article',
  'snack.locale.createdMessage': 'Locale created successfully',
  'snack.locale.deletedMessage': 'Locale deleted',
  'snack.locale.editedMessage': 'Locale changes saved',
  'snack.locale.enabled': 'Locale enabled',
  'snack.locale.disabled': 'Locale disabled',
  'snack.template.createdMessage': 'Template created successfully',
  'snack.template.deletedMessage': 'Template deleted',
  'snack.template.editedMessage': 'Template changes saved',
  'snack.release.createdMessage': 'Release created successfully',
  'snack.release.deletedMessage': 'Release deleted',
  'snack.migration.createdMessage': 'Site data updated',
  'toolbar.search': 'Search',
  'toolbar.save': 'Save',
  'toolbar.stencil': 'theStencil',
  'toolbar.wrench': 'theWrench',
  'toolbar.menu': 'Menu',
  'toolbar.help': 'Help',
  'toolbar.services': 'Services',
  'toolbar.import': 'Import data',
  'toolbar.tasks': 'Tasks',
  'toolbar.about': 'About',
  'stencil.services.found.none': 'No services found',
  'link.type.internal': 'Internal',
  'link.type.external': 'External',
  'link.type.phone': 'Phone number',
  'link.search.title': 'Search links by value',
  'link.value': 'Link value',
  'sitelocale.label.select.alreadyDefined': 'Cannot add because this locale is already defined',
  'sitelocale.label.table.editLocaleValue': 'Edit locale value',
  'locales.label.table.title': 'Locale labels',
  'locales.label.title.helper': 'At least one language code (locale) + locale label value is required',
  'locales.label.table.value': 'Locale label values',
  'locales.enabledMessage': 'Enabled: Content for this locale will be displayed on the portal side',
  'locales.disabledMessage': 'Disabled: Content for this locale will be hidden from the portal side. Content can still be edited.',
  'transferlist.noItemsSelected': 'No items selected',
  'transferlist.search': 'Search',
  'transferlist.noSearchResults': 'No search results found',
  'explorer.tabs.search': 'Search',
  'explorer.tabs.articles': 'Articles',
  'explorer.tabs.links': 'Links',
  'explorer.tabs.services': 'Services',
  'imports': 'Imports',
  'imports.select': 'Select a file to import',
  'imports.import.action': 'Import selected',
  'article.order': 'Article order number',
  'article.order.view': 'View current Article ordering hierarchy',
  'article.select': 'Select Articles',
  'article.links.selectedlinks': 'Selected links',
  'article.composer.title': 'Create new Article',
  'article.composer.parent': 'Parent Article',
  'article.parent.helper': 'If a Parent article is selected, this article will live inside this parent, like a file inside a folder does.',
  'article.composer.parent.unselected': 'No parent article',
  'article.create': 'Create article',
  'article.name': 'Article name',
  'article.delete.title': 'Delete article',
  'article.delete.description': 'Deleting this article will remove it and its associated pages globally from the application.',
  'article.edit.title': 'Edit article',
  'article.edit.parent': 'Parent article',
  'article.edit.orderhelper': 'Three-digit number for ordering purposes',
  'article.devmode.helper': 'If Development mode is active, this article will only appear in the development environment for testing. It will not be included in production releases.',
  'article.devmode': 'Development mode',
  'articleservices': 'Article services: {name}',
  'articlelinks': 'Article links: {name}',
  'article.composer.orderhelper': 'The lower the number, the higher up this article will appear in your portal UI Topic Menu.  Example: 000 will be the first Topic menu item, while 999 will be the last.',
  'allarticles': 'Select all articles',
  'allarticles.individual': 'De-select all articles',
  'add.allarticles.link.help': 'This link will be added to (or removed from) all articles. Any previous link-article associations will be lost once this change has been applied',
  'add.allarticles.service.help': 'This service will be added to (or removed from) all articles. Any previous service-article associations will be lost once this change has been applied.',
  'button.create': 'Create',
  'button.add': 'Add',
  'button.disable': 'Continue and disable',
  'button.enable': 'Continue and enable',
  'button.remove': 'Continue and remove',
  'button.apply': 'Apply changes',
  'button.releasegraph': 'Graph',
  'button.view.all.locales': 'View locales',
  'button.view.all.releases': 'View releases',
  'button.view.all.templates': 'View templates',
  'links.message': 'Expand rows to view Link - Article associations',
  'links.searchAll': 'Search all links',
  'link.article.add.title': 'Add link to an Article',
  'link.article.select': 'Select Article',
  'link.type': 'Type',
  'link.url': 'URL / value',
  'link.locale.all': 'All locales',
  'link.content': 'Link URL / path',
  'link.composer.title': 'Create a new link',
  'link.composer.descriptionlabel': 'Description',
  'link.composer.descriptionhelper': 'Text that the user will see',
  'link.composer.valuehelper': 'URL / path of link (http://www.example.com)',
  'link.edit.title': 'Edit link',
  'link.delete.title': 'Delete link',
  'link.delete': 'Deleting this link will permanently remove it from the application, and all associations with Articles/Pages will be lost.',
  'link.removepage.title': 'Remove this link?',
  'link.removepage': 'Removing the link only removes its association with this article. To delete this item permanently, click the Delete icon.',
  'link.options': 'Link options',
  'link.options.add': 'Add links to article',
  'resource.edit.links': 'Edit links',
  'links.change': 'Change existing links',
  'link.create': 'Create new link',
  'link.devmode.helper': 'If Development mode is active, this link will only appear in the development environment for testing. It will not be included in production releases.',
  'link.devmode': 'Development mode',
  'locale.create': 'Create locale',
  'locale.disable.title': 'Disable this locale?',
  'locale.enable.title': 'Enable this locale?',
  'locale.disable': 'Any Pages using this locale will be hidden on the UI. Pages can still be edited.',
  'locale.enable': 'All Pages using this locale will be displayed on the UI.',
  'locale.composer.title': 'Create a new locale',
  'locale.composer.placeholder': 'Two-letter language code',
  'locale.composer.helper': 'Two-letter language codes designate the content language. Common examples: en = English, fi = Finnish, sv = Swedish',
  'locale.overview': 'Locale usage overview',
  'locales.overview.description': 'Manage the languages of your site content. Disable locales to hide all content associated with that language from your site',
  'locales.content': 'Page in this locale has content',
  'locales.nocontent': 'Page in this locale has no content',
  'locales.nopage': 'There is no page for this locale in this Article',
  'locales.label.table.locale': 'Language code',
  'newpage.title': 'Create a new page',
  'newpage.info': 'A page consists of localised content and must be associated with an Article.',
  'newpage.article.info': 'Confirm creation of page for: {article} with locale: {locale}',
  'page.create': 'Create page',
  'page.delete.dialog.title': 'Delete a page from article:',
  'page.delete.description': 'The selected page and all of its content will be permanently removed from your site',
  'pages.save': 'Save pages',
  'pages.add': 'Add a page',
  'pages.change': 'Change a page locale',
  'pages.select.locale': 'Edit localised page content',
  'pages.select.locale.edit.desc': 'Select two languages to enable side-by-side editing in one tab.',
  'pages.edit.language1': 'Edit this language',
  'pages.edit.language2': 'Edit this language side-by-side',
  'pages.edit.currentlyEditing.language2': 'Editing side-by-side',
  'pages.edit.currentlyEditing.language1': 'Editing this language',
  'pages.change.info': 'Select a page from this Article and enter a new value for its locale.',
  'pages.change.devmode': 'Change a page development mode',
  'pages.change.devmode.info': 'Select a page from this Article and change its development mode.',
  'pages.devmode.helper': 'If Development mode is active, this page will only appear in the development environment for testing. It will not be included in production releases.',
  'pages.devmode': 'Development mode',
  'pages.delete': 'Delete a page',
  'pages.delete.message': 'Select a page to delete from this Article.',
  'pages.options': 'Page options',
  'pages.edit.selectpage': 'Select page',
  'pages.edit.selectTargetLocale': 'Select target locale',
  'release.create': 'Create release',
  'release.composer.title': 'Create a new release',
  'release.composer.label': 'Tag Name',
  'release.composer.note': 'Note',
  'release.composer.helper': 'Optional additional information for future reference',
  'release.desc': 'View all releases and download all site content in JSON format. For more detailed information on specific releases and their content, view the Graph.',
  'release.delete.title': 'Delete release',
  'release.delete.desc': 'Delete this release permanently from site data?',
  'releases.view.note': 'Notes',
  'releases.view.tag': 'Name',
  'releases.view.created': 'Created',
  'releases.view.download': 'JSON download',
  'buttons.create': 'Create',
  'buttons.apply': 'Apply',
  'buttons.delete': 'Delete',
  'buttons.copy': 'Copy',
  'button.compose': 'Compose',
  'buttons.download': 'Download',
  'content.loading': 'Loading',
  'explorer.tabs.flows': 'Flows',
  'explorer.tabs.decisions': 'Decisions',
  'explorer.active.branch': 'Active branch: {name}',
  'explorer.active.branch.default': 'Default',
  'activities.flows.title': 'Workflow',
  'activities.flows.desc': 'A a sequence of tasks which are defined by using simple configuration language.',
  'activities.decisions.title': 'Decisions',
  'activities.decisions.desc': 'A decision table that can be used to make decisions based on input data.',
  'activities.services.title': 'Services',
  'activities.services.desc': 'A piece of Java or Groovy code that is embedded inside of a flow as a task.',
  'activities.releases.title': 'Releases',
  'activities.releases.desc': 'A Release is a snapshot of all site content at one certain point of time.',
  'activities.releases.desc.additional': 'Each Release can be downloaded to be used for production or backup purposes, or can be branched for further editing. This will replace all current assets so make sure any changes are saved.',
  'activities.releases.view': 'View all releases',
  'activities.releases.graph': 'Graph',
  'activities.compare.title': 'Compare',
  'activities.compare.desc': 'Compare two releases to see what has changed between them.',
  'activities.compare.view': 'Compare',
  'activities.templates.view': 'View all templates',
  'activities.debug.title': 'Debug',
  'activities.debug.desc': 'Simulate execution of an asset. Can be done via form input, JSON input, or by using a CSV file.',
  'activities.debug.view': 'Simulate',
  'activities.assets.saveSuccess': 'Saved asset: {name}',
  'programs.error.title': 'Program error',
  'programs.warning.title': 'Program warning',
  'flows': 'Flows',
  'migrations.title': 'Migration',
  'migrations.create': 'Perform migration',
  'migrations.select': 'Select tag.json file',
  'flows.edit.title': 'Edit flow',
  'flows.copyas.title': 'Copy flow as',
  'flows.delete.title': 'Delete flow',
  'flows.delete.error.title': 'Failed to delete flow',
  'flows.delete.content': 'Are you sure you want to delete FLOW: {name}?',
  'flows.deleted.message': 'Deleted FLOW: {name}',
  'flows.simulate.title': 'Debug the flow',
  'flows.composer.title': 'Create new FLOW',
  'flows.composer.copyTitle': 'Copy FLOW as',
  'flows.composer.createdMessage': 'Created FLOW: {name}',
  'flows.composer.copiedMessage': 'Copied FLOW {name} as: {newName}',
  'flows.composer.errorsTitle': 'Failed to create FLOW',
  'flows.composer.assetName': 'Unique name for the FLOW',
  'flows.autocomplete.task.create': 'Create new asset',
  'flows.autocomplete.task.link': 'Link selected asset',
  'flows.autocomplete.task.searchField': 'Search for asset...',
  'flows.autocomplete.task.searchPlaceholder': 'Asset name or description',
  'flows.autocomplete.task.selectType': 'Select asset type to link',
  'flows.autocomplete.task.searchHelper': 'Matches asset name and description',
  'flows.autocomplete.task.searchResults': 'Search results',
  'flows.autocomplete.task': 'Add existing asset or create new one',
  'flows.autocomplete.task.snackbar.created': 'Created new {type}: {name}',
  'flows.autocomplete.task.snackbar.creating': 'Creating new {type}: {name}',
  'flows.graph.show': 'Show flow graph',
  'flows.graph.hide': 'Hide flow graph',
  'services.searchAll': 'Search all services',
  'services.edit.title': 'Edit service',
  'services.copyas.title': 'Copy service as',
  'services.delete.title': 'Delete service',
  'services.delete.error.title': 'Failed to delete SERVICE',
  'services.delete.content': 'Are you sure you want to delete SERVICE: {name}?',
  'services.deleted.message': 'Deleted SERVICE: {name}',
  'services.simulate.title': 'Debug the service',
  'services.composer.title': 'Create new SERVICE',
  'services.composer.copyTitle': 'Copy SERVICE as',
  'services.composer.createdMessage': 'Created SERVICE: {name}',
  'services.composer.copiedMessage': 'Copied SERVICE {name} as: {newName}',
  'services.composer.errorsTitle': 'Failed to create SERVICE',
  'services.composer.assetName': 'Unique name for the SERVICE',
  'decisions.name': 'Name',
  'decisions.desc': 'Description',
  'decisions.simulate.title': 'Debug the decision',
  'decisions.hitpolicy': 'Hit-policy',
  'decisions.edit.title': 'Edit decision',
  'decisions.copyas.title': 'Copy decision as',
  'decisions.delete.error.title': 'Failed to delete DECISION',
  'decisions.delete.title': 'Delete decision',
  'decisions.delete.content': 'Are you sure you want to delete DECISION: {name}?',
  'decisions.deleted.message': 'Deleted DECISION: {name}',
  'decisions.table.hitpolicy': 'Matches',
  'decisions.table.options': 'Options',
  'decisions.composer.title': 'Create new DECISION',
  'decisions.composer.copyTitle': 'Copy DECISION as',
  'decisions.composer.createdMessage': 'Created DECISION: {name}',
  'decisions.composer.copiedMessage': 'Copied DECISION {name} as: {newName}',
  'decisions.composer.errorsTitle': 'Failed to create DECISION',
  'decisions.composer.assetName': 'Unique name for the DECISION',
  'decisions.toolbar.addInputColumn': 'Add input column',
  'decisions.toolbar.addOutputColumn': 'Add output column',
  'decisions.toolbar.addRow': 'Add row',
  'decisions.toolbar.csvDownload': 'Download CSV, with separator \';\'',
  'decisions.toolbar.csvUpload': 'Upload CSV, with separator \';\'',
  'decisions.toolbar.nameAndHitpolicy': 'Name and hit-policy',
  'decisions.toolbar.organize.rows.columns': 'Organize rows and columns',
  'decisions.toolbar.organize.action': 'Select action',
  'decisions.toolbar.organize.action.helper': 'Move column or row based on name/index',
  'decisions.toolbar.organize.action.expression': 'Select expression',
  'decisions.toolbar.organize.action.expression.column': 'Select column',
  'decisions.toolbar.organize.action.deleteColumn': 'Delete whole column',
  'decisions.toolbar.organize.action.deleteRow': 'Delete whole row',
  'decisions.toolbar.organize.action.deleteRow.contents': 'Row contents',
  'decisions.toolbar.organize.action.move.from.column': 'Column to move',
  'decisions.toolbar.organize.action.move.from.row': 'Row to move',
  'decisions.toolbar.organize.action.move.to.column': 'New Position',
  'decisions.toolbar.organize.action.move.to.row': 'New Position',
  'decisions.table.inputs.title': 'Matching rules',
  'decisions.table.outputs.title': 'Results',
  'decisions.header.dialog.title': 'Decision table: {name}, column: {column}',
  'decisions.cells.dialog.title': 'Decision table: {name}, column: {column}, value: {value}',
  'decisions.cells.newvalue.boolean': 'Enter new value',
  'decisions.cells.newvalue.boolean.helper': 'Select boolean value',
  'decisions.cells.newvalue.boolean.empty': 'No value selected',
  'decisions.cells.newvalue.date.operator': 'Operator',
  'decisions.cells.newvalue.date.start': 'Start date',
  'decisions.cells.newvalue.date.end': 'End date',
  'decisions.cells.newvalue.date.value': 'Date',
  'decisions.cells.newvalue.number.comparisonType': 'Comparison',
  'decisions.cells.newvalue.number.comparisonTypeEmpty': 'Comparison not selected',
  'decisions.cells.newvalue.number.comparisonValue': 'New numerical value',
  'decisions.cells.newvalue.number.comparisonToRange': 'Change to range',
  'decisions.cells.newvalue.number.rangeStart': 'Start',
  'decisions.cells.newvalue.number.rangeEnd': 'End',
  'decisions.cells.newvalue.number.value': 'New numerical value',
  'decisions.cells.newvalue.number.rangeIncluded': 'Included',
  'decisions.cells.newvalue.number.rangeToComparison': 'Change to comparison',
  'decisions.cells.newvalue.string.comparisonType': 'Comparison',
  'decisions.cells.newvalue.string.addValue': 'Add new value',
  'decisions.cells.newvalue.string.available': 'Available values',
  'decisions.cells.newvalue.string.selected': 'Selected values',
  'decisions.cells.newvalue.string.empty': 'Comparison not selected',
  'decisions.cells.newvalue.clear': 'Clear current value',
  'decisions.valueSet': 'Define value set',
  'decisions.valueSet.description': 'Value sets can be used to define a predetermined set of values for any input',
  'decisions.valueSet.add': 'Add to value set',
  'decisions.valueSet.remove': 'Remove from value set',
  'decisions.valueSet.current': 'Current value set',
  'decisions.valueSet.empty': 'Value set is empty',
  'dt.header.name': 'Name',
  'dt.header.delete': 'Delete',
  'dt.header.expression': 'Expression',
  'dt.header.dataType': 'Data type',
  'dt.header.script': 'Script',
  'decisions': 'Decisions',
  'program.status.DEPENDENCY_ERROR': 'Dependency Errors',
  'program.status.UP': 'Program is UP',
  'program.status.AST_ERROR': 'Syntax errors',
  'program.status.PROGRAM_ERROR': 'Compiler errors',
  'package.explorer.flows': 'flows',
  'package.explorer.servicetasks': 'services',
  'package.explorer.decisiontables': 'decisions',
  'dialog.addtype.title': 'Add new asset',
  'dialog.addtype.button.cancel': 'Cancel',
  'dialog.addtype.button.confirm': 'Create',
  'dialog.addtype.error.unique': 'Asset name must be unique!',
  'dialog.addtype.error.filled': 'Asset name must be filled!',
  'dialog.addtype.input.serviceType': 'Asset type',
  'dialog.addtype.input.name': 'Asset name',
  'dialog.copyas.title': 'Copy asset',
  'dialog.copyas.button.cancel': 'Cancel',
  'dialog.copyas.button.confirm': 'Copy',
  'dialog.copyas.input.from': 'Copy from',
  'dialog.copyas.input.to': 'New asset name',
  'dialog.copyas.error.unique': 'Asset name must be unique!',
  'dialog.copyas.error.filled': 'Asset name must be filled!',
  'dialog.save.title': 'Save asset: {name}',
  'dialog.save.content': 'Are you sure you want to save?',
  'dialog.save.errors': 'Failed to save asset',
  'dialog.save.button.cancel': 'Cancel',
  'dialog.save.button.confirm': 'Save',
  'release.delete.content': 'Are you sure you want to delete release: {name}',
  'release.delete.error.title': 'Error deleting release',
  'release.deleted.message': 'Release {name} deleted',
  'releases.composer.createdMessage': 'Created new release {name}',
  'releases.view.action': 'Action',
  'releases.composer.title': 'Create new release',
  'releases.composer.assetName': 'Release name',
  'releases.composer.assetDesc': 'Release description',
  'releases.composer.errorsTitle': 'Error while creating release',
  'releases.table.title': 'Releases and Branches',
  'releases.table.column.name': 'Name',
  'releases.table.column.message': 'Message',
  'releases.table.column.created': 'Created',
  'releases.table.name': 'All releases',
  'releases.add.error.unique': 'Release must be unique!',
  'releases.add.error.filled': 'Release name must be filled!',
  'releases.add.input.name': 'Name',
  'releases.add.input.msg': 'Comment',
  'releases.add.button.create': 'Create Release',
  'releases.button.compare': 'Compare',
  'releases.button.branch': 'Create new branch',
  'releases.button.checkout': 'Checkout',
  'releases.button.release': 'Release',
  'releases.button.details': 'View release assets',
  'releases.default.name': 'default',
  'releases.default.note': 'This is the default branch that you can go back to',
  'releases.latest.name': 'latest',
  'releases.latest.note': 'These are current assets with the latest changes that can be released',
  'releases.details.title': 'Release assets: {name}',
  'branch.delete.title': 'Delete branch',
  'branch.delete.content': 'Are you sure you want to delete branch: {name}',
  'branch.delete.error.title': 'Error deleting branch',
  'release.branch.creating': 'Creating new branch: {name}',
  'release.branch.created': 'Created new branch: {name}',
  'release.branch.deleting': 'Deleting branch: {name}',
  'release.branch.deleted': 'Deleted branch: {name}',
  'release.branch.checkout': 'Checked out to branch: {name}',
  'debug.toolbar.options': 'Options',
  'debug.toolbar.selectAsset': 'Select asset to debug',
  'debug.toolbar.inputCsv': 'Define input data as a CSV',
  'debug.toolbar.inputForm': 'Define input data as a FORM',
  'debug.toolbar.inputJson': 'Define input data as a JSON',
  'debug.toolbar.execute': 'Execute',
  'debug.toolbar.noAsset': 'Select asset from options',
  'debug.toolbar.openAsset': 'Open',
  'debug.toolbar.download': 'Download results as CSV',
  'debug.input.noAsset': 'There is no ASSET selected',
  'debug.input.form': 'Debug using FORM',
  'debug.input.formTitle': 'Define inputs',
  'debug.input.form.invalid.integer': 'Value must be an integer',
  'debug.input.form.invalid.number': 'Value must be a number',
  'debug.input.form.invalid.range': 'Value must be in the specified range',
  'debug.input.json': 'Debug using JSON',
  'debug.input.jsonTitle': 'Define JSON input',
  'debug.input.csvUpload': 'Debug using CSV',
  'debug.input.csvFile': 'Upload CSV FILE',
  'debug.input.csvFileTitle': 'Upload CSV file - semicolon-delimited (;)',
  'debug.input.csvFileOrText': 'Or paste CSV contents - semicolon-delimited (;)',
  'debug.inputs.fieldName': 'Field Name',
  'debug.inputs.fieldValue': 'Field Value',
  'debug.select.title': 'Select asset to debug',
  'debug.select.assetType': 'Asset type to filter',
  'debug.select.searchField': 'Asset name to search',
  'debug.select.searchHelper': 'Search matches asset name or description',
  'debug.select.searchPlaceholder': 'Keyword to search',
  'debug.select.searchResults': 'Found assets',
  'debug.select.confirm': 'Select',
  'debug.inputs.format': 'Asset input format: {type}',
  'debug.asset.select.label': 'Asset to debug',
  'debug.asset.select.clear': 'Clear run data',
  'debug.asset.select.execute': 'Execute asset',
  'debug.asset.execute.inputs': 'Debug inputs',
  'debug.asset.execute.errors': 'Execution errors',
  'debug.asset.execute.outputs.dt.json': 'Matched row(s)',
  'debug.asset.execute.outputs.dt.rejects': 'Rejected row(s)',
  'debug.asset.execute.outputs.dt.rejects.order': 'Execution order',
  'debug.asset.execute.outputs.flow.step': 'Step name: {name}, status: {status}',
  'debug.csv.row': 'Data row: {row}',
  'debug.csv.download': 'Download results as CSV',
  'debug.csv.download.delimiter': 'Choose a delimiter for the CSV file',
  'debug.csv.download.delimiter.semicolon': 'Semicolon (;)',
  'debug.csv.download.delimiter.comma': 'Comma (,)',
  'debug.csv.download.options': 'Export options',
  'debug.csv.download.wrap': 'Wrap cells containing delimiters with quotes',
  'compare.tip': 'Select releases to compare below. Base is the starting point of the comparison, and target is the release that will be compared to the base.',
  'compare.base': 'Select base release',
  'compare.target': 'Select target release',
  'compare.dialog.title': 'Comparing releases {base} and {target}',
  'compare.dialog.line': 'Inline',
  'compare.dialog.side': 'Side-by-side',
  'menu.feedbackAllTasks': 'All feedback',
  'menu.activities': 'Activities',
  'feedback.all': 'All feedback',
  'feedback.none': 'No feedback available',
  'feedback.search': 'Search',
  'feedback.search.placeholder': 'Feedback, process, or task id',
  'feedback.search.filter.category': 'Filter by category',
  'feedback.search.filter.subCategory': 'Filter by sub-category',
  'feedback.filter.selectNone': 'None',
  'queues.all': 'Queues',
  'consumers.all': 'Consumers',
  'queue.config.appId': 'App id',
  'queue.config.none': 'Loading',
  'queue.config.consumerName': 'Consumer name',
  'queue.config.routingKey': 'Routing key',
  'queue.config.consumerStatus': 'Status',
  'queue.config.comment': 'Comment',
  'queue.config.consumerId': 'Id',
  'queue.config.qualifiedJavaName': 'Tech name',
  'queue.config.queueName': 'Queue name',
  'queue.config.createdAt': 'Created at',
  'queue.config.createdBy': 'Created by',
  'queue.all_deliveries.title': 'All deliveries',
  'queue.all_deliveries.created': 'Created',
  'queue.all_deliveries.consumerComment': 'Comment',
  'queue.all_deliveries.status': 'Status',
  'queue.all_deliveries.messageId': 'Message id',
  'queue.all_deliveries.consumerId': 'Consumer id',
  'queue.all_messages.title': 'All messages',
  'queue.all_messages.routingKey': 'Routing key',
  'queue.all_messages.messageId': 'Message id',
  'queue.all_messages.bodyId': 'Body id',
  'queue.all_messages.bodyType': 'Body type',
  'queue.all_messages.status': 'Status',
  'queue.all_messages.body': 'Body',
  'queue.all_messages.created': 'Created',
  'menu.messages': 'Messages',
  'menu.deliveries': 'Deliveries',
  'explorer.pages': 'Pages',
  'articles.searchAll': 'Search all articles',
  'eveli.error.general': 'Ooops, we have encountered an error!',
  'eveli.error.notFound': 'Ooops, the thing you are looking for is not found!',
  'eveli.error.backToHome': 'Go back to our home page'
}