export const fi = {
  'document.title': 'DigiExpress',
  'booleanValue.true': 'Kyllä',
  'booleanValue.false': 'Ei',
  'eveli.textSeparatorColon': ': ',
  'eveli.noValueIndicator': '--',
  'eveli.permissions.none.title': 'Joitain meni väärin!',
  'eveli.permissions.none.desc1': 'Sinulla ei ole oikeuksia tämän sovelluksen käyttöön',
  'eveli.permissions.none.desc2': 'Ota yhteyttä teidän käyttöoikeuksista vastaan henkilöön',
  'tasksView.title': 'Tehtävät',
  'tasksTableHeader.taskName': 'Tehtävän nimi',
  'tasksTableHeader.category': 'Tyyppi',
  'tasksTableHeader.status': 'Tila',
  'tasksTableHeader.dueDate': 'Eräpäivä',
  'tasksTableHeader.priority': 'Prioriteetti',
  'tasksTableHeader.assigned': 'Käsitteljä',
  'tasksTableAction.editTask': 'Muokkaa tehtävää',
  'tasksTableAction.deleteTask': 'Poista tehtävää',
  'taskPriority.low': 'Ei kiireellinen',
  'taskPriority.normal': 'Normaali',
  'taskPriority.high': 'Kiire',
  'taskDialog.priority': 'Prioriteetti',
  'taskDialog.subject': 'Aihe',
  'taskDialog.description': 'Asiakkaan tiedot',
  'taskDialog.dueDate': 'Eräpäivä',
  'taskDialog.assignedTo': 'Käsittelijän rooli',
  'taskDialog.assignedUser': 'Käsittelijä',
  'taskDialog.status': 'Tila',
  'taskDialog.task': 'Tehtävä',
  'taskDialog.category': 'Tyyppi',
  'taskDialog.source': 'Lähde',
  'taskDialog.additionalInfo': 'Lisätieto',
  'task.priority.low': 'Ei kiireellinen',
  'task.priority.normal': 'Normaali',
  'task.priority.high': 'Kiire',
  'task.status.new': 'Uusi',
  'task.status.open': 'Käsittelyssä',
  'task.status.completed': 'Valmis',
  'task.status.rejected': 'Ei käsittelyä',
  'task.status.transferred': 'Siirretty',
  'task.status.delegated': 'Delegoitu',
  'task.status.waiting': 'Odottaa',
  'task.form.review': 'Avaa lomake',
  'task.form.feedback.manage': 'Hallinnoi palautetta',
  'task.form.feedback.updated': 'Palautteen päivitys onnistui!',
  'task.created': 'Luotu',
  'task.updated': 'Päivitetty',
  'comments': 'Kommentit',
  'task.comments.external.createTask': 'Luo tehtävä ennen ulkoisten kommenttien lisäämistä',
  'task.comments.internal.createTask': 'Luo tehtävä ennen sisäisten kommenttien lisäämistä',
  'task.attachments.createTask': 'Luo tehtävä ennen liitteiden lataamista',
  'task.comments.external.added': 'Sisäinen kommentti tallletettu',
  'task.feedback.publishedSaved': 'Palautemuutokset tallennettu',
  'task.comments.internal.added': 'Kommentti lisätty',
  'internalComments': 'Sisäiset kommentit',
  'externalComments': 'Asiakas viestit',
  'comment.store': 'Tallenna',
  'comment.add': 'Lisää kommentti',
  'comment.addInternal': 'Lisää sisäinen kommentti',
  'comment.addExternal': 'Viesti/palaute asiakkaalle',
  'comment.reply': 'Vastaa',
  'taskButton.addTask': 'Lisää tehtävä',
  'taskButton.refresh': 'Tarkista uudet tehtävät',
  'taskButton.accept': 'Hyväksy',
  'taskButton.cancel': 'Takaisin',
  'table.body.emptyDataSourceMessage': 'Ei dataa',
  'table.body.filterRow.filterTooltip': 'Suodatin',
  'table.body.deleteTooltip': 'Poista',
  'table.body.editRow.deleteText': 'Haluatko varmasti poistaa tämän tehtävän?',
  'table.body.editRow.cancelTask': 'Peruuta',
  'table.body.editRow.saveTask': 'Tallenna',
  'table.header.actions': 'Toiminnot',
  'table.pagination.labelDisplayedRows': '{from}-{to} / {count}',
  'table.pagination.labelRowsPerPage': 'Riviä per sivu:',
  'table.pagination.firstPage': 'Ensimmäinen sivu',
  'table.pagination.previousPage': 'Edellinen',
  'table.pagination.nextPage': 'Seuraava',
  'table.pagination.lastPage': 'Viimeinen sivu',
  'table.toolbar.search': 'Etsi',
  'table.toolbar.showColumnsTitle': 'Näytä sarakkeet',
  'table.toolbar.addRemoveColumns': 'Lisää tai poista sarakkeita',
  'taskLink.title': 'Lomake',
  'taskLink.button.open': 'Asiakkaan antamat tiedot',
  'taskLink.pdf.open': 'PDF',
  'explorer.title': 'Julkinen viesti',
  'explorer.login': 'Kirjaudu sisään',
  'locale.fi': 'Suomi',
  'locale.sv': 'Ruotsi',
  'locale.en': 'Englanti',
  'app.logout': 'Kirjaudu ulos',
  'app.login': 'Kirjaudu sisään',
  'app.feedback': 'Palaute',
  'main.articles.all': 'Kaikki Artikkelit',
  'main.links.all': 'Kaikki Linkit',
  'main.services.all': 'Kaikki Palvelut',
  'main.flows.all': 'Kaikki  Palveluprosessit',
  'main.debug': 'Testaa',
  'main.compare': 'Vertaa',
  'main.decisions.all': 'Kaikki Päätöstaulut',
  'menu.dashboard': 'Kojelauta',
  'menu.profile': 'Käyttäjän profiili',
  'menu.tasks': 'Tehtävät',
  'menu.evaluations': 'Kyselyt',
  'menu.forms': 'Dialob',
  'menu.queues': 'Queues',
  'menu.users': 'Käyttäjät',
  'menu.help': 'Ohjeet',
  'menu.flow': 'theWrench',
  'menu.processes': 'Monitorointi',
  'menu.reports': 'Raportointi',
  'menu.workflows': 'Stencil palvelut',
  'menu.logout': 'Kirjaudu ulos',
  'menu.workflowTags': 'Versiointi',
  'menu.publications': 'Julkaisut',
  'menu.services': 'Palvelut',
  'menu.content': 'Stencil',
  'menu.calendar': 'Kalenteri',
  'menu.feedback': 'Palaute',
  'menu.compose': 'Luo uusi',
  'menu.pages': 'Sivut',
  'menu.articles': 'Artikkelit',
  'menu.links': 'Linkit',
  'menu.locales': 'Kielet',
  'menu.migrations': 'Migraatiot',
  'menu.templates': 'Valmis pohjat',
  'menu.flows': 'Palveluprosessit',
  'menu.decisions': 'Päätöstaulut',
  'menu.debug': 'Testaa',
  'menu.releases': 'Versiot',
  'menu.compare': 'Vertaile',
  'front.intro.title': 'Tervetuloa!',
  'profile.title': 'Käyttäjän profiili',
  'profile.user.name': 'Nimi:',
  'profile.user.email': 'Sähköposti:',
  'profile.user.role': 'Rooli:',
  'profile.user.phone': 'Puhelin:',
  'profile.app.version': 'Sovellusversio:',
  'button.cancel': 'Peruuta',
  'button.confirmDelete': 'Poista',
  'button.delete': 'Poista tämä palaute',
  'button.delete.template': 'Poista tämä valmispohja',
  'button.delete.link': 'Poista tämä linkki',
  'button.delete.article': 'Poista tämä artikkeli',
  'button.delete.page': 'Poista tämä sivu',
  'button.unpublish': 'Poista avoin julkaisu',
  'button.update': 'Päivitä',
  'button.publish': 'Julkaise',
  'button.accept': 'Hyväksy',
  'button.edit': 'Avaa',
  'button.close': 'Sulje',
  'button.reject': 'Hylkää',
  'button.send': 'Lähetä',
  'button.save': 'Save',
  'button.dismiss': 'Sulje',
  'button.editRoles': 'Muokkaa',
  'button.select': 'Valita',
  'button.startBatch': 'Start batch',
  'error.minTextLength': 'Annetun arvon pitää olla vähintään {minLength} merkkiä',
  'error.maxTextLength': 'Annetun arvon tulee olla enintään {max} merkkiä pitkä',
  'error.valueRequired': 'Vaaditaan',
  'error.title': 'Virhe!',
  'error.dialob.session': 'Lomaketta ei voida aukaista juuri nyt. Yritä uudelleen myöhemmin',
  'error.errorLoadingData': 'Error during data loading',
  'error.unauthorized.title': 'Käyttöoikeutesi ovat puutteelliset',
  'error.unauthorized.text': 'Ota yhteyttä IT-palveluihin lähettämällä tukipyyntö Tiketin kautta -> Jätä tukipyyntö -> Kirjautumisongelma.',
  'error.unauthorizedAccess': 'Käyttöoikeutesi ovat puutteelliset',
  'error.dataAccess': 'Virhe toiminnassa',
  'error.statusOpenError': 'Required when status is open',
  'error.workflowCreation': 'Virhe konfiguroinnissa, tarkista nimen yksilöllisyys',
  'table.body.addTooltip': 'Lisää',
  'table.body.editTooltip': 'Avaa',
  'table.body.editRow.deleteMessage': 'Halutko varmasti poistaa tämän?',
  'workflowTable.title': 'Kokoonpano',
  'workflowTableHeader.name': 'Nimi',
  'workflowTableHeader.formName': 'Lomake',
  'workflowTableHeader.flowName': 'Prosessi',
  'workflowTableHeader.updated': 'Päivitetty',
  'workflowTable.addButton': 'Lisää uusi',
  'workflowTable.editButton': 'Muokka',
  'workflow.dialogTitle': 'Työnkulku',
  'workflow.name': 'Nimi',
  'workflow.form.formName': 'Lomakkeen nimi',
  'workflow.form.formTag': 'Lomakkeen versio',
  'workflow.flowName': 'Prosessi',
  'processTable.title': 'Työt',
  'processTableHeader.workflow': 'Tyyppi',
  'processTableHeader.user': 'Käyttäjä',
  'processTableHeader.status': 'Tila',
  'processTableHeader.created': 'Luotu',
  'processTableHeader.questionnaireId': 'Lomake',
  'processTableHeader.taskRef': 'Task reference',
  'process.status.ANSWERED': 'Lähetetty',
  'process.status.CREATED': 'Luotu',
  'process.status.ANSWERING': 'Keskeneräinen',
  'process.status.IN_PROGRESS': 'Käsittelyssä',
  'process.status.WAITING': 'Odottaa',
  'process.status.COMPLETED': 'Valmis',
  'process.status.REJECTED': 'Hylätty',
  'comment.button': 'Anna palautetta',
  'comment.title': 'Anna palautetta',
  'comment.form.email': 'Sähköposti',
  'comment.form.feedbackType': 'Tyyppi',
  'comment.form.body': 'Viesti',
  'comment.type.general': 'Anna palautetta',
  'comment.type.propose': 'Ehdota uutta palvelua',
  'comment.type.contact': 'Ota yhteyttä',
  'comment.submitted.success': 'Kiitos palautteesta!',
  'comment.submitted.failure': 'Lähetys epäonnistui',
  'spoTasksTableHeader.taskName': 'Nimi',
  'spoTasksTableHeader.category': 'Tyyppi',
  'spoTasksTableHeader.status': 'Tila',
  'spoTasksTableHeader.priority': 'Prioriteetti',
  'spoTasksTableHeader.dueDate': 'Eräpäivä',
  'spoTasksTableHeader.assigned': 'Rooli',
  'spoTasksTableHeader.assignedUser': 'Käsittelijä',
  'spoTasksTableHeader.created': 'Luotu',
  'spoTasksTableHeader.clientName': 'Asiakas',
  'spoTasksTableHeader.additionalInfo': 'Info',
  'taskDialog.clientIdentificator': 'Asiakas',
  'taskDialog.assignedUserEmail': 'Käyttäjän sähköposti',
  'task.editRoles': 'Tehtäväryhmät',
  'Questionnaire': 'Lomake',
  'Manual': 'Manuaalinen',
  'Protected': 'Suojattu',
  'Normal': 'Normaali',
  'Represented': 'Valtuutetu',
  'CustomerCreated': 'Asiakas luotu',
  'Internal': 'Sisäinen',
  'task.role.assignedAllUsers': 'Kaikki käyttäjät',
  'task.feedback.published': 'Julkaistu vastaus',
  'confirm.close.title': 'Vahvistus vaaditaan',
  'confirm.unsavedChanges': 'Tallentamattomat muutokset menetetään. Haluatko jatkaa?',
  'task.statistics.statusCount': 'Tilan mukaan',
  'task.statistics.priorityCount': 'Prioriteetin mukaan',
  'task.statistics.daily': 'Päivittäin',
  'task.statistics.overdue': 'Myöhässä',
  'feedback.button': 'Lähetä palautetta',
  'feedback.thanks': 'Kiitos palautteestasi!',
  'feedback.create.title': 'Luo vastine asiakkaan palautteeseen',
  'feedback.title': 'Vastine asiakkaan palautteesen',
  'feedback.update.title': 'Editoi vastinetta asiakkaan palautteelle',
  'feedback.description': 'Kuvaus',
  'feedback.name': 'Nimesi',
  'feedback.sendScreenshot': 'Lähetä ruutukaappaus',
  'feedback.close': 'Peru',
  'feedback.send': 'Lähetä',
  'feedback.taskReferenceId': 'Tehtävän viite',
  'feedback.taskReferenceId.short': 'Task Ref',
  'feedback.taskId': 'Tehtävän ID',
  'feedback.mainCategory': 'Aihe',
  'feedback.subCategory': 'Tarkempi aihealue',
  'feedback.feedbackValue': 'Asiakkaan palaute',
  'feedback.customerTitle': 'Palautteen otsikko',
  'feedback.myReply': 'Vastaa asiakkaalle',
  'feedback.noFeedback.info1': 'Ei vastinettta palautteelle!',
  'feedback.noFeedback.info2': 'Please send an external comment to customer, then you can publish the external comment.',
  'feedback.customerFeedback': 'Asikkaan palaute',
  'feedback.customerApprovals': 'Asiakkaan suostumukset',
  'feedback.sourceTaskId': 'Pää tehtävän tunnus',
  'feedback.formName': 'Lomakkeen nimi',
  'feedback.dateReceived': 'Saapunut asiakkaalta',
  'feedback.createdBy': 'Luonut',
  'feedback.updatedBy': 'Päivittänyt',
  'feedback.updated': 'Viimeisin päivitys',
  'feedback.notPublished': 'Tätä vastinetta ei ole julkaistu',
  'feedback.isPublished': 'Tämä vastine on julkaistu',
  'feedback.delete.confirmTitle': 'Poista palaute?',
  'feedback.delete.confirmText': 'Haluatko varmasti poistaa tämän palautteen?',
  'feedback.main_topic.youthservice': 'Nuorisopalvelu',
  'help.title': 'Ohjeet',
  'attachmentView.title': 'Liitetiedostot',
  'attachmentTableHeader.size': 'Koko',
  'attachmentTableHeader.updated': 'Päivitetty',
  'attachmentTableHeader.created': 'Luotu',
  'attachmentTableHeader.name': 'Aihe',
  'attachmentButton.addAttachment': 'Lisää tiedosto',
  'attachmentButton.downloadAttachment': 'Lataa tiedosto',
  'attachmentButton.deleteAttachment': 'Poista tiedosto',
  'attachment.uploadOk': 'Tiedosto {fileName} ladattu',
  'attachment.uploadFailed': 'Tiedoston {fileName} lataaminen epäonnistui!',
  'attachment.delete.confirmTitle': 'Poista tiedosto?',
  'attachment.delete.confirmText': 'Haluatko varmasti poistaa tiedoston {fileName}?',
  'attachment.deleteFailed': 'Tiedoston {fileName} poistaminen epäonnistui!',
  'workflowReleaseTable.title': 'Työnkulku',
  'workflowReleaseTableHeader.name': 'Nimi',
  'workflowReleaseTableHeader.description': 'Kuvaus',
  'workflowReleaseTableHeader.updatedBy': 'Päivittäjä',
  'workflowReleaseTableHeader.updated': 'Päivitetty',
  'workflowReleaseTable.addButton': 'Lisää uusi',
  'workflowReleaseTable.viewButton': 'Katso',
  'workflowReleaseTable.exportButton': 'Lataa',
  'workflowRelease.dialogTitle': 'Työnkulun julkaisu',
  'workflowRelease.name': 'Nimi',
  'workflowRelease.description': 'Kuvaus',
  'workflowRelease.releaseCreationFailed': 'Palveluversion luominen epäonnistui, syy: {cause}',
  'publicationsTable.title': 'Julkaisut',
  'publicationsTableHeader.name': 'Julkaisun tunniste',
  'publicationsTableHeader.description': 'Kuvaus',
  'publicationsTableHeader.createdBy': 'Päivittäjä',
  'publicationsTableHeader.created': 'Luotu',
  'publicationsTableHeader.contentTag': 'Sisältöversio',
  'publicationsTableHeader.workflowTag': 'Workflow versio',
  'publicationsTableHeader.wrenchTag': 'theWrench versio',
  'publicationsTableHeader.liveDate': 'Päivitetty',
  'publicationsTable.addButton': 'Lisää uusi',
  'publicationsTable.viewButton': 'Katso',
  'publicationsTable.exportButton': 'Lataa ulos',
  'publicationsTable.uploadButton': 'Lataa sisään',
  'publications.external': 'Tämä on ulkoisesti konfiguroitu päivitys, joka astuu voimaan vasta kun muut päivitykset on tehty',
  'publications.changeStatus': 'Muokkaa päivityksen tilaan',
  'publications.currentStatus': 'Nykyisen päivitysen status',
  'publications.remove': 'Poista päivitys',
  'publications.deploy': 'Julkaise nyt',
  'publications.dialogTitle': 'Tee uusi julkaisu',
  'publications.name': 'Julkaisun tunniste',
  'publications.description': 'Kuvaus',
  'publications.workflowTag': 'Workflow versio',
  'publications.wrenchTag': 'theWrench versio',
  'publications.contentTag': 'Sisältöversio',
  'publications.createNewTag': 'Luo uusi versio \"{tag}\"',
  'publications.downloadFailed': 'Julkaisun lataus epäonnistui, syy: {cause}',
  'publications.tagCreationFailed': 'Julkaisun luominen epäonnistui, syy: {cause}',
  'publications.uploadDialogTitle': 'Lataa julkaisu',
  'dialobForms.dialog.heading': 'Lomakkeet',
  'dialobForms.table.tooltip.add': 'Lisää',
  'dialobForms.table.label': 'Nimi',
  'dialobForms.table.created': 'Luotu',
  'dialobForms.table.lastSaved': 'Päivitetty',
  'dialobForms.table.tooltip.edit': 'Muokkaa',
  'dialobForms.dialog.emptyTitle': '-',
  'dialobForms.table.tooltip.copy': 'Kopio',
  'dialobForms.table.tooltip.delete': 'Poista',
  'dialobForm.saveFailed': 'Tallennus epäonnistui',
  'dialobForm.downloadFailed': 'Tallennus epäonnistui',
  'dialobForm.deleteFailed': 'Poisto epäonnistui',
  'dialobForm.heading.copyDialog': 'Kopio lomake',
  'dialobForm.heading.addDialog': 'Lisää lomake',
  'dialobForm.dialog.formName': 'ID',
  'dialobForm.dialog.formLabel': 'Nimi',
  'dialobForm.error.invalidFormName': 'Väärä ID',
  'dialobForm.dialog.deleteQuestion': 'Haluatko poistaa lomakkeen \"{formName}\"?',
  'dialobForm.heading.deleteDialog': 'Lomakkeen poisto',
  'dialobForm.review.title': 'Lomakkeen tarkistus',
  'feedback.notenabled': 'Feedback is not enabled for this task',
  'pages': 'Sivut',
  'articles': 'Artikkelit',
  'locale': 'Sijainti',
  'locales': 'Sijainnit',
  'tag': 'Merkintä',
  'links': 'Linkit',
  'releases': 'Julkaisut',
  'options': 'Valinnat',
  'value': 'Arvo',
  'date': 'Päiväys',
  'order': 'Järjestys',
  'description': 'Kuvaus',
  'name': 'Nimi',
  'delete': 'Poista',
  'download': 'Lataa JSON',
  'disable': 'Poista käytöstä',
  'status': 'Status',
  'created': 'Luotu',
  'modified': 'Muokattu',
  'rename': 'Nimeä uudelleen',
  'reorder': 'Järjestä uudelleen',
  'remove': 'Poista',
  'composer.select.article': 'Valitse artikkelit',
  'search.field.label': 'Haku',
  'search.articles': 'Artikkeleita',
  'search.services': 'Palveluja',
  'search.links': 'Linkkejä',
  'search.templates': 'Templeitit',
  'activities.article.title': 'Artikkeli',
  'activities.locale.title': 'Lokalistointi',
  'activities.page.title': 'Sivu',
  'activities.link.title': 'Linkki',
  'activities.release.title': 'Julkaisu',
  'activities.migration.title': 'Migraatio',
  'migration.create': 'Migraatio data',
  'activities.migration.desc': 'Käytä JSON tiedosta tämän portaalin migrointiin',
  'activities.templates.title': 'Mallipohjat',
  'activities.version.composer': 'Composer: build version {version}, build date {date}',
  'activities.version.core': 'Core: build version {version}, build date {date}',
  'dialog.about.title': 'DigiExpress',
  'templates': 'Mallipohjat',
  'template.name': 'Nimi',
  'template.name.desc': 'Mallipohjan nimi',
  'template.create': 'Luo mallipohja',
  'template.edit': 'Muokkaa mallipohjaa',
  'template.type': 'Mallipohjan tyyppi',
  'template.page': 'Sivun mallipohja',
  'template.desc': 'Kuvaus',
  'template.delete': 'Poista mallipohja',
  'services': 'Palvelut',
  'services.create': 'Luo palvelu',
  'services.add': 'Lisää palvelu',
  'services.technicalname': 'Palvelun nimi',
  'services.modeselect.title': 'Configuration options',
  'services.modeselect.label': 'Select',
  'services.devmode.label': 'Development mode',
  'services.devmode.tooltip': 'Development mode',
  'services.disabledmode.label': 'Disabled mode',
  'services.disabledmode.helper': 'Palvelu ei ole portaalissa näkyvissä',
  'services.disabledmode.tooltip': 'Disabled mode',
  'services.none.label': 'No configuration selected',
  'services.none.helper': 'Default configuration',
  'services.none.tooltip': 'No special configuration',
  'services.anonmode.label': 'Anonymous mode',
  'services.anonmode.tooltip': 'Anonymous mode',
  'services.flowName': 'Workflow',
  'services.flowName.description': 'Workflow theWrench nimi',
  'services.formName': 'Dialob lomakkeen nimi',
  'services.formName.description': 'Lomakkeen nimi',
  'services.formTag': 'Lomakkeen versionumero',
  'services.formTag.description': 'Lomakkeen versionnumero',
  'services.startdate': 'Palvelun saataville',
  'services.startdate.description': 'Palvelun julkaisuajankohta',
  'services.enddate': 'Palvelun pois saatavilta',
  'services.enddate.description': 'Palvelu poistuu käytöstä',
  'services.delete': 'Poista palvelu',
  'snack.article.createdMessage': 'Artikkeli luotu',
  'snack.article.deletedMessage': 'Artikkeli poistettu',
  'snack.article.editedMessage': 'Artikkelin muutokset tallennettu',
  'snack.page.createdMessage': 'Sivu luotu',
  'snack.page.deletedMessage': 'Sivu poistettu',
  'snack.page.savedMessage': 'Sivun muutokset tallennettu',
  'toolbar.search': 'Hae',
  'toolbar.save': 'Tallenna',
  'toolbar.stencil': 'theStencil',
  'toolbar.wrench': 'theWrench',
  'toolbar.menu': 'Valikko',
  'toolbar.help': 'Tuki',
  'toolbar.services': 'Palvelut',
  'toolbar.import': 'Tuo dataa',
  'toolbar.tasks': 'Tehtävät',
  'toolbar.about': 'Tietoja',
  'stencil.services.found.none': 'Ei tuloksia',
  'link.type.internal': 'Sisäinen (domainin sisällä)',
  'link.type.external': 'Ulkoinen (domainin ulkopuolella)',
  'link.type.phone': 'Puhelinnumero',
  'link.search.title': 'Etsi linkkejä',
  'link.value': 'Linkin tiedot',
  'sitelocale.label.select.alreadyDefined': 'Tämä lokalisointi on jo käytössä',
  'sitelocale.label.table.editLocaleValue': 'Editoi lokalisointia',
  'locales.label.table.title': 'Lokalisonti tunniste',
  'locales.label.table.value': 'Lokalisointi',
  'transferlist.noItemsSelected': 'Ei valintoja',
  'transferlist.search': 'Hae',
  'transferlist.noSearchResults': 'Ei tuloksia',
  'explorer.tabs.search': 'Hae',
  'explorer.tabs.articles': 'Artikkelit',
  'explorer.tabs.links': 'Lomakkeet',
  'explorer.tabs.services': 'Palvelut',
  'imports': 'Tuotu sisältö',
  'imports.select': 'Valitse tuotava tiedosto',
  'imports.import.action': 'Tuonti valittu',
  'article.order': 'Artikkelin järjestysnumero',
  'article.order.view': 'Näytä Artikkelien järjestys',
  'article.select': 'Valitse Artikkeli',
  'article.links.selectedlinks': 'Valitse Linkki',
  'article.composer.title': 'Luo uusi artikkeli',
  'article.composer.parent': 'Emoartikkeli',
  'article.composer.parent.unselected': 'Ei valittu',
  'article.create': 'Luo artikkeli',
  'article.name': 'Artikkelin nimi',
  'article.delete.title': 'Poista tämä artikkeli pysyvästi?',
  'article.delete.description': 'Artikkelin poistaminen poistaa sen ja siihen yhdistetyt sivut koko sovelluksesta.',
  'article.edit.title': 'Muokkaa artikkelia',
  'article.edit.parent': 'Juuri Artikkeli',
  'article.edit.orderhelper': 'Kolmenumeroinen luku järjestelyyn',
  'article.devmode.helper': 'Jos kehitysverisio on aktiivinen niin Artikkeli näkyy ainoastaan kehitysympäristössä',
  'article.devmode': 'Julkaisu tyyppi',
  'articleservices': 'Artikkelin palvelut: {name}',
  'articlelinks': 'Artikkelin linkit: {name}',
  'article.composer.orderhelper': 'Mitä pienempi numero sen ylempänän tämä Artikkeli on valinnoissa',
  'allarticles': 'Valitse kaikki',
  'allarticles.individual': 'Poista kaikki vallinnat',
  'button.create': 'Luo',
  'button.add': 'Lisää',
  'button.disable': 'Jatka ja deaktivoi',
  'button.enable': 'Jatka ja salli käyttö',
  'button.remove': 'Jatka ja poista käytöstä',
  'button.apply': 'Salli muutokset ja jatka',
  'button.releasegraph': 'Graafi',
  'button.view.all.locales': 'Näytä kaikki sijainnit',
  'button.view.all.releases': 'Näytä kaikki julkaisut',
  'button.view.all.templates': 'Maillipohjat',
  'links.message': 'Suurenna rivejä tarkastellaksesi linkki-artikkeli yhteyksiä',
  'links.searchAll': 'Etsi linkkejä',
  'link.article.add.title': 'Lisää linkki artikkeliin',
  'link.article.select': 'Valitse artikkeli',
  'link.type': 'Tyyppi',
  'link.url': 'URL / arvo',
  'link.locale.all': 'Kaikki sijainnit',
  'link.content': 'Linkki URL / reitti',
  'link.composer.title': 'Luo uusi linkki',
  'link.composer.descriptionlabel': 'Kuvaus',
  'link.composer.descriptionhelper': 'Teksti, jonka käyttäjä näkee',
  'link.composer.valuehelper': 'URL / linkin reitti (http://www.example.com)',
  'link.edit.title': 'Muokkaa linkkiä',
  'link.delete.title': 'Poista linkki pysyvästi?',
  'link.delete': 'Linkin poistaminen poistaa sen lopullisesti koko sovelluksesta ja sen kaikki yhteydet artikkeleihin/sivuihin menetetään.',
  'link.removepage.title': 'Irrota tämä linkki?',
  'link.removepage': 'Linkin irrottaminen poistaa vain sen yhteyden tähän artikkeliin. Poistaaksesi kohteen pysyvästi, valitse \Poista\"."',
  'link.options': 'Linkkivalinnat',
  'link.options.add': 'Lisää artikkeliin linkkejä',
  'resource.edit.links': 'Lisää ja poista artikkelilinkkejä',
  'links.change': 'Muokkaa linkkejä',
  'link.create': 'Luo linkki',
  'link.devmode': 'Kehitysversion aktivointi',
  'locale.create': 'Luo lokalisointi',
  'locale.disable.title': 'Poista lokalisointi käytöstä?',
  'locale.enable.title': 'Salli lokalisoinnin käyttö?',
  'locale.disable': 'Kaikki tätä lokalisointi käyttävät sivut ovat käyttöliittymässä piilossa. Sivuja voidaan edelleen muokata.',
  'locale.enable': 'Kaikki tätä lokalisointi käyttävät sivut ovat esillä käyttöliittymässä.',
  'locale.composer.title': 'Luo uusi lokalisointi',
  'locale.composer.placeholder': 'Kaksikirjaiminen kielitunniste',
  'locale.composer.helper': 'Kaksikirjaiminen kielitunniste',
  'locale.overview': 'Lokalisointien yhteenveto',
  'locales.content': 'Sivulta löytyy lokalisoitua sisältöä',
  'locales.nocontent': 'Sivulta ei löydy lokalisoitua',
  'locales.nopage': 'Artikkelissa ei löyd tätä kieliversiota',
  'locales.label.table.locale': 'Kielikoodi',
  'newpage.title': 'Luo uusi sivu',
  'newpage.info': 'Sivulla on sisällöstä ja sen tulee olla yhdistetty artikkeliin.',
  'newpage.article.info': 'Vahvista sivun luominen artikkelille: {article} sijainnilla: {locale}',
  'page.create': 'Luo sivu',
  'page.delete.dialog.title': 'Poista sivu tästä artikkelista',
  'pages.save': 'Tallenna sivut',
  'pages.add': 'Lisää sivu',
  'pages.change': 'Muuta sivun lokalisointia',
  'pages.select.locale': 'Muokkaa lokalisoitua sivun sisältöä',
  'pages.select.locale.edit.desc': 'Ota käyttöön vierekkäinen muokkaus yhdellä välilehdellä valitsemalla kaksi kieltä.',
  'pages.edit.language1': 'Muokkaa tätä kieltä',
  'pages.edit.language2': 'Muokkaa tätä kieltä vierekkäin',
  'pages.edit.currentlyEditing.language2': 'Muokkaus vierekkäin',
  'pages.edit.currentlyEditing.language1': 'Muokkaa tätä kieltä',
  'pages.change.info': 'Valitse sivu tästä artikkelista ja anna uusi arvo sen sijainnille.',
  'pages.change.devmode': 'Muuta sivun kehitystilaa',
  'pages.change.devmode.info': 'Valitse sivu tästä artikkelista ja muuta sen kehitystapaa.',
  'pages.devmode': 'Kehitysversio aktiivinen',
  'pages.delete': 'Poista sivu',
  'pages.delete.message': 'Valitse artikkelista poistettava sivu',
  'pages.options': 'Sivuvalinnat',
  'pages.edit.selectpage': 'Valitse sivue',
  'pages.edit.selectTargetLocale': 'Valitse kieli',
  'release.create': 'Luo julkaisu',
  'release.composer.title': 'Luo uusi julkaisu',
  'release.composer.label': 'Version nimi nimi',
  'release.composer.note': 'Info',
  'release.composer.helper': 'Valinnainen lisätieto tulevaa käyttöä varten',
  'release.desc': 'Katso kaikki julkaisut ja lataa kaikki sivuston sisältö JSON-muodossa. Tarkempia tietoja tietyistä julkaisuista ja niiden sisällöstä on kaaviossa.',
  'release.delete.title': 'Poista päivitys?',
  'release.delete.desc': 'Haluatko poista päivityksen pysyvästi',
  'releases.view.note': 'Lisä tietoa',
  'releases.view.tag': 'Nimi',
  'releases.view.created': 'Luotu',
  'releases.view.download': 'JSON alas lataus',
  'buttons.create': 'Lisää',
  'buttons.apply': 'Laita voimaan',
  'buttons.delete': 'Poista',
  'buttons.copy': 'Kopio',
  'button.compose': 'Luo',
  'buttons.download': 'Lataa',
  'content.loading': 'Ladataan',
  'explorer.tabs.flows': 'Virtaukset',
  'explorer.tabs.decisions': 'Päätökset',
  'explorer.active.branch': 'Aktiivinen haara: {name}',
  'explorer.active.branch.default': 'Oletus',
  'activities.flows.title': 'Workflow',
  'activities.flows.desc': 'A a sequence of tasks which are defined by using simple configuration language.',
  'activities.decisions.title': 'Decisions',
  'activities.decisions.desc': 'A decision table that can be used to make decisions based on input data.',
  'activities.services.title': 'Services',
  'activities.services.desc': 'A piece of Java or Groovy code that is embedded inside of a flow as a task.',
  'activities.releases.title': 'Releases',
  'activities.releases.desc': 'A Release is a snapshot of all site content at one certain point of time.',
  'activities.releases.desc.additional': 'Each Release can be downloaded to be used for production or backup purposes, or can be branched for further editing. This will replace all current assets so make sure any changes are saved.',
  'activities.releases.view': 'View all releases',
  'activities.releases.graph': 'Graph',
  'activities.compare.title': 'Compare',
  'activities.compare.desc': 'Compare two releases to see what has changed between them.',
  'activities.compare.view': 'Compare',
  'activities.templates.view': 'View all templates',
  'activities.debug.title': 'Debug',
  'activities.debug.desc': 'Simulate execution of an asset. Can be done via form input, JSON input, or by using a CSV file.',
  'activities.debug.view': 'Simulate',
  'activities.assets.saveSuccess': 'Saved asset: {name}',
  'programs.error.title': 'Program error',
  'programs.warning.title': 'Program warning',
  'flows': 'Flows',
  'migrations.title': 'Migration',
  'migrations.create': 'Perform migration',
  'migrations.select': 'Select tag.json file',
  'flows.edit.title': 'Edit flow',
  'flows.copyas.title': 'Copy flow as',
  'flows.delete.title': 'Delete flow',
  'flows.delete.error.title': 'Failed to delete flow',
  'flows.delete.content': 'Are you sure you want to delete FLOW: {name}?',
  'flows.deleted.message': 'Deleted FLOW: {name}',
  'flows.simulate.title': 'Debug the flow',
  'flows.composer.title': 'Create new FLOW',
  'flows.composer.copyTitle': 'Copy FLOW as',
  'flows.composer.createdMessage': 'Created FLOW: {name}',
  'flows.composer.copiedMessage': 'Copied FLOW {name} as: {newName}',
  'flows.composer.errorsTitle': 'Failed to create FLOW',
  'flows.composer.assetName': 'Unique name for the FLOW',
  'flows.autocomplete.task.create': 'Create new asset',
  'flows.autocomplete.task.link': 'Link selected asset',
  'flows.autocomplete.task.searchField': 'Search for asset...',
  'flows.autocomplete.task.searchPlaceholder': 'Asset name or description',
  'flows.autocomplete.task.selectType': 'Select asset type to link',
  'flows.autocomplete.task.searchHelper': 'Matches asset name and description',
  'flows.autocomplete.task.searchResults': 'Search results',
  'flows.autocomplete.task': 'Add existing asset or create new one',
  'flows.autocomplete.task.snackbar.created': 'Created new {type}: {name}',
  'flows.autocomplete.task.snackbar.creating': 'Creating new {type}: {name}',
  'flows.graph.show': 'Show flow graph',
  'flows.graph.hide': 'Hide flow graph',
  'services.searchAll': 'Search all services',
  'services.edit.title': 'Edit service',
  'services.copyas.title': 'Copy service as',
  'services.delete.title': 'Delete service',
  'services.delete.error.title': 'Failed to delete SERVICE',
  'services.delete.content': 'Are you sure you want to delete SERVICE: {name}?',
  'services.deleted.message': 'Deleted SERVICE: {name}',
  'services.simulate.title': 'Debug the service',
  'services.composer.title': 'Create new SERVICE',
  'services.composer.copyTitle': 'Copy SERVICE as',
  'services.composer.createdMessage': 'Created SERVICE: {name}',
  'services.composer.copiedMessage': 'Copied SERVICE {name} as: {newName}',
  'services.composer.errorsTitle': 'Failed to create SERVICE',
  'services.composer.assetName': 'Unique name for the SERVICE',
  'decisions.name': 'Name',
  'decisions.desc': 'Description',
  'decisions.simulate.title': 'Debug the decision',
  'decisions.hitpolicy': 'Hit-policy',
  'decisions.edit.title': 'Edit decision',
  'decisions.copyas.title': 'Copy decision as',
  'decisions.delete.error.title': 'Failed to delete DECISION',
  'decisions.delete.title': 'Delete decision',
  'decisions.delete.content': 'Are you sure you want to delete DECISION: {name}?',
  'decisions.deleted.message': 'Deleted DECISION: {name}',
  'decisions.deleteConfirmTitle': 'Confirm Delete',
  'decisions.deleteConfirmText': 'Are you sure you want to delete this {type}?',
  'decisions.type.row': 'row',
  'decisions.type.column': 'column',
  'decisions.table.hitpolicy': 'Matches',
  'decisions.table.options': 'Options',
  'decisions.composer.title': 'Create new DECISION',
  'decisions.composer.copyTitle': 'Copy DECISION as',
  'decisions.composer.createdMessage': 'Created DECISION: {name}',
  'decisions.composer.copiedMessage': 'Copied DECISION {name} as: {newName}',
  'decisions.composer.errorsTitle': 'Failed to create DECISION',
  'decisions.composer.assetName': 'Unique name for the DECISION',
  'decisions.toolbar.addInputColumn': 'Add input column',
  'decisions.toolbar.addOutputColumn': 'Add output column',
  'decisions.toolbar.addRow': 'Add row',
  'decisions.toolbar.csvDownload': 'Download CSV, with separator \';\'',
  'decisions.toolbar.csvUpload': 'Upload CSV, with separator \';\'',
  'decisions.toolbar.nameAndHitpolicy': 'Name and hit-policy',
  'decisions.toolbar.organize.rows.columns': 'Organize rows and columns',
  'decisions.toolbar.organize.action': 'Select action',
  'decisions.toolbar.organize.action.helper': 'Move column or row based on name/index',
  'decisions.toolbar.organize.action.expression': 'Select expression',
  'decisions.toolbar.organize.action.expression.column': 'Select column',
  'decisions.toolbar.organize.action.deleteColumn': 'Delete whole column',
  'decisions.toolbar.organize.action.deleteRow': 'Delete whole row',
  'decisions.toolbar.organize.action.deleteRow.contents': 'Row contents',
  'decisions.toolbar.organize.action.move.from.column': 'Column to move',
  'decisions.toolbar.organize.action.move.from.row': 'Row to move',
  'decisions.toolbar.organize.action.move.to.column': 'New Position',
  'decisions.toolbar.organize.action.move.to.row': 'New Position',
  'decisions.table.inputs.title': 'Matching rules',
  'decisions.table.outputs.title': 'Results',
  'decisions.header.dialog.title': 'Decision table: {name}, column: {column}',
  'decisions.cells.dialog.title': 'Decision table: {name}, column: {column}, value: {value}',
  'decisions.cells.dialog.title.simple': 'Edit Value',
  'decisions.header.dialog.title.simple': 'Edit Header',
  'decisions.cells.dialog.title.intl': 'Edit Localized Value',
  'decisions.cells.newvalue.boolean': 'Enter new value',
  'decisions.cells.newvalue.boolean.helper': 'Select boolean value',
  'decisions.cells.newvalue.boolean.empty': 'No value selected',
  'decisions.cells.newvalue.date.operator': 'Operator',
  'decisions.cells.newvalue.date.start': 'Start date',
  'decisions.cells.newvalue.date.end': 'End date',
  'decisions.cells.newvalue.date.value': 'Date',
  'decisions.cells.newvalue.number.comparisonType': 'Comparison',
  'decisions.cells.newvalue.number.comparisonTypeEmpty': 'Comparison not selected',
  'decisions.cells.newvalue.number.comparisonValue': 'New numerical value',
  'decisions.cells.newvalue.number.comparisonToRange': 'Change to range',
  'decisions.cells.newvalue.number.rangeStart': 'Start',
  'decisions.cells.newvalue.number.rangeEnd': 'End',
  'decisions.cells.newvalue.number.value': 'New numerical value',
  'decisions.cells.newvalue.number.rangeIncluded': 'Included',
  'decisions.cells.newvalue.number.rangeToComparison': 'Change to comparison',
  'decisions.cells.newvalue.string.comparisonType': 'Comparison',
  'decisions.cells.newvalue.string.addValue': 'Add new value',
  'decisions.cells.newvalue.string.available': 'Available values',
  'decisions.cells.newvalue.string.selected': 'Selected values',
  'decisions.cells.newvalue.string.empty': 'Comparison not selected',
  'decisions.cells.newvalue.clear': 'Clear current value',
  'decisions.valueSet': 'Define value set',
  'decisions.valueSet.description': 'Value sets can be used to define a predetermined set of values for any input',
  'decisions.valueSet.add': 'Add to value set',
  'decisions.valueSet.remove': 'Remove from value set',
  'decisions.valueSet.current': 'Current value set',
  'decisions.valueSet.empty': 'Value set is empty',
  'dt.header.name': 'Name',
  'dt.header.delete': 'Delete',
  'dt.header.expression': 'Expression',
  'dt.header.dataType': 'Data type',
  'dt.header.script': 'Script',
  'decisions': 'Decisions',
  'program.status.DEPENDENCY_ERROR': 'Dependency Errors',
  'program.status.UP': 'Program is UP',
  'program.status.AST_ERROR': 'Syntax errors',
  'program.status.PROGRAM_ERROR': 'Compiler errors',
  'package.explorer.flows': 'flows',
  'package.explorer.servicetasks': 'services',
  'package.explorer.decisiontables': 'decisions',
  'dialog.addtype.title': 'Lisää uusi sisältö',
  'dialog.addtype.button.cancel': 'Peruuttaa',
  'dialog.addtype.button.confirm': 'Luoda',
  'dialog.addtype.error.unique': 'Omaisuuden nimen on oltava yksilöllinen!',
  'dialog.addtype.error.filled': 'Kohteen nimi on täytettävä!',
  'dialog.addtype.input.serviceType': 'Omaisuuden tyyppi',
  'dialog.addtype.input.name': 'Omaisuuden nimi',
  'dialog.copyas.title': 'Kopioi omaisuus',
  'dialog.copyas.button.cancel': 'Peruuttaa',
  'dialog.copyas.button.confirm': 'Kopioida',
  'dialog.copyas.input.from': 'Kopioi kohteesta',
  'dialog.copyas.input.to': 'Uusi omaisuuden nimi',
  'dialog.copyas.error.unique': 'Omaisuuden nimen on oltava yksilöllinen!',
  'dialog.copyas.error.filled': 'Kohteen nimi on täytettävä!',
  'dialog.save.title': 'Tallenna sisältö: {name}',
  'dialog.save.content': 'Haluatko varmasti tallentaa?',
  'dialog.save.errors': 'Omaisuuden tallentaminen epäonnistui',
  'dialog.save.button.cancel': 'Peruuttaa',
  'dialog.save.button.confirm': 'Tallentaa',
  'release.delete.content': 'Haluatko varmasti poistaa julkaisun: {name}',
  'release.delete.error.title': 'Virhe julkaisun poistamisessa',
  'release.deleted.message': 'Julkaisu {name} poistettu',
  'releases.composer.createdMessage': 'Luotu uusi julkaisu {name}',
  'releases.view.action': 'Toiminta',
  'releases.composer.title': 'Luo uusi julkaisu',
  'releases.composer.assetName': 'Julkaisun nimi',
  'releases.composer.assetDesc': 'Julkaisun kuvaus',
  'releases.composer.errorsTitle': 'Virhe luotaessa julkaisua',
  'releases.table.title': 'Julkaisut ja sivuliikkeet',
  'releases.table.column.name': 'Nimi',
  'releases.table.column.message': 'Viesti',
  'releases.table.column.created': 'Luotu',
  'releases.table.name': 'Kaikki julkaisut',
  'releases.add.error.unique': 'Julkaisun on oltava ainutlaatuinen!',
  'releases.add.error.filled': 'Julkaisun nimi on täytettävä!',
  'releases.add.input.name': 'Nimi',
  'releases.add.input.msg': 'Kommentti',
  'releases.add.button.create': 'Luo julkaisu',
  'releases.button.compare': 'Vertaa',
  'releases.button.branch': 'Luo uusi haara',
  'releases.button.checkout': 'Kassalle',
  'releases.button.release': 'Vapauta',
  'releases.button.details': 'Näytä julkaisusisältö',
  'releases.default.name': 'oletuksena',
  'releases.default.note': 'Tämä on oletushaara, johon voit palata',
  'releases.latest.name': 'uusin',
  'releases.latest.note': 'Nämä ovat lyhytaikaisia ​​varoja, joiden viimeisimmät muutokset voidaan vapauttaa',
  'releases.details.title': 'Julkaisusisältö: {name}',
  'branch.delete.title': 'Poista haara',
  'branch.delete.content': 'Haluatko varmasti poistaa haaran: {name}',
  'branch.delete.error.title': 'Virhe haaran poistamisessa',
  'release.branch.creating': 'Luodaan uutta haaraa: {name}',
  'release.branch.created': 'Luotu uusi haara: {name}',
  'release.branch.deleting': 'Poistetaan haaraa: {name}',
  'release.branch.deleted': 'Poistettu haara: {name}',
  'release.branch.checkout': 'Kirjattu konttoriin: {name}',
  'debug.toolbar.options': 'Vaihtoehdot',
  'debug.toolbar.selectAsset': 'Valitse virheenkorjattava sisältö',
  'debug.toolbar.inputCsv': 'Määritä syöttötiedot CSV-tiedostona',
  'debug.toolbar.inputForm': 'Määrittele syötetiedot FORM-muodossa',
  'debug.toolbar.inputJson': 'Määritä syöttötiedot JSON-muodossa',
  'debug.toolbar.execute': 'Suorittaa',
  'debug.toolbar.noAsset': 'Valitse omaisuus vaihtoehdoista',
  'debug.toolbar.openAsset': 'Avata',
  'debug.toolbar.download': 'Lataa tulokset CSV-muodossa',
  'debug.input.noAsset': 'Yhtään OMAA ei ole valittu',
  'debug.input.form': 'Virheenkorjaus FORM:n avulla',
  'debug.input.formTitle': 'Määritä tulot',
  'debug.input.form.invalid.integer': 'Arvon on oltava kokonaisluku',
  'debug.input.form.invalid.number': 'Arvon on oltava numero',
  'debug.input.form.invalid.range': 'Arvon on oltava määritetyllä alueella',
  'debug.input.json': 'Viankorjaus JSON:n avulla',
  'debug.input.jsonTitle': 'Määritä JSON-tulo',
  'debug.input.csvUpload': 'Viankorjaus CSV:n avulla',
  'debug.input.csvFile': 'Lataa CSV-TIEDOSTO',
  'debug.input.csvFileTitle': 'Lähetä CSV-tiedosto - puolipisteellä eroteltu (;)',
  'debug.input.csvFileOrText': 'Tai liitä CSV-sisältö - puolipisteellä eroteltu (;)',
  'debug.inputs.fieldName': 'Kentän nimi',
  'debug.inputs.fieldValue': 'Kentän arvo',
  'debug.select.title': 'Valitse virheenkorjattava sisältö',
  'debug.select.assetType': 'Suodatettava sisältötyyppi',
  'debug.select.searchField': 'Haettavan kohteen nimi',
  'debug.select.searchHelper': 'Haku vastaa sisällön nimeä tai kuvausta',
  'debug.select.searchPlaceholder': 'Hakusana',
  'debug.select.searchResults': 'Löytyi omaisuutta',
  'debug.select.confirm': 'Valitse',
  'debug.inputs.format': 'Sisällön syöttömuoto: {type}',
  'debug.asset.select.label': 'Virheenkorjattava sisältö',
  'debug.asset.select.clear': 'Tyhjennä ajotiedot',
  'debug.asset.select.execute': 'Suorita omaisuus',
  'debug.asset.execute.inputs': 'Virheenkorjaustulot',
  'debug.asset.execute.errors': 'Suoritusvirheet',
  'debug.asset.execute.outputs.dt.json': 'Vastaavat rivit',
  'debug.asset.execute.outputs.dt.rejects': 'Hylätyt rivit',
  'debug.asset.execute.outputs.dt.rejects.order': 'Toteutusmääräys',
  'debug.asset.execute.outputs.flow.step': 'Vaiheen nimi: {name}, tila: {status}',
  'debug.csv.row': 'Tietorivi: {row}',
  'debug.csv.download': 'Lataa tulokset CSV-muodossa',
  'debug.csv.download.delimiter': 'Valitse CSV-tiedoston erotin',
  'debug.csv.download.delimiter.semicolon': 'Puolipiste (;)',
  'debug.csv.download.delimiter.comma': 'Pilkku (,)',
  'debug.csv.download.options': 'Vientivaihtoehdot',
  'debug.csv.download.wrap': 'Kääri erottimet sisältävät solut lainausmerkkeihin',
  'compare.tip': 'Valitse verrattavat julkaisut alta. Perus on vertailun lähtökohta, ja kohde on julkaisu, jota verrataan perustaan.',
  'compare.base': 'Valitse perusvapautus',
  'compare.target': 'Valitse kohdejulkaisu',
  'compare.dialog.title': 'Verrataan julkaisuja {base} ja {target}',
  'compare.dialog.line': 'Inline',
  'compare.dialog.side': 'Vierekkäin',
  'menu.feedbackAllTasks': 'Kaikki palaute',
  'menu.activities': 'Aktiviteetit',
  'feedback.all': 'Kaikki palaute',
  'feedback.none': 'Palautetta ei ole saatavilla',
  'feedback.search': 'Haku',
  'feedback.search.placeholder': 'Palaute-, prosessi- tai tehtävätunnus',
  'feedback.search.filter.category': 'Suodata luokan mukaan',
  'feedback.search.filter.subCategory': 'Suodata alakategorian mukaan',
  'feedback.filter.selectNone': 'Ei mitään',
  'queues.all': 'Jonot',
  'consumers.all': 'Kuluttajat',
  'queue.config.appId': 'Sovelluksen tunnus',
  'queue.config.none': 'Ladataan',
  'queue.config.consumerName': 'Kuluttajan nimi',
  'queue.config.routingKey': 'Reititysavain',
  'queue.config.consumerStatus': 'Status',
  'queue.config.comment': 'Kommentti',
  'queue.config.consumerId': 'Id',
  'queue.config.qualifiedJavaName': 'Tekninen nimi',
  'queue.config.queueName': 'Jonon nimi',
  'queue.config.createdAt': 'Luotu klo',
  'queue.config.createdBy': 'Luonut',
  'queue.all_deliveries.title': 'Kaikki toimitukset',
  'queue.all_deliveries.created': 'Luotu',
  'queue.all_deliveries.consumerComment': 'Kommentti',
  'queue.all_deliveries.status': 'Status',
  'queue.all_deliveries.messageId': 'Viestin tunnus',
  'queue.all_deliveries.consumerId': 'Kuluttajatunnus',
  'queue.all_messages.title': 'Kaikki viestit',
  'queue.all_messages.routingKey': 'Reititysavain',
  'queue.all_messages.messageId': 'Viestin tunnus',
  'queue.all_messages.bodyId': 'Rungon tunnus',
  'queue.all_messages.bodyType': 'Vartalotyyppi',
  'queue.all_messages.status': 'Status',
  'queue.all_messages.body': 'Runko',
  'queue.all_messages.created': 'Luotu',
  'menu.messages': 'Viestit',
  'menu.deliveries': 'Toimitukset',
  'toolbar.preview': 'Live-esikatselu',
  'workflow.edit.title': 'Muokkaa työnkulkua',
  'workflow.create': 'Luo työnkulku',
  'button.view.all.articles': 'Näytä kaikki artikkelit',
  'button.view.all.pages': 'Näytä kaikki sivut',
  'button.view.all.links': 'Näytä kaikki linkit',
  'button.view.all.workflows': 'Näytä kaikki työnkulut',
  'workflows': 'Työnkulku',
  'associations.add': 'Yhdistä artikkeliin',
  'explorer.pages': 'Sivut',
  'explorer.pages.create': 'Luo sivu',
  'explorer.pages.dualview': 'Kaksoisnäkymä',
  'explorer.locale.empty': 'Ei sijainteja',
  'articles.message': 'Suurenna rivejä tarkastellaksesi artikkeleihin yhdistettyjä sivuja ja muokkaa näitä yhteyksiä',
  'article.deletepage.title': 'Poista tämä sivu?',
  'article.deletepage': 'Sivun poistaminen poistaa sen lopullisesti koko sovelluksesta.',
  'article.options': 'Artikkelivalinnat',
  'article.addlink': 'Lisää tämä linkki artikkeliin',
  'article.links.addremove': 'Lisää ja poista artikkelilinkkejä',
  'article.links': 'Artikkelilinkit',
  'article.links.sitelinks': 'Sivustolinkit',
  'article.links.remove': 'Irrota/poista linkkiyhteys tähän artikkeliin',
  'article.workflows.addremove': 'Lisää ja poista artikkelien työnkulkuja',
  'article.workflows': 'Artikkelien työnkulut',
  'article.workflows.add': 'Yhdistä tämä työnkulku tähän artikkeliin',
  'article.workflows.remove': 'Poista tämän työnkulun yhteys tähän artikkeliin',
  'article.workflows.siteworkflows': 'Site workflows',
  'button.view': 'Katsele',
  'button.addremove': 'Lisää/Irrota',
  'composer.article.title': 'Artikkeli',
  'composer.article.desc': 'Ryhmä yhdistettyjä sivuja, linkkejä, työnkulkuja ja sijainteja',
  'composer.locale.title': 'Sijainti',
  'composer.locale.desc': 'Lisää, aktivoi ja deaktivoi sisällön kieliä globaalisti',
  'composer.page.title': 'Sivu',
  'composer.page.desc': 'Tiedosto, joka edustaa yhtä kieltä ja siihen yhdistettyjä linkkejä ja työnkulkuja artikkelin sisällä',
  'composer.link.title': 'Linkki',
  'composer.link.desc': 'Sisäiset linkit yhdistävät sisältöön domainin sisällä ja ulkoiset linkit yhdistävät sisältöön domainin ulkopuolella',
  'composer.workflow.title': 'Työnkulku',
  'composer.workflow.desc': 'Yhdistä lomakkeet ja prosessit',
  'composer.release.title': 'Julkaise',
  'composer.release.desc': 'Luo kuva sivun kaikesta sisällöstä tietyssä tilassa testaamis- ja tuotantotarkoituksiin',
  'toolbar.dashboard': 'Hallintatyökalu',
  'dashboard.view.helper': 'Katsele, muokkaa ja poista sisältöjä',
  'link.associate.title': 'Yhdistä linkki artikkeliin',
  'link.options.edit': 'Muokkaa artikkelin linkkejä',
  'link.options.remove': 'Irrota linkit artikkelista',
  'resource.options': 'Resurssivalinnat',
  'resource.edit.workflows': 'Lisää ja poista artikkelityönkulkuja',
  'workflow.associate.title': 'Yhdistä työnkulku artikkeliin',
  'workflow.composer.title': 'Lisää työnkulku',
  'workflow.composer.name': 'Paikannettu nimi',
  'workflow.technicalname': 'Tekninen nimi',
  'workflow.composer.select': 'Valitse olemassaoleva työnkulku',
  'workflow.composer.helper': 'Käyttäjille näytettävä nimi',
  'workflow.composer.placeholder': 'Lupahakemus',
  'workflow.delete.title': 'Poista tämä työnkulku pyvyvästi?',
  'workflow.delete': 'Työnkulun poistaminen poistaa sen koko sovelluksesta.',
  'workflow.removepage.title': 'Irrota tämä työnkulku?',
  'workflow.removepage': 'Työnkulun irrottaminen poistaa vain sen yhteyden tähän artikkeliin. Poistaaksesi kohteen kokonaan/pysyvästi, valitse \Poista\"."',
  'workflow.options': 'Työnkulun valinnat',
  'workflow.add': 'Lisää työnkulku',
  'workflow.edit': 'Muokkaa työnkulkua',
  'workflow.remove': 'Irrota työnkulku',
  'toolbar.articles': 'Artikkeliyhteenveto',
  'toolbar.newarticle': 'Luo uusi artikkeli',
  'toolbar.newlocale': 'Lisää uusi sijainti',
  'toolbar.explorer': 'Explorer',
  'toolbar.links': 'Linkkiyhteenveto',
  'toolbar.workflows': 'Työnkulkuyhteenveto',
  'toolbar.releases': 'Julkaisut',
  'toolbar.locales': 'Sijainnit',
  'eveli.batches.batchView..averageRunTime': 'Average run time',
  'eveli.batches.batchView.averageRunTime.ms': 'ms',
  'taskcard.style.COMPACT': 'Compact',
  'taskcard.style.DEFAULT': 'Default',
  'taskcard.style.LARGE': 'Large'
}