export const fi = {
  'tasksView.title': 'Tehtävät',
  'tasksTableHeader.taskName': 'Nimi',
  'tasksTableHeader.category': 'Tyyppi',
  'tasksTableHeader.status': 'Tila',
  'tasksTableHeader.dueDate': 'Eräpäivä',
  'tasksTableHeader.priority': 'Prioriteetti',
  'tasksTableHeader.assigned': 'Käsittelijä',
  'tasksTableAction.editTask': 'Muokkaa tehtävää',
  'tasksTableAction.deleteTask': 'Poista tehtävää',
  'taskPriority.low': 'Ei kiireellinen',
  'taskPriority.normal': 'Normaali',
  'taskPriority.high': 'Kiire',
  'taskDialog.priority': 'Prioriteetti',
  'taskDialog.subject': 'Aihe',
  'taskDialog.description': 'Asiakkaan tiedot',
  'taskDialog.dueDate': 'Eräpäivä',
  'taskDialog.assignedTo': 'Käsittelijä ryhmä',
  'taskDialog.assignedUser': 'Käyttäjä',
  'taskDialog.status': 'Tila',
  'taskDialog.task': 'Tehtävä',
  'taskDialog.category': 'Tyyppi',
  'taskDialog.source': 'Lähde',
  'task.priority.low': 'Ei kiireellinen',
  'task.priority.normal': 'Normaali',
  'task.priority.high': 'Kiire',
  'task.status.new': 'Uusi',
  'task.status.open': 'Käsittelyssä',
  'task.status.completed': 'Tehty',
  'task.status.rejected': 'Hylätty',
  'task.form.review': 'Katso täytetty lomake',
  'task.form.feedback.manage': 'Hallita palautetta',
  'task.created': 'Luotu',
  'task.updated': 'Päivitetty',
  'comments': 'Kommentit',
  'task.comments.external.createTask': 'Luo tehtävä ennen ulkoisten kommenttien lisäämistä',
  'task.comments.internal.createTask': 'Luo tehtävä ennen sisäisten kommenttien lisäämistä',
  'task.attachments.createTask': 'Luo tehtävä ennen liitteiden lataamista',
  'internalComments': 'Sisäiset kommentit',
  'externalComments': 'Julkiset kommentit',
  'comment.store': 'Tallenna',
  'comment.add': 'Lisää kommentti',
  'comment.addInternal': 'Lisää sisäinen kommentti',
  'comment.addExternal': 'Lähetä asiakkaalle viesti',
  'comment.reply': 'Vastaa',
  'taskButton.addTask': 'Lisää tehtävä',
  'taskButton.refresh': 'Tarkista uudet tehtävät',
  'taskButton.accept': 'Hyväksy',
  'taskButton.cancel': 'Takaisin',
  'table.body.emptyDataSourceMessage': 'Ei dataa',
  'table.body.filterRow.filterTooltip': 'Suodatin',
  'table.body.deleteTooltip': 'Poista',
  'table.body.editRow.deleteText': 'Haluatko varmasti poistaa tämän tehtävän?',
  'table.body.editRow.cancelTask': 'Peruuta',
  'table.body.editRow.saveTask': 'Tallenna',
  'table.pagination.labelDisplayedRows': '{from}-{to} / {count}',
  'table.pagination.labelRowsPerPage': 'Riviä per sivu:',
  'table.pagination.firstPage': 'Ensimmäinen sivu',
  'table.pagination.previousPage': 'Edellinen',
  'table.pagination.nextPage': 'Seuraava',
  'table.pagination.lastPage': 'Viimeinen sivu',
  'table.toolbar.search': 'Etsi',
  'table.toolbar.showColumnsTitle': 'Show columns',
  'table.toolbar.addRemoveColumns': 'Add or remove columns',
  'taskLink.title': 'Lomake',
  'taskLink.button.open': 'Asiakkaan antamat tiedot',
  'taskLink.pdf.open': 'PDF',
  'explorer.title': 'Public feedback',
  'explorer.login': 'Kirjaudu sisään',
  'locale.fi': 'Suomi',
  'locale.sv': 'Ruotsi',
  'locale.en': 'Englanti',
  'app.logout': 'Kirjaudu ulos',
  'app.login': 'Kirjaudu sisään',
  'app.feedback': 'Palaute',
  'menu.dashboard': 'Kojelauta',
  'menu.profile': 'Käyttäjän profiili',
  'menu.tasks': 'Tasks',
  'menu.evaluations': 'Kyselyt',
  'menu.forms': 'Dialob',
  'menu.queues': 'Queues',
  'menu.users': 'Käyttäjät',
  'menu.help': 'Ohjeet',
  'menu.flow': 'Wrench',
  'menu.processes': 'Monitorointi',
  'menu.reports': 'Raportointi',
  'menu.workflows': 'Konfigurointi',
  'menu.logout': 'Kirjaudu ulos',
  'menu.workflowTags': 'Versiointi',
  'menu.publications': 'Julkaisut',
  'menu.services': 'Palvelut',
  'menu.content': 'Stencil',
  'menu.calendar': 'Kalenteri',
  'menu.feedback': 'Palaute',
  'front.intro.title': 'Tervetuloa!',
  'profile.title': 'Käyttäjän profiili',
  'profile.user.name': 'Nimi:',
  'profile.user.email': 'Sähköposti:',
  'profile.user.role': 'Rooli:',
  'profile.user.phone': 'Puhelin:',
  'profile.app.version': 'Sovellusversio:',
  'button.cancel': 'Cancel',
  'button.delete': 'Delete this feedback',
  'button.update': 'Update',
  'button.publish': 'Publish',
  'button.accept': 'Hyväksy',
  'button.edit': 'Avaa',
  'button.close': 'Sulje',
  'button.reject': 'Hylkää',
  'button.send': 'Lähetä',
  'button.dismiss': 'Sulje',
  'button.editRoles': 'Muokkaa',
  'button.select': 'Valita',
  'error.minTextLength': 'Annetun arvon pitää olla vähintään {minLength} merkkiä',
  'error.maxTextLength': 'Annetun arvon tulee olla enintään {max} merkkiä pitkä',
  'error.valueRequired': 'Vaaditaan',
  'error.title': 'Virhe!',
  'error.dialob.session': 'Lomaketta ei voida aukaista juuri nyt. Yritä uudelleen myöhemmin',
  'error.errorLoadingData': 'Error during data loading',
  'error.unauthorized.title': 'Käyttöoikeutesi ovat puutteelliset',
  'error.unauthorized.text': 'Ota yhteyttä IT-palveluihin lähettämällä tukipyyntö Tiketin kautta -> Jätä tukipyyntö -> Kirjautumisongelma.',
  'error.unauthorizedAccess': 'Käyttöoikeutesi ovat puutteelliset',
  'error.dataAccess': 'Virhe toiminnassa',
  'error.statusOpenError': 'Required when status is open',
  'error.workflowCreation': 'Virhe konfiguroinnissa, tarkista nimen yksilöllisyys',
  'table.body.addTooltip': 'Lisää',
  'table.body.editTooltip': 'Avaa',
  'table.body.editRow.deleteMessage': 'Halutko varmasti poistaa tämän?',
  'workflowTable.title': 'Kokoonpano',
  'workflowTableHeader.name': 'Nimi',
  'workflowTableHeader.formName': 'Lomake',
  'workflowTableHeader.flowName': 'Prosessi',
  'workflowTableHeader.updated': 'Päivitetty',
  'workflowTable.addButton': 'Lisää uusi',
  'workflowTable.editButton': 'Muokka',
  'workflow.dialogTitle': 'Työnkulku',
  'workflow.name': 'Nimi',
  'workflow.form.formName': 'Lomakkeen nimi',
  'workflow.form.formTag': 'Lomakkeen versio',
  'workflow.flowName': 'Prosessi',
  'processTable.title': 'Työt',
  'processTableHeader.workflow': 'Tyyppi',
  'processTableHeader.user': 'Käyttäjä',
  'processTableHeader.status': 'Tila',
  'processTableHeader.created': 'Luotu',
  'processTableHeader.questionnaireId': 'Lomake',
  'process.status.ANSWERED': 'Lähetetty',
  'process.status.CREATED': 'Luotu',
  'process.status.ANSWERING': 'Keskeneräinen',
  'process.status.IN_PROGRESS': 'Käsittelyssä',
  'process.status.WAITING': 'Odottaa',
  'process.status.COMPLETED': 'Valmis',
  'process.status.REJECTED': 'Hylätty',
  'comment.button': 'Anna palautetta',
  'comment.title': 'Anna palautetta',
  'comment.form.email': 'Sähköposti',
  'comment.form.feedbackType': 'Tyyppi',
  'comment.form.body': 'Viesti',
  'comment.type.general': 'Anna palautetta',
  'comment.type.propose': 'Ehdota uutta palvelua',
  'comment.type.contact': 'Ota yhteyttä',
  'comment.submitted.success': 'Kiitos palautteesta!',
  'comment.submitted.failure': 'Lähetys epäonnistui',
  'spoTasksTableHeader.taskName': 'Nimi',
  'spoTasksTableHeader.category': 'Tyyppi',
  'spoTasksTableHeader.status': 'Tila',
  'spoTasksTableHeader.priority': 'Prioriteetti',
  'spoTasksTableHeader.dueDate': 'Eräpäivä',
  'spoTasksTableHeader.assigned': 'Käsittelijä',
  'spoTasksTableHeader.assignedUser': 'Käyttäjä',
  'spoTasksTableHeader.created': 'Luotu',
  'spoTasksTableHeader.clientName': 'Asiakas',
  'taskDialog.clientIdentificator': 'Asiakas',
  'taskDialog.assignedUserEmail': 'Käyttäjän sähköposti',
  'task.editRoles': 'Tehtäväryhmät',
  'Questionnaire': 'Lomake',
  'Manual': 'Manuaalinen',
  'Protected': 'Suojattu',
  'Normal': 'Normaali',
  'Represented': 'Valtuutetu',
  'CustomerCreated': 'Asiakas luotu',
  'Internal': 'Sisäinen',
  'task.role.assignedAllUsers': 'Kaikki käyttäjät',
  'task.feedback.published': 'Julkaistu vastaus',
  'confirm.close.title': 'Vahvistus vaaditaan',
  'confirm.unsavedChanges': 'Tallentamattomat muutokset menetetään. Haluatko jatkaa?',
  'task.statistics.statusCount': 'Tilan mukaan',
  'task.statistics.priorityCount': 'Prioriteetin mukaan',
  'task.statistics.daily': 'Päivittäin',
  'task.statistics.overdue': 'Myöhässä',
  'feedback.button': 'Lähetä palautetta',
  'feedback.thanks': 'Kiitos palautteestasi!',
  'feedback.create.title': 'Create public reply to customer feedback',
  'feedback.title': 'Public reply to customer feedback',
  'feedback.update.title': 'Edit public reply to customer feedback',
  'feedback.description': 'Kuvaus',
  'feedback.name': 'Nimesi',
  'feedback.sendScreenshot': 'Lähetä ruutukaappaus',
  'feedback.close': 'Peru',
  'feedback.send': 'Lähetä',
  'feedback.category': 'Category',
  'feedback.subCategory': 'Subcategory',
  'feedback.myReply': 'Reply to customer',
  'feedback.noFeedback.info1': 'No reply to publish!',
  'feedback.noFeedback.info2': 'Please send an external comment to customer, then you can publish the external comment.',
  'feedback.customerFeedback': 'Customer feedback',
  'feedback.customerApprovals': 'Customer approvals',
  'feedback.sourceTaskId': 'Source task id',
  'feedback.formName': 'Form name',
  'feedback.dateReceived': 'Date received from customer',
  'feedback.createdBy': 'Created by',
  'feedback.updatedBy': 'Updated by',
  'feedback.updated': 'Last updated',
  'feedback.notPublished': 'This feedback is not published',
  'feedback.isPublished': 'This feedback is published and publicly viewable',
  'help.title': 'Ohjeet',
  'attachmentView.title': 'Liitetiedostoja',
  'attachmentTableHeader.size': 'Koko',
  'attachmentTableHeader.updated': 'Päivitetty',
  'attachmentTableHeader.created': 'Luotu',
  'attachmentTableHeader.name': 'Nimi',
  'attachmentButton.addAttachment': 'Lisää tiedosto',
  'attachmentButton.downloadAttachment': 'Lataa tiedosto',
  'attachment.uploadOk': 'Tiedosto {fileName} ladattu',
  'attachment.uploadFailed': 'tiedoston {fileName} lataaminen epäonnistui!',
  'workflowReleaseTable.title': 'Kokoonpano',
  'workflowReleaseTableHeader.name': 'Nimi',
  'workflowReleaseTableHeader.description': 'Kuvaus',
  'workflowReleaseTableHeader.updatedBy': 'Päivittäjä',
  'workflowReleaseTableHeader.updated': 'Päivitetty',
  'workflowReleaseTable.addButton': 'Lisää uusi',
  'workflowReleaseTable.viewButton': 'Katso',
  'workflowReleaseTable.exportButton': 'Lataa',
  'workflowRelease.dialogTitle': 'Työnkulun julkaisu',
  'workflowRelease.name': 'Nimi',
  'workflowRelease.description': 'Kuvaus',
  'workflowRelease.releaseCreationFailed': 'Palveluversion luominen epäonnistui, syy: {cause}',
  'publicationsTable.title': 'Julkaisut',
  'publicationsTableHeader.name': 'Tunniste',
  'publicationsTableHeader.description': 'Kuvaus',
  'publicationsTableHeader.createdBy': 'Päivittäjä',
  'publicationsTableHeader.created': 'Luotu',
  'publicationsTableHeader.contentTag': 'Sisältöversio',
  'publicationsTableHeader.workflowTag': 'Palveluversio',
  'publicationsTableHeader.wrenchTag': 'Prosessiversio',
  'publicationsTable.addButton': 'Lisää uusi',
  'publicationsTable.viewButton': 'Katso',
  'publicationsTable.exportButton': 'Lataa',
  'publications.dialogTitle': 'Julkaisu',
  'publications.name': 'Tunniste',
  'publications.description': 'Kuvaus',
  'publications.workflowTag': 'Palveluversio',
  'publications.wrenchTag': 'Prosessiversio',
  'publications.contentTag': 'Sisältöversio',
  'publications.createNewTag': 'Luo uusi versio \"{tag}\"',
  'publications.downloadFailed': 'Julkaisun lataus epäonnistui, syy: {cause}',
  'publications.tagCreationFailed': 'Julkaisun luominen epäonnistui, syy: {cause}',
  'dialobForms.dialog.heading': 'Lomakkeet',
  'dialobForms.table.tooltip.add': 'Lisää',
  'dialobForms.table.label': 'Nimi',
  'dialobForms.table.created': 'Luotu',
  'dialobForms.table.lastSaved': 'Päivitetty',
  'dialobForms.table.tooltip.edit': 'Muokkaa',
  'dialobForms.dialog.emptyTitle': '-',
  'dialobForms.table.tooltip.copy': 'Kopio',
  'dialobForms.table.tooltip.delete': 'Poista',
  'dialobForm.saveFailed': 'Tallennus epäonnistui',
  'dialobForm.downloadFailed': 'Tallennus epäonnistui',
  'dialobForm.deleteFailed': 'Poisto epäonnistui',
  'dialobForm.heading.copyDialog': 'Kopio lomake',
  'dialobForm.heading.addDialog': 'Lisää lomake',
  'dialobForm.dialog.formName': 'ID',
  'dialobForm.dialog.formLabel': 'Nimi',
  'dialobForm.error.invalidFormName': 'Väärä ID',
  'dialobForm.dialog.deleteQuestion': 'Haluatko poistaa lomakkeen \"{formName}\"?',
  'dialobForm.heading.deleteDialog': 'Lomakkeen poisto',
  'dialobForm.review.title': 'Lomakkeen tarkistus',
  'feedback.notenabled': 'Feedback is not enabled for this task',
  'pages': 'Sivut',
  'articles': 'Artikkelit',
  'locale': 'Sijainti',
  'locales': 'Sijainnit',
  'tag': 'Merkintä',
  'links': 'Linkit',
  'releases': 'Julkaisut',
  'options': 'Valinnat',
  'value': 'Arvo',
  'date': 'Päiväys',
  'order': 'Järjestys',
  'description': 'Kuvaus',
  'name': 'Nimi',
  'delete': 'Poista',
  'download': 'Lataa JSON',
  'disable': 'Poista käytöstä',
  'status': 'Status',
  'created': 'Luotu',
  'modified': 'Muokattu',
  'rename': 'Nimeä uudelleen',
  'reorder': 'Järjestä uudelleen',
  'remove': 'Irrota',
  'composer.select.article': 'Valitse artikkelit',
  'toolbar.help': 'Tuki',
  'toolbar.import': 'Tuo dataa',
  'link.type.internal': 'Sisäinen (domainin sisällä)',
  'link.type.external': 'Ulkoinen (domainin ulkopuolella)',
  'link.type.phone': 'Puhelinnumero',
  'imports': 'Tuotu sisältö',
  'imports.select': 'Valitse tuotava tiedosto',
  'imports.import.action': 'Tuonti valittu',
  'article.composer.title': 'Luo uusi artikkeli',
  'article.composer.parent': 'Emoartikkeli',
  'article.composer.parent.unselected': 'Ei valittu',
  'article.create': 'Luo artikkeli',
  'article.name': 'Artikkelin nimi',
  'article.delete.title': 'Poista tämä artikkeli pysyvästi?',
  'article.delete.description': 'Artikkelin poistaminen poistaa sen ja siihen yhdistetyt sivut koko sovelluksesta.',
  'article.edit.title': 'Muokkaa artikkelia',
  'article.edit.parent': 'Emoartikkeli',
  'article.edit.orderhelper': 'Kolmenumeroinen luku järjestelyyn',
  'article.composer.orderhelper': 'Numero valikon järjestelyyn',
  'button.create': 'Luo',
  'button.add': 'Lisää',
  'button.disable': 'Jatka ja poista käytöstä',
  'button.enable': 'Jatka ja salli käyttö',
  'button.remove': 'Jatka ja irrota',
  'button.apply': 'Salli muutokset ja jatka',
  'button.view.all.locales': 'Näytä kaikki sijainnit',
  'button.view.all.releases': 'Näytä kaikki julkaisut',
  'links.message': 'Suurenna rivejä tarkastellaksesi linkki-artikkeli yhteyksiä',
  'link.article.add.title': 'Lisää linkki artikkeliin',
  'link.article.select': 'Valitse artikkeli',
  'link.type': 'Tyyppi',
  'link.url': 'URL / arvo',
  'link.locale.all': 'Kaikki sijainnit',
  'link.content': 'Linkki URL / reitti',
  'link.composer.title': 'Luo uusi linkki',
  'link.composer.descriptionlabel': 'Kuvaus',
  'link.composer.descriptionhelper': 'Teksti, jonka käyttäjä näkee',
  'link.composer.valuehelper': 'URL / linkin reitti (http://www.example.com)',
  'link.edit.title': 'Muokkaa linkkiä',
  'link.delete.title': 'Poista linkki pysyvästi?',
  'link.delete': 'Linkin poistaminen poistaa sen lopullisesti koko sovelluksesta ja sen kaikki yhteydet artikkeleihin/sivuihin menetetään.',
  'link.removepage.title': 'Irrota tämä linkki?',
  'link.removepage': 'Linkin irrottaminen poistaa vain sen yhteyden tähän artikkeliin. Poistaaksesi kohteen pysyvästi, valitse \Poista\"."',
  'link.options': 'Linkkivalinnat',
  'link.options.add': 'Lisää artikkeliin linkkejä',
  'resource.edit.links': 'Lisää ja poista artikkelilinkkejä',
  'link.create': 'Luo linkki',
  'locale.create': 'Luo sijainti',
  'locale.disable.title': 'Poista sijainti käytöstä?',
  'locale.enable.title': 'Salli sijainnin käyttö?',
  'locale.disable': 'Kaikki tätä sijaintia käyttävät sivut ovat käyttöliittymässä piilossa. Sivuja voidaan edelleen muokata.',
  'locale.enable': 'Kaikki tätä sijaintia käyttävät sivut ovat esillä käyttöliittymässä.',
  'locale.composer.title': 'Luo uusi sijainti',
  'locale.composer.helper': 'Kaksikirjaiminen sijaintitunniste',
  'locale.overview': 'Sijainnin käytön yhteenveto',
  'locales.content': 'Tässä sijainnissa olevalla sivulla on sisältöä',
  'locales.nocontent': 'Tässä sijainnissa olevalla sivulla ei ole sisältöä',
  'locales.nopage': 'Tällä sijainnilla ei ole sivua tässä artikkelissa',
  'newpage.title': 'Luo uusi sivu',
  'newpage.info': 'Sivu koostuu paikannetusta sisällöstä ja sen tulee olla yhdistetty artikkeliin.',
  'newpage.article.info': 'Vahvista sivun luominen artikkelille: {article} sijainnilla: {locale}',
  'page.create': 'Luo sivu',
  'pages.save': 'Tallenna sivut',
  'pages.add': 'Lisää sivu',
  'pages.change': 'Muuta sivun sijaintia',
  'pages.change.info': 'Valitse sivu tästä artikkelista ja anna uusi arvo sen sijainnille.',
  'pages.delete': 'Poista sivu',
  'pages.delete.message': 'Valitse artikkelista poistettava sivu.',
  'pages.options': 'Sivuvalinnat',
  'pages.edit.selectpage': 'Select page',
  'pages.edit.selectTargetLocale': 'Select target locale',
  'release.create': 'Luo julkaisu',
  'release.composer.title': 'Luo uusi julkaisu',
  'release.composer.label': 'Merkinnän nimi',
  'release.composer.note': 'Note',
  'release.composer.helper': 'Valinnainen lisätieto tulevaa käyttöä varten',
  'menu.feedbackAllTasks': 'All feedback',
  'feedback.all': 'All feedback',
  'feedback.none': 'No feedback available',
  'feedback.search': 'Search',
  'feedback.search.placeholder': 'Feedback, process, or task id',
  'feedback.search.filter.category': 'Filter by category',
  'feedback.search.filter.subCategory': 'Filter by sub-category',
  'feedback.filter.selectNone': 'None',
  'toolbar.preview': 'Live-esikatselu',
  'workflow.edit.title': 'Muokkaa työnkulkua',
  'workflow.create': 'Luo työnkulku',
  'button.view.all.articles': 'Näytä kaikki artikkelit',
  'button.view.all.pages': 'Näytä kaikki sivut',
  'button.view.all.links': 'Näytä kaikki linkit',
  'button.view.all.workflows': 'Näytä kaikki työnkulut',
  'workflows': 'Työnkulku',
  'associations.add': 'Yhdistä artikkeliin',
  'explorer.pages': 'Sivut',
  'explorer.pages.create': 'Luo sivu',
  'explorer.pages.dualview': 'Kaksoisnäkymä',
  'explorer.locale.empty': 'Ei sijainteja',
  'articles.message': 'Suurenna rivejä tarkastellaksesi artikkeleihin yhdistettyjä sivuja ja muokkaa näitä yhteyksiä',
  'article.deletepage.title': 'Poista tämä sivu?',
  'article.deletepage': 'Sivun poistaminen poistaa sen lopullisesti koko sovelluksesta.',
  'article.options': 'Artikkelivalinnat',
  'article.addlink': 'Lisää tämä linkki artikkeliin',
  'article.links.addremove': 'Lisää ja poista artikkelilinkkejä',
  'article.links': 'Artikkelilinkit',
  'article.links.sitelinks': 'Sivustolinkit',
  'article.links.remove': 'Irrota/poista linkkiyhteys tähän artikkeliin',
  'article.workflows.addremove': 'Lisää ja poista artikkelien työnkulkuja',
  'article.workflows': 'Artikkelien työnkulut',
  'article.workflows.add': 'Yhdistä tämä työnkulku tähän artikkeliin',
  'article.workflows.remove': 'Poista tämän työnkulun yhteys tähän artikkeliin',
  'article.workflows.siteworkflows': 'Site workflows',
  'button.view': 'Katsele',
  'button.addremove': 'Lisää/Irrota',
  'composer.article.title': 'Artikkeli',
  'composer.article.desc': 'Ryhmä yhdistettyjä sivuja, linkkejä, työnkulkuja ja sijainteja',
  'composer.locale.title': 'Sijainti',
  'composer.locale.desc': 'Lisää, aktivoi ja deaktivoi sisällön kieliä globaalisti',
  'composer.page.title': 'Sivu',
  'composer.page.desc': 'Tiedosto, joka edustaa yhtä kieltä ja siihen yhdistettyjä linkkejä ja työnkulkuja artikkelin sisällä',
  'composer.link.title': 'Linkki',
  'composer.link.desc': 'Sisäiset linkit yhdistävät sisältöön domainin sisällä ja ulkoiset linkit yhdistävät sisältöön domainin ulkopuolella',
  'composer.workflow.title': 'Työnkulku',
  'composer.workflow.desc': 'Yhdistä lomakkeet ja prosessit',
  'composer.release.title': 'Julkaise',
  'composer.release.desc': 'Luo kuva sivun kaikesta sisällöstä tietyssä tilassa testaamis- ja tuotantotarkoituksiin',
  'toolbar.dashboard': 'Hallintatyökalu',
  'dashboard.view.helper': 'Katsele, muokkaa ja poista sisältöjä',
  'link.associate.title': 'Yhdistä linkki artikkeliin',
  'link.options.edit': 'Muokkaa artikkelin linkkejä',
  'link.options.remove': 'Irrota linkit artikkelista',
  'resource.options': 'Resurssivalinnat',
  'resource.edit.workflows': 'Lisää ja poista artikkelityönkulkuja',
  'workflow.associate.title': 'Yhdistä työnkulku artikkeliin',
  'workflow.composer.title': 'Lisää työnkulku',
  'workflow.composer.name': 'Paikannettu nimi',
  'workflow.technicalname': 'Tekninen nimi',
  'workflow.composer.select': 'Valitse olemassaoleva työnkulku',
  'workflow.composer.helper': 'Käyttäjille näytettävä nimi',
  'workflow.composer.placeholder': 'Lupahakemus',
  'workflow.delete.title': 'Poista tämä työnkulku pyvyvästi?',
  'workflow.delete': 'Työnkulun poistaminen poistaa sen koko sovelluksesta.',
  'workflow.removepage.title': 'Irrota tämä työnkulku?',
  'workflow.removepage': 'Työnkulun irrottaminen poistaa vain sen yhteyden tähän artikkeliin. Poistaaksesi kohteen kokonaan/pysyvästi, valitse \Poista\"."',
  'workflow.options': 'Työnkulun valinnat',
  'workflow.add': 'Lisää työnkulku',
  'workflow.edit': 'Muokkaa työnkulkua',
  'workflow.remove': 'Irrota työnkulku',
  'toolbar.articles': 'Artikkeliyhteenveto',
  'toolbar.newarticle': 'Luo uusi artikkeli',
  'toolbar.newlocale': 'Lisää uusi sijainti',
  'toolbar.explorer': 'Explorer',
  'toolbar.links': 'Linkkiyhteenveto',
  'toolbar.workflows': 'Työnkulkuyhteenveto',
  'toolbar.releases': 'Julkaisut',
  'toolbar.locales': 'Sijainnit'
}