export const sv = {
  'tasksView.title': 'Uppgiften',
  'tasksTableHeader.taskName': 'Uppgiftens namn',
  'tasksTableHeader.category': 'Typ',
  'tasksTableHeader.status': 'Status',
  'tasksTableHeader.dueDate': 'Deadline',
  'tasksTableHeader.priority': 'Prioritet',
  'tasksTableHeader.assigned': 'Hanterare',
  'tasksTableAction.editTask': 'Redigera uppgiften',
  'tasksTableAction.deleteTask': 'Ta bort uppgift',
  'taskPriority.low': 'Inte bråttom',
  'taskPriority.normal': 'Normal',
  'taskPriority.high': 'Brådskande',
  'taskDialog.priority': 'Prioritet',
  'taskDialog.subject': 'Ämne',
  'taskDialog.description': 'Kundupgifter',
  'taskDialog.dueDate': 'Deadline',
  'taskDialog.assignedTo': 'Hanteraregrupp',
  'taskDialog.assignedUser': 'Användare',
  'taskDialog.status': 'Status',
  'taskDialog.task': 'Uppgiften',
  'taskDialog.category': 'Typ',
  'taskDialog.source': 'Källa',
  'task.priority.low': 'Inte bråttom',
  'task.priority.normal': 'Normal',
  'task.priority.high': 'Brådskande',
  'task.status.new': 'Nya',
  'task.status.open': 'Läsning',
  'task.status.completed': 'Redo',
  'task.status.rejected': 'Övergiven',
  'task.form.review': 'Review form',
  'task.form.feedback.manage': 'Manage feedback',
  'task.created': 'Skapad',
  'task.updated': 'Uppdaterad',
  'comments': 'Meddelanden',
  'task.comments.external.createTask': 'Skapa uppgift innan du lägger till externa kommentarer',
  'task.comments.internal.createTask': 'Skapa uppgift innan du lägger till interna kommentarer',
  'task.attachments.createTask': 'Skapa uppgift innan du laddar upp bilagor',
  'task.comments.external.added': 'Extern kommentar har lagts till',
  'task.feedback.publishedSaved': 'Publicerat svar har sparats',
  'task.comments.internal.added': 'Intern kommentar har lagts till',
  'internalComments': 'Interna kommentarer',
  'externalComments': 'Kundmeddelanden',
  'comment.store': 'Spara',
  'comment.add': 'Skriv en kommentar',
  'comment.addInternal': 'Skriva en intern kommentar',
  'comment.addExternal': 'Skriva ett meddelande till kunden',
  'comment.reply': 'Ansvar',
  'taskButton.addTask': 'Mer uppgift',
  'taskButton.refresh': 'Sök efter nya uppgifter',
  'taskButton.accept': 'Acceptera',
  'taskButton.cancel': 'Avbryt',
  'table.body.emptyDataSourceMessage': 'Ingen data',
  'table.body.filterRow.filterTooltip': 'Filtrera',
  'table.body.deleteTooltip': 'Radera',
  'table.body.editRow.deleteText': 'Är du säker på att du vill radera den här uppgiften?',
  'table.body.editRow.cancelTask': 'Avbryt',
  'table.body.editRow.saveTask': 'Spara',
  'table.header.actions': 'Funktioner',
  'table.pagination.labelDisplayedRows': '{from}-{to} av {count}',
  'table.pagination.labelRowsPerPage': 'Rader per sida:',
  'table.pagination.firstPage': 'Första sidan',
  'table.pagination.previousPage': 'Färegående',
  'table.pagination.nextPage': 'Nästa',
  'table.pagination.lastPage': 'Sista sidan',
  'table.toolbar.search': 'Söka',
  'table.toolbar.showColumnsTitle': 'Visa kolumner',
  'table.toolbar.addRemoveColumns': 'Add or remove columns',
  'taskLink.title': 'Uppgiften link',
  'taskLink.button.open': 'Uppgifter som kunden lämnat',
  'taskLink.pdf.open': 'PDF',
  'explorer.title': 'Public feedback',
  'explorer.login': 'Logga in',
  'locale.fi': 'Finska',
  'locale.sv': 'Svenska',
  'locale.en': 'Engelska',
  'app.logout': 'Logga ut',
  'app.login': 'Logga in',
  'app.feedback': 'Respons',
  'main.articles.all': 'Alla Artiklar',
  'main.links.all': 'Alla Länkar',
  'main.services.all': 'Alla Tjänster',
  'main.flows.all': 'Alla Serviceflöden',
  'main.debug': 'Debuggning',
  'main.compare': 'Jämföra',
  'main.decisions.all': 'Alla Beslutstabeller',
  'menu.dashboard': 'Översiktspanel',
  'menu.profile': 'Användarens profil',
  'menu.tasks': 'Tasks',
  'menu.evaluations': 'Förfrågningar',
  'menu.forms': 'Dialob',
  'menu.queues': 'Queues',
  'menu.users': 'Användare',
  'menu.help': 'Anvisningar',
  'menu.flow': 'theWrench',
  'menu.processes': 'Övervakning',
  'menu.reports': 'Rapportering',
  'menu.workflows': 'Konfigurera',
  'menu.logout': 'Logga ut',
  'menu.workflowTags': 'Arbetsflödestaggar',
  'menu.publications': 'Offentliggörande',
  'menu.services': 'Tjänster',
  'menu.content': 'Stencil',
  'menu.calendar': 'Kalender',
  'menu.feedback': 'Feedback',
  'menu.compose': 'Compose',
  'menu.pages': 'Sidot',
  'menu.articles': 'Artiklar',
  'menu.links': 'Länkar',
  'menu.locales': 'Språk',
  'menu.migrations': 'Migrationer',
  'menu.templates': 'Mallar',
  'menu.flows': 'Serviceflöden',
  'menu.decisions': 'Beslutstabeller',
  'menu.debug': 'Debuggning',
  'menu.releases': 'Släpp',
  'menu.compare': 'Jämföra',
  'front.intro.title': 'Välkommen!',
  'profile.title': 'Användarprofil',
  'profile.user.name': 'Namn:',
  'profile.user.email': 'e-post:',
  'profile.user.role': 'Roll:',
  'profile.user.phone': 'Telefon:',
  'profile.app.version': 'Applikationsversion:',
  'button.cancel': 'Cancel',
  'button.confirmDelete': 'Ta bort',
  'button.delete': 'Ta bort denna feedback',
  'button.delete.template': 'Ta bort denna mall',
  'button.delete.link': 'Avlägsna denna länk',
  'button.delete.article': 'Avlägsna denna artikel',
  'button.delete.page': 'Avlägsna denna sidan',
  'button.unpublish': 'Avlägsna denna feedback',
  'button.update': 'Uppdatering',
  'button.publish': 'Ladda upp',
  'button.accept': 'Acceptera',
  'button.edit': 'Öppna',
  'button.close': 'Stäng',
  'button.reject': 'Avslå',
  'button.send': 'Skicka',
  'button.dismiss': 'Stäng',
  'button.editRoles': 'Redigera',
  'button.select': 'Select',
  'error.minTextLength': 'Texten måste vara minst {minLength} tecken lång.',
  'error.maxTextLength': 'Texten måste vara max {max} tecken lång.',
  'error.valueRequired': 'Nödvändig',
  'error.title': 'Fel!',
  'error.dialob.session': 'Blanketten kan inte öppnas just nu. Vänligen försök på nytt senare',
  'error.errorLoadingData': 'Fel då försöker ladda data',
  'error.unauthorized.title': 'Du saknar rättighet till tjänsten',
  'error.unauthorized.text': 'Tag kontakt med IT genom att göra en Tiket: Rapportera IT problem -> Problem med inloggning.',
  'error.unauthorizedAccess': 'Du saknar rättighet till tjänsten',
  'error.dataAccess': 'Fel vid drift',
  'error.statusOpenError': 'Required when status is open',
  'error.workflowCreation': 'Error on workflow creation, check worflow name for duplicates',
  'table.body.addTooltip': 'Lägg till',
  'table.body.editTooltip': 'Öppna',
  'table.body.editRow.deleteMessage': 'Är du säker på att du vill radera detta?',
  'workflowTable.title': 'Sammansättning',
  'workflowTableHeader.name': 'Namn',
  'workflowTableHeader.formName': 'Formulär',
  'workflowTableHeader.flowName': 'Process',
  'workflowTableHeader.updated': 'Uppdaterad',
  'workflowTable.addButton': 'Lägg till ny',
  'workflowTable.editButton': 'Editera',
  'workflow.dialogTitle': 'Nytt arbetsflöde',
  'workflow.name': 'Namn',
  'workflow.form.formName': 'Formulär namn',
  'workflow.form.formTag': 'Formulär version',
  'workflow.flowName': 'Process',
  'processTable.title': 'Arbeten',
  'processTableHeader.workflow': 'Typ',
  'processTableHeader.user': 'Användare',
  'processTableHeader.status': 'Status',
  'processTableHeader.created': 'Skapad',
  'processTableHeader.questionnaireId': 'Formulär',
  'process.status.ANSWERED': 'Skickad',
  'process.status.CREATED': 'Skapad',
  'process.status.ANSWERING': 'På hälft',
  'process.status.IN_PROGRESS': 'Under arbete',
  'process.status.WAITING': 'Väntar',
  'process.status.COMPLETED': 'Färdig',
  'process.status.REJECTED': 'Avslagen',
  'comment.button': 'Ge respons',
  'comment.title': 'Ge respons',
  'comment.form.email': 'E-post',
  'comment.form.feedbackType': 'Typ',
  'comment.form.body': 'Meddelande',
  'comment.type.general': 'Ge respons',
  'comment.type.propose': 'Föreslå ny tjänst',
  'comment.type.contact': 'Tag kontakt',
  'comment.submitted.success': 'Tack för din respons!',
  'comment.submitted.failure': 'Överföringen lyckades inte!',
  'spoTasksTableHeader.taskName': 'Uppgiftens namn',
  'spoTasksTableHeader.category': 'Typ',
  'spoTasksTableHeader.status': 'Status',
  'spoTasksTableHeader.priority': 'Prioritet',
  'spoTasksTableHeader.dueDate': 'Förfallodag',
  'spoTasksTableHeader.assigned': 'Hanterare',
  'spoTasksTableHeader.assignedUser': 'Användare',
  'spoTasksTableHeader.created': 'Ankomnstdatum',
  'spoTasksTableHeader.clientName': 'Kund',
  'taskDialog.clientIdentificator': 'Kundens namn',
  'taskDialog.assignedUserEmail': 'Användarens e-post',
  'task.editRoles': 'Arbetsgrupper',
  'Questionnaire': 'Formulär',
  'Manual': 'Manuellt',
  'Protected': 'Skyddad',
  'Normal': 'Normalt',
  'Represented': 'Representerade',
  'CustomerCreated': 'Kund skapad',
  'Internal': 'Intern',
  'task.role.assignedAllUsers': 'Alla användare',
  'task.feedback.published': 'Publicerat svar',
  'confirm.close.title': 'Bekräftelse krävs',
  'confirm.unsavedChanges': 'Osparade ändringar kommer att gå förlorade, vill du fortsätta?',
  'task.statistics.statusCount': 'Efter status',
  'task.statistics.priorityCount': 'Efter prioritet',
  'task.statistics.daily': 'Dagligen',
  'task.statistics.overdue': 'Försenad',
  'feedback.button': 'Skicka respons',
  'feedback.thanks': 'Tack för din respons!',
  'feedback.create.title': 'Create public reply to customer feedback',
  'feedback.title': 'Public reply to customer feedback',
  'feedback.update.title': 'Edit public reply to customer feedback',
  'feedback.description': 'Beskrivning',
  'feedback.name': 'Ditt namn',
  'feedback.sendScreenshot': 'Skicka en skärmdump',
  'feedback.close': 'Avbryt',
  'feedback.send': 'Skicka',
  'feedback.category': 'Category',
  'feedback.subCategory': 'Subcategory',
  'feedback.myReply': 'Reply to customer',
  'feedback.noFeedback.info1': 'No reply to publish!',
  'feedback.noFeedback.info2': 'Please send an external comment to customer, then you can publish the external comment.',
  'feedback.customerFeedback': 'Customer feedback',
  'feedback.customerApprovals': 'Customer approvals',
  'feedback.sourceTaskId': 'Source task id',
  'feedback.formName': 'Form name',
  'feedback.dateReceived': 'Date received from customer',
  'feedback.createdBy': 'Skapat av',
  'feedback.updatedBy': 'Uppdaterad av',
  'feedback.updated': 'Senast uppdaterad',
  'feedback.notPublished': 'This feedback is not published',
  'feedback.isPublished': 'This feedback is published and publicly viewable',
  'feedback.delete.confirmTitle': 'Ta bort feedback?',
  'feedback.delete.confirmText': 'Är du säker på att du vill ta bort denna feedback?',
  'help.title': 'Anvisningar',
  'attachmentView.title': 'Attachments',
  'attachmentTableHeader.size': 'Size',
  'attachmentTableHeader.updated': 'Updated',
  'attachmentTableHeader.created': 'Created',
  'attachmentTableHeader.name': 'Name',
  'attachmentButton.addAttachment': 'Add file',
  'attachmentButton.downloadAttachment': 'Download file',
  'attachmentButton.deleteAttachment': 'Remove file',
  'attachment.uploadOk': 'File {fileName} uploaded',
  'attachment.uploadFailed': 'File {fileName} upload failed!',
  'workflowReleaseTable.title': 'Workflow release',
  'workflowReleaseTableHeader.name': 'Name',
  'workflowReleaseTableHeader.description': 'Description',
  'workflowReleaseTableHeader.updatedBy': 'Updater',
  'workflowReleaseTableHeader.updated': 'Updated',
  'workflowReleaseTable.addButton': 'Add',
  'workflowReleaseTable.viewButton': 'View',
  'workflowReleaseTable.exportButton': 'Export',
  'workflowRelease.dialogTitle': 'View workflow release',
  'workflowRelease.name': 'Release name',
  'workflowRelease.description': 'Description',
  'workflowRelease.releaseCreationFailed': 'Workflow tag creation failed, cause: {cause}',
  'publicationsTable.title': 'Release',
  'publicationsTableHeader.name': 'Release name',
  'publicationsTableHeader.description': 'Description',
  'publicationsTableHeader.createdBy': 'User',
  'publicationsTableHeader.created': 'Created',
  'publicationsTableHeader.contentTag': 'Content tag',
  'publicationsTableHeader.workflowTag': 'Workflow tag',
  'publicationsTableHeader.wrenchTag': 'theWrench tag',
  'publicationsTableHeader.liveDate': 'Lanseringsdatum',
  'publicationsTable.addButton': 'Tillägg',
  'publicationsTable.viewButton': 'Utsikt',
  'publicationsTable.exportButton': 'Export',
  'publicationsTable.uploadButton': 'Uppladdning',
  'publications.external': 'This is externally configured deployment and will be in effect when there are no other deployments',
  'publications.changeStatus': 'Ändra driftsstatusen',
  'publications.currentStatus': 'Nuvarande distributionsstatus',
  'publications.deploy': 'Driftsätt nu',
  'publications.dialogTitle': 'Release',
  'publications.name': 'Release name',
  'publications.description': 'Description',
  'publications.workflowTag': 'Workflow tag',
  'publications.wrenchTag': 'Wrench tag',
  'publications.contentTag': 'Content tag',
  'publications.createNewTag': 'Create new tag \"{tag}\"',
  'publications.downloadFailed': 'Release download failed, cause: {cause}',
  'publications.tagCreationFailed': 'Release creation failed, cause: {cause}',
  'dialobForms.dialog.heading': 'Forms',
  'dialobForms.table.tooltip.add': 'Add',
  'dialobForms.table.label': 'ID',
  'dialobForms.table.created': 'Created',
  'dialobForms.table.lastSaved': 'Updated',
  'dialobForms.table.tooltip.edit': 'Edit',
  'dialobForms.dialog.emptyTitle': '-',
  'dialobForms.table.tooltip.copy': 'Copy',
  'dialobForms.table.tooltip.delete': 'Remove',
  'dialobForm.saveFailed': 'Saving failed',
  'dialobForm.downloadFailed': 'Saving failed',
  'dialobForm.deleteFailed': 'Remove failed',
  'dialobForm.heading.copyDialog': 'Copy',
  'dialobForm.heading.addDialog': 'Add',
  'dialobForm.dialog.formName': 'ID',
  'dialobForm.dialog.formLabel': 'Name',
  'dialobForm.error.invalidFormName': 'Incorrect ID',
  'dialobForm.dialog.deleteQuestion': 'Do you want to remove form \"{formName}\"?',
  'dialobForm.heading.deleteDialog': 'Remove form',
  'dialobForm.review.title': 'Form review',
  'feedback.notenabled': 'Feedback is not enabled for this task',
  'search.field.label': 'Sök',
  'search.all': 'Alla',
  'toolbar.search': 'Sök',
  'toolbar.stencil': 'theStencil',
  'toolbar.wrench': 'theWrench',
  'menu.feedbackAllTasks': 'All feedback',
  'feedback.all': 'All feedback',
  'feedback.none': 'No feedback available',
  'feedback.search': 'Search',
  'feedback.search.placeholder': 'Feedback, process, or task id',
  'feedback.search.filter.category': 'Filter by category',
  'feedback.search.filter.subCategory': 'Filter by sub-category',
  'feedback.filter.selectNone': 'None'
}