export const sv = {
  'document.title': 'DigiExpress',
  'booleanValue.true': 'Ja',
  'booleanValue.false': 'Inga',
  'eveli.textSeparatorColon': ':',
  'eveli.permissions.none.title': 'Oops!',
  'eveli.permissions.none.desc1': 'Du har inte rätt åtkomsträttigheter för att använda denna applikation.',
  'eveli.permissions.none.desc2': 'Kontakta din systemadministratör.',
  'tasksView.title': 'Uppgiften',
  'tasksTableHeader.taskName': 'Uppgiftens namn',
  'tasksTableHeader.category': 'Typ',
  'tasksTableHeader.status': 'Status',
  'tasksTableHeader.dueDate': 'Deadline',
  'tasksTableHeader.priority': 'Prioritet',
  'tasksTableHeader.assigned': 'Hanterare',
  'tasksTableAction.editTask': 'Redigera uppgiften',
  'tasksTableAction.deleteTask': 'Ta bort uppgift',
  'taskPriority.low': 'Inte bråttom',
  'taskPriority.normal': 'Normal',
  'taskPriority.high': 'Brådskande',
  'taskDialog.priority': 'Prioritet',
  'taskDialog.subject': 'Ämne',
  'taskDialog.description': 'Kundupgifter',
  'taskDialog.dueDate': 'Deadline',
  'taskDialog.assignedTo': 'Hanteraregrupp',
  'taskDialog.assignedUser': 'Användare',
  'taskDialog.status': 'Status',
  'taskDialog.task': 'Uppgiften',
  'taskDialog.category': 'Typ',
  'taskDialog.source': 'Källa',
  'taskDialog.additionalInfo': 'Tilläggsinformation',
  'task.priority.low': 'Inte bråttom',
  'task.priority.normal': 'Normal',
  'task.priority.high': 'Brådskande',
  'task.status.new': 'Nya',
  'task.status.open': 'Läsning',
  'task.status.completed': 'Redo',
  'task.status.rejected': 'Övergiven',
  'task.form.review': 'Review form',
  'task.form.feedback.manage': 'Manage feedback',
  'task.form.feedback.updated': 'Uppdatering av feedback lyckades!',
  'task.created': 'Skapad',
  'task.updated': 'Uppdaterad',
  'comments': 'Meddelanden',
  'task.comments.external.createTask': 'Skapa uppgift innan du lägger till externa kommentarer',
  'task.comments.internal.createTask': 'Skapa uppgift innan du lägger till interna kommentarer',
  'task.attachments.createTask': 'Skapa uppgift innan du laddar upp bilagor',
  'task.comments.external.added': 'Extern kommentar har lagts till',
  'task.feedback.publishedSaved': 'Publicerat svar har sparats',
  'task.comments.internal.added': 'Intern kommentar har lagts till',
  'internalComments': 'Interna kommentarer',
  'externalComments': 'Kundmeddelanden',
  'comment.store': 'Spara',
  'comment.add': 'Skriv en kommentar',
  'comment.addInternal': 'Skriva en intern kommentar',
  'comment.addExternal': 'Skriva ett meddelande till kunden',
  'comment.reply': 'Ansvar',
  'taskButton.addTask': 'Mer uppgift',
  'taskButton.refresh': 'Sök efter nya uppgifter',
  'taskButton.accept': 'Acceptera',
  'taskButton.cancel': 'Avbryt',
  'table.body.emptyDataSourceMessage': 'Ingen data',
  'table.body.filterRow.filterTooltip': 'Filtrera',
  'table.body.deleteTooltip': 'Radera',
  'table.body.editRow.deleteText': 'Är du säker på att du vill radera den här uppgiften?',
  'table.body.editRow.cancelTask': 'Avbryt',
  'table.body.editRow.saveTask': 'Spara',
  'table.header.actions': 'Funktioner',
  'table.pagination.labelDisplayedRows': '{from}-{to} av {count}',
  'table.pagination.labelRowsPerPage': 'Rader per sida:',
  'table.pagination.firstPage': 'Första sidan',
  'table.pagination.previousPage': 'Färegående',
  'table.pagination.nextPage': 'Nästa',
  'table.pagination.lastPage': 'Sista sidan',
  'table.toolbar.search': 'Söka',
  'table.toolbar.showColumnsTitle': 'Visa kolumner',
  'table.toolbar.addRemoveColumns': 'Lägg till eller ta bort kolumner',
  'taskLink.title': 'Uppgiften link',
  'taskLink.button.open': 'Uppgifter som kunden lämnat',
  'taskLink.pdf.open': 'PDF',
  'explorer.title': 'Public feedback',
  'explorer.login': 'Logga in',
  'locale.fi': 'Finska',
  'locale.sv': 'Svenska',
  'locale.en': 'Engelska',
  'app.logout': 'Logga ut',
  'app.login': 'Logga in',
  'app.feedback': 'Respons',
  'main.articles.all': 'Alla Artiklar',
  'main.links.all': 'Alla Länkar',
  'main.services.all': 'Alla Tjänster',
  'main.flows.all': 'Alla Serviceflöden',
  'main.debug': 'Debuggning',
  'main.compare': 'Jämföra',
  'main.decisions.all': 'Alla Beslutstabeller',
  'menu.dashboard': 'Översiktspanel',
  'menu.profile': 'Användarens profil',
  'menu.tasks': 'Uppgifter',
  'menu.evaluations': 'Förfrågningar',
  'menu.forms': 'Dialob',
  'menu.queues': 'Queues',
  'menu.users': 'Användare',
  'menu.help': 'Anvisningar',
  'menu.flow': 'theWrench',
  'menu.processes': 'Övervakning',
  'menu.reports': 'Rapportering',
  'menu.workflows': 'Konfigurera',
  'menu.logout': 'Logga ut',
  'menu.workflowTags': 'Arbetsflödestaggar',
  'menu.publications': 'Offentliggörande',
  'menu.services': 'Tjänster',
  'menu.content': 'Stencil',
  'menu.calendar': 'Kalender',
  'menu.feedback': 'Feedback',
  'menu.compose': 'Compose',
  'menu.pages': 'Sidot',
  'menu.articles': 'Artiklar',
  'menu.links': 'Länkar',
  'menu.locales': 'Språk',
  'menu.migrations': 'Migrationer',
  'menu.templates': 'Mallar',
  'menu.flows': 'Serviceflöden',
  'menu.decisions': 'Beslutstabeller',
  'menu.debug': 'Debuggning',
  'menu.releases': 'Släpp',
  'menu.compare': 'Jämföra',
  'front.intro.title': 'Välkommen!',
  'profile.title': 'Användarprofil',
  'profile.user.name': 'Namn:',
  'profile.user.email': 'e-post:',
  'profile.user.role': 'Roll:',
  'profile.user.phone': 'Telefon:',
  'profile.app.version': 'Applikationsversion:',
  'button.cancel': 'Avboka',
  'button.confirmDelete': 'Ta bort',
  'button.delete': 'Ta bort denna feedback',
  'button.delete.template': 'Ta bort denna mall',
  'button.delete.link': 'Avlägsna denna länk',
  'button.delete.article': 'Avlägsna denna artikel',
  'button.delete.page': 'Avlägsna denna sidan',
  'button.unpublish': 'Avlägsna denna feedback',
  'button.update': 'Uppdatering',
  'button.publish': 'Ladda upp',
  'button.accept': 'Acceptera',
  'button.edit': 'Öppna',
  'button.close': 'Stäng',
  'button.reject': 'Avslå',
  'button.send': 'Skicka',
  'button.dismiss': 'Stäng',
  'button.editRoles': 'Redigera',
  'button.select': 'Select',
  'error.minTextLength': 'Texten måste vara minst {minLength} tecken lång.',
  'error.maxTextLength': 'Texten måste vara max {max} tecken lång.',
  'error.valueRequired': 'Nödvändig',
  'error.title': 'Fel!',
  'error.dialob.session': 'Blanketten kan inte öppnas just nu. Vänligen försök på nytt senare',
  'error.errorLoadingData': 'Fel då försöker ladda data',
  'error.unauthorized.title': 'Du saknar rättighet till tjänsten',
  'error.unauthorized.text': 'Tag kontakt med IT genom att göra en Tiket: Rapportera IT problem -> Problem med inloggning.',
  'error.unauthorizedAccess': 'Du saknar rättighet till tjänsten',
  'error.dataAccess': 'Fel vid drift',
  'error.statusOpenError': 'Required when status is open',
  'error.workflowCreation': 'Error on workflow creation, check worflow name for duplicates',
  'table.body.addTooltip': 'Lägg till',
  'table.body.editTooltip': 'Öppna',
  'table.body.editRow.deleteMessage': 'Är du säker på att du vill radera detta?',
  'workflowTable.title': 'Sammansättning',
  'workflowTableHeader.name': 'Namn',
  'workflowTableHeader.formName': 'Formulär',
  'workflowTableHeader.flowName': 'Process',
  'workflowTableHeader.updated': 'Uppdaterad',
  'workflowTable.addButton': 'Lägg till ny',
  'workflowTable.editButton': 'Editera',
  'workflow.dialogTitle': 'Nytt arbetsflöde',
  'workflow.name': 'Namn',
  'workflow.form.formName': 'Formulär namn',
  'workflow.form.formTag': 'Formulär version',
  'workflow.flowName': 'Process',
  'processTable.title': 'Arbeten',
  'processTableHeader.workflow': 'Typ',
  'processTableHeader.user': 'Användare',
  'processTableHeader.status': 'Status',
  'processTableHeader.created': 'Skapad',
  'processTableHeader.questionnaireId': 'Formulär',
  'process.status.ANSWERED': 'Skickad',
  'process.status.CREATED': 'Skapad',
  'process.status.ANSWERING': 'På hälft',
  'process.status.IN_PROGRESS': 'Under arbete',
  'process.status.WAITING': 'Väntar',
  'process.status.COMPLETED': 'Färdig',
  'process.status.REJECTED': 'Avslagen',
  'comment.button': 'Ge respons',
  'comment.title': 'Ge respons',
  'comment.form.email': 'E-post',
  'comment.form.feedbackType': 'Typ',
  'comment.form.body': 'Meddelande',
  'comment.type.general': 'Ge respons',
  'comment.type.propose': 'Föreslå ny tjänst',
  'comment.type.contact': 'Tag kontakt',
  'comment.submitted.success': 'Tack för din respons!',
  'comment.submitted.failure': 'Överföringen lyckades inte!',
  'spoTasksTableHeader.taskName': 'Uppgiftens namn',
  'spoTasksTableHeader.category': 'Typ',
  'spoTasksTableHeader.status': 'Status',
  'spoTasksTableHeader.priority': 'Prioritet',
  'spoTasksTableHeader.dueDate': 'Förfallodag',
  'spoTasksTableHeader.assigned': 'Hanterare',
  'spoTasksTableHeader.assignedUser': 'Användare',
  'spoTasksTableHeader.created': 'Ankomnstdatum',
  'spoTasksTableHeader.clientName': 'Kund',
  'spoTasksTableHeader.additionalInfo': 'Info',
  'taskDialog.clientIdentificator': 'Kundens namn',
  'taskDialog.assignedUserEmail': 'Användarens e-post',
  'task.editRoles': 'Arbetsgrupper',
  'Questionnaire': 'Formulär',
  'Manual': 'Manuellt',
  'Protected': 'Skyddad',
  'Normal': 'Normalt',
  'Represented': 'Representerade',
  'CustomerCreated': 'Kund skapad',
  'Internal': 'Intern',
  'task.role.assignedAllUsers': 'Alla användare',
  'task.feedback.published': 'Publicerat svar',
  'confirm.close.title': 'Bekräftelse krävs',
  'confirm.unsavedChanges': 'Osparade ändringar kommer att gå förlorade, vill du fortsätta?',
  'task.statistics.statusCount': 'Efter status',
  'task.statistics.priorityCount': 'Efter prioritet',
  'task.statistics.daily': 'Dagligen',
  'task.statistics.overdue': 'Försenad',
  'feedback.button': 'Skicka respons',
  'feedback.thanks': 'Tack för din respons!',
  'feedback.create.title': 'Skapa offentliga svar på kundfeedback',
  'feedback.title': 'Offentligt svar på kundfeedback',
  'feedback.update.title': 'Redigera offentligt svar på kundfeedback',
  'feedback.description': 'Beskrivning',
  'feedback.name': 'Ditt namn',
  'feedback.sendScreenshot': 'Skicka en skärmdump',
  'feedback.close': 'Avbryt',
  'feedback.send': 'Skicka',
  'feedback.taskReferenceId': 'Ärende-ID',
  'feedback.taskId': 'Ärende-ID',
  'feedback.mainCategory': 'Ämne',
  'feedback.subCategory': 'Specifikt ämnesområde',
  'feedback.feedbackValue': 'Kundfeedback',
  'feedback.customerTitle': 'Feedback titel',
  'feedback.myReply': 'Svara kunden',
  'feedback.noFeedback.info1': 'Inget svar att publicera!',
  'feedback.noFeedback.info2': 'Please send an external comment to customer, then you can publish the external comment.',
  'feedback.customerFeedback': 'Kundfeedback',
  'feedback.customerApprovals': 'Kundgodkännanden',
  'feedback.sourceTaskId': 'Source task id',
  'feedback.formName': 'Formnamn',
  'feedback.dateReceived': 'Datum mottaget från kund',
  'feedback.createdBy': 'Skapat av',
  'feedback.updatedBy': 'Uppdaterad av',
  'feedback.updated': 'Senast uppdaterad',
  'feedback.notPublished': 'This feedback is not published',
  'feedback.isPublished': 'This feedback is published and publicly viewable',
  'feedback.delete.confirmTitle': 'Ta bort feedback?',
  'feedback.delete.confirmText': 'Är du säker på att du vill ta bort denna feedback?',
  'help.title': 'Anvisningar',
  'attachmentView.title': 'Fastsättning',
  'attachmentTableHeader.size': 'Storlek',
  'attachmentTableHeader.updated': 'Uppdaterad',
  'attachmentTableHeader.created': 'Skapad',
  'attachmentTableHeader.name': 'Ämne',
  'attachmentButton.addAttachment': 'Lägg till fil',
  'attachmentButton.downloadAttachment': 'Ladda ner filen',
  'attachmentButton.deleteAttachment': 'Ta bort fil',
  'attachment.uploadOk': 'Fil {fileName} uploaded',
  'attachment.uploadFailed': 'Fil {fileName} upload failed!',
  'attachment.delete.confirmTitle': 'Delete file?',
  'attachment.delete.confirmText': 'Är du säker på att du vill ta bort denna {fileName}?',
  'attachment.deleteFailed': 'File {fileName} delete failed!',
  'workflowReleaseTable.title': 'Workflow release',
  'workflowReleaseTableHeader.name': 'Name',
  'workflowReleaseTableHeader.description': 'Description',
  'workflowReleaseTableHeader.updatedBy': 'Updater',
  'workflowReleaseTableHeader.updated': 'Updated',
  'workflowReleaseTable.addButton': 'Add',
  'workflowReleaseTable.viewButton': 'View',
  'workflowReleaseTable.exportButton': 'Export',
  'workflowRelease.dialogTitle': 'View workflow release',
  'workflowRelease.name': 'Release name',
  'workflowRelease.description': 'Description',
  'workflowRelease.releaseCreationFailed': 'Workflow tag creation failed, cause: {cause}',
  'publicationsTable.title': 'Publikationer',
  'publicationsTableHeader.name': 'Publikationer nam',
  'publicationsTableHeader.description': 'Beskrivning',
  'publicationsTableHeader.createdBy': 'User',
  'publicationsTableHeader.created': 'Skapad',
  'publicationsTableHeader.contentTag': 'Innehållstagg',
  'publicationsTableHeader.workflowTag': 'Workflow tag',
  'publicationsTableHeader.wrenchTag': 'theWrench tag',
  'publicationsTableHeader.liveDate': 'Lanseringsdatum',
  'publicationsTable.addButton': 'Tillägg',
  'publicationsTable.viewButton': 'Utsikt',
  'publicationsTable.exportButton': 'Export',
  'publicationsTable.uploadButton': 'Uppladdning',
  'publications.external': 'Detta är externt konfigurerad distribution och kommer att gälla när det inte finns några andra distributioner',
  'publications.changeStatus': 'Ändra driftsstatusen',
  'publications.currentStatus': 'Nuvarande distributionsstatus',
  'publications.remove': 'Ta bort distributionen',
  'publications.deploy': 'Driftsätt nu',
  'publications.dialogTitle': 'Skapa ny publikation',
  'publications.name': 'Utgivningsnamn',
  'publications.description': 'Description',
  'publications.workflowTag': 'Workflow tag',
  'publications.wrenchTag': 'theWrench tag',
  'publications.contentTag': 'Content tag',
  'publications.createNewTag': 'Create new tag \"{tag}\"',
  'publications.downloadFailed': 'Release download failed, cause: {cause}',
  'publications.tagCreationFailed': 'Release creation failed, cause: {cause}',
  'publications.uploadDialogTitle': 'Ladda upp publicering',
  'dialobForms.dialog.heading': 'Forms',
  'dialobForms.table.tooltip.add': 'Add',
  'dialobForms.table.label': 'ID',
  'dialobForms.table.created': 'Created',
  'dialobForms.table.lastSaved': 'Updated',
  'dialobForms.table.tooltip.edit': 'Edit',
  'dialobForms.dialog.emptyTitle': '-',
  'dialobForms.table.tooltip.copy': 'Copy',
  'dialobForms.table.tooltip.delete': 'Remove',
  'dialobForm.saveFailed': 'Saving failed',
  'dialobForm.downloadFailed': 'Saving failed',
  'dialobForm.deleteFailed': 'Remove failed',
  'dialobForm.heading.copyDialog': 'Copy',
  'dialobForm.heading.addDialog': 'Add',
  'dialobForm.dialog.formName': 'ID',
  'dialobForm.dialog.formLabel': 'Name',
  'dialobForm.error.invalidFormName': 'Incorrect ID',
  'dialobForm.dialog.deleteQuestion': 'Do you want to remove form \"{formName}\"?',
  'dialobForm.heading.deleteDialog': 'Remove form',
  'dialobForm.review.title': 'Form review',
  'feedback.notenabled': 'Feedback is not enabled for this task',
  'pages': 'Sidor',
  'articles': 'Artiklar',
  'locale': 'Plats',
  'locales': 'Webbplatsspråk',
  'tag': 'Märka',
  'links': 'Länkar',
  'releases': 'Släpps',
  'options': 'Alternativ',
  'value': 'Värde',
  'date': 'Datum',
  'order': 'Beställa',
  'description': 'Beskrivning',
  'name': 'Namn',
  'delete': 'Radera',
  'download': 'Ladda ner JSON',
  'disable': 'Inaktivera',
  'status': 'Status',
  'created': 'Skapad',
  'modified': 'Ändrad',
  'rename': 'Döpa om',
  'reorder': 'Beställ om',
  'remove': 'Ta bort',
  'site.content.empty': 'Webbplatsen har inget innehåll! Skapa innehåll innan du gör en release!',
  'composer.select.article': 'Välj Artikel',
  'search.field.placeholder': 'Ange sökord',
  'search.results.title': 'Sökresultat',
  'search.field.label': 'Söka',
  'search.all': 'Alla',
  'search.articles': 'Artiklar',
  'search.services': 'Tjänster',
  'search.links': 'Länkar',
  'search.templates': 'Mallar',
  'search.flows': 'Flöden',
  'search.decisions': 'Beslut',
  'activities.title': 'Aktiviteter',
  'activities.desc': 'Skapa, visa och navigera på webbplatsresurser',
  'activities.article.title': 'Artikel',
  'activities.article.desc': 'En artikel är som en kategori: Den grupperar sidor, länkar och tjänster under ett tak.',
  'activities.locale.title': 'Plats',
  'activities.locale.desc': 'Språk är dina språk: Lägg till, aktivera och inaktivera språk för hela webbplatsen här. Du kan lägga till en sida på ett specifikt språk om du har definierat ett språk för den sidan.',
  'activities.page.title': 'Sida',
  'activities.page.desc': 'En sida är en innehållsfil i en artikel. Det representerar ett språk och alla länkar/arbetsflöden som är associerade med en artikel. Det är skrivet med Markdown-syntax.',
  'activities.link.title': 'Hyperlänk',
  'activities.link.desc': 'En hyperlänk kopplar användare till webbsidor du äger, webbsidor för andra organisationer och dina telefonnummer.',
  'activities.release.title': 'Släppa',
  'activities.release.desc': 'En release är en ögonblicksbild av allt innehåll på webbplatsen vid en viss tidpunkt. Använd detta för testning, produktion eller säkerhetskopiering.',
  'activities.migration.title': 'Migration',
  'migration.create': 'Migrera data',
  'activities.migration.desc': 'Använd en JSON-fil för att utföra en migrering av en webbplats.',
  'activities.templates.title': 'Mallar',
  'activities.templates.desc': 'Använd mallar för att anpassa och standardisera en sidas standard Markdown-innehåll och/eller -struktur. Mallar kan appliceras på nya sidor när de skapas. Inte implementerat ännu!',
  'activities.version.composer': 'Kompositör: byggversion {version}, byggdatum {date}',
  'activities.version.core': 'Kärna: byggversion {version}, byggdatum {date}',
  'dialog.about.title': 'Om',
  'dialog.about.preamble': 'DigiExpress är baserad på öppen källkodsprojekt:',
  'dialog.about.trademark': 'DigiExpress varumärke och logotyp upphovsrättsskyddat av ReSys OÜ',
  'templates': 'Mallar',
  'template.name': 'Namn',
  'template.name.desc': 'Användarnamn för denna mall',
  'template.create': 'Skapa mall',
  'template.edit': 'Redigera mall',
  'template.type': 'Malltyp',
  'template.page': 'Sidmall',
  'template.page.desc': 'Denna mall kan appliceras på en ny sida när den sidan skapas.',
  'template.description': 'Skriv mallar i Markdown för att tillämpa på dina sidor och innehåll. Mallar hjälper till att påskynda din utveckling och förena din innehållsstruktur.',
  'template.desc': 'Beskrivning',
  'template.description.desc': 'Ytterligare information för att identifiera användningsfallen för denna mall',
  'template.delete': 'Ta bort mall',
  'template.delete.message': 'Denna mall kommer att tas bort permanent från applikationen',
  'template.newpage.none': 'Ingen',
  'templates.templatesview.description': 'En ny sida kan skapas från en mall',
  'templates.intro': 'Kom ihåg att använda en Markdown Level 1 Heading (# My Heading 1) när du komponerar dina mallar.',
  'services': 'Tjänster',
  'services.create': 'Skapa tjänst',
  'services.desc': 'Anslut dina formulär och andra integrationer till ditt innehåll med Wrench- och Dialob-arbetsflödena',
  'services.add': 'Lägg till en tjänst',
  'services.change': 'Ändra befintliga tjänster',
  'services.edit': 'Redigera tjänst',
  'services.technicalname': 'Användarens unika tjänstnamn',
  'services.technicalname.description': 'Arbetsflödesbeskrivande namn',
  'services.selected': 'Utvalda tjänster',
  'services.modeselect.title': 'Konfigurationsalternativ',
  'services.modeselect.label': 'Välja',
  'services.devmode.helper': 'Utvecklingsläge: Tjänsten visas endast i utvecklingsmiljön för testning och ingår inte i produktionsutgåvor.',
  'services.devmode.label': 'Utvecklingsläge',
  'services.devmode.tooltip': 'Utvecklingsläge',
  'services.disabledmode.label': 'Inaktiverat läge',
  'services.disabledmode.helper': 'Inaktiverat läge: Tjänsten visas inte på klientportalen',
  'services.disabledmode.tooltip': 'Inaktiverat läge',
  'services.none.label': 'Ingen konfiguration har valts',
  'services.none.helper': 'Standardläge: Tjänsten visas i produktion, är ENDAST tillgänglig för autentiserade användare och är ansluten till ALLA ARTIKLAR om ingen artikel är vald',
  'services.none.tooltip': 'Ingen speciell konfiguration',
  'services.anonmode.helper': 'Anonymt läge: Tjänsten visas för BÅDE anonyma och autentiserade användare.',
  'services.anonmode.label': 'Anonymt läge',
  'services.anonmode.tooltip': 'Anonymt läge',
  'services.flowName': 'Flödes namn',
  'services.flowName.description': 'Flödesnamn enligt definitionen i skiftnyckeln',
  'services.formName': 'Dialob formnamn',
  'services.formName.description': 'Namn på Dialob-formuläret som används i tjänsten',
  'services.formTag': 'Dialob formtagg',
  'services.formTag.description': 'Taggnamn för Dialob-formulär som används i tjänsten',
  'services.startdate': 'Startdatum och tid',
  'services.startdate.description': 'Serviceaktiveringsdatum och tid',
  'services.enddate': 'Slutdatum och tid',
  'services.enddate.description': 'Serviceaktiveringens slutdatum och tid',
  'services.delete': 'Ta bort tjänsten',
  'services.delete.desc': 'Om du tar bort den här tjänsten tas den bort permanent från applikationen, och alla kopplingar till artiklar/sidor kommer att gå förlorade.',
  'snack.article.createdMessage': 'Artikel skapad framgångsrikt',
  'snack.article.deletedMessage': 'Artikel raderad',
  'snack.article.editedMessage': 'Artikeländringar sparade',
  'snack.page.createdMessage': 'Sidan har skapats',
  'snack.page.deletedMessage': 'Sidan raderad',
  'snack.page.savedMessage': 'Sidändringar sparade',
  'snack.page.missingTitle': 'Lägg till en titel till {locale} i {articleName}',
  'snack.link.createdMessage': 'Länken har skapats',
  'snack.link.deletedMessage': 'Länken raderad',
  'snack.link.editedMessage': 'Länkändringar har sparats',
  'snack.link.addedMessage': 'Länk till artikeln',
  'snack.link.removedMessage': 'Länken har tagits bort från artikeln',
  'snack.workflow.createdMessage': 'Tjänsten har skapats',
  'snack.workflow.deletedMessage': 'Tjänsten raderad',
  'snack.workflow.editedMessage': 'Tjänständringar sparade',
  'snack.workflow.addedMessage': 'Tjänsten har lagts till i artikeln',
  'snack.workflow.removedMessage': 'Tjänsten har tagits bort från artikeln',
  'snack.locale.createdMessage': 'Språket har skapats',
  'snack.locale.deletedMessage': 'Språket har tagits bort',
  'snack.locale.editedMessage': 'Ändringar av språk har sparats',
  'snack.locale.enabled': 'Språk aktiverat',
  'snack.locale.disabled': 'Plats inaktiverad',
  'snack.template.createdMessage': 'Mallen har skapats',
  'snack.template.deletedMessage': 'Mallen raderad',
  'snack.template.editedMessage': 'Malländringar sparade',
  'snack.release.createdMessage': 'Release skapad framgångsrikt',
  'snack.release.deletedMessage': 'Release raderad',
  'snack.migration.createdMessage': 'Webbplatsdata uppdaterad',
  'toolbar.search': 'Söka',
  'toolbar.save': 'Spara',
  'toolbar.stencil': 'stencilen',
  'toolbar.wrench': 'skiftnyckeln',
  'toolbar.menu': 'Meny',
  'toolbar.help': 'Hjälp',
  'toolbar.services': 'Tjänster',
  'toolbar.import': 'Importera data',
  'toolbar.tasks': 'Uppgifter',
  'toolbar.about': 'Om',
  'stencil.services.found.none': 'Inga tjänster hittades',
  'link.type.internal': 'Inre',
  'link.type.external': 'Extern',
  'link.type.phone': 'Telefonnummer',
  'link.search.title': 'Sök länkar efter värde',
  'link.value': 'Länkvärde',
  'sitelocale.label.select.alreadyDefined': 'Kan inte lägga till eftersom det här språket redan är definierat',
  'sitelocale.label.table.editLocaleValue': 'Redigera språkvärde',
  'locales.label.table.title': 'Platsetiketter',
  'locales.label.title.helper': 'Minst en språkkod (lokal) + lokaletikettvärde krävs',
  'locales.label.table.value': 'Platsetikettvärden',
  'locales.enabledMessage': 'Aktiverad: Innehåll för den här lokalen kommer att visas på portalsidan',
  'locales.disabledMessage': 'Inaktiverad: Innehåll för den här lokalen kommer att döljas från portalsidan. Innehållet kan fortfarande redigeras.',
  'transferlist.noItemsSelected': 'Inga objekt har valts',
  'transferlist.search': 'Söka',
  'transferlist.noSearchResults': 'Inga sökresultat hittades',
  'explorer.tabs.search': 'Söka',
  'explorer.tabs.articles': 'Artiklar',
  'explorer.tabs.links': 'Länkar',
  'explorer.tabs.services': 'Tjänster',
  'imports': 'Importer',
  'imports.select': 'Välj en fil att importera',
  'imports.import.action': 'Importera valt',
  'article.order': 'Artikelbeställningsnummer',
  'article.order.view': 'Se aktuell artikelordningshierarki',
  'article.select': 'Välj Artiklar',
  'article.links.selectedlinks': 'Valda länkar',
  'article.composer.title': 'Skapa ny artikel',
  'article.composer.parent': 'Föräldraartikel',
  'article.parent.helper': 'Om en överordnad artikel väljs, kommer den här artikeln att finnas i denna förälder, som en fil i en mapp gör.',
  'article.composer.parent.unselected': 'Ingen överordnad artikel',
  'article.create': 'Skapa artikel',
  'article.name': 'Artikelnamn',
  'article.delete.title': 'Ta bort artikel',
  'article.delete.description': 'Om du tar bort den här artikeln tas den och dess associerade sidor bort globalt från programmet.',
  'article.edit.title': 'Redigera artikel',
  'article.edit.parent': 'Överordnad artikel',
  'article.edit.orderhelper': 'Tresiffrigt nummer för beställningsändamål',
  'article.devmode.helper': 'Om utvecklingsläget är aktivt kommer den här artikeln endast att visas i utvecklingsmiljön för testning. Det kommer inte att inkluderas i produktionsutgåvor.',
  'article.devmode': 'Utvecklingsläge',
  'articleservices': 'Artikeltjänster: {name}',
  'articlelinks': 'Artikellänkar: {name}',
  'article.composer.orderhelper': 'Ju lägre siffra, desto högre upp kommer denna artikel att visas i portalens gränssnittsämnesmeny.  Exempel: 000 kommer att vara det första ämnesmenyn, medan 999 kommer att vara det sista.',
  'allarticles': 'Välj alla artiklar',
  'allarticles.individual': 'Avmarkera alla artiklar',
  'add.allarticles.link.help': 'Denna länk kommer att läggas till (eller tas bort från) alla artiklar. Eventuella tidigare länk-artikelassociationer kommer att gå förlorade när denna ändring har tillämpats',
  'add.allarticles.service.help': 'Denna tjänst kommer att läggas till (eller tas bort från) alla artiklar. Alla tidigare kopplingar till tjänsteartiklar kommer att gå förlorade när denna ändring har tillämpats.',
  'button.create': 'Skapa',
  'button.add': 'Tillägga',
  'button.disable': 'Fortsätt och inaktivera',
  'button.enable': 'Fortsätt och aktivera',
  'button.remove': 'Fortsätt och ta bort',
  'button.apply': 'Tillämpa ändringar',
  'button.releasegraph': 'Graf',
  'button.view.all.locales': 'Visa lokaler',
  'button.view.all.releases': 'Visa releaser',
  'button.view.all.templates': 'Visa mallar',
  'links.message': 'Expandera rader för att se Länk - Artikelföreningar',
  'links.searchAll': 'Sök i alla länkar',
  'link.article.add.title': 'Lägg till länk till en artikel',
  'link.article.select': 'Välj Artikel',
  'link.type': 'Typ',
  'link.url': 'URL/värde',
  'link.locale.all': 'Alla lokaler',
  'link.content': 'Länk URL / sökväg',
  'link.composer.title': 'Skapa en ny länk',
  'link.composer.descriptionlabel': 'Beskrivning',
  'link.composer.descriptionhelper': 'Text som användaren kommer att se',
  'link.composer.valuehelper': 'URL/sökväg till länk (http://www.example.com)',
  'link.edit.title': 'Redigera länk',
  'link.delete.title': 'Ta bort länk',
  'link.delete': 'Om du tar bort den här länken kommer den att tas bort permanent från applikationen och alla kopplingar till artiklar/sidor kommer att gå förlorade.',
  'link.removepage.title': 'Vill du ta bort den här länken?',
  'link.removepage': 'Att ta bort länken tar bara bort dess koppling till den här artikeln. För att ta bort det här objektet permanent, klicka på ikonen Ta bort.',
  'link.options': 'Länkalternativ',
  'link.options.add': 'Lägg till länkar till artikeln',
  'resource.edit.links': 'Redigera länkar',
  'links.change': 'Ändra befintliga länkar',
  'link.create': 'Skapa ny länk',
  'link.devmode.helper': 'Om utvecklingsläget är aktivt kommer denna länk endast att visas i utvecklingsmiljön för testning. Det kommer inte att inkluderas i produktionsutgåvor.',
  'link.devmode': 'Utvecklingsläge',
  'locale.create': 'Skapa språk',
  'locale.disable.title': 'Inaktivera den här lokalen?',
  'locale.enable.title': 'Vill du aktivera det här språket?',
  'locale.disable': 'Alla sidor som använder detta språk kommer att döljas i användargränssnittet. Sidor kan fortfarande redigeras.',
  'locale.enable': 'Alla sidor som använder den här lokalen kommer att visas i användargränssnittet.',
  'locale.composer.title': 'Skapa en ny lokal',
  'locale.composer.placeholder': 'Språkkod på två bokstäver',
  'locale.composer.helper': 'Språkkoder på två bokstäver anger innehållsspråket. Vanliga exempel: en = engelska, fi = finska, sv = svenska',
  'locale.overview': 'Översikt över användning av språk',
  'locales.overview.description': 'Hantera språken för innehållet på din webbplats. Inaktivera språk för att dölja allt innehåll som är kopplat till det språket från din webbplats',
  'locales.content': 'Sidan i det här språket har innehåll',
  'locales.nocontent': 'Sidan i det här språket har inget innehåll',
  'locales.nopage': 'Det finns ingen sida för detta språk i denna artikel',
  'locales.label.table.locale': 'Språkkod',
  'newpage.title': 'Skapa en ny sida',
  'newpage.info': 'En sida består av lokaliserat innehåll och måste kopplas till en artikel.',
  'newpage.article.info': 'Bekräfta skapandet av sidan för: {article} med språk: {locale}',
  'page.create': 'Skapa sida',
  'page.delete.dialog.title': 'Ta bort en sida från artikeln:',
  'page.delete.description': 'Den valda sidan och allt dess innehåll kommer att tas bort permanent från din webbplats',
  'pages.save': 'Spara sidor',
  'pages.add': 'Lägg till en sida',
  'pages.change': 'Ändra en sidspråk',
  'pages.select.locale': 'Redigera lokaliserat sidinnehåll',
  'pages.select.locale.edit.desc': 'Välj två språk för att möjliggöra sida vid sida redigering på en flik.',
  'pages.edit.language1': 'Redigera detta språk',
  'pages.edit.language2': 'Redigera detta språk sida vid sida',
  'pages.edit.currentlyEditing.language2': 'Redigering sida vid sida',
  'pages.edit.currentlyEditing.language1': 'Redigerar detta språk',
  'pages.change.info': 'Välj en sida från den här artikeln och ange ett nytt värde för dess språk.',
  'pages.change.devmode': 'Ändra ett sidutvecklingsläge',
  'pages.change.devmode.info': 'Välj en sida från den här artikeln och ändra dess utvecklingsläge.',
  'pages.devmode.helper': 'Om utvecklingsläget är aktivt kommer denna sida endast att visas i utvecklingsmiljön för testning. Det kommer inte att inkluderas i produktionsutgåvor.',
  'pages.devmode': 'Utvecklingsläge',
  'pages.delete': 'Ta bort en sida',
  'pages.delete.message': 'Välj en sida att ta bort från denna artikel.',
  'pages.options': 'Sidalternativ',
  'pages.edit.selectpage': 'Välj sida',
  'pages.edit.selectTargetLocale': 'Välj målspråk',
  'release.create': 'Skapa release',
  'release.composer.title': 'Skapa en ny version',
  'release.composer.label': 'Taggnamn',
  'release.composer.note': 'Notera',
  'release.composer.helper': 'Valfri ytterligare information för framtida referens',
  'release.desc': 'Visa alla utgåvor och ladda ner allt innehåll på webbplatsen i JSON-format. För mer detaljerad information om specifika utgåvor och deras innehåll, se diagrammet.',
  'release.delete.title': 'Ta bort release',
  'release.delete.desc': 'Vill du ta bort den här versionen permanent från webbplatsdata?',
  'releases.view.note': 'Anteckningar',
  'releases.view.tag': 'Namn',
  'releases.view.created': 'Skapad',
  'releases.view.download': 'Ladda ner JSON',
  'buttons.create': 'Skapa',
  'buttons.apply': 'Tillämpas',
  'buttons.delete': 'Radera',
  'buttons.copy': 'Kopiera',
  'button.compose': 'Komponera',
  'buttons.download': 'Ladda ner',
  'content.loading': 'Belastning',
  'explorer.tabs.flows': 'Flöden',
  'explorer.tabs.decisions': 'Beslut',
  'explorer.active.branch': 'Aktiv gren: {name}',
  'explorer.active.branch.default': 'Standard',
  'activities.flows.title': 'Flöden',
  'activities.flows.desc': 'En sekvens av uppgifter som definieras med ett enkelt konfigurationsspråk.',
  'activities.decisions.title': 'Beslut',
  'activities.decisions.desc': 'En beslutstabell som kan användas för att fatta beslut baserat på indata.',
  'activities.services.title': 'Tjänster',
  'activities.services.desc': 'En del av Java- eller Groovy-kod som är inbäddad i ett flöde som en uppgift.',
  'activities.releases.title': 'Släpps',
  'activities.releases.desc': 'En release är en ögonblicksbild av allt innehåll på webbplatsen vid en viss tidpunkt.',
  'activities.releases.desc.additional': 'Varje utgåva kan laddas ner för att användas för produktion eller säkerhetskopiering, eller kan förgrenas för ytterligare redigering. Detta kommer att ersätta alla befintliga tillgångar så se till att alla ändringar sparas.',
  'activities.releases.view': 'Se alla utgåvor',
  'activities.releases.graph': 'Graf',
  'activities.compare.title': 'Jämföra',
  'activities.compare.desc': 'Jämför två utgåvor för att se vad som har förändrats mellan dem.',
  'activities.compare.view': 'Jämföra',
  'activities.templates.view': 'Se alla mallar',
  'activities.debug.title': 'Felsökning',
  'activities.debug.desc': 'Simulera utförande av en tillgång. Kan göras via formulärinmatning, JSON-inmatning eller genom att använda en CSV-fil.',
  'activities.debug.view': 'Simulera',
  'activities.assets.saveSuccess': 'Sparad tillgång: {name}',
  'programs.error.title': 'Programfel',
  'programs.warning.title': 'Programvarning',
  'flows': 'Flöden',
  'migrations.title': 'Migration',
  'migrations.create': 'Utför migrering',
  'migrations.select': 'Välj tag.json-fil',
  'flows.edit.title': 'Redigera flöde',
  'flows.copyas.title': 'Kopiera flöde som',
  'flows.delete.title': 'Ta bort flöde',
  'flows.delete.error.title': 'Det gick inte att ta bort flödet',
  'flows.delete.content': 'Är du säker på att du vill ta bort FLOW: {name}?',
  'flows.deleted.message': 'Raderat FLÖDE: {name}',
  'flows.simulate.title': 'Felsök flödet',
  'flows.composer.title': 'Skapa nytt FLOW',
  'flows.composer.copyTitle': 'Kopiera FLOW som',
  'flows.composer.createdMessage': 'Skapat FLÖDE: {name}',
  'flows.composer.copiedMessage': 'Kopierade FLÖDE {name} som: {newName}',
  'flows.composer.errorsTitle': 'Det gick inte att skapa FLOW',
  'flows.composer.assetName': 'Unikt namn för FLOW',
  'flows.autocomplete.task.create': 'Skapa ny tillgång',
  'flows.autocomplete.task.link': 'Länka vald tillgång',
  'flows.autocomplete.task.searchField': 'Sök efter tillgång...',
  'flows.autocomplete.task.searchPlaceholder': 'Tillgångens namn eller beskrivning',
  'flows.autocomplete.task.selectType': 'Välj tillgångstyp att länka',
  'flows.autocomplete.task.searchHelper': 'Matchar tillgångens namn och beskrivning',
  'flows.autocomplete.task.searchResults': 'Sökresultat',
  'flows.autocomplete.task': 'Lägg till befintlig tillgång eller skapa en ny',
  'flows.autocomplete.task.snackbar.created': 'Skapat ny {type}: {name}',
  'flows.autocomplete.task.snackbar.creating': 'Skapar ny {type}: {name}',
  'flows.graph.show': 'Visa flödesdiagram',
  'flows.graph.hide': 'Dölj flödesdiagram',
  'services.searchAll': 'Sök i alla tjänster',
  'services.edit.title': 'Redigera tjänst',
  'services.copyas.title': 'Kopiera tjänst som',
  'services.delete.title': 'Ta bort tjänsten',
  'services.delete.error.title': 'Det gick inte att ta bort SERVICE',
  'services.delete.content': 'Är du säker på att du vill ta bort SERVICE: {name}?',
  'services.deleted.message': 'Raderad SERVICE: {name}',
  'services.simulate.title': 'Felsök tjänsten',
  'services.composer.title': 'Skapa ny SERVICE',
  'services.composer.copyTitle': 'Kopiera SERVICE som',
  'services.composer.createdMessage': 'Skapat TJÄNST: {name}',
  'services.composer.copiedMessage': 'Kopierade SERVICE {name} som: {newName}',
  'services.composer.errorsTitle': 'Det gick inte att skapa SERVICE',
  'services.composer.assetName': 'Unikt namn för TJÄNSTEN',
  'decisions.name': 'Namn',
  'decisions.desc': 'Beskrivning',
  'decisions.simulate.title': 'Felsök beslutet',
  'decisions.hitpolicy': 'Hit-policy',
  'decisions.edit.title': 'Redigera beslut',
  'decisions.copyas.title': 'Kopiera beslut som',
  'decisions.delete.error.title': 'Det gick inte att ta bort DECISION',
  'decisions.delete.title': 'Ta bort beslut',
  'decisions.delete.content': 'Är du säker på att du vill ta bort BESLUT: {name}?',
  'decisions.deleted.message': 'Raderat BESLUT: {name}',
  'decisions.table.hitpolicy': 'Tändstickor',
  'decisions.table.options': 'Alternativ',
  'decisions.composer.title': 'Skapa nytt BESLUT',
  'decisions.composer.copyTitle': 'Kopiera BESLUT som',
  'decisions.composer.createdMessage': 'Skapat BESLUT: {name}',
  'decisions.composer.copiedMessage': 'Kopierade BESLUT {name} som: {newName}',
  'decisions.composer.errorsTitle': 'Det gick inte att skapa DECISION',
  'decisions.composer.assetName': 'Unikt namn för BESLUTET',
  'decisions.toolbar.addInputColumn': 'Lägg till inmatningskolumn',
  'decisions.toolbar.addOutputColumn': 'Lägg till utdatakolumn',
  'decisions.toolbar.addRow': 'Lägg till rad',
  'decisions.toolbar.csvDownload': 'Ladda ner CSV, med separator \';\'',
  'decisions.toolbar.csvUpload': 'Ladda upp CSV, med separator \';\'',
  'decisions.toolbar.nameAndHitpolicy': 'Namn och träffpolicy',
  'decisions.toolbar.organize.rows.columns': 'Organisera rader och kolumner',
  'decisions.toolbar.organize.action': 'Välj åtgärd',
  'decisions.toolbar.organize.action.helper': 'Flytta kolumn eller rad baserat på namn/index',
  'decisions.toolbar.organize.action.expression': 'Välj uttryck',
  'decisions.toolbar.organize.action.expression.column': 'Välj kolumn',
  'decisions.toolbar.organize.action.deleteColumn': 'Ta bort hela kolumnen',
  'decisions.toolbar.organize.action.deleteRow': 'Ta bort hela raden',
  'decisions.toolbar.organize.action.deleteRow.contents': 'Radens innehåll',
  'decisions.toolbar.organize.action.move.from.column': 'Kolumn att flytta',
  'decisions.toolbar.organize.action.move.from.row': 'Rad att flytta',
  'decisions.toolbar.organize.action.move.to.column': 'Ny position',
  'decisions.toolbar.organize.action.move.to.row': 'Ny position',
  'decisions.table.inputs.title': 'Matchande regler',
  'decisions.table.outputs.title': 'Resultat',
  'decisions.header.dialog.title': 'Beslutstabell: {name}, kolumn: {column}',
  'decisions.cells.dialog.title': 'Beslutstabell: {name}, kolumn: {column}, värde: {value}',
  'decisions.cells.newvalue.boolean': 'Ange nytt värde',
  'decisions.cells.newvalue.boolean.helper': 'Välj booleskt värde',
  'decisions.cells.newvalue.boolean.empty': 'Inget värde valt',
  'decisions.cells.newvalue.date.operator': 'Operatör',
  'decisions.cells.newvalue.date.start': 'Startdatum',
  'decisions.cells.newvalue.date.end': 'Slutdatum',
  'decisions.cells.newvalue.date.value': 'Datum',
  'decisions.cells.newvalue.number.comparisonType': 'Jämförelse',
  'decisions.cells.newvalue.number.comparisonTypeEmpty': 'Jämförelse har inte valts',
  'decisions.cells.newvalue.number.comparisonValue': 'Nytt numeriskt värde',
  'decisions.cells.newvalue.number.comparisonToRange': 'Byt till intervall',
  'decisions.cells.newvalue.number.rangeStart': 'Start',
  'decisions.cells.newvalue.number.rangeEnd': 'Avsluta',
  'decisions.cells.newvalue.number.value': 'Nytt numeriskt värde',
  'decisions.cells.newvalue.number.rangeIncluded': 'Ingår',
  'decisions.cells.newvalue.number.rangeToComparison': 'Ändra till jämförelse',
  'decisions.cells.newvalue.string.comparisonType': 'Jämförelse',
  'decisions.cells.newvalue.string.addValue': 'Lägg till nytt värde',
  'decisions.cells.newvalue.string.available': 'Tillgängliga värden',
  'decisions.cells.newvalue.string.selected': 'Valda värden',
  'decisions.cells.newvalue.string.empty': 'Jämförelse har inte valts',
  'decisions.cells.newvalue.clear': 'Rensa aktuellt värde',
  'decisions.valueSet': 'Definiera värdeuppsättning',
  'decisions.valueSet.description': 'Värdeuppsättningar kan användas för att definiera en förutbestämd uppsättning värden för vilken ingång som helst',
  'decisions.valueSet.add': 'Lägg till värdeuppsättning',
  'decisions.valueSet.remove': 'Ta bort från värdeuppsättningen',
  'decisions.valueSet.current': 'Aktuellt värde inställt',
  'decisions.valueSet.empty': 'Värdet är tomt',
  'dt.header.name': 'Namn',
  'dt.header.delete': 'Radera',
  'dt.header.expression': 'Uttryck',
  'dt.header.dataType': 'Datatyp',
  'dt.header.script': 'Manus',
  'decisions': 'Beslut',
  'program.status.DEPENDENCY_ERROR': 'Beroendefel',
  'program.status.UP': 'Programmet är UPP',
  'program.status.AST_ERROR': 'Syntaxfel',
  'program.status.PROGRAM_ERROR': 'Kompilatorfel',
  'package.explorer.flows': 'flöden',
  'package.explorer.servicetasks': 'tjänster',
  'package.explorer.decisiontables': 'beslut',
  'dialog.addtype.title': 'Lägg till ny tillgång',
  'dialog.addtype.button.cancel': 'Avboka',
  'dialog.addtype.button.confirm': 'Skapa',
  'dialog.addtype.error.unique': 'Tillgångens namn måste vara unikt!',
  'dialog.addtype.error.filled': 'Tillgångens namn måste fyllas i!',
  'dialog.addtype.input.serviceType': 'Tillgångstyp',
  'dialog.addtype.input.name': 'Tillgångens namn',
  'dialog.copyas.title': 'Kopiera tillgång',
  'dialog.copyas.button.cancel': 'Avboka',
  'dialog.copyas.button.confirm': 'Kopiera',
  'dialog.copyas.input.from': 'Kopiera från',
  'dialog.copyas.input.to': 'Nytt tillgångsnamn',
  'dialog.copyas.error.unique': 'Tillgångens namn måste vara unikt!',
  'dialog.copyas.error.filled': 'Tillgångens namn måste fyllas i!',
  'dialog.save.title': 'Spara tillgång: {name}',
  'dialog.save.content': 'Är du säker på att du vill spara?',
  'dialog.save.errors': 'Det gick inte att spara tillgången',
  'dialog.save.button.cancel': 'Avboka',
  'dialog.save.button.confirm': 'Spara',
  'release.delete.content': 'Är du säker på att du vill ta bort release: {name}',
  'release.delete.error.title': 'Det gick inte att ta bort versionen',
  'release.deleted.message': 'Release {name} raderad',
  'releases.composer.createdMessage': 'Skapat ny version {name}',
  'releases.view.action': 'Handling',
  'releases.composer.title': 'Skapa ny release',
  'releases.composer.assetName': 'Utgivningsnamn',
  'releases.composer.assetDesc': 'Utgivningsbeskrivning',
  'releases.composer.errorsTitle': 'Ett fel uppstod när versionen skapades',
  'releases.table.title': 'Releases och filialer',
  'releases.table.column.name': 'Namn',
  'releases.table.column.message': 'Meddelande',
  'releases.table.column.created': 'Skapad',
  'releases.table.name': 'Alla releaser',
  'releases.add.error.unique': 'Utgivningen måste vara unik!',
  'releases.add.error.filled': 'Releasenamn måste fyllas i!',
  'releases.add.input.name': 'Namn',
  'releases.add.input.msg': 'Kommentar',
  'releases.add.button.create': 'Skapa release',
  'releases.button.compare': 'Jämföra',
  'releases.button.branch': 'Skapa ny filial',
  'releases.button.checkout': 'Kassa',
  'releases.button.release': 'Släppa',
  'releases.button.details': 'Visa releasetillgångar',
  'releases.default.name': 'standard',
  'releases.default.note': 'Detta är standardgrenen som du kan gå tillbaka till',
  'releases.latest.name': 'senast',
  'releases.latest.note': 'Dessa är omsättningstillgångar med de senaste ändringarna som kan släppas',
  'releases.details.title': 'Frisläppande tillgångar: {name}',
  'branch.delete.title': 'Ta bort gren',
  'branch.delete.content': 'Är du säker på att du vill ta bort filial: {name}',
  'branch.delete.error.title': 'Fel vid borttagning av gren',
  'release.branch.creating': 'Skapar ny filial: {name}',
  'release.branch.created': 'Skapat ny filial: {name}',
  'release.branch.deleting': 'Tar bort gren: {name}',
  'release.branch.deleted': 'Raderad gren: {name}',
  'release.branch.checkout': 'Checkade ut till filial: {name}',
  'debug.toolbar.options': 'Alternativ',
  'debug.toolbar.selectAsset': 'Välj tillgång att felsöka',
  'debug.toolbar.inputCsv': 'Definiera indata som en CSV',
  'debug.toolbar.inputForm': 'Definiera indata som ett FORM',
  'debug.toolbar.inputJson': 'Definiera indata som en JSON',
  'debug.toolbar.execute': 'Utföra',
  'debug.toolbar.noAsset': 'Välj tillgång från alternativen',
  'debug.toolbar.openAsset': 'Öppna',
  'debug.toolbar.download': 'Ladda ner resultat som CSV',
  'debug.input.noAsset': 'Ingen TILLGÅNG har valts',
  'debug.input.form': 'Felsök med FORM',
  'debug.input.formTitle': 'Definiera ingångar',
  'debug.input.form.invalid.integer': 'Värdet måste vara ett heltal',
  'debug.input.form.invalid.number': 'Värdet måste vara ett tal',
  'debug.input.form.invalid.range': 'Värdet måste ligga inom det angivna intervallet',
  'debug.input.json': 'Felsök med JSON',
  'debug.input.jsonTitle': 'Definiera JSON-ingång',
  'debug.input.csvUpload': 'Felsök med CSV',
  'debug.input.csvFile': 'Ladda upp CSV-FIL',
  'debug.input.csvFileTitle': 'Ladda upp CSV-fil - semikolonavgränsad (;)',
  'debug.input.csvFileOrText': 'Eller klistra in CSV-innehåll - semikolonavgränsat (;)',
  'debug.inputs.fieldName': 'Fältnamn',
  'debug.inputs.fieldValue': 'Fältvärde',
  'debug.select.title': 'Välj tillgång att felsöka',
  'debug.select.assetType': 'Tillgångstyp att filtrera',
  'debug.select.searchField': 'Tillgångens namn att söka',
  'debug.select.searchHelper': 'Sökningen matchar tillgångens namn eller beskrivning',
  'debug.select.searchPlaceholder': 'Nyckelord att söka',
  'debug.select.searchResults': 'Hittade tillgångar',
  'debug.select.confirm': 'Välja',
  'debug.inputs.format': 'Inmatningsformat för tillgångar: {typ}',
  'debug.asset.select.label': 'Tillgång att felsöka',
  'debug.asset.select.clear': 'Rensa kördata',
  'debug.asset.select.execute': 'Utför tillgång',
  'debug.asset.execute.inputs': 'Felsöka ingångar',
  'debug.asset.execute.errors': 'Utförandefel',
  'debug.asset.execute.outputs.dt.json': 'Matchade rad(er)',
  'debug.asset.execute.outputs.dt.rejects': 'Avvisade rad(er)',
  'debug.asset.execute.outputs.dt.rejects.order': 'Avrättningsorder',
  'debug.asset.execute.outputs.flow.step': 'Stegnamn: {name}, status: {status}',
  'debug.csv.row': 'Datarad: {rad}',
  'debug.csv.download': 'Ladda ner resultat som CSV',
  'debug.csv.download.delimiter': 'Välj en avgränsare för CSV-filen',
  'debug.csv.download.delimiter.semicolon': 'Semikolon (;)',
  'debug.csv.download.delimiter.comma': 'Komma (,)',
  'debug.csv.download.options': 'Exportalternativ',
  'debug.csv.download.wrap': 'Radbryt celler som innehåller avgränsare med citattecken',
  'compare.tip': 'Välj utgåvor att jämföra nedan. Bas är utgångspunkten för jämförelsen, och målet är den utgivning som kommer att jämföras med basen.',
  'compare.base': 'Välj basutlösning',
  'compare.target': 'Välj målsläpp',
  'compare.dialog.title': 'Jämför utgåvor {base} och {target}',
  'compare.dialog.line': 'Inline',
  'compare.dialog.side': 'Sida vid sida',
  'menu.feedbackAllTasks': 'All feedback',
  'menu.activities': 'Aktiviteter',
  'feedback.all': 'All feedback',
  'feedback.none': 'Ingen feedback tillgänglig',
  'feedback.search': 'Söka',
  'feedback.search.placeholder': 'Feedback, process eller uppgifts-id',
  'feedback.search.filter.category': 'Filtrera efter kategori',
  'feedback.search.filter.subCategory': 'Filtrera efter underkategori',
  'feedback.filter.selectNone': 'Ingen',
  'queues.all': 'Köer',
  'consumers.all': 'Konsumenter',
  'queue.config.appId': 'App-id',
  'queue.config.none': 'Belastning',
  'queue.config.consumerName': 'Konsumentnamn',
  'queue.config.routingKey': 'Routing nyckel',
  'queue.config.consumerStatus': 'Status',
  'queue.config.comment': 'Kommentar',
  'queue.config.consumerId': 'Id',
  'queue.config.qualifiedJavaName': 'Tekniskt namn',
  'queue.config.queueName': 'Könamn',
  'queue.config.createdAt': 'Skapad på',
  'queue.config.createdBy': 'Skapad av',
  'queue.all_deliveries.title': 'Alla leveranser',
  'queue.all_deliveries.created': 'Skapad',
  'queue.all_deliveries.consumerComment': 'Kommentar',
  'queue.all_deliveries.status': 'Status',
  'queue.all_deliveries.messageId': 'Meddelande-id',
  'queue.all_deliveries.consumerId': 'Konsument-id',
  'queue.all_messages.title': 'Alla meddelanden',
  'queue.all_messages.routingKey': 'Routing nyckel',
  'queue.all_messages.messageId': 'Meddelande-id',
  'queue.all_messages.bodyId': 'Kropps-ID',
  'queue.all_messages.bodyType': 'Kroppstyp',
  'queue.all_messages.status': 'Status',
  'queue.all_messages.body': 'Kropp',
  'queue.all_messages.created': 'Skapad',
  'menu.messages': 'Meddelanden',
  'menu.deliveries': 'Leveranser'
}