import { FsDirentProps } from './fs-types'

export const mockFsDirentProperties: Record<string, FsDirentProps> = {

  'content': {
    id: 'content',
    type: 'folder',
    expanded: true,
    reference: false,
    locked: false,
    description: 'Root content folder for all municipal services.',
    configOptions: [],
    comments: [],
    changes: [
      { changeType: 'create', changeDate: '07.01.2024', changedBy: { userName: 'Mikael Berg', email: 'mikael.berg@example.com' } },
      { changeType: 'update', changeDate: '07.01.2025', changedBy: { userName: 'Sarah Johnson', email: 'sarah.johnson@example.com' } }
    ],
    permissions: [],
    labels: [
      { id: 'label-001', value: 'Needs improvement' }
    ],
    errors: [],
  },

  'shared': {
    id: 'shared',
    type: 'folder',
    expanded: false,
    reference: false,
    locked: false,
    description: undefined,
    configOptions: [],
    comments: [],
    changes: [],
    permissions: [],
    labels: [],
    errors: [],
  },

  'printouts': {
    id: 'printouts',
    type: 'folder',
    expanded: false,
    reference: false,
    locked: false,
    description: undefined,
    configOptions: [],
    comments: [],
    changes: [],
    permissions: [],
    labels: [],
    errors: [],
  },

  'main.article': {
    id: 'main.article',
    type: 'article',
    expanded: false,
    reference: false,
    locked: false,
    description: 'Main landing article for the municipal services portal.',
    configOptions: [],
    comments: [
      { comment: 'This article needs updated localization for the 2025 service period.', author: 'Anna Virtanen', created: '07.01.2025' },
      { comment: 'Images are missing from the Swedish version.', author: 'Mikael Berg', created: '15.02.2025' }
    ],
    changes: [],
    permissions: [],
    labels: [
      { id: 'label-003', value: 'Needs translation' },
      { id: 'label-004', value: 'Under review' }
    ],
    errors: [
      { code: 'MISSING_LOCALE', severity: 'WARNING', message: 'Swedish locale content is missing.' }
    ],
  },

  'ref.article': {
    id: 'ref.article',
    type: 'article',
    expanded: false,
    reference: true,
    locked: false,
    description: undefined,
    configOptions: [],
    comments: [],
    changes: [],
    permissions: [],
    labels: [],
    errors: [],
  },

  'fi-main': {
    id: 'fi-main',
    type: 'language',
    expanded: false,
    reference: false,
    locked: false,
    description: undefined,
    configOptions: ['disabledMode'],
    comments: [],
    changes: [],
    permissions: [],
    labels: [],
    errors: [],
    localeCode: 'fi',
  },

  'sv-main': {
    id: 'sv-main',
    type: 'language',
    expanded: false,
    reference: false,
    locked: false,
    description: undefined,
    configOptions: [],
    comments: [],
    changes: [],
    permissions: [],
    labels: [],
    errors: [],
    localeCode: 'sv',
  },

  'en-main': {
    id: 'en-main',
    type: 'language',
    expanded: false,
    reference: false,
    locked: false,
    description: undefined,
    configOptions: [],
    comments: [],
    changes: [],
    permissions: [],
    labels: [],
    errors: [],
    localeCode: 'en',
  },

  'info-gdpr.article': {
    id: 'info-gdpr.article',
    type: 'article',
    expanded: false,
    reference: false,
    locked: false,
    description: undefined,
    configOptions: [],
    comments: [],
    changes: [],
    permissions: [],
    labels: [],
    errors: [],
  },

  'general-message.service': {
    id: 'general-message.service',
    type: 'service',
    expanded: false,
    reference: false,
    locked: false,
    description: undefined,
    configOptions: ['devMode'],
    comments: [
      { comment: 'Form linked correctly after the January Dialob update.', author: 'Sarah Johnson', created: '10.01.2025' }
    ],
    changes: [
      { changeType: 'create', changeDate: '15.03.2024', changedBy: { userName: 'Anna Virtanen', email: 'anna.virtanen@example.com' } }
    ],
    permissions: [],
    labels: [
      { id: 'label-005', value: 'Draft' }
    ],
    errors: [
      { code: 'MISSING_FLOW', severity: 'CRITICAL', message: 'No flow assigned to service.' }
    ],
    serviceName: 'General Message',
    dialobFormName: 'general-message.dialob',
    dialobFormTag: 'latest',
    flowName: 'taskMsgFlow.flow',
    validityStart: '01.01.2025',
    validityEnd: undefined,
    articles: ['main.article'],
    intlValues: { en: 'General message', fi: 'Yleinen viesti', sv: 'Allmänt meddelande' },
  },

  'public-inforeq.service': {
    id: 'public-inforeq.service',
    type: 'service',
    expanded: false,
    reference: false,
    locked: true,
    description: undefined,
    configOptions: [],
    comments: [],
    changes: [],
    permissions: [],
    labels: [
      { id: 'label-006', value: 'Active' },
      { id: 'label-007', value: 'Reviewed' }
    ],
    errors: [],
    serviceName: 'Public Information Request',
    dialobFormName: 'public-inforeq.dialob',
    dialobFormTag: 'v2',
    flowName: 'taskGenericFlow.flow',
    validityStart: '01.03.2024',
    validityEnd: undefined,
    articles: ['info-gdpr.article'],
    intlValues: { en: 'Public information request', fi: 'Julkinen tietopyyntö', sv: 'Offentlig informationsbegäran' },
  },

  'wilma-preschool.service': {
    id: 'wilma-preschool.service',
    type: 'service',
    expanded: false,
    reference: false,
    locked: false,
    description: undefined,
    configOptions: ['devMode', 'assignableMode'],
    comments: [],
    changes: [],
    permissions: [
      { name: 'admin', types: ['read', 'write'] }
    ],
    labels: [
      { id: 'label-002', value: 'Priority' }
    ],
    errors: [],
    serviceName: 'Wilma Preschool Application',
    dialobFormName: 'wilma-preschool.dialob',
    dialobFormTag: 'latest',
    flowName: 'taskGenericFlow.flow',
    validityStart: '01.08.2024',
    validityEnd: undefined,
    articles: ['main.article', 'info-gdpr.article'],
    intlValues: { en: 'Preschool application', fi: 'Varhaiskasvatushakemus', sv: 'Ansökan om förskola' },
  },

  'general-message.dialob': {
    id: 'general-message.dialob',
    type: 'dialob',
    expanded: false,
    reference: false,
    locked: false,
    description: undefined,
    configOptions: [],
    comments: [],
    changes: [],
    permissions: [],
    labels: [],
    errors: [],
    formName: 'General Message Form',
    formTechnicalId: 'general_msg_v1',
    versionTag: 'latest',
  },

  'public-inforeq.dialob': {
    id: 'public-inforeq.dialob',
    type: 'dialob',
    expanded: false,
    reference: false,
    locked: false,
    description: undefined,
    configOptions: [],
    comments: [],
    changes: [],
    permissions: [],
    labels: [],
    errors: [
      { code: 'FORM_VERSION_MISMATCH', severity: 'WARNING', message: 'Form version tag does not match deployed version.' }
    ],
    formName: 'Public Info Request Form',
    formTechnicalId: 'pub_inforeq_v2',
    versionTag: 'v2',
  },

  'wilma-preschool.dialob': {
    id: 'wilma-preschool.dialob',
    type: 'dialob',
    expanded: false,
    reference: false,
    locked: false,
    description: undefined,
    configOptions: [],
    comments: [],
    changes: [],
    permissions: [],
    labels: [],
    errors: [],
    formName: 'Preschool Application Form',
    formTechnicalId: 'wilma_preschool_v1',
    versionTag: undefined,
  },

  'taskMsgFlow.flow': {
    id: 'taskMsgFlow.flow',
    type: 'flow',
    expanded: false,
    reference: false,
    locked: false,
    description: 'Task messaging workflow',
    configOptions: [],
    comments: [],
    changes: [],
    permissions: [],
    labels: [],
    errors: [],
  },

  'taskGenericFlow.flow': {
    id: 'taskGenericFlow.flow',
    type: 'flow',
    expanded: false,
    reference: false,
    locked: false,
    description: undefined,
    configOptions: [],
    comments: [],
    changes: [],
    permissions: [],
    labels: [],
    errors: [],
  },

  'taskSplitFlow.flow': {
    id: 'taskSplitFlow.flow',
    type: 'flow',
    expanded: false,
    reference: false,
    locked: false,
    description: undefined,
    configOptions: [],
    comments: [],
    changes: [],
    permissions: [],
    labels: [],
    errors: [],
  },

  'index-main.phone': {
    id: 'index-main.phone',
    type: 'phone',
    expanded: false,
    reference: false,
    locked: false,
    description: undefined,
    configOptions: [],
    comments: [],
    changes: [],
    permissions: [],
    labels: [],
    errors: [],
    phoneValue: '+358 9 235 11',
    intlValues: { en: 'City Hall switchboard', fi: 'Kaupungintalon vaihde', sv: 'Stadshuset växel' },
  },

  'democracy-info.phone': {
    id: 'democracy-info.phone',
    type: 'phone',
    expanded: false,
    reference: false,
    locked: false,
    description: undefined,
    configOptions: ['devMode'],
    comments: [],
    changes: [],
    permissions: [],
    labels: [],
    errors: [],
    phoneValue: '+358 9 235 22',
    intlValues: { en: 'Democracy services', fi: 'Demokratiapalvelut', sv: 'Demokratitjänster' },
  },

  'water-services.phone': {
    id: 'water-services.phone',
    type: 'phone',
    expanded: false,
    reference: false,
    locked: false,
    description: undefined,
    configOptions: [],
    comments: [],
    changes: [],
    permissions: [],
    labels: [],
    errors: [],
    phoneValue: '+358 9 235 33',
    intlValues: { en: 'Water services', fi: 'Vesihuolto', sv: 'Vattentjänster' },
  },

  'sipoo-main-site.link': {
    id: 'sipoo-main-site.link',
    type: 'link',
    expanded: false,
    reference: false,
    locked: false,
    description: undefined,
    configOptions: ['disabledMode'],
    comments: [],
    changes: [],
    permissions: [],
    labels: [],
    errors: [],
    urlValue: 'https://www.sipoo.fi',
    intlValues: { en: 'Sipoo official website', fi: 'Sipoon virallinen sivusto', sv: 'Sibbo officiella webbplats' },
  },

  'wilma-info.link': {
    id: 'wilma-info.link',
    type: 'link',
    expanded: false,
    reference: false,
    locked: false,
    description: undefined,
    configOptions: [],
    comments: [],
    changes: [],
    permissions: [],
    labels: [],
    errors: [],
    urlValue: 'https://wilma.sipoo.fi',
    intlValues: { en: 'Wilma student portal', fi: 'Wilma-oppilasjärjestelmä', sv: 'Wilma elevportal' },
  },

  'lupapiste.link': {
    id: 'lupapiste.link',
    type: 'link',
    expanded: false,
    reference: false,
    locked: false,
    description: undefined,
    configOptions: [],
    comments: [],
    changes: [],
    permissions: [],
    labels: [],
    errors: [],
    urlValue: 'https://www.lupapiste.fi',
    intlValues: { en: 'Lupapiste permit service', fi: 'Lupapiste-lupajärjestelmä', sv: 'Lupapiste tillståndstjänst' },
  },

  'sipoo-main-logo.png': {
    id: 'sipoo-main-logo.png',
    type: 'image',
    expanded: false,
    reference: false,
    locked: false,
    description: undefined,
    configOptions: [],
    comments: [],
    changes: [],
    permissions: [],
    labels: [],
    errors: [],
  },

  'sipoo-color-logo.png': {
    id: 'sipoo-color-logo.png',
    type: 'image',
    expanded: false,
    reference: false,
    locked: false,
    description: undefined,
    configOptions: [],
    comments: [],
    changes: [],
    permissions: [],
    labels: [],
    errors: [],
  },

  'municipal-seal.svg': {
    id: 'municipal-seal.svg',
    type: 'image',
    expanded: false,
    reference: false,
    locked: false,
    description: undefined,
    configOptions: [],
    comments: [],
    changes: [],
    permissions: [],
    labels: [],
    errors: [],
  },

  'new-construction-permit.printout': {
    id: 'new-construction-permit.printout',
    type: 'printout',
    expanded: false,
    reference: false,
    locked: false,
    description: undefined,
    configOptions: [],
    comments: [
      { comment: 'Swedish template needs review before next release.', author: 'Lars Eriksson', created: '20.03.2025' }
    ],
    changes: [],
    permissions: [],
    labels: [
      { id: 'label-008', value: 'Needs translation' },
      { id: 'label-009', value: 'Pending approval' }
    ],
    errors: [],
    printoutServiceName: 'NewConstructionPermitService',
    orchestratorName: 'taskSplitFlow.flow',
    intlValues: { fi: 'Uudisrakennuslupa', sv: 'Nybyggnadstillstånd' },
  },

  'municipal-services-guide.printout': {
    id: 'municipal-services-guide.printout',
    type: 'printout',
    expanded: false,
    reference: false,
    locked: false,
    description: undefined,
    configOptions: [],
    comments: [],
    changes: [],
    permissions: [],
    labels: [],
    errors: [],
    printoutServiceName: 'MunicipalServicesGuideService',
    orchestratorName: 'taskGenericFlow.flow',
    intlValues: { fi: 'Kunnallispalveluopas', sv: 'Kommunal serviceguide', en: 'Municipal services guide' },
  },

  'waste-management-info.printout': {
    id: 'waste-management-info.printout',
    type: 'printout',
    expanded: false,
    reference: false,
    locked: false,
    description: undefined,
    configOptions: [],
    comments: [],
    changes: [],
    permissions: [],
    labels: [
      { id: 'label-010', value: 'Outdated' }
    ],
    errors: [],
    printoutServiceName: 'WasteManagementService',
    orchestratorName: 'taskGenericFlow.flow',
    intlValues: { fi: 'Jätehuolto-ohje' },
  },

  'fi-construction-permit': {
    id: 'fi-construction-permit',
    type: 'template',
    expanded: false,
    reference: false,
    locked: false,
    description: undefined,
    configOptions: [],
    comments: [],
    changes: [],
    permissions: [],
    labels: [],
    errors: [],
    serviceId: 'new-construction-permit.printout',
    localeId: 'fi',
    content: undefined,
  },

  'sv-construction-permit': {
    id: 'sv-construction-permit',
    type: 'template',
    expanded: false,
    reference: false,
    locked: false,
    description: undefined,
    configOptions: [],
    comments: [],
    changes: [],
    permissions: [],
    labels: [],
    errors: [],
    serviceId: 'new-construction-permit.printout',
    localeId: 'sv',
    content: undefined,
  },

  'en-construction-permit': {
    id: 'en-construction-permit',
    type: 'template',
    expanded: false,
    reference: false,
    locked: false,
    description: undefined,
    configOptions: [],
    comments: [],
    changes: [],
    permissions: [],
    labels: [],
    errors: [],
    serviceId: 'municipal-services-guide.printout',
    localeId: 'en',
    content: undefined,
  },

};
