import { FsNode } from './fs-types'

export const mockFsData: FsNode[] = [
  {
    id: 'content',
    name: 'content',
    type: 'folder',
    comments: undefined,
    expanded: true,
    reference: false,
    locked: false,
    error: false,
    children: [
      {
        id: '000_index',
        name: '000_index',
        type: 'folder',
        comments: undefined,
        expanded: true,
        reference: false,
        locked: true,
        error: false,
        configOptions: [{
          devMode: true,
        }],
        labels: [
          {
            id: 'index-label-1',
            value: 'main-content',
            nodeId: '000_index'
          },
          {
            id: 'index-label-2',
            value: 'featured',
            nodeId: '000_index'
          }
        ],
        children: [
          {
            id: 'main.article',
            name: 'main.article',
            type: 'article',
            error: true,
            comments: [
              {
                comment: 'Found a typo in the content - should be "municipality" not "municipalty"',
                author: 'Sarah Johnson',
                created: '1.2.2025 14:30'
              },
              {
                comment: 'The Finnish translation needs review by a native speaker',
                author: 'Michael Chen',
                created: '28.1.2025 10:15'
              },
              {
                comment: 'Consider adding a confirmation dialog before deletion',
                author: 'Tom Walsh',
                created: '18.1.2025 11:35'
              }
            ],
            expanded: true,
            reference: false,
            locked: false,
            configOptions: [{
              disabledMode: true,
            }],
            labels: [
              {
                id: 'main-article-label-1',
                value: 'homepage',
                nodeId: 'main.article'
              },
              {
                id: 'main-article-label-2',
                value: 'welcome',
                nodeId: 'main.article'
              },
              {
                id: 'main-article-label-3',
                value: 'multilingual',
                nodeId: 'main.article'
              }
            ],
            children: [
              {
                id: 'ref.article',
                name: 'ref.article',
                type: 'article',
                comments: undefined,
                expanded: false,
                reference: true,
                locked: false,
                error: false,
                description: 'Reference article for common content',
                labels: [
                  {
                    id: 'ref-article-label-1',
                    value: 'reference',
                    nodeId: 'ref.article'
                  },
                  {
                    id: 'ref-article-label-2',
                    value: 'reusable',
                    nodeId: 'ref.article'
                  },
                  {
                    id: 'ref-article-label-3',
                    value: 'common-content',
                    nodeId: 'ref.article'
                  }
                ],
                children: [
                  {
                    id: 'fi-ref',
                    name: 'fi',
                    type: 'language',
                    comments: undefined,
                    expanded: false,
                    reference: false,
                    locked: false,
                    error: false,
                    description: 'Yleinen viitesisältö',
                    labels: [
                      {
                        id: 'fi-ref-label-1',
                        value: 'finnish',
                        nodeId: 'fi-ref'
                      },
                      {
                        id: 'fi-ref-label-2',
                        value: 'reference-content',
                        nodeId: 'fi-ref'
                      }
                    ],
                    updated: '03.02.2025',
                    updatedByUser: { userName: 'John Smith', email: 'john.smith@example.com' },
                  },
                  {
                    id: 'en-ref',
                    name: 'en',
                    type: 'language',
                    comments: undefined,
                    expanded: false,
                    reference: false,
                    locked: false,
                    error: false,
                    description: 'Common reference content',
                    labels: [
                      {
                        id: 'en-ref-label-1',
                        value: 'english',
                        nodeId: 'en-ref'
                      },
                      {
                        id: 'en-ref-label-2',
                        value: 'reference-content',
                        nodeId: 'en-ref'
                      }
                    ],
                    updated: '10.02.2025',
                    updatedByUser: { userName: 'Anna Virtanen', email: 'anna.virtanen@example.com' },
                  }
                ],
                updated: '28.01.2025',
                updatedByUser: { userName: 'Diana Hasselback', email: 'diana.hasselback@example.com' },
              },
              {
                id: 'fi-main',
                name: 'fi',
                type: 'language',
                comments: undefined,
                expanded: false,
                reference: false,
                locked: false,
                error: false,
                description: 'Tervetuloa Sipoon Oma asiointiin!',
                labels: [
                  {
                    id: 'fi-main-label-1',
                    value: 'finnish',
                    nodeId: 'fi-main'
                  },
                  {
                    id: 'fi-main-label-2',
                    value: 'primary-language',
                    nodeId: 'fi-main'
                  }
                ],
                updated: '17.02.2025',
                updatedByUser: { userName: 'Mikael Berg', email: 'mikael.berg@example.com' },
              },
              {
                id: 'sv-main',
                name: 'sv',
                type: 'language',
                comments: undefined,
                expanded: false,
                reference: false,
                locked: false,
                error: false,
                labels: [
                  {
                    id: 'sv-main-label-1',
                    value: 'swedish',
                    nodeId: 'sv-main'
                  },
                  {
                    id: 'sv-main-label-2',
                    value: 'secondary-language',
                    nodeId: 'sv-main'
                  }
                ],
                updated: '24.02.2025',
                updatedByUser: { userName: 'Sarah Johnson', email: 'sarah.johnson@example.com' },
              },
              {
                id: 'en-main',
                name: 'en',
                type: 'language',
                comments: undefined,
                expanded: false,
                reference: false,
                locked: false,
                error: false,
                labels: [
                  {
                    id: 'en-main-label-1',
                    value: 'english',
                    nodeId: 'en-main'
                  },
                  {
                    id: 'en-main-label-2',
                    value: 'international',
                    nodeId: 'en-main'
                  }
                ],
                updated: '03.03.2025',
                updatedByUser: { userName: 'Michael Chen', email: 'michael.chen@example.com' },
              }
            ],
            updated: '21.01.2025',
            updatedByUser: { userName: 'Tom Walsh', email: 'tom.walsh@example.com' },
          },
          {
            id: 'info-gdpr.article',
            name: 'info-gdpr.article',
            type: 'article',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            configOptions: [{
              devMode: true,
              disabledMode: true,
            }],
            labels: [
              {
                id: 'gdpr-label-1',
                value: 'privacy',
                nodeId: 'info-gdpr.article'
              },
              {
                id: 'gdpr-label-2',
                value: 'legal',
                nodeId: 'info-gdpr.article'
              },
              {
                id: 'gdpr-label-3',
                value: 'compliance',
                nodeId: 'info-gdpr.article'
              },
              {
                id: 'gdpr-label-4',
                value: 'data-protection',
                nodeId: 'info-gdpr.article'
              }
            ],
            updated: '10.03.2025',
            updatedByUser: { userName: 'Tom Walsh', email: 'tom.walsh@example.com' },
          },
          {
            id: 'general-message.service',
            name: 'general-message.service',
            type: 'service',
            comments: undefined,
            expanded: true,
            reference: false,
            locked: true,
            error: false,
            configOptions: [{
              devMode: true,
              assignableMode: true,
              disabledMode: true,
              anonymousMode: true,
            }],
            labels: [
              {
                id: 'general-msg-label-1',
                value: 'communication',
                nodeId: 'general-message.service'
              },
              {
                id: 'general-msg-label-2',
                value: 'messaging',
                nodeId: 'general-message.service'
              },
              {
                id: 'general-msg-label-3',
                value: 'contact-form',
                nodeId: 'general-message.service'
              },
              {
                id: 'general-msg-label-4',
                value: 'public-service',
                nodeId: 'general-message.service'
              },
              {
                id: 'general-msg-label-5',
                value: 'reusable',
                nodeId: 'general-message.service'
              }
            ],
            children: [
              {
                id: 'fi-general',
                name: 'fi',
                type: 'language',
                comments: undefined,
                expanded: false,
                reference: false,
                locked: false,
                error: false,
                description: 'Lähetä viesti',
                labels: [
                  {
                    id: 'fi-general-label-1',
                    value: 'finnish',
                    nodeId: 'fi-general'
                  },
                  {
                    id: 'fi-general-label-2',
                    value: 'send-message',
                    nodeId: 'fi-general'
                  }
                ],
                updated: '24.03.2025',
                updatedByUser: { userName: 'John Smith', email: 'john.smith@example.com' },
              },
              {
                id: 'sv-general',
                name: 'sv',
                type: 'language',
                comments: undefined,
                expanded: false,
                reference: false,
                locked: false,
                error: false,
                labels: [
                  {
                    id: 'sv-general-label-1',
                    value: 'swedish',
                    nodeId: 'sv-general'
                  }
                ],
                updated: '31.03.2025',
                updatedByUser: { userName: 'Anna Virtanen', email: 'anna.virtanen@example.com' },
              }
            ],
            updated: '17.03.2025',
            updatedByUser: { userName: 'Diana Hasselback', email: 'diana.hasselback@example.com' },
          },
          {
            id: 'general-message.dialob',
            name: 'general-message.dialob',
            type: 'dialob',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            labels: [
              {
                id: 'general-dialob-label-1',
                value: 'form',
                nodeId: 'general-message.dialob'
              },
              {
                id: 'general-dialob-label-2',
                value: 'user-input',
                nodeId: 'general-message.dialob'
              },
              {
                id: 'general-dialob-label-3',
                value: 'messaging',
                nodeId: 'general-message.dialob'
              }
            ],
            updated: '07.04.2025',
            updatedByUser: { userName: 'Mikael Berg', email: 'mikael.berg@example.com' },
          },
          {
            id: 'taskMsgFlow.flow',
            name: 'taskMsgFlow.flow',
            type: 'flow',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            configOptions: [{
              assignableMode: true,
              anonymousMode: true,
            }],
            labels: [
              {
                id: 'msg-flow-label-1',
                value: 'workflow',
                nodeId: 'taskMsgFlow.flow'
              },
              {
                id: 'msg-flow-label-2',
                value: 'task-management',
                nodeId: 'taskMsgFlow.flow'
              },
              {
                id: 'msg-flow-label-3',
                value: 'message-routing',
                nodeId: 'taskMsgFlow.flow'
              }
            ],
            updated: '14.04.2025',
            updatedByUser: { userName: 'Sarah Johnson', email: 'sarah.johnson@example.com' },
          }
        ],
        updated: '14.01.2025',
        updatedByUser: { userName: 'Michael Chen', email: 'michael.chen@example.com' },
      },
      {
        id: '100_residence',
        name: '100_residence',
        type: 'folder',
        comments: undefined,
        expanded: false,
        reference: false,
        locked: false,
        error: false,
        labels: [
          {
            id: 'residence-label-1',
            value: 'housing',
            nodeId: '100_residence'
          },
          {
            id: 'residence-label-2',
            value: 'category-100',
            nodeId: '100_residence'
          }
        ],
        children: [
          {
            id: 'ref-article-ref1',
            name: 'ref.article',
            type: 'article',
            comments: undefined,
            expanded: false,
            reference: true,
            locked: false,
            error: false,
            updated: '28.04.2025',
            updatedByUser: { userName: 'Tom Walsh', email: 'tom.walsh@example.com' },
          },
          {
            id: 'general-message-ref1',
            name: 'general-message.service',
            type: 'service',
            comments: undefined,
            expanded: false,
            reference: true,
            locked: false,
            error: false,
            updated: '05.05.2025',
            updatedByUser: { userName: 'Diana Hasselback', email: 'diana.hasselback@example.com' },
          },
          {
            id: 'public-inforeq.service',
            name: 'public-inforeq.service',
            type: 'service',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            configOptions: [{
              devMode: true,
              assignableMode: true,
            }],
            updated: '12.05.2025',
            updatedByUser: { userName: 'John Smith', email: 'john.smith@example.com' },
          },
          {
            id: 'public-inforeq.dialob',
            name: 'public-inforeq.dialob',
            type: 'dialob',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            updated: '19.05.2025',
            updatedByUser: { userName: 'Anna Virtanen', email: 'anna.virtanen@example.com' },
          },
          {
            id: 'taskGenericFlow-ref1',
            name: 'taskGenericFlow.flow',
            type: 'flow',
            comments: undefined,
            expanded: false,
            reference: true,
            locked: false,
            error: false,
            updated: '26.05.2025',
            updatedByUser: { userName: 'Mikael Berg', email: 'mikael.berg@example.com' },
          }
        ],
        updated: '21.04.2025',
        updatedByUser: { userName: 'Michael Chen', email: 'michael.chen@example.com' },
      },
      {
        id: '200_democracy',
        name: '200_democracy',
        type: 'folder',
        comments: undefined,
        expanded: false,
        reference: false,
        locked: false,
        error: false,
        labels: [
          {
            id: 'democracy-label-1',
            value: 'governance',
            nodeId: '200_democracy'
          },
          {
            id: 'democracy-label-2',
            value: 'sensitive',
            nodeId: '200_democracy'
          },
          {
            id: 'democracy-label-3',
            value: 'temporary',
            nodeId: '200_democracy'
          },
          {
            id: 'democracy-label-4',
            value: 'voting-rights',
            nodeId: '200_democracy'
          },
          {
            id: 'democracy-label-5',
            value: 'hasPrintout',
            nodeId: '200_democracy'
          }
        ],
        children: [
          {
            id: 'ref-article-ref2',
            name: 'ref.article',
            type: 'article',
            comments: undefined,
            expanded: false,
            reference: true,
            locked: false,
            error: false,
            updated: '09.06.2025',
            updatedByUser: { userName: 'Michael Chen', email: 'michael.chen@example.com' },
          },
          {
            id: 'trustee-info-form.service',
            name: 'trustee-info-form.service',
            type: 'service',
            comments: undefined,
            expanded: true,
            reference: false,
            locked: false,
            error: false,
            children: [
              {
                id: 'fi-trustee',
                name: 'fi',
                type: 'language',
                comments: undefined,
                expanded: false,
                reference: false,
                locked: false,
                error: false,
                description: 'Luottamushenkilön tietolomake',
                updated: '23.06.2025',
                updatedByUser: { userName: 'Diana Hasselback', email: 'diana.hasselback@example.com' },
              }
            ],
            updated: '16.06.2025',
            updatedByUser: { userName: 'Tom Walsh', email: 'tom.walsh@example.com' },
          },
          {
            id: 'trustee-info.dialob',
            name: 'trustee-info.dialob',
            type: 'dialob',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            updated: '30.06.2025',
            updatedByUser: { userName: 'John Smith', email: 'john.smith@example.com' },
          },
          {
            id: 'taskGenericFlow-ref2',
            name: 'taskGenericFlow.flow',
            type: 'flow',
            comments: undefined,
            expanded: false,
            reference: true,
            locked: false,
            error: false,
            updated: '07.07.2025',
            updatedByUser: { userName: 'Anna Virtanen', email: 'anna.virtanen@example.com' },
          },
          {
            id: 'trustee-travel-pay.service',
            name: 'trustee-travel-pay.service',
            type: 'service',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            updated: '14.07.2025',
            updatedByUser: { userName: 'Mikael Berg', email: 'mikael.berg@example.com' },
          },
          {
            id: 'trustee-travel-pay.dialob',
            name: 'trustee-travel-pay.dialob',
            type: 'dialob',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            updated: '21.07.2025',
            updatedByUser: { userName: 'Sarah Johnson', email: 'sarah.johnson@example.com' },
          },
          {
            id: 'general-message-ref2',
            name: 'general-message.service',
            type: 'service',
            comments: undefined,
            expanded: false,
            reference: true,
            locked: false,
            error: false,
            updated: '28.07.2025',
            updatedByUser: { userName: 'Michael Chen', email: 'michael.chen@example.com' },
          }
        ],
        updated: '02.06.2025',
        updatedByUser: { userName: 'Sarah Johnson', email: 'sarah.johnson@example.com' },
      },
      {
        id: '350_education',
        name: '350_education',
        type: 'folder',
        comments: undefined,
        expanded: false,
        reference: false,
        locked: false,
        error: false,
        children: [
          {
            id: 'ref-article-ref3',
            name: 'ref.article',
            type: 'article',
            comments: undefined,
            expanded: false,
            reference: true,
            locked: false,
            error: false,
            updated: '11.08.2025',
            updatedByUser: { userName: 'Diana Hasselback', email: 'diana.hasselback@example.com' },
          },
          {
            id: 'wilma-preschool.service',
            name: 'wilma-preschool.service',
            type: 'service',
            comments: undefined,
            expanded: true,
            reference: false,
            locked: false,
            error: false,
            children: [
              {
                id: 'fi-wilma',
                name: 'fi',
                type: 'language',
                comments: undefined,
                expanded: false,
                reference: false,
                locked: false,
                error: false,
                description: 'Wilmatunnukset esiopetuslapsen huoltajalle',
                updated: '25.08.2025',
                updatedByUser: { userName: 'Anna Virtanen', email: 'anna.virtanen@example.com' },
              }
            ],
            updated: '18.08.2025',
            updatedByUser: { userName: 'John Smith', email: 'john.smith@example.com' },
          },
          {
            id: 'wilma-preschool.dialob',
            name: 'wilma-preschool.dialob',
            type: 'dialob',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            updated: '01.09.2025',
            updatedByUser: { userName: 'Mikael Berg', email: 'mikael.berg@example.com' },
          },
          {
            id: 'taskGenericFlow-ref3',
            name: 'taskGenericFlow.flow',
            type: 'flow',
            comments: undefined,
            expanded: false,
            reference: true,
            locked: false,
            error: false,
            updated: '08.09.2025',
            updatedByUser: { userName: 'Sarah Johnson', email: 'sarah.johnson@example.com' },
          },
          {
            id: 'protection-order-school.service',
            name: 'protection-order-school.service',
            type: 'service',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            updated: '15.09.2025',
            updatedByUser: { userName: 'Michael Chen', email: 'michael.chen@example.com' },
          },
          {
            id: 'protection-order-school.dialob',
            name: 'protection-order-school.dialob',
            type: 'dialob',
            error: true,
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            updated: '22.09.2025',
            updatedByUser: { userName: 'Tom Walsh', email: 'tom.walsh@example.com' },
          },
          {
            id: 'general-message-ref3',
            name: 'general-message.service',
            type: 'service',
            comments: undefined,
            expanded: false,
            reference: true,
            locked: false,
            error: false,
            updated: '29.09.2025',
            updatedByUser: { userName: 'Diana Hasselback', email: 'diana.hasselback@example.com' },
          }
        ],
        updated: '04.08.2025',
        updatedByUser: { userName: 'Tom Walsh', email: 'tom.walsh@example.com' },
      },
      {
        id: '400_traffic-and-roads',
        name: '400_traffic-and-roads',
        type: 'folder',
        comments: undefined,
        expanded: false,
        reference: false,
        locked: false,
        error: false,
        children: [
          {
            id: 'ref-article-ref4',
            name: 'ref.article',
            type: 'article',
            comments: undefined,
            expanded: false,
            reference: true,
            locked: false,
            error: false,
            updated: '13.10.2025',
            updatedByUser: { userName: 'Anna Virtanen', email: 'anna.virtanen@example.com' },
          },
          {
            id: 'dig-permit.service',
            name: 'dig-permit.service',
            type: 'service',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            updated: '20.10.2025',
            updatedByUser: { userName: 'Mikael Berg', email: 'mikael.berg@example.com' },
          },
          {
            id: 'dig-permit.dialob',
            name: 'dig-permit.dialob',
            type: 'dialob',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            updated: '27.10.2025',
            updatedByUser: { userName: 'Sarah Johnson', email: 'sarah.johnson@example.com' },
          },
          {
            id: 'taskSplitFlow.flow',
            name: 'taskSplitFlow.flow',
            type: 'flow',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            configOptions: [{
              devMode: true,
              disabledMode: true,
              anonymousMode: true,
            }],
            updated: '03.11.2025',
            updatedByUser: { userName: 'Michael Chen', email: 'michael.chen@example.com' },
          },
          {
            id: 'rent-street-area.service',
            name: 'rent-street-area.service',
            type: 'service',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            updated: '10.11.2025',
            updatedByUser: { userName: 'Tom Walsh', email: 'tom.walsh@example.com' },
          },
          {
            id: 'rent-street-area.dialob',
            name: 'rent-street-area.dialob',
            type: 'dialob',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            updated: '17.11.2025',
            updatedByUser: { userName: 'Diana Hasselback', email: 'diana.hasselback@example.com' },
          },
          {
            id: 'private-road-sign.service',
            name: 'private-road-sign.service',
            type: 'service',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            updated: '24.11.2025',
            updatedByUser: { userName: 'John Smith', email: 'john.smith@example.com' },
          },
          {
            id: 'private-road-sign.dialob',
            name: 'private-road-sign.dialob',
            type: 'dialob',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            updated: '01.12.2025',
            updatedByUser: { userName: 'Anna Virtanen', email: 'anna.virtanen@example.com' },
          },
          {
            id: 'general-message-ref4',
            name: 'general-message.service',
            type: 'service',
            comments: undefined,
            expanded: false,
            reference: true,
            locked: false,
            error: false,
            updated: '08.12.2025',
            updatedByUser: { userName: 'Mikael Berg', email: 'mikael.berg@example.com' },
          }
        ],
        updated: '06.10.2025',
        updatedByUser: { userName: 'John Smith', email: 'john.smith@example.com' },
      },
      {
        id: '425_invoicing',
        name: '425_invoicing',
        type: 'folder',
        comments: undefined,
        expanded: false,
        reference: false,
        locked: false,
        error: false,
        children: [
          {
            id: 'main-invoicing.article',
            name: 'main.article',
            type: 'article',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            description: 'Laskutus',
            updated: '22.12.2025',
            updatedByUser: { userName: 'Michael Chen', email: 'michael.chen@example.com' },
          },
          {
            id: 'invoicing-erapaiva.service',
            name: 'invoicing-erapaiva.service',
            type: 'service',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            updated: '29.12.2025',
            updatedByUser: { userName: 'Tom Walsh', email: 'tom.walsh@example.com' },
          },
          {
            id: 'invoicing-erapaiva.dialob',
            name: 'invoicing-erapaiva.dialob',
            type: 'dialob',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            updated: '05.01.2026',
            updatedByUser: { userName: 'Diana Hasselback', email: 'diana.hasselback@example.com' },
          },
          {
            id: 'taskGenericFlow-ref4',
            name: 'taskGenericFlow.flow',
            type: 'flow',
            comments: undefined,
            expanded: false,
            reference: true,
            locked: false,
            error: false,
            updated: '12.01.2026',
            updatedByUser: { userName: 'John Smith', email: 'john.smith@example.com' },
          },
          {
            id: 'invoice-copy-request.service',
            name: 'invoice-copy-request.service',
            type: 'service',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            updated: '19.01.2026',
            updatedByUser: { userName: 'Anna Virtanen', email: 'anna.virtanen@example.com' },
          },
          {
            id: 'invoice-copy-request.dialob',
            name: 'invoice-copy-request.dialob',
            type: 'dialob',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            updated: '26.01.2026',
            updatedByUser: { userName: 'Mikael Berg', email: 'mikael.berg@example.com' },
          },
          {
            id: 'bank-account-info.service',
            name: 'bank-account-info.service',
            type: 'service',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            updated: '02.02.2026',
            updatedByUser: { userName: 'Sarah Johnson', email: 'sarah.johnson@example.com' },
          },
          {
            id: 'bank-account-info.dialob',
            name: 'bank-account-info.dialob',
            type: 'dialob',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            updated: '09.02.2026',
            updatedByUser: { userName: 'Michael Chen', email: 'michael.chen@example.com' },
          }
        ],
        updated: '15.12.2025',
        updatedByUser: { userName: 'Sarah Johnson', email: 'sarah.johnson@example.com' },
      },
      {
        id: '517_sipoo-institute',
        name: '517_sipoo-institute',
        type: 'folder',
        comments: undefined,
        expanded: false,
        reference: false,
        locked: false,
        error: false,
        children: [
          {
            id: 'main-institute.article',
            name: 'main.article',
            type: 'article',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            description: 'Sipoon opisto',
            updated: '23.02.2026',
            updatedByUser: { userName: 'Diana Hasselback', email: 'diana.hasselback@example.com' },
          },
          {
            id: 'teacher-info.service',
            name: 'teacher-info.service',
            type: 'service',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            updated: '02.03.2026',
            updatedByUser: { userName: 'John Smith', email: 'john.smith@example.com' },
          },
          {
            id: 'teacher-info.dialob',
            name: 'teacher-info.dialob',
            type: 'dialob',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            updated: '09.03.2026',
            updatedByUser: { userName: 'Anna Virtanen', email: 'anna.virtanen@example.com' },
          },
          {
            id: 'taskGenericFlow-ref5',
            name: 'taskGenericFlow.flow',
            type: 'flow',
            comments: undefined,
            expanded: false,
            reference: true,
            locked: false,
            error: false,
            updated: '16.03.2026',
            updatedByUser: { userName: 'Mikael Berg', email: 'mikael.berg@example.com' },
          },
          {
            id: 'teacher-travel-pay.service',
            name: 'teacher-travel-pay.service',
            type: 'service',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            updated: '08.01.2025',
            updatedByUser: { userName: 'Sarah Johnson', email: 'sarah.johnson@example.com' },
          },
          {
            id: 'teacher-travel-pay.dialob',
            name: 'teacher-travel-pay.dialob',
            type: 'dialob',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            updated: '15.01.2025',
            updatedByUser: { userName: 'Tom Walsh', email: 'tom.walsh@example.com' },
          },
          {
            id: 'study-voucher.service',
            name: 'study-voucher.service',
            type: 'service',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            updated: '22.01.2025',
            updatedByUser: { userName: 'Michael Chen', email: 'michael.chen@example.com' },
          },
          {
            id: 'study-voucher.dialob',
            name: 'study-voucher.dialob',
            type: 'dialob',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            updated: '29.01.2025',
            updatedByUser: { userName: 'Anna Virtanen', email: 'anna.virtanen@example.com' },
          },
          {
            id: 'general-message-ref5',
            name: 'general-message.service',
            type: 'service',
            comments: undefined,
            expanded: false,
            reference: true,
            locked: false,
            error: false,
            updated: '05.02.2025',
            updatedByUser: { userName: 'John Smith', email: 'john.smith@example.com' },
          }
        ],
        updated: '16.02.2026',
        updatedByUser: { userName: 'Tom Walsh', email: 'tom.walsh@example.com' },
      },
      {
        id: '520_sipoo-water',
        name: '520_sipoo-water',
        type: 'folder',
        comments: undefined,
        expanded: false,
        reference: false,
        locked: false,
        error: false,
        configOptions: [{
          disabledMode: true,
        }],
        children: [
          {
            id: 'main-water.article',
            name: 'main.article',
            type: 'article',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            description: 'Sipoon Vesi',
            updated: '19.02.2025',
            updatedByUser: { userName: 'Diana Hasselback', email: 'diana.hasselback@example.com' },
          },
          {
            id: 'water-supply-maintenance.service',
            name: 'water-supply-maintenance.service',
            type: 'service',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            updated: '26.02.2025',
            updatedByUser: { userName: 'Sarah Johnson', email: 'sarah.johnson@example.com' },
          },
          {
            id: 'water-supply-maintenance.dialob',
            name: 'water-supply-maintenance.dialob',
            type: 'dialob',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            updated: '05.03.2025',
            updatedByUser: { userName: 'Tom Walsh', email: 'tom.walsh@example.com' },
          },
          {
            id: 'taskGenericFlow-ref6',
            name: 'taskGenericFlow.flow',
            type: 'flow',
            comments: undefined,
            expanded: false,
            reference: true,
            locked: false,
            error: false,
            updated: '12.03.2025',
            updatedByUser: { userName: 'Michael Chen', email: 'michael.chen@example.com' },
          },
          {
            id: 'water-invoice-erapaiva.service',
            name: 'water-invoice-erapaiva.service',
            type: 'service',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            updated: '19.03.2025',
            updatedByUser: { userName: 'Anna Virtanen', email: 'anna.virtanen@example.com' },
          },
          {
            id: 'water-invoice-erapaiva.dialob',
            name: 'water-invoice-erapaiva.dialob',
            type: 'dialob',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            updated: '26.03.2025',
            updatedByUser: { userName: 'John Smith', email: 'john.smith@example.com' },
          },
          {
            id: 'water-connection-statement.service',
            name: 'water-connection-statement.service',
            type: 'service',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            updated: '02.04.2025',
            updatedByUser: { userName: 'Mikael Berg', email: 'mikael.berg@example.com' },
          },
          {
            id: 'water-connection-statement.dialob',
            name: 'water-connection-statement.dialob',
            type: 'dialob',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            updated: '09.04.2025',
            updatedByUser: { userName: 'Diana Hasselback', email: 'diana.hasselback@example.com' },
          },
          {
            id: 'general-message-ref6',
            name: 'general-message.service',
            type: 'service',
            comments: undefined,
            expanded: false,
            reference: true,
            locked: false,
            error: false,
            updated: '16.04.2025',
            updatedByUser: { userName: 'Sarah Johnson', email: 'sarah.johnson@example.com' },
          }
        ],
        updated: '12.02.2025',
        updatedByUser: { userName: 'Mikael Berg', email: 'mikael.berg@example.com' },
      },
      {
        id: '650_leisure-time-and-youth',
        name: '650_leisure-time-and-youth',
        type: 'folder',
        comments: undefined,
        expanded: false,
        reference: false,
        locked: false,
        error: false,
        children: [
          {
            id: 'main-leisure.article',
            name: 'main.article',
            type: 'article',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            description: 'Vapaa-aika ja nuoret',
            updated: '30.04.2025',
            updatedByUser: { userName: 'Michael Chen', email: 'michael.chen@example.com' },
          },
          {
            id: 'sports-grant-settlement.service',
            name: 'sports-grant-settlement.service',
            type: 'service',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            updated: '07.05.2025',
            updatedByUser: { userName: 'Anna Virtanen', email: 'anna.virtanen@example.com' },
          },
          {
            id: 'sports-grant-settlement.dialob',
            name: 'sports-grant-settlement.dialob',
            type: 'dialob',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            updated: '14.05.2025',
            updatedByUser: { userName: 'John Smith', email: 'john.smith@example.com' },
          },
          {
            id: 'taskGenericFlow-ref7',
            name: 'taskGenericFlow.flow',
            type: 'flow',
            comments: undefined,
            expanded: false,
            reference: true,
            locked: false,
            error: false,
            updated: '21.05.2025',
            updatedByUser: { userName: 'Mikael Berg', email: 'mikael.berg@example.com' },
          },
          {
            id: 'sports-fee-return.service',
            name: 'sports-fee-return.service',
            type: 'service',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            updated: '28.05.2025',
            updatedByUser: { userName: 'Diana Hasselback', email: 'diana.hasselback@example.com' },
          },
          {
            id: 'sports-fee-return.dialob',
            name: 'sports-fee-return.dialob',
            type: 'dialob',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            updated: '04.06.2025',
            updatedByUser: { userName: 'Sarah Johnson', email: 'sarah.johnson@example.com' },
          },
          {
            id: 'children-sport-grant.service',
            name: 'children-sport-grant.service',
            type: 'service',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            updated: '11.06.2025',
            updatedByUser: { userName: 'Tom Walsh', email: 'tom.walsh@example.com' },
          },
          {
            id: 'children-sport-grant.dialob',
            name: 'children-sport-grant.dialob',
            type: 'dialob',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            updated: '18.06.2025',
            updatedByUser: { userName: 'Michael Chen', email: 'michael.chen@example.com' },
          }
        ],
        updated: '23.04.2025',
        updatedByUser: { userName: 'Tom Walsh', email: 'tom.walsh@example.com' },
      }
    ],
    updated: '07.01.2025',
    updatedByUser: { userName: 'Sarah Johnson', email: 'sarah.johnson@example.com' },
  },
  {
    id: 'shared',
    name: 'shared',
    type: 'folder',
    comments: undefined,
    expanded: false,
    reference: false,
    locked: false,
    error: false,
    children: [
      {
        id: 'shared-taskGenericFlow.flow',
        name: 'taskGenericFlow.flow',
        type: 'flow',
        comments: undefined,
        expanded: false,
        reference: false,
        locked: false,
        error: false,
        updated: '02.07.2025',
        updatedByUser: { userName: 'John Smith', email: 'john.smith@example.com' },
      },
      {
        id: 'shared-taskMsgFlow.flow',
        name: 'taskMsgFlow.flow',
        type: 'flow',
        comments: undefined,
        expanded: false,
        reference: false,
        locked: false,
        error: false,
        updated: '09.07.2025',
        updatedByUser: { userName: 'Mikael Berg', email: 'mikael.berg@example.com' },
      },
      {
        id: 'shared-taskSplitFlow.flow',
        name: 'taskSplitFlow.flow',
        type: 'flow',
        comments: undefined,
        expanded: false,
        reference: false,
        locked: false,
        error: false,
        updated: '16.07.2025',
        updatedByUser: { userName: 'Diana Hasselback', email: 'diana.hasselback@example.com' },
      }
    ],
    updated: '25.06.2025',
    updatedByUser: { userName: 'Anna Virtanen', email: 'anna.virtanen@example.com' },
  },
  {
    id: 'links',
    name: 'links',
    type: 'folder',
    comments: undefined,
    expanded: false,
    reference: false,
    locked: false,
    error: false,
    children: [
      {
        id: 'sipoo-main-site.link',
        name: 'sipoo-main-site.link',
        type: 'link',
        comments: undefined,
        expanded: false,
        reference: false,
        locked: false,
        error: false,
        description: 'https://www.sipoo.fi',
        configOptions: [{
          devMode: true,
        }],
        updated: '30.07.2025',
        updatedByUser: { userName: 'Tom Walsh', email: 'tom.walsh@example.com' },
      },
      {
        id: 'wilma-info.link',
        name: 'wilma-info.link',
        type: 'link',
        comments: undefined,
        expanded: false,
        reference: false,
        locked: false,
        error: false,
        updated: '06.08.2025',
        updatedByUser: { userName: 'Michael Chen', email: 'michael.chen@example.com' },
      },
      {
        id: 'lupapiste.link',
        name: 'lupapiste.link',
        type: 'link',
        comments: undefined,
        expanded: false,
        reference: false,
        locked: false,
        error: false,
        configOptions: [{
          disabledMode: true,
        }],
        updated: '13.08.2025',
        updatedByUser: { userName: 'Anna Virtanen', email: 'anna.virtanen@example.com' },
      }
    ],
    updated: '23.07.2025',
    updatedByUser: { userName: 'Sarah Johnson', email: 'sarah.johnson@example.com' },
  },
  {
    id: 'printouts',
    name: 'printouts',
    type: 'folder',
    comments: undefined,
    expanded: false,
    reference: false,
    locked: false,
    error: false,
    children: [
      {
        id: 'sipoo-main-logo.png',
        name: 'sipoo-main-logo.png',
        type: 'image',
        comments: undefined,
        expanded: false,
        reference: false,
        locked: false,
        error: false,
        description: 'logo: black and white',
        updated: '27.08.2025',
        updatedByUser: { userName: 'Mikael Berg', email: 'mikael.berg@example.com' },
      },
      {
        id: 'sipoo-color-logo.png',
        name: 'sipoo-color-logo.png',
        type: 'image',
        comments: undefined,
        expanded: false,
        reference: false,
        locked: false,
        error: false,
        description: 'logo: full color version',
        updated: '03.09.2025',
        updatedByUser: { userName: 'Diana Hasselback', email: 'diana.hasselback@example.com' },
      },
      {
        id: 'municipal-seal.svg',
        name: 'municipal-seal.svg',
        type: 'image',
        comments: undefined,
        expanded: false,
        reference: false,
        locked: false,
        error: false,
        description: 'official municipal seal',
        updated: '10.09.2025',
        updatedByUser: { userName: 'Sarah Johnson', email: 'sarah.johnson@example.com' },
      },
      {
        id: 'new-construction-permit.printout',
        name: 'new-construction-permit.printout',
        type: 'printout',
        comments: undefined,
        expanded: false,
        reference: false,
        locked: false,
        error: false,
        children: [
          {
            id: 'fi-construction-permit',
            name: 'fi',
            type: 'template',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            description: 'Finnish construction permit template',
            updated: '24.09.2025',
            updatedByUser: { userName: 'Michael Chen', email: 'michael.chen@example.com' },
          },
          {
            id: 'sv-construction-permit',
            name: 'sv',
            type: 'template',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            description: 'Swedish construction permit template',
            updated: '01.10.2025',
            updatedByUser: { userName: 'Anna Virtanen', email: 'anna.virtanen@example.com' },
          }
        ],
        updated: '17.09.2025',
        updatedByUser: { userName: 'Tom Walsh', email: 'tom.walsh@example.com' },
      },
      {
        id: 'municipal-services-guide.printout',
        name: 'municipal-services-guide.printout',
        type: 'printout',
        comments: undefined,
        expanded: false,
        reference: false,
        locked: false,
        error: false,
        children: [
          {
            id: 'fi-services-guide',
            name: 'fi',
            type: 'template',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            description: 'Kunnan palveluopas',
            updated: '15.10.2025',
            updatedByUser: { userName: 'Mikael Berg', email: 'mikael.berg@example.com' },
          },
          {
            id: 'sv-services-guide',
            name: 'sv',
            type: 'template',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            description: 'Kommunal servicehandbok',
            updated: '22.10.2025',
            updatedByUser: { userName: 'Diana Hasselback', email: 'diana.hasselback@example.com' },
          },
          {
            id: 'en-services-guide',
            name: 'en',
            type: 'template',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            description: 'Municipal services guide',
            updated: '29.10.2025',
            updatedByUser: { userName: 'Sarah Johnson', email: 'sarah.johnson@example.com' },
          }
        ],
        updated: '08.10.2025',
        updatedByUser: { userName: 'John Smith', email: 'john.smith@example.com' },
      },
      {
        id: 'waste-management-info.printout',
        name: 'waste-management-info.printout',
        type: 'printout',
        comments: undefined,
        expanded: false,
        reference: false,
        locked: false,
        error: false,
        children: [
          {
            id: 'fi-waste-info',
            name: 'fi',
            type: 'template',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            description: 'Jätehuolto-ohje',
            updated: '12.11.2025',
            updatedByUser: { userName: 'Michael Chen', email: 'michael.chen@example.com' },
          }
        ],
        updated: '05.11.2025',
        updatedByUser: { userName: 'Tom Walsh', email: 'tom.walsh@example.com' },
      },
      {
        id: 'tax-information-leaflet.printout',
        name: 'tax-information-leaflet.printout',
        type: 'printout',
        comments: undefined,
        expanded: false,
        reference: false,
        locked: false,
        error: false,
        children: [
          {
            id: 'fi-tax-info',
            name: 'fi',
            type: 'template',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            description: 'Verotietoesite',
            updated: '26.11.2025',
            updatedByUser: { userName: 'John Smith', email: 'john.smith@example.com' },
          },
          {
            id: 'sv-tax-info',
            name: 'sv',
            type: 'template',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            description: 'Skatteinformationsbroschyr',
            updated: '03.12.2025',
            updatedByUser: { userName: 'Mikael Berg', email: 'mikael.berg@example.com' },
          },
          {
            id: 'en-tax-info',
            name: 'en',
            type: 'template',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            description: 'Tax information leaflet',
            updated: '10.12.2025',
            updatedByUser: { userName: 'Diana Hasselback', email: 'diana.hasselback@example.com' },
          },
          {
            id: 'ee-tax-info',
            name: 'ee',
            type: 'template',
            comments: undefined,
            expanded: false,
            reference: false,
            locked: false,
            error: false,
            description: 'Maksuteabe leht',
            updated: '17.12.2025',
            updatedByUser: { userName: 'Sarah Johnson', email: 'sarah.johnson@example.com' },
          }
        ],
        updated: '19.11.2025',
        updatedByUser: { userName: 'Anna Virtanen', email: 'anna.virtanen@example.com' },
      }
    ],
    updated: '20.08.2025',
    updatedByUser: { userName: 'John Smith', email: 'john.smith@example.com' },
  },
];