spring:
  config.activate.on-profile: 'dev'
  jpa:
    showSql: false
    generateDdl: false
    hibernate:
      ddlAuto: "validate"
      autoQuoteKeyword: true
      connection:
        useUnicode: true
        characterEncoding: 'UTF-8'
        charSet: 'UTF-8'
  flyway:
    enabled: true
    locations: classpath:db/postgresql
    validate-on-migrate: true

management:
  server:
    servlet.context-path: "/manage"
    add-application-context-header: false
  endpoints:
    web:
      exposure:
        include: "health,mappings"

# Logging config
logging.level.org.springframework.web: DEBUG
#logging.org.springframework.http: DEBUG
#logging.level.org.springframework.boot: DEBUG


# DB config
spring.datasource.url: "jdbc:postgresql://localhost:5433/eveli-app"
spring.datasource.username: "eveli-app"
spring.datasource.password: "password123"

eveli.task.adminsearch: true

# dialob related config
eveli.dialob.enabled: true
eveli.dialob.service-url: http://localhost:9000
eveli.dialob.api-key: