spring:
  jpa:
    showSql: false
    generateDdl: false
    hibernate:
      ddlAuto: "validate"
      autoQuoteKeyword: true
      connection:
        useUnicode: true
        characterEncoding: 'UTF-8'
        charSet: 'UTF-8'
  flyway:
    enabled: true
    locations: classpath:db/postgresql
    validate-on-migrate: true

management:
  server:
    servlet.context-path: "/manage"
    add-application-context-header: false
  endpoints:
    web:
      exposure:
        include: "health,mappings"

# Logging config
#logging.level.org.springframework.web: INFO
#logging.org.springframework.http: INFO
#logging.level.org.springframework.boot: INFO

logging.level.io.vertx.core.impl.btc.BlockedThreadChecker: OFF
logging.level.io.vertx.core.impl.BlockedThreadChecker: OFF


# DB config
spring.datasource.url: "jdbc:postgresql://localhost:5433/eveli-app"
spring.datasource.username: "eveli-app"
spring.datasource.password: "password123"

# gamut config
eveli.gamut.anon-forms: palautteet


eveli.task.adminsearch: true
eveli.assets.timezoneOffset: +2

# dialob related config
eveli.dialob.enabled: true
eveli.dialob.service-url: http://localhost:9000
eveli.dialob.api-key:
  
# jwt linked crm from security proxy
eveli.crm.enabled: false
eveli.crm.host: 
eveli.crm.service-path-company: gw/api/ypa/organizationRoles
eveli.crm.service-path-person: gw/api/hpa/authorizationList
  
# feedback  
eveli.feedback.enabled: true
eveli.feedback.forms: palautteet
eveli.feedback.category-main: mainList
eveli.feedback.category-sub: cityServiceGroup, preschoolEducationGroup, cityServiceMainList, constructionMainList, youthServiceMainList, exerciseMainList, schoolMainList, employmentImmigrationMainList, freeTimeCultureMainList, preschoolMainList, communicationMainList, cooperationMainList
eveli.feedback.question-title: feedBackTitle
eveli.feedback.question: feedBackTxt
eveli.feedback.username-allowed: publicAnswerAllowed
  
app.jwt.public-key-value:
app.jwt.issuer: "https://frontdesk.digiexpress.io/gateway/issuer"
app.jwt.portal.public-key-value: 
app.jwt.portal.issuer: "https://portal.digiexpress.io/gateway/issuer"
