export const bs = {
  'booleanValue.true': 'Da',
  'booleanValue.false': 'Ne',
  'cust.inbox.message.sender-name.org-user': 'Info pult',
  'cust.phone': 'Telefon: 123 456 7890',
  'cust.email': 'info@lifeDigital.com',
  'header.userIdentity.label': 'Prijavljeni ste kao',
  'document.title': 'DigiExpress',
  'footer.column2.title': 'DigiExpress',
  'footer.column2.subtitle': 'Open-source platforma za usluge digitalizacije',
  'footer.column3.title': 'Brzi linkovi',
  'footer.column3.link.acessibility': 'Izjava o pristupačnosti',
  'footer.column3.link.dataProtection': 'Zaštita podataka',
  'footer.column3.link.feedback': 'Povratne informacije i razvojne ideje',
  'footer.column3.link.siteInfo': 'Informacije o stranici',
  'footer.column3.link.newsletter': 'Pretplatite se na newsletter',
  'footer.column4.title': 'DigiExpress info',
  'footer.column4.email': 'Email: info@digiExpress.io',
  'footer.column4.phone': 'Telefon: 123 456 7890',
  'footer.column4.address': 'Adresa za posjetu: 1234 Any Street MyTown',
  'footer.column4.postalCode': 'Poštanski broj: 1234',
  'gamut.forms': 'Obrasci',
  'gamut.new-messages': 'Nove poruke',
  'gamut.services': 'Usluge',
  'gamut.bookings': 'Kalendarske rezervacije',
  'gamut.noValueIndicator': '-',
  'gamut.noValueIndicatorColon': '-',
  'gamut.textSeparatorColon': ':',
  'gamut.loading': 'Učitavanje sadržaja',
  'gamut.public.servicesHome': 'Usluge',
  'gamut.public.forms.summary.button.backToServicesHome': 'Povratak na usluge',
  'gamut.buttons.login': 'Prijava',
  'gamut.buttons.logout': 'Odjava',
  'gamut.buttons.search': 'Pretraga',
  'gamut.buttons.cancel': 'Otkaži',
  'gamut.buttons.select': 'Odaberi',
  'gamut.buttons.close': 'Zatvori',
  'gamut.buttons.reply': 'Odgovori',
  'gamut.buttons.serviceSelect': 'Naše usluge',
  'gamut.buttons.attachment.add': 'Dodaj prilog',
  'gamut.locale.en': 'Engleski',
  'gamut.locale.fi': 'Finski',
  'gamut.locale.sv': 'Švedski',
  'gamut.locale.my': 'Malajski',
  'gamut.locale.bs': 'Bosanski',
  'gamut.search.placeholder': 'Pretraga naših usluga',
  'gamut.search.popover.title': 'Pretraga naše stranice',
  'gamut.search.popover.input.placeholder': 'Unesi pojam za pretragu',
  'gamut.search.popover.allForms': 'Sve forme',
  'gamut.search.popover.allPhones': 'Svi brojevi telefona',
  'gamut.search.popover.allLinks': 'Svi linkovi',
  'gamut.search.popover.allServices': 'Sve usluge',
  'gamut.search.results.allResults': 'Svi rezultati',
  'gamut.search.results.noResults': 'Nema rezultata',
  'gamut.search.results.serviceLinks': 'Usluge',
  'gamut.search.results.formLinks': 'Obrasci',
  'gamut.search.results.phoneLinks': 'Telefoni',
  'gamut.search.results.internalExternalLinks': 'Linkovi',
  'gamut.search.results.internalLinks': 'Linkovi',
  'gamut.search.results.externalLinks': 'Eksterni linkovi',
  'gamut.article.pagelinks.forms.title': 'Obrasci',
  'gamut.article.pagelinks.otherlinks.title': 'Linkovi',
  'gamut.forms.formName': 'Ime',
  'gamut.forms.taskRefId': 'Referentni broj',
  'gamut.forms.started': 'Započeto',
  'gamut.forms.attachments': 'Prilozi',
  'gamut.forms.status': 'Status',
  'gamut.forms.status.OPEN': 'U toku',
  'gamut.forms.status.NEW': 'Obrada počinje uskoro',
  'gamut.forms.status.COMPLETED': 'Završeno',
  'gamut.forms.status.REJECTED': 'Odbijeno',
  'gamut.forms.status.DELEGATED': 'Završeno',
  'gamut.forms.status.TRANSFERRED': 'U toku',
  'gamut.forms.status.WAITING': 'U toku',
  'gamut.forms.lastModified': 'Zadnje izmijenjeno',
  'gamut.forms.files': 'Datoteke',
  'gamut.forms.messages': 'Poruke',
  'gamut.forms.page.subtitle': 'Sljedeće:{nextPageTitle}',
  'gamut.forms.page.subtitle.complete': 'Sljedeće: Završi',
  'gamut.forms.page.stepper': '{start] od {end}',
  'gamut.forms.page.selection.key': 'Korak {stepNumber} od {totalSteps}',
  'gamut.forms.page.next': 'Sledeći',
  'gamut.forms.page.complete': 'Završi',
  'gamut.forms.page.cancel': 'Otkaži',
  'gamut.forms.filling.welcome': 'Dobrodošli!',
  'gamut.forms.filling.must_be_authenticated': 'Za popunjavanje obrasca potrebno je biti prijavljen',
  'gamut.forms.filling.authenticated_and_welcome': 'Zdravo {userName}!',
  'gamut.forms.filling.proceed_to_form': 'Kliknite ispod da pokrenete obrazac',
  'gamut.forms.filling.anonUser_and_welcome': 'Hello!',
  'gamut.forms.filling.start': 'Popunjavanje obrasca započinje',
  'gamut.forms.filling.login-then-start.button': 'Prijavi se sada',
  'gamut.forms.filling.start.info1': 'Obrazac se automatski sprema tokom popunjavanja',
  'gamut.forms.filling.start.button': 'Nastavak na obrazac',
  'gamut.forms.filling.cancel.button': 'Otkaži',
  'gamut.forms.filling.summary': 'Obrazac je uspješno popunjen',
  'gamut.forms.filling.summary.thank-you': 'Hvala!',
  'gamut.forms.filling.summary.info1': 'Osoblje je obaviješteno o zahtjevu i uskoro će početi s obradom.',
  'gamut.forms.filling.summary.info2': 'Preporučuje se redovno provjeravati Moj pregled',
  'gamut.forms.filling.summary.info3': 'Ažuriranje statusa obrade obrasca',
  'gamut.forms.filling.summary.info4': 'Nove poruke osoblja u vezi sa zahtjevom',
  'gamut.forms.filling.summary.info5': 'Nove poslane ili zatražene datoteke',
  'gamut.forms.filling.summary.info6': 'Za dodatna pitanja moguće je kontaktirati telefonom na xxxx-xxxx',
  'gamut.forms.filling.representativeNotAuthorized': 'Nemate ovlasti za ispunjavanje ovog obrasca. Obratite se našem uredu.',
  'gamut.forms.summary.button.back-to-overview': 'Povratak na Moj pregled',
  'gamut.forms.answer.date.placeholder.day': 'dd',
  'gamut.forms.answer.date.placeholder.month': 'mm',
  'gamut.forms.answer.date.placeholder.year': 'gggg',
  'gamut.forms.answer.date.placeholder.hour': 'ss',
  'gamut.forms.answer.date.placeholder.minute': 'mm',
  'gamut.forms.answer.boolean.yes': 'Da',
  'gamut.forms.answer.boolean.no': 'Ne',
  'gamut.forms.unfinished.none': 'Nema nedovršenih obrazaca',
  'gamut.forms.unfinished.title': 'Nedovršeni obrasci',
  'gamut.forms.unfinished.subtitle': 'Obrada nije započeta - Potrebno je odabrati formu za nastavak popunjavanja, ili otkazati',
  'gamut.forms.awaitingDecision.title': 'Obrasci koji čekaju na odluku',
  'gamut.forms.awaitingDecision.subtitle': 'Obrada je započeta - Naše osoblje radi na ovom zahtjevu',
  'gamut.forms.withDecision.title': 'Obrasci sa konačnom odlukom',
  'gamut.forms.withDecision.subtitle': 'Obrada je završena',
  'gamut.offers.deleteForm.title': 'Izbrisati nedovršene obrasce',
  'gamut.offers.deleteForm.content': 'Želiš li izbrisati ovu formu? Ova radnja se ne može poništiti.',
  'gamut.offers.deleteForm.cancelButton': 'Ne, zadrži ovaj obrazac',
  'gamut.offers.deleteForm.deleteButton': 'Da, izbriši ovaj obrazac',
  'gamut.inbox.title': 'Dolazne poruke',
  'gamut.inbox.subtitle': 'Poruke i datoteke povezane sa obrascima',
  'gamut.inbox.messages.title': 'Poruke',
  'gamut.inbox.subjectAttachment.title': 'Prilozi',
  'gamut.inbox.newMessage.placeholder': 'Unesi poruku',
  'gamut.inbox.newMessage.replyingTo': 'Odgovor na',
  'gamut.inbox.newMessage.sendNew': 'Pošalji novu poruku',
  'gamut.inbox.newMessage.replyingTo.subject': 'Predmet',
  'gamut.inbox.newMessage.notAllowed1': 'Ovaj obrazac je uspješno obrađen i slanje novih poruka je onemogućeno.',
  'gamut.inbox.newMessage.notAllowed2': 'Izvinjavamo se zbog neugodnosti.',
  'gamut.inbox.newMessage.notAllowed.questions': 'Za dodatna pitanja moguće je kontaktirati telefonom ili e-mailom.',
  'gamut.inbox.noMessages': 'Nema poruka',
  'gamut.inbox.newMessageFrom': 'Nova poruka od',
  'gamut.subjectMessage.title': 'Poruke o {subject}',
  'gamut.bookings.title': 'Kalendarske rezervacije',
  'gamut.bookings.subtitle': 'Upravljanje postojećim terminima i rezervacijama ovdje',
  'gamut.bookings.serviceName': 'Naziv usluge',
  'gamut.bookings.bookingDateTime': 'Zakazani datum i vrijeme',
  'gamut.bookings.deleteBooking.title': 'Otkazivanje rezervacije',
  'gamut.bookings.deleteBooking.content': 'Želite li otkazati ovu rezervaciju? Ova radnja se ne može poništiti.',
  'gamut.bookings.deleteBooking.cancelButton': 'Ne, zadrži moju rezervaciju',
  'gamut.bookings.deleteBooking.deleteButton': 'Da, otkaži ovu rezervaciju',
  'gamut.userOverview.services.detail.title': 'Pronađi uslugu i pokreni obrazac',
  'gamut.userOverview.buttons.logout-representative': 'Odjava predstavnika',
  'gamut.userOverview.buttons.login-representative': 'Prijava predstavnika',
  'gamut.userOverview.buttons.logout': 'Odjava',
  'gamut.userOverview.buttons.logout-company': 'Odjava kompanije',
  'gamut.userOverview.buttons.login-company': 'Prijava kompanije',
  'gamut.userOverview.buttons.user-overview': 'Moj pregled',
  'gamut.userOverview.buttons.services': 'Pronađi uslugu i pokreni obrazac',
  'gamut.userOverview.buttons.requests-in-progress': 'Nedovršeni obrasci',
  'gamut.userOverview.buttons.awaiting-decision': 'Obrasci koji čekaju na odluku',
  'gamut.userOverview.buttons.with-decision': 'Obrasci sa konačnom odlukom',
  'gamut.userOverview.buttons.inbox': 'Dolazne poruke',
  'gamut.userOverview.buttons.bookings': 'Kalendarske rezervacije',
  'gamut.userOverview.home': 'Moj pregled',
  'gamut.userOverview.welcome.title': 'Dobrodošli na Moj pregled',
  'gamut.userOverview.unfinished-forms.detail.title': 'Nedovršeni obrasci',
  'gamut.userOverview.waiting-forms.detail.title': 'Obrasci koji čekaju na odluku',
  'gamut.userOverview.decided-forms.detail.title': 'Obrasci sa odlukom',
  'gamut.userOverview.inbox.detail.title': 'Dolazne poruke',
  'gamut.userOverview.bookings.detail.title': 'Kalendarske rezervacije',
  'gamut.userOverview.welcome.desc': 'Odavde je moguće pretraživati i prijaviti se za naše usluge, pregledati status prijava, slati poruke i datoteke, te rezervisati termine.',
  'gamut.feedback.table.sorted.desc': 'Sortirano opadajuće',
  'gamut.feedback.table.sorted.asc': 'Sortirano rastuće',
  'gamut.feedback.table.topic': 'Tema',
  'gamut.feedback.table.subtopic': 'Podtema',
  'gamut.feedback.table.updatedOnDate': 'Datum',
  'gamut.feedback.table.title': 'Povratna informacija',
  'gamut.feedback.table.topicTitle': 'Naziv',
  'gamut.feedback.table.nodata': 'Nema podataka',
  'gamut.feedback.vote.title': 'Da li je odgovor bio od pomoći?',
  'gamut.feedback.vote.notHelpful': 'Ne, nije bio od pomoći',
  'gamut.feedback.vote.yesHelpful': 'Da, bio je od pomoći',
  'gamut.feedback.vote.loginReq': 'Za ocjenjivanje povratne informacije potrebno je biti prijavljen',
  'gamut.feedback.updatedOnDate': 'Ažuriran datum',
  'gamut.feedback.feedbackViewerTitle': 'Povratna informacija klijenta',
  'gamut.feedback.feedbackViewerSubTitle': 'Odgovor organizacije',
  'dialob.review.title': 'Pregled obrasca',
  'dialob.review.button.close': 'Zatvori'
}