export const en = {
  'booleanValue.true': 'Yes',
  'booleanValue.false': 'No',
  'cust.inbox.message.sender-name.org-user': 'Info desk',
  'cust.phone': 'Phone: 123 456 7890',
  'cust.email': 'info@lifeDigital.com',
  'header.userIdentity.label': 'You are logged in as',
  'document.title': 'DigiExpress',
  'footer.column2.title': 'DigiExpress',
  'footer.column2.subtitle': 'Open source platform for digitalisation services',
  'footer.column3.title': 'Quick links',
  'footer.column3.link.acessibility': 'Accessibility statement',
  'footer.column3.link.dataProtection': 'Data protection',
  'footer.column3.link.feedback': 'Feedback and development ideas',
  'footer.column3.link.siteInfo': 'Information about the site',
  'footer.column3.link.newsletter': 'Subscribe to the newsletter',
  'footer.column4.title': 'DigiExpress info',
  'footer.column4.email': 'Email: info@digiExpress.io',
  'footer.column4.phone': 'Phone: 123 456 7890',
  'footer.column4.address': 'Visiting address: 1234 Any Street MyTown',
  'footer.column4.postalCode': 'Postal code: 1234',
  'gamut.forms': 'Forms',
  'gamut.new-messages': 'New messages',
  'gamut.services': 'Services',
  'gamut.bookings': 'Calendar reservations',
  'gamut.noValueIndicator': '-',
  'gamut.noValueIndicatorColon': '-',
  'gamut.textSeparatorColon': ':',
  'gamut.loading': 'Your content is on the way',
  'gamut.public.servicesHome': 'Services home',
  'gamut.public.forms.summary.button.backToServicesHome': 'Back to Services Home',
  'gamut.buttons.login': 'Log in',
  'gamut.buttons.logout': 'Log out',
  'gamut.buttons.search': 'Search',
  'gamut.buttons.cancel': 'Cancel',
  'gamut.buttons.select': 'Select',
  'gamut.buttons.close': 'Close',
  'gamut.buttons.reply': 'Reply',
  'gamut.buttons.serviceSelect': 'Our services',
  'gamut.buttons.attachment.add': 'Add attachment',
  'gamut.buttons.sort-last-modified.offers': 'Sort by last modified',
  'gamut.locale.en': 'English',
  'gamut.locale.fi': 'Finnish',
  'gamut.locale.sv': 'Swedish',
  'gamut.locale.my': 'Malay',
  'gamut.locale.bs': 'Bosnian',
  'gamut.search.placeholder': 'Search our services',
  'gamut.search.popover.title': 'Search our site',
  'gamut.search.popover.input.placeholder': 'What are you looking for?',
  'gamut.search.popover.allForms': 'All forms',
  'gamut.search.popover.allPhones': 'All phone numbers',
  'gamut.search.popover.allLinks': 'All links',
  'gamut.search.popover.allServices': 'All services',
  'gamut.search.results.allResults': 'All results',
  'gamut.search.results.noResults': 'No results',
  'gamut.search.results.serviceLinks': 'Services',
  'gamut.search.results.formLinks': 'Forms',
  'gamut.search.results.phoneLinks': 'Phones',
  'gamut.search.results.internalExternalLinks': 'Links',
  'gamut.search.results.internalLinks': 'Links',
  'gamut.search.results.externalLinks': 'External links',
  'gamut.article.pagelinks.forms.title': 'Forms',
  'gamut.article.pagelinks.otherlinks.title': 'Links',
  'gamut.forms.formName': 'Name',
  'gamut.forms.taskRefId': 'Reference Id',
  'gamut.forms.started': 'Started',
  'gamut.forms.attachments': 'Attachments',
  'gamut.forms.status': 'Status',
  'gamut.forms.selectionUndefined': 'Select',
  'gamut.forms.status.OPEN': 'In progress',
  'gamut.forms.status.NEW': 'Processing starts soon',
  'gamut.forms.status.COMPLETED': 'Completed',
  'gamut.forms.status.REJECTED': 'Rejected',
  'gamut.forms.status.DELEGATED': 'Completed',
  'gamut.forms.status.TRANSFERRED': 'In progress',
  'gamut.forms.status.WAITING': 'In progress',
  'gamut.forms.lastModified': 'Last modified',
  'gamut.forms.files': 'Files',
  'gamut.forms.messages': 'Messages',
  'gamut.forms.page.subtitle': 'Next:{nextPageTitle}',
  'gamut.forms.page.subtitle.complete': 'Next: Complete',
  'gamut.forms.page.stepper': '{start} of {end}',
  'gamut.forms.page.selection.key': 'Step {stepNumber} out of {totalSteps}',
  'gamut.forms.page.next': 'Next',
  'gamut.forms.page.previous': 'Previous',
  'gamut.forms.page.complete': 'Complete',
  'gamut.forms.page.cancel': 'Cancel',
  'gamut.forms.filling.welcome': 'Welcome!',
  'gamut.forms.filling.must_be_authenticated': 'You must be logged in to fill this form',
  'gamut.forms.filling.authenticated_and_welcome': 'Hello {userName}!',
  'gamut.forms.filling.proceed_to_form': 'Please click below to start the form',
  'gamut.forms.filling.proceed_to_form_anonUser': 'By selecting Continue with form you will begin filling out the form. If you want a response select Cancel and then log in to the portal. Restart your form after logging in.',
  'gamut.forms.filling.anonUser_and_welcome': 'Hello!',
  'gamut.forms.filling.start': 'You are about to start this form',
  'gamut.forms.filling.login-then-start.button': 'Log in now',
  'gamut.forms.filling.start.info1': 'Your form progress is saved automatically as you go',
  'gamut.forms.filling.start.button': 'Continue to form',
  'gamut.forms.filling.cancel.button': 'Cancel',
  'gamut.forms.filling.summary': 'You have completed the form',
  'gamut.forms.filling.summary.thank-you': 'Thank you!',
  'gamut.forms.filling.summary.info1': 'Our staff has been notified of your request and will begin processing soon.',
  'gamut.forms.filling.summary.info2': 'Be sure to check My Overview regularly for',
  'gamut.forms.filling.summary.info3': 'Case status updates',
  'gamut.forms.filling.summary.info4': 'New messages from our staff regarding your request',
  'gamut.forms.filling.summary.info5': 'New files we have sent to you or requested from you',
  'gamut.forms.filling.summary.info6': 'Still have questions? Contact us by phone at xxxx-xxxx with questions',
  'gamut.forms.filling.representativeNotAuthorized': 'Sorry, you have not been authorised to fill this form. Please contact our office for questions.',
  'gamut.forms.summary.button.back-to-overview': 'Back to My Overview',
  'gamut.forms.answer.date.placeholder.day': 'dd',
  'gamut.forms.answer.date.placeholder.month': 'mm',
  'gamut.forms.answer.date.placeholder.year': 'yyyy',
  'gamut.forms.answer.date.placeholder.hour': 'hh',
  'gamut.forms.answer.date.placeholder.minute': 'mm',
  'gamut.forms.answer.boolean.yes': 'Yes',
  'gamut.forms.answer.boolean.no': 'No',
  'gamut.forms.unfinished.none': 'You do not have any unfinished forms',
  'gamut.forms.unfinished.title': 'Unfinished forms',
  'gamut.forms.unfinished.subtitle': 'Please select a form to continue filling or cancel',
  'gamut.forms.awaitingDecision.title': 'Cases under review',
  'gamut.forms.awaitingDecision.subtitle': 'Cases whose processing has begun',
  'gamut.forms.withDecision.title': 'Cases are closed',
  'gamut.forms.withDecision.subtitle': 'Case processing is complete and finalised',
  'gamut.offers.deleteForm.title': 'Delete unfinished form',
  'gamut.offers.deleteForm.content': 'Are you sure you want to delete this form? You can not undo this action.',
  'gamut.offers.deleteForm.cancelButton': 'No keep this form',
  'gamut.offers.deleteForm.deleteButton': 'Yes delete this form',
  'gamut.inbox.title': 'Inbox',
  'gamut.inbox.subtitle': 'Messages and files related to your cases',
  'gamut.inbox.messages.title': 'Messages',
  'gamut.inbox.subjectAttachment.title': 'Attachments',
  'gamut.inbox.subjectAttachmentAssignedNotCompleted.title': 'Forms assigned to me but not yet completed',
  'gamut.inbox.newMessage.placeholder': 'Please write your message',
  'gamut.inbox.newMessage.replyingTo': 'Replying to',
  'gamut.inbox.newMessage.sendNew': 'Send a new message',
  'gamut.inbox.newMessage.replyingTo.subject': 'Subject',
  'gamut.inbox.newMessage.notAllowed1': 'The messaging function related to this case has not been activated yet.',
  'gamut.inbox.newMessage.notAllowed2': 'It will be activated as soon as your case is opened.',
  'gamut.inbox.newMessage.notAllowed.questions': 'Please contact us by phone or email with further questions.',
  'gamut.inbox.noMessages': 'No messages',
  'gamut.inbox.newMessageFrom': 'New message from',
  'gamut.subjectMessage.title': 'Messages regarding {subject}',
  'gamut.bookings.title': 'Calendar reservations',
  'gamut.bookings.subtitle': 'Manage your existing appointments and reservations here',
  'gamut.bookings.serviceName': 'Name of service',
  'gamut.bookings.bookingDateTime': 'Scheduled date and time',
  'gamut.bookings.deleteBooking.title': 'Cancel calendar reservation',
  'gamut.bookings.deleteBooking.content': 'Are you sure you want to cancel your reservation? You can not undo this action.',
  'gamut.bookings.deleteBooking.cancelButton': 'No keep my reservation',
  'gamut.bookings.deleteBooking.deleteButton': 'Yes cancel this reservation',
  'gamut.userOverview.services.detail.title': 'Find services and start forms',
  'gamut.userOverview.buttons.logout-representative': 'Log out as representative',
  'gamut.userOverview.buttons.login-representative': 'Log in as representative',
  'gamut.userOverview.buttons.logout': 'Log out',
  'gamut.userOverview.buttons.logout-company': 'Log out as company',
  'gamut.userOverview.buttons.login-company': 'Log in as company',
  'gamut.userOverview.buttons.user-overview': 'User overview home',
  'gamut.userOverview.buttons.services': 'Find services and start forms',
  'gamut.userOverview.buttons.requests-in-progress': 'Unfinished forms',
  'gamut.userOverview.buttons.awaiting-decision': 'Cases pending',
  'gamut.userOverview.buttons.with-decision': 'Closed cases',
  'gamut.userOverview.buttons.inbox': 'Inbox',
  'gamut.userOverview.buttons.bookings': 'Calendar reservations',
  'gamut.userOverview.home': 'User overview home',
  'gamut.userOverview.welcome.title': 'Welcome to my Overview',
  'gamut.userOverview.unfinished-forms.detail.title': 'Unfinished forms',
  'gamut.userOverview.waiting-forms.detail.title': 'Forms awaiting decision',
  'gamut.userOverview.decided-forms.detail.title': 'Forms with final decision',
  'gamut.userOverview.inbox.detail.title': 'Inbox',
  'gamut.userOverview.bookings.detail.title': 'Calendar bookings',
  'gamut.userOverview.welcome.desc': 'From here you can search and apply for our services view the status of your applications send messages and files and book appointments with us',
  'gamut.feedback.table.sorted.desc': 'Sorted descending',
  'gamut.feedback.table.sorted.asc': 'Sorted ascending',
  'gamut.feedback.table.topic': 'Topic',
  'gamut.feedback.table.subtopic': 'Sub topic',
  'gamut.feedback.table.updatedOnDate': 'Date',
  'gamut.feedback.table.title': 'Feedback',
  'gamut.feedback.table.topicTitle': 'Title',
  'gamut.feedback.table.nodata': 'No data',
  'gamut.feedback.vote.title': 'Was this answer helpful?',
  'gamut.feedback.vote.notHelpful': 'No this was not helpful',
  'gamut.feedback.vote.yesHelpful': 'Yes this was helpful',
  'gamut.feedback.vote.loginReq': 'You must be logged in to rate feedback',
  'gamut.feedback.updatedOnDate': 'Updated',
  'gamut.feedback.feedbackViewerTitle': 'Customer feedback',
  'gamut.feedback.feedbackViewerSubTitle': 'Organisation reply',
  'dialob.review.title': 'Form review',
  'dialob.review.button.close': 'Close',
  'gamut.cockpit.selection.dialog': 'Select Cockpit'
}