export const fi = {
  'booleanValue.true': 'Kyllä',
  'booleanValue.false': 'Ei',
  'cust.inbox.message.sender-name.org-user': 'Info',
  'cust.phone': 'Puhelin 123 456 7890',
  'cust.email': 'info@lifeDigital.com',
  'header.userIdentity.label': 'Kirjauduttu käyttäjänä',
  'document.title': 'DigiExpress',
  'footer.column2.title': 'DigiExpress',
  'footer.column2.subtitle': 'Avoimen lähdekoodin alusta palvelujen digitalisointiin',
  'footer.column3.title': 'Pikalinkkejä',
  'footer.column3.link.acessibility': 'Saavutettavuus seloste',
  'footer.column3.link.dataProtection': 'Tietosuoja',
  'footer.column3.link.feedback': 'Palautteet',
  'footer.column3.link.siteInfo': 'Lisätieto tästä sivustosta',
  'footer.column3.link.newsletter': 'Tilaa uutiskirje',
  'footer.column4.title': 'DigiExpress info',
  'footer.column4.email': 'Sähköposti: info@digiExpress.io',
  'footer.column4.phone': 'Phone: 123 456 7890',
  'footer.column4.address': 'Käyntiosoite: 1234 Suomentie 4, Suomi',
  'footer.column4.postalCode': 'Postinumero: 1234',
  'gamut.forms': 'Lomake',
  'gamut.new-messages': 'Uusi viesti',
  'gamut.services': 'Palvelut',
  'gamut.bookings': 'Kalenteri varaukset',
  'gamut.noValueIndicator': '-',
  'gamut.noValueIndicatorColon': '-',
  'gamut.textSeparatorColon': ':',
  'gamut.loading': 'Sisältöä ladataan',
  'gamut.public.servicesHome': 'Palvelut pääsivu',
  'gamut.public.forms.summary.button.backToServicesHome': 'Takaisin Palvelut pääsivulle',
  'gamut.buttons.login': 'Kirjaudu sisään',
  'gamut.buttons.logout': 'Kirjaudu ulos',
  'gamut.buttons.search': 'Hae',
  'gamut.buttons.cancel': 'Peruuta',
  'gamut.buttons.select': 'Valitse',
  'gamut.buttons.close': 'Sulje',
  'gamut.buttons.reply': 'Vastaa',
  'gamut.buttons.serviceSelect': 'Palvelumme',
  'gamut.buttons.attachment.add': 'Lisää liite',
  'gamut.buttons.sort-last-modified.offers': 'Järjestä viimeksi muokattu mukaan',
  'gamut.locale.en': 'Englanti',
  'gamut.locale.fi': 'Suomi',
  'gamut.locale.sv': 'Ruotsi',
  'gamut.locale.my': 'Malaiji',
  'gamut.locale.bs': 'Bosnia',
  'gamut.search.placeholder': 'Hae palvelua',
  'gamut.search.popover.title': 'Hae sivustolta',
  'gamut.search.popover.input.placeholder': 'Mitä etsi',
  'gamut.search.popover.allForms': 'Kaikki lomakkeet',
  'gamut.search.popover.allPhones': 'Kaikki puhelin numerot',
  'gamut.search.popover.allLinks': 'Kaikki linkit',
  'gamut.search.popover.allServices': 'Kaikki palvelut',
  'gamut.search.results.allResults': 'Kaikki hakutulokset',
  'gamut.search.results.noResults': 'Ei hakutuloksia',
  'gamut.search.results.serviceLinks': 'Palvelut',
  'gamut.search.results.formLinks': 'Lomakkeet',
  'gamut.search.results.phoneLinks': 'Puhelin',
  'gamut.search.results.internalExternalLinks': 'Linkit',
  'gamut.search.results.internalLinks': 'Linkit',
  'gamut.search.results.externalLinks': 'Ulkoiset linkit',
  'gamut.article.pagelinks.forms.title': 'Lomakkeet',
  'gamut.article.pagelinks.otherlinks.title': 'Linkit',
  'gamut.forms.formName': 'Lomakkeen nimi',
  'gamut.forms.taskRefId': 'Viitetunnus',
  'gamut.forms.started': 'Aloitettu',
  'gamut.forms.attachments': 'Liitteet',
  'gamut.forms.status': 'Tila',
  'gamut.forms.selectionUndefined': 'Valitse',
  'gamut.forms.status.OPEN': 'Käsittelyssä',
  'gamut.forms.status.NEW': 'Valmis käsittelyyn',
  'gamut.forms.status.COMPLETED': 'Käsitelty',
  'gamut.forms.status.REJECTED': 'Poistettu',
  'gamut.forms.status.DELEGATED': 'Käsitelty',
  'gamut.forms.status.TRANSFERRED': 'Käsittelyssä',
  'gamut.forms.status.WAITING': 'Käsittelyssä',
  'gamut.forms.lastModified': 'Viimeksi muutettu',
  'gamut.forms.files': 'Liitteet',
  'gamut.forms.messages': 'Viestit',
  'gamut.forms.page.subtitle': 'Seuraava:{nextPageTitle}',
  'gamut.forms.page.subtitle.complete': 'Seuraava: Valmis',
  'gamut.forms.page.stepper': '{start} sivu {end}',
  'gamut.forms.page.selection.key': 'Vaihe {stepNumber} vaiheista {totalSteps}',
  'gamut.forms.page.next': 'Seuraava',
  'gamut.forms.page.previous': 'Edellinen',
  'gamut.forms.page.complete': 'Valmis',
  'gamut.forms.page.cancel': 'Peruuta',
  'gamut.forms.filling.welcome': 'Tervetuloa',
  'gamut.forms.filling.must_be_authenticated': 'Sinun on kirjauduttava sisään täyttääksesi tämän lomakkeen',
  'gamut.forms.filling.authenticated_and_welcome': 'Moi {userName}!',
  'gamut.forms.filling.proceed_to_form': 'Valitsemalla tästä aloitat lomakkeen täyttämisen',
  'gamut.forms.filling.proceed_to_form_anonUser': 'Valitsemalla Jatka lomakkeella aloitat lomakkeen täyttämisen. Jos haluat siihen vastauksen valitse Peruuta ja valitse Kirjaudu sisään ja valitse tämä lomake sieltä.',
  'gamut.forms.filling.anonUser_and_welcome': 'Terve!',
  'gamut.forms.filling.start': 'Olet aloittamassa lomaketta',
  'gamut.forms.filling.login-then-start.button': 'Kirjaudu sisään',
  'gamut.forms.filling.start.info1': 'Lomake tallentuu automaattisesti sitä täytettäessä',
  'gamut.forms.filling.start.button': 'Jatka lomakkeella',
  'gamut.forms.filling.cancel.button': 'Peruuta',
  'gamut.forms.filling.summary': 'Olemme vastaanottaneet lomakkeesi',
  'gamut.forms.filling.summary.thank-you': 'Kiitos!',
  'gamut.forms.filling.summary.info1': 'Saat ilmoituksen kun asiontipyyntösi on otettu käsittelyyn',
  'gamut.forms.filling.summary.info2': 'Muistahan välillä tarkistaa Minun asiat osiota',
  'gamut.forms.filling.summary.info3': 'Asian käsittelyn tila',
  'gamut.forms.filling.summary.info4': 'Viereillä oleviin asioihin liittyvä uudet viestit',
  'gamut.forms.filling.summary.info5': 'Uudet tiedostot, jotka olemme toimittaneet sinulle tai pyytäneet sinulta',
  'gamut.forms.filling.summary.info6': 'Jäikö kysyttävää? Ota yhteyttä puhelimitse numeroon xxxx-xxxx kysymyksiä varten.',
  'gamut.forms.filling.representativeNotAuthorized': 'Ei valtuutusta täyttää tätä lomaketta. Ota yhteyttä.',
  'gamut.forms.summary.button.back-to-overview': 'Takaisin Minun Asiat sivulle',
  'gamut.forms.answer.date.placeholder.day': 'pp',
  'gamut.forms.answer.date.placeholder.month': 'kk',
  'gamut.forms.answer.date.placeholder.year': 'vvvv',
  'gamut.forms.answer.date.placeholder.hour': 'tt',
  'gamut.forms.answer.date.placeholder.minute': 'mm',
  'gamut.forms.answer.boolean.yes': 'Kyllä',
  'gamut.forms.answer.boolean.no': 'Ei',
  'gamut.forms.unfinished.none': 'Sinulla ei ole keskeneräisiä lomakkeita',
  'gamut.forms.unfinished.title': 'Keskeneräiset lomakkeet',
  'gamut.forms.unfinished.subtitle': 'Valitse lomake jatkaaksesi sen täyttämistä',
  'gamut.forms.awaitingDecision.title': 'Asiat, jotka odottavat käsittelyä',
  'gamut.forms.awaitingDecision.subtitle': 'Asiat, jotka on otettu käsittelyyn',
  'gamut.forms.withDecision.title': 'Asiat, jotka on käsitelty',
  'gamut.forms.withDecision.subtitle': 'Asiointitapahtuma on valmis',
  'gamut.offers.deleteForm.title': 'Poista keskeneräiset lomakkeet',
  'gamut.offers.deleteForm.content': 'Haluatko varmasti poistaa tämän lomakkeen? Et voi kumota tätä toimintoa.',
  'gamut.offers.deleteForm.cancelButton': 'Älä poista tätä lomaketta',
  'gamut.offers.deleteForm.deleteButton': 'Kyllä haluan poistaa tämän lomakkeen',
  'gamut.inbox.title': 'Saapuneet',
  'gamut.inbox.subtitle': 'Viestit ja liitteet liittyen asiontitapahtumiin',
  'gamut.inbox.messages.title': 'Viestit',
  'gamut.inbox.subjectAttachment.title': 'Liitteet',
  'gamut.inbox.subjectAttachmentAssignedNotCompleted.title': 'Minulle osoitetut lomakkeet',
  'gamut.inbox.newMessage.placeholder': 'Kirjoita viestisi',
  'gamut.inbox.newMessage.replyingTo': 'Vastaa viestiin',
  'gamut.inbox.newMessage.sendNew': 'Lähetä uusi viesti',
  'gamut.inbox.newMessage.replyingTo.subject': 'Aihe',
  'gamut.inbox.newMessage.notAllowed1': 'Tähän asiontiin liittyvä viestitoiminto ei ole vielä aktivoitu.',
  'gamut.inbox.newMessage.notAllowed2': 'Se aktivoituu heti kun asiasi otetaan käsittelyyn.',
  'gamut.inbox.newMessage.notAllowed.questions': 'Ota meihin yhteyttä puhelimitse tai sähköpostitse, jos sinulla on lisäkysymyksiä.',
  'gamut.inbox.noMessages': 'Ei viestejä',
  'gamut.inbox.newMessageFrom': 'Uusi viesti',
  'gamut.subjectMessage.title': 'Viestit koskien {subject}',
  'gamut.bookings.title': 'Kalenterivaraukset',
  'gamut.bookings.subtitle': 'Hallinnoi kalenterivarauksiasi',
  'gamut.bookings.serviceName': 'Palvelun nimi',
  'gamut.bookings.bookingDateTime': 'Varaa aika',
  'gamut.bookings.deleteBooking.title': 'Peruuta aika',
  'gamut.bookings.deleteBooking.content': 'Haluatko varmasti peruuttaa varauksesi? Et voi kumota tätä toimintoa.',
  'gamut.bookings.deleteBooking.cancelButton': 'Ei haluan pitää varaukseni',
  'gamut.bookings.deleteBooking.deleteButton': 'Kyllä haluan peruuttaa varauksen',
  'gamut.userOverview.services.detail.title': 'Etsi palveluja ja lomakkeita',
  'gamut.userOverview.buttons.logout-representative': 'Kirjaudu ulos edustajana',
  'gamut.userOverview.buttons.login-representative': 'Kirjaudu sisään edustajana',
  'gamut.userOverview.buttons.logout': 'Kirjaudu ulos edustajana',
  'gamut.userOverview.buttons.logout-company': 'Kirjaudu ulos yrityksen edustajana',
  'gamut.userOverview.buttons.login-company': 'Kirjaudu sisään yrityksen edustajana',
  'gamut.userOverview.buttons.user-overview': 'Käyttäjän tiedot',
  'gamut.userOverview.buttons.services': 'Etsi palveluja ja lomakkeita',
  'gamut.userOverview.buttons.requests-in-progress': 'Keskeneräiset lomakkeet',
  'gamut.userOverview.buttons.awaiting-decision': 'Asiat jotka odottavat käsittelyä',
  'gamut.userOverview.buttons.with-decision': 'Asiat jotka on käsitelty',
  'gamut.userOverview.buttons.inbox': 'Viestit',
  'gamut.userOverview.buttons.bookings': 'Kalenterivaraukset',
  'gamut.userOverview.home': 'Käyttäjän tiedot',
  'gamut.userOverview.welcome.title': 'Tervetuloa minun tietoihin',
  'gamut.userOverview.unfinished-forms.detail.title': 'Keskeneräiset lomakkeet',
  'gamut.userOverview.waiting-forms.detail.title': 'Asiat, jotka odottavat käsittelyä',
  'gamut.userOverview.decided-forms.detail.title': 'Asiat, jotka on käsitelty',
  'gamut.userOverview.inbox.detail.title': 'Viestit',
  'gamut.userOverview.bookings.detail.title': 'Kalenteri varaukseni',
  'gamut.userOverview.welcome.desc': 'Täältä voit etsiä ja hakea palveluitamme, tarkastella hakemustesi tilaa, lähettää viestejä ja tiedostoja sekä varata aikoja kanssamme.',
  'gamut.feedback.table.sorted.desc': 'Lajiteltu laskevassa järjestyksessä',
  'gamut.feedback.table.sorted.asc': 'Lajiteltu nousevassa järjestyksessä',
  'gamut.feedback.table.topic': 'Aihe',
  'gamut.feedback.table.subtopic': 'Aliaihe',
  'gamut.feedback.table.updatedOnDate': 'Päivämäärä',
  'gamut.feedback.table.title': 'Palaute',
  'gamut.feedback.table.topicTitle': 'Otsikko',
  'gamut.feedback.table.nodata': 'Ei tietoja',
  'gamut.feedback.vote.title': 'Oliko vastauksesta hyötyä?',
  'gamut.feedback.vote.notHelpful': 'Ei vastauksesta ei ollut apua',
  'gamut.feedback.vote.yesHelpful': 'Kyllä vastauksesta oli apua',
  'gamut.feedback.vote.loginReq': 'Sinun on kirjauduttava sisään arvioidaksesi palautetta',
  'gamut.feedback.updatedOnDate': 'Päivitetty',
  'gamut.feedback.feedbackViewerTitle': 'Asiakas palaute',
  'gamut.feedback.feedbackViewerSubTitle': 'Organisaation palaute',
  'dialob.review.title': 'Lomakkeen esikatselu',
  'dialob.review.button.close': 'Sulje',
  'gamut.cockpit.selection.dialog': 'Select Cockpit'
}