export const sv = {
  'booleanValue.true': 'Ja',
  'booleanValue.false': 'Inga',
  'cust.inbox.message.sender-name.org-user': 'Infodisk',
  'cust.phone': 'Telefon: 123 456 7890',
  'cust.email': 'info@lifeDigital.com',
  'header.userIdentity.label': 'Inloggad som',
  'document.title': 'DigiExpress',
  'footer.column2.title': 'DigiExpress',
  'footer.column2.subtitle': 'Öppen källkodsplattform för digitaliseringstjänster',
  'footer.column3.title': 'Snabblänkar',
  'footer.column3.link.acessibility': 'Tillgänglighetsförklaring',
  'footer.column3.link.dataProtection': 'Dataskydd',
  'footer.column3.link.feedback': 'Feedback och utvecklingsidéer',
  'footer.column3.link.siteInfo': 'Information om webbplatsen',
  'footer.column3.link.newsletter': 'Prenumerera på nyhetsbrevet',
  'footer.column4.title': 'DigiExpress info',
  'footer.column4.email': 'E-post: info@digiExpress.io',
  'footer.column4.phone': 'Telefon: 123 456 7890',
  'footer.column4.address': 'Besöksadress: 1234 Any Street MyTown',
  'footer.column4.postalCode': 'Postnummer: 1234',
  'gamut.forms': 'Formulär',
  'gamut.new-messages': 'Nya meddelanden',
  'gamut.services': 'Tjänster',
  'gamut.bookings': 'Kalenderreservationer',
  'gamut.noValueIndicator': '-',
  'gamut.noValueIndicatorColon': '-',
  'gamut.textSeparatorColon': ':',
  'gamut.loading': 'Ditt innehåll är på väg',
  'gamut.public.servicesHome': 'Tjänster hem',
  'gamut.public.forms.summary.button.backToServicesHome': 'Tillbaka till Tjänster Hem',
  'gamut.buttons.login': 'Logga in',
  'gamut.buttons.logout': 'Logga ut',
  'gamut.buttons.search': 'Söka',
  'gamut.buttons.cancel': 'Avboka',
  'gamut.buttons.select': 'Välja',
  'gamut.buttons.close': 'Nära',
  'gamut.buttons.reply': 'Svar',
  'gamut.buttons.serviceSelect': 'Våra tjänster',
  'gamut.buttons.attachment.add': 'Lägg till bilaga',
  'gamut.buttons.sort-last-modified.offers': 'Sortera efter senaste modifiering',
  'gamut.locale.en': 'Engelska',
  'gamut.locale.fi': 'Finska',
  'gamut.locale.sv': 'Svenska',
  'gamut.locale.my': 'Malajisk',
  'gamut.locale.bs': 'Bosnian',
  'gamut.search.placeholder': 'Sök i våra tjänster',
  'gamut.search.popover.title': 'Sök på vår sida',
  'gamut.search.popover.input.placeholder': 'Vad letar du efter?',
  'gamut.search.popover.allForms': 'Alla former',
  'gamut.search.popover.allPhones': 'Alla telefonnummer',
  'gamut.search.popover.allLinks': 'Alla länkar',
  'gamut.search.popover.allServices': 'Alla tjänster',
  'gamut.search.results.allResults': 'Alla sökresultat',
  'gamut.search.results.noResults': 'Inga sökträffar',
  'gamut.search.results.serviceLinks': 'Tjänster',
  'gamut.search.results.formLinks': 'Formulär',
  'gamut.search.results.phoneLinks': 'Telefon',
  'gamut.search.results.internalExternalLinks': 'Hyperlänkar',
  'gamut.search.results.internalLinks': 'Hyperlänkar',
  'gamut.search.results.externalLinks': 'Externa länkar',
  'gamut.article.pagelinks.forms.title': 'Formulär',
  'gamut.article.pagelinks.otherlinks.title': 'Länkar',
  'gamut.forms.formName': 'Namn',
  'gamut.forms.taskRefId': 'Referens ID',
  'gamut.forms.started': 'Startade',
  'gamut.forms.status': 'Status',
  'gamut.forms.status.OPEN': 'Pågår',
  'gamut.forms.status.NEW': 'Bearbetningen startar snart',
  'gamut.forms.status.COMPLETED': 'Avslutad',
  'gamut.forms.status.REJECTED': 'Avvisad',
  'gamut.forms.status.DELEGATED': 'Avslutad',
  'gamut.forms.status.TRANSFERRED': 'Pågår',
  'gamut.forms.status.WAITING': 'Pågår',
  'gamut.forms.lastModified': 'Senast ändrad',
  'gamut.forms.files': 'Filer',
  'gamut.forms.messages': 'Meddelanden',
  'gamut.forms.page.subtitle': 'Nästa:{nextPageTitle}',
  'gamut.forms.page.subtitle.complete': 'Nästa: Komplett',
  'gamut.forms.page.stepper': '{start} av {slut}',
  'gamut.forms.page.selection.key': 'Steg {stepNumber} av {totalSteps}',
  'gamut.forms.page.next': 'Nästa',
  'gamut.forms.page.complete': 'Komplett',
  'gamut.forms.page.cancel': 'Avboka',
  'gamut.forms.filling.welcome': 'Välkomna!',
  'gamut.forms.filling.must_be_authenticated': 'Du måste vara inloggad för att fylla i detta formulär',
  'gamut.forms.filling.authenticated_and_welcome': 'Hei {userName}!',
  'gamut.forms.filling.proceed_to_form': 'Klicka nedan för att starta formuläret',
  'gamut.forms.filling.proceed_to_form_anonUser': 'Genom att välja Fortsätt med formulär börjar du fylla i formuläret. Om du vill ha svar väljer du Avbryt och väljer Logga in och väljer det här formuläret därifrån.',
  'gamut.forms.filling.anonUser_and_welcome': 'Hej!',
  'gamut.forms.filling.start': 'Du är på väg att starta detta formulär',
  'gamut.forms.filling.login-then-start.button': 'Logga in nu',
  'gamut.forms.filling.start.info1': 'Dina formulärförlopp sparas automatiskt när du går',
  'gamut.forms.filling.start.button': 'Fortsätt att bilda',
  'gamut.forms.filling.cancel.button': 'Avboka',
  'gamut.forms.filling.summary': 'Du har fyllt i formuläret',
  'gamut.forms.filling.summary.thank-you': 'Tack!',
  'gamut.forms.filling.summary.info1': 'Vår personal har underrättats om din förfrågan och kommer att börja behandla snart.',
  'gamut.forms.filling.summary.info2': 'Se till att kontrollera Min översikt regelbundet för',
  'gamut.forms.filling.summary.info3': 'Statusuppdateringar för formulärbearbetning',
  'gamut.forms.filling.summary.info4': 'Nya meddelanden från vår personal angående din förfrågan',
  'gamut.forms.filling.summary.info5': 'Nya filer som vi har skickat till dig eller begärt av dig',
  'gamut.forms.filling.summary.info6': 'Har du fortfarande frågor? Kontakta oss per telefon på xxxx-xxxx med frågor',
  'gamut.forms.filling.representativeNotAuthorized': 'Ej behörig att fylla i detta formulär. Kontakta vårt kontor.',
  'gamut.forms.summary.button.back-to-overview': 'Tillbaka till Min översikt',
  'gamut.forms.answer.date.placeholder.day': 'dd',
  'gamut.forms.answer.date.placeholder.month': 'mm',
  'gamut.forms.answer.date.placeholder.year': 'åååå',
  'gamut.forms.answer.date.placeholder.hour': 'hh',
  'gamut.forms.answer.date.placeholder.minute': 'mm',
  'gamut.forms.answer.boolean.yes': 'Ja',
  'gamut.forms.answer.boolean.no': 'Inga',
  'gamut.forms.unfinished.none': 'Du har inga oavslutade formulär',
  'gamut.forms.unfinished.title': 'Oavslutade former',
  'gamut.forms.unfinished.subtitle': 'Bearbetningen har inte startat - Välj ett formulär för att fortsätta fylla eller avbryta',
  'gamut.forms.awaitingDecision.title': 'Blanketter som väntar på beslut',
  'gamut.forms.awaitingDecision.subtitle': 'Behandlingen har påbörjats - Vår personal arbetar med din förfrågan',
  'gamut.forms.withDecision.title': 'Blanketter med slutligt beslut',
  'gamut.forms.withDecision.subtitle': 'Bearbetningen är klar och slutförd',
  'gamut.offers.deleteForm.title': 'Ta bort oavslutat formulär',
  'gamut.offers.deleteForm.content': 'Är du säker på att du vill ta bort det här formuläret? Du kan inte ångra den här åtgärden.',
  'gamut.offers.deleteForm.cancelButton': 'Nej, behåll detta formulär',
  'gamut.offers.deleteForm.deleteButton': 'Ja, ta bort detta formulär',
  'gamut.inbox.title': 'Inkorg',
  'gamut.inbox.subtitle': 'Meddelanden och filer relaterade till dina formulär',
  'gamut.inbox.messages.title': 'Meddelanden',
  'gamut.inbox.subjectAttachment.title': 'Bilagor',
  'gamut.inbox.newMessage.placeholder': 'Skriv ditt meddelande',
  'gamut.inbox.newMessage.replyingTo': 'Svarar på',
  'gamut.inbox.newMessage.sendNew': 'Skicka ett nytt meddelande',
  'gamut.inbox.newMessage.replyingTo.subject': 'Ämne',
  'gamut.inbox.newMessage.notAllowed1': 'Messages are not enabled.',
  'gamut.inbox.newMessage.notAllowed2': 'Vi ber om ursäkt för besväret.',
  'gamut.inbox.newMessage.notAllowed.questions': 'Kontakta oss gärna via telefon eller e-post med ytterligare frågor.',
  'gamut.inbox.noMessages': 'Inga meddelanden',
  'gamut.inbox.newMessageFrom': 'Ny meddelande från',
  'gamut.subjectMessage.title': 'Meddelanden om {ämne}',
  'gamut.bookings.title': 'Kalenderreservationer',
  'gamut.bookings.subtitle': 'Hantera dina befintliga möten och bokningar här',
  'gamut.bookings.serviceName': 'Tjänstens namn',
  'gamut.bookings.bookingDateTime': 'Schemalagt datum och tid',
  'gamut.bookings.deleteBooking.title': 'Avboka kalenderreservation',
  'gamut.bookings.deleteBooking.content': 'Är du säker på att du vill avboka din bokning? Du kan inte ångra den här åtgärden.',
  'gamut.bookings.deleteBooking.cancelButton': 'Nej, behåll min reservation',
  'gamut.bookings.deleteBooking.deleteButton': 'Ja avboka denna reservation',
  'gamut.userOverview.services.detail.title': 'Hitta tjänster och startformulär',
  'gamut.userOverview.buttons.logout-representative': 'Logga ut som representant',
  'gamut.userOverview.buttons.login-representative': 'Logga in som representant',
  'gamut.userOverview.buttons.logout': 'Logga ut',
  'gamut.userOverview.buttons.logout-company': 'Logga ut som företag',
  'gamut.userOverview.buttons.login-company': 'Logga in som företag',
  'gamut.userOverview.buttons.user-overview': 'Användaröversikt hem',
  'gamut.userOverview.buttons.services': 'Hitta tjänster och startformulär',
  'gamut.userOverview.buttons.requests-in-progress': 'Oavslutade former',
  'gamut.userOverview.buttons.awaiting-decision': 'Blanketter som väntar på beslut',
  'gamut.userOverview.buttons.with-decision': 'Blanketter med slutligt beslut',
  'gamut.userOverview.buttons.inbox': 'Inkorg',
  'gamut.userOverview.buttons.bookings': 'Kalenderreservationer',
  'gamut.userOverview.home': 'Användaröversikt hem',
  'gamut.userOverview.welcome.title': 'Välkommen till min översikt',
  'gamut.userOverview.unfinished-forms.detail.title': 'Oavslutade former',
  'gamut.userOverview.waiting-forms.detail.title': 'Blanketter som väntar på beslut',
  'gamut.userOverview.decided-forms.detail.title': 'Blanketter med slutligt beslut',
  'gamut.userOverview.inbox.detail.title': 'Inkorg',
  'gamut.userOverview.bookings.detail.title': 'Kalenderbokningar',
  'gamut.userOverview.welcome.desc': 'Härifrån kan du söka och ansöka om våra tjänster se status för dina applikationer skicka meddelanden och filer och boka möten med oss',
  'gamut.feedback.table.sorted.desc': 'Sorterat fallande',
  'gamut.feedback.table.sorted.asc': 'Sorterat stigande',
  'gamut.feedback.table.topic': 'Ämne',
  'gamut.feedback.table.subtopic': 'Underämne',
  'gamut.feedback.table.updatedOnDate': 'Datum',
  'gamut.feedback.table.title': 'Feed-back',
  'gamut.feedback.table.topicTitle': 'Titel',
  'gamut.feedback.table.nodata': 'Ingen data',
  'gamut.feedback.vote.title': 'Var detta svar till hjälp?',
  'gamut.feedback.vote.notHelpful': 'Nej, detta var inte till hjälp.',
  'gamut.feedback.vote.yesHelpful': 'Ja, detta var hjälpsamt.',
  'gamut.feedback.vote.loginReq': 'Du måste vara inloggad för att betygsätta feedback',
  'gamut.feedback.updatedOnDate': 'Uppdaterat datum',
  'gamut.feedback.feedbackViewerTitle': 'Kundrespons',
  'gamut.feedback.feedbackViewerSubTitle': 'Organisationens svar',
  'dialob.review.title': 'Formulärgranskning',
  'dialob.review.button.close': 'Stäng'
}