version: '3.1'

services:

  digiexpress-dev-db:
    image: postgres:14.7
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasks_db
    ports:
      - 5432:5432

  digiexpress-dev-app:
    image: docker.io/library/digiexpress-dev-app:1-snapshot
    restart: always
    environment:
      QUARKUS_DATASOURCE_PASSWORD: postgres
      QUARKUS_DATASOURCE_USERNAME: postgres
      TASKS_PROJECT_ID: "tasks-repo"
      TASKS_DB_REPOSITORYNAME: "tasks-repo"
      TASKS_DB_PG_PGPORT: 5432 
      TASKS_DB_PG_PGHOST: "digiexpress-dev-db"
      TASKS_DB_PG_PGDB: "tasks_db"
      TASKS_DB_PG_PGUSER: "postgres"
      TASKS_DB_PG_PGPASS: "postgres"
      TASKS_DB_PG_PGPOOLSIZE: 5
    ports:
      - 8080:8080
    links:
      - digiexpress-dev-db