version: '3.1'

services:

  stencil_db:
    image: postgres:13.9
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8091:8080
