services:
  postgresql:
    image: postgres:16
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_USER=eveli-app
      - TZ=Europe/Helsinki
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
      - ./db_data:/var/lib/postgresql/data