spring:

server:
  port: 8081
  use-forward-headers: true
  servlet:
    context-path: "/"
    session.timeout: 7200
  error:
    include-stacktrace: always
    

host: "http://localhost:${server.port}"

management:
  server:
    servlet.context-path: "/manage"
    add-application-context-header: false
      

# disable all configurations 
digiexpress.enabled: true

#
digiexpress.composer.ui.enabled: true
digiexpress.composer.ui.redirect: true
digiexpress.composer.ui.https: false 
digiexpress.composer.ui.oidc-path:  ''
digiexpress.composer.ui.status-path: ''
digiexpress.composer.ui.service-path: /q/digi

digiexpress.composer.service.enabled: true
digiexpress.composer.service.service-path: /q/digi/rest/api

# form releated db enabled, default path classpath*:assets/
digiexpress.db.inmemory.enabled: false
digiexpress.db.inmemory.path: classpath*:assets/

#form db config - local file storage
digiexpress.db.file.enabled: false
digiexpress.db.file.path: src/main/resources
digiexpress.db.file.email: asset.manager@resys.io

# form db config - postgresql storage
# - create test db via shell
#     psql -p 5432 -U postgres -h localhost
#     create database digiexpress encoding 'UTF8' lc_collate='en_US.UTF8' lc_ctype='en_US.UTF8' template template0;
#     revoke connect on database digiexpress from public;
#     create user digiexpress;
#     grant all privileges on database "digiexpress" to digiexpress;
#     \password digiexpress
#     password: example

digiexpress.db.pg.enabled: true
digiexpress.db.pg.autoCreate: true
digiexpress.db.pg.repositoryName: "digiexpress-repo-1" 
digiexpress.db.pg.branchSpecifier: "main"
digiexpress.db.pg.pgHost: "localhost"
digiexpress.db.pg.pgDb: "digiexpress"
digiexpress.db.pg.pgUser: "digiexpress"
digiexpress.db.pg.pgPass: "example"


