spring:
  config:
    import: "sm://"  
  jpa:
    showSql: false
    generateDdl: false
    hibernate:
      ddlAuto: "validate"
      autoQuoteKeyword: true
      connection:
        useUnicode: true
        characterEncoding: 'UTF-8'
        charSet: 'UTF-8'
  flyway:
    enabled: true
    locations: classpath:db/postgresql
    validate-on-migrate: true
  cloud:
    gcp:
      logging:
        enabled: true

management:
  server:
    servlet.context-path: "/manage"
    add-application-context-header: false
  endpoints:
    web:
      exposure:
        include: "health,mappings"

# Logging config
#logging.level.org.springframework.web: INFO
#logging.org.springframework.http: INFO
#logging.level.org.springframework.boot: INFO

logging.level.io.vertx.core.impl.btc.BlockedThreadChecker: OFF
logging.level.io.vertx.core.impl.BlockedThreadChecker: OFF


# DB config
spring.datasource.url: "jdbc:postgresql://localhost:5433/eveli-app"
spring.datasource.username: "eveli-app"
spring.datasource.password: "password123"

eveli.attachment-config.download-bucket:
eveli.task.adminsearch: true
eveli.assets.use-form-id: false

# dialob related config
eveli.dialob.enabled: true
eveli.dialob.service-url: http://localhost:9000
eveli.dialob.api-key:
  
# feedback  
eveli.feedback.enabled: true
eveli.feedback.forms: palautteet
eveli.feedback.category-main: mainList
eveli.feedback.category-sub: cityServiceGroup, preschoolEducationGroup, cityServiceMainList, constructionMainList, youthServiceMainList, exerciseMainList, schoolMainList, employmentImmigrationMainList, freeTimeCultureMainList, preschoolMainList, communicationMainList, cooperationMainList
eveli.feedback.question-title: feedBackTitle
eveli.feedback.question: feedBackTxt
eveli.feedback.username-allowed: publicAnswerAllowed

# jwt linked crm from security proxy
eveli.crm.enabled: false
eveli.crm.host: 
eveli.crm.service-path-company: gw/api/ypa/organizationRoles
eveli.crm.service-path-person: gw/api/hpa/authorizationList

# mq
eveli.mq.enabled: true
eveli.mq.app-id: task-app
eveli.mq.channel-name: main-channel-for-all

eveli.jwt.eveli-public-key-value: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAi4PobwPTnWPJWwjnND2j\naYZoF8i0xGVI0FZsIcQ1cF1qSSHJH1J2JfspDpY4dJwN8zGsS3el4kgI0XcOzLam\n3s9U/Ix70kxTXvEosydtsPeKEh8qKIoTszPyHETPe3OyfhTR8mFggn0+2B1xSbMd\nsnlPLai+Xdp+o4Yg5A4ApxRpF/nvu8LdpSGfw3z1un+D+nEX3joWzc55mloHWiDi\nj2TUuqrDVNUz5oUYJJPUAYHa23hGFhWP21tFaqYeFwO6CGC8LxL6tN5ERh2hvXms\nLdN4ATCa/LjQQqv4Rls93R7jrEuNHjjMX2EOI/rLXZ1jgkB5VOYeJ7qHMmTu2YLY\nfQIDAQAB\n-----END PUBLIC KEY-----\n"
eveli.jwt.eveli-issuer: https://frontdesk.digiexpress.io/gateway/issuer
eveli.jwt.gamut-public-key-value: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkb8vttXCPPraVCQBkFR/\nNIVP4PXnYS9Ik3KBX3Th684d3P1OdEnQ4EMU3gn+jnG5+qQSs+KpXBvwcCsyE1jx\ncIeSQ5GpuXC1BwhCTSM6RY78I2A+mcnt4h45a9ipPi6W9PHfk+PzYFrrp9jgFflZ\n6fyJt5Hfaz3yhnPb7Y/GE5zz9v+HgoCLDbu7xj98BOgt7rIZ27End90Q1iFyQpu1\nYbyyvGy/61hUv/rDeL7gsypyfvjL1n5a1mJ2A3VheXLyLJIleu4vNw8yejtXqp7S\nHc9EiCCf+ccEQnQgAAWLOvgYMaIvaXmuT/MszCjSpsQyqbGV5k9TrlZ7X7gxvcOJ\njQIDAQAB\n-----END PUBLIC KEY-----\n"
eveli.jwt.gamut-issuer: "https://portal.digiexpress.io/gateway/issuer"



# Comms email - io.digiexpress.eveli.client.config.EveliPropsEmail
eveli.email.enabled: false
eveli.email.host-name: 
eveli.email.host-port: 
eveli.email.sender-email: 
eveli.email.sender-name: 
eveli.email.sender-password: 
eveli.email.allowed-recipients: 
eveli.email.enabled-domains:

# Comms sms WSL - io.digiexpress.notification.client.SuomiFiWSLProperties
eveli.suomifi.wsl.enabled: false
eveli.suomifi.wsl.id: 
eveli.suomifi.wsl.service-id: 
eveli.suomifi.wsl.message-version: 
eveli.suomifi.wsl.message-cert-c-name: 
eveli.suomifi.wsl.organization-name: 

# Comms sms REST - io.digiexpress.notification.client.SuomiFiRestProperties
eveli.suomifi.rest.enabled: false  
eveli.suomifi.rest.service-id: 
eveli.suomifi.rest.endpoint: 
eveli.suomifi.rest.password: 
eveli.suomifi.rest.markdown-enabled: true
 
eveli.org.service-url:

eveli.envir.cache-expirations.short-deployment: PT30M
eveli.envir.cache-expirations.long-runtime: PT60M
 