on:
  push:
    paths:
      - 'ts_setup/tasks-ui/**'

    branches:
      - dev
  workflow_call: # Enables manual triggering
permissions:
  contents: read
  id-token: write
    
name: Build Tasks UI
jobs:
    build:
      runs-on: ubuntu-latest  # windows-latest || macos-latest
      defaults:
        run:
          working-directory: ts_setup/tasks-ui
      env:
        NODE_ENV: test
        CI: true
      name: Build Tasks UI
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: 20
            cache: 'yarn'
            cache-dependency-path: ts_setup/tasks-ui/yarn.lock
        - name: Install dependencies 📦
          run: yarn install --frozen-lockfile
        - name: Test
          run: yarn test --passWithNoTests
        - name: Build 
          run: yarn build
          env:
            CI: false # 
            PUBLIC_URL: //${{ secrets.CDN_S3_BUCKET }}/digiexpress-io/tasks-ui/${{ github.ref_name }}
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v3
          with:
            role-to-assume: ${{ secrets.ASSUME_ROLE }}
            aws-region: ${{ secrets.AWS_REGION }}
        - name: Publish assets
          uses: osiegmar/s3-publisher-action@v1
          with:
            bucket: ${{ secrets.CDN_S3_BUCKET }}
            dir: ts_setup/tasks-ui/build
            prefix: digiexpress-io/tasks-ui/${{ github.ref_name }}/
            delete-orphaned: true
    