on:
  push:
    paths:
      - 'ts_setup/tasks-ui/**'

    branches:
      - dev
  workflow_call: # Enables manual triggering
permissions:
  contents: read
  id-token: write
    
name: Build Tasks UI
jobs:
    build:
      runs-on: ubuntu-latest  # windows-latest || macos-latest
      defaults:
        run:
          working-directory: ts_setup/tasks-ui
      env:
        NODE_ENV: test
        CI: true
      name: Build Tasks UI
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: 20
            cache: 'pnpm'
            cache-dependency-path: ts_setup/tasks-ui/pnpm-lock.yaml
        - uses: pnpm/action-setup@v2
          name: install pnpm
          with:
            version: 8
        - name: Install dependencies 📦
          run: pnpm install --frozen-lockfile
        - name: Test
          run: pnpm test --passWithNoTests
        - name: Build 
          run: pnpm build
          env:
            CI: false # 
            PUBLIC_URL: //${{ secrets.CDN_S3_BUCKET }}/digiexpress-io/tasks-ui/${{ github.ref_name }}
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v3
          with:
            role-to-assume: ${{ secrets.ASSUME_ROLE }}
            aws-region: ${{ secrets.AWS_REGION }}
        - name: Publish assets
          run: |
            aws s3 sync --exclude '*.html' --delete --cache-control public,max-age=3600 --acl public-read build/ s3://${{ secrets.CDN_S3_BUCKET }}/digiexpress-io/tasks-ui/${{ github.ref_name }}/
            aws s3 sync --include '*.html' --cache-control no-cache --acl public-read build/ s3://${{ secrets.CDN_S3_BUCKET }}/digiexpress-io/tasks-ui/${{ github.ref_name }}/
