on:
  workflow_dispatch: # Enables manual triggering

  pull_request:
    paths:
      - 'mvn_setup/**'
    branches:
      - dev

  push:
    paths:
      - 'mvn_setup/**'
    branches:
      - dev
permissions:
  id-token: write
name: Build backend snapshot (prod)
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    - id: build
      name: Maven build
      run: |
        cd ./mvn_setup
        ./mvnw -B -Drevision=$(head -1 ./build-parent/next-release.version | tr -d '\n')-SNAPSHOT -DaltDeploymentRepository=local::file:./target/staging \
          clean deploy

    - uses: actions/upload-artifact@v4
      id: snapshot-artifacts
      name: Upload artifacts
      with:
        name: snapshot-artifacts
        path: mvn_setup/target/staging/
        retention-days: 7

    - id: dispatch
      name: Trigger test environment update
      run: |
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ secrets.DIGIEXPRESS_DISPATCH_TARGET }}/dispatches \
          ${{ secrets.DIGIEXPRESS_DISPATCH_PAT }} \
          -F "event_type=snapshot-build" \
          -F "client_payload[run_id]=${{ github.run_id }}" \
          -F "client_payload[from_event_name]=${{ github.event_name }}" \
          -F "client_payload[from_event_name]=${{ github.ref_type }}" \
          -F "client_payload[from_event_name]=${{ github.ref_name }}" \
          -F "client_payload[artifact-id]=${{ steps.snapshot-artifacts.outputs.artifact-id }}" \
          -F "client_payload[artifact-url]=${{ steps.snapshot-artifacts.outputs.artifact-url }}" \
          -F "client_payload[artifact-digest]=${{ steps.snapshot-artifacts.outputs.artifact-digest }}"

