on:
  workflow_dispatch: # Enables manual triggering

  pull_request:
    paths:
      - 'mvn_setup/**'
    branches:
      - dev

  push:
    paths:
      - 'mvn_setup/**'
    branches:
      - dev
permissions:
  id-token: write
name: Build backend snapshot (prod)
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    - id: build
      name: Maven build
      run: |
        cd ./mvn_setup
        ./mvnw -B clean install
