on:
  push:
    branches:
      - dev

name: snapshot build
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Maven build
      run: |
        cd ./mvn_setup
        ./mvnw -B clean build
      env:
        CI: true
        QUARKUS_CONTAINER_IMAGE: 
        QUARKUS_CONTAINER_IMAGE_BUILD: "true"
        QUARKUS_CONTAINER_IMAGE_PUSH: "true"
        QUARKUS_CONTAINER_IMAGE_GROUP: ${{ github.repository_owner }}
        QUARKUS_CONTAINER_IMAGE_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
        QUARKUS_CONTAINER_IMAGE_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        QUARKUS_CONTAINER_IMAGE_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
        QUARKUS_CONTAINER_IMAGE_ADDITIONAL_TAGS: "${{ github.ref_name }},latest"
        
