on:
  push:
    paths:
      - 'mvn_setup/prod-version/**'
    branches:
      - dev
  workflow_call: # Enables manual triggering

permissions:
  contents: write
  id-token: write

name: Release digiexpress-parent
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mvn_setup/prod-version
    
    name: release digiexpress-parent branch dev
    steps:
    - uses: actions/checkout@v4


    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        gpg-private-key: ${{ secrets.GPG_KEY }}
        gpg-passphrase: GPG_KEY_SEC
        server-id: s01.oss.sonatype.org
        server-username: OSSRH_USER
        server-password: OSSRH_PASS
    
    - name: maven digiexpress-parent release
      run: ./build-parent/digiexp-parent-prod-release.sh
      env:
        BOT_EMAIL: jocelyn.mutso@resys.io 
        BOT_NAME: jocelyn.mutso
        GPG_KEY_SEC: ${{ secrets.GPG_KEY_SEC }}
        