on:
  push:
    paths:
      - 'ts_setup/gamut/**'

    branches:
      - dev
  workflow_call: # Enables manual triggering
permissions:
  contents: write
  id-token: write
    
name: Release Gamut
jobs:
    build:
      runs-on: ubuntu-latest  # windows-latest || macos-latest
      defaults:
        run:
          working-directory: ts_setup/gamut
      env:
        NODE_ENV: test
        CI: true
        
      name: Release Gamut into NPMJS 
      steps:
        - uses: actions/checkout@v4

        - uses: pnpm/action-setup@v2
          name: install pnpm
          with:
            version: 8

        - uses: actions/setup-node@v4
          with:
            node-version: 20
            cache: 'pnpm'
            cache-dependency-path: ts_setup/gamut/pnpm-lock.yaml
            registry-url: 'https://registry.npmjs.org'

        - name: Install dependencies 📦
          run: pnpm install -r --prefer-frozen-lockfile
#        - name: Test
#          run: pnpm test -r

        - name: Run 'gamut-release.sh'  
          run: ./build-scripts/gamut-release.sh
          env:
            CI: false # 
            BOT_EMAIL: jocelyn.mutso@resys.io 
            BOT_NAME: jocelyn.mutso
            NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}