on:
  push:
    branches:
      - main

name: react-burger-release
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:

    - name: Setup variables from commit
      id: commit_variables
      run: |
        echo ::set-output name=SOURCE_COMMIT::${GITHUB_SHA}
        echo ::set-output name=SOURCE_REF::${GITHUB_REF}


    - name: Setup ENV variables
      run: |
        echo $GITHUB_REF
        echo $SOURCE_COMMIT
      env:
        GITHUB_REF: ${{ steps.commit_variables.outputs.GITHUB_REF }}
        SOURCE_COMMIT: ${{ steps.commit_variables.outputs.SOURCE_COMMIT }}

    - name: Checkout code
      uses: actions/checkout@main
      with:
        ref: main

    - name: Setup node and yarn
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'yarn'
        registry-url: 'https://registry.npmjs.org'

    - name: Run release script
      run: ./.build-scripts/react-burger-main-branch-release.sh
      env:
        CI: false
        NODE_AUTH_TOKEN: ${{ secrets.BOT_TOKEN }}
        GIT_EMAIL: olev.mutso@gmail.com 
        GIT_USER: olev.mutso
        
