on:
  push:
    branches:
      - main

name: Create release from a tag
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main
      with:
        ref: main

    - uses: joschi/setup-jdk@v2
      with:
        java-version: '11'
    
    - name: Maven release
      run: ./zoe-build-parent/release.sh
      env:
        CI: false
        BOT_EMAIL: jocelyn.mutso@gmail.com
        BOT_NAME: jocelyn.mutso
        GITHUB_SHA: ${GITHUB_SHA}
        GITHUB_REF: ${GITHUB_REF}
        GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
        GPG_KEY: ${{ secrets.GPG_KEY }}
        GPG_KEY_SEC:  ${{ secrets.GPG_SEC }}
        OSSRH_PASS: ${{ secrets.OSSRH_PASS }}
        OSSRH_USER: ${{ secrets.OSSRH_USER }}
        
        
