on:
  push:
    branches:
      - main

name: Create thena release from a tag
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@main
      with:
        ref: main

    - uses: joschi/setup-jdk@v2
      with:
        java-version: '11'
    
    - name: Maven release
      run: ./thena-build-parent/release.sh
      env:
        CI: false
        BOT_NAME: olev.mutso
        BOT_EMAIL: olev.mutso@resys.io
        GITHUB_SHA: ${GITHUB_SHA}
        GITHUB_REF: ${GITHUB_REF}
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        GPG_KEY_ID: ${{ secrets.HDES_GPG_KEY_ID }}
        GPG_KEY: ${{ secrets.HDES_GPG_KEY }}
        GPG_KEY_SEC:  ${{ secrets.HDES_GPG_SEC }}
        OSSRH_PASS: ${{ secrets.OSSRH_PASS }}
        OSSRH_USER: ${{ secrets.OSSRH_USER }}
        
        
