const en = {

  //----------------START NEW-------------------------
  'explorer.title': 'DigiExpress Task Management',
  'explorer.logout': 'Log out',
  'explorer.feedback': 'Send feedback',

  // ---------------END NEW --------------------------


  'locale.fi': 'Suomi',
  'locale.sv': 'Svenska',
  'locale.en': 'English',

  'app.logout': 'Log out',
  'app.login': 'Log in',
  'app.feedback': 'Feedback',

  'menu.dashboard': 'Dashboard',
  'menu.profile': 'Profile',
  'menu.tasks': 'Tasks',
  'menu.evaluations': 'Questionnaires',
  'menu.forms': 'Dialob',
  'menu.users': 'Users',
  'menu.help': 'Help',
  'menu.flow': 'Wrench',
  'menu.processes': 'Monitoring',
  'menu.reports': 'Reports',
  'menu.workflows': 'Workflows',
  'menu.workflowTags': 'Workflow tags',
  'menu.publications': 'Publications',
  'menu.services': 'Services',
  'menu.content': 'Stencil',
  'menu.calendar': 'Calendar',

  'front.intro.title': 'Welcome!',

  'profile.title': 'User Profile',
  'profile.user.name': 'Name:',
  'profile.user.email': 'e-mail:',
  'profile.user.role': 'Role:',
  'profile.user.phone': 'Phone:',
  'profile.app.version': "Application version:",

  'button.cancel' : 'Cancel',
  'button.accept' : 'Accept',
  'button.edit' : 'Edit',
  'button.close' : 'Close',
  'button.reject' : 'Reject',
  'button.send': 'Send',
  'button.dismiss': 'Dismiss',
  'button.editRoles': 'Edit',
  'button.select': 'Select',

  'error.minTextLength': 'Value should be at least {minLength} characters long',
  'error.maxTextLength': 'Value should be no more than {max} characters long',
  'error.valueRequired': 'Value required',
  'error.title': 'Error!',
  'error.dialob.session': 'Questionnaire cannot be opened at this moment, please try again later',
  'error.errorLoadingData': 'Error during data loading',
  'error.unauthorized.title': 'Missing access role',
  'error.unauthorized.text': 'Contact your system administrator to check your role',
  'error.unauthorizedAccess': 'Missing access role',
  'error.dataAccess': 'Error during data loading',
  'error.statusOpenError': 'Required when status is open',
  'error.workflowCreation': 'Error on workflow creation, check worflow name for duplicates',

  'table.body.addTooltip': 'Add',
  'table.body.editTooltip': 'Edit',
  'table.body.editRow.deleteMessage': 'Are you sure you want to delete this?',

  'workflowTable.title': 'Workflows',
  'workflowTableHeader.name': 'Name',
  'workflowTableHeader.formName': 'Form',
  'workflowTableHeader.flowName': 'Flow',
  'workflowTableHeader.updated': 'Updated',
  'workflowTable.addButton': 'New workflow',
  'workflowTable.editButton': 'Edit workflow',

  'workflow.dialogTitle': 'Workflow',
  'workflow.name': 'Name',
  'workflow.form.formName': 'Form name',
  'workflow.form.formTag': 'Form tag',
  'workflow.flowName': 'Flow name',

  'processTable.title': 'Processes',
  'processTableHeader.workflow': 'Workflow name',
  'processTableHeader.user': 'User id',
  'processTableHeader.status': 'Status',
  'processTableHeader.created': 'Created',
  'processTableHeader.questionnaireId': 'Questionnaire',

  'process.status.ANSWERED': 'Answered',
  'process.status.CREATED': 'Created',
  'process.status.ANSWERING': 'Answering',
  'process.status.IN_PROGRESS': 'In progress',
  'process.status.WAITING': 'Waiting',
  'process.status.COMPLETED': 'Completed',
  'process.status.REJECTED': 'Rejected',

  'comment.button': 'Send comment',
  'comment.title': 'Send comment',
  'comment.form.email': 'E-mail',
  'comment.form.feedbackType': 'Type',
  'comment.form.body': 'Message',
  'comment.type.general': 'General',
  'comment.type.propose': 'Propose',
  'comment.type.contact': 'Contact me',
  'comment.submitted.success': 'Thank you for your feedback!',
  'comment.submitted.failure': 'Comment submission failed!',

  'spoTasksTableHeader.taskName': 'Task name',
  'spoTasksTableHeader.category': 'Type',
  'spoTasksTableHeader.status': 'Status',
  'spoTasksTableHeader.priority': 'Priority',
  'spoTasksTableHeader.dueDate': 'Due date',
  'spoTasksTableHeader.assigned': 'Assigned to',
  'spoTasksTableHeader.assignedUser': 'User',
  'spoTasksTableHeader.created': 'Created',
  'spoTasksTableHeader.clientName': 'Client',

  'taskDialog.clientIdentificator': 'Client name',
  'taskDialog.assignedUserEmail': 'User\'s email',
  'task.editRoles': 'Task groups',

  // for task labels
  'Questionnaire': 'Questionnaire',
  'Manual': 'Manual',
  'Protected': 'Protected',
  'Normal': 'Normal',
  'Represented': 'Represented',
  "CustomerCreated": "Customer created",
  "Internal": "Internal",

  'task.role.assignedAllUsers': 'All users',

  'confirm.close.title': 'Confirmation required',
  'confirm.unsavedChanges': 'Unsaved changes will be lost, do you want to continue?',

  'task.statistics.statusCount': 'By status',
  'task.statistics.priorityCount': 'By priority',
  'task.statistics.daily': 'Daily',
  'task.statistics.overdue': 'Overdue',


  'feedback.button': 'Send feedback',
  'feedback.thanks': 'Thank you for your feedback!',
  'feedback.title': 'Send feedback',
  'feedback.description': 'Description',
  'feedback.name': 'Your name',
  'feedback.sendScreenshot': 'Send screenshot',
  'feedback.close': 'Close',
  'feedback.send': 'Send',

  'help.title': 'Help',
  
  'attachmentView.title': 'Attachments',
  'attachmentTableHeader.size': 'Size',
  'attachmentTableHeader.updated': 'Updated',
  'attachmentTableHeader.created': 'Created',
  'attachmentTableHeader.name': 'Name',
  'attachmentButton.addAttachment': 'Add file',
  'attachmentButton.downloadAttachment': 'Download file',
  'attachment.uploadOk': 'File {fileName} uploaded',
  'attachment.uploadFailed': 'File {fileName} upload failed!',

  'workflowReleaseTable.title': 'Workflow release tags',
  'workflowReleaseTableHeader.name': 'Name',
  'workflowReleaseTableHeader.description': 'Description',
  'workflowReleaseTableHeader.updatedBy': 'Updater',
  'workflowReleaseTableHeader.updated': 'Updated',
  'workflowReleaseTable.addButton': 'Add',
  'workflowReleaseTable.viewButton': 'View',
  'workflowReleaseTable.exportButton': 'Export',
  
  'workflowRelease.dialogTitle': 'Workflow release',
  'workflowRelease.name': 'Release name',
  'workflowRelease.description': 'Description',
  'workflowRelease.releaseCreationFailed': 'Workflow tag creation failed, cause: {cause}',

  'publicationsTable.title': 'Publications',
  'publicationsTableHeader.name': 'Release name',
  'publicationsTableHeader.description': 'Description',
  'publicationsTableHeader.createdBy': 'User',
  'publicationsTableHeader.created': 'Created',
  'publicationsTableHeader.contentTag': 'Content tag',
  'publicationsTableHeader.workflowTag': 'Workflow tag',
  'publicationsTableHeader.wrenchTag': 'Wrench tag',
  'publicationsTable.addButton': 'Add',
  'publicationsTable.viewButton': 'View',
  'publicationsTable.exportButton': 'Export',

  'publications.dialogTitle': 'Create new Publication',
  'publications.name': 'Release name',
  'publications.description': 'Description',
  'publications.workflowTag': 'Workflow tag',
  'publications.wrenchTag': 'Wrench tag',
  'publications.contentTag': 'Content tag',
  'publications.createNewTag': 'Create new tag "{tag}"',
  'publications.downloadFailed': 'Release download failed, cause: {cause}',
  'publications.tagCreationFailed': 'Release creation failed, cause: {cause}',

  'dialobForms.dialog.heading': 'Forms',
  'dialobForms.table.tooltip.add': 'Add',
  'dialobForms.table.label': 'ID',
  'dialobForms.table.created': 'Created',
  'dialobForms.table.lastSaved': 'Updated',
  'dialobForms.table.tooltip.edit':'Edit',
  'dialobForms.dialog.emptyTitle':'-',
  'dialobForms.table.tooltip.copy':'Copy',
  'dialobForms.table.tooltip.delete':'Remove',
  'dialobForm.saveFailed': 'Saving failed',
  'dialobForm.downloadFailed':'Saving failed',
  'dialobForm.deleteFailed': 'Remove failed',
  'dialobForm.heading.copyDialog':'Copy',
  'dialobForm.heading.addDialog':'Add',
  'dialobForm.dialog.formName':'ID',
  'dialobForm.dialog.formLabel':'Name',
  'dialobForm.error.invalidFormName': 'Incorrect ID',
  'dialobForm.dialog.deleteQuestion': 'Do you want to remove form "{formName}"?',
  'dialobForm.heading.deleteDialog':'Remove form',
};

export default en;
