const fi = {

  //----------------START NEW-------------------------
  'explorer.title': 'DigiExpress Task Management',
  'explorer.logout': 'Kirjaudu ulos',
  'explorer.feedback': 'Lähetä palautetta',

  // ---------------END NEW --------------------------


  'locale.fi': 'Suomi',
  'locale.sv': 'Ruotsi',
  'locale.en': 'Englanti',

  'app.logout': 'Kirjaudu ulos',
  'app.login': 'Kirjaudu sisään',
  'app.feedback': 'Palaute',

  'menu.dashboard': 'Kojelauta',
  'menu.profile': 'Käyttäjän profiili',
  'menu.tasks': 'Tehtävä',
  'menu.evaluations': 'Kyselyt',
  'menu.forms': 'Dialob',
  'menu.users': 'Käyttäjät',
  'menu.help': 'Ohjeet',
  'menu.flow': 'Wrench',
  'menu.processes': 'Monitorointi',
  'menu.reports': 'Raportointi',
  'menu.workflows': 'Konfigurointi',
  'menu.workflowReleases': 'Versiointi',
  'menu.releases': 'Julkaisut',
  'menu.services': 'Palvelut',
  'menu.content': 'Stencil',
  'menu.calendar': 'Kalenteri',

  'front.intro.title': 'Tervetuloa!',
  
  'profile.title': 'Käyttäjän profiili',
  'profile.user.name': 'Nimi:',
  'profile.user.email': 'Sähköposti:',
  'profile.user.role': 'Rooli:',
  'profile.user.phone': 'Puhelin:',
  'profile.app.version': "Sovellusversio:",

  'button.cancel' : 'Peruuta',
  'button.accept' : 'Hyväksy',
  'button.edit' : 'Avaa',
  'button.close' : 'Sulje',
  'button.reject' : 'Hylkää',
  'button.send': 'Lähetä',
  'button.dismiss': 'Sulje',
  'button.editRoles': 'Muokkaa',

  'error.minTextLength': 'Annetun arvon pitää olla vähintään {minLength} merkkiä',
  'error.maxTextLength': 'Annetun arvon tulee olla enintään {max} merkkiä pitkä',
  'error.valueRequired': 'Vaaditaan',
  'error.title': 'Virhe!',
  'error.dialob.session': 'Lomaketta ei voida aukaista juuri nyt. Yritä uudelleen myöhemmin',
  'error.errorLoadingData': 'Error during data loading',
  'error.unauthorized.title': 'Käyttöoikeutesi ovat puutteelliset',
  'error.unauthorized.text': 'Ota yhteyttä IT-palveluihin lähettämällä tukipyyntö Tiketin kautta -> Jätä tukipyyntö -> Kirjautumisongelma.',
  'error.unauthorizedAccess': 'Käyttöoikeutesi ovat puutteelliset',
  'error.dataAccess': 'Virhe toiminnassa',
  'error.statusOpenError': 'Required when status is open',
  'error.workflowCreation': 'Virhe konfiguroinnissa, tarkista nimen yksilöllisyys',

  'table.body.addTooltip': 'Lisää',
  'table.body.editTooltip': 'Avaa',
  'table.body.editRow.deleteMessage': 'Halutko varmasti poistaa tämän?',
  
  'workflowTable.title': 'Kokoonpano',
  'workflowTableHeader.name': 'Nimi',
  'workflowTableHeader.formName': 'Lomake',
  'workflowTableHeader.flowName': 'Prosessi',
  'workflowTableHeader.updated': 'Päivitetty',
  'workflowTable.addButton': 'Lisää uusi',
  'workflowTable.editButton': 'Muokka',

  'workflow.dialogTitle': 'Kokoonpano',
  'workflow.name': 'Nimi',
  'workflow.form.formName': 'Lomakkeen nimi',
  'workflow.form.formTag': 'Lomakkeen versio',
  'workflow.flowName': 'Prosessi',

  'processTable.title': 'Työt',
  'processTableHeader.workflow': 'Tyyppi',
  'processTableHeader.user': 'Käyttäjä',
  'processTableHeader.status': 'Tila',
  'processTableHeader.created': 'Luotu',
  'processTableHeader.questionnaireId': 'Lomake',

  'process.status.ANSWERED': 'Lähetetty',
  'process.status.CREATED': 'Luotu',
  'process.status.ANSWERING': 'Keskeneräinen',
  'process.status.IN_PROGRESS': 'Käsittelyssä',
  'process.status.WAITING': 'Odottaa',
  'process.status.COMPLETED': 'Valmis',
  'process.status.REJECTED': 'Hylätty',

  'comment.button': 'Anna palautetta',
  'comment.title': 'Anna palautetta',
  'comment.form.email': 'Sähköposti',
  'comment.form.feedbackType': 'Tyyppi',
  'comment.form.body': 'Viesti',
  'comment.type.general': 'Anna palautetta',
  'comment.type.propose': 'Ehdota uutta palvelua',
  'comment.type.contact': 'Ota yhteyttä',
  'comment.submitted.success': 'Kiitos palautteesta!',
  'comment.submitted.failure': 'Lähetys epäonnistui',

  'spoTasksTableHeader.taskName': 'Nimi',
  'spoTasksTableHeader.category': 'Tyyppi',
  'spoTasksTableHeader.status': 'Tila',
  'spoTasksTableHeader.priority': 'Prioriteetti',
  'spoTasksTableHeader.dueDate': 'Eräpäivä',
  'spoTasksTableHeader.assigned': 'Käsittelijä',
  'spoTasksTableHeader.assignedUser': 'Käyttäjä',
  'spoTasksTableHeader.created': 'Luotu',
  'spoTasksTableHeader.clientName': 'Asiakas',

  'taskDialog.clientIdentificator': 'Asiakas',
  'taskDialog.assignedUserEmail': 'Käyttäjän sähköposti',
  'task.editRoles': 'Tehtäväryhmät',

  // for task labels
  'Questionnaire': 'Lomake',
  'Manual': 'Manuaalinen',
  'Protected': 'Suojattu',
  'Normal': 'Normaali',
  'Represented': 'Valtuutetu',
  "CustomerCreated": "Asiakas luotu",
  "Internal": "Sisäinen",

  'task.role.assignedAllUsers': 'Kaikki käyttäjät',
  
  'confirm.close.title': 'Vahvistus vaaditaan',
  'confirm.unsavedChanges': 'Tallentamattomat muutokset menetetään. Haluatko jatkaa?',

  'task.statistics.statusCount': 'Tilan mukaan',
  'task.statistics.priorityCount': 'Prioriteetin mukaan',
  'task.statistics.daily': 'Päivittäin',
  'task.statistics.overdue': 'Myöhässä',

  'feedback.button': 'Lähetä palautetta',
  'feedback.thanks': 'Kiitos palautteestasi!',
  'feedback.title': 'Lähetä palautetta',
  'feedback.description': 'Kuvaus',
  'feedback.name': 'Nimesi',
  'feedback.sendScreenshot': 'Lähetä ruutukaappaus',
  'feedback.close': 'Peru',
  'feedback.send': 'Lähetä',

  'help.title': 'Ohjeet',

  'attachmentView.title': 'Liitetiedostoja',
  'attachmentTableHeader.size': 'Koko',
  'attachmentTableHeader.updated': 'Päivitetty',
  'attachmentTableHeader.created': 'Luotu',
  'attachmentTableHeader.name': 'Nimi',
  'attachmentButton.addAttachment': 'Lisää tiedosto',
  'attachmentButton.downloadAttachment': 'Lataa tiedosto',
  'attachment.uploadOk': 'Tiedosto {fileName} ladattu',
  'attachment.uploadFailed': 'tiedoston {fileName} lataaminen epäonnistui!',

  'workflowReleaseTable.title': 'Kokoonpano',
  'workflowReleaseTableHeader.name': 'Nimi',
  'workflowReleaseTableHeader.description': 'Kuvaus',
  'workflowReleaseTableHeader.updatedBy': 'Päivittäjä',
  'workflowReleaseTableHeader.updated': 'Päivitetty',
  'workflowReleaseTable.addButton': 'Lisää uusi',
  'workflowReleaseTable.viewButton': 'Katso',
  'workflowReleaseTable.exportButton': 'Lataa',

  'workflowRelease.dialogTitle': 'Palveluversio',
  'workflowRelease.name': 'Nimi',
  'workflowRelease.description': 'Kuvaus',
  'workflowRelease.releaseCreationFailed': 'Palveluversion luominen epäonnistui, syy: {cause}',

  'assetReleaseTable.title': 'Julkaisut',
  'assetReleaseTableHeader.name': 'Tunniste',
  'assetReleaseTableHeader.description': 'Kuvaus',
  'assetReleaseTableHeader.updatedBy': 'Päivittäjä',
  'assetReleaseTableHeader.updated': 'Päivitetty',
  'assetReleaseTableHeader.contentTag': 'Sisältöversio',
  'assetReleaseTableHeader.workflowTag': 'Palveluversio',
  'assetReleaseTableHeader.wrenchTag': 'Prosessiversio',
  'assetReleaseTable.addButton': 'Lisää uusi',
  'assetReleaseTable.viewButton': 'Katso',
  'assetReleaseTable.exportButton': 'Lataa',

  'assetRelease.dialogTitle': 'Julkaisu',
  'assetRelease.name': 'Tunniste',
  'assetRelease.description': 'Kuvaus',
  'assetRelease.workflowTag': 'Palveluversio',
  'assetRelease.wrenchTag': 'Prosessiversio',
  'assetRelease.contentTag': 'Sisältöversio',
  'assetRelease.createNewTag': 'Luo uusi versio "{tag}"',
  'assetRelease.downloadFailed': 'Julkaisun lataus epäonnistui, syy: {cause}',
  'assetRelease.tagCreationFailed': 'Julkaisun luominen epäonnistui, syy: {cause}',

  'dialobForms.dialog.heading': 'Lomakkeet',
  'dialobForms.table.tooltip.add': 'Lisää',
  'dialobForms.table.label': 'Nimi',
  'dialobForms.table.created': 'Luotu',
  'dialobForms.table.lastSaved': 'Päivitetty',
  'dialobForms.table.tooltip.edit':'Muokkaa',
  'dialobForms.dialog.emptyTitle':'-',
  'dialobForms.table.tooltip.copy':'Kopio',
  'dialobForms.table.tooltip.delete':'Poista',
  'dialobForm.saveFailed': 'Tallennus epäonnistui',
  'dialobForm.downloadFailed':'Tallennus epäonnistui',
  'dialobForm.deleteFailed': 'Poisto epäonnistui',
  'dialobForm.heading.copyDialog':'Kopio lomake',
  'dialobForm.heading.addDialog':'Lisää lomake',
  'dialobForm.dialog.formName':'ID',
  'dialobForm.dialog.formLabel':'Nimi',
  'dialobForm.error.invalidFormName': 'Väärä ID',
  'dialobForm.dialog.deleteQuestion': 'Haluatko poistaa lomakkeen "{formName}"?',
  'dialobForm.heading.deleteDialog':'Lomakkeen poisto',
};

export default fi;
